- modules/bvl_feedback/test/TestPlan.md
addresses https://redmine.cbrain.mcgill.ca/issues/14936.
updates test plan accordingly
> [bvl_feedback] Update test plan

- modules/data_team_helper/test/TestPlan.md
There is now mention in the test plan that only 'study' sites should appear in the sites drop-down list.
> Corrected the test plan for the Data Team Helper module.

- modules/instrument_list/php/instrument_list.class.inc
This pull request fixing the  _hasAccess() function. The variables are not initialized.
https://redmine.cbrain.mcgill.ca/issues/14730
> [20.0-release] [instrument_list] fixing the  _hasAccess() function - The variables are not initialized.

- htdocs/api/v0.0.3-dev/projects/Images.php
There is no such thing as a PCSID.
> Fix typo in API endpoint

- modules/user_accounts/php/edit_user.class.inc
- modules/user_accounts/test/TestPlan.md
This is a branch update PR
**This PR should not be squashed**
> [RELEASE] push 19.1.2 changes to 20.0 branch

- PULL_REQUEST_TEMPLATE.md
This Pull Request aims to improve our workflow by encouraging developers to add more information to their new pull requests.
Importantly, it encourages developers to provide testing instructions. The hope is that this well prevent PRs becoming cursed when no one knows how to help the author.
Most importantly, this PR template includes an element of public shame if people fail to follow it.
This is inspired by the presentation by @ridz1208.
> [Core] New Pull Request template

- PULL_REQUEST_TEMPLATE.md
I should've added a space when creating the PR template. Right now when people create PRs the checkboxes won't render.
> [PR Template] Add space so markdown checkboxes actually render

- modules/document_repository/ajax/documentEditUpload.php
- modules/document_repository/php/document_repository.class.inc
- modules/document_repository/templates/menu_document_repository.tpl
This pull request touches up the doc repo to enhance its readability, error reporting, and performance.
I have self-reviewed to provide feedback on specific points. 
* Everything should work the same as before. Try basic doc repo functions and make sure nothing is broken.
> [Doc Repo] Enhancements to readability and logging for edit/upload ajax file

- modules/statistics/php/stats_demographic.class.inc
Inside the Demographic of the statistics module, undefined index errors were populated and I used isset to catch them.
https://redmine.cbrain.mcgill.ca/issues/15251
> [statistics] Fixed undefined index errors with Demographic

- modules/media/jsx/mediaIndex.js
- php/libraries/Utility.class.inc
The media module was not working on my local setup. The problem was a non well formed numeric value encountered in Utility.class.inc on line 1074. Simple casting will fix the issue.
Also fixes imaging_uploader module.
https://redmine.cbrain.mcgill.ca/issues/15257
> [media][imaging_uploader] Fixed a non well formed numeric value encountered in Utility.class.inc

- modules/create_timepoint/php/create_timepoint.class.inc
- php/libraries/LorisForm.class.inc
Fixes undefined index warnings in create_timepoint module and when user creates a timepoint.
https://redmine.cbrain.mcgill.ca/issues/15260
> [create_timepoint]  Fixed Undefined index warnings

- modules/create_timepoint/README.md
Just correcting some small things as I was reading the Create Timepoint README
- Read the README
> Correcting some small mistakes in Create Timepoint README

- php/libraries/Utility.class.inc
Fixing the incorrectly parsed Data Coordinating Center site in `getAssociativeSiteList` in `Utilities.class.inc` for the past 6-7years
> [Core] Fix getAssociativeSiteList in Utility.class.inc

- Dockerfile
- Dockerfile.MySQL
- Dockerfile.test.php7
update PHP Mysql and Ubuntu version
Can't run integration test properly.
run integration test
> [Docker] update PHP,Mysql and Ubuntu version

- tools/score_instrument.php
Cleaning up some junk in score_instrument.php
> [Tools] Minor cleanup for score_instrument.php

- php/libraries/NDB_Client.class.inc
Noticed someone likes tabs over spaces
> [Meta] tabs r ew in NDB_Client.class.inc

- SQL/New_patches/2018-08-27_add_name_of_mri_config_file_to_config_module.sql
Two dashes makes MySQL happy and three makes it sad.
* Try running the old patch. MySQL should complain
* Try running this path. MySQL should giggle
> [SQL] Fix triple dash that causes SQL errors

- php/libraries/NDB_Page.class.inc
addBasicDate should use `$this->dateOptions` by default if applicable
> [NDB_Page] addBasicDate() use dateOptions by default

- modules/issue_tracker/README.md
Improving README formatting and grammar
> [Issue Tracker] Improving README formatting and grammar

- php/libraries/Site.class.inc
See #3878 for a more detailed explanation.
> [Core: Site] Add type declarations to function signatures

- modules/new_profile/php/new_profile.class.inc
- modules/next_stage/php/next_stage.class.inc
Checks are addred to ensure that variables are defined well before being processed.
This PR addresses bugs that are causing problems in #4047 and #4049 and must be merged before they can progress.
> [Next Stage, New Profile] Fix misc. errors and warnings that are blocking other PRs

- php/libraries/TimePoint.class.inc
See #3878 for a better description.
> [Core: TimePoint] Add type declarations to function signatures

- php/libraries/NDB_Client.class.inc
> [Core: Client] Add type declarations to function signatures

- php/libraries/Settings.class.inc
> [Core: Settings] Add type declarations to function signatures

- php/libraries/Utility.class.inc
#4118 removed the only code using this function, so it's time to get rid of it.
> [Core: Utility] Remove arrayMergeRecursiveOverwriting()

- modules/new_profile/php/new_profile.class.inc
- php/libraries/Candidate.class.inc
- test/unittests/CandidateTest.php
See #3878 for a more detailed description.
> [Core: Candidate]  Add type declarations to function signatures

- htdocs/fontawesome
- modules/instrument_list/php/instrument_list_controlpanel.class.inc
- modules/instrument_list/templates/instrument_list_controlpanel.tpl
- package.json
- smarty/templates/main.tpl
Motivated by UI issues with the instrument panel from https://github.com/aces/Loris/pull/4007, I have installed Font Awesome as a dependency on LORIS and changed all icons on the instrument panel to fa icons.
Before & after:
> [CSS/Instrument_list] Install FontAwesome!

- src/Http/Error.php
- src/Middleware/AuthMiddleware.php
Makes the 403 page pretty. See linked issue.
Resolves #3908
>  [Core: Middleware] Restore 403 page to its former beauty 

- php/libraries/BVL_Feedback_Panel.class.inc
> [Core: BVL_Feedback_Panel] Add type declarations to function signatures

- modules/mri_violations/js/.gitignore
This compiled file should be ignored and it causes issues when changing branches after compiling.
> [MRI Violations] Add mri_protocol_violations_columnFormatter.js to gitignore

- php/libraries/NDB_BVL_InstrumentStatus.class.inc
- php/libraries/NDB_BVL_InstrumentStatus_ControlPanel.class.inc
> [Core: InstrumentStatus] Add type declarations to function signatures

- php/libraries/NDB_BVL_Instrument.class.inc
- php/libraries/NDB_BVL_InstrumentStatus_ControlPanel.class.inc
- php/libraries/TimePoint.class.inc
- test/phpunit.xml
- test/test_instrument/test_instrumentTest.php
Fixing PHP warning and notice.
make major branch to pass Travis.
> Fix error on Major for php 7.3

- php/libraries/NDB_Caller.class.inc
> [Core: NDB_Caller] Add type declarations to function signatures

- php/libraries/Notify.class.inc
See https://github.com/aces/Loris/issues/4072
> [Core: Notify] Add type declarations to function signatures

- SQL/Archive/20.1/Cleanup/2018-08-20_remove_duplicate_incoming_path_from_config_tables.sql
```
ERROR 1064 (42000): You have an error in your SQL syntax; 
check the manual that corresponds to your MySQL server version 
for the right syntax to use near '-
```
replacing `---` by `--`
> [SQL] Fix syntax error

- php/libraries/BVL_Feedback_Panel.class.inc
change int to string
https://redmine.cbrain.mcgill.ca/issues/15783
to test it --
loading any instrument
> [BVL_feedback] fix a type error

- php/libraries/User.class.inc
Types are good!
Further PRs to follow if Travis fails.
* #4033
> [Core: User] Add type declarations to function signatures

- htdocs/survey.php
- modules/instrument_list/php/instrument_list.class.inc
- modules/instrument_list/php/instrument_list_controlpanel.class.inc
- modules/login/php/requestaccount.class.inc
- src/Http/StringStream.php
Fixes some mismatched return type declarations and PHPDocs discovered in #4069.
> Fix some mismatched return type errors flagged by phan

- php/libraries/State.class.inc
See https://github.com/aces/Loris/issues/4072
> [Core: State] Add type declarations to function signatures

- test/Quick_Setup.md
- test/README.md
This pull request adds a quick step for Loris developers to set up the integration test environment.
> [Integration Test] How to setup integration test environment 

- htdocs/bootstrap/css/custom-css.css
- jsx/DataTable.js
- jsx/Filter.js
- jsx/FilterableDataTable.js
- jsx/Form.js
- modules/dicom_archive/jsx/dicom_archive.js
- modules/dicom_archive/test/dicom_archiveTest.php
- modules/media/test/MediaTest.php
PR as a result of discussions in UX WG to address problem of adding 'Call To Action' buttons within the menu filter as found in https://github.com/aces/Loris/pull/4167
- Creates a new FieldsetElement component
- Changes Filter component to use FieldsetElement instead of FormElement. Any implementation of FormElement component should not be changed (i.e. Media Upload Form)
- Changes look of DataTable and insert call to action buttons within the table 'header'
- added title prop to Dicom Archive to render title in card panel header
-  UI should look like screenshots above, and functionality should remain the same. Report any bugs.
> [jsx] FilterableDataTable UI Redesign

- SQL/Archive/20.1/Cleanup/2018-08-20_remove_duplicate_incoming_path_from_config_tables.sql
- modules/instrument_list/php/instrument_list.class.inc
- modules/instrument_list/php/module.class.inc
- php/libraries/Module.class.inc
- smarty/templates/500.tpl
Setting master to the latest release 20.1.2
This PR should not be squashed
> Pull back v20.1.2 into master

- SQL/Archive/20.1/Cleanup/2018-08-20_remove_duplicate_incoming_path_from_config_tables.sql
- modules/instrument_list/php/instrument_list.class.inc
- modules/instrument_list/php/module.class.inc
- php/libraries/Module.class.inc
- smarty/templates/500.tpl
pushing latest release to minor
This PR should not be squashed
> Push v20.1.2 into minor

- php/libraries/CouchDB.class.inc
> [Core: CouchDB] Add type declarations to function signatures

- php/libraries/NDB_BVL_Instrument.class.inc
- php/libraries/NDB_BVL_Instrument_LINST.class.inc
- php/libraries/NDB_BVL_Instrument_instrument_preview.class.inc
- test/test_instrument/NDB_BVL_Instrument_testtest.class.inc
See #3878 for more info.
This is the first one of these PRs done using #4064 so things might get weird.
This PR includes multiple classes that are all required to have the same function signatures.
It also fixes one instance of the Warning describe in #4037
> [Core: Instrument, Instrument_LINST, instrument_preview] Add type declarations to function signatures

- php/libraries/NDB_BVL_Instrument.class.inc
This typo is causing a fatal error on one of my sandboxes
> [Instrument] fix timepoint casing

- modules/dashboard/css/dashboard.css
> [Dashboard] Fix 'Views' Btn CSS

- php/libraries/Module.class.inc
These changes allow for the module class to properly load JS and CSS files as JS/CSS instead of text/html
> [Module Class] Add ability to load JS and CSS within Static module directory

- php/libraries/NDB_Notifier.class.inc
- php/libraries/NDB_Notifier_Abstract.class.inc
Usual typing changes. Also tried to make the code a little smaller in places.
> [Core] Add return type declarations to Notifier classes

- .travis.yml
- Dockerfile.test.php7
- Makefile
- modules/datadict/test/datadictTest.php
- modules/server_processes_manager/test/server_processes_managerTest.php
Running Docker test in Travis.
Saving time
easy to test
>  Docker test in Travis with PHP 7.2 and 7.3

- modules/api/php/module.class.inc
- php/libraries/Module.class.inc
Add return types to the Module class
> [Core] Add return types to Module class

- modules/dicom_archive/README.md
- modules/dicom_archive/php/dicom_archive.class.inc
- modules/dicom_archive/php/module.class.inc
- modules/dicom_archive/test/TestPlan.md
- modules/imaging_browser/README.md
- modules/imaging_browser/test/TestPlan.md
- modules/media/ajax/FileUpload.php
- php/libraries/NDB_BVL_Instrument.class.inc
This PR should not be squashed and merged
> PUSH FORWARD FROM BUGFIX TO 20.2.0 upcoming release

- htdocs/feedback_mri_popup.php
Fix TypeErrors that arose after merging #4264
> [Imaging] Fix type errors in feedback pop-up/FeedbackMRI

- SQL/0000-00-01-Permission.sql
- SQL/0000-00-02-Menus.sql
- SQL/New_patches/2018-11-29-Add_instrument_manager_permission.sql
- modules/instrument_manager/README.md
- modules/instrument_manager/php/instrument_manager.class.inc
- modules/instrument_manager/test/TestPlan.md
- modules/instrument_manager/test/instrument_managerTest.php
Add a permission particular to the Instrument Manager module.
> [Instrument Manager] Add specific permission to this module so that superuser isn't necessary

- .phan/config.php
- modules/server_processes_manager/php/mriuploadserverprocess.class.inc
- php/libraries/NDB_BVL_Instrument.class.inc
This updates the rules in phan to include checking that constants which
are used have been declared, and fixes a couple bugs that it found.
> [phan] Add undeclared constant verification to rules enforced by phan.

- Dockerfile.test.php7
Cleaning up the detail messages and Hash Sum mismatch.
Removing zip dependency in the Docker PHP file.
> [Travis] Clean up the detail messages and Hash Sum mismatch

- modules/help_editor/js/.gitignore
This file is leftover from module Reactification and causes problems when switching branches after running `make dev`
> [Help Editor] Remove compiled Javascript file

- modules/genomic_browser/php/genomic_file.class.inc
- modules/genomic_browser/php/genomic_file_uploader.class.inc
- modules/genomic_browser/php/view_genomic_file.class.inc
Some brief TLC to this code. There were some PHP Notices generated and I noticed certain issues pop up when trying to implement phan rules so I figured I'd tie up some loose threads here.
> [Genomics] Quick cleanup

- php/libraries/ConflictDetector.class.inc
Noticed while testing another PR.
> [Core] Fixing a Bug in ConflictDetector class

- CONTRIBUTING.md
- docs/CodingStandards.md
Just wanted to add some things to the documentation to reflect some undocumented standards we have in code review.
> [Documentation] Small update to coding standards

- php/libraries/NDB_BVL_Instrument.class.inc
Change type, it should be a string, not an array.
load any instrument.
> [Core] fix type error in NDB_BVL_Instrument.class.inc 

- php/libraries/Candidate.class.inc
This function was first written 11 years ago and was marked as deprecated 5 years ago. I think it's time to remove it.
> [Candidate] Remove deprecated function

- modules/imaging_browser/php/imaging_browser.class.inc
$list_of_projects could be undefined when useProjects isn't true
Fixes: Undefined variable: list_of_projects in modules/imaging_browser/php/imaging_browser.class.inc on line 372.
> [imaging_browser] $list_of_projects could be undefined when useProjects isn't true

- modules/examiner/test/ExaminerTest.php
- php/libraries/UserPermissions.class.inc
Add superuser into the hasAnyPermission function.
How to test.
Only give a user "superuser" permission and load the examiner module.
> [Core - UserPermissions] hasAnyPermission does not include "superuser" 

- modules/instrument_builder/jsx/react.instrument_builder.js
This PR fixes the Build & Load of instrument_builder.
> [Instrument_builder] Build & Load were broken in react.

- modules/conflict_resolver/js/.gitignore
- modules/dicom_archive/js/.gitignore
- modules/issue_tracker/js/.gitignore
- modules/media/js/.gitignore
add files to git ignore so compiled js files don't show up when trying to change branches
> add ignore files

- composer.json
- composer.lock
- htdocs/installdb.php
- htdocs/mri/jiv/get_file.php
- htdocs/router.php
- modules/data_team_helper/php/data_team_helper.class.inc
- modules/dicom_archive/php/viewdetails.class.inc
- modules/document_repository/ajax/documentEditUpload.php
- modules/genomic_browser/ajax/genomic_file_upload.php
- modules/imaging_browser/php/imaging_browser.class.inc
- modules/imaging_browser/php/viewsession.class.inc
- modules/instrument_list/php/instrument_list_controlpanel.class.inc
- modules/timepoint_list/php/timepoint_list.class.inc
- php/installer/Installer.class.inc
- php/libraries/File_Upload.class.inc
- php/libraries/LorisForm.class.inc
- php/libraries/Utility.class.inc
Our PHPCS was a few versions behind so I figured it was time to update. Versions 3.0 - 3.3 are incompatible with PHP 7.3.* and there is [a bug](https://github.com/squizlabs/PHP_CodeSniffer/issues/2442) in version 3.4 that causes unresolvable errors with certain parts of our code base. As a result the best case for us right now is the last stable version of version 2.
This PR also contains coding style changes generates by phpcbf according to the new phpcs version.
Resolves #4099
> [Meta] Update phpcs to 2.9.2

- .phan/config.php
- modules/dashboard/php/dashboard.class.inc
- modules/dicom_archive/php/dicomarchiveanonymizer.class.inc
- modules/examiner/php/editexaminer.class.inc
- modules/help_editor/php/edit_help_content.class.inc
- modules/instrument_list/php/instrument_list_controlpanel.class.inc
- modules/statistics/php/stats_behavioural.class.inc
- modules/user_accounts/php/edit_user.class.inc
- modules/user_accounts/php/my_preferences.class.inc
- php/libraries/CouchDB.class.inc
- php/libraries/NDB_Config.class.inc
- php/libraries/SinglePointLogin.class.inc
- php/libraries/TimePoint.class.inc
Adds PhanTypeArraySuspiciousNullable rule to our analysis. This rule flags code where array elements are accessed in places where the arrays can be null. As a result this PR adds a lot of `is_null` checks to DB results and throws a lot of Exceptions in case they happen.
> [Phan] Add PhanTypeArraySuspiciousNullable rule

- modules/candidate_parameters/php/candidate_parameters.class.inc
These functions were marked in the codebase as to be deleted on major.
> [Candidate Parameters] Remove deprecated functions

- php/libraries/Database.class.inc
- test/unittests/Database_Test.php
> Revert "[Database] Add NOQUOTES as an HTML escaping option for JSON"

- php/libraries/Project.class.inc
This fixes a bug from type hinting on major the LORIS API:
https://{loris-instance}/api/v0.0.3-dev/projects/{project_name}/images
> [php/libraries/Project.class.inc] fix type hinting error by cast int

- test/unittests/AnonymousUserTest.php
This is the easiest test case demo for a class without dependency. (For summer student)
https://github.com/aces/Loris/pull/4383
Todo: 
Breadcrumb.class.inc
BreadcrumbTrail.class.inc
Identifier.class.inc
LorisForm.class.inc
> [Test] unittest for AnonymousUser.class.inc

- .travis.yml
> [Travis] remove  distro

- .travis.yml
> Push bugfix into 20.3 release

- SQL/0000-00-00-schema.sql
- SQL/0000-00-01-Permission.sql
- SQL/0000-00-02-Menus.sql
- SQL/0000-00-03-ConfigTables.sql
- SQL/Archive/20.3/2018-05-28_publication_schema.sql
The SQL for publication module was omitted accidentally
+ changed a `utf8mb4` to `utf8` for consistency
> Add publication module SQL to the schema files

- modules/media/ajax/FileUpload.php
- modules/media/php/media.class.inc
This pull request changes [] to array() in the media module. Changes were made to two files - Fileupload.php and media.class.inc. 
-Pull the PR and test in you VM.
-Make sure the instrument builder in the media module is fully working.
-Look at the code to make sure the change has been made
> [SQL] Fixed array convention from [] to array()

- .phan/config.php
- htdocs/main.php
- modules/brainbrowser/ajax/image.php
- modules/candidate_parameters/ajax/formHandler.php
- modules/dataquery/ajax/retrieveCategoryDocs.php
- modules/dataquery/ajax/saveQuery.php
- modules/genomic_browser/ajax/genomic_file_upload.php
- modules/genomic_browser/php/view_genomic_file.class.inc
- modules/imaging_browser/php/viewsession.class.inc
- modules/publication/ajax/FileUpload.php
- modules/server_processes_manager/php/mriuploadserverprocess.class.inc
- modules/statistics/php/stats_demographic.class.inc
- modules/statistics/php/stats_mri.class.inc
- php/installer/Installer.class.inc
- php/libraries/CouchDB.class.inc
- php/libraries/Email.class.inc
- php/libraries/File_Upload.class.inc
- php/libraries/LorisForm.class.inc
- php/libraries/Module.class.inc
- php/libraries/NDB_BVL_Battery.class.inc
- php/libraries/NDB_BVL_Feedback.class.inc
- php/libraries/NDB_BVL_Instrument.class.inc
- php/libraries/NDB_Caller.class.inc
- php/libraries/NDB_Config.class.inc
- php/libraries/Site.class.inc
- src/Data/MapIterator.php
- src/Http/StringStream.php
This rule makes sure that when we use PHP built-in functions that the arguments we pass to them are of the correct type.
~~Blocked by https://github.com/aces/Loris/pull/4330 and https://github.com/aces/Loris/pull/4320.~~
>  [Phan] Add rule PhanTypeMismatchArgumentInternal 

- modules/media/jsx/mediaIndex.js
- modules/media/php/hidefilefilter.class.inc
- modules/media/php/media.class.inc
- modules/media/php/mediafile.class.inc
- modules/media/php/mediafileprovisioner.class.inc
- modules/media/test/MediaTest.php
Implemented the Data Framework for the Media Module. 
- Make sure that everything is loading properly in the datatable
- Make sure the filter is filtering data properly
- Make sure that when the permissions are not set to 'superuser', the hidden files are indeed hidden from the datatable.
> [Media] Data FrameWork Implementation

- php/libraries/User.class.inc
Resolves #4490 
See for more info: https://www.php.net/manual/en/function.htmlspecialchars-decode.php
> [Authentication] Fixing password encoding / decoding error

- htdocs/bootstrap/css/custom-css.css
- jsx/DataTable.js
- modules/candidate_list/test/candidate_listTest.php
- modules/dicom_archive/test/dicom_archiveTest.php
- modules/survey_accounts/test/survey_accountsTest.php
- modules/user_accounts/test/user_accountsTest.php
fixes https://github.com/aces/Loris/issues/4500 by using flex
before: 
after:
> [UI CSS] fix data table grid css

- modules/dashboard/js/dashboard-helper.js
This PR fixes the console output error when viewing the dashboard on a clean install of Loris.
Before:
TypeError: undefined is not an object (evaluating 'data.datasets.female')
https://github.com/aces/Loris/projects/19#card-21296577
After:
> [Dashboard] TypeError: undefined is not an object (evaluating 'data.datasets.female')

- tools/install.sh
https://github.com/aces/Loris/issues/4538
> [install] fix path

- php/libraries/User.class.inc
Fixes a type error that caused the publication module to throw a 500 error.
@christinerogers Giving you the assignment because you reported the bug.
Resolves #4562
> [User] Fix TypeError that broke Publications module

- php/libraries/NDB_Notifier.class.inc
- php/libraries/NDB_Notifier_Abstract.class.inc
https://github.com/aces/Loris/issues/4504
> [document_repository] int to string - can't upload file

- modules/acknowledgements/jsx/acknowledgementsIndex.js
- modules/acknowledgements/php/acknowledgements.class.inc
Fixes when multiple values such as douglas,mcgill need to be in the Affiliations column. Output will be Douglas, McGill
> [acknowledgements] End Date, Affiliations,Degrees columns not populated

- SQL/Cleanup_patches/2019-05-15-Reliability_link.sql
> Remove Menu link for reliability

- modules/login/php/passwordreset.class.inc
fixes https://github.com/aces/Loris/issues/4511
> [Login] Add required to password-reset field

- modules/bvl_feedback/jsx/react.behavioural_feedback_panel.js
> [bvl_feedback] Fix broken link to instruments in summary panel

- php/libraries/NDB_BVL_InstrumentStatus_ControlPanel.class.inc
- smarty/templates/instrumentstatus_controlpanel.tpl
> [InstrumentControlPanel/CSS] change icons to font awesome

- modules/login/php/requestaccount.class.inc
- php/libraries/LorisForm.class.inc
fixes https://github.com/aces/Loris/issues/4512
> [login/RequestAccount] Add required to form fields

- modules/user_accounts/php/edit_user.class.inc
Fixes the error output of there being no NA_Password key in the $values array.
> [user_accounts] Undefined index: NA_Password when updating user settings

- jsx/DataTable.js
fixes 1 part of https://github.com/aces/Loris/issues/4626
> [jsx/DataTable] Revert UI changes made in issuetracker PR

- modules/issue_tracker/php/issuewatchermapper.class.inc
Problem: Clean install of LORIS with importing RB will result in issue_tracker not working at all. 
This fix makes the module work.
> [issue_tracker] Notice: Undefined index: userID in issuewatchermapper.class.inc

- modules/data_integrity_flag/jsx/dataIntegrityFlagIndex.js
- modules/data_integrity_flag/php/data_integrity_flag.class.inc
- modules/data_integrity_flag/test/TestPlan.md
fixes https://github.com/aces/Loris/issues/4542
> [Data Integrity Flag] Add users option in filtering + fix link to datateamhelper

- modules/acknowledgements/jsx/acknowledgementsIndex.js
- modules/acknowledgements/php/acknowledgements.class.inc
- fixes issue https://github.com/aces/Loris/issues/4519
- fixes issue https://github.com/aces/Loris/issues/4509
- removes swal warning on exiting 'add acknowledgements' form if form is empty
> [Acknowledgement] fix end date filtering

- php/libraries/TimePoint.class.inc
Changing the return type.
To test: load instrument_list on test.loris.ca (has been fixed on testing VM).
> [instrument_list] can not load for next stage

- php/libraries/ConflictDetector.class.inc
fixes https://github.com/aces/Loris/issues/4581
> [Instrument] Change null to empty string in ConflictDetector

- modules/bvl_feedback/jsx/react.behavioural_feedback_panel.js
to resolve https://github.com/aces/Loris/issues/4580
> [bvl_feedback] feedback will only save after toggling 'Feedback Type'

- modules/instrument_builder/jsx/react.questions.js
Resolve : https://github.com/aces/Loris/issues/4608
> [instrument_builder] Clicking "Edit" on a Header crashes the system

- modules/timepoint_list/test/TestPlan.md
Updated [Testplan.md](https://github.com/aces/Loris/blob/minor/modules/timepoint_list/test/TestPlan.md)
- Resolves #4529 
- Navigate to [TestPlan.md](https://github.com/kchatpar/Loris/blob/updateTimepointtestPlan/modules/timepoint_list/test/TestPlan.md) and make sure that item 2's first bullet says "For a candidate of a different site than your user, attempt to access the timepoint list via the url. The page should load with a message of 'Permission Denied' which redirects the user back to the homepage."
> [Timepoint/TestPlan] Updated TestPlan.md

- modules/instrument_manager/php/instrument_manager.class.inc
- modules/instrument_manager/test/TestPlan.md
- php/libraries/NDB_BVL_Instrument.class.inc
Adds some bug fixes to issues discovered during manual testing.
Resolves #4522 
Resolves #4525
Resolves #4526
> Fix errors in instrument manager and update test plan

- SQL/0000-00-00-schema.sql
- SQL/New_patches/2019-04-04_add_image_type_to_mri_protocol.sql
- modules/media/ajax/FileUpload.php
- tools/install.sh
This merges the minor branch (which has SQL changes required for LORIS-MRI) into the 21.0 release branch.
> Merge Minor Branch into Release

- modules/README.md
- modules/dataquery/jsx/react.tabs.js
- modules/issue_tracker/jsx/index.js
- php/libraries/User.class.inc
This pulls the latest bugfix changes into the 21.0-release branch.
Note that there were conflicts in php/libraries/User.class.inc and modules/dataquery/jsx/reacts.tabs.js. Extra care should be taken reviewing file changes from those files.
> Push bugfix into 21.0.0

- modules/help_editor/jsx/help_editor.js
to solve: https://github.com/aces/Loris/issues/4705
> [help_editor] fix help id

- modules/document_repository/jsx/docIndex.js
- modules/document_repository/php/files.class.inc
- modules/document_repository/test/TestPlan.md
Fixes
```
5. Undefined index php notices in error log
8. Pointer cursor can be added for 'Delete'
13. test plan probably needs updating
```
from https://github.com/aces/Loris/issues/4702
> [Doc repo] Fix undefined index error and update test plan

- htdocs/feedback_mri_popup.php
- php/libraries/FeedbackMRI.class.inc
to solve : https://github.com/aces/Loris/issues/4726
> [imaging_browser] Cannot access Visit-level QC feedback dialog window

- modules/candidate_parameters/jsx/FamilyInfo.js
> [Candidate Parameters] Fixing Family Info Tab Not Loading Any Data Issue

- modules/instrument_list/php/instrument_list_controlpanel.class.inc
fixes 1 part of https://github.com/aces/Loris/issues/4584
> [instrument_list] Fix BVLQCType on ControlPanel

- jsx/Form.js
- modules/document_repository/jsx/childTree.js
- modules/document_repository/jsx/docIndex.js
- modules/document_repository/jsx/parentTree.js
If you look at the console log on https://test.loris.ca/document_repository/, you'll see a bunch of errors. This PR fixes all those, including the functionality of the 'Global Selection Filter' checkbox + tree display on change. It also does some cleanup and removes `console.logs`
**Note: this PR only focuses on fixing errors in the 'Browse' tab.**
> [Doc Repo] Fix errors from reactification

- modules/imaging_browser/css/imaging_browser.css
to solve :https://github.com/aces/Loris/issues/4678
> [Imaging Browser]  tiny css change

- test/unittests/BreadcrumbTest.php
I made a new unit test class for Breadcrumb.class.inc
I might add more edge cases (like whitespace) if necessary.
https://github.com/aces/Loris/pull/4378
Travis
> [Test] unittests for Breadcrumb.class.inc

- modules/bvl_feedback/test/TestPlan.md
To resolve the test plan format.
https://github.com/aces/Loris/issues/4586
> [bvl_feedback] Amend test plan - format

- modules/document_repository/jsx/childTree.js
- modules/document_repository/jsx/docIndex.js
fixes 
`12. No 'date uploaded' date` of https://github.com/aces/Loris/issues/4702
> [Doc repo] Restore date_uploaded column

- jsx/MultiSelectDropdown.js
- modules/dataquery/jsx/react.app.js
- modules/dataquery/jsx/react.fieldselector.js
- modules/dataquery/jsx/react.filterBuilder.js
- modules/dataquery/jsx/react.tabs.js
- removes console log errors
- includes changes from https://github.com/aces/Loris/pull/4464 which i will now close
- replaces functions with arrow functions for automatic binding, allowing us to remove silly things like `var that = this`
> [DQT] Fix react errors 

- modules/user_accounts/test/TestPlan.md
Updates the user account test plan so that it i inline with the development that's been done for 21.0.
> Update the user account test plan.

- jsx/DataTable.js
- jsx/Filter.js
- modules/issue_tracker/php/issuerowprovisioner.class.inc
- modules/issue_tracker/php/issuewatchermapper.class.inc
1. Fixes https://github.com/aces/Loris/issues/4762
2. Fixes errors in console about uncontrolled -> controlled checkbox
3. Fixes 'Watching' filtering
4. Fixes 
To test:
> [Issue_tracker] Fix multiple bugs from 21.0 testing

- htdocs/feedback_mri_popup.php
- htdocs/router.php
This should fix item 22 of the imaging browser test plan -- the
page should be viewable by all, regardless of imaging_browser_qc
permission.
Fixes #4785
> [Imaging Browser] Fix loading of feedback popup for non-QC users

- modules/quality_control/jsx/qualityControlIndex.js
- modules/quality_control/php/quality_control.class.inc
Fixed this problem:
Notice: Undefined variable: projectList2 in 
Loris/modules/quality_control/php/quality_control.class.inc on line 240
Also fixed frontend undefined errors for when no data exists on fresh install of LORIS.
Please comment if the error message displayed to the user when no data exists should be something else.
> [quality_control] fresh install fixed quality_control frontend errors

- modules/data_integrity_flag/php/data_integrity_flag.class.inc
Resolves #4673 
To test:
Follow last step of test plan
> [data_integrity_flag] fix validation on non-required element before db insert

- raisinbread/instruments/NDB_BVL_Instrument_medical_history.class.inc
fixes https://github.com/aces/Loris/issues/4847
> [Medical history] gender to sex

- modules/imaging_uploader/jsx/UploadForm.js
Fixes the message dialog for an error when uploading.
> [Imaging Uploader] fixed Incorrect 'Fields do not match filename' error message

- package-lock.json
- test/unittests/BreadcrumbTrailTest.php
I made a unit test class for BreadcrumbTrail.class.inc which includes one unit test for the __toString() method.
#4378 
Run "sudo npm run tests:unit -- --filter BreadcrumbTrail" or check out Travis
> [Test] unittests for BreadcrumbTrail.class.inc

- modules/media/ajax/FileUpload.php
Add check to verify that the date of administration is not
in the future, if provided.
Fixes #4573.
> [Media] Ensure date of administration is not in the future

- modules/dashboard/test/TestPlan.md
This PR updates the dashboard test plan to reflect its current behaviour.
> [Dashboard] Update test plan

- modules/candidate_list/help/candidate_list.md
Fixing formatting issue with help text in Candidate List module
> [Help] Fixing formatting issue with help text in Candidate List module 

- modules/document_repository/jsx/uploadForm.js
to solve: https://github.com/aces/Loris/issues/4776
to test: upload a duplicate file.
> [Document repository] fix Upload formdata gets erased if error

- jsx/DataTable.js
fixes https://github.com/aces/Loris/issues/4715
> [jsx/DataTable] Fix rows per page

- modules/document_repository/jsx/uploadForm.js
to solve:https://github.com/aces/Loris/issues/4780
> [Document repository] fix Newly uploaded file does not appear until refresh

- modules/issue_tracker/ajax/EditIssue.php
> [Travis] block - phan error fix

- modules/candidate_list/test/TestPlan.md
> [candidate_list] Fix Typo in Test Plan

- modules/candidate_parameters/test/TestPlan.md
> [candidate_parameters] Fix Typo in Test Plan

- tools/CouchDB_Import_Demographics.php
- tools/CouchDB_Import_Instruments.php
the escaping was happening mid field name. the resulting would look like this
```
cc`1`.Status
```
instead of 
```
`cc1`.Status
```
> [Couch importers] Issue in escaping

- modules/data_team_helper/test/TestPlan.md
This updates the data team helper test plan with the latest feature of that module.
> Update data team helper test plan

- jsx/DataTable.js
- jsx/FilterableDataTable.js
- modules/document_repository/jsx/docIndex.js
to solve: https://github.com/aces/Loris/issues/4777
> [document_repository] show sub-category in empty table

- modules/timepoint_list/test/TestPlan.md
Update TestPlan item 1 to hint the access to timepoint_list without permission.
> [timepoint_list]update test plan to hint the access to timepoint_list

- SQL/0000-00-00-schema.sql
- SQL/Archive/21.0/2019-05-03-deprecate_useprojects.sql
- SQL/Release_patches/20.3_To_21.0_upgrade.sql
Adding missing statemnt into the default schema for `loris` default project.
> [SQL] Missing statement from default schema

- raisinbread/README.md
adding helpful troubleshooting tips
> [RB] small change in instructions

- SQL/0000-00-00-schema.sql
- SQL/New_patches/2019-07-10-subproject-session-FK.sql
- modules/dashboard/test/DashboardTest.php
- modules/mri_violations/test/mri_violationsTest.php
- modules/survey_accounts/test/survey_accountsTest.php
> [SQL] Add foreign key to session table for subprojects

- modules/README.md
This updates the document explaining the structure of a directory in the
modules/ directory, both to provide more detail and remove outdated
information such as telling people to use the ajax/ directory.
> [Doc] Update modules/README.md

- modules/timepoint_list/templates/timepoint_list_controlpanel.tpl
Unnecessary extra data_entry permission check...
> [Timepoint List] Fixing bad logic in Timepoint List Control Panel

- php/libraries/NDB_BVL_Instrument.class.inc
This is the same PR as #4970 which was merged into minor. Re-issuing because bugfix was made to wrong branch. Want it on 21.0-release.
> [Core: Instrument] Fix bug related to altered return type (RE-ISSUED)

- .phan/config.php
- modules/server_processes_manager/php/serverprocessfactory.class.inc
- php/libraries/NDB_Factory.class.inc
Phan will now make sure that we are only calling methods on entities that it believes are objects.
Not too many bugs to fix with this one.
> Add new phan rule PhanNonClassMethodCall

- .travis.yml
- composer.json
- composer.lock
- htdocs/survey.php
- modules/configuration/ajax/updateProject.php
- modules/new_profile/php/new_profile.class.inc
- modules/server_processes_manager/php/abstractserverprocess.class.inc
- modules/server_processes_manager/php/process.class.inc
- modules/statistics/php/stats_mri.class.inc
- php/libraries/ConflictDetector.class.inc
- php/libraries/File_Upload.class.inc
- php/libraries/NDB_BVL_Battery.class.inc
- php/libraries/User.class.inc
- php/libraries/Utility.class.inc
Our Phan version is aging. Since it's a static analysis dev tool, we should keep it up-to-date to benefit from bug fixes and new features.
In particular, this version of `phan` supports the `--redundant-condition-detection` which is unsupported by our current version.
I recommend that this PR gets merged into `minor` and `major` as well as bugfix ASAP so that the same static analysis conditions are run against every branch.
Takes over some functionality of #4433
> [Testing] Update Phan to latest version

- Dockerfile.test.php7
- README.md
- php/libraries/NDB_BVL_Instrument.class.inc
- src/Api/Endpoints/Projects.php
> PUSH of 21.0-release into BUGFIX again

- tools/install.sh
projectname: unbound variable
https://github.com/aces/Loris/issues/5158
> [install]  Install.sh - Unbound Variable errors in Bash scripts

- CONTRIBUTING.md
Update our CONTRIBUTING doc to include a directive on updating Raisinbread when SQL changes are made.
> [Test] Add link to Raisinbread modification instructions to the CONTRIBUTING doc

- package-lock.json
`npm audit` reported a ton of vulnerabilities on the `major` branch.
I ran `npm audit fix` and then committed the `package-lock.json` file.
> Update npm packages containing security problems

- php/libraries/Utility.class.inc
Remove note which no one seems to understand the origin of
and is causing confusion. Resolves #5227.
> [Utility] Remove confusing note

- jsx/Form.js
- modules/media/jsx/uploadForm.js
Add HeaderElement as a form element, useful for future instrument rendering in React
1. Go to Media module Upload form. Test that 'Upload a media file' form header looks exactly the same
> [jsx/Form.js] Add <HeaderElement />

- .phan/config.php
- modules/dashboard/php/dashboard.class.inc
- php/libraries/Database.class.inc
- php/libraries/NDB_Page.class.inc
This rule checks whether value is being converted to a string when it doesn't make sense to do that, such as for booleans.
> Add new phan rule PhanTypeSuspiciousStringExpression

- modules/media/jsx/mediaIndex.js
- modules/media/php/media.class.inc
- php/libraries/DataFrameworkMenu.class.inc
- php/libraries/Module.class.inc
Update the Media module to use the new DataFrameworkMenu class.
Should work the same as before.
> [Media] Use DataFrameworkMenu class

- README.md
`contribute` instead of `contribue` to LORIS!
Look up proper spelling of `contribute` in English
> [Meta] Small fix in README

- modules/acknowledgements/test/TestPlan.md
Fixing TestPlan to proper Markdown syntax
Check that the TestPlan renders as Markdown
> [Acknowledgements] Fixing TestPlan to proper Markdown syntax

- raisinbread/migration
> [Raisinbread] update migration log major

- htdocs/css/panel.css
- modules/bvl_feedback/js/bvl_feedback_panel_jquery.js
- modules/bvl_feedback/jsx/react.behavioural_feedback_panel.js
fixes https://github.com/aces/Loris/issues/5074
1. Check BVL Feedback panel with data
*https://redmine.cbrain.mcgill.ca/issues/15186
> [BVL Feedback] Add dynamictable and fix margin-top

- src/Http/Response/Created.php
- src/Http/Response/OK.php
Builds on the work of @xlecours's PR https://github.com/aces/Loris/pull/4275 to add the OK and Created responses with our src/ directory.
This will allow us to simplify the writing of PSR-compliant code.
> [Core] Add '200 OK' and '201 Created' responses to src/

- .gitignore
- modules/api/php/endpoints/candidate/visit/visit.class.inc
- modules/api/php/endpoints/project/candidates.class.inc
- modules/api/php/endpoints/project/images.class.inc
- modules/api/php/endpoints/project/instrument/instrument.class.inc
- modules/api/php/endpoints/project/instruments.class.inc
- modules/api/php/endpoints/project/project.class.inc
- modules/api/php/endpoints/project/visits.class.inc
- modules/api/php/views/project/instruments.class.inc
- php/libraries/Image.class.inc
- php/libraries/TimePoint.class.inc
- src/Data/Filters/PhantomsFilter.php
- src/Data/Filters/ScansFilter.php
- src/Data/Models/ImageDTO.php
- Moving Phantoms and Scans filters in src
- Adding filters to the timepoint images provisioner
* force add `modules/api/php/endpoints/project` folder to git tracked files
* force add `modules/api/php/views/project` folder to git tracked files
fixes  #5341
> [API] Make candidate images permission "protected"

- composer.json
- composer.lock
As long as Travis passes then that means the update is successful.
> Update phan to latest minor version

- modules/user_accounts/php/edit_user.class.inc
Admin user can't add or edit a user.
Resolves #5368
> [user_account] can't add or edit a user on major

- modules/new_profile/php/new_profile.class.inc
It needs to return a candID as a string, not an object.
> [new_profile] can't create a new profile on major

- modules/acknowledgements/test/TestPlan.md
This updates the test plan of the acknowledgements module.
> [acknowledgements] update module test plan

- SQL/0000-00-00-schema.sql
missing alais in default project was preventing schema sourcing
> [SQL] fix unsourcable schema

- modules/timepoint_list/test/TestPlan.md
Small updates to the test plan for the timepoint list module.
> [timepoint_list] Update test plan

- modules/brainbrowser/test/brainbrowser_test_plan.md
- modules/imaging_browser/README.md
> [Brainbrowser] Test plan update

- modules/api/php/provisioners/candidatesprovisioner.class.inc
- modules/statistics/php/stats_behavioural.class.inc
fix instances of `c.ProjectID` coming from the merge of minor into major
> [Project] Fix instances of c.project coming from minor

- modules/document_repository/jsx/uploadForm.js
- modules/document_repository/php/files.class.inc
fixes https://github.com/aces/Loris/issues/5453
1. test #11 of test plan
* https://github.com/aces/Loris/issues/5453
> [DocRepo] fix duplicate file error

- htdocs/bootstrap/css/custom-css.css
- modules/statistics/templates/form_statistics.tpl
Fixes minor UI issue in dropdown in <900px wide screens.
* #5460
> fix UI for statistics when on mobile mode

- smarty/templates/directentry.tpl
> Fix repetitive messages in review page issue 5116

- modules/statistics/php/stats_behavioural.class.inc
Fixes https://github.com/aces/Loris/issues/5463
* https://github.com/aces/Loris/issues/5463
> [Statistics] Fix Behavioural Statistics Value Not Updating Issue

- php/libraries/File_Upload.class.inc
> [Imaging Uploader] Fix error where uploaded image did not display on front-end

- modules/issue_tracker/test/issue_tracker_test_plan.md
To fix the test plan indicating that some the function was not available now
Check the test plan that the following items are removed:
Issue Tracker Create New Issue [Manual Testing]
7. Navigation bar should lead you back to list
Issue Tracker Edit Existing Issue [Manual Testing]
7. Check that the navigation bar bring you to the next issue in your previously filtered list of issues.
fixes #5495
*
> [Issue Tracker] update test plan to delete items not relevant

- modules/configuration/README.md
- modules/configuration/test/TestPlan.md
Most changes are whitespace, I added new lines for readability in raw format
> [configuration] clean-up of testplan for readability

- modules/instrument_builder/test/TestPlan.md
Group validate process together to improve the test work flow
1. Read the TestPlan item 1 to item 8.
fixed:
#5494 
#5493 
#5488 
#5484 
*
> Improve instrument builder test plan

- modules/create_timepoint/php/create_timepoint.class.inc
- modules/create_timepoint/test/create_timepointTest.php
Fixed bug below and changed behaviour to only display projects user is affiliated with
https://github.com/aces/Loris/issues/5418
> [create_timepoint] Fix null project bug

- modules/datadict/test/TestPlan.md
https://github.com/aces/Loris/issues/5551
mostly white space changes except the path in item 11
> [datadict] Test plan improved readability and fixed script location

- modules/document_repository/jsx/docIndex.js
1. Remove extraneous files that actually belong to subdirectories
2. Add global filtering of files only, without directory structure
3. Rename a couple states and functions to be more meaningful
On `22.0-release`, verify:
1.  Files in subcategories are recursively shown in parent categories (read description of this issue https://github.com/aces/Loris/issues/5449 for more clarity)
2. Clicking on 'Global Selection Filter' just takes you to the root directory
On this branch, test:
1. Files exist in their rightful categories and their categories alone.
2. Clicking on 'Filter globally' removes the directory structure and lists all files so that you can filter for all. The directory tree display ( _Root > ...._ ) disappears as well.
3. Unchecking 'Filter globally' will return table to normal …
> [DocRepo] Clean up directory content and let filter without folders

- modules/mri_violations/php/mri_protocol_check_violations.class.inc
- modules/mri_violations/php/mri_protocol_violations.class.inc
- modules/mri_violations/php/mri_violations.class.inc
- modules/mri_violations/php/resolved_violations.class.inc
- modules/mri_violations/test/TestPlan.md
- modules/mri_violations/test/mri_violationsTest.php
Allows users with the 'edit' permission to view the module even if they don't have 'view' permissions.
Adds an integration test to the above + code cleanup.
Rewrites the test plan to be up-to-date and easier to follow.
* Resolves #5419 
* Resolves #5421 
* Resolves #5422
> [MRI_Violations] Fixes permission bug; integration test to confirm bug fix; test plan update

- modules/configuration/ajax/updateProject.php
- modules/configuration/js/project.js
- modules/configuration/templates/form_project.tpl
- php/libraries/NDB_Config.class.inc
- php/libraries/Project.class.inc
- test/unittests/NDB_ConfigTest.php
https://github.com/aces/Loris/issues/5539
> [Configuration] Added new Alias field to the front end

- modules/brainbrowser/test/brainbrowser_test_plan.md
removed vestigial instructions
> [brainbrowser] testplan update

- raisinbread/RB_files/RB_Config.sql
> [RB] Add a default for the config setting instrumentResetting

- jsx/DataTable.js
This PR resolves the following issues:
#5566: The pagination is now functional on the DataTable.
#5458: All filtered rows will be downloaded when clicking on 'Download CSV' button.
> [JSX - DataTable] Resolve Pagination and CSVDownload Issues

- modules/user_accounts/templates/form_edit_user.tpl
- modules/user_accounts/templates/form_my_preferences.tpl
Update user accounts module to properly display the new password strength guidelines. These match the ones on the password expiry form in the login module.
> [User Accounts] Update password strength rules documentation

- modules/behavioural_qc/jsx/behavioural_qc_module.js
- modules/behavioural_qc/templates/form_behavioural_qc.tpl
- modules/behavioural_qc/test/behavioural_qcTest.php
replace `beahavioural` by `behavioural`
> [behavioural_qc] Fix rida cant spell issues

- raisinbread/instruments/NDB_BVL_Instrument_mri_parameter_form.class.inc
- raisinbread/instruments/instrument_sql/mri_parameter_form.sql
- removed unused functions in instrument
- removed old date conversion logic when single date fields were not yet used
- fixed scantypes displayed in instrument to match SQL
1. make sure to dump and resource RB data because instrument SQL changed
2. make sure to re-copy the `raisinbread/instruments` into `project/instruments`
* fixes https://github.com/aces/Loris/issues/5517
> [RB instruments] Fixed MRI parameter form not saving dates

- modules/dashboard/help/dashboard.md
New copy for LORIS dashboard (homepage) help text
1. Edit copy if necessary
2. Check out screenshot of rendering below
*https://github.com/aces/Loris/issues/5576
> [Dashboard] Updated module help text

- modules/configuration/ajax/process.php
- modules/configuration/js/configuration_helper.js
multiple entry fields broken
https://github.com/aces/Loris/issues/5506
> [Configuration] multiple entry fields broken - bug fix

- README.CentOS7.md
- modules/user_accounts/php/edit_user.class.inc
See https://github.com/aces/Loris/issues/5451
Solves building errors with composer on CentOS.
> [install CentOS] required extensions for composer

- SQL/New_patches/2019-11-12-Rename_modules_QC_and_DTH.sql
Adjust the SQL patch for mysql server error:
`ERROR 1093 (HY000): You can't specify target table 'LorisMenu' for update in FROM clause`
run the patch. There should be no error.
> [SQL] using variable instead of subselect

- modules/dataquery/test/TestPlan.md
Adds the test plan for the DQT...
1. Follow the test plan
> [dataquery] Adding the test plan

- modules/imaging_browser/php/viewsession.class.inc
- modules/issue_tracker/ajax/EditIssue.php
Solves error log pollution when issueComment is null.
1. Checkout PR
2. View issue when no comment
#5365
> [issue_tracker] Cleanup PHP Notice caused by unset variable

- modules/candidate_list/help/candidate_list.md
Updated file for the Access Profile module help text
1. Edit copy if necessary
2. Check out screenshot of rendering below
*https://github.com/aces/Loris/issues/5576
> [Access Profile/candidate_list] Updated module help text

- modules/examiner/help/examiner.md
New copy for Examiner module help text
1. Edit copy if necessary
2. Check out screenshot of rendering below
*https://github.com/aces/Loris/issues/5576
> [Examiner] Updated module help text

- modules/media/help/media.md
New copy for Media module help text
1. Edit copy if necessary
2. Check out screenshot of rendering below
*https://github.com/aces/Loris/issues/5576
> [Media] updated module help text

- docs/wiki/01 - STUDY PARAMETERS SETUP/01 - Study Variables/00 - Introduction to Study Variables.md
> [WIKI] Study param overview

- modules/dataquery/jsx/react.app.js
- modules/dataquery/jsx/react.fieldselector.js
Merge DQT fix which was merged into 21.0-release into 22.0-release.
> 21.0 release branch merge

- modules/new_profile/jsx/NewProfileIndex.js
- modules/new_profile/test/new_profileTest.php
Addressed Issue #5550 by removing the Panel around the New Profile Form and replacing it with a Fieldset.
> [New Profile] Removed Panel From New Profile Module

- modules/statistics/help/statistics.md
> [Statistics] Help file typo

- modules/dataquery/help/dataquery.md
* Replaces #5200 
linked to: #5576
> [DQT] Restore help file; update contents

- modules/api/php/endpoints/candidates.class.inc
- modules/api/php/provisioners/projectimagesrowprovisioner.class.inc
Two tiny bug fixes related to the project structure.
1. test that you can create a new candidate via the API
2. test that you can access all the images of a project
*
> [api] fixed project bugs in the API

- modules/mri_violations/test/TestPlan.md
added some clarifications to the test plan
> [MRI_violation] clarification to instruction and few grammatical corrections

- README.CentOS7.md
Updates the installation command for NodeJS and so version 8 will be installed.
1. Test command on CentOS
* https://github.com/aces/Loris/issues/5725#issuecomment-558259292
> [CentOS] update installation instructions for NodeJS

- php/libraries/NDB_BVL_InstrumentStatus.class.inc
- php/libraries/NDB_BVL_InstrumentStatus_ControlPanel.class.inc
Solves the issue #https://github.com/aces/Loris/issues/5736 
1. Access an instrument and check if status is switched.
* https://github.com/aces/Loris/issues/5736
> [Instruments/instrument_list] Fix bug where Instrument set to in progress as soon as it is accessed

- modules/issue_tracker/ajax/EditIssue.php
fixes https://github.com/aces/Loris/issues/5794
> Fix issue tracker only pscid provided

- php/libraries/NDB_BVL_Instrument.class.inc
https://github.com/aces/Loris/issues/5700
test: click "Delete instrument data" button and two checkboxes. 
Then check the form of this instrument.
> [instrument_list] fix "Delete instrument data" 500 Error

- jsx/Form.js
- modules/candidate_list/jsx/candidateListIndex.js
- modules/login/php/requestaccount.class.inc
- modules/new_profile/jsx/NewProfileIndex.js
Merge bug fixes from 21.0-release into 22.0-release.
> Branch Merge of 21.0 to 22.0

- docs/wiki/01 - STUDY PARAMETERS SETUP/01 - Study Variables/02 - Projects.md
How to add/configure Projects
___
*This and all upcoming PRs for the WIKI will contain one or a couple files at most. this will hopefully prevent PRs from staying open for very long periods.*
*This and all upcoming PRs are open to discussions and suggestions. Most of the content has been copied over from the existing WIKI with sometimes minor, major or total changes.*
*Feel free to make suggestions and/or push directly to the branch !!
> [WIKI] Study Parameters - Projects

- docs/wiki/01 - STUDY PARAMETERS SETUP/01 - Study Variables/05 - Timepoints.md
- docs/wiki/99 - Developers/SQL Dictionary.md
How to add/configure Visits
___
*This and all upcoming PRs for the WIKI will contain one or a couple files at most. this will hopefully prevent PRs from staying open for very long periods.*
*This and all upcoming PRs are open to discussions and suggestions. Most of the content has been copied over from the existing WIKI with sometimes minor, major or total changes.*
*Feel free to make suggestions and/or push directly to the branch !!
> [WIKI] Study Parameters - Visits

- htdocs/postdeploy.php
Adding the EEG sqls into the postdeploy script
Run the 1-click installer if you want to test
> Updating postdeploy script for Heroku

- docs/wiki/01 - STUDY PARAMETERS SETUP/01 - Study Variables/01 - Identifiers.md
How to add, configure the ID generation for the study
___
*This and all upcoming PRs for the WIKI will contain one or a couple files at most. this will hopefully prevent PRs from staying open for very long periods.*
*This and all upcoming PRs are open to discussions and suggestions. Most of the content has been copied over from the existing WIKI with sometimes minor, major or total changes.*
*Feel free to make suggestions and/or push directly to the branch !!*
> [WIKI] Study Parameter - Identifiers

- docs/wiki/01 - STUDY PARAMETERS SETUP/01 - Study Variables/04 - Subprojects.md
- docs/wiki/99 - Developers/SQL Dictionary.md
How to add/configure Subprojects
new PR to replace #4307 
___
*This and all upcoming PRs for the WIKI will contain one or a couple files at most. this will hopefully prevent PRs from staying open for very long periods.*
*This and all upcoming PRs are open to discussions and suggestions. Most of the content has been copied over from the existing WIKI with sometimes minor, major or total changes.*
*Feel free to make suggestions and/or push directly to the branch !!
> [WIKI] Study Parameters - Subprojects

- modules/survey_accounts/php/addsurvey.class.inc
Use the designed function to get the full name of the test name.
1. Go to Admin / Survey module, and try to send a candidate's existing Instrument. a translated message should appear.
* Issue #5774
> [Survey Accounts] Fix formatting of error message

- mkdocs.yml
Adds the style guide to the Read The Docs sidebar.
> [ReadTheDocs] Add style guide to navigation bar

- CONTRIBUTING.md
Remove references to old major/minor/bugfix branch scheme and update text to refer to our new branch system post-22 release.
* #5392
> Update CONTRIBUTING.md with new branch information

- modules/document_repository/test/TestPlan.md
> [document_repository] Update TestPlan.md

- package-lock.json
This should prevent issues for developers when switching between branches.
Steps taken:
1. Checkout aces/master
2. `make dev`
3. `git add package-lock.json`
* Alternative to #5820
> [Core] Update package-lock file

- mkdocs.yml
@ridz1208 Recently authored some new wiki documents. This PR adds them to the ReadTheDocs navigation bar.
> [ReadTheDocs] Add Subprojects & Timepoints to nav bar

- modules/dashboard/templates/form_dashboard.tpl
"Welcome, $name." doesn't sound very welcoming.
"Welcome, $name!" sounds more welcoming.
> [Dashboard] Make welcome message more enthusiastic.

- .phan/config.php
- composer.lock
- modules/instrument_list/php/instrument_list.class.inc
- src/Router/BaseRouter.php
This updates phan to the latest version. Replaces #5762 (which is updating to an older version of phan that still has problems with PHP 7.4.)
Fixes #5651.
> Update phan to the newest version.

- composer.json
- composer.lock
- htdocs/installdb.php
- modules/acknowledgements/php/module.class.inc
- modules/bvl_feedback/ajax/react_get_bvl_threads.php
- modules/data_release/php/module.class.inc
- modules/dicom_archive/php/dicomarchiveanonymizer.class.inc
- modules/genomic_browser/php/module.class.inc
- modules/genomic_browser/php/snp_browser.class.inc
- modules/imaging_browser/php/module.class.inc
- modules/imaging_browser/php/viewsession.class.inc
- modules/imaging_qc/php/imaging_qc.class.inc
- modules/instrument_list/php/instrument_list_controlpanel.class.inc
- modules/issue_tracker/php/issue.class.inc
- modules/issue_tracker/php/module.class.inc
- modules/mri_violations/php/module.class.inc
- modules/next_stage/php/next_stage.class.inc
- modules/publication/php/module.class.inc
- php/libraries/BVL_Feedback_Panel.class.inc
- php/libraries/NDB_BVL_Instrument.class.inc
- php/libraries/NDB_BVL_InstrumentStatus_ControlPanel.class.inc
- php/libraries/NDB_BVL_Instrument_LINST.class.inc
- php/libraries/SiteIDGenerator.php
The latest version is 3.5.3 and this updates the package as well as fixes new violations.
> Update PHPCS to latest version

- docs/API/LorisRESTAPI.md
- raisinbread/instruments/NDB_BVL_Instrument_medical_history.class.inc
Documentation update requested in https://github.com/aces/Loris/issues/4995
> Change remaining instances of "gender" to "sex"

- modules/api/php/endpoints/candidate/candidate.class.inc
- modules/api/php/views/candidate.class.inc
- modules/api/php/views/visit.class.inc
- modules/api/php/views/visit/dicoms.class.inc
- modules/api/php/views/visit/flags.class.inc
- modules/api/php/views/visit/image/qc.class.inc
- modules/api/php/views/visit/images.class.inc
- modules/api/php/views/visit/instrument.class.inc
- modules/api/php/views/visit/instruments.class.inc
- modules/api/php/views/visit/qc.class.inc
Fixes bugs identified by @cmadjar while testing the API for https://github.com/aces/Loris/pull/5354
> Various api fixes

- .travis.yml
- Dockerfile.test.php7
update PHP from 7.2 to 7.3
Travis
> [Travis ] php7.2 to 7.3

- .phan/config.php
- modules/statistics/php/charts.class.inc
- modules/statistics/php/statistics_mri_site.class.inc
- php/libraries/CandIDGenerator.php
- php/libraries/File_Upload.class.inc
- php/libraries/NDB_BVL_Instrument.class.inc
- test/unittests/UtilityTest.php
This makes a few stylistic changes and fixes some comments in order
to make it easier for Phan to reason about the code and as a result
fixes the PhanMismatchReturn error type.
> Phan mismatched return

- modules/datadict/php/datadictrowprovisioner.class.inc
Somehow a branch was merged containing PHPMD errors. 
This PR fixes them. 
Until it's merged, all PRs will fail Travis.
> Fix PHPMD errors on master causing all PRs to fail Travis

- modules/conflict_resolver/test/TestPlan.md
This button was removed from the module during refactoring. This PR updates the doucmentation.
* Resolves #5410.
> [Conflict Resolver] Remove outdated reference to "Show Data" button

- test/run-php-linter.sh
- tools/assign_missing_instruments.php
> Add tools/assign_missing_instruments.php to PHPCS

- modules/behavioural_qc/test/TestPlan.md
Issues about this module's test plan raised during 22 testing round
https://github.com/aces/Loris/issues/5507
> [Behavioural QC] Change testplan to get rid of issue

- mkdocs.yml
#5849 introduced a new document. The config file was updated but contained a syntax error. This should fix the issue.
#6037 will help us find syntax errors more quickly.
> [ReadTheDocs] Fix syntax error in mkdocs.yml

- modules/electrophysiology_browser/php/electrophysiologybrowserrow.class.inc
This fixes one of the comment in the code for the electrophysiology browser that was spotted by @driusan.
> Fix one of the comment in the EEG browser module

- docs/wiki/99 - Developers/Automated Testing.md
This tool was added by #5356 but I didn't document it.
> Add PHPStan information to Automated Testing Wiki document

- jsx/Card.js
- webpack.config.js
very simple. essentially just uses the already existing Panel component but adds onclick functionality
> [React] New Card component

- .phan/config.php
- modules/examiner/php/editexaminer.class.inc
- modules/imaging_qc/php/imaging_qc.class.inc
- modules/imaging_uploader/php/file_decompress.class.inc
- modules/instrument_list/php/instrument_list_controlpanel.class.inc
- modules/server_processes_manager/ajax/ProcessStateRequestHandler.php
- modules/server_processes_manager/php/mriuploadserverprocess.class.inc
- php/libraries/FilesUploadHandler.class.inc
- php/libraries/NDB_Factory.class.inc
- src/Http/StringStream.php
This makes sure that classes really exist when we try to use them.
> Add PhanUndeclaredClassMethod to phan checks

- modules/candidate_list/test/candidate_listTest.php
- modules/create_timepoint/test/create_timepointTest.php
- test/integrationtests/LorisIntegrationTest.class.inc
- test/integrationtests/LorisIntegrationTestWithCandidate.class.inc
- test/run-php-linter.sh
The `test/` folder so far has not been checked by PHPCS (though it is checked by phan).
This PR starts the process of getting this code to be compliant with our coding standards.
> Add test/ folder to PHPCS analysis

- modules/timepoint_list/php/timepoint_list.class.inc
- php/libraries/Candidate.class.inc
- src/StudyEntities/AccessibleResource.php
Add AccessibleResource interface and implement for the Candidate class. This is used
to determine if a user can access a resource. Candidates can be accessed by a user
if they have a project and a center in common (either a RegistrationCenterID or a CenterID of a visit.)
> [Permissions] Add helper function to \Candidate class to validate accessibility

- SQL/Archive/22.0/2019-11-01-Add_data_release_permissions.sql
- SQL/Cleanup_patches/2019-12-05-Remove_lorisMenuPermissions_for_data_release.sql
- SQL/Release_patches/21.0_To_22.0_upgrade.sql
> Push v21.0.6 into 22.0 release

- docs/wiki/00 - SERVER INSTALL AND CONFIGURATION/02 - Website Configuration/Handling Large File Uploads.md
Add configuration setting in php.ini from user feedback
> [ReadTheDocs] Add additional configuration instructions for enabling large file uploads

- jsx/Tabs.js
This fixes the eslint errors in jsx/Tabs.js when running webpack.
> Fix eslint errors in jsx/Tabs.js

- modules/dashboard/README.md
Module spec readme for the Dashboard
Resolves: [this Project card](https://github.com/aces/Loris/projects/6#card-5826572)
(rebase of PR #5437)
> [Dashboard] Add readme module spec from #5437

- .github/PULL_REQUEST_TEMPLATE.md
Adding prompts to PR template -
Which documentation was updated or should be updated to accompany this code change?
Resolves #5338 
(This is a rebase of PR #5477)
> [meta] adding documentation prompts to GitHub PR template from #5477

- modules/data_release/test/data_releaseTest.php
Adds integration tests to ensure that the module loads IFF the user has the correct permissions.
* Resolves #5563
> [Data Release] Add basic integration tests

- modules/timepoint_list/README.md
Add README for timepoint_list module.
This is the last module in the GitHub project https://github.com/aces/Loris/projects/6 that does not have an open PR.
> [Timepoint List] Add README for timepoint_list module

- modules/document_repository/php/doctree.class.inc
solve :[Document Repository] Module broken, does not load https://github.com/aces/Loris/issues/6066
wrong variable name.
> [document_repository] fix can't load 

- modules/server_processes_manager/jsx/server_processes_managerIndex.js
This is the last error on my screen, and the squeaky wheel gets the grease.
> [server_processes_manager] Fix eslint errors in server_processes_managerIndex.js

- modules/examiner/php/editexaminer.class.inc
[ examiner ]  fix can't refresh page after Edit.
Header location doesn't work.
https://github.com/aces/Loris/issues/5735
> [ examiner ]  fix can't refresh page after Edit

- docker-compose.yml
update selenium 2.53 to 3.81
Travis
> selenium update

- php/installer/Installer.class.inc
This PR adds eletrophysiology related SQL in installer.
* Resolves issue #6163
> [Install] add ElectrophysiologyTables.sql to list of schemas sourced during install process

- modules/acknowledgements/php/acknowledgements.class.inc
> [Acknowledgements] Update User::singleton() declarations to facilitate unit testing

- modules/issue_tracker/test/issue_tracker_test_plan.md
- modules/user_accounts/php/edit_user.class.inc
Updated the testing plan for issue_tracker module. In regard to uploading attachments.
#6214
> [issue_tracker] Update testing plan for issue attachments

- modules/publication/jsx/projectFields.js
- modules/publication/jsx/viewProject.js
* Resolves #6308 
Filename not displayed even if the file is uploaded.
**Before Fix**
**After fix**
> [Publication] Fixing Filename not displaying Issue

- modules/user_accounts/test/TestPlan.md
* Removed line 5 from [modules/user_accounts/test/TestPlan.md](https://github.com/aces/Loris/blob/23.0-release/modules/user_accounts/test/TestPlan.md).
* Updated all following line numbers.
* Resolves #6316 
* Related to #6294 
#GSOC Applicant
CC @christinerogers
> [User Accounts] Removed line 5 from TestPlan.md

- htdocs/bootstrap/css/custom-css.css
- htdocs/js/helpHandler.js
- htdocs/main.css
- smarty/templates/main.tpl
This PR is primarily to address issue https://github.com/aces/Loris/issues/6235. However, while fixing that, I found a number of related UI/UX bugs that I also address in this PR. The scope of this PR is only the navigation bar.
Test the following steps on 23.0-release first to see current ui/ux, and then on this PR branch to see the changes.
1. Test on mobile and small screen desktop, noticing the ui/ux:
- click/unclick 'LORIS', '?', and the downturned chevron
- with the menu items showing, click on each menu item
- with the dropdown showing, click on any submenu item
2. Test on full screen desktop, noticing the ui/ux
- hover over every item on the navigation bar
- click/unclick on every item on the nav bar
- with one of the dropdowns showing, click on a submenu item
* Resolves …
> [UI] Improve navigation bar + support mobile/tablet

- modules/imaging_browser/css/imaging_browser.css
- modules/imaging_browser/php/imaging_session_controlpanel.class.inc
- modules/imaging_browser/templates/form_viewSession.tpl
- modules/imaging_browser/templates/imaging_session_controlpanel.tpl
If some instruments are not present, the imaging browser will throw an exception, I feel that this behavour is not necessary.
Issue #6219
> [imaging_browser] Imaging browser exception

- modules/imaging_uploader/php/imaging_uploader.class.inc
session ID must be null or integer, not ''.
Uploade a phantom scan 
https://github.com/aces/Loris/issues/6285
> [imaging_uploader] can't upload file with Phantom set 'yes'

- modules/document_repository/jsx/docIndex.js
fix no file under root folder
load the page, it will show all the files and all categories in the table.
compare with https://demo.loris.ca/document_repository/
https://github.com/aces/Loris/issues/6405
> [document_repository] fix no file under root folder 

- modules/document_repository/jsx/docIndex.js
> Revert "[document_repository] fix no file under root folder "

- jsx/DataTable.js
Allowed sorting by array value for the DataTable.js
2. Sort by clicking on the table header of Subproject
https://github.com/aces/Loris/issues/6326
> [Candidate list] Fixed Subproject header in candidate list sorting

- modules/bvl_feedback/jsx/react.behavioural_feedback_panel.js
Updated the propTypes of components to correspond with the correct "type" of the data being passed to the components. Updated initial state to correspond with propType of component.
1. Visit the Candidate profile 
2. View browser console for errors
edit: Make sure the sandbox value is set to 1.
```
<config>
<dev>
<sandbox>1</sandbox>
</dev>
...
</config>
```
#6380
> [Candidate profile] Browser console error cleanup

- modules/candidate_parameters/test/TestPlan.md
Adding instructions to TestPlan for the following new features:
* Date of Birth Tab (#4915)
* Date of Death Tab (#4929)
Assigning @maltheism since she is responsible for testing candidate parameters during this testing round.
> [candidate_parameters] Update TestPlan to include DoB and DoD tabs

- modules/media/test/TestPlan.md
Media test plan update
* Resolves #6336
> [media / Test Plan] Update TestPlan.md

- modules/genomic_browser/test/TestPlan.md
Refines some of the Genomic Browser Test plan 
Resolves: #4753 
Resolves: #6301 
and some of: #6297
* Does it read better for testing, @HenriRabalais ?
> [Genomic Browser] TestPlan tweak Format, Uploading, Help

- modules/document_repository/test/TestPlan.md
update test plan
10. Check that when performing a search without global filtering, the resulting files which are under the current category are shown in a list format. 
* Resolves https://github.com/aces/Loris/issues/6306
> [ document_repository]  update test plan

- modules/login/test/Reset_Password_Test_Plan.md
1. Follow the test plan and make sure it makes sense.
* Resolves #6246
> [Login] Update test plan for password resets

- SQL/0000-00-01-Permission.sql
- SQL/New_patches/2020-04-20-Rename_highlander_permission.sql
- modules/user_accounts/test/TestPlan.md
- raisinbread/RB_files/RB_permissions.sql
- raisinbread/migration.md
Changed description of super user to a clearer one
* Resolves #6355
> [permissions] Renamed description of superuser

- modules/api/test/TestPlan.md
Simple document that explain what is expected when testing the api module.
Some examples provided.
fixes aces/Loris#6322
> [API] Add TestPlan.md

- modules/new_profile/php/new_profile.class.inc
Updates the JSON Response to the new idiom which solves the type error.
1. Create a new profile. It should succeed.
* Resolves #6224
> [New Profile] Fix TypeError on candidate creation

- modules/document_repository/test/TestPlan.md
Updates the test plan to be more clear and more accurate.
This will be tested in further 23.0 testing rounds.
* Resolves #6307
> [Doc Repo] Update test plan

- modules/dicom_archive/jsx/dicom_archive.js
- modules/dicom_archive/php/dicom_archive.class.inc
Changes UI for the Sex filter to be a dropdown of possible values instead of a text field.
1. Go to DICOM Archive and filter by Sex
* Resolves #6286
> [DICOM Archive] Change Sex filter from text to dropdown

- modules/login/php/module.class.inc
­login is accessible after user login, the current PR will redirect user to the dashboard if that happens.
1. Login then check /login link
@maltheism reported the behavior
> [Login] Login control

- php/libraries/LorisForm.class.inc
Rida will address this
1. Rida will address this
* Resolves #Ridawilladdressthis
> [LorisForms] Suppresses errors

- modules/configuration/ajax/updateSubproject.php
- modules/configuration/js/project.js
- modules/configuration/js/subproject.js
- modules/configuration/templates/form_project.tpl
- modules/configuration/templates/form_subproject.tpl
Fixes a bad error message when submitting a subproject change.
Also cleans up the code.
EDIT: This also resolves #6291. I disabled the refresh entirely because it doesn't seem to provide any advantage; the changes a user makes are already reflected back to them.
1. Go to Configuration and update an existing subproject.
2. Modify recruitment target to a non-integer value or a number less than or equal to zero
3. Make sure you get an appropriate error message.
* Resolves https://github.com/aces/Loris/issues/6290
> [Configuration] Fix error messages

- modules/instruments/test/TestPlan.md
Added a testplan.md file for the instrument module
1.  Check that the instructions are
- accurate
- complete
- without syntax or grammar errors
* Resolves #  6293
> [Instruments] adding a TestPlan.md file

- modules/candidate_list/test/candidate_listTest.php
[Candidate_list] integration test - complete all skip tests, test react select dropdown menu by value not by order.
Travis
> [Candidate_list] integration test - complete skip test

- modules/media/test/TestPlan.md
1. Follow the TestPlan.md instructions for the media module.
#6439
> [media] Media module test plan does not test widgets

- modules/mri_violations/README.md
- modules/mri_violations/test/TestPlan.md
1. Follow the README.md and TestPlan.md instructions for the mri_violations module.
#6440
> [mri violations] MRI Violations module does not describe or test widgets

- CONTRIBUTING.md
Contributing.md file should be updated include a mention like For feature changes that would be included in the Release notes, be sure to modify the ChangeLog.md file.
* Resolves #6311
> [Documentation] Update Contributing.md to mention ChangeLog

- modules/instruments/README.md
- modules/instruments/php/module.class.inc
- modules/instruments/test/TestPlan.md
Adds check for `data_entry` permission before allowing access to instruments
related to #6414
> [instruments] Check for data_entry permissions

- modules/imaging_browser/test/TestPlan.md
- Updated the test plan to test the new widgets in the new Access profile module
* Resolves #6436
> [imaging_browser] Updated test plan

- smarty/templates/main.tpl
I added a container-fluid in navbar to fix the horizontal scrollbar issue in all pages of Loris.
Resolves #6530
> [Loris] Horizontal scroll

- CONTRIBUTING.md
I fixed a broken link in CONTRIBUTING.md pointing to raisinbread#exporting-rb.
Resolves #6537
> [Documentation] CONTRIBUTING.md broken link

- php/libraries/NDB_Page.class.inc
- raisinbread/instruments/NDB_BVL_Instrument_medical_history.class.inc
Modification after the merge of the PR #6395
1. Check instrument medical_history page 2 display, especially the table header.
> [raisinbread] modification after the PR #6395

- modules/imaging_qc/test/TestPlan.md
This is a **potential** test plan based on the README of the imaging_qc module. The test plan requires review from someone more familiar with the module.
* Resolves #5481
> [imaging_qc] New Test Plan

- CONTRIBUTING.md
Fix the RB broken link in CONTRIBUTING.md and added the README.md file in the link label.
* Resolves #6546
> [Documentation] CONTIBUTING.md - RB broken link fix

- modules/next_stage/test/TestPlan.md
Made file .md and added header so that it matches format of other testplans.
1.
* Resolves #6559
> [next_stage] Fix format of TestPlan

- modules/examiner/test/TestPlan.md
Some steps were added to the examiner module test plan for clarity.
* Resolves #6603
> [Documentation] Examiner Test Plan updated

- htdocs/bootstrap/css/custom-css.css
I updated a css rule to improve the visibility of some dropdown elements
* Resolves #6584
> [UI] DQT dropdown visibility issue

- modules/survey_accounts/test/TestPlan.md
The Test Plan for the survey_accounts module was updated to include additional steps (Project permissions and adding a survey). The formatting was also changed.
* Resolves #6585
> [Documentation] survey_accounts Test Plan updated

- modules/issue_tracker/help/issue.md
I created a new markdown file (modules/issue_tracker/help/issue.md) to add help text on Issue Tracker > Create/Edit Issue
* Resolves #6565
> [Documentation] Issue tracker help markdown

- htdocs/survey.php
Fixes Travis, broken by #6644.
> Fix Phan error on release branch

- modules/issue_tracker/ajax/EditIssue.php
Minor fix to decode an issue description special characters (&<>).
* Resolves #6614
> [Issue Tracker] Description and special characters decoding fix

- modules/statistics/php/stats_behavioural.class.inc
- modules/statistics/php/stats_mri.class.inc
I added a Projects permsission check in Statistics > Behavioural and Statistics >Imaging.
Side notes: the project dropdown does not produce any effect for me in Behavioural.
* Resolves #6675 
* Resolves comments made in #6659
> [Statistics] Project Permission

- modules/dashboard/test/TestPlan.md
- modules/instruments/README.md
- modules/instruments/test/TestPlan.md
1. Read the README.md for the instruments module.
2. Follow the TestPlan.md instructions for the instruments module.
#6437
> [instruments] updated README and test plan for widgets

- CHANGELOG.md
Release notes preparation for 23.0
@aces/loris_triage and @aces/loris_write feel free to suggest additional line items to this document, we will include them as necessary
@johnsaigle @driusan @cmadjar If you can check it out would be great
> [RELEASE] Release notes sanity check

- modules/mri_violations/test/TestPlan.md
The correct permission here is the `ownsites` permission, not edit.
* Resolves #6574
> [MRI Violations] Correct name of permission in test plan

- modules/issue_tracker/test/issue_tracker_test_plan.md
Minor changes to the test plan after my observations during manual testing.
* Replace #6599
* Resolves #6597
> [Documentation] Issue Tracker test plan update

- modules/user_accounts/php/edit_user.class.inc
- php/libraries/User.class.inc
Adds a function to determine whether a user can access another user.
See #6093
> [User] Add helper function to \User class to validate accessibility

- modules/imaging_uploader/README.md
> [Imaging Uploader] Mention in README that LORIS-MRI is required

- php/libraries/User.class.inc
There was a PHPCS issue in https://github.com/aces/Loris/pull/6180 but it was merged
> Fix PHPCS error on main branch

- modules/candidate_list/php/validateids.class.inc
- modules/candidate_list/test/Feedback_BVL_Test_Plan.md
- modules/document_repository/php/doctree.class.inc
- modules/document_repository/php/files.class.inc
- modules/imaging_browser/test/TestPlan.md
- modules/server_processes_manager/php/serverprocessesmonitor.class.inc
- php/libraries/NDB_Client.class.inc
- src/Data/Filter.php
- src/Middleware/Authenticator.php
I replaced all occurrences of iff found in master by only if .
Some occurrence are in 23.0-release and will need expansion after the final release.
* Resolves #6420
> [Documentation] iff expansion for clarity

- php/libraries/NDB_BVL_Instrument.class.inc
As the comment suggests, the block of code seems to be useless and was removed.
* Resolves #6481
> Instrument Cleanup

- php/libraries/Utility.class.inc
- test/unittests/UtilityTest.php
Adds a utility function for intelligently joining paths. See linked ticket for more details.
* Resolves #5873
> [Utility] Add pathJoin() function

- test/unittests/Database_Test.php
This PR fixes the failing unit test that is causing Travis to fail on the master branch. This was caused by a change made in merged PR #6553.
> [Test] Fix failing unit test causing Travis fail

- .eslintrc.json
- jsx/DataTable.js
- jsx/DynamicDataTable.js
- jsx/Filter.js
- jsx/FilterForm.js
- jsx/Form.js
- jsx/PaginationLinks.js
- jsx/Panel.js
- jsx/StaticDataTable.js
- webpack.config.js
This PR:
* Fixes all max-len warnings for the core files
* Updates the eslint max-len rule to ignore strings
* Updates the eslint rules to switch the level of the max-len rule to error for the core files
* Updates webpack.config.js to log warnings and errors only
* Resolves #6750 (partially)
> [eslint] Fix max-len warnings for core files

- .eslintrc.json
- modules/battery_manager/jsx/batteryManagerIndex.js
This PR:
* resolves all eslint no-console warnings
* raises no-console severity to error
* resolves #6750 (partially)
> [eslint] Fix console

- modules/api/php/views/projects.class.inc
- modules/behavioural_qc/ajax/GetCandidates.php
- modules/behavioural_qc/php/behavioural_qc.class.inc
- php/libraries/Candidate.class.inc
- php/libraries/Utility.class.inc
- test/unittests/UtilityTest.php
* Moves some functions out of Utility into classes that actually use them
* Deletes unnecessary comments
* Fixes incorrect comments
1. For the most part this should be covered by integration/unit tests
2. use `git grep $functionname` to make sure deleted functions are not used elsewhere in the codebase.
* Resolves some points from #4428
> [Utility] Cleanup

- docs/wiki/00_SERVER_INSTALL_AND_CONFIGURATION/01_LORIS_Install/Ubuntu/README.md
UNIX permissions were changed in #5057. This updates the Ubuntu wiki to match what's in the main README.
* Resolves #5324 
* Resolves #6181 (new permissions will be included and documented)
> Add new UNIX permissions to Ubuntu install document

- modules/battery_manager/test/TestPlan.md
Removed an unnecessary testing instruction since site is a dropdown.
* Resolves #6685
> [Battery Manager] Test plan update

- php/libraries/NDB_BVL_Instrument.class.inc
> fix bug in #6179

- test/run-php-linter.sh
- tools/populate_visit_windows.php
> [Tools] Enable PHPCS for populate_visit_windows.php

- .eslintrc.json
- htdocs/js/advancedMenu.js
- htdocs/js/filterControl.js
- htdocs/js/instrument_controlpanel_swaldeletedata.js
- htdocs/js/instrument_form_control.js
- htdocs/js/jquery.csv.js
- jsx/Breadcrumbs.js
- jsx/Card.js
- jsx/DataTable.js
- jsx/DynamicDataTable.js
- jsx/Filter.js
- jsx/FilterForm.js
- jsx/FilterableDataTable.js
- jsx/Form.js
- jsx/Markdown.js
- jsx/Modal.js
- jsx/MultiSelectDropdown.js
- jsx/PaginationLinks.js
- jsx/Panel.js
- jsx/ProgressBar.js
- jsx/StaticDataTable.js
- jsx/Tabs.js
- jsx/TriggerableModal.js
This PR:
* resolves all eslint js-doc warnings for the core files
* raises js-doc severity to error for the core files
```
rm -R nodes_modules/
npm install
```
```
make checkstatic
```
No warnings `js-doc` should be printed.
```
git checkout 'one-modiifed file'
make checkstatic
```
An error `js-doc` should be printed.
* resolves #6750 (partially)
> [eslint] Fix core js-doc warning

- modules/conflict_resolver/test/conflict_resolverTest.php
finish test function [from unresolved to resolve]
Travis
> [conflict resolver] finish test function [from unresolved to resolve]

- test/integrationtests/BatteryLookup_Test.php
- test/integrationtests/Login_Test.php
- test/run-php-linter.sh
> Add PHPCS to core integration tests 

- php/installer/Installer.class.inc
> installer error fix

- modules/create_timepoint/php/create_timepoint.class.inc
- modules/new_profile/php/new_profile.class.inc
- php/libraries/Utility.class.inc
This is the recreation of the #5892, which was wrongly operated under the master branch, then somehow closed, in a panic I thought it was merged. Sorry.
>  [new_profile/create_timepoint] code improvement

- modules/login/php/requestaccount.class.inc
- modules/login/test/Request_Account_test_plan.md
- smarty/templates/email/request_account.tpl
When a user requests an account, an email will be sent to the study admin.
---
---
1. Follow the new steps added to the test plan in this PR.
* Resolves #5943
> Send email to admin upon account request

- test/run-php-linter.sh
- tools/manage_modules.php
> [Tools] Enable PHPCS for manage_modules.php 

- .eslintrc.json
- modules/acknowledgements/jsx/acknowledgementsIndex.js
- modules/brainbrowser/jsx/Brainbrowser.js
- modules/configuration/jsx/SubprojectRelations.js
- modules/datadict/jsx/dataDictIndex.js
- modules/dicom_archive/jsx/dicom_archive.js
- modules/help_editor/jsx/help_editor.js
- modules/imaging_qc/jsx/imagingQCIndex.js
- modules/module_manager/jsx/modulemanager.js
- modules/new_profile/jsx/NewProfileIndex.js
- modules/survey_accounts/jsx/surveyAccountsIndex.js
* js-doc rule has been raised to error on all files except the one already lacking js-doc comments (to be fixed later). This will ensure that all future modules will conform to the rule.
* max-len has been raised to error on all files since all problem has been solved in #6756 and #6761
* 0 has been replaced by it's more verbose "off" equivalent.
* Resolves #6750
> [eslint] Fix .eslint rules

- modules/survey_accounts/php/addsurvey.class.inc
- modules/survey_accounts/test/survey_accountsTest.php
In another PR I encountered an issue with these integration tests. 
Basically it's required to submit an instrument and a visit label in this form but the test was not actually checking for this.
* First discovered in #5796. This PR blocks that one.
> [Survey Accounts] Make integration test more robust

- test/run-php-linter.sh
- test/unittests/Database_Test.php
> Add phpcs to Database_Test.php

- test/run-php-linter.sh
- tools/DB_date_zeros_removal.php
> [Tools] Enable PHPCS for DB_date_zeros_removal.php

- test/run-php-linter.sh
- tools/config_to_db.php
> [Tools] Enable PHPCS for config_to_db.php

- test/run-php-linter.sh
- tools/detect_conflicts.php
> [Tools] Enable PHPCS for detect_conflicts.php

- modules/dataquery/README.md
Small tweak to improve the phrasing in the DQT README.md file. 
Clarifies the steps which are optional and the scope when they are required.
* Resolves #6469
> [Documentation] DQT readme optional steps clarification

- modules/imaging_browser/php/imagingbrowserrowprovisioner.class.inc
Pull bug fix from 22.0.3 forward into the 23 release branch.
> Pull 22.0.3 into 23.0.x

- modules/imaging_browser/php/viewsession.class.inc
- modules/imaging_browser/test/TestPlan.md
Changed check from project from the candidate's registration project to the session's project.
solves https://github.com/aces/Loris/issues/6872
> [Imaging_browser] Access to view session based on session project

- SQL/Release_patches/22.0_To_23.0_upgrade.sql
- jsx/Form.js
- modules/battery_manager/jsx/batteryManagerIndex.js
- modules/battery_manager/php/test.class.inc
- modules/battery_manager/php/testendpoint.class.inc
- modules/candidate_parameters/php/module.class.inc
- modules/electrophysiology_browser/php/sessions.class.inc
- modules/imaging_browser/php/imagingbrowserrowprovisioner.class.inc
- modules/imaging_browser/php/viewsession.class.inc
- modules/imaging_browser/test/TestPlan.md
- modules/issue_tracker/ajax/EditIssue.php
- modules/issue_tracker/jsx/IssueForm.js
- modules/issue_tracker/jsx/issueTrackerIndex.js
- modules/issue_tracker/php/issue_tracker.class.inc
- modules/issue_tracker/php/issuerowprovisioner.class.inc
- modules/issue_tracker/test/issue_tracker_test_plan.md
- modules/module_manager/jsx/modulemanager.js
- modules/statistics/php/statistics_dd_site.class.inc
- modules/statistics/php/statistics_site.class.inc
- modules/statistics/php/stats_behavioural.class.inc
- modules/timepoint_list/php/timepoint_list_controlpanel.class.inc
- modules/timepoint_list/templates/menu_timepoint_list.tpl
- modules/timepoint_list/templates/timepoint_list_controlpanel.tpl
- modules/timepoint_list/test/TestPlan.md
- modules/user_accounts/php/edit_user.class.inc
- php/libraries/Module.class.inc
- php/libraries/NDB_Page.class.inc
- php/libraries/Settings.class.inc
Merge latest release into the main dev branch.
Conflicts:
modules/imaging_browser/php/viewsession.class.inc
modules/issue_tracker/ajax/EditIssue.php
modules/issue_tracker/php/issue_tracker.class.inc
modules/module_manager/jsx/modulemanager.js
modules/statistics/php/statistics_site.class.inc
modules/statistics/php/stats_behavioural.class.inc
> Merge v23.0.2 into main

- modules/imaging_browser/.gitignore
- modules/instruments/.gitignore
> [meta] add compiled JS files to gitignore

- test/run-php-linter.sh
- tools/CouchDB_Import_MRI.php
> [Tools] Enable PHPCS for CouchDB_Import_MRI.php

- modules/user_accounts/jsx/userAccountsIndex.js
- modules/user_accounts/php/edit_user.class.inc
- modules/user_accounts/templates/form_edit_user.tpl
- modules/user_accounts/test/user_accountsTest.php
- php/libraries/NDB_Page.class.inc
Improvements for the Add/Edit user form:
* add a red asterisk next to the required fields
* toggle `Generate new password`:
- clear the new/confirm password fields if on
- enable/disable the new/confirm password fields 
- toggle the required marker on the new/confirm password fields
- toggle Send email to user 
* toggle `Make user name match email address` :
- clear the User name field if on
- enable/disable the User name field
- toggle the required marker on the User name field
Solved warnings/fatal errors due to type errors in `edit_user.class.inc` (seems to happen in test mode only).
> [User Accounts] Form improvements

- test/unittests/NDB_BVL_Instrument_Test.php
The unit tests for `NDB_BVL_Instrument` that were merged with main in PR #6819 were causing Travis to fail. This PR fixes those errors.
The reason it failed Travis was because the changes made in merged PR #5352 were not added to the testing PR. These changes caused it to fail Travis but were not flagged before.
1. Check Travis
> [Test] Fixing unittests causing Travis failure

- test/run-php-linter.sh
- tools/CouchDB_Confirm_Integrity.php
> [Tools] Enable PHPCS for CouchDB_Confirm_Integrity.php

- test/run-php-linter.sh
- tools/CouchDB_Import_Instruments.php
> [Tools] Enable PHPCS for CouchDB_Import_Instruments.php

- modules/new_profile/test/TestPlan.md
Adjust test plan to reflect new behavior.
see: https://github.com/aces/Loris/pull/6156
> adjust test plan to new behavior

- test/run-php-linter.sh
- tools/CouchDB_MRI_Importer.php
> [Tools] Enable PHPCS for CouchDB_MRI_Importer.php

- modules/survey_accounts/php/addsurvey.class.inc
- modules/survey_accounts/test/TestPlan.md
- fix testplan
- fix type in selectBattery
This is 1 of N because it do not solve the 404 Not Found when creating a new survey.
> [Survey] Fix survey module 1 of N  

- modules/bvl_feedback/ajax/bvl_panel_ajax.php
- modules/bvl_feedback/ajax/react_get_bvl_threads.php
- modules/bvl_feedback/jsx/react.behavioural_feedback_panel.js
Fixes:
- a 500 error encountered when submitting a feedback (sessionID type must be of type SessionID or NULL) 
- a minor console error (wrong type for onClickOpen)
* Resolves #7029
> [bvl_feedback] SessionID fix

- modules/datadict/test/TestPlan.md
* Resolves #6966  (Reference the issue this fixes, if any.)
> [datadict] Edit description

- modules/user_accounts/test/TestPlan.md
* Resolves #6954  (Reference the issue this fixes, if any.)
> [User Accounts] Update TestPlan

- modules/login/test/Request_Account_test_plan.md
* Resolves #6960  (Reference the issue this fixes, if any.)
> [login] Test instructions

- modules/login/test/Request_Account_test_plan.md
* Resolves #6963 (Reference the issue this fixes, if any.)
> [login] Notify check box

- modules/media/ajax/FileUpload.php
- modules/media/jsx/mediaIndex.js
- modules/media/jsx/uploadForm.js
Solves #6949 
1. Visit media module
2. Upload file
3. Go visit the table and see new data in table
* Resolves #6949
> [media] Update datatable upon file upload without having to refresh

- modules/media/test/TestPlan.md
* Resolves #6948  (Reference the issue this fixes, if any.)
> [media] Update uploaded form TestPlan

- modules/user_accounts/test/TestPlan.md
* Resolves #6974  (Reference the issue this fixes, if any.)
> [user_accounts] Resolve Conflicting Steps in TestPlan

- test/run-php-linter.sh
- tools/CouchDB_Import_RadiologicalReview.php
> [Tools] Enable PHPCS for CouchDB_Import_RadiologicalReview.php

- modules/login/js/login_helper.js
- modules/login/php/login.class.inc
- modules/login/templates/form_login.tpl
- modules/login/templates/form_passwordexpiry.tpl
- modules/my_preferences/.gitignore
- modules/my_preferences/js/my_preferences_helper.js
- modules/my_preferences/php/my_preferences.class.inc
- modules/my_preferences/templates/form_my_preferences.tpl
- modules/user_accounts/.gitignore
- modules/user_accounts/js/edit_user_helper.js
- modules/user_accounts/php/edit_user.class.inc
- modules/user_accounts/templates/form_edit_user.tpl
Add password visibility buttons on the password fields when a user is requested to change his password (account request and password expiry).
Resolves #6961
> [Login] Password expiry - Password visibility button

- modules/battery_manager/test/TestPlan.md
> [Battery Manager] Testplan update

- README.md
- docs/wiki/00_SERVER_INSTALL_AND_CONFIGURATION/01_LORIS_Install/CentOS/README.md
- docs/wiki/00_SERVER_INSTALL_AND_CONFIGURATION/01_LORIS_Install/Ubuntu/README.md
> Update NodeJS version

- jsx/Modal.js
- modules/battery_manager/jsx/batteryManagerIndex.js
- modules/battery_manager/php/testendpoint.class.inc
Fixes bugs validation bugs and console errors found in battery manager during the testing round.
* Resolves #6957
* Resolves #6958 
* Resolves #6955
> [battery_manager] Fixing testing bugs

- .travis.yml
Fix composer travis issue on 23. replica of #7113
> [TRAVIS] fix composer issue for 23

- README.md
It does not work with "or higher", composer 2 only works on the
main branch.
> Update documented version of composer in README for 23 release

- README.md
Updates README.md System Requirements section about php requirement
> [readme.md] Update System Requirements for PHP

- .eslintrc.json
- modules/dataquery/jsx/react.app.js
- modules/dataquery/jsx/react.fieldselector.js
- modules/dataquery/jsx/react.filterBuilder.js
- modules/dataquery/jsx/react.paginator.js
- modules/dataquery/jsx/react.sidebar.js
- modules/dataquery/jsx/react.tabs.js
- package.json
- webpack.config.js
It's the end of an amazing journey, thousands lines of warnings are finally gone for good.
Also edited webpack.config.js to get rid of:
```
WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/configuration/mode/
```
Resolves #6750
> [dataquery] Eslint fixes

- modules/README.md
- test/unittests/CandidateTest.php
- test/unittests/Database_Test.php
- test/unittests/LorisForms_Test.php
- test/unittests/NDB_BVL_Instrument_LINST_ToJSON_Test.php
- test/unittests/NDB_BVL_Instrument_Test.php
- test/unittests/NDB_Menu_Filter_Test.php
- test/unittests/SinglePointLoginTest.php
fixing phpunit warning, fixing the unittest case for phpunit 9.4.
passing git actions
> [git actions] fixing warning and error for phpunit 9.4.

- test/run-php-linter.sh
- tools/single_use/cleanup_mri_tables_for_19-0_release.php
- tools/single_use/config_to_db.php
Migrate tools/config_to_db.php and tools/cleanup_mri_tables_for_19-0_release.php in tools/single_use/.
> [Tools] Cleanup - single_use migration

- .github/workflows/loristest.yml
- README.md
- composer.lock
- php/libraries/CouchDB.class.inc
- php/libraries/LorisForm.class.inc
- php/libraries/NDB_BVL_Battery.class.inc
- php/libraries/TimePoint.class.inc
> Push 23.0 release into main

- modules/dicom_archive/jsx/dicom_archive.js
- modules/dicom_archive/php/dicomarchiveanonymizer.class.inc
- modules/dicom_archive/php/dicomarchiverowprovisioner.class.inc
The logic of the HIDDEN patient name was incorrect in the DICOM archive menu. This fixes the logic.
* Resolves #7208
> [DICOM archive] Fix patient name and patient ID hidden logic of the menu filter

- raisinbread/instruments/bmi.linst
- raisinbread/instruments/bmi.rules
- raisinbread/instruments/bmi.score
> [RB/BMI] Do not call the imperial system the "standard system"

- modules/conflict_resolver/test/TestPlan.md
Formatting issues (list) were fixed.
> [Conflict resolver] Test plan update

- docker-compose.yml
Change the path for fake data-raisinbread
> correct data-raisinbread path

- modules/candidate_parameters/test/TestPlan.md
Removing outdated step from test plan which refers to a table with candidate information that is no longer in candidate_parameters
* Resolves #6989
> [candidate_parameters] Update test plan to remove DOB and Sex info step

- package.json
update react react-dom react-markdown
1. npm install
2. npm run compile
3. browser loris
4. visit the help info of each module
https://github.com/aces/Loris/issues/7109
> [dependencies] update react react-dom react-markdown

- modules/battery_manager/test/TestPlan.md
> [battery_manager] test plan remove tabs

- SQL/Archive/21.0/Cleanup/2020-12-18-Remove_survey_emails.sql
- modules/survey_accounts/jsx/surveyAccountsIndex.js
- modules/survey_accounts/php/addsurvey.class.inc
- modules/survey_accounts/php/survey_accounts.class.inc
> Push 21.0.7 into 22.0 release

- SQL/Archive/21.0/Cleanup/2020-12-18-Remove_survey_emails.sql
- modules/survey_accounts/jsx/surveyAccountsIndex.js
- modules/survey_accounts/php/addsurvey.class.inc
> Push v22.0.4 into 23.0 release

- .eslintrc.json
- modules/datadict/jsx/dataDictIndex.js
> [Datadict] jQuery cleanup

- jsx/DynamicDataTable.js
Solves eslint errors for no-extra-semi and useful for removing the off found in this PR: https://github.com/aces/Loris/pull/7137
> [eslint] Unnecessary semicolon  no-extra-semi

- jsx/StaticDataTable.js
Solves eslint errors for no-invalid-this and useful for removing the off found in this PR: #7137
> [eslint] Unexpected 'this'  no-invalid-this

- composer.json
- composer.lock
- src/Middleware/ExceptionHandlingMiddleware.php
- test/integrationtests/LorisIntegrationTest.class.inc
Update phan to the latest version.. there were only 2 errors that had to be fixed:
```
src/Middleware/ExceptionHandlingMiddleware.php:51 PhanPossiblyUndeclaredVariable Variable $status is possibly undeclared
test/integrationtests/LorisIntegrationTest.class.inc:593 PhanPossiblyUndeclaredVariable Variable $e is possibly undeclared
```
> [phan] Upgrade phan to v4.x

- src/Middleware/UserPageDecorationMiddleware.php
> [Middleware/UserPageDecorationMiddleware] add page !==null

- modules/my_preferences/test/my_preferencesTest.php
- test/phpunit.xml
The my_preferences module is not currently in the list of modules for which the test suite is run. The module seems to have tests, they should be run.
> Add my_preferences module to list of tests to run

- modules/data_release/jsx/addPermissionForm.js
- modules/data_release/jsx/uploadFileForm.js
- modules/help_editor/js/help_editor_helper.js
- modules/instrument_manager/jsx/uploadForm.js
- modules/media/jsx/uploadForm.js
Following #7323, this PR fixes all the callback regressions introduced by #6195.
> Fix swal callback not working (#6195 regression)

- modules/publication/ajax/FileUpload.php
- smarty/templates/email/notifier_publication_edit.tpl
- smarty/templates/email/notifier_publication_review.tpl
- smarty/templates/email/notifier_publication_submission.tpl
add notification funtion for upload , review and submission.
upload , review or submit a proposal, then user who has the notification services will get the email.
https://github.com/aces/Loris/issues/7204
>  [publication] fix notification

- docs/wiki/99_Developers/Help_Style_Guide.md
> Help Style Guide - Fix broken image link

- test/run-php-linter.sh
- tools/generate_tables_sql.php
- tools/generate_tables_sql_and_testNames.php
> [Tools] Enable PHPCS for generate_tables_sql_and_testNames.php

- Dockerfile.test.php7.debug
- docker-compose.yml
- modules/create_timepoint/test/create_timepointTest.php
- modules/survey_accounts/test/survey_accountsTest.php
- test/phpunit.xml
Fixes for problems found while investigating integration test failure for #7316
> [Tests] Dockerized tests fix

- modules/instrument_list/php/instrument_list.class.inc
A string was given and this change resolves it.
> [libraries/BVL_Feedback_Panel] $sessionID must be type SessionID

- modules/imaging_browser/php/mrinavigation.class.inc
Fix for
```
PHP Fatal error:  Uncaught TypeError: Typed property LORIS\\imaging_browser\\MRINavigation::$_FilteredSessionList must be array, null used in /var/www/html/loris-core/modules/imaging_browser/php/mrinavigation.class.inc:48
```
> [Imaging Browser] Fix nullable type fatal error

- modules/statistics/php/stats_mri.class.inc
add the quotation marks for the variable as array key.
fix issue 
https://github.com/aces/Loris/issues/7341
> [statistics] fix "Illegal offset type" 

- .github/workflows/loristest.yml
> [Travis] add php extension

- modules/imaging_browser/php/module.class.inc
- php/libraries/Module.class.inc
This extracts the imaging browser data dictionary portion of
PR#6936 and puts it into a separate PR for reviewability.
> [imaging_browser] Add Data Dictionary to imaging browser

- .github/workflows/loristest.yml
Fix a build problem under php7.3 on v23.0 (see https://github.com/aces/Loris/pull/7397#issuecomment-801271969 for reference).
> [Test] Fix broken build - php-ast

- htdocs/feedback_mri_popup.php
- php/libraries/FeedbackMRI.class.inc
Fix type errors thrown when opening the Visit Level
popup in the imaging browser.
Fixes #7405
> [imaging_browser] Fix type errors in visit MRI popup

- test/unittests/NDB_BVL_Instrument_Test.php
Fix warnings and remove the invalid test function in unit tests.
> [Unit Test] fix warnings

- php/libraries/NDB_BVL_Instrument.class.inc
added sorting to the Instrument class functions to reduce differences with old deprecated functions.
> [Instrument] add sorting to getInstrumentNamesList()

- htdocs/main.css
- modules/user_accounts/php/edit_user.class.inc
- modules/user_accounts/templates/form_edit_user.tpl
> [User accounts] Fix edit user layout

- test/unittests/NDB_BVL_Instrument_Test.php
> [git actions] fix unit test 

- tools/single_use/Cleanup_Special_Chars_Document_Repository.php
- fixes script from this PR: #7383
* See comment from #7386
> [document_repository] Fix special characters script

- modules/electrophysiology_browser/test/electrophysiologyBrowserTest.php
Re-enable and fix skipped tests in #PR 7345 before we forget about them :)
> [EEG Browser] Integration tests fix

- modules/document_repository/jsx/editFormIndex.js
- modules/document_repository/php/files.class.inc
fixing the file id method and handle put method to edit a file.
upload a file and edit it. 
https://github.com/aces/Loris/issues/7002
> [Document Repository]  fix Unable to edit an uploaded file issue #7002

- modules/behavioural_qc/templates/form_behavioural_qc.tpl
> [Behavioural QC] Typo fix in title

- SQL/0000-00-03-ConfigTables.sql
- SQL/New_patches/2021-07-19-log_level.sql
- modules/candidate_list/test/candidate_listTest.php
- modules/configuration/php/configuration.class.inc
- modules/configuration/templates/form_configuration.tpl
- modules/instrument_list/php/instrument_list.class.inc
- modules/instruments/php/module.class.inc
- modules/timepoint_list/php/timepoint_list.class.inc
- php/libraries/Database.class.inc
- php/libraries/LogSettings.class.inc
- php/libraries/Module.class.inc
- php/libraries/NDB_Config.class.inc
- php/libraries/NDB_Factory.class.inc
- php/libraries/NDB_Page.class.inc
- raisinbread/RB_files/RB_Config.sql
- raisinbread/RB_files/RB_ConfigSettings.sql
- src/Log/ErrorLogLogger.php
- src/Middleware/ExceptionHandlingMiddleware.php
- src/Router/BaseRouter.php
- test/test_instrument/test_instrumentTest.php
- test/unittests/NDB_PageTest.php
This adds a PSR3 logger implementation to LORIS. This  implements a single
logger type, ErrorLogLogger, which logs to the web server's standard error_log
based on the current log level verbosity configuration in the LORIS config
module.
Three types of logs are implemented in this PR, the verbosity: 1. Database logging
2. HTTP Request logging and 3. Exception logging
> Add PSR3 Logger

- raisinbread/README.md
* Resolves #6935  (Reference the issue this fixes, if any.)
> [docs] Improve RaisinBread Docs

- modules/statistics/php/stats_demographic.class.inc
> Stats mini fix

- modules/candidate_list/test/candidate_listTest.php
- modules/candidate_profile/test/candidate_profileTest.php
- modules/genomic_browser/test/genomic_browserTest.php
- test/integrationtests/LorisIntegrationTest.class.inc
- test/phpunit.xml
> [Travis] fix the test error in main branch

- CHANGELOG.md
This adds my PRs to the CHANGELOG.md that seemed to be missing.
> [Rida] Add CHANGELOG.md entries

- modules/media/ajax/FileUpload.php
- modules/media/php/media.class.inc
- modules/media/php/mediafileprovisioner.class.inc
- php/libraries/NDB_BVL_Instrument_LINST.class.inc
The field instrument in media (Upload) displays the Test_name instead of the Full_name. This PR fixes the issue.
Per @ridz1208's comment, this PR also changes the way the full name is queried in the rest of the module to use the instrument getFullName()'s  method.
> [Media] Display instrument name

- CHANGELOG.md
- test/integrationtests/LorisIntegrationTest.class.inc
> [release ATTN Rida] Add to changelog

- tools/install.sh
https://github.com/aces/Loris/issues/7096
fix centos group issue on project/
install Loris 
https://acesloris.readthedocs.io/en/latest/docs/wiki/00_SERVER_INSTALL_AND_CONFIGURATION/01_LORIS_Install/Ubuntu/README.html
or https://acesloris.readthedocs.io/en/latest/docs/wiki/00_SERVER_INSTALL_AND_CONFIGURATION/01_LORIS_Install/CentOS/README.html
> [install.sh] fix could not write config.xml file to the project/

- modules/create_timepoint/jsx/createTimepointIndex.js
Solves issue: https://github.com/aces/Loris/issues/7728
1. Visit create_timepoint module
2. Test for the bug
* Resolves #7728
> [create_timepoint] First visit in list automatically selected

- src/Middleware/UserPageDecorationMiddleware.php
add missing element
1. login the dashboard page, and find the user name on the top-right menubar.
*https://github.com/aces/Loris/issues/7792
> [Menu] Username not appearing in menu bar - fix

- modules/data_release/test/TestPlan.md
Fix permission name in test plan to match new name in database
> [Data Release] Small testplan modification

- modules/dqt/css/dataquery.css
- modules/dqt/js/arrayintersect.js
- modules/dqt/jsx/react.app.js
- modules/dqt/jsx/react.filterBuilder.js
- modules/dqt/jsx/react.savedqueries.js
- modules/dqt/jsx/react.tabs.js
- modules/dqt/php/dqt.class.inc
- package.json
Solves issue: https://github.com/aces/Loris/issues/7684
1. Go to 'Data Query Tool (Beta)' module
2. Click on 'Load Existing Query' and compare 'User' and 'Shared' saved queries.
* Resolves #7684
> [dqt] Saved queries show fields for private but not for public queries

- php/libraries/NDB_BVL_Instrument.class.inc
Merging latest release, No real changes since functionality was altered in 24 already
> Push v23.0.9 into main

- raisinbread/instruments/bmi.score
updating scoring code to latest standards
> [RB] Fix BMI scoring code

- modules/battery_manager/README.md
This PR fixes the README (bad grammar) for module battery manager.
Fixes #7687
> [Battery Manager] Fix README

- modules/conflict_resolver/test/TestPlan.md
Updated test plan with correct list of automated vs manual testing. 
* Resolves #7700
> [conflict_resolver] Updating automated test list in Test Plan

- modules/statistics/php/statistics_site.class.inc
Fixes broken links in statistics module.
1. See issue
* Resolves #7839
> [Statistics] "View details" link does not work in Data Entry Statistics and Double Data Entry Statistics table

- src/Middleware/ExceptionHandlingMiddleware.php
This fixes the ExceptionHandlingMiddleware to also catch PHP Fatal
errors. Fatal PHP errors are things like running out of memory or
type errors, which do not throw exceptions. We register a shutdown
handler to try and catch these.
1. Generate a PHP Fatal error (such as a type error) from a module in LORIS
2. Verify that it gets logged in the Apache error log and isn't silently discarded.
> [Core] Log PHP Fatal errors

- .github/workflows/loristest.yml
- Dockerfile.test.php7
- Dockerfile.test.php8
- docker-compose.yml
add  comma into PHP version array 
remove php7 
add php8
Travis
> [gitactions] fix php version 

- modules/new_profile/jsx/NewProfileIndex.js
Updates the sweet alert error message to show the error for the user.
1. See issue instructions
* Resolves #7900
> [New Profile] No user feedback on wrongly formatted PSCID

- modules/electrophysiology_browser/test/electrophysiologyBrowserTest.php
- modules/help_editor/test/help_editorTest.php
- modules/instrument_builder/test/instrument_builderTest.php
- modules/my_preferences/test/my_preferencesTest.php
- modules/next_stage/test/next_stageTest.php
- modules/user_accounts/test/user_accountsTest.php
- test/integrationtests/LorisIntegrationTest.class.inc
- test/test_instrument/test_instrumentTest.php
fix the random failure in the git actions
> [git action] fix test

- modules/issue_tracker/jsx/IssueForm.js
- modules/issue_tracker/php/edit.class.inc
Solves unnecessary error message when making a comment in issue_tracker module without uploading an attachment. Also solves error messages not being displayed to user and solves form value wrongly being cleared causing confusion for user.
1. Checkout PR
2. Make comment in issue tracker module
* Resolves #7846
> [issue_tracker] Error given when updating issue

- modules/document_repository/test/TestPlan.md
> [document_repository] Update TestPlan

- modules/instrument_list/help/instrument_list.md
- modules/instrument_list/test/TestPlan.md
> [instrument_list] Update Test plan & Help

- modules/candidate_list/test/candidate_listTest.php
add test scan done link test 
add subproject filter test.
Travis
[candidate_list] Missing automated tests #7644
> [candidate_test ] add missing test 

- modules/create_timepoint/test/create_timepointTest.php
- modules/dicom_archive/test/dicom_archiveTest.php
- modules/document_repository/test/document_repositoryTest.php
- modules/examiner/test/ExaminerTest.php
- modules/help_editor/test/help_editorTest.php
- modules/imaging_browser/test/imaging_browserTest.php
- modules/issue_tracker/test/Issue_TrackerTest.php
- modules/new_profile/test/new_profileTest.php
- modules/server_processes_manager/test/server_processes_managerTest.php
rewrite skip test funtions
Travis
> [test] remove skip test

- modules/dqt/ajax/saveQuery.php
- modules/dqt/js/arrayintersect.js
- modules/dqt/jsx/react.app.js
- modules/dqt/jsx/react.filterBuilder.js
- modules/dqt/jsx/react.tabs.js
- modules/dqt/php/dqt.class.inc
- tools/CouchDB_Import_Demographics.php
Solution for the following bugs:
* Fixes the unable to load a saved query bug. One of the functions needed wasn't being imported in the react.app.js
* Fixes page error when trying to filter on select elements.
* Fixes saving query failure. 
* Fixes Deleting all filters causes query page to fail
* Fixes Filters - Project menu breaks if one of them has apostrophe in the title
2. make clean && make dev
3. visit DQT module
4. load query
* Resolves #7939
* Resolves #7936
* Resolves #7935
* Resolves #5124
> [dqt] Unable to Load a Saved Query and Other bugs

- php/libraries/NDB_BVL_Instrument.class.inc
> Push v23.0.10 into main

- php/libraries/NDB_BVL_Instrument.class.inc
> Push v23.0.10 into v24.0.0

- CHANGELOG.md
- php/libraries/NDB_BVL_Instrument.class.inc
* Resolves issue discussed in comments of #7995
> [NDB_BVL_Instrument] Fix null recognition of getSessionID

- .github/workflows/loristest.yml
fix cache composer error in git actions.
> [Git actions] error fix - 24.0-release

- modules/issue_tracker/test/issue_tracker_test_plan.md
> [issue_tracker] update test plan

- modules/dqt/test/TestPlan.md
> [DQT] Testplan update

- modules/user_accounts/test/TestPlan.md
> [User Accounts] Testplan update

- modules/behavioural_qc/test/TestPlan.md
Multiple changes to the format/content of the testplan
***NOTE:** To whomever is testing this. The module currently has a bug where data returned is NOT filtered for the user's sites so the module in its current state will fail this test plan but that issue is being resolved in a different PR.*
* Resolves #7193
> [behavioural_qc] Testplan revamp

- modules/configuration/test/TestPlan.md
Removed some unrealistic expectations and redundant instructions
> [configuration] Test plan update

- CHANGELOG.md
- modules/server_processes_manager/php/server_processes_manager.class.inc
Removes lines that are causing timeout & not accomplishing anything as discussed in #8039
1. Load server_processes_manager module
* Resolves #8039
> [server_processes_manager] Fix timeout

- tools/data_integrity/fix_candidate_age.php
- tools/data_integrity/score_instrument.php
- tools/lorisform_parser.php
Fix some function calls with incorrect arguments in:
- data_integrity/fix_candidate_age.php
- data_integrity/score_instrument.php
- lorisform_parser.php
> [tools] Fix passing of LorisInstance to some tools

- .github/workflows/loristest.yml
fix [gitactions] compose error on 23.0-release
> fix [gitactions] compose error on 23.0-release

- modules/instrument_manager/README.md
- modules/instrument_manager/test/TestPlan.md
- test/instruments/test_all_fields.linst
> [instrument_manager] Update docs

- README.md
- docs/wiki/01_STUDY_PARAMETERS_SETUP/02_Clinical_Instruments/02_instrument_format/PHP_instrument.md
updating wiki to include the LorisFormDictionaryImpl trait and updating the version for the release
> [WIKI] datadict trait and version update

- php/libraries/NDB_BVL_Instrument_LINST.class.inc
> Push v23.0.11 into 24.0 release

- README.md
- docs/wiki/01_STUDY_PARAMETERS_SETUP/02_Clinical_Instruments/02_instrument_format/PHP_instrument.md
- modules/timepoint_list/php/timepoint_list.class.inc
- modules/timepoint_list/templates/menu_timepoint_list.tpl
- php/libraries/NDB_BVL_Instrument_LINST.class.inc
> Push 24.1 release into main

- composer.json
- composer.lock
- src/Log/ErrorLogLogger.php
ubuntu 21.1
php 8
node 16
npm 8.11
composer 2.3.7) . EEG is ok.
There are two bugs (composer missing psr/log and missing void in the ErrorLogLogger file )
> [Loris 24.0-release ] fix composer and error

- modules/login/php/signup.class.inc
- modules/user_accounts/jsx/userAccountsIndex.js
- modules/user_accounts/php/edit_user.class.inc
- modules/user_accounts/php/useraccountrowprovisioner.class.inc
- tools/exporters/data_dictionary_builder.php
DO NOT SQUASH
Conflicts
```
Changes to be committed:
modified:   modules/user_accounts/jsx/userAccountsIndex.js
modified:   modules/user_accounts/php/edit_user.class.inc
Unmerged paths:
(use "git add/rm <file>..." as appropriate to mark resolution)
deleted by us:   modules/dataquery/jsx/react.fieldselector.js
deleted by us:   modules/login/php/requestaccount.class.inc
both modified:   modules/user_accounts/php/useraccountrowprovisioner.class.inc
both modified:   tools/exporters/data_dictionary_builder.php
```
> Push v23.0.12 into 24.0 release

- jsx/Form.js
- modules/login/php/signup.class.inc
- modules/user_accounts/jsx/userAccountsIndex.js
- modules/user_accounts/php/edit_user.class.inc
- modules/user_accounts/php/useraccountrowprovisioner.class.inc
- php/libraries/LorisFormDictionaryImpl.class.inc
- tools/CouchDB_Confirm_Integrity.php
- tools/exporters/data_dictionary_builder.php
> PUSH 24.0-release into 24.1-release demo

- modules/data_release/jsx/uploadFileForm.js
Fixes error from data_release/jsx/uploadForm.js when compiling javascript
```
188:9  warning  Unexpected console statement  no-console
```
> Remove console.log from data_release form

- modules/imaging_uploader/php/module.class.inc
- modules/imaging_uploader/static/schema.yml
This adds a schema file to describe the imaging_uploader module endpoints. 
The file can be used by the api_docs module.
> [imaging_uploader] HasApiSpecification-->true

- jsx/FilterableDataTable.js
> [Core] FiterableDataTable typo fix

- package.json
- webpack.config.js
Updates package.json for latest version of copy-webpack-plugin.
1. make clean
2. make dev
3. navigate around Loris
> [webpack.config.js] update dependencies for copy-webpack-plugin

- docs/wiki/99_Developers/Alternative_Install/LORIS_on_Macintosh/README.md
Updates the macOS development setup guide for the latest dependency requirement.
> Update developer guide

- modules/electrophysiology_browser/jsx/react-series-data-viewer/package.json
- modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/components/AnnotationForm.tsx
- modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/components/IntervalSelect.tsx
> [EEG Browser] Make fix

- modules/electrophysiology_browser/jsx/react-series-data-viewer/package.json
- modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/components/AnnotationForm.tsx
- modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/components/IntervalSelect.tsx
Fix https://github.com/aces/Loris/issues/8170
> [EEG Browser] Make fix [v24.1]

- modules/candidate_profile/test/candidate_profileTest.php
add test for candidate profile
link for instrument and fix page load test
pass git actions
> [integration test] add test for candidate profile

- modules/instruments/jsx/VisitInstrumentList.js
Cleanup of redundant css properties.
1. checkout pr
2. visit a candidate profile (beta) `ex. http://localhost/candidate_profile/300007/`
> [instruments] cleanup redundant css properties

- modules/api/php/module.class.inc
- modules/login/php/module.class.inc
- php/libraries/Module.class.inc
Add a return type hint to the isPublicModule method.
Resolves #4282
> [Module] Add return type hint to isPublicModule

- raisinbread/instruments/NDB_BVL_Instrument_aosi.class.inc
> [RB] fix instrument scoring and alot of whitespaces

- modules/electrophysiology_browser/jsx/react-series-data-viewer/src/eeglab/EEGLabSeriesProvider.tsx
- package.json
Upgrade TS to fix a compilation error:
```
ERROR in /home/runner/work/Loris/Loris/modules/electrophysiology_browser/jsx/react-series-data-viewer/node_modules/@types/lodash/common/object.d.ts
2431:64-74
[tsl] ERROR in /home/runner/work/Loris/Loris/modules/electrophysiology_browser/jsx/react-series-data-viewer/node_modules/@types/lodash/common/object.d.ts(2431,65)
TS1005: ';' expected.
```
> [TS] Upgrade to fix compilation error

- php/libraries/NDB_BVL_Instrument.class.inc
after delete the data, the loris page need to refresh
instrument #7892
1. delete an instrument data
2. the data disappeares .
instrument #7892
> [Delete instrument data] fix refresh

- package-lock.json
This PR fix the tests failure introduced by #7491
> Add missing package in package-lock.json

- CHANGELOG.md
- modules/electrophysiology_browser/jsx/electrophysiologySessionView.js
- modules/electrophysiology_browser/jsx/react-series-data-viewer/src/eeglab/EEGLabSeriesProvider.tsx
- modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/components/EEGMontage.tsx
- modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/components/EventManager.tsx
- modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/components/LineChunk.tsx
- modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/components/SeriesRenderer.tsx
- modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/store/logic/fetchChunks.tsx
- modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/store/state/dataset.tsx
- fixes a glitch with clippath
- truncate the epoch timing values
- fixes #8208 
- Manage different signal samplings
- Improve 2D electrode montage
> [EEG Browser] Viz bugfixes

- composer.json
- composer.lock
- php/libraries/SinglePointLogin.class.inc
We're currently using 3.0, but the library is up to 6.3.1. This updates the LORIS code to use the latest version of our JWT library.
> [Libraries] Update JWT library

- SQL/0000-00-00-schema.sql
- SQL/New_patches/2021-09-13_fix_project_primary_key.sql
Add a UNIQUE constraint on Project.Name
* Resolves #7464 
Copy of https://github.com/aces/Loris/pull/7566
> [DB schema] UNIQUE Project name

- npm-postinstall.js
- package-lock.json
Fix ESLINT for npm-postinstall.js
> ESLINT postinstall fix

- modules/electrophysiology_browser/README.md
Added troubleshooting point for Protobuf `>v3.20.x` install in README.
> [Electrophysiology Browser] README.md update

- .phan/config.php
- htdocs/mri/jiv/get_file.php
- htdocs/postdeploy.php
- modules/help_editor/php/edit_help_content.class.inc
- modules/publication/ajax/FileUpload.php
- modules/statistics/php/charts.class.inc
- modules/statistics/php/stats_behavioural.class.inc
- modules/user_accounts/php/edit_user.class.inc
This fixes all errors of type PhanPossiblyInvalidDimOffsets. This catches
code paths which attempt to access an offset in an array that may not
be defined in some code paths.
> [phan] Fix PhanPossiblyInvalidDimOffset errors

- Makefile
Fix a regression introduced by #8224
> Make typo fix

- modules/help_editor/ajax/process.php
- modules/help_editor/jsx/help_editor_helper.js
fixes https://github.com/aces/Loris/issues/6940 that broke in https://github.com/aces/Loris/pull/7018
1.
> [help_editor] Fix saving changes

- SQL/0000-00-00-schema.sql
- SQL/New_patches/20230119_add_index_on_violations_resolved.sql
This adds an index in the `violations_resolved`. It should make the dashboard load faster.
> [SQL schema] Add index on violations_resolved

- modules/instrument_builder/jsx/react.questions.js
> [instrument_builder] Fix display order of select options

- modules/api/php/models/candidatesrow.class.inc
- modules/api/static/schema.yml
Added missing `ProjectID` tag and change descriptors to be less copy pasted
> [API] Minor schema fixes

- modules/publication/test/PublicationTest.php
- raisinbread/RB_files/RB_publication.sql
- raisinbread/RB_files/RB_publication_collaborator.sql
- test/phpunit.xml
[publication module] Implement automated tests #7637
add automation test for publication module
> add test for publication

- modules/document_repository/README.md
- modules/document_repository/help/document_repository.md
explain how the filter works in the document_repository help section.
filter a file in a folder that contains some files. (not root, try pdf or txt...)
https://github.com/aces/Loris/issues/7865
> [document_repository] add usage doc for filter

- modules/dqt/README.md
better late than never
followup on https://github.com/aces/Loris/pull/2720
1.
> [DQT] Update README.md

- modules/data_release/test/TestPlan.md
Adding testing step for unversioned files. 
#8025
> [Data release] - Update Test Plan instruction

- modules/candidate_list/jsx/candidateListIndex.js
- modules/candidate_list/test/candidate_listTest.php
> [candidate_list] Fix Feedback dropdown options

- modules/survey_accounts/php/survey_accounts.class.inc
- php/libraries/NDB_BVL_Feedback.class.inc
- php/libraries/NDB_BVL_Instrument.class.inc
- php/libraries/UserPermissions.class.inc
- tools/single_use/Cleanup_multiple_firstVisits.php
- tools/single_use/Remove_Data_entry_completion_status_instr_column.php
- tools/single_use/SaveUserIDToInstrumentData.php
- tools/single_use/Set_Required_elements_completed_flag.php
- tools/single_use/instrument_double_escape_report.php
- tools/single_use/populate_visits.php
> Remove LORIS Deprecation Warning and PHP Notices

- tools/CouchDB_Import_MRI.php
- tools/importers/CouchDB_MRI_Importer.php
- Remove the side effect in CouchDB_MRI_Importer.php
- Migrate CouchDB_MRI_Importer.php in importers/
- Migrate the import statements in CouchDB_MRI_Importer.php
> [Tools] CouchDB_Import_MRI.php cleanup

- modules/battery_manager/php/battery_manager.class.inc
- modules/electrophysiology_browser/php/electrophysiology_browser.class.inc
- modules/media/php/media.class.inc
This removes some comments that claim they're doing something for NDB_Menu_Filter when, in fact, the class isn't an NDB_Menu_Filter.
> [Meta] Fix incorrect references to NDB_Menu_Filter

- tools/single_use/DB_date_zeros_removal.php
fixes https://github.com/aces/Loris/issues/8066
> [tools] Replace a constant date with current date

- modules/examiner/help/examiner.md
- modules/examiner/jsx/examinerIndex.js
- modules/examiner/test/TestPlan.md
> [examiner] Remove link to edit examiner if certification is not enabled

- CHANGELOG.md
> ChangeLog update

- modules/api_docs/help/api_docs.md
- modules/api_docs/test/TestPlan.md
- Add testPlan
- Fix help text
* Resolves https://github.com/aces/Loris/issues/7875
> [API Docs] Test plan & help text

- tools/data_integrity/data_deletion/delete_physiological_file.php
The order of deleted queries is changed, with a few extra necessary queries added
Related to #8232
> [Tools] Modified deletion query order for physiological file deletion

- modules/examiner/jsx/examinerIndex.js
- modules/examiner/php/addexaminer.class.inc
- modules/examiner/php/examiner.class.inc
- modules/examiner/php/examinerprovisioner.class.inc
- modules/examiner/php/examinerrow.class.inc
- modules/examiner/php/modulerow.class.inc
- modules/examiner/test/ExaminerTest.php
rewrite the Examiner module with data framework
> [Examiner] data framework

- jsx/StaticDataTable.js
- modules/login/jsx/loginIndex.js
- modules/login/jsx/passwordExpiry.js
- modules/login/jsx/requestAccount.js
- modules/login/jsx/resetPassword.js
I happened to noticed that these data types were incorrectly assigned.
> [Proptypes] Fixed conflicting data type assignments

- modules/candidate_profile/test/TestPlan.md
> [candidate_profile] Update docs

- modules/dqt/test/TestPlan.md
The second step was the same as the first step in the TestPlan for dqt, so I removed the second step which was less detailed.
> [dqt] Update TestPlan to remove redundant step

- modules/imaging_browser/jsx/ImagePanel.js
This fixes all the JS console warning message for the imaging browser view session page.
> Fix warning JS messages for imaging browser

- modules/battery_manager/help/battery_manager.md
- modules/battery_manager/test/TestPlan.md
Minor text amendments to the `TestPlan.md` and the `help/battery_manager.md` files to reflect new changes and fix typos.
Related issue: #8505
> [battery_manager] Updated Test Plan and Help Text

- modules/statistics/css/statistics.css
> [statistics] fix statistics site display format

- modules/imaging_uploader/test/TestPlan.md
Updates the Test Plan for `imaging uploader` module
> [imaging uploader] Test Plan update

- modules/module_manager/test/TestPlan.md
Updating test plan with Frontend name for the permissions
> [module_manager] - updating testplan

- modules/media/help/media.md
- modules/media/test/MediaTest.php
- modules/media/test/TestPlan.md
Minor text amendments to the `TestPlan.md`, `MediaTest.php` and `help/media.md` files to reflect new changes and fix typos.
Related issues: 
- #8506
- #7678
> [media] Test Plan and Help Text Documentation Update

- modules/candidate_parameters/README.md
Updating readme file with frontend permissions' name. 
Issue #8557
> [candidate_parameter] - update readme with frontend name

- raisinbread/RB_files/RB_notification_modules_services_rel.sql
[my_preferences] - Notification missing for media module #8553 add RB data
https://github.com/aces/Loris/issues/8553
> [my_preferences] - Notification missing for media module #8553 add RB data

- modules/instruments/help/instruments.md
- modules/instruments/test/TestPlan.md
> [instruments] Update Test + Help docs

- jsx/Form.js
- modules/issue_tracker/jsx/IssueForm.js
- modules/issue_tracker/php/edit.class.inc
- modules/issue_tracker/php/issuerowprovisioner.class.inc
Fixes  #8552
Also fixes some JS warnings, and another bug found along the way (Creating an issue without an assignee will successfully create an issue that won't display in the list of issues).
> [Issue Tracker] Release fixes

- modules/battery_manager/jsx/batteryManagerForm.js
- modules/battery_manager/jsx/batteryManagerIndex.js
- modules/battery_manager/php/testendpoint.class.inc
- modules/media/ajax/FileDownload.php
> [Battery_manager] Fixed min/max validation 

- modules/electrophysiology_uploader/help/electrophysiology_uploader.md
Added 'Help' content for `electrophysiology_uploader` module. #8597
> [electrophysiology_uploader] Added 'Help' content for users

- CHANGELOG.md
- modules/configuration/ajax/updateProject.php
- modules/configuration/js/project.js
- modules/examiner/templates/form_editExaminer.tpl
- modules/instruments/test/TestPlan.md
- modules/issue_tracker/jsx/IssueForm.js
- modules/issue_tracker/jsx/attachments/attachmentsList.js
- modules/issue_tracker/php/edit.class.inc
- modules/issue_tracker/php/issue_tracker.class.inc
- modules/new_profile/php/new_profile.class.inc
- modules/new_profile/test/new_profileTest.php
- php/libraries/NDB_BVL_Feedback.class.inc
- php/libraries/NDB_BVL_InstrumentStatus_ControlPanel.class.inc
- src/StudyEntities/Candidate/Sex.php
- tools/data_integrity/fix_candidate_age.php
- tools/single_use/instrument_double_escape_report.php
- webpack.config.js
Merge the 24.1-release branch into 25.0-release.
> Push 24.1-release branch to 25

- SQL/Release_patches/24.1_To_25.0_upgrade.sql
combine files in the New_patches into one release file.
> 24.1 to 25.0 release patch

- modules/document_repository/help/document_repository.md
Updated content to mention new feature to support uploading multiple files at once.
For testing assignment #8519.
> [document_repository] Update help content

- modules/acknowledgements/test/TestPlan.md
Correct step about clearing filters wording and add step to check the citation policy works.
Fixes #8736
> [acknowledgements] Update test plan

- jsx/Form.js
- Removed the legacy JQuery month picker that is no longer needed, without it the issue is gone.
* Resolves #8753
> [new_profile] DateElement in 'Y-m' Fix

- modules/issue_tracker/php/module.class.inc
- Replace username with full name in "My Issues" card link of the dashboard
* Resolves #8007
> Fix for "My Issues" problem in dashboard

- raisinbread/test/api/LorisApiAuthenticatedTest.php
- raisinbread/test/api/LorisApiAuthenticated_v0_0_3_Test.php
- raisinbread/test/api/LorisApiDicomsTest.php
- raisinbread/test/api/LorisApiLoginTest.php
- raisinbread/test/api/LorisApiLogin_v0_0_3_Test.php
Test the login once, instead of testing it once per class by moving it out of the base class.
Resolves #8780
> [Tests] Remove duplicated login test

- modules/api/php/views/visit/flags.class.inc
- modules/api/php/views/visit/instrument.class.inc
Push the latest changes from the 24.1 branch into the 25 branch.
> Push24 to25

- modules/mri_violations/help/mri_violations.md
- Updated the help content of mri_violations to be a bit more clear
* Resolves #8737
> [mri_violations] Update Help

- modules/survey_accounts/test/TestPlan.md
> [survey_accounts] Update test plan

- modules/issue_tracker/php/edit.class.inc
- Update the comment for module to reflect on the unavailability of the module linked to the issue
* Resolves #8075
> Fix for inactive module based issues

- jsx/Filter.js
- Fix the issue with checkbox when unchecked (filtering happened for listing all entries where the condition is false instead of just removing the filter)
* Resolves #6985
> [IssueTracker] Fix for checkbox problem

- jsx/Form.js
- modules/issue_tracker/jsx/IssueForm.js
- Fix for singular user highlighting in other watching list
* Resolves #8866
> [IssueTracker] Fix single watcher problem

- php/libraries/Module.class.inc
Remove code saying its a hack for tests and fix any tests that break.
(It does not seem to break any tests.)
Resolves #6497
> [Module] Remove breadcrumb hack code

- jsx/PaginationLinks.d.ts
Add `.d.ts` file for PaginationLinks so that it can be imported from typescript and type checked.
> [TypeScript] Add PaginationLinks module definition

- jsx/Modal.d.ts
Add .d.ts file so that Modal can be imported from typescript.
> [Typescript] Add Modal typescript definition

- php/libraries/NDB_BVL_Instrument.class.inc
- php/libraries/NDB_BVL_Instrument_LINST.class.inc
This PR will allow for easier maintenance of the method
1.
> [NDB_BVL_Instrument] Cleanup duplicate method definition for _addMetadataFields()

- Makefile
- modules/issue_tracker/jsx/IssueForm.js
- modules/issue_tracker/jsx/attachments/attachmentsList.js
- modules/issue_tracker/jsx/attachments/uploadForm.js
Add missing Form.js import statements to the issue tracker javascript.
Resolves #8970
> [issue_tracker] Add missing imports

- modules/datadict/test/datadictTest.php
[datadict] Missing automated tests #7648
landing and ui test already added. 
add filter and clear buttun test.
> [datadict] Missing automated tests 

- Makefile
- modules/module_manager/jsx/modulemanager.js
Fix module manager loading by adding missing import statement.
> [module_manager] Fix page load

- modules/imaging_qc/test/TestPlan.md
- [x ] Have you updated related documentation?
https://github.com/aces/Loris/issues/8607
> [imaging_qc] Update TestPlan

- modules/publication/test/PublicationTest.php
publication - test all page load and check first element render well
> [publication ] test

- SQL/New_patches/2023-04-25-FixIssueWrongModuleID.sql
- modules/behavioural_qc/jsx/tabs_content/behaviouralFeedback.js
- modules/genomic_browser/jsx/tabs_content/files.js
- modules/genomic_browser/php/filemanager.class.inc
- modules/genomic_browser/php/uploading/genomicfile.class.inc
- modules/issue_tracker/jsx/IssueForm.js
- modules/issue_tracker/php/edit.class.inc
- modules/issue_tracker/php/issue.class.inc
- modules/issue_tracker/php/issue_tracker.class.inc
- modules/issue_tracker/test/issue_tracker_test_plan.md
- modules/media/php/mediafileprovisioner.class.inc
- php/libraries/NDB_BVL_Instrument.class.inc
- php/libraries/NDB_BVL_Instrument_LINST.class.inc
- php/libraries/User.class.inc
- raisinbread/RB_files/RB_issues_history.sql
- smarty/templates/email/issue_assigned_modified.tpl
- smarty/templates/email/issue_change.tpl
- test/unittests/NDB_BVL_Instrument_Test.php
- test/unittests/UserTest.php
- tools/data_integrity/fix_candidate_age.php
Pull v24.1.x forward into v25.
DO NOT SQUASH.
> Push v24.1.6 changes into 25 branch

- .github/workflows/loristest.yml
Thanks @driusan. 
It fixed the sql issue in raisinbread.
> fix API test - replace code in loristest.yml

- modules/data_release/jsx/addPermissionForm.js
- modules/data_release/jsx/managePermissionsForm.js
- modules/data_release/jsx/uploadFileForm.js
Refactoring module
1. The module should properly load now in the main branch.
> [data_release] refactoring module. 

- modules/user_accounts/jsx/userAccountsIndex.js
> [User Accounts] Site as multi select

- SQL/New_patches/2024-01-29-create-sex-table.sql
> [candate_list] Sex table fix column name

- modules/issue_tracker/jsx/IssueForm.js
[issue tracker]fix - jsx import issue
create a new issue.
> [issue tracker]fix - jsx import issue

- modules/imaging_uploader/jsx/ImagingUploader.js
- modules/instrument_manager/jsx/uploadForm.js
- modules/publication/jsx/publicationIndex.js
While doing some tests, I found more missing imports and fixed them.
> Fix more missing imports

- modules/media/jsx/editForm.js
jsx import issue [media] fix load issue
https://github.com/aces/Loris/issues/9082
> [media] fix load issue

- modules/document_repository/jsx/editForm.js
[document_repository/edit] can't load form #9083
> [document_repository/edit] can't load form #9083

- modules/battery_manager/jsx/batteryManagerForm.js
Add missing imports to the battery_manager.
Resolves #9078
> [battery_manager] Fix loading of edit form 

- modules/dataquery/test/TestPlan.md
> [dataquery] test plan

- modules/instrument_builder/jsx/react.questions.js
> [instrument builder ]fix jsx import issue

- modules/instrument_list/templates/instrument_list_controlpanel.tpl
- Made the 'Send to DCC' button also refresh the page.
1. See issue
* Resolves #9071
> [Instrument_list] Refresh on Send to DCC

- tools/CouchDB_Import_Demographics.php
[tools/script] fix projectID issue #9069
[tools/script] fix projectID issue
run php CouchDB_Import_Demographics.php without issue
> [tools/script] fix projectID issue

- php/libraries/NDB_Client.class.inc
This PR allows images from https://loris.images.ca to be loaded in `<img>` tags.
> [NDB_Client] Allow loading images from images.loris.ca 

- htdocs/main.css
> Help UI fix

- modules/genomic_browser/test/TestPlan.md
This PR modifies the test plan for the genomic browser module. The changes are mostly cosmetics but also include corrections of the permission names and table headers mentioned in the plan.
Fixes #9151
> [genomic_browser] Minor edits to the test plan

- .github/workflows/loristest.yml
V2 using node 12 in gitaction, V3 using node 16. It might help accelerate the testing process a bit.
> gitaction v2 to v3

- SQL/0000-00-03-ConfigTables.sql
- raisinbread/RB_files/RB_Config.sql
[Acknowledgment] Fix awkward language in citation policy placeholder 
[#9246](https://github.com/aces/Loris/issues/9246)
> [Acknowledgment] Fix awkward language in citation policy placeholder  #9246 - modify text

- modules/issue_tracker/test/issue_tracker_test_plan.md
Closes #9254.
This PR improves the test plan by further specifying the requirement of one of the steps.
> [issue_tracker] Add specification to issue_tracker_test_plan.md 

- modules/media/jsx/CandidateMediaWidget.js
replace "ajax/FileDownload.php?File=" to "files/"
> [media] ajax function has been removed

- modules/imaging_uploader/php/imaging_uploader.class.inc
Fix form freezing when uploading a big file 
Resolves #9247
> [imaging uploader] fixing upload a large file frozen

- SQL/Cleanup_patches/2023-01-24-DropPresent.sql
- modules/acknowledgements/help/acknowledgements.md
- modules/acknowledgements/jsx/acknowledgementsIndex.js
- modules/acknowledgements/php/acknowledgements.class.inc
Since this was triggered by confusion over what "Present" means, this also updates the help text to add a brief description.
Resolves #6231
> [acknowledgements] Remove "Present" column from database and dynamically calculate

- modules/acknowledgements/test/AcknowledgementsTest.php
Enhance the testing to align with the new code.
[acknowledgements] Remove "Present" column from database and dynamically calculate #8339 was fail in gitactions.
> [acknowledgements] Remove "Present" column from database and dynamica… fix failures for testing

- test/dockerized-integration-tests.sh
- test/dockerized-unit-tests.sh
> Fix GitHub Actions failure on the 25

- .github/workflows/loristest.yml
- test/dockerized-integration-tests.sh
- test/dockerized-unit-tests.sh
>  Fix GitHub Actions failure on the 26

- test/dockerized-integration-tests.sh
- test/dockerized-unit-tests.sh
> Fix GitHub Actions failure on the main

- modules/mri_violations/php/mri_violations.class.inc
Fixes #9350, @driusan proposed solution seems to be working.
> [mri violations] Fix protocols query

- modules/battery_manager/test/BatteryManagerTest.php
- modules/battery_manager/test/TestPlan.md
- test/phpunit.xml
> battery manager test

- php/libraries/LorisForm.class.inc
- test/unittests/LorisForms_Test.php
> [User Account] Checkbox alignments

- tools/manage_modules.php
[tools] manage_modules.php failing with --remove #8068
test
run "php manage_modules.php  --remove" without errors and all the modules will be removed.
> [tools] manage_modules.php failing - bug fix

- modules/behavioural_qc/test/behavioural_qcTest.php
> [behavioural_qc] test

- modules/behavioural_qc/php/provisioners/behaviouralprovisioner.class.inc
- modules/behavioural_qc/php/provisioners/conflictsprovisioner.class.inc
- modules/behavioural_qc/php/provisioners/incompleteprovisioner.class.inc
The new added integration test catch this bug in gitaction. 
test: pass gitactions
> [behavioural_qc ] fix 500 error

- jsx/StaticDataTable.js
- modules/issue_tracker/php/edit.class.inc
- tools/detect_duplicated_commentids.php
> Push 24.1.8 to 25

- modules/api/php/endpoints/candidate/visit/image/qc.class.inc
- modules/mri_violations/php/mri_violations.class.inc
- raisinbread/test/api/LorisApiImagesTest.php
- raisinbread/test/api/LorisApiImages_v0_0_3_Test.php
Push changes into latest release.
> Push LORIS 25 changes into LORIS 26

- CHANGELOG.md
- README.md
- docs/wiki/00_SERVER_INSTALL_AND_CONFIGURATION/01_LORIS_Install/CentOS/README.md
- modules/api/php/endpoints/candidate/visit/image/qc.class.inc
- modules/candidate_parameters/jsx/DiagnosisEvolution.js
- modules/electrophysiology_uploader/README.md
- modules/electrophysiology_uploader/jsx/ElectrophysiologyUploader.js
- modules/imaging_uploader/php/imaging_uploader.class.inc
- modules/media/test/MediaTest.php
- modules/media/test/TestPlan.md
- modules/mri_violations/php/mri_violations.class.inc
- modules/statistics/php/charts.class.inc
- modules/statistics/php/statistics_dd_site.class.inc
- modules/statistics/php/statistics_mri_site.class.inc
- modules/statistics/php/statistics_site.class.inc
- raisinbread/test/api/LorisApiImagesTest.php
- raisinbread/test/api/LorisApiImages_v0_0_3_Test.php
- tools/generic_includes.php
Push any changes from the 26 development branch into the main branch.
> Push 26 to Main

- modules/imaging_qc/php/imaging_qc.class.inc
- modules/media/ajax/FileUpload.php
- modules/statistics/php/statistics_mri_site.class.inc
- modules/statistics/php/statistics_site.class.inc
- modules/survey_accounts/ajax/ValidateEmailSubmitInput.php
- modules/survey_accounts/php/addsurvey.class.inc
- Update flag.Test_name to flag.TestID and test_names.Test_name wherever it was missing in #9338 
- Error caused part of the media module to not load, and I imagine it is a similar case with the rest of them
> [bugfix] Cleanup TestName->TestID transition

- modules/issue_tracker/jsx/issueTrackerIndex.js
#9339 got merged after #9430 without rebasing, which allowed some wrong indents to be committed to main.
> Fix JS lint error on main

- php/libraries/NDB_BVL_Instrument.class.inc
fix Line exceeds 85 characters; contains 87 characters
> [Github] fix line format

- jsx/Form.d.ts
- jsx/Form.js
- jsx/form/DateTimePartialElement.tsx
- modules/battery_manager/jsx/batteryManagerForm.js
- modules/conflict_resolver/jsx/fix_conflict_form.js
- modules/data_release/jsx/addPermissionForm.js
- modules/data_release/jsx/managePermissionsForm.js
- modules/data_release/jsx/uploadFileForm.js
- modules/document_repository/jsx/categoryForm.js
- modules/document_repository/jsx/deleteCategoryForm.js
- modules/document_repository/jsx/editCategoryForm.js
- modules/document_repository/jsx/editForm.js
- modules/document_repository/jsx/uploadForm.js
- modules/electrophysiology_uploader/jsx/UploadForm.js
- modules/genomic_browser/jsx/tabs_content/filemanager/uploadForm.js
- modules/imaging_uploader/jsx/UploadForm.js
- modules/issue_tracker/jsx/IssueForm.js
- modules/issue_tracker/jsx/IssueTrackerBatchMode.js
- modules/media/jsx/uploadForm.js
This pull request removes the `hasError` boolean prop from various form elements and updates the error handling logic to rely solely on the `errorMessage` prop. This change simplifies the error handling mechanism and ensures consistency across all form components.
- **Removed `hasError` prop** from form elements in `jsx/Form.js`, `jsx/Form.d.ts`, and other related files.
- **Updated form components** to check for the presence of `errorMessage` instead of `hasError` to determine if an error state should be displayed.
- **Modified default props and prop types** to remove `hasError` and ensure `errorMessage` is used appropriately.
- **Adjusted form usage** in various modules to reflect this change, including:
- `battery_manager/jsx/batteryManagerForm.js`
- …
> [JSX] Remove `hasError` Boolean from Form Elements

- tools/recreate_conflicts.php
- Fix recreate conflicts script after Test_name change #9338 
1. Try running recreate_conflicts.php and see that it now runs.
> [Recreate_Conflicts] Fix Test_name change

- modules/examiner/jsx/examinerIndex.js
[Examiner] fix missing edit examiner url-link
> [Examiner] fix missing edit examiner url-link

- php/libraries/LorisForm.class.inc
- php/libraries/NDB_BVL_Instrument.class.inc
- Fix php warnings / deprecations
- Lots of error are shown on CCNA when running `recreate_conflicts.php`
[CCNA OVERRIDE PR](https://github.com/aces/CCNA/pull/7174)
> [libraries] Library php warnings / deprecations

- tools/importers/CouchDB_MRI_Importer.php
- Fix types of MRI import so the script can actually run
- Fix the dates so that they import as human readable dates rather than something like "1622400"
1. Run `php /var/www/loris/tools/CouchDB_Import_MRI.php`
2. Confirm the script runs
3. May need to add data that has dates, and then confirm data with dates shows up as Y-m-d in dqt.
[CCNA OVERRIDE PR](https://github.com/aces/CCNA/pull/6700)
> [CouchDB] MRI Import Date Fix

- webpack.config.ts
This is the first of a series of PRs that will optimize the Webpack configuration. This PR only cleans up the current configuration with more explicit typing, and isolating some logic into functions.
The code is sometimes a little heavy because I use a rather functional approach, but I believe this leads to a cleaner logic (create new record instead of mutating existing one).
```
(loris-mri-python) lorisadmin@mmulder-dev:/var/www/loris$ time npm run compile
> loris@1.0.0 compile
> webpack --node-env=development
Building all modules
webpack compiled successfully
webpack compiled successfully
real	2m29.071s
user	1m42.369s
sys	0m5.481s
(loris-mri-python) lorisadmin@mmulder-dev:/var/www/loris$ export target=login
(loris-mri-python) lorisadmin@mmulder-dev:/var/www/loris$ time npm run compile
> …
```
> Clean up Webpack configuration

- SQL/0000-00-03-ConfigTables.sql
- raisinbread/RB_files/RB_Config.sql
- raisinbread/RB_files/RB_ConfigSettings.sql
[SQL] remove downloadpath from sql files
[Config] Fix default DownloadPath in ConfigSettings #9464
> [SQL] remove DownloadPath from sql files - 26.0-release

- modules/electrophysiology_uploader/jsx/ElectrophysiologyUploader.js
- modules/electrophysiology_uploader/jsx/UploadForm.js
- Update `Browse` tab on successful upload of a file.
- Clear any possible error messages from previous file uploads when selecting a file.
1. Upload a file with a name that does not fit the convention and press submit
2. Upload a valid file
* Resolves #9258
> [electrophysiology_uploader] Fix minor unexpected behaviours

- src/Database/Query.php
Queries which use pselectRow that return data can fail to load with an error about not being able to execute queries with pending results.
pselectRow does a count on the database connection, which executes the query. When getFirstRow is called after, the query has already been executed but the results have not been fetched when getIterator() attempts to re-execute the query.
This keeps track of the execution state so that it is only executed the first time.
Fixes #9500
> [Core] Fix loading of pselectRow queries

- tools/CouchDB_Import_Demographics.php
Fix type error in CouchDB_Import_Demographics script.
Resolves #9507
> [Deprecated DQT] Fix type error in demographic import script

- SQL/New_patches/2024-10-08-issuetracker-watch-all.sql
- modules/issue_tracker/README.md
- modules/issue_tracker/php/edit.class.inc
- modules/issue_tracker/php/issue.class.inc
- Adds the ability to enable receiving notifications for all new or modified issues
1. Set your notifications in My Preferences so that you receive emails when an issue is modified or created
2. From another account, create an issue on the issue_tracker. Check that you receive the email.
3. From another account, comment on an issue in the issue_tracker. Check that you receive the email.
4. Repeat steps 2-3 without the notifications set in My Preferences, and make sure you do not receive an email.
[CCNA OVERRIDE PR](https://github.com/aces/CCNA/pull/7241)
> [issue_tracker] Receive notifications for all issues

- php/libraries/Candidate.class.inc
- php/libraries/Database.class.inc
- php/libraries/TimePoint.class.inc
Fix bug about "[SQL] Refactor FK CandID int(6) to CandidateID int(10) (candidate.ID PK) #9556"
The CandID column has been removed from session table, so the insertdata should be updated.
> fix can't create timepoint bug

- htdocs/installdb.php
- modules/configuration/ajax/process.php
- modules/examiner/php/editexaminer.class.inc
- modules/help_editor/php/edit_help_content.class.inc
- modules/instrument_list/php/module.class.inc
- modules/login/php/signup.class.inc
- modules/my_preferences/php/my_preferences.class.inc
- modules/publication/ajax/FileUpload.php
- modules/statistics/php/stats_behavioural.class.inc
- modules/statistics/php/stats_demographic.class.inc
- modules/statistics/php/stats_mri.class.inc
- modules/user_accounts/php/edit_user.class.inc
- php/installer/Installer.class.inc
- php/libraries/Database.class.inc
- php/libraries/LorisForm.class.inc
- php/libraries/NDB_Page.class.inc
- src/Middleware/UserPageDecorationMiddleware.php
- tools/exporters/data_dictionary_builder.php
- tools/generate_tables_sql_and_testNames.php
updated all instances of htmlspecialchars() to turn off double escaping
> HTMLSpecialChars() Double escaping default to false

- modules/imaging_uploader/php/imaging_uploader.class.inc
It seems unlikely that users accessing the imaging uploader are looking for the first 20 scans ever uploaded. It's much more likely that they want the latest...
1.
* Resolves MY OCD ISSUES
> [imaging_uploader] Sort by UploadDate for most recent uploads

- modules/imaging_uploader/php/imaging_uploader.class.inc
- php/libraries/NDB_BVL_Feedback.class.inc
Fixes #9581 
These problems were noticed during the testing blitz and these exact changes were made to enable testing.
> [imaging_uploader / NDB_BVL_Feedback] Fix errors caused by CandidateID refactor

- modules/survey_accounts/ajax/ValidateEmailSubmitInput.php
> [survey_accounts] Fix CandID reference

- modules/dataquery/test/TestPlan.md
> Update dataquery test plan to mention need for dictionary module access.

- modules/media/test/TestPlan.md
> [media] Update TestPlan.md

- modules/dictionary/jsx/dataDictIndex.js
dictionary fix loading issue 
test: load the main page
> dictionary fix loading issue

- modules/help_editor/test/TestPlan.md
submitted by  @christinerogers 
resolves #9586 and #9443 
addresses one point in #5776
> [help_editor] Update TestPlan.md

- raisinbread/RB_files/RB_permissions.sql
- raisinbread/RB_files/RB_user_perm_rel.sql
fix missing dataquery perm for admin in RB
> [dataquery] fix missing dataquery perm for admin in RB

- modules/survey_accounts/ajax/ValidateEmailSubmitInput.php
- modules/survey_accounts/php/addsurvey.class.inc
can't create a new survey #9637
Fix can't create a survey or email a survey. 
Test : create a survey, make sure it works.
> [survey] - fix can't add or email a survey

- modules/mri_violations/php/usercentermatchornulloranypermission.class.inc
[mri_violations] Cannot access module with "Own sites" permission #9603
> [mri_violations] Cannot access module with "Own sites" permission #9603 -fix 

- modules/electrophysiology_browser/css/electrophysiology_browser.css
- modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/components/DatasetTagger.tsx
- modules/electrophysiology_browser/php/sessions.class.inc
- webpack.config.ts
Closes #9583.
Will only work if #9653 is merged
> [electrophysiology_browser] Fix webpack + css references + HED schema payload

- tools/exporters/DB_dump_table_data.php
[tools - exporters/DB_dump_table_data.php] Does not run #9640
> [tools] fix exporters/DB_dump_table_data.php 

- webpack.config.ts
> [candidate_parameters/webpack] Add DiagnosisEvolution to webpack

- modules/issue_tracker/jsx/IssueTrackerBatchMode.js
This PR orders the watcher list on the front-end based on the user full name.
Resolves #9700
> [issue tracker] batch mode ordered watchers

- tools/data_integrity/update_candidate_latest_diagnosis.php
(https://github.com/aces/Loris/issues/9710)
test it : run "php data_integrity/update_candidate_latest_diagnosis.php"  no issues.
> [tools] error in data_integrity/update_candidate_latest_diagnosis.php #9710

- SQL/0000-00-00-schema.sql
- SQL/New_patches/2025-05-02-openidconnect.sql
add openid_connect_providers openid_connect_csrf tables into default schema.
> [SQL]  add missing openID tables into main branch

- modules/imaging_uploader/php/imaging_uploader.class.inc
Fixes issue where CandID and PSCID were not showing for all rows
1.
* Resolves #9765
> [imaging_uploader] ID fix not displaying

- modules/schedule_module/php/appointment.class.inc
[schedule_module] fix can't add new appointment without set time #9767
test add a new appointment without set time.
> [schedule_module] fix can't add new appointment without set time 

- tools/CouchDB_Import_Instruments.php
run "php CouchDB_Import_Instruments.php" without issue
> [tools]fix CouchDB_Import_Instruments.php

- modules/conflict_resolver/test/TestPlan.md
- I used proper markdown, table of contents, the word "assert". 
- I simplified the language, made it a fairly step-by-step testing process.
- Some lingering uncertainty of the original intention of the `resolved conflicts` and `unresolved conflicts` sections
- 
This is the documentation
This is the test.
#8766
> [conflict_resolver] Test Plan

- php/libraries/UserPermissions.class.inc
- test/unittests/UserTest.php
Bugfixes permission actions by forcing the order of the listed actions.
> User permissions/actions verbose tests

- Makefile
- modules/datadict/jsx/dataDictIndex.js
- modules/datadict/locale/hi/LC_MESSAGES/datadict.po
- modules/datadict/locale/ja/LC_MESSAGES/datadict.po
Add Japanese strings for better testing the datadict module.
> [Multilingual] Add Japanese datadict translations

- htdocs/index.php
fix can't override in project/moudle
> [IBIS 27] [htdocs] fix can't override in project/moudle

- modules/genomic_browser/php/provisioners/snpprovisioner.class.inc
[genomic_browser] SNP does not load #9970
1052 Column 'cohort.CohortID' in on clause is ambiguous
> [genomic_browser] SNP does not load  - fix

- modules/battery_manager/jsx/batteryManagerForm.js
- modules/battery_manager/jsx/batteryManagerIndex.js
> [Battery manager] fix can't active and edit using 0 days as minimum age days

- smarty/templates/public_layout.tpl
> Update MNI+MCIN URLs
