php/libraries/NDB_BVL_Instrument.class.inc
This fixes Redmine issue 14918 where an API request for instrument data fails with 500 error.
the error was due to a `NULL` value being passed where a string is expected in NDB_Page. the solution was to mimic the existing code above for the `page` variable and setting `commentId=''`
=> [API] Fix loading instruments from API

modules/user_accounts/php/edit_user.class.inc
This PR fixes the issue that whenever a user has the examiner_multisite permission and creates a new user, the new user will always be added to the examiner table even if no examiner options were set. 
This bug was found by @ZainVirani so assigning him to be a reviewer to this new PR.
=> [user accounts] Fixing users being always inserted into examiner table upon save

smarty/templates/403.tpl, smarty/templates/404.tpl, smarty/templates/500.tpl
When LORIS returns a 403, 404, or 500 error, a small template is shown to display that error. It currently says "Go to login page" when the URL actually points to baseURL. As a result this message is inaccurate when a user is already logged in as they'll be redirected to the dashboard (not logged out).
=> [Smarty Errors] "Go to login page" --> "Go to main page"

modules/help_editor/php/helpfile.class.inc
The HelpFile class has been changed to use the safe update function from the database class instead of the explicitly unsafe version.
`unsafeupdate` is to be used ["with caution, only when you know you need to insert HTML and know that you can trust it"](https://github.com/aces/Loris/blob/20.0-release/php/libraries/Database.class.inc#L442). I don't believe that data submitted by users into the help editor can be considered trusted as this is a cross-site scripting vector.
This change fixes a security issue while preserving the markup functionality of the help editor. HTML will not directly render but Markdown will. I believe this is closer to the intended functionality of the help editor.
No reported issues but this fix mitigates a confirmed cross-site scripting exploit.
This fix should …
=> [Help Editor] Use safe update instead of unsafe update

SQL/0000-00-03-ConfigTables.sql, SQL/New_patches/2018-08-16_make_config_lookup_center_a_drop_down.sql, modules/configuration/php/configuration.class.inc, modules/configuration/templates/form_configuration.tpl
This pull request is making the 'lookupCenterNameUsing' configuration under the 'Imaging Pipeline section" of the config module a drop down instead of an open text field. The options of the drop down: PatientID, PatientName
1. check that this field is indeed an open text field on minor
2. pull the code, run the SQL patch and check that the field is now a drop down
3. make sure the saving is working properly and saving the proper value
See also: Redmine ticket https://redmine.cbrain.mcgill.ca/issues/15104
=> Making lookupCenterNameUsing configuration field a drop down

.phan/config.php, modules/dashboard/ajax/get_scan_line_data.php, modules/media/ajax/FileUpload.php
This fixes the phan errors about function redeclarations.
These are mostly harmless and caused by different ajax endpoints
using the same function names with no namespacing, but it's better
to ensure we don't accidentally redeclare autoloaded functions in
a more dangerous context in the future.
=> [phan/dashboard/media] Fix function redeclaration errors

modules/media/ajax/FileUpload.php, php/libraries/Database.class.inc
This pull request adds two new methods to the database class: `insertOnDuplicateUpdate()` and `unsafeInsertOnDuplicateUpdate()`
These methods will attempt to `insert` a new row into the database given the query array passed as an argument. However, if one of the values to be inserted is a duplicate value for a unique key column, the query will be changed to an `update` statement for the row where the duplicate was found.
The `unsafe` version of the method will not escape insertion of HTML characters or JSON objects.
Reference:
https://dev.mysql.com/doc/refman/8.0/en/insert-on-duplicate.html
This PR also includes a use-case in the media module, which consolidates a few lines of code using the new function.
How to test:
1. Go to `Media` module and click on the `Upload` tab.
2. Upload a file …
=> Added On Duplicate Update Function to Database Class

modules/create_timepoint/php/create_timepoint.class.inc
Redmine #13790
While CandID comes from the database and is expected to be trusted, this PR explicitly sanitizes the candID variable before it is injected into the href element.
=> [Create Timepoint] Sanitize CandID in href

webpack.config.js
Somehow PR#3886 passed Travis despite forgetting to remove a line from
webpack.config.js, which results in npm run compile failing. This
fixes the major branch by removing that line.
=> [Travis] Fix major branch

htdocs/main.php, smarty/templates/401.tpl
This pull request attempts to fix https://redmine.cbrain.mcgill.ca/issues/14445. 
It redirects to a 401 error rather than a 500 error when a user tries to access an instrument when they are not logged in (ie. tries to go back a page after they have logged out).
=> [LorisForm] Returning 401 error when accessing instrument instead of 500

php/libraries/Database.class.inc
In an effort to take advantage of PHP's type system, we should add type declarations to our code, especially in the core classes.
The [PDO documentation](https://secure.php.net/manual/en/pdostatement.fetchall.php) says that `fetchAll` returns the empty set when no data in the DB matches a given query and FALSE on failure. However we do not distinguish this in our codebase and so a FALSE value is allowed to bubble up through subsequent DB calls.
This makes it so that these functions must sometimes return the Bool type (in addition to String, Array, and Null) meaning we cannot use return type declarations.
Following a discussion in #3854, this PR adds an exception when the `fetchAll` class fails. This will allow us to remove Bool as one of the return types. 
This is likely to break some …
=> [Core: Database] Add exception on fetchAll failure case

docs/API/LorisRESTAPI_v0.0.3.md
This pull request normalizes the API v3 documentation so that:
* Top-level headers are h1
* Second-level headers are h2
* Third level headers are h3
Also fixed small typos.
=> [API] Normalize headers in documentation

tools/single_use/Normalize_Consent_Data.php
Initially, we assumed that consent date would only be given if status=yes. Therefore, if status=no but there is a consent date, it is assumed that consent was withdrawn, thus, a withdrawn date is required. The script validates there being a withdrawn date for withdrawn consent. However, IBIS also takes consent date for status=no, breaking down our assumption on withdrawal. This PR removes that validation.
Edit: also adds check for empty consent status as found in IBIS data
=> [Tools/Normalize_consent] Remove validation for consent status "no"

modules/instrument_list/php/instrument_list.class.inc, modules/instrument_list/php/module.class.inc
This refactors the fix in #3721 in order to remove references
to superglobals. Instead, the variables are instantiated on the
module level from the PSR object so that the page can assume
they exist.
=> [instrument_list] Remove superglobal access

SQL/0000-00-00-schema.sql, SQL/New_patches/2018-08-22_user_activeFrom-activeTo.sql, modules/user_accounts/php/edit_user.class.inc, modules/user_accounts/templates/form_edit_user.tpl, php/libraries/SinglePointLogin.class.inc
For the project we are working at CHU Sainte-Justine we realize we will need to set (for a given user) access to the system but only for a given time window (due to policies of data access and privacy). It's a specific requirement of our project that could be useful for others. 
The way it was implemented (following @ridz1208 recommendations. Very helpful!! Thanks!) should not break/interfere others functionalities of the system. 
The changes are all additions limited to the following files:
php/libraries/SinglePointLogin.class.inc
modules/user_accounts/templates/form_edit_user.tpl
modules/user_accounts/php/edit_user.class.inc
Also it's necessary to add two fields on the Users table:
SQL/New_patches/2018-08-22_user_activeFrom-activeTo.sql
1. To access the system with a user with …
=> [Core: Login, User Accounts] Allow certain users to access the system in a time window basis

php/libraries/Module.class.inc
The default module router is supposed to delegate to the page
based on the first component of the path of the URL. A typo
means that it was using '@' instead of '/' to determine path
components, so it would only delegate to pages that have an
exact match.
=> [Router] Fix routing to subpages

modules/data_team_helper/php/data_team_helper.class.inc, modules/data_team_helper/test/data_team_helperTest.php, php/libraries/Utility.class.inc
Just ensure that `test_name` is a string. Shouldn't be too controversial.
This type coercion is causing issues with #3878 which is why it needs to be fixed.
This shouldn't alter the behaviour of LORIS. I'm not really sure how `data_team_helper` works but it should work the same!
=> [Data Team Helper] Ensure test_name is always a string

modules/candidate_list/README.md
This adds a README for the candidate list module, following
the template of the imaging browser.
=> Added README for candidate list module

CONTRIBUTING.md
This pull request modifies the CONTRIBUTING document.
Changes made:
* Update the base branch practices
* Add code formatting and branch label colours
* Re-organize information flow
* Skew tone toward on-boarding new devs
=> [Docs] Update and rework CONTRIBUTING.md

SQL/0000-00-00-schema.sql, SQL/New_patches/2018_08_27_BIDSScanTypeTable.sql
Add tables to the database to support the creation of a BIDS dataset for imaging data.
This is mostly to be used with PR #198 (https://github.com/aces/Loris-MRI/pull/198) on the MRI side.
Essentially 2 new tables are created, `bids_mri_scan_type_rel` and `bids_category`.
The former links to the `mri_scan_type` table and creates a link between the existing acquisition protocol IDs, and all the related derivatives needed from it to create a BIDS compliant dataset/filenames. The latter defines the different BIDS categories which structures the different MRI modalities in sub-directories.
More specifically, a detailed column description per table is as follows:
1) `MRIScanTypeID`: link to the mri_scan_type ID column (e.g. `44` for `t1` images in our default schema)
2) `BIDSCategory` which …
=> [MRI Preprocessing]: Adding tables to support BIDS dataset creation on the MRI side

tools/DB_date_zeros_removal.php
This PR updates the `DB_date_zeros_removal.php` script. At present, the script doesn't check if not nullable fields are date times or timestamps, so this is modified.
=> [Tools] updating date zeros removal script

tools/assign_missing_instruments.php
This shouldn't happen in a properly configured LORIS instance but just in case your test_battery/overrides aren't ironed out, you may want to avoid adding duplicate instruments into your flag+instrument tables
=> [Tools] Making sure the list of instruments to add is unique in assign_missing_instruments.php

modules/examiner/php/editexaminer.class.inc
Warnings were created when `$certificationInstruments['test']` was not set. I'm not sure what this does exactly but this code change handles the case when it's not there. 
Also fixed a typo ~~and added a return type to the function according to its PHP doc.~~
=> [Examiner] Fix warnings caused by absent variable

php/libraries/Candidate.class.inc, php/libraries/Database.class.inc, php/libraries/NDB_BVL_Feedback.class.inc, test/unittests/CandidateTest.php
This makes pselectRow error out in more invalid cases. In particular,
it throws an exception if called on a query that returns more than
one row (and as a result, also adds this behaviour to pselectOne) since
there's no way to know which row was intended. It also returns null,
not an empty array, if no rows are matched.
This improves LORIS by making latent errors more obvious
and exposing problems that might otherwise go unnoticed.
=> [Database] Make pselectRow more exceptional

jsx/StaticDataTable.js
The loris.hiddenHeaders variable has been replaced by this.props.hiddenHeaders. This is to allow the formatColumns function in reactified modules to live in the main index file for that module. States should be passed down as props, and not saved as global variables; hence the change.
The merging of this PR will allow those that reference this PR to be unblocked.
=> [JSX] StaticDataTable - Replaced loris.hiddenHeaders with this.props.hiddenheaders

php/libraries/NDB_Form.class.inc, php/libraries/NDB_Page.class.inc, src/Http/Response.php, src/Router/ModuleFileRouter.php
A couple places in our code are tightly coupled to the Zend Diactoros
Response object. This weaks the coupling by adding a class in between
which can be changed to another PSR15 implementation if desired. It
also solves the problem wherein I can never remember how to spell
"diactoros".
=> [Core] Add Response object implementation

php/libraries/Database.class.inc
In [the process](https://github.com/aces/Loris/pull/3878) of adding return types and type declarations to the
Database class, the LORIS integration tests failed when an int value was
passed to htmlspecialchars.
This PR checks that inputs to that function are of string type before
passing them as arguments.
A comment is added to this function to let developers know that
htmlspecialchars as called in the DB is not a magic bullet to preventing
JS injection.
Functionality should remain the same.
=> [Core: Database] Add type check to HTMLEscapeArray

modules/mri_violations/php/mri_violations.class.inc
This pull request fixes a bug in the MRI violations module for which it displays the same violations more than once if a candidate has visits that are spread across multiple subprojects.
Example of MRI violations before the fix for a subject belonging to two different subprojects:
Same candidate MRI violations after the fix from this PR:
How to test this PR:
Pick one candidate that shows in the MRI violations module and that has multiple visits. If all these visits are all from the same subproject, manually edit one in the `session` table so that it has a different subprojectID than all other visits (could be NULL) and:
1) check that you can reproduce the bug on 20.0-release
2) check that the bug is fixed by this PR
See also: https://redmine.cbrain.mcgill.ca/issues/14960
=> Fix duplication of MRI violations when multiple subprojects per candidate

modules/create_timepoint/php/create_timepoint.class.inc
Shifting calls a bit to rectify fault in logic. If projects are disabled all subrojects should be displayed by default when creating a timepoint (this was and still is working). When projects are enabled and the `project_rel` has data for all projects only the designated subprojects should be displayed in the dropdown when creating a timepoint (this was and still is working). When projects are enabled but the `project_rel` table IS NOT populated, no options should be displayed when creating a timepoint; this PR fixes that, before this PR the dropdown would default to all subprojects.
- empty `project_rel` table
- enable `useProjects`
- go to create_timepoint
- the dropdown should be empty
=> [create timepoint] Fix error in logic when projects are enabled

.travis.yml, modules/server_processes_manager/php/mriuploadserverprocess.class.inc
The arguments being used in getShellCommand() are user-supplied and need to be checked. This PR validates and sanitizes the values that are eventually sent to the dangerous `exec` function.
A proof-of-concept exploit is available upon request.
Come see me for information if you want to see or learn about the exploit.
=> [Server Processes Manager] Prevent OS command injection

php/libraries/NDB_BVL_Battery.class.inc
Instruments set a `table` attribute that detail the name of the table where the instrument's data is stored
The battery library should use this rather than `$testName` when inserting new rows
This is needed for a CCNA feature
=> [Core, NDB_BVL_Battery] Use instrument table attribute over test name when inserting new entries / CommentIDs

modules/acknowledgements/jsx/columnFormatter.js, modules/candidate_list/jsx/columnFormatter.js, modules/conflict_resolver/jsx/resolved_conflicts_columnFormatter.js, modules/conflict_resolver/jsx/unresolved_columnFormatter.js, modules/data_integrity_flag/jsx/columnFormatter.js, modules/datadict/jsx/columnFormatter.js, modules/dicom_archive/jsx/columnFormatter.js, modules/examiner/jsx/columnFormatter.js, modules/genomic_browser/jsx/profileColumnFormatter.js, modules/help_editor/jsx/columnFormatter.js, modules/imaging_browser/jsx/columnFormatter.js, modules/imaging_uploader/jsx/columnFormatter.js, modules/issue_tracker/jsx/columnFormatter.js, modules/media/jsx/columnFormatter.js, modules/mri_violations/jsx/columnFormatter.js, modules/mri_violations/jsx/columnFormatterUnresolved.js, modules/mri_violations/jsx/mri_protocol_check_violations_columnFormatter.js, modules/mri_violations/jsx/mri_protocol_violations_columnFormatter.js, modules/server_processes_manager/jsx/columnFormatter.js, modules/survey_accounts/jsx/columnFormatter.js, modules/user_accounts/jsx/columnFormatter.js
This replaces the typo "arrray" with the real word "array" in various javascript files.
I don't know what the origin of this typo is, but I'm tired of pointing it out in every javascript PR that bases it on something else.
(Sent to major to avoid conflicts in compiled javascript files)
=> [JS] Replace arrray with array throughout javascript files

modules/data_release/php/data_release.class.inc
The data_release test plan mentions that `2. Make sure that only the 'superuser' can ... as well as the list of already uploaded files` which makes sens but is not currently the case. this PR changes the query slightly to make sure the Admin user can see all the files and only regular users have a limited subsection.
=> [data_release] Fix access for admin

docs/Routing.md, htdocs/AjaxHelper.php
This adds a document to the docs directory explicitly telling developers not to depend on the `module/*/ajax` directory and puts in place a (commented out, until more modules are updated) deprecation warnings in AjaxHelper.php.
The document explains why the deprecation is happening and points to an example PR of how to update an ajax script to the new architecture. It can be updated to be more helpful as people have more experience doing so or find common patterns, but for now this is better than nothing.
=> Add document describing new routing

php/libraries/NDB_BVL_Instrument.class.inc
this line was generating the notice:
`PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in /var/www/loris/php/libraries/NDB_BVL_Instrument.class.inc on line 2118`
on version 7.3
i don't think this really fixes anything. from looking at the code, it seems that using a continue or a break would result in the same behavior. i decided to go with `continue 2` since that seems to be closer with what the original author had in mind and it's what my PHP version condescendingly told me to use.
for more info: http://php.net/manual/en/control-structures.continue.php
this just prevents the Warning from coming up. Warning will occur when running any script which uses `generic_includes.php` on PHP 7.3 (or so i'm guessing since this is the first i've …
=> [Instrument] Fix PHP Warning

README.md
Specifiy that Apache 2.4 is required.
Heroku deploy is no longer "new" so that is removed.
=> [Docs] Specify Apache 2.4 required in README

modules/examiner/php/examiner.class.inc, php/libraries/UserPermissions.class.inc
Now we can do
```php
return $user->hasAllPermissions(array('permission1', 'permission2', ...));
```
or
```php
return $user->hasAnyPermission(array('permission1', 'permission2', ...));
```
instead of 
```php
return $user->hasPermission('examiner_view')
|| $user->hasPermission('examiner_multisite')
|| ....;
```
Which will help to make it easier to review permissions.
=> [Core] Add hasAllPermissions and hasAnyPermission to facilitate privilege-checking

SQL/0000-00-05-ElectrophysiologyTables.sql, SQL/New_patches/2018-09-07_EEG_tables.sql
This PR includes the SQL patch to be run to create the EEG tables for the insertion scripts of the LORIS-MRI. Note that these tables will be used by the new Electrophysiology Browser module that will be in a separate PR.
This PR goes hand in hand with the following LORIS-MRI PR: https://github.com/aces/Loris-MRI/pull/337
For people that are visual, here is a screenshot summarizing the table structure for the EEG tables:
- Run the SQL patch and makes sure all statements work properly
- If you have an empty database, run the default schema with the new changes to make sure all statements work properly
- Feel free to make sure that the tables follow the LORIS SQL standard (crossing my fingers that I did not omit anything there!)
=> [New Feature] Adding the SQL patch for the EEG tables

php/libraries/User.class.inc
The `hasCenter` method enforces strict type checking, however in the function doc it explicitly says that it expects an `int`. This `int` is then forced to be compared with a `string` provided by the `getCenterIDs` method. Therefore, if an `int` is passed to the function, the result will necessarily be false.
I cast the value being stored in the CenterIDs array to ints. This allows a strict comparison between the values passed to `hasCenterID` and the `getCenterIDs` array.
=> [Core: User] Fixed Type Check for hasCenter Method - HACKTOBERFEST 2018 🎃

htdocs/main.php
Reflected XSS was possible by providing a javascript payload into the sessionID GET parameter.
This PR adds escaping to the error message in way that is consistent elsewhere in the file.
=> [Main] Sanitize Timepoint error message

modules/media/ajax/FileDownload.php, modules/media/php/media.class.inc
Previously when a user had the media_write permission but not the media_read permission they could not access the module. Although this is probably a misconfiguration, it makes sense that if someone can upload files that they should also be able to browse them.
Also added a note about whether FileDownload should be a read permission or a write permission.
=> [Media] Allow access to the module when a user has only 'media_write'

php/libraries/Project.class.inc, php/libraries/ProjectDefault.class.inc
See #3878 for more details. 
These two classes are done together so that their function signatures are compatible.
=> [Core: Project, ProjectDefault] Add type declarations to function signatures

jsx/Form.js
This allows for the possibility to sort the options of a select dropdown (render with react) by the value for both SelectElements and SearchableDropdowns. i.e. you query from the DB and pass to the JS an array of the form `$examinerID =>$examinerName`, in PHP this array looks like 
```
array(
5=>"Rida", 
1=>"Dave", 
4=>"Zal",
2=>"Henri", 
3=>"John", 
)
```
the object created in React will automatically sort the values as follows
```
{
1:"Dave",
2:"Henri",
3:"Zal",
4:"John",
5:"Rida"
}
``` 
This allows you to pass in a bool `sortByValue` that would render the options sorted by name as follows:
```
{
1:"Dave",
2:"Henri",
4:"John",
5:"Rida",
3:"Zal"
}
``` 
***PS:** To all react pros... if you have a better way of doing this, please share your wisdom with us lesser people.*
YOU BET I DIDN'T
=> [JSX/Form.js] Adding sortByValue for Selects and SearchableSelects

modules/imaging_browser/ajax/setSortedRows.php, modules/imaging_browser/php/imaging_browser.class.inc, modules/imaging_browser/php/mrinavigation.class.inc, modules/imaging_browser/php/viewsession.class.inc
The permissions string for imaging browser is pretty wacky. This PR takes advantage of a [new function](#3966 ) added on the major branch to hopefully make the permissions a little more readable.
=> [Imaging Browser] Simplify permission checking

smarty/templates/main.tpl, smarty/templates/public_layout.tpl
Without [noopener](https://mathiasbynens.github.io/rel-noopener/), an external page that is opened and is malicious or compromised gains control over the `window` of the opening page's DOM. 
Basically it allows a website partial control over the tab that a user navigated from.
Noreferrer is a workaround for the same for browsers that do not support noopener. It also scrubs the Referer header which is a tiny privacy boost.
Also checkout https://www.jitbit.com/alexblog/256-targetblank---the-most-underestimated-vulnerability-ever/
=> [Smarty] Add noopener and noreferrer to external links

modules/user_accounts/php/edit_user.class.inc, modules/user_accounts/php/my_preferences.class.inc, php/libraries/User.class.inc
After toggling the "Strict types" flag in the User class in another PR Travis gave the error `TypeError: mktime() expects parameter 5 to be integer, string given`.
This PR uses `strtotime()` to generate a password expiry date instead of `mktime()`. This way we don't have to juggle types. It also has the benefit of being more readable.
This function also standardizes the `$expiry` variable to be a string everywhere instead of a nullable string.
=> [Core: User, My Preferences] Eliminate type juggling in password expiration functionality

modules/imaging_uploader/php/imaging_uploader.class.inc
Imaging Uploader only checks if a file already exists on the front end. This makes it possible to insert duplicate scans which happens surprisingly often on CCNA. This change adds a backend check for an existing mri_upload entry that is not being intentionally overwritten / updated.
mri_upload duplicates
Open the Imaging Uploader Upload tab in two browser tabs. Fill out both simultaneously for the same scan, then submit one after the other. The first submission should go through and the other should throw an error.
=> [Imaging Uploader] Prevent duplicate insertions

modules/imaging_browser/php/imaging_session_controlpanel.class.inc
This query was throwing exceptions due to there being entries for both initial and double data entry using `pselectRow`
Fixed by excluding DDE entries
#4068
=> [Imaging Browser] Exclude DDE instruments from imaging browser instruments query

php/libraries/SinglePointLogin.class.inc, test/integrationtests/Login_Test.php
_Note: It's best to add `?w=1` to the URL when reviewing the code as there are many spacing changes._
----
Adds a log entry when a user enters the wrong password. I imagine that this was intended to be included by the original author but was left out for some reason. 
Also did happy path refactoring in this function to make it more clear. The important line is [this](https://github.com/aces/Loris/compare/bugfix...johnsaigle:180911-LogBadPasswords?expand=1#diff-2c13360f65cfe03fa685449b9074176eR321).
Finally, changed the front-end error message to say "Invalid username" instead of "Invalid email" and updated the integration tests accordingly.
=> [Core: Login] Log bad password attempts

modules/statistics/php/stats_behavioural.class.inc, modules/statistics/php/stats_demographic.class.inc, php/libraries/Utility.class.inc
See #3878 for a more detailed description.
This PR also fixes problematic calling classes in the statistics module.
=> [Core: Utility]  Add type declarations to function signatures

htdocs/api/v0.0.2/.htaccess, htdocs/api/v0.0.3-dev/.htaccess, modules/api/php/apiendpoint.class.inc, modules/api/php/projects.class.inc
Now redirect `/login` and `/projects` to the `module/api` endpoints
send a the following curl request:
```
curl -k https://<your-vm-hostname>/api/v0.0.3-dev/login -d '{"username": "your-username", "password": "your-password"}'
#put the string token from the response in a token variable
curl -k -H "Authorization: Bearer $token" https://<your-vm-hostname>/api/v0.0.3-dev/projects/
curl -k -H "Authorization: Bearer $token" https://<your-vm-hostname>/api/v0.0.2/projects/
```
Note that the `-k` option is used only if your vm ssl certificat is not up to date.
=> Fix api redirects and bugs

composer.json, composer.lock
This updates the version of phan from 0.x to 1.x, which
should also make it slightly easier to install since the
1.x line has php-ast as a suggestion rather than a requirement.
=> [Dev] Update version of phan installed by composer

modules/dashboard/php/dashboard.class.inc, php/libraries/AnonymousUser.class.inc, php/libraries/NDB_Config.class.inc, php/libraries/User.class.inc
The old function returned a string concatenated with semi-colons which is confusing and wasn't well documented. Now the function returns an array as you'd expect. I updated the calling code.
In updating the calling code I found that the function `mergeSettings()` in `NDB_Config` probably was never working correctly with multisites. `Utility::getCleanString()` would just remove the semicolons in the siteNames array, e.g. `dcc;ottawa;montreal;rome` --> `dccottawamontrealrome`. 
I don't think this was ever a valid array key which means the whole function is essentially pointless. The git blame shows that this `getCleanString` call hasn't been updated in 11 years so it's likely something we can remove.
If Travis doesn't complain I think this change should be safe.
Everything should work the …
=> [Core: User] getSiteNames now returns array instead of a string

tools/create-project.sh, tools/install.sh
This extracts the create-project.sh script from PR #1965
I've removed the bits about smarty, since they don't belong in the
project directory.
I'm sending this to major even though it's relatively minor because it's step 1 of trying to bring the debian packaging PR up to date.
To test this: try the install.sh script and ensure it still installs LORIS correctly.
=> Add create-project script

modules/acknowledgements/php/acknowledgements.class.inc, modules/candidate_list/php/candidate_list.class.inc, modules/datadict/php/datadict.class.inc, modules/examiner/php/examiner.class.inc, modules/genomic_browser/php/cnv_browser.class.inc, modules/genomic_browser/php/cpg_browser.class.inc, modules/genomic_browser/php/genomic_browser.class.inc, modules/genomic_browser/php/genomic_file_uploader.class.inc, modules/genomic_browser/php/snp_browser.class.inc, modules/help_editor/php/help_editor.class.inc, modules/issue_tracker/php/issue_tracker.class.inc, modules/media/php/media.class.inc, modules/mri_violations/php/mri_violations.class.inc, modules/mri_violations/php/resolved_violations.class.inc, modules/server_processes_manager/php/server_processes_manager.class.inc, modules/user_accounts/php/user_accounts.class.inc, php/libraries/NDB_Menu_Filter.class.inc
This PR refactors a change made in #4054. Rather than place the $fieldOptions variable in each individual class that extends NDB_Menu_Filter, this PR places the variable in NDB_Menu_Filter itself.
=> Refactor changes made in Reactification Template PR #4054

php/libraries/Database.class.inc, test/unittests/Database_Test.php
Type declarations and return type declarations are added to all function signatures in the Database class. This follows a discussion about moving toward the universal use of PHP's typing features to prevent notices, warnings, and other nasty behaviour resulting from type coercion. 
I tried not to alter any functionality by following the return types already listed in the PHP Docs for each function:
* In some cases where the documentation conflicted with the actual return type, the documentation was amended and the functionality preserved. 
* Functions that were documented as returning void but had a return statement were changed to not return anything.
* ~~Default values were largely left as is even in cases where another might arguably be better (e.g. Strings set to `null` instead of the …
=> [Core: Database] Add type declarations to function signatures

php/libraries/TimePoint.class.inc
#4049 introduced strict typing into TimePoint. While on my sandbox I found a case where getBVLQCType() needs to return null or else LORIS will crash with a TypeError.
=> [Core: TimePoint] Make return value of getBVLQCType() nullable

htdocs/feedback_mri_popup.php
When an unauthenticated user tries to access the feedback pop up it will now go through proper 401/403 handling instead of quixotically calling functions that do not exist.
=> [Feedback MRI Popup] Don't call functions that don't exist!

php/libraries/Utility.class.inc
Pursuant to the conversation in #4131, this functionality of LORIS should be documented in the code. 
Whether to use 30 day months or more accurate date calculations will be discussed in an upcoming LORIS meeting. If it's decided that LORIS should use 30 day months, this PR should be merged. Otherwise #4131 should be re-opened and merged.
Adding Blocked and Discussion Required until we know the right approach to take based on the needs of researchers.
=> [Core: Utility] Add code comment on calculateAge()

htdocs/bootstrap/css/custom-css.css, htdocs/css/panel.css, htdocs/css/simple-sidebar.css, htdocs/main.css, modules/dicom_archive/css/dicom_archive.css, modules/imaging_browser/css/imaging_browser.css, modules/imaging_browser/templates/form_viewSession.tpl
As presented in a LORIS meeting a couple months back, here is the PR of the proposed UI/UX colour/elements changes. Since then, I have removed the big orange buttons but kept links as orange on hover.
- Pick one or two of you favourite LORIS modules, and check out its new look!
- If something looks off, checkout `aces/minor` and compare the two to see if it's really an issue with this PR
- If you don't like something and have a suggestion to make it better, comment!
=> UI Makeover <3

modules/media/ajax/FileUpload.php
Users may only upload files to a candidate for a visit label at a site that the user belongs to.
This PR:
- replaces #3697, which I will be closing. this PR should include all important changes from the old PR
- cleans up #3697 by removing unnecessary changes
- removes $candIdList query and variable because it's not ever used
**Note: Media module should be refactored to have a real LORIS endpoint i.e. remove ajax. this is out of the scope of this PR. changes made here should only be sufficient to address the permission issue.**
1. On superuser/all sites account, go to Media module 'Upload' tab. 'PSCID' select element should have all candidates.
2. On non-superuser account,
- assign a set of (not all) sites
- uncheck `Across all sites access candidate profiles`
- check both `Media files` …
=> [MediaUpload] Restrict file upload to candidate who has visited user's site

php/libraries/NDB_Menu_Filter.class.inc, php/libraries/Utility.class.inc
`arrayToCsv` and `getCleanString` are only used by `NDB_Menu_Filter` and so they should go there instead of `Utility`.
This PR is based on #4118 as that PR removes the only occurrence of `getCleanString()` that occurs elsewhere.
=> [Core: Utility, Menu Filter] Move functions from Utility to Menu Filter because they're not used elsewhere

package.json
This updates the version of SWAL2 to the most recent
version in order to ensure we have the fix in
https://github.com/sweetalert2/sweetalert2/pull/1305
applied.
SweetAlert2 had a dependency on https://github.com/dominictarr/event-stream/issues/116. This updates the version in package.json to one which has the dependency removed.
(The bitcoin stealing code doesn't affect LORIS since our npm package description is not "A Secure Bitcoin Wallet", but it's still best to remove it.)
=> Update SweetAlert2 version

SQL/0000-00-03-ConfigTables.sql, SQL/New_patches/2018-11-28_add_SNR_modalities_to_config_module.sql
This moves the list of modalities on which the insertion pipeline can also compute SNR out of the profile file (a.k.a. MRI config file). Now projects can configure which of their modality they want the SNR to be computed on directly in the Config module (see screenshot below).
This PR goes with the following LORIS-MRI PR: https://github.com/aces/Loris-MRI/pull/358
=> Added the modalities for which to compute SNR to the Config module

php/libraries/BVL_Feedback_Panel.class.inc, test/test_instrument/NDB_BVL_Instrument_testtest.class.inc
Merging #4124 caused some errors to appear in Travis and make it crash. This will make every PR to major fail and also means that no candidate info can be accessed.
This PR should fix those errors. For an example see this report: https://travis-ci.org/aces/Loris/jobs/462997840
=> [Core: BVL_Feedback] Fix error that makes LORIS crash when accessing candidate info on `major` branch

modules/configuration/templates/form_subproject.tpl
This PR rewords the warning telling users that visit labels have to be manually created via config.xml. Most people aren't likely to be familiar with the language of "back-end"/"front-end". I also shifted the message to be above the form as it's easier to spot.
=> [Configuration] Clarify warning when creating new subprojects

php/libraries/NDB_Config.class.inc
Fix Loris can't load on local VM with a specific config setting. 
This function can't handle a string.
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to NDB_Config::isNumericArray() must be of the type array, string given
test loading your Loris on this branch without issue.
=> [Core:NDB_Config] fix parameter type

php/libraries/Module.class.inc, smarty/templates/500.tpl
Previously LORIS would crash and show a blank page on 500 errors OR mistakenly show a 404 page. 
This was because ~~the try-catch in Module only had a catch case for `NotFound` exceptions. Thus all exceptions were treated as 404 as a result even though it was wrong~~ of `reasons`.
On top of this, the actual exception message would be swallowed and would not appear in the error logs, making things very difficult to debug.
This PR fixes this issues and serves well-decorated 500 pages containing a message to the user. A special message is returned for ConfigurationExceptions as they reflect errors on the user's part rather than on LORIS's part. The exception information is also logged to assist with debugging.
Should address numerous issues that have arisen in PRs …
=>  [Core: Module] Handle 500 errors properly 

modules/imaging_browser/php/viewsession.class.inc, php/libraries/Candidate.class.inc
The view session page is currently broken on major for projects not using EDC. This PR fixes the bug so that projects not using EDC can still load the view session page of the imaging browser module.
=> [Imaging Browser] Fix a bug in imaging browser view session page for projects without EDC

test/phpunit.xml, test/unittests/CandidateTest.php, test/unittests/SettingsTest.php
Removing skip test in Candidate Test.
It fixes the" setExpectedException has been deprecated!"
=> [unittest] remove skip test

docs/API/LorisRESTAPI_v0.0.3.md
Small correction in the json replied by the end-point GET /candidates/$CandID/$Visit/dicoms. Closing '}'s for the objects inside the array DicomTars were missing.
This pull request `fix a small typo in the API documentation`.
=> Correction in returned object in Candidate DICOMs

package.json
Should fix errors like `ERROR in Cannot find module 'babel-core'` when compiling React files on the `minor` branch. 
Issuing this to `minor` because I think we'll probably have a minor release soon and so this will bubble up into future bugfix releases.
=> [Core] Add babel-core as a dependency on minor branch

Makefile
When `make`ing a dev environment it makes sense to install the node modules you need. Let me know if there's a reason not to do this.
=> [Core] Add "npm install" to make's "dev" target

modules/instrument_list/php/instrument_list_controlpanel.class.inc, modules/new_profile/php/new_profile.class.inc, modules/next_stage/php/next_stage.class.inc, php/libraries/Candidate.class.inc, php/libraries/TimePoint.class.inc, test/unittests/CandidateTest.php
Previously the setData() function in both of these classes accepted arrays or two separate strings. This prevents being able to use return types in these classes.
These functions were refactored to accept key-value arrays as they are occasionally called with multiple values to update. Calling functions are changed to use this new method of passing arguments.
* #4049 
* #4047
=> [Candidate, TimePoint] Refactor setData() to accept only array as argument

php/libraries/NDB_Config.class.inc, php/libraries/TimePoint.class.inc
=> [Core: Config] Add type declarations to function signatures

SQL/0000-00-00-schema.sql, SQL/New_patches/2018-11-23_insert_imaging_non_minc_file_insertion_in_notification_types.sql
This PR accompanies the LORIS-MRI PR to insert non MINC files into the database (https://github.com/aces/Loris-MRI/pull/271). In order for the notification for this new script to save in the notification table, we have to add one row to the `notification_types` table.
=> Adding "imaging non minc file insertion" to the types of notification

modules/create_timepoint/php/create_timepoint.class.inc, modules/examiner/php/editexaminer.class.inc, modules/training/php/training.class.inc, php/libraries/NDB_BVL_Instrument.class.inc, php/libraries/TimePoint.class.inc, php/libraries/Utility.class.inc, tools/populate_visit_windows.php, tools/single_use/Normalize_Consent_Data.php
Following #4133 `toArray()` is being deprecated in favour of the more precise function `associativeToNumericArray()`. This function does the same thing as toArray() but only accepts and returns arrays. 
This change reduces confusion between toArray and asArray as well as allows us to be more precise with the way we're using types.
The calling code has been updated to use the new function and the old function will throw a deprecation exception in the next release.
=> [Core: Utility] Deprecate Utility::toArray()

composer.json, composer.lock
[Guzzle](https://github.com/php-http/guzzle6-adapter) is an implementation of a PSR18 Http Client. It is used to make requests to external servers. As discussed in a recent LORIS meeting, this is required for many different functions we would like to include in LORIS. See ticket for examples.
Guzzle is chosen as it is the [most-downloaded](https://packagist.org/providers/psr/http-client-implementation) PSR18 implementation and likely to be well-maintained in the foreseeable future.
Merging this into major will allow for different features to be developed simultaneously. A good example usage will be a forthcoming update to the "Have I Been Pwned" API call in https://github.com/aces/Loris/pull/3961.
https://github.com/aces/Loris/issues/4187
=> [Core] Add Guzzle dependency

docs/API/LorisRESTAPI.md
Clarify the JSON object form replied when creating a Candidate.
The API documentation does no specify the form of the JSON object replied when creation a Candidate, the user has to figure it out.
=> Clarify response after creating a Candidate

modules/instrument_list/php/instrument_list.class.inc, modules/instrument_list/php/module.class.inc, php/libraries/Module.class.inc
Instrument List crashes on `bugfix` because the `$user` variable was not properly set. A TypeError is thrown by `responseStatus500()` as a result.
This isn't clear from the code changes but this should fix errors like:
`Fatal error: Uncaught TypeError: Argument 2 passed to Module::responseStatus500() must be an instance of User, null given, called in /home/travis/build/aces/Loris/php/libraries/Module.class.inc on line 309 and defined in /home/travis/build/aces/Loris/php/libraries/Module.class.inc:334`
=> [Core: Module] Fix errors in 500-reponse logic

php/libraries/Module.class.inc
While working on #3881 I kept running into a problem where I would have a bug but all the error log would display was something like 
```
PHP Fatal error:  Uncaught NotFound: media in /var/www/loris/php/libraries/Module.class.inc:81
```
and a generic stack trace. As a result normal PHP errors got swallowed up by the NotFound exception making it very hard to determine what was actually going wrong.
This change logs the entire path that the Module class tries to resolve and also explains what's happening behind the scenes.
=> [Core: Module] Make debugging more verbose

php/libraries/NDB_Client.class.inc
As of PHP 7.3 we can now use the SameSite flag on the session cookie to totally prevent CSRF attacks. This approach will be taken instead of ad-hoc implementation.
This PR will be marked as `Blocked` until we require 7.3 as the minimum PHP version. Travis is expected to fail for the 7.2 environment.
=> [Core: Client] Add SameSite flag to session cookie to prevent CSRF

.travis.yml, Makefile, php/libraries/UserPermissions.class.inc
This adds a "make check" target to perform basic unittests and
does some minor refactoring of the makefile
The target "make checkstatic" and "make unittests" are also
added to make it easier to quickly run a smoke test.
=> Add `make check` target

php/libraries/SinglePointLogin.class.inc
This fixes an error about password_verify getting a null but expecting
a string which could occur when attempting to login if Password_hash was
null.
=> [Login] Fix type error when attempting to log in

htdocs/api/v0.0.1/.htaccess, htdocs/api/v0.0.2/.htaccess, htdocs/api/v0.0.3-dev/.htaccess, modules/api/php/login.class.inc, modules/api/php/module.class.inc, modules/api/php/projects.class.inc, php/libraries/Project.class.inc, src/Api/Endpoint.php, src/Api/Endpoints/Projects/Project.php, src/Middleware/ETag.php
- Adding `/projects/$projectname` endpoint in the api module
- Moving endpoints in PSR-4 autoloading scope
- Adding logic in ETag middleware to not overwrite ETag header
HTTP/1.1 GET api/v0.0.1/projects/`$projectname` 
HTTP/1.1 GET api/v0.0.2/projects/`$projectname` 
HTTP/1.1 GET api/v0.0.3-dev/projects/`$projectname` 
The response should match the specification found @ https://github.com/aces/Loris/blob/minor/docs/API/LorisRESTAPI_v0.0.3.md#21-single-project
=> [API] Adding /projects/$projectname

php/libraries/NDB_Caller.class.inc, php/libraries/Utility.class.inc
This function is used in only NDB_Caller so it belongs there.
=> [Core: Utility, NDB_Caller] Move removeCommonAffix() to NDB_Caller

php/libraries/TimePoint.class.inc
This fixes a warning about htmlspecialchars expecting a string but receiving an int. It simply removes the call, since integers can't have special characters in them and the signature for the variable where $sessionID is defined is an int.
=> Fix error about htmlspecialchars expecting string but getting int

README.md
Made a bunch of changes to the presentation of the Readme. This is obviously very subjective so let me know what you think.
I mainly tried to reduce duplication, change the format to highlight the most important areas, and encourage readers to open issues and reach out to us generally.
Also removed the build status chart and replaced it with the `master` build status which was placed beside the title.
=> [Readme] Reformatting, add "Contributing" and "Help" sections

modules/instrument_list/php/module.class.inc, smarty/templates/404.tpl
When bad input is given to instrument list, LORIS will crash and the back-end will throw either a LorisException or TypeError depending on the type of input.
This PR handles these cases as a 500 response and displays an error to the user instead of crashing.
=> [Instrument List] Prevent TypeErrors from crashing instrument list

php/libraries/Breadcrumb.class.inc, php/libraries/BreadcrumbTrail.class.inc
These settings will create a Fatal error if types are used incorrectly in these classes
=> [Core] Declare strict types in Breadcrumb classes

modules/dicom_archive/php/dicom_archive.class.inc, modules/dicom_archive/php/module.class.inc
While hunting down a PHP Warning I discovered that `dicomarchiveanonymizer.class.inc` does not do any validation on the config settings it uses. This results in empty values being sent to `preg_match` with possible consequences where DICOMs are not properly anonymized. I did not actually discover a case where this is true but my dummy imaging data is very limited.
This PR adds some validation to `dicom_archive.class.inc`. It will now refuse to show DICOM data when the regex config values are not properly configured. 
Should eliminate warnings like
`
PHP Warning:  preg_match(): Empty regular expression in /var/www/loris/modules/dicom_archive/php/dicomarchiveanonymizer.class.inc on line 62, referer: https://jsaigle-dev.loris.ca/dicom_archive/
`
* If so, check out my branch and you should …
=> [DICOM archive] Ensure that settings necessary for anonymization exist

php/libraries/NDB_BVL_InstrumentStatus_ControlPanel.class.inc
CommentID is an alpha-numerical string. Removing the intval here allows me to correctly access an instrument's subtest pages.
=> [Instruments] Revert intval of CommentID because CommentID is not an int

SQL/0000-00-03-ConfigTables.sql, SQL/New_patches/2018-10-05_change_regex_config.sql, modules/dicom_archive/php/dicomarchiveanonymizer.class.inc, modules/dicom_archive/php/viewdetails.class.inc
This PR changes the default regex configurations to not contain forward slashes and replaces them with equivalent expressions. 
LORIS-MRI would like to start using the configuration options made available in the Config module,
however the current default values are incompatible with Perl
=> [Config / DICOM Archive / Imaging]Change default phantom regex config

php/libraries/NDB_BVL_Instrument.class.inc
Rida has requested that this function (used frequently in CCNA) be added to the LORIS repo. Perhaps some other projects may find it useful to have a function that returns the subprojectID. 
In CCNA we use this function particularly in cases where more than one version of an instrument exists for different cohorts. In cases where the versions differ subtly (different drop down options, or an additional question), rather than re-coding the instrument, we use if-blocks to determine what the user will see / what will be displayed depending on the current candidate's subprojectID.
1. Make a call to the function from any instrument: `$subprojectID = $this->getSubprojectID();`
2. Display the subprojectID: `print_r($subprojectID);`
3. Access the instrument from different candidate profiles and …
=> [Core: Instrument class] Added function that gets the subprojectID

.eslintrc.json
Having console.log be a javascript error encourages developers to
just use console.error (which is allowed) as a work-around while
trying to do development. Forgetting to remove the console.error
leaves us in the same state (or perhaps slightly worse) than having
the console.log would have in the first place.
This converts usage of console.log from a compilation error to a warning,
so that it can still be used for development.
We should be catching any forgotten logs in code review anyways.
=> [JS] Convert console.log from a javascript error to a warning

tools/install.sh
change to way to detect the Linux distro
It will also detect any Debian base as Ubuntu and any Red Hat base as CentOS.
unable to detect CentOS properly, was reporting unknow distro
clone the code to an empty dir and run tools/install.sh script, look for os detection message
=> [core install] use /etc/os-release to get distro info

src/Api/Endpoints/Login.php
There was an instance where an array was passed to StringStream causing a TypeError. This PR normalizes the way JSON data is passed to the StringStream class.
=> [API] Fix type error when passing JSON data to StringStream

php/libraries/NDB_Menu_Filter.class.inc
This PR adds an is_array check for foreach() .
Warning: Invalid argument supplied for foreach() in /app/php/libraries/NDB_Menu_Filter.class.inc on line 149
Warning: Cannot modify header information - headers already sent by (output started at /app/php/libraries/NDB_Menu_Filter.class.inc:149) in /app/htdocs/index.php on line 53
Warning: Cannot modify header information - headers already sent by (output started at /app/php/libraries/NDB_Menu_Filter.class.inc:149) in /app/htdocs/index.php on line 59
=> [Core] Fix PHP Warning

modules/media/ajax/FileUpload.php
`$sessionID` is a string value so `count()` causes a PHP Warning.
=> [Media] Fix call for count() on strings. Use strlen() instead

.phan/config.php, php/libraries/File_Upload.class.inc, php/libraries/NDB_BVL_Feedback.class.inc
This is a pretty straightforward rule that doesn't cause problems to include in LORIS. 
It's a good idea to progressively introduce more checks to phan to make our code cleaner. 
The issues with Feedback_MRI are addressed by #4264. Until then I'll keep the blocked label on.
=> [Testing] Add PhanTypeMismatchDefault rule to checks

.phan/config.php
My various PRs to increase phan's strictness (https://github.com/aces/Loris/projects/14) require `htdocs/api` changes. However @xlecours is converting this code to be module-based so conflicts are likely to arise. 
This PR suspends checking `htdocs/api/` with Phan as per @driusan's suggestion to deal with these conflicts.
=> [Testing] Prevent phan from checking htdocs/api since this is being refactored into a module

tools/data_integrity/fix_candidate_age.php
Minor revamp of the tool script that:
- make sure to use the table name used by the instrument rather than the value in the test_names table (BUGFIX)
- moved tool the the new directory structure
- improved readability
CCNA issue where if an instrument is named differently than it's SQL table this tool fails miserably
=> [tools/Fix Candidate Age] Cleanup and bugfixes

SQL/0000-00-03-ConfigTables.sql, SQL/New_patches/2018-11-13_add_path_to_config_enum.sql
To fix a [bug](https://github.com/aces/Loris/pull/4023 ) in the configuration module @driusan suggested that these data types be added in the back-end. This way when their values are being changed we know what should be validated as a full apache-reachable path on the filesystem.
=> [SQL] Add 'path' and 'web_path' data types to ConfigSettings

.phan/config.php
This enables the PhanRedefineClass and PhanRedefinedExtendedClass rules,
which cause no errors but were still being ignored.
=> [phan] Add two rules that created no errors

.phan/config.php, htdocs/feedback_mri_popup.php, modules/document_repository/php/document_repository.class.inc, modules/genomic_browser/test/genomic_browserTest.php, modules/imaging_uploader/test/imaging_uploaderTest.php, modules/statistics/php/stats_behavioural.class.inc, modules/statistics/php/stats_demographic.class.inc, modules/statistics/php/stats_mri.class.inc
This rule makes sure that when you pass a variable to foreach that the variable is expected to be something iterable. We had a few cases where parameters that were declared to be strings were actually arrays.
=> [Testing] Add PhanTypeMismatchForeach rule to static analysis

docs/API/LorisRESTAPI_v0.0.3.md, htdocs/api/v0.0.2/candidates/visits/images/qc/QC.php, htdocs/api/v0.0.3-dev/candidates/visits/images/headers/Headers.php, htdocs/api/v0.0.3-dev/candidates/visits/images/qc/QC.php
**Updates to the API v.0.0.3 on the imaging side:**
- Addition of scanner information to the summary header of the API for a given filename (manufacturer, model, software version, serial number)
- Addition of the image Caveat flag with the reason for the Caveat flag in the file qc page of the API
**Fix to API v0.0.2 on the imaging side:**
- The selected were not queried at the right place. The selected has been part of the files_qcstatus for several LORIS releases so updated the API queries so we can grep the Selected flag (before it returned some hash, now it returns True or False)
Did not take the time to create an issue for that. Needed for the phantom VM so I figured I would issue a PR to the LORIS repo at the same time :).
You need imaging data to test this
Yes I read it ;)
=> Update API summary header and qc too grep more info

php/libraries/NDB_BVL_Instrument_LINST.class.inc
Fixes changes made in https://github.com/aces/Loris/pull/4073 that now throws a return type error on major. XINValidate() shouldn't have a return type for now.
=> [Instrument_LINST] Fix XINValidate() return type error

.phan/config.php, php/libraries/SinglePointLogin.class.inc
This removes the intentional redeclaration of the PHP getallheaders
function in SinglePointLogin.
It was previously required because getallheaders() only existed under
Apache. According to the PHP documentation (http://php.net/manual/en/function.getallheaders.php)
it became available under the CLI server in PHP 5.5.7, so it should
no longer be required for Travis or development purposes under
supported versions of PHP.
=> [phan] Remove redeclaration of PHP internal getallheaders function

php/libraries/NDB_Notifier.class.inc, php/libraries/NDB_Notifier_Abstract.class.inc
A previous PR introduced a TypeError issue by using the PHPDoc return type as two functions' return type when the functions were not annotated properly. 
This PR removes one function altogether as it acted as a wrapper for \User which can be directly accessed. The other was changed to use the array type instead of the string type.
=> [Core] Fix TypeError in Notifier

.phan/config.php, composer.json, composer.lock, modules/instrument_manager/php/instrument_manager.class.inc, modules/login/php/passwordreset.class.inc, php/libraries/FeedbackMRI.class.inc, php/libraries/NDB_BVL_Instrument.class.inc
Our previous version of Phan was 1.0.1 and the current is 1.2.3 so I figured it was time to update. Since this is a dev-only tool updating shouldn't have any adverse effects on projects. 
Since new features have been introduced I have added the new rules to our list of ignored rules. They can be tracked and amended using https://github.com/aces/Loris/projects/14.
The PR also deletes a function in FeedbackMRI.class.inc that was [previously removed](https://github.com/aces/Loris/pull/4264/files#r248417342) and mistakenly re-added to the codebase.
=> Update Phan to newest version

php/libraries/Utility.class.inc
Utility::returnBytes returns an int in all code paths, never a string.
=> [Utility] Fix type for Utility::returnBytes function

.phan/config.php, modules/instrument_manager/php/instrument_manager.class.inc
Fix errors in instrument manager about a continue statement inside
of a switch statement. These are changed to a break, since that's
how the continue behaves in that context anyways. "continue 2" or
"break" are equivalent in this context, since the switch in question
is at the end of a loop, so breaking out of the switch will already
continue to the next iteration.
=> [phan] Fix error about continue targetting switch

php/libraries/TimePoint.class.inc
The return type for the function getBVLQCExclusionStatusList should be an array.
=> [libraries/TimePoint.class.inc] change return type to array from string

composer.json
I added the ext-json to composer.json and so the "ext-json is missing in composer.json" warning is not shown. The extension is used with JavaScript Object Notation and specifically when we use json_encode in Loris. I'm not sure if it's necessary because the method does work already without needing to require the extension in composer but it does get rid of the warning in my IDE that is setup to watch composer.json.
=> [composer] ext-json is missing in composer.json

modules/dataquery/ajax/GetDoc.php, modules/dataquery/ajax/datadictionary.php, modules/dataquery/ajax/getAllSessions.php, modules/dataquery/ajax/queryContains.php, modules/dataquery/ajax/queryEqual.php, modules/dataquery/ajax/queryGreaterThanEqual.php, modules/dataquery/ajax/queryLessThanEqual.php, modules/dataquery/ajax/queryNotEqual.php, modules/dataquery/ajax/queryStartsWith.php, modules/dataquery/ajax/retrieveCategoryDocs.php, modules/dataquery/ajax/saveQuery.php, modules/dataquery/php/dataquery.class.inc, php/libraries/CouchDB.class.inc, php/libraries/NDB_Factory.class.inc, tools/CouchDB_Confirm_Integrity.php, tools/CouchDB_Import_Demographics.php, tools/CouchDB_Import_Instruments.php, tools/CouchDB_Import_RadiologicalReview.php, tools/CouchDB_MRI_Importer.php
The $port should be an int but $couchConfig returns a string. I added the intval function when using the $couchConfig function to retrieve the port from config.xml. I also updated the comment for the constructor to reflect an int for $port and not a string.
=> [CouchDB] $port should be an int not a string

.phan/config.php, htdocs/feedback_mri_popup.php, modules/create_timepoint/php/create_timepoint.class.inc, modules/data_integrity_flag/php/data_integrity_flag.class.inc, php/libraries/NDB_BVL_Instrument_LINST.class.inc
This rule checks whether something is being treated like an array when it isn't necessarily an array. For LORIS that occurs where we are using `mixed` or `object` PHPDocs. This PR mostly uses the `asArray` function in Utility to make it clear that we are interested in arrays.
=> Add new phan rule PhanTypeArraySuspicious

modules/api/php/module.class.inc, src/Api/Endpoint.php, src/Api/Endpoints/Login.php, src/Http/Response/BadRequest.php, src/Http/Response/Conflict.php, src/Http/Response/Forbidden.php, src/Http/Response/InternalServerError.php, src/Http/Response/JsonResponse.php, src/Http/Response/MethodNotAllowed.php, src/Http/Response/NotFound.php, src/Http/Response/NotImplemented.php, src/Http/Response/NotModified.php, src/Http/Response/Unauthorized.php, src/Middleware/ETag.php
This brings current development from https://github.com/aces/Loris/pull/4244 to minor so it can be share/use earlier then when the other PR will be merged.
- Allow to generate PSR-7 responses in one line instead of repeating the same 7 lines each time.
- Login endpoint now use the new response classes
- Etag are added only if the header do not exists. (This resolves issue where etag from subendpoints were overwritten by parents endpoint.)
Todo:
=> [API] Adding json responses classes

php/libraries/SinglePointLogin.class.inc
Make it so that many bad passwords attempts result in a message telling the user they'll need to wait before trying to login again. This helps protect us in the case where an attacker would try many many logins to try to break in to LORIS.
More detailed explanations exist in the comments to the code.
Addresses rate limiting mentioned in #3314 
**Note** until [[Core: Login] Log login attempts using bad passwords](#3949) is merged, the below won't work because we don't actually log bad passwords attempts right now...
=> [Core: Login] Add rate limiting/account lockout

php/libraries/SinglePointLogin.class.inc
This remove the $_POST['username'] in favor of $username variable passed to the function as a parameter.
It fixes `PHP Fatal error:  Uncaught TypeError: Argument 1 passed to SinglePointLogin::accountLocked() must be of the type string, null given` occurring because the API consumes 'application/json' content-type and $_POST is populated only; 
> [...] when using application/x-www-form-urlencoded or multipart/form-data as the HTTP Content-Type in the request.
http://php.net/manual/en/reserved.variables.post.php
=> [SinglePointLogin] fix passwordAuthenticate accessing $_POST superglobal

modules/new_profile/php/new_profile.class.inc
I found a bug in major when creating a new profile. 
The previous code would throw an error:
Notice: Undefined index: ProjectID in /Users/alizee/Development/GitHub/McGill/Loris/modules/new_profile/php/new_profile.class.inc on line 77
Turns out the ProjectID was being made "0" when it's set as null because the intval returns 0 (when given null). New line of code fixes this bug.
=> [new_profile] Notice: Undefined index: ProjectID 

.phan/config.php, modules/dataquery/ajax/saveQuery.php, modules/imaging_browser/php/mrinavigation.class.inc, modules/issue_tracker/php/issue_tracker_controlpanel.class.inc
Add another phan rule to our checks. This rule makes sure that when array elements are accessed that they have the right type (e.g. numeric arrays should have numeric keys).
=> [Phan] Add PhanTypeMismatchDimAssignment to static analysis rules

modules/imaging_uploader/php/imaging_uploader.class.inc
Makes error message consistent with upload size limit that's displayed on the front-end in the case where `post_max_size != upload_max_filesize`
=> [Imaging Uploader] Use Utility::getMaxUploadSize() instead of ini_get

modules/new_profile/php/new_profile.class.inc, modules/next_stage/php/next_stage.class.inc, php/libraries/Utility.class.inc
Remove the `_checkDate()` function from Utility and delete instances of calling code.
* The function was declared to accept only strings and generated no bugs -- therefore it was never used in the `array` context
* The `empty()` checks at the beginning of the function always return true on a string input, therefore the function would always short circuit and not validate dates properly
* The calling code pass strings, never arrays in "QuickForm array format"
* The calling code in `next_stage` and `new_profile` are generated using JavaScript date picker elements and so there should never be an occasion where a date is manually entered by a user and require this kind of validation.
=> [Core] Remove checkDate() function from Utility

modules/brainbrowser/ajax/image.php
The paths stored in the 3 violation tables (`MRICandidateErrors`, `mri_violations_log` and `mri_protocol_violated_scans`) were wrong and a tool script has been provided on the [LORIS-MRI](https://github.com/aces/Loris-MRI/pull/403) side to correct the paths to the MINC files so that they are valid paths.
Due to the bad paths being present in those tables, brainbrowser was hacked on the LORIS side to be able to display the images. Now that the paths are corrected, this hack can be removed which also simplifies the code.
This PR goes with https://github.com/aces/Loris-MRI/pull/403 on the LORIS-MRI side where more details can be found regarding the bad paths stored in the violation tables.
Make sure to run the tool script called `cleanup_paths_of_violation_tables.pl` on the LORIS-MRI side in …
=> Brainbrowser not working after fixing paths in violation tables

modules/login/php/passwordreset.class.inc
This PR changes the module to use the `factory` function instead of the `singleton` function from the `User` class. Singleton is having issues as it returns an AnonymousUser instance when no logged-in session is active. This prevents the retrieval of the Email value for users attempting to reset their passwords.
This fix should solve the issue but the logic of this functionality should be reworked down the line.
Resolves #4360 
* Trigger a password reset email by using the "Forgot Password?" link on the front-page of LORIS. Make sure you can reset your password.
=> [Login] Fix issue where password reset emails were not sent

.phan/config.php, composer.json, htdocs/installdb.php, php/installer/Database.class.inc, php/installer/Installer.class.inc, php/installer/NDB_Config.class.inc, test/unittests/CandidateTest.php
Add a real namespace to php/installer and remove it as an
exception from phan.
There is no good reason to pretend that the classes are
the same, so this no longer does so.
=> Properly namespace php/installer and add to phan

modules/imaging_uploader/jsx/UploadForm.js, modules/imaging_uploader/php/imaging_uploader.class.inc
Somehow the name got changed and now there's a bug. I'm changing back the name to match the prop key
To test:
- on major, in 'Imaging Uploader' module, under 'Upload' tab, try to add a file to upload. the file element field stays empty and you can't click submit.
- on this branch, there are no issues
=> [ImagingUploader] Revert file upload element name

CONTRIBUTING.md
This pull request fixes the broken link to [CodingStandards.md](https://github.com/aces/Loris/blob/minor/docs/CodingStandards.md) in [CONTRIBUTING.MD](https://github.com/aces/Loris/blob/minor/CONTRIBUTING.md).
This resolves issue Github #4361 
- In the main LORIS top level directory open [Contributing.md](https://github.com/aces/Loris/blob/fixdocumentation/CONTRIBUTING.md), and click on the Coding Standards link in the second paragraph and make sure it opens to the correct file.
=> [Documentation] Fixed the link to codingstandards.md in Contributing.md

php/installer/Installer.class.inc
#4273 was just merged and flags an issue in the Installer.class.inc. Since this was merged to major, every major build will fail until this PR goes through. Not sure why it wasn't caught in the original PR.
Discovered in PR #4374 which fails with this message:
> php/installer/Installer.class.inc:127 PhanUndeclaredVariable Variable $PHP_RELEASE_VERSION is undeclared
=> [Meta] Fix Travis failure on major

tools/single_use/Engine_Change_MyISAM_to_INNODB.php
`array_merge()` re-indexes keys when creating the new merged array, the `+` operator prevent re-indexing. 
In this specific case, re-indexing is necessary because the `+` operator is truncating the array when the key is not unique across both arrays. if 2 keys collide, only the second value will be stored.
ie:
```
$a1 = array(
1 => apple
2 => orange
)
$a2 = array(
1 => godzilla
3 => banana
)
``` 
the output of `+`
```
array(
1 => godzilla
2 => orange
3 => banana
)
```
the output of `array_merge()`
```
array(
1 => apple
2 => orange
3 => godzilla
4 => banana
)
```
=> [tool/Innodb converter] Change + to array_merge() to force reindexing

test/run-php-linter.sh
Make Travis/linting less verbose by hiding messages telling us everything is fine. Only STDOUT is affected so error messages will still appear.
* Deliberately make a syntax error in a php file in LORIS. Run `make checkstatic` and it should fail and flag the syntax error
* Do the same on my branch. The same should happen but without output from `php -l`
=> [Meta] Prevent verbose "No syntax errors detected in..." from appearing in test output

SQL/0000-00-03-ConfigTables.sql, SQL/New_patches/2019-02-08_cleanup_duplicated_data_path_in_Config.sql, htdocs/api/v0.0.2/candidates/visits/images/Image.php, htdocs/api/v0.0.3-dev/candidates/visits/images/Image.php, htdocs/mri/jiv/get_file.php, modules/brainbrowser/ajax/image.php, php/installer/Installer.class.inc
This PR cleans up all the different paths that are referring to the same path (a.k.a. `/data/%PROJECT%/data/`. This gets rid of the Config settings `mincPath` and `data` and updates the code accordingly.
The code changes on the LORIS-MRI front can be found in https://github.com/aces/Loris-MRI/pull/399
Make sure that your Config setting `dataDirBasepath` and `imagePath` are configured to the proper data path (typically `/data/%PROJECT%/data`). Note that `dataDirBasepath` is the path used by the LORIS-MRI pipelines and `imagePath` is the path where the imaging data can be read by the web server.
=> Cleanup duplicated data config paths

.travis.yml
If you see this "No output has been received " at the end of Travis. 
Mostly it means you are unable to initialize the database.
Use [- docker-compose up --build] to debug it.
=> [Travis] How to debug travis when the schema changed.

modules/login/php/requestaccount.class.inc
Hey y'all! 
Charlie and I came across a weird use case that results in a 500 error on the request account page. 
Normally, if the email provided is not unique, a success message is still supposed to be displayed for security reasons. 
However, the current code only checks if the email exists under the 'Email' column in users table. In the case where the UserID and Email are different (as in, 2 different email addresses), this leads to a database duplication error. This PR addresses that problem by checking whether the email provided exists in either of the columns mentioned. 
`SELECT Email, UserID FROM users WHERE Email <> UserID;`
=> [Login: Request Account] Fixing 500 Error that arises due to email discrepancy 

php/libraries/NDB_BVL_Instrument.class.inc
a null value should be allowed here for all the `field{@}=={@}NEVER_REQUIRED` cases of xin rules.
By default any field is required by xin rules. in order to make fields not required, a rule is added to them that translates into `this field is only required if this field is equal to NEVER_REQUIRED` this bypasses the mandatory nature of xin rules on instrument fields.
If if a field have NEVER REQUIRED on it then it will probably not be filled in and thus this value here is then null which should be okai. without this PR all instruments are broken
=> [Instrument] Fix instrument typehinting

modules/server_processes_manager/php/mriuploadserverprocess.class.inc
As the tile says, when auto-launch was turned on, the MRI uploader always failed to automatically execute the MRI pipeline. This bug was introduced in 20.2. This fix should consequently be propagated to that branch also.
"Priority High", as instructed by @ridz1208
=> Fixed MRI uploader with auto-launch turned on that was not working.

htdocs/api/v0.0.2/candidates/Visit.php, htdocs/api/v0.0.3-dev/candidates/Visit.php, modules/create_timepoint/php/create_timepoint.class.inc, php/libraries/Candidate.class.inc, php/libraries/TimePoint.class.inc
This refactors the TimePoint::createNew function so that it:
1. Uses classes instead of integers/strings for its parameters
2. Does not directly access data from SQL
3. Requires the site to be passed explicitly.
It also fixes a bug where V0.0.2 of the API was not passing the CenterID to 
createNew and verifies that a user has at least one site before allowing them
to create timepoints in create_timepoint.
Fixes #4414.
=>  Refactor TimePoint::createNew

.eslintignore, webpack.config.js
This is necessary to keep supporting projects adding their own modules to webpack from the `webpack-project.config.js`
this functionality was added in https://github.com/aces/Loris/pull/3006
Everything was simplified here the only requirement is to create a `webpack-project.config.js` with the following content
```
const entry = {
'./project/modules/candidate_parameters/js/index.js': './project/modules/candidate_parameters/jsx/index.js',
'./project/modules/media/js/mediaIndex.js': './project/modules/media/jsx/mediaIndex.js',
};
module.exports = entry;
```
This will simply concatenate the lines to the `webpack.config.js` loris file and all the jsx files will be then transpiled.
Also, added the `project/*` to the ignore list for eslint since project files do not need to be linted.
- simply …
=> [webpack] simplification of the project webpack file

modules/candidate_list/php/candidate_list.class.inc
On a fresh install of LORIS candidate_list will not load and displays the error: 
```
Notice: Undefined variable: project_options in 
Loris/modules/candidate_list/php/candidate_list.class.inc on line 158
```
This PR fixes the issue by initializing the project_options outside the loop.
=> [candidate_list] fixed undefined project_options on Major

php/libraries/LegacyInstrumentTrait.class.inc, php/libraries/NDB_BVL_Instrument.class.inc, php/libraries/NDB_BVL_Instrument_LINST.class.inc, test/test_instrument/NDB_BVL_Instrument_testtest.class.inc, test/unittests/NDB_BVL_Instrument_ToJSON_Test.php
The NDB_BVL_Instrument class has two functions 
which select from the database to get metadata
about the instrument: getFullName and getSubtestList.
Neither of these are pieces of metadata that should
be coming from the database, since they're information
about the instrument itself, not data.
This makes the functions abstract, forcing instruments
to implement the functions themselves and return appropriate
values.
A trait is provided to provide the legacy behaviour for
existing instruments.
Fixes #4405.
=> Make getFullName and getSubtestList abstract

SQL/0000-00-00-schema.sql, SQL/New_patches/2019-03-20-session-notnull.sql
These should always be populated, so this updates the schema
to enforce that they can not be null.
=> Make session CenterID and Visit_label not nullable

modules/user_accounts/php/edit_user.class.inc
Remove the password check, new user the password always be null.
To test: create a new user.
=> [User_accouts] bugfix - can't create a new user

php/libraries/SessionID.php, src/Api/Endpoints/Login.php, src/StudyEntities/Candidate/CandID.php, tools/delete_candidate.php, tools/delete_timepoint.php, tools/detect_conflicts.php, tools/detect_duplicated_commentids.php, tools/generate_project_statistics_csv.php, tools/resetpassword.php, tools/single_use/Engine_Change_MyISAM_to_INNODB.php
Replaced [magic numbers](https://en.wikipedia.org/wiki/Magic_number_%28programming%29#Unnamed_numerical_constants) in LORIS with documented constants where it was
easy to do so. These were flagged by the tool PHP Magic Number Detector.
Also updated some documentation and formatting.
=> [Cleanup] Remove many magic numbers from the codebase

php/libraries/Database.class.inc, test/unittests/Database_Test.php
Modify the unsafe* family of functions to allow for a NOQUOTES option
when inserting data. This provides a middle ground between escaping all
HTML characters and none. This is important for working with JSON in the
database as escaping the quotation marks seems to make the data
difficult to work with.
Data that is stored in this way will need to be decoded using the html_entity_decode() function when it is retrieved.
- Resolves #4371
=> [Database] Add NOQUOTES as an HTML escaping option for JSON

SQL/0000-00-03-ConfigTables.sql, SQL/New_patches/2019-01-28_Add_Pwned_Password_ConfigSetting.sql, modules/login/php/passwordexpiry.class.inc, modules/user_accounts/php/edit_user.class.inc, modules/user_accounts/php/my_preferences.class.inc, php/libraries/SinglePointLogin.class.inc, php/libraries/User.class.inc, src/Http/Client.php, src/Http/Request.php
Add the [pwned passwords API](https://haveibeenpwned.com/API/v2#PwnedPasswords) into the LORIS password logic. This is part of a refactoring effort to modernize the way LORIS does passwords.
In particular, this API prevents users from creating passwords that are known to be present in previous data leaks. After a password breach, hackers compose large lists of the password and try them in brute force attacks against the sites. 
After this PR users will be prevented from creating a password like `Spring2016!` which is a bad password even though it passes the (current) LORIS password strength requirements.
#3314, #3949, #3950 
As @zaliqarosli pointed out, curl is required so if you get an error do 
`sudo apt-get install php7.2-curl; sudo service apache2 restart`
=> [Core] Add pwned passwords API to prevent common passwords and password reuse

modules/server_processes_manager/php/module.class.inc, modules/server_processes_manager/test/server_processes_managerTest.php
Fixes a white-screen-of-death when `mriCodePath` is not set and the user tries to go to Server Processes Manager
Also adds a new integration test to check for this case.
=> [Server Processes Manager] Fix LORIS crashing when mriCodePath is invalid

modules/instrument_list/templates/menu_instrument_list.tpl
This replaces the 100% width single cell table with embedded formatting
tags with a normal `<h3>` element in the instrument_list page for the
"Behavioural Battery of Instruments" header.
This is slightly prettier in the front end, and makes reading the HTML
significantly less soul crushing.
=> [instrument_list] Replace header table with HTML header element

htdocs/bootstrap/css/custom-css.css, jsx/DataTable.js
At the moment, if the data table is empty, the action buttons aren't rendered. This PR renders action buttons, i.e. to add an entry to the table, when no result found.
before: 
after:
1. choose newly reactified module with action buttons e.g. 'examiner'. manipulate the data so that the data table is empty. you will see that there is no way to add an examiner.
2. on this branch, you can add an entry to the empty table.
=> [React/jsx] Render action buttons when data table is empty

SQL/0000-00-00-schema.sql, SQL/New_patches/2019-04-04_add_image_type_to_mri_protocol.sql
This PR contains the SQL patches to run to add the `image_type` check in the `mri_protocol` and `mri_protocol_violated_scans`. 
This `image_type` header field is a key variable as this is the only MINC header that allows to differentiate between a fieldmap phase difference from a fieldmap magnitude file which have different purposes when it comes to analyses and the insertion pipeline should be able to recognize one from the other. This is also the case for MP2RAGE modalities and other modern imaging modalities, hence the need to add that field in the mri_protocol table.
Example:
- image_type for fieldmap phase difference image: `ORIGINAL\\PRIMARY\\P\\ND` (P for phase)
- image_type for fieldmap magnitude image: `ORIGINAL\\PRIMARY\\M\\ND` (M for magnitude)
Note that because of the multiple …
=> Adding the image_type to the mri_protocol when identifying for imaging protocol

tools/install.sh
In [install.sh](https://github.com/aces/Loris/blob/minor/tools/install.sh), line number 199 updated the Ubuntu version number from "14.04" to "14.04 or later",  to include later versions of Ubuntu.
=> [Install.sh/Typo] Updated Ubuntu version number to include later versions

modules/candidate_parameters/jsx/CandidateParameters.js, modules/candidate_parameters/jsx/ProbandInfo.js
Visit:
Candidate->Access Profile-> "Click on PSCID" of a Candidate Profile. Then click on the Edit Candidate Info button and your browser console will output these errors:
```
Uncaught ReferenceError: PropTypes is not defined ProbandInfo.js:328
Uncaught ReferenceError: PropTypes is not defined CandidateParameters.js:69
```
The change needed was to import PropTypes.
=> [candidate_parameters] PropTypes is not defined when clicking "edit candidate info" on major

SQL/New_patches/2019-04-26-Delete_cascades_parameter_type_rel.sql
run the New_patches/2019-04-26-Delete_cascades_parameter_type_rel.sql script on 20.0.0 database
=> fix syntax to drop foreign key in script

htdocs/bootstrap/css/custom-css.css
any buttton using the .btn class is misaligned to the right. this PR is a quick fix for 21.0 before we revamp all of LORIS's css into flexbox anyways
=> [CSS] .btn class CSS misaligned

php/libraries/TimePoint.class.inc
A brief summary of the issue: Test battery was not being populated when starting new visit stage. 
After some digging, it turned out that the issue was being caused by new session data only being updated in the database and not in the timepoint instance itself. 
This PR edits the `setData` function of the TimePoint class. When setting data for a timepoint, we should be updating the singleton instance to include the new data. 
Please refer to[ this PR](https://github.com/aces/Loris/commit/0eb134a33a2eb076177adb7865c79344b99767a9#diff-3331857654de63c280eeedba8a7fca9cL368) where this line seems to have been omitted
=> [Core/Timepoint] bug fix to update timepoint object when setting new data

htdocs/api/v0.0.3-dev/APIBase.php, php/libraries/NDB_Client.class.inc
**Solved by:**
The new change is making the session_cache_limiter be called before session_start
**Fixes:**
The LORIS API displays a warning when calling the localhost/api/v0.0.3-dev/candidates
The warning:
Warning: session_cache_limiter(): Cannot change cache limiter when session is active in /Users/alizee/Development/GitHub/McGill/Loris/htdocs/api/v0.0.3-dev/APIBase.php on line 130
```
Call Stack
--
1 | 0.0013 | 399280 | {main}( ) | .../Candidates.php:0
2 | 0.0019 | 412376 | Loris\API\Candidates->__construct( ) | .../Candidates.php:258
3 | 0.0019 | 412376 | Loris\API\Candidates->__construct( ) | .../Candidates.php:44
4 | 0.0073 | 599368 | Loris\API\Candidates->handleRequest( ) | .../APIBase.php:87
5 | 0.0073 | 599368 | Loris\API\Candidates->handleETag( ) | .../APIBase.php:103
6 | 0.0073 …
```
=> Fix Api Warning

SQL/0000-00-02-Menus.sql, SQL/New_patches/2019-05-15-LorisMenuPermissions_QC_and_datarelease.sql
the data release module has it's own permissions but QC depends on already existing permissions (that needs to be changed in the future)
=> Add QC and data_release Loris Menu Permissions

php/libraries/Candidate.class.inc
Solved by adding null as return type in case of scanner.
=> Candidate::getCandidateSex() must be of the type string, null returned in Loris/php/libraries/Candidate.class.inc on line 499 Call Stack

jsx/DataTable.js
Fixes the console react error for the FilteredDataTable Maximum rows to display for the table.
No longer will this error output:
`Warning: Failed prop type: You provided a valueprop to a form field without anonChangehandler. This will render a read-only field. If the field should be mutable usedefaultValue. Otherwise, set either onChangeorreadOnly.`
=> [acknowledgements] [FilteredDataTable] onChange handler for Maximum rows per page

modules/login/php/requestaccount.class.inc
Checkboxes are not submitted when they are not checked and thus they are not set in the `$_REQUEST` array(). added `isset()` checks to avoid warnings
=> [login] Fix login Error log notice for examiner/radiologist

jsx/Markdown.js
Fixes the "Warning: Each child in an array or iterator should have a unique "key" prop" when clicking on the "?" help_editor button.
=> [help_editor] Warning: Each child in an array or iterator should have a unique "key" prop.

modules/examiner/jsx/examinerIndex.js, modules/examiner/test/TestPlan.md
- resets 'Add Examiner' form fields to empty on closing modal
- updates test plan
=> [Examiner] Fix swal/modal closing

php/libraries/User.class.inc
This function is called statically during the change password procedure but it was not explicitly declared to be static. This generates a PHP Warning in recent versions.
Resolves #4503
=> [User] Make pwnedPassword function static

htdocs/api/v0.0.3-dev/candidates/InstrumentData.php, src/Api/Endpoints/Project/Instruments.php
Fixed by supplying string for 3rd argument of the NDB_BVL_Instrument::factor
Second commit fixes:
`TypeError: Argument 2 passed to NDB_BVL_Instrument::factory() must be of the type string, null given, called in /Users/alizee/Development/GitHub/McGill/Loris/src/Api/Endpoints/Project/Instruments.php on line 107 in /Users/alizee/Development/GitHub/McGill/Loris/php/libraries/NDB_BVL_Instrument.class.inc on line 173`
when api: `localhost/api/v0.0.3-dev/projects/Rye/instruments/bmi` is called.
=> fix api call for argument 3 needs to be string

jsx/DataTable.js, jsx/PaginationLinks.js
This PR Kills 2 bugs with one stone.
1. Pagination works again.
2. When the user is not on the first page of the datatable and alters the number of rows in the datatable via the filter such that the new number of rows is less than the previous number of rows, the user is returned to the first page of the datatable.
1. #4626
2. #3948
1. Go to your favourite reactified module.
2. Make sure pagination works.
3. Change one of the filter values
4. Make sure that you are returned to the first page of the datatable.
5. Repeat steps 1-4 for another reactified module.
=> [JSX] Fixed Datatable Pagination Bugs

SQL/New_patches/2019-05-03-deprecate_useprojects.sql
select from DUAL table as  we can't use WHERE clause in a SELECT without FROM table
Resolves https://github.com/aces/Loris/issues/4595
run the SQL/New_patches/2019-05-03-deprecate_useprojects.sql script on a version 20 database
=> Fix INSERT ... WHERE EXIST

jsx/StaticDataTable.js
Made a slight change so that Hidden Headers remain hidden in non-reactified modules.
#4634
1. Go to a non-reactified module (e.g. MRI Violations, etc.) and make sure there are no extra columns at the end of the datatable with empty rows.
2. Test another non-reactified module.
=> [JSX] Fixed Bug That Revealed Hidden Headers

modules/data_release/ajax/AddPermission.php
Bad logic in PHP code for adding permissions via the version in Data Release
=> [Data Release] Fixing PHP logic for adding permissions via versions

jsx/Filter.js, jsx/FilterableDataTable.js
Changes to the Filter are now reflected in the URL as query params. This allows the filter to be auto-loaded upon page load for all reactified menu filters. 
#4536
#4533
1. Go to a module that has a reactified menu Filter.
2. Change some of the values in the filter.
3. Make sure those changes are reflected as URL query params.
4. Refresh the page. Make sure that the query param values in the URL are populated in the filter.
5. Copy the URL to another browser window and make sure the query param values in the URL are populated in the filter.
6. Press 'Clear Filter' and make sure that the URL query params are also cleared.
7. Repeat 1-6 with another module.
=> [JSX] Enabled Filter Query Params

modules/dicom_archive/.gitignore, modules/dicom_archive/js/view_details_link.js
Fixed the broken 'Acquisition ID' link on the DICOM archive details page. The link now redirects to the MRI violations module and shows the MRI violations for the patient name associated to the DICOM archive.
1. Access the DICOM archive module and click on any archive to access its details.
2. Click on the link displayed  in the 'Acquisition ID' row and ensure that you are redirected to the MRI violations module, with the filter's patient name filled with the name of the patient who's associated with the archive.
=> Retored broken 'Acquisition ID' link on dicom archive details page.

modules/statistics/php/stats_demographic.class.inc
This addresses a FIXME issue where $visits wasn't populated. They are now populated via Utility.
On `21.0-release`
1. Go to the statistics module click on the Demo Statistics tab
2. The "Breakdown of Registered Candidates" table should be empty/filled with 0s.
On this branch 
3. The table should now contain some numbers
=> [Statistics] Fix breakdown stats issue when visits were not populated

modules/dicom_archive/jsx/dicom_archive.js
In the DICOM archive module, when downloading an archive, the patient name should be prepended to the archive file name to facilitate identification. 
Access the DICOM archive module and download any archive. Check that the downloaded file name starts with the patient name.
=> Patient name should be prepended to the name of a downloaded DICOM archive

jsx/DataTable.js
Fixes the react table to resize correctly like the past.
=> [many modules] Tables overflow background on non-reactified modules.

php/libraries/NDB_BVL_Instrument.class.inc, php/libraries/NDB_BVL_Instrument_LINST.class.inc
The `preview` variable was defined in the instrument LINST class. it is being referred to from the `NDB_Caller` class however so notices are being sent out every time a non-LINST instrument is loaded
```
[Wed May 22 14:15:16.875450 2019] [php7:notice] [pid 21882] [client 132.216.56.93:53922] PHP Notice:  Undefined property: NDB_BVL_Instrument_mri_parameter_form::$preview in /var/www/loris/php/libraries/NDB_Caller.class.inc on line 453, referer: https://abou-haider-dev.loris.ca/instrument_list/?candID=587630&sessionID=1053
```
=> [Instruments] Remove notice for undefined property: preview

jsx/DataTable.js
Fixes an issue with being unable to toggle sort again, after clicking one of the column headers of the DataTable.
=> [jsx/DataTable.js] fix toggle sort order

modules/instrument_list/php/instrument_list_controlpanel.class.inc
This notice shows when the instrument list has no instruments
```
[Wed May 22 16:24:36.707496 2019] [php7:notice] [pid 21890] [client 132.216.56.93:54728] PHP Notice:  Undefined variable: dataEntry in /var/www/loris/modules/instrument_list/php/instrument_list_controlpanel.class.inc on line 439
[Wed May 22 16:24:36.707825 2019] [php7:notice] [pid 21890] [client 132.216.56.93:54728] PHP Notice:  Undefined variable: dataEntry in /var/www/loris/modules/instrument_list/php/instrument_list_controlpanel.class.inc on line 444
[Wed May 22 16:24:36.708003 2019] [php7:notice] [pid 21890] [client 132.216.56.93:54728] PHP Notice:  Undefined variable: dataEntry in /var/www/loris/modules/instrument_list/php/instrument_list_controlpanel.class.inc on line 444
```
=> [instrument_list] remove notices when no instruments are loaded in battery

php/libraries/TimePoint.class.inc
This variable can be null in certain cases. The `sessions` table in MySQL which stores this value has a `NULL` value as the default, so it follows that this value can be `null` within PHP.
Resolves #4585
=> [TimePoint] Allow getApprovalStatus function to return null

modules/candidate_list/jsx/candidateListIndex.js
Fixes path to scan done in candidate list. 
This PR + @HenriRabalais 's PR #4590 resolve the issue #4533
=> [candidate_list] Fix path to scan 

modules/publication/help/publication.md
Added Readme.md to be the help info for the module because it describes the module.
=> [publication] help dialog info

modules/statistics/php/stats_mri.class.inc, modules/statistics/templates/form_stats_MRI.tpl, modules/statistics/templates/table_statistics.tpl, modules/user_accounts/templates/form_my_preferences.tpl
The imaging tab of statistics depends on the scan types defined in the `mri_scan_type` table. each scan type is crossmatched with a column in the `mri_parameter_form` table. if that column does not exist the SQL query is now bypassed and an error message is displayed stating that the column does not exist
> to review use the hide white spaces changes option
=> [statistics] fix imaging tab loading when Scan_Done is not in mri_parameter_form

htdocs/survey.php
Unable to proceed after the main page of the survey as it was throwing error
`Attempt to use pselectRow on a query that returns multiple rows` This PR fixes the issue.
=> [survey_accounts] Fixing unable to proceed/complete survey issue

modules/candidate_list/test/candidate_listTest.php, modules/dicom_archive/test/dicom_archiveTest.php
This test seems to fail sometimes without a clear cause, forcing us to restart Travis. This PR skips it for now and marks it as needing work.
=> [Dicom Archive + Candidate List] Skip test causing transitory failures

jsx/Filter.js, modules/candidate_list/jsx/candidateListIndex.js
Toggling the 'Show Advanced Filter' Button will append a query param to the URL that will propagate the state of the toggled filter when the loading the page with that URL.
#4540
1. Go to Candidate List module.
2. Press the 'Show Advanced Filter' Button.
3. Make sure a query param in the url is added called `hide` with value `false`
4. Refresh the page.
5. Make sure the advanced filters are still revealed.
6. Repeat steps 2-5 except by pressing the `Hide Advanced Filter` Button.
=> [Candidate List] Enabled Advanced Filter Toggle Via Query Params

php/libraries/SinglePointLogin.class.inc
the `user_login_history` table of the database has been logging the IP address of the proxy instead of the real IP of the user. to prevent that, we are checking for an IP address set in the `X-FORWARDED-FOR` variable and only if that is NULL we are fetching the `REMOTE_ADDR` and setting it.
=> [login] check for X-FORWARDED-FOR before REMOTE_ADDR

modules/dicom_archive/php/viewdetails.class.inc
When more than one MRI upload is associated to a given archive, its details cannot be displayed in the DICOM archive: an HTTP 500 error is generated (a `pselectRow` statement returns more than one row).
This PR also fixes the breadcrumbs on the DICOM archive details page: clicking on the 'details' breadcrumb if your are already on the DICOM archive details page takes you to a DICOM archive details page where all the lines in the displayed table are empty.
Access the DICOM archive and try to view the details of an archive associated to multiple MRI uploads. On the test VM, one such archive has TarchiveID=2.
=> DICOM archive details does not work when more than one upload is associated to the archive.

modules/media/jsx/uploadForm.js, package.json
change the example text to meet expectation of the code
https://github.com/aces/Loris/issues/4571 
go to media and upload a file for instrument Body Mass Index (BMI)
=> [media] Correct explainer text in the Upload tab

modules/statistics/php/statistics_site.class.inc
The `$centerID` variable was being passed as a string when it should've been an int. This caused a TypeError to be thrown.
Resolves https://github.com/aces/Loris/issues/4555
=> [Statistics] Fix type error causing "breakdown by participant" link to give 500 error

modules/imaging_browser/jsx/imagingBrowserIndex.js, modules/imaging_browser/php/imaging_browser.class.inc
to resolve: 
https://github.com/aces/Loris/issues/4635
=> [Imaging Browser] Sequence type column

modules/document_repository/php/files.class.inc
Got rid of `$fullPath` usage. Code was checking for a directory named by the file, creating a directory named by the file, and uploading the file inside this new directory. 
Fixes uploading and downloading files in Document Repository
=> [Document Repository] Fixing bug in pathing

modules/timepoint_list/php/timepoint_list.class.inc, src/Router/BaseRouter.php
Fixes the breadcrumb containing an extra forward slash. Ex. http://localhost//162517/
https://github.com/aces/Loris/issues/4723
=> [timepoint_list] Breadcrumb link fix for Candidate profile

src/Data/Filters/UserSiteMatch.php
When a CenterID is null, the code falls through to the exception, but
the error message is misleading. The resource had a getCenterID, it
just returned null. Add a more explicit error message.
=> [Data Provisioner] Throw more explicit exception when CenterID is null

SQL/9999-99-99-drop_tables.sql
This PR adds the publication tables to the drop table SQL patch.
No issue reported. Found out this when reloading RB dataset from scratch.
=> added the publication tables to the drop tables SQL patch

modules/configuration/test/TestPlan.md
correct the test plan for latest update in the config page (use projects yes/no button) and 
removed the project-subproject relation check
-  https://github.com/aces/Loris/issues/4771 
- https://github.com/aces/Loris/issues/4772
open the TestPlan for the configuration module and check  section `Project`
=> [Configuration] remove `use projects` details and project-subproject relation check from the test plan

modules/issue_tracker/jsx/issueTrackerIndex.js, modules/issue_tracker/php/issue.class.inc
There was a regression introduced in #4112 where the issue tracker
links reverted to getting the ID from a query parameter instead
of the URL. This was done inconsistently, and as a result some
places loaded URLs such as "...&issueID=?issueID=1". This fixes
the links to parse the ID from the URL, so that issues can now
be loaded with the php development web server.
=> [Issue Tracker] Fix incorrect links to individual issues

modules/dashboard/js/dashboard-helper.js, modules/dashboard/php/dashboard.class.inc, modules/dashboard/templates/form_dashboard.tpl
While testing the login module, I noticed that the 'Account pending approval' link on the dashboard wasn't working. This PR fixes that as well as the other links I found broken on the Dashboard module.
=> [Dashboard] Fix href link locations

htdocs/api/v0.0.2/candidates/InstrumentData.php
Instrument endpoint on the candidate level (https://test.loris.ca/api/v0.0.2/candidates/475906/V3/instruments/bmi) returned a 500 error. This PR fixes the issue.
Note: this error was found only on v0.0.2 (v0.0.3-dev worked fine)
No issues reported as the bug was fixed in this PR directly
=> [API v0.0.2] Fix API candidate level instrument endpoint

htdocs/api/v0.0.2/.htaccess
The link to `QC.php` script was incorrect in `htdocs/api/.htaccess` which resulted in the following error:
Not Found
The requested URL /api/v0.0.2/candidates/visits/images/qc/Qc.php was not found on this server.
Example: https://test.loris.ca/api/v0.0.2/candidates/475906/V3/images/demo_475906_V3_t2_001.mnc/qc
Note: bug only present in v0.0.2 (v0.0.3-dev was working fine)
No tickets created as the bug was fixed when found.
=> [API v0.0.2] fix the image QC endpoint

modules/brainbrowser/jsx/Brainbrowser.js
The value in the image size dropdown was not changing value
because "this" wasn't bound in the handleChange function. This
binds it in the constructor so that it changes to the correct value.
Fixes #4766
Note: I don't have any images to test this on locally, I could only
verify that the dropdown changed value whereas it didn't previously.
=> [Brainbrowser] Fix image size dropdown

modules/imaging_browser/jsx/imagingBrowserIndex.js
The imaging browser data table had a "Sequence Type" column
added by #4692.
This was unintentional, as the data is only there for the
filter. The table does not properly format/display it and
will likely not scale to large protocols.
This sets the column back to hidden, but the filter should
still work.
=> [Imaging Browser] Hide Sequence Type in data table

modules/imaging_browser/test/TestPlan.md
The show data button was removed as filtering is now
done live.
Fixes #4714.
=> [Imaging Browser] Remove reference to Show Data button

htdocs/api/v0.0.2/.htaccess, htdocs/api/v0.0.3-dev/.htaccess
This PR fixes the `format/brainbrowser` endpoint of an image for both version of the APIs. The link to the `BrainBrowser.php` API script was not present in either `.htaccess` file
No issue reported as the bug was fixed as soon as found.
=> [API] Fix the image brainbrowser endpoint of the API

htdocs/feedback_mri_popup.php, php/libraries/FeedbackMRI.class.inc
The fieldname was incorrectly being cast to an int, which
was resulting in the ParameterTypeID not being found when
loading the value after having been saved.
Fixes #4784.
=> [Imaging Browser] Fix loading of dropdowns in MRI QC

modules/imaging_uploader/jsx/UploadForm.js
This PR add the display of the error message in the submission error pop up window at the time of upload of larger files than authorized.
=> [imaging uploader] Display error message in the Submission Error pop up at the time of upload

htdocs/AjaxHelper.php, htdocs/router.php, modules/issue_tracker/ajax/EditIssue.php, php/libraries/NDB_Client.class.inc
When running under "php -S", the router does not correctly
match paths that have query params, because the $_SERVER['REQUEST_URI']
includes the "?foo=bar" part of the URI, which causes the
regex matching to fail.
This updates the code to use $_SERVER['PHP_SELF'], which
only contains the path portion of the URL. (However, since
the regex is only used for routing, the host is irrelevant
at this point.)
To test this change load a URL which contains query parameters
(in particular, any ajax call) using the built in PHP web serer.
=> [Router] Fix ajax scripts with built in PHP web server

jsx/Filter.js
This fixes 2 bugs relating to the handling of how "nothing" is handled in multiselects.
1. The empty option is removed, because it has undefined semantics and the way that it works for single selects (ie. act as no filter) is better expressed by simply unselecting everything
2. A bug regarding unselecting everything from a multiselect is fixed. Before this, it was filtering out all results, instead of resetting the filter to not filter anything.
Fixes #4794, #4713
=> [JSX] Improve handling of empty multilselects

htdocs/feedback_mri_popup.php, php/libraries/FeedbackMRI.class.inc
The top of the imaging browser qc popup contained the following warnings for me:
```
Notice: Undefined index: fire_away in /Users/driusan/Code/Loris/htdocs/feedback_mri_popup.php on line 43
Notice: Undefined variable: comments in /Users/driusan/Code/Loris/php/libraries/FeedbackMRI.class.inc on line 164
Notice: Undefined variable: comments in /Users/driusan/Code/Loris/php/libraries/FeedbackMRI.class.inc on line 164
Notice: Undefined variable: statusField in /Users/driusan/Code/Loris/php/libraries/FeedbackMRI.class.inc on line 350
Notice: Undefined variable: statusField in /Users/driusan/Code/Loris/php/libraries/FeedbackMRI.class.inc on line 351
```
This fixes them so that the window loads cleanly.
=> [Imaging Browser QC] Fix Notices when loading imaging browser MRI QC window

modules/imaging_browser/php/imaging_session_controlpanel.class.inc
When no linkedInstruments config setting are defined, $config->getSetting()
can return an empty string. This results in a warning about invalid
argument in foreach in the imaging browser control panel.
This simply converts anything that isn't an array into an empty
array to fix the warning.
=> [Imaging Browser] Fix Invalid argument support for foreach error

modules/issue_tracker/ajax/EditIssue.php, modules/issue_tracker/jsx/issueTrackerIndex.js, modules/issue_tracker/php/issue.class.inc
Fix the loading of the form for the "new issue" page on
the issue tracker. It currently just displays an error
page after clicking the link.
Fixes #4811
=> [Issue tracker] Fix loading of "new issue"

modules/issue_tracker/jsx/IssueForm.js
When rules are violated creating a new issue, the JSON includes
a message describing the error, but the front end currently throws
it away and display a generic error message.
This updates it to use the message from the server.
Fixes #4764.
=> [Issue Tracker] Display errors to user when creating a new issue

modules/issue_tracker/php/issuerowprovisioner.class.inc
The query for the issue tracker was joining the issues_watching table for
the watching filter, but not restricting the join to the current user. This
resulted in the row being duplicated n times for the number of watchers,
and the "Watching?" filter returning rows if there were any watchers, not
only the current user.
Fixes #4810, #4813.
=> [Issue Tracker] Fix "Watching" filter and duplicated rows in issue tracker

modules/dicom_archive/test/TestPlan.md
This fixed the documentation of 'Dicom Archive' module TestPlan Item 2, since 'Selection Filter' became not clickable in the newer version.
=> Fix dicom archive test plan item2

php/libraries/NDB_BVL_Instrument.class.inc, tools/exporters/data_dictionary_builder.php, tools/generate_tables_sql.php, tools/generate_tables_sql_and_testNames.php, tools/lorisform_parser.php
In some instances of the code, we still refer to `quickform_parser.php` in the documentation/comments while the script has been renamed to `lorisform_parser.php`. This PR corrects those misleading instances.
No issue reported as this was found while testing the data dictionary builder tool and looking for `quickform_parser.php`.
Nothing to test since this is only comments and documentation changes
=> Update the code comments and the code documentation to refer to lorisform instead of quickform

php/libraries/SinglePointLogin.class.inc
The SinglePoint login was redirecting the password-expiry page to the
password-expiry page when the same password was entered, which was
resulting in the error message disappearing before it got to the
login module. This suppresses the redirection if that was already the
page destination.
Fixes #4756
=> [Login/Password Expiry] Fix bug preventing "same password" message from being seen

tools/exporters/data_dictionary_builder.php
replaced DELETE query using multi-JOIN by 2 query
https://github.com/aces/Loris/issues/4615
run the tools/exporters/data_dictionary_builder.php script
=> [tools] 2019 06 10 fix data dict builder

package-lock.json
Every time I run "make", the package-lock.json file
changes because somehow the URLs all changed from http
to https.
This updates the lock file to use https.
=> [NPM] Change URLs in lock file from http to https

modules/media/ajax/FileUpload.php
All types of errors were being returned to the user as
internal server error. This was clearly incorrect in
some situations where the error was caused by user error.
Update the showMediaError to take a status code to go
with it, and at the same time improved some error messages
(such as permission denied, which didn't include any
message at all before this change.)
=> [Media] Fix HTTP response codes when uploading files

modules/media/test/TestPlan.md
Update media module test plan to clarify that a modal
window is opened, not a new page.
Fixes #4739.
=> [Media] Update test plan to reference modal window

tools/install.sh
- change the message on how to install composer if not already done
- create user_uploads dir if are not existing before changing group ownership
https://github.com/aces/Loris/issues/4825
https://github.com/aces/Loris/issues/4824 (first item only)
for the message, run the script on a server where composer is not installed (or not accessible), check that new instruction are showne.
For second part run the script on a new installation of Loris (in a new directory i.e. /tmp or ~/) and check that the 2 directories are created and have group set to www-data (Ubuntu)
=> [tools] fix message to install composer,

modules/media/jsx/editForm.js, modules/media/jsx/mediaIndex.js
This fixes 2 problems when a user does not have write permission:
1. The reason the update failed is not given to the user.
2. The user should not have seen the button in the first place.
Fixes #4737.
=> [Media] Fix errors for users with no media_write permission

modules/configuration/js/project.js
This PR customizes the error message shown in the configuration module under the project section when someone tries to save a target recruitment that is not a number. Now proper error message is displayed to the user telling them that the recruitment target must be a number.
=> [Config] Fix error message in the project page of the configuration module

php/libraries/NDB_BVL_Instrument.class.inc
fixes https://github.com/aces/Loris/issues/4808
to test:
=> [Breadcrumbs] Instrument test_name to Full Name

modules/issue_tracker/ajax/EditIssue.php
Fix warnings/notices that are printed (resulting in invalid json in the response)
when creating an issue where optional fields are not set.
Fixes #4817
=> [Issue Tracker] Fix warnings when optional fields are not set in new issue

php/libraries/IdentifierGenerator.php
fix creation of first ID in sequential mode with min value. 
Currently create a php fatal error
- create a new test site
- set PSCID generation to sequential with min value `"min"=1`
- create a first candidate for this site PSCID should be `<sitealias>0001` if `"minLength"=4` as been set.
=> [core] 2019 06 03 fix id generation

modules/mri_violations/php/resolved_violations.class.inc, modules/mri_violations/test/mri_violationsTest.php
This pull request fixes a bug in the MRI violations module for which it displays the same violations more than once if a candidate has visits that are spread across multiple subprojects.
How to test this PR:
Pick one candidate that shows in the MRI violations module and that has multiple visits. If all these visits are all from the same subproject, manually edit one in the `session` table so that it has a different subprojectID than all other visits (could be NULL) and:
1) check that you can reproduce the bug on 20.0-release
2) check that the bug is fixed by this PR
See also: https://github.com/aces/Loris/issues/4781
(Note: a similar fix had been sent for the unresolved tab of the module, see https://github.com/aces/Loris/pull/3860)
=> [mri_violation ] Fix resolved violated scans duplication

modules/document_repository/php/files.class.inc
Update error message when there's a failure to create a
directory in the document repository, so that the sysadmin
can try and figure out what's happening. (This exception
message shows up in the web server error logs, not to the
user.)
=> [Document Repository] Include path in web server error log

modules/issue_tracker/jsx/IssueForm.js
Fix a warning that appears in the javascript console when a user
has multiple sites affiliated.
Fixes #4727.
=> [Issue Tracker] Fix javascript console warning multisite user

modules/timepoint_list/test/TestPlan.md
The test plan was not clear enough on which permission is required in order to view the "Create time point", "Edit Candidate Info" and "View Candidate Info" buttons on the timepoint list page. This PR clarifies those.
=> [Timepoint list] Clarifying test plan

modules/imaging_uploader/jsx/ImagingUploader.js, modules/imaging_uploader/php/imaging_uploader.class.inc
The data table of the browser page of the imaging uploader showed several flaws:
- a PatientName name column was present in the header of the table but not the content (was not properly hidden)
- The Tarchive Info column showed the tarchiveID instead of the "View details" link to the DICOM archive module for that tarchive ID
- The Number of MINCs created column leads to the ViewSession page of the imaging browser since a given upload will always be linked to only one SessionID. 
- The header row has prettier strings for the eyes
Check that the improvements mentioned above works better in this PR than on the current 21.0 branch.
=> [Imaging Uploader] Fix browse data table

modules/candidate_parameters/test/TestPlan.md
The test plan for consent status in Candidate Parameters seems to be outdated. This PR updates the test plan with the last major release changes made in consent status.
(As of the last major release, Date of Consent is required for both Yes/No consent)
=>  [Candidate Parameters - Consent Status]Test Plan Update

jsx/Form.js, modules/new_profile/jsx/NewProfileIndex.js, modules/new_profile/php/new_profile.class.inc, php/libraries/LorisForm.class.inc
fixes https://github.com/aces/Loris/issues/4728 and https://github.com/aces/Loris/issues/4564
to test:
caveat: Firefox allows 5/6 digit years because the "max" attribute breaks on that browser
=> [new_profile] Fix 6 digit years & month functionality

htdocs/api/v0.0.3-dev/candidates/Visit.php
casting CandID object into an integer to fit Timepoint::validateVisitLabel signature
Send a PUT request to /candidates/<candid>/<visit_label> . A 201 should be returned
=> [API] Fix PUT /candidates/visits

jsx/DataTable.js
At the moment, all data tables are by default sorted in ascending order by the second column. we want to sort by default the first 'No.' column
this PR fixes the default column value and restores it to what it was before this testing round
=> [jsx/DataTable] Default sort order by first column

modules/candidate_list/php/validateids.class.inc
Open Profile gets stuck validating when you try to input a DCCID that contains alphabet characters. This PR adds a validation to check if DCCID is an integer.
=> [candidate_list] Check If DCCID is an Integer String

modules/user_accounts/php/edit_user.class.inc
Spaces are not allowed anymore in user names. This PR implements this new restriction.
This replaces #4744, which is now closed.
=> Do not allow whitespace characters in user names.

htdocs/api/v0.0.3-dev/Candidates.php, php/libraries/Candidate.class.inc
The documentation of v0.0.3-dev differ from v0.0.2 for POST request sent to /candidates.
A `CandidateObject` should be returned instead of the CandID alone
This adds the CandidateObject to the response.
Send a POST request to /candidates and see if the response format fits the documentation
=> [API] Fix POST /candidates response format

modules/issue_tracker/ajax/EditIssue.php
Fix changing the "Watching?" dropdown when editing an issue. There
were 2 problems:
1. The code was checking if a statement returned an array to determine
if there was data. Comparing to null is more reliable.
2. The Watching? insert statement was done before Other watchers. This
was unreliable, since Other Watchers starts by deleting all watches.
Fixing both of these issues resolves both the saving and display of
the Watching? dropdown when editing an issue.
Fixes #4582
=> [Issue Tracker] Fix watching dropdown when editing issue

modules/examiner/php/editexaminer.class.inc
Cannot access Edit Examiner page when you have permissions to view and edit examiner but your certification is not enabled in config.xml. This PR adds a ConfigurationException so that if your certification is not enabled, you will get an error message that reads "LORIS configuration settings are invalid or missing and as a result execution cannot proceed" instead of "You do not have access to this page."
=> [examiner] Add a ConfigurationException When Certification Disabled

htdocs/main.css
Fixes page cutoff on instrument builder and any other page where there's not enough content to make the page bigger than the screen.
- As reported by Yang Ding
=> [Instrument_builder] Fix page min-height for list

modules/dataquery/jsx/react.tabs.js, php/libraries/CouchDB.class.inc
1. runQuery javascript function was called with the expected parameters.
2. Content-Lenght header value now fit the content-length of the data sent.
Go to DQT, select fields, run query... does results appear? For some reason, the tab shows the info tab content instead of results... the tester need to switch tabs. 
See:  https://github.com/aces/Loris/issues/4905
=> [DQT] Fix data not loading

php/libraries/NDB_BVL_Instrument.class.inc
Instrument level breadcrumb lead to the dashboard. This PR fixes the issue and the breadcrumb now return to the instrument page.
=> Fix instrument level breadcrumb

modules/dataquery/jsx/react.app.js, modules/dataquery/jsx/react.tabs.js
Using the Active property of TabPane to "select" the Active tab
Bonus: fix Warning: Each child in an array or iterator should have a unique "key" prop in the render method of `StatsVisualizationTabPane`
=> [DQT] Fix info tab showing instead of query results

.phan/config.php
We get this rule for free! No existing issues in LORIS.
=> Add new phan rule PhanTypeExpectedObjectPropAccessButGotNull to static analysis

Dockerfile.test.php7
The base docker image for PHP was upgraded to add support
for Debian Buster 6 days ago. Debian Buster doesn't ship with
MySQL, but instead uses the (compatible) MariaDB client. This
updates the docker file to install mariadb-client instead of
mysql-client, and fix the Travis errors that are currently
happening when building the LORIS docker image.
See also: https://stackoverflow.com/questions/57048428/e-package-mysql-client-has-no-installation-candidate-in-php-fpm-image-build-u,
https://github.com/docker-library/php/commit/ccbe53516fa2fd2d3b0ba680b83148b443a6ccf1
=> [Travis] Update Dockerfile to use MariaDB instead of MySQL

tools/exporters/DB_dump_table_data.php
Resolves #4878 by changing the export location to be built using the base URL instead of using a relative path.
Also adds some cleanup.
=> [Tools] Fix Raisinbread exporter location

smarty/templates/install.tpl
I made changes to the [Loris/smarty/templates/install.tpl](https://github.com/aces/Loris/blob/minor/smarty/templates/install.tpl) file to fix the formatting of the checkboxes in the loris-url/installdb.php frontend.
Here is the original formatting:
And the fixed formatting:
Since Loris is already installed, you will need to move the config.xml file out of the project folder so that when you check out <loris-url>/installdb.php, it does not say "Loris already installed".
1. Move config.xml from loris/project to another folder (ex. just the loris folder)
2. Put loris-url/installdb.php in browser (ex. for me, it is alivadas-dev.loris.ca/installdb.php)
3. Check that the changes were made.
=> [install] Fixed checkbox formatting in installdb.php frontend

modules/dataquery/php/dataquery.class.inc
If your `project/config.xml` file does not contain entries for `CouchDB` values, LORIS crashes with a blank page. 
This PR prints a simple error message and logs a more informative error instead of crashing.
=> [DQT] Fix crash when CouchDB values not set in project/config.xml

php/libraries/NDB_BVL_Instrument.class.inc
Changing logic in functions `getSubprojectID` and `getVisitLabel` to accommodate a change in return type that was made to function `getSessionID` in instrument class. The change in return type was made here #4073 : https://github.com/aces/Loris/pull/4073/files#diff-b5d8239d1c2c763a7e09840eb58ee20bL1411
On CCNA we get the following error:
```
[Wed Jul 17 17:00:42.428543 2019] [php7:error] [pid 14598] [client 142.157.25.61:54151] PHP Fatal error:  Uncaught LorisException: Failed to retrieve data for timepoint -1 in /var/www/loris/project/libraries/TimePoint.class.inc:146\nStack trace:\n#0 /var/www/loris/project/libraries/TimePoint.class.inc(90): TimePoint->select(-1)\n#1 /var/www/loris/php/libraries/NDB_BVL_Instrument.class.inc(1454): TimePoint::singleton(-1)\n#2 …
```
=> [Core: Instrument] Fix bug related to altered return type

Dockerfile.test.php7, src/Api/Endpoints/Projects.php
This add a call to `hasAccess` function in `/projects` to lomit the access to logged in users only.
This also add mariadb-client to DockerFile.php7 because it was never added in 21.0
1. send a curl request to /projects or any subendpoints before being logged in. It should return a `HTTP/1.1 401 Unauthorized` response code with `{"error":"unauthorized"}` as body content.
=> Checking for logged in users

SQL/New_patches/2019_07_04_remove_header_row_from_parameter_file_and_convert_back_to_Value_field_to_text.sql
Until now, the whole header of a MINC file was dumped into a row of parameter_file, taking a lot of space in the database and the SQL dump created for that table, while not being used at all.
During the imaging meeting of July 4th, a decision has been made to no longer store that row to gain some space in the database, hence, removing it from the imaging pipeline code.
This is linked to https://github.com/aces/Loris-MRI/pull/453 PR on the LORIS-MRI side.
Note: the API does not look specifically for that header but dumps all the values present in the `parameter_file` table so no changes were needed.
=> [Clean up] deletion of the full MINC header entry from parameter_file as not used anymore

modules/candidate_list/php/candidate_list.class.inc, modules/candidate_list/php/candidatelistrow.class.inc, modules/candidate_list/php/candidatelistrowprovisioner.class.inc, php/libraries/DataFrameworkMenu.class.inc, php/libraries/File_Upload.class.inc
This updates the candidate_list module to use the LORIS data framework. It does so by adding a new abstract DataFrameworkMenu class, which can be extended in order to remove some of the boilerplate of converting menu filters to the data framework.
In order to use the DataFrameworkMenu class, an implementation must supply:
1. a getFieldOptions function which returns a list of fieldOptions to include in the array for the frontend
2. a getBaseDataProvisioner function which returns a data provisioner
3.  a useSiteFilter function which returns whether or not the data provisioner should have the UserSiteFilter match applied.
In return, the class takes care of using that dataprovisioner, adding default LORIS data filters, and serializing to JSON in the format expected by react menu filters.
=> [Data Framework] Update candidate list to use data framework

php/libraries/Database.class.inc
The getAffected() function was unused. Upon trying
to use it, I discovered that it was also always
returning "0" after an update regardless of how many
rows were actually updated. This removes the function
and related code so that no one accidentally tries to use
a function which silently returns an incorrect result.
Resolves #4972.
1.
*
=> [Database] Remove unused function

composer.json, composer.lock, test/unittests/Loris_PHPUnit_Database_TestCase.php, test/unittests/NDB_BVL_FeedbackTest.php
This PR takes over some of the responsibility of #4433. 
It is concerned only with removing the DB Unit package which is blocking PR #4914.
I'm not sure if this will actually worked but Shen says we don't actually use this package and made moves to remove it. 
1. Travis should succeed. No manual testing necessary.
* Covers some of the functionality of #4433 
* Unblocks #4914 (and therefore #4928) once merged.
=> [Testing] Remove DB Unit package

php/libraries/NDB_Config.class.inc, php/libraries/User.class.inc
Adds a new helper function `settingEnabled` to determine whether a boolean-style config setting is enabled or not.
This is designed to add some syntactic sugar and  hide some of the implementation details of our Config library from calling code. 
The calling code only cares whether a setting is enabled. Developers shouldn't need to concern  themselves with doing a strict string type comparison on config settings.
e.g. this code:
```php
if ($config->getSetting('useEDC') === 'true') {
...
}
```
can now be written as
```php
if ($config->settingEnabled('useEDC')) {
...
}
```
I feel like this is an improvement because it's a bit cleaner. I think it removes some potential confusion also as it's not immediately clear why LORIS code is doing a string check for something that looks like a bool.
=> [Config] Add settingEnabled() helper function

test/unittests/VisitTest.php
Adding to unit tests for the Visit.class.inc and VisitController.class.inc libraries. 
This PR completes the basic test coverage of the Visit and VisitController classes.
Run `npm run tests:unit -- --filter Visit` or check out Travis!
=> [Test] Adding to unittests for Visit and VisitController

package-lock.json
When running `make` on various branches I noticed that several packages we use are marked with high security vulnerabilities. I used `npm audit fix` to address them.
All I did:
`git fetch aces`
`git checkout aces/minor`
`make dev`
`npm audit fix`
and then committed the package-lock.json file.
=> [Node] Update insecure npm packages

raisinbread/README.md, raisinbread/instruments/instrument_sql/9999-99-99-drop_instrument_tables.sql
This includes instructions on how to delete a RB dataset when needing to empty a database with the RB dataset. It includes a patch to delete first the instrument tables and then uses the already existant `9999-99-99-drop_tables.sql` in the SQL directory.
1. Try running the delete instructions in the README.md and check that all tables from the RB dataset were removed.
* Resolves #4990
=> [RaisinBread] Adding instructions on how to delete the RB tables

smarty/templates/install.tpl, tools/setconfig.php
This adds a new script to change the config settings
in the database without SQL access. This may be is useful
when the Config module page is unavailable due to bad
paths or otherwise when providing user support, where
it can be easier to just tell the user what to type
copy/paste in a terminal than describe where to find
a setting on the frontend.
1.
*
=> [Tools] Add script for changing config settings

tools/install.sh
Provide an error message and die if the user is trying
to run install.sh as root. The install script invokes
sudo, and should not be directly invoked as root.
1.
*
=> Add check for running install script as root.

test/README.md
The setup instructions in the [README.md](https://github.com/aces/Loris/tree/minor/test) includes a link to information on how to create a Docker Group. The link was incorrect and I changed it to point to the correct information!
Take a look at the README and check that the link is correct! It should point to Docker documentation that details how to create a docker group.
=> [Documentation] Changed link to Docker Group info in test/README.md

php/libraries/NDB_Config.class.inc, test/unittests/NDB_ConfigTest.php
I am adding unit tests to [NDB_ConfigTest.php](https://github.com/aces/Loris/blob/major/test/unittests/NDB_ConfigTest.php) for the [NDB_Config.class.inc](https://github.com/aces/Loris/blob/major/php/libraries/NDB_Config.class.inc) library. 
I also changed some of the singleton() declarations, which is related to issue #4989 
Run `npm run tests:unit -- --filter NDB_Config` under `/var/www/loris` or check out Travis
* Closed PR for previously completed NDB_Config tests: #4383
=> [Test] Adding to unittests for NDB_Config.class.inc

README.md
As of (at least) version 21, it's necessary to use new-ish versions of NodeJS in order to properly package and run the LORIS front-end React components.
In lieu of a package or container or bootstrapping post-install script, we should at least make it clear that this is as essential to getting a non-development LORIS started as MySQL, Apache, etc.
=> [README] Add nodejs as a system requirement

Makefile
The vendor directory created by composer is a directory, not
a file, so it needs to be deleted with "rm -rf", not "rm -f".
1.
*
=> Fix make clean build target

php/installer/Database.class.inc, php/installer/Installer.class.inc
The code which checks if the connection to the database failed
was assuming $db->connect() throws an Exception. However,
$db->connect() catches all exceptions and returns false.
Check return value so that an error is displayed to the user
if the credentials are incorrect on the first page of installer.
=> Show error when installdb.php can not connect to database

tools/exporters/DB_dump_table_data.php
The previous iteration of the script was dependent on the existence of a mysql configuration file (`.my.cnf` for example). this instead makes it depend on the quat values in the configuration file
=> [tools/raisinbread exporter] Use config.xml credentials

modules/examiner/php/editexaminer.class.inc
Bugfix for DomainException that was being thrown in examiner module. Please see ticket that is linked below for full description of the issue that this resolves. 
1. Update a certification for any examiner. 
2. Refresh the page and ensure that no 500 error is thrown.
#4980
=> [Examiner] Bugfix for pselectRow returning multiple rows (certification_history)

php/libraries/NDB_BVL_Instrument.class.inc
Was getting the following error when running the tool script `fix_candidate_age.php`. 
```
lorisadmin@jcallegaro-dev:/var/www/loris/tools/data_integrity$ php fix_candidate_age.php confirm
Instrument: Teams_Visit_Checklist_V4 (12-Month Visit (Visit 4) Checklist)
PHP Fatal error:  Uncaught ArgumentCountError: Too few arguments to function NDB_BVL_Instrument::getCandidateAge(), 0 passed in /var/www/loris/tools/data_integrity/fix_candidate_age.php on line 125 and exactly 1 expected in /var/www/loris/php/libraries/NDB_BVL_Instrument.class.inc:2093
Stack trace:
#0 /var/www/loris/tools/data_integrity/fix_candidate_age.php(125): NDB_BVL_Instrument->getCandidateAge()
#1 {main}
thrown in /var/www/loris/php/libraries/NDB_BVL_Instrument.class.inc on line 2093
```
Since the documentation in Instrument …
=> [Core/Instrument] added default date value to getCandidateAge function

modules/media/ajax/FileUpload.php
This PR fixes issue reported in #4998. When entering a date in the past and attempting to upload a file, you get an error saying that the date cannot be in the future. 
date_diff is used to find the difference between the date entered and now. 
`$now - $date` returns a positive number if `$date` is in the past, therefore the PR simply switches the comparison operator. 
1. Try uploading a media file with a date in the past, should work fine.
2. Try uploading a media file with a date in the future, should get the expected message that date cannot be in the future.
=> [Media Uploader] Bugfix date of administration field

modules/candidate_parameters/ajax/formHandler.php
This PR fixes the logic for data validation on consent status tab. As it stands, if no status stays no or record existed as NULL the validation checks that :
1. consent date **is not** empty
2. withdrawal date **is** empty
However, if Consent Status at one point changes from 'YES' to 'NO' ==> user must fill in date of withdrawal. Therefore, consents that = 'NO' and have non-empty dates of withdrawal are considered non-valid (Displays error message).
1. Change consent from 'yes' to 'no'. Fill in date of withdrawal & submit.
2. Change some other consent or date or simply re-submit the same form. 
3. Make sure you don't get a data validation error.
=> [candidate_parameter] Consent Status data validation bugfix

modules/dicom_archive/jsx/dicom_archive.js, modules/dicom_archive/php/dicom_archive.class.inc, modules/dicom_archive/php/dicomarchiveanonymizer.class.inc, modules/dicom_archive/php/dicomarchiverowprovisioner.class.inc
This updates the DICOM archive module to use the DataFrameworkMenu class.
1. Follow the test plan of the module to make sure there was no change in behaviour
=> [DICOM archive - Data Framework] Make DICOM archive menu filter use the DataFrameworkMenu 

jsx/Form.js
This PRs allows the ability to render SelectElements and TextboxElements without its label. If a label prop is provided, the label will render and take up 3 spaces in the row, with the input element taking up the rest of the 9 spaces. This is also the case if the label prop is an empty string. If a label prop is not provided at all, the default is that the label won't be rendered at all and the input element takes up all 12 spaces of the row.
This change is useful for modules such as login that still need to be reactified and have input elements without labels:
This PR pulls out some code from https://github.com/aces/Loris/pull/4395
1. This change shouldn't affect any existing SelectElements and TextboxElements in loris. Browse different modules, and see if any of them are missing labels …
=> [jsx/Form.js] Make rendering label for SelectElement and TextboxElement optional

modules/statistics/php/stats_demographic.class.inc, modules/statistics/php/stats_mri.class.inc, modules/statistics/templates/table_statistics.tpl
The stats table in 21.0.0 is used in the demographics tab as well as the MRI tab, for the MRI tab, additional check were added to display an error message when the scan type is not associated with a `scan_type_scan_done` field i nthe MRI parameter form.
The demographics however should never display that error message since the error does not apply to it.
In this PR, the error flag was renamed from `scan_done_exists` to `render_table` to make it more generic for all tabs and an additional check was added to only display that error message on the MRI tab.  
1. try loading the demographics tab, no errors should be displayed
2. try loading the Imaging tab, errors should only be displayed IF the selected scan does not have a `Scan_Done` column in the `mri_parameter_form` table
* #4912
=> [Statistics] Fix render stats table to only render the MRI error on the MRI page

modules/candidate_parameters/ajax/formHandler.php, modules/candidate_parameters/ajax/getData.php
The requesting user must have candidate_parameter_edit, not just being authenticated.
Also fix `\Candidate::singleton((int) $candID);` call with a string. It wad generating an error : 
`PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Candidate::singleton() must be of the type integer, string given`
=> [Candidate Parameters] fix permission check

docs/config/config.xml, test/config.xml, test/unittests/CandidateTest.php
This should've been updated in #4241 but I overlooked it. 
`minLength` hasn't existed since the above PR was merged; now it is just length.
There is an [extended conversation](https://github.com/aces/Loris/pull/4469#pullrequestreview-288703473) on this topic in another PR which is how this came up.
There is another lingering instance of minLength and maxLength being used in Utility and this has to do with user-generated PSCID formats. I'm leaving this out of this PR and have opened #5227 to speak about this case.
=> Correct 'minLength' to 'length' for PSCID generation

php/libraries/Module.class.inc
This bugfix fixes the incorrect slash in front of the class name and such as when including a directory for endpoint php classes.
Example: module/php/endpoints/classnames.class.inc 
Instead of the usual module/php/classnames.class.inc
=> [php/libraries] Module.class.inc fixes slash bug when including directory for endpoint.

.phan/config.php
This rule should've been added in #4345 but wasn't. Might've been a rebase error on my part.
=> [Phan] Re-add PhanTypeSuspiciousStringExpression rule

php/libraries/NDB_Page.class.inc, test/unittests/NDB_PageTest.php
Unit tests for the [NDB_Page.class.inc](https://github.com/aces/Loris/blob/major/php/libraries/NDB_Page.class.inc) library. 
**I've also added a lot of FIXME comments to NDB_Page.class.inc because some methods have code smells.**
Run `npm run tests:unit -- --filter NDB_Page` or check out Travis.
* #4423 -- GSOC "to-do" list
=> [Test] unittests for NDB_Page.class.inc

php/libraries/Utility.class.inc
This function should've been properly deprecated in LORIS v21 but was missed during the release process.
See #4151
=> [Utility] Deprecate toArray() function

modules/timepoint_list/php/timepoint_list_controlpanel.class.inc, modules/timepoint_list/templates/timepoint_list_controlpanel.tpl
When user has the permissions:
"View candidate parameters" but NOT "Edit candidate parameters", the button is supposed to read "View candidate info" (which it does), but it is not responsive. Clicking on it does not load the candidate parameters page.
Changed the tag in template so that the button in question actually redirects.
1. Assign yourself the appropriate permissions and see if the link redirects to candidate parameters
=> [timepoint_list][bugfix] 'View Candidate Info' button wasn't redirecting

test/run-php-linter.sh
With the introduction of php subdirectories in modules, run-php-linter fails. This uses `find` instead of `ls` to create the file list.
create a subdirectory in a `module/?/php`. 
add a `.php` or `.class.inc` file in the directory.
test with a syntax error and without.
`./test/run-php-linter.sh` should exit if an error is found.
=> Fix php linter

tools/install.sh
Adds `-p` flag to `mkdir` so that the install script won't fail when `user_uploads/` already exists (for whatever reason) in doc_repo or data_release.
Fixes #5244.
=> [Install] Add -p to mkdir so install doesn't fail

modules/media/ajax/FileUpload.php, modules/media/jsx/uploadForm.js
When uploading a form to media module, you cannot enter a date greater than 2017-12-31. The date of administration field is currently hard-coded to have a minYear of '2000' and a maxYear of '2017'. This PR aims to change this. The min and max year are now determined by the study's start and end year (taken from configuration).
1. Try uploading a file with a date of administration that is within the bounds of the study's start and end year.
=> [media] Use study's start/end date as min/max values for Date of Administration field

raisinbread/README.md
The rendered Markdown (i.e. in the GitHub front-end) should now have appropriate syntax highlighting for code snippets.
=> Add syntax highlighting in raisinbread README

CONTRIBUTING.md
Update `CONTRIBUTING.md` to tell developers to work based off of forks instead of committing to the repo.
Resolves #5209.
=> Instruct new developers to not create new branches on the repo

php/libraries/SiteIDGenerator.php
The `static` PSCID generation was not working anymore because the `$prefix` was never null since the site abbreviation always exist. the logic of choosing `siteAbbrev` vs `static` was moved in this PR to the if/else statement of the `prefix case`
1. modify your config.xml to use a static option.
2. check that the static string gets prepended
3. change the config.xml to use the siteAbbrev
4. check that the correct site Alias gets prepended
* PR changing the logic https://github.com/aces/Loris/pull/4241
* Resolves https://github.com/aces/Loris/issues/5268
=> [Core] Fix static PSCID generation

.travis.yml
PHP 7.4 will be released in 2 months, at the end of November. It would be nice to move LORIS toward this as a minimum version requirement for LORIS 22. #5063 
At the same time PHP 7.2 will stop receiving active support. https://www.php.net/supported-versions.php
Until its release, Travis offers a "snapshot" build which should be equivalent to the rc1 or rc2 of 7.4. This can be updated after the official release, but for now this gives us a chance to see how LORIS is doing.
=> Add PHP 7.4 (snapshot build) to TravisCI tests

tools/install.sh
Allows the shell script to continue if the command "hostnamectl" is not found.
Note: Let me know if the else statement is unnecessary.
1. Test on macOS
2. Test on Ubuntu or centOS
* Fixes #5262
See other PR: #5286
=> [tools/install.sh] fix for other operating systems

php/libraries/Utility.class.inc, test/unittests/UtilityTest.php
When checking data coming from e.g. the database or a form, there are some weird subtleties with using `intval()`. It'll return `0` on an input of `null` which makes it hard to differentiate between inputs that are `null` and `0` and those that are unset. It also has non-intuitive behaviour for array and object inputs, see: https://secure.php.net/manual/en/function.intval.php
This PR adds a simple function to check whether a given value is a positive integer as well as unit tests to prove that it works.
=> [Utility] Add isPositiveInteger function (+ unit tests)

modules/login/php/passwordexpiry.class.inc
The password expiry code was making static calls to `updatePassword` and `passwordChanged` in the User class which are non-static methods. This created errors such as `PHP Fatal error:  Uncaught Error: Using $this when not in object context`, making it impossible to update an expired password.
This is due to an oversight in #4411, so it only affects `aces/major`.
1. Checkout `aces/major` and run `make dev`.
2. Update a user to have an expired password (i.e. change the `Password_expiry` field in the `users` table to be a date earlier than the current date).
3. Login to LORIS. The password expiry screen should appear.
4. You will get an undecorated 403 error when trying to update your password.
5. Checkout this branch and run `make dev`.
6. Repeat step 3. The password should update …
=> [Login] Fix issue where expired passwords could not be updated on major

php/libraries/FilesUploadHandler.class.inc, src/Api/Endpoints/Login.php, src/Api/Endpoints/Project/Candidates.php, src/Api/Endpoints/Project/Images.php, src/Api/Endpoints/Project/Instruments.php, src/Api/Endpoints/Project/Project.php, src/Api/Endpoints/Projects.php, src/Http/Response/JSON/BadRequest.php, src/Http/Response/JSON/Conflict.php, src/Http/Response/JSON/Created.php, src/Http/Response/JSON/Forbidden.php, src/Http/Response/JSON/InternalServerError.php, src/Http/Response/JSON/MethodNotAllowed.php, src/Http/Response/JSON/NotFound.php, src/Http/Response/JSON/NotImplemented.php, src/Http/Response/JSON/NotModified.php, src/Http/Response/JSON/OK.php, src/Http/Response/JSON/Unauthorized.php
Move ambiguously named HTTP response classes which only handle JSON responses to an explicit JSON sub-directory/namespace.
This should avoid confusion by making the fact that they're only useful for JSON more explicit.
=> Move Response objects to explicit JSON namespace

jsx/DataTable.js
This improves the efficiency of the DataTable JSX component when dealing with
large data tables. When counting the number of rows which match the filters
for the count in the header/footer, it returns an array of indexes which matched
the filter rather than returning a count. This prevents the need to needlessly
duplicate the work of tracking which rows match for the data table.
The indexed array is then sorted, and we work with that sorted list of indexes
instead of repeatedly going over this.props.data after the first time the matching
rows are calculated.
I suspect that somewhere in the deleted code there was an O(n^2) iteration over
the data that was avoided by re-writing and only directly working with the filtered
data after computing it, but I didn't track down where that was …
=> [Data Tables] Improve efficiency of DataTable filtering for large data tables

modules/configuration/ajax/process.php, modules/configuration/js/configuration_helper.js
I was recently able to develop an exploit where I could upload and execute scripts via manipulating config path settings. This PR ensures that these settings actually correspond to existing paths on the system before changing their values in the database.
* Try changing one of the Configuration settings under `Paths` to an invalid path. You'll get a `400` error.
=> [Configuration] Path settings must be valid paths

modules/candidate_parameters/php/candidate_parameters.class.inc, modules/candidate_parameters/test/TestPlan.md
When clicking on the breadcrumb in `Candidate Parameters`, the CandID was not being included in the link and thus was throwing a 500 error (specifically in the `Consent Status` tab). See screenshot.
1. Click the breadcrumb and ensure that you stay on the same page.
=> [candidate_parameters] Fixing breadcrumb 

php/libraries/Database.class.inc
`Database->pselect()` now always returns an array, thus removing the need to check if its result is an array before proceeding.
This should be safe as it is just a wrapper for the `execute()` function which already returns an array.
I'm not sure if this has implications for overrides or instruments so for now I'm adding the Caveat label.
#5318, #4284
=> [Core: Database] Add array return type to pselect

tools/install.sh
Using `command -v` is POSIX standard. `which` can also give weird path results sometimes so we should avoid it.
1. The install script should work as normal
* Resolves #5298
=> [Install] Use "command" instead of "which" to determine if a binary is installed

composer.json, composer.lock
>The new maintainer team of PHPMD is pleased to announce its first minor release PHP Mess Detector version 2.7.0.
This contains all the new features, improvements and fixes from over 250 commits from two and a half years since 2.6.0.
https://github.com/phpmd/phpmd/releases/tag/2.7.0
PHPMD has been resurrected!
=> Update phpmd (first new release in 2.5 years)

modules/dataquery/php/dataquery.class.inc
"ConfigException" doesn't exist and causing LORIS to crash when an exception is thrown.
1. Using invalid CouchDB credentials, go the DQT module. LORIS will crash.
=> [DQT] Fix 500 error caused by bad Exception name

mkdocs.yml
Running into a known issue when ReadTheDocs and Mkdocs compatibility: https://github.com/readthedocs/readthedocs.org/issues/4922
However it looks like the fix is as easy as changing the option from `nav` to `pages`. Both are building for me locally at https://loristest.readthedocs.io/en/latest/ (which is a copy of `minor` as of its latest changes from today). 
Not sure why there's a difference, but this should fix it.
=> [ReadTheDocs] Fix build error

modules/data_team_helper/jsx/behavioural_qc_module.js
This PR fixes a broken link reported in #5376
1. Make sure all links in data team helper module are working as expected 
* #5376 
* aces/CCNA#3375
=> [data_team_helper] fixed broken link that should redirect to candidate's timepoint

modules/statistics/php/stats_mri.class.inc
A user with role Data Entry was able to see **imaging** statistics from sites it does not belong/have access
For example if there are two users and two sites:
user Site 1 is associate only to Site_1.
user Site 2 is associate only to Site_2.
(Both of them have the role Data Entry and nothing more in the permissions)
When going to MainMenu->Reports->Statistics->**Imaging** Statistics
The user of Site 1 is able to see the **imaging** statistics for Site 2 and vice versa
Now each user should be able to see only the **imaging** statistics for the sites it belong/have access
=> [Statistics / Imaging Statistics] Fix permission issue where users were allowed to see imaging statistics from sites they don't have access to.

modules/media/jsx/editForm.js
Follow up to #5248.
Issue: Resolves #5361 
Date of administartion min and max year are currently hard-coded, but should use the config values of study start and end date.
1. Edit a form. Make sure you can enter any date between the study's start and end year. 
* #5361 
* #5248.
=> [media][editForm.js] Use study's start/end date as min/max values for Date of Administration field

modules/imaging_uploader/php/imaging_uploader.class.inc
This PR cleans up the `imaging_uploader.class.inc` file by removing all declaration of variables that are never used.
1. Follow the test plan of the imaging uploader module
* #5043
=> [imaging_uploader] Removed unused variables from imaging_uploader.class.inc

tools/deprecated/create_candidates.php
This adds a script used to generate a large number of candidates
for testing #5299. The candidates are not realistic or even necessarily
valid, but only intended to see how the candidate_list data table
holds up with a large amount of data  (I tested with up to 20,000 candidates.)
This needs a lot of work to be made robust enough to be useable
for general purpose testing and is unlikely to be maintained, so
is added directly to the "deprecated" directory, but I'm sending it
to LORIS at @maltheism's request.
=> [Script] Add script to generate fake candidates

jsx/Form.js
- I created a "slider" component for the form in LORIS.
- The component is named: `<SliderElement/>`
- Also it will resize well with the browser in the form!
**Note:** I kept the design simple for now.
Preview:
* https://github.com/aces/instrument-builder/issues/56
* https://github.com/aces/instrument-builder/issues/14
2. Add to a form.
3. Test away!
Example replace modules/new_profile/jsx/NewProfileIndex.js with:
```
import Panel from 'Panel';
import Loader from 'Loader';
import swal from 'sweetalert2';
/**
* New Profile Form
*
* Create a new profile form
*
* @author  Shen Wang
* @version 1.0.0
* */
class NewProfileIndex extends React.Component {
constructor(props) {
super(props);
this.state = {
configData: {},
formData: {},
newData: {},
isLoaded: false,
isCreated: false, …
```
=> [jsx/Form.js] new slider component! 

modules/imaging_uploader/jsx/UploadForm.js, modules/imaging_uploader/test/TestPlan.md
Modified the behaviour of the upload tab of the imaging uploader module. PSCID, CandID and Visit Label fields are now automatically populated based on the name of the selected file to be uploaded.
1. Follow the test plan of the module
Note that there has been a change of behaviour for the upload tab of the imaging uploader module. The PSCID, CandID and Visit Label fields are now populated automatically based on the name of the file to be uploaded when a scan is not a phantom scan.
=> [imaging uploader] Automatically populate PSCID, CandID & visit label based on the filename upon upload

php/installer/Installer.class.inc
There was a slight issue with the logic during the install process that swallowed a DB exeption in favour of returning false; however, the return value of this function was never checked so the code kept trying to function without a DB connection. This could give a 500 error in some cases, making the install look messy and hard to debug.
This PR simply checks the return status of the `connect` function and throws a DB exception if it is false.
* Try to install a fresh LORIS. Provide incorrect DB information and use these installation settings:
You will get a blank page (500 error).
* On this branch, do the same thing. You will get a front-end error message with MySQL debug information.
* #5311
=> [Install] Fix Database connection edge-case that resulted in 500 error

jsx/DataTable.js
When optimising the Datatable, #5299 introduced some bugs in the file. This PR removes those bugs.
1. It maps the headers to values to allow the `this.props.getFormattedCell` to function properly.
2. It pushes `rowData` to `filterData` so that when downloading the CSV, only the filtered data is passed.
3. Checks for cases where `data=null` because `null.toLowerCase()` cannot be executed.
There are still issues with pagination, which could be fixed in either this or another PR.
=> Fixing bugs introduced when optimizing DataTable

modules/dataquery/ajax/datadictionary.php
When `ajax/datadictionary.php` is called, Notices are generated when the `category` or `key` params are checked when not present in the request.
=> [DQT] Fix PHP Notices

modules/candidate_parameters/php/candidate_parameters.class.inc, modules/quality_control/php/quality_control.class.inc, modules/quality_control/php/quality_control_behavioral.class.inc
Previously only users with `candidate_parameter_view` could view the module. This allows users with `candidate_parameter_edit` to view it also.
I also cleaned up some unused code and documentation (probably introduced via copy-pasting).
1. Ensure that with only the `candidate_parameter_edit` permission that you're able to view the data in the module.
* Resolves #5372
=> [Cand. Params] Users with cand param edit permission should be able to view module 

modules/brainbrowser/ajax/image.php
`nii.gz` files could not be opened with the brainbrowser module. This PR modifies the way we read the image so that if the file is gzipped, it is decompressed first before reading the content of the file.
=> [brainbrowser] Add possibility to read nii.gz files with BB

php/libraries/Database.class.inc
1. Created a check to make sure that both the `ignore` and `onDuplicateInsert` flags are not used simultaneously in the `_realInsert` function.
2. Removed the unsetting of the unique key when using the pselectWithIndexKey function. I believe there are a lot of cases where still having the index key within the array and be able to access it's value via a key is incredibly useful.
=> [Database] Update database class

modules/candidate_list/php/candidate_list.class.inc, modules/candidate_list/php/candidatelistrow.class.inc, modules/candidate_list/php/candidatelistrowprovisioner.class.inc, modules/candidate_list/test/candidate_listTest.php, modules/dicom_archive/php/dicom_archive.class.inc, modules/media/php/media.class.inc, modules/media/php/mediafile.class.inc, modules/media/php/mediafileprovisioner.class.inc, php/libraries/DataFrameworkMenu.class.inc, php/libraries/User.class.inc, src/Data/Filters/UserProjectMatch.php, src/Data/Filters/UserSiteMatch.php
Creation of the userProjectMatch filter for the data framework and implementing it on the candidate_list and media modules.
With this filter you should now be able to restrict the data in  the data-table by both sites and projects.
1. assign a specific set of projects to your user and make sure the user is only able to access candidates and media files from those specific projects.
=> [Core] Create UserProjectMatch filter

SQL/0000-00-00-schema.sql, SQL/New_patches/2019-10-05-Add_alias_to_projects.sql, modules/new_profile/php/new_profile.class.inc, php/libraries/Candidate.class.inc, php/libraries/ExternalIDGenerator.php, php/libraries/IdentifierGenerator.php, php/libraries/PSCIDGenerator.php, php/libraries/Project.class.inc, php/libraries/SiteIDGenerator.php, php/libraries/Utility.class.inc, raisinbread/RB_files/RB_Project.sql, test/unittests/CandidateTest.php
Added option to generate PSCIDs using the project alias instead of the site alias. this is needed by several projects where permissions will be more project oriented then site.
to test:
- in your config.xml change between `static`, `siteAbbrev` and `projectAbbrev` make sure the correct PSCID gets generated
=> Add project to PSCID generation 

SQL/0000-00-00-schema.sql, SQL/New_patches/2019-07-01_add_projects_to_sessions.sql, modules/imaging_browser/php/imagingbrowserrowprovisioner.class.inc
This fixes the query for the imaging browser by taking the ProjectID from the session table instead of the candidate table.
1. Test that loading imaging browser on 22.0 fails
2. Test that after running the SQL patches it works again
The following patch (`SQL/New_patches//2019-07-01_add_projects_to_sessions.sql`) should be modified so that the `ProjectID` is populated correctly in the `session` table when studies have `scanner` candidates that are not associated to projects.
The update statement in that file should have been:
```
UPDATE session s JOIN candidate c ON s.CandID=c.CandID SET ProjectID=c.RegistrationProjectID WHERE PSCID != 'scanner';
```
@driusan @ridz1208 What should I do about this one? Should I create a new patch or just modify the one with the update since this is from a …
=> [imaging_browser] fixed query for the imaging browser

modules/candidate_parameters/ajax/getData.php
This is a fix for #5434 in which the forms were loading and then disappearing quickly afterwards.
I've attached a screenshot of what was appearing in the console. 
If you follow the link of the minified error, react documentation specifies the following:
`Objects are not valid as a React child (found: object with keys {}).`
Essentially, when returning the CandID object in the getData.php file, react freaks out because it expecting a string and cannot render the object that was passed.
1. Try accessing the candidate parameter module and ensure that it loads.
* Resolves #5434
=> [candidate_parameters][bugfix] getData returning candID object was breaking in react

modules/acknowledgements/jsx/acknowledgementsIndex.js
This changes allows the display of the 'Add Acknowledgement' button only if the user has `acknowledgements_edit` permission.
1. Check that the button 'Add Acknowledgement' renders when a user has `acknowledgements_edit` permission
2. Check that the button 'Add Acknowledgement' does not render when a user has only `acknowledgements_view` permission
* #5407
=> [acknowledgement] Remove edit buttons from UI when the user has no edit permission

modules/configuration/ajax/updateProject.php, php/libraries/Project.class.inc
Projects can now be added without requiring that subproject data be configured at the same time. This error was encountered during v.22 release testing.
This PR also refactors the file and adds accessor methods to the Project class to make the code easier to maintain going forward as well as to take advantage of typing.
* Resolves #5511
=> [Configuration] Fix issue where a Project could not be added without subproject data

modules/user_accounts/php/edit_user.class.inc, modules/user_accounts/php/my_preferences.class.inc
Password and Confirm Password on the front-end don't need to match on major. This check was removed by mistake during Password refactoring.
1. For both Edit User and My Preferences, try creating a new password and enter something different in the Confirm field. You should get an error message.
* Resolves #5417 
* Resolves #5416
=> [User Accounts] Fix password bugs: "confirm password" must match; password cannot be email

modules/document_repository/test/TestPlan.md
Remove `13. User A edits a file. User B tries to delete the same file in the meantime. Check that he can't.` and renumber because that functionality was never implemented
Resolves https://github.com/aces/Loris/issues/5456
=> [DocRepo] Update test plan for 22.0-release

modules/data_team_helper/README.md
Remove reference to the Data Team Helper module being listed as
"Quality Control" in the LORIS menu (which in fact links to the
quality_control module.)
Fixes #5503.
=> [Data Team Helper] Remove untrue statement from DTH README

php/installer/Installer.class.inc
The _sourceSchemaFile function wasn't logging potential errors when running the installdb.php in the browser.
Note: Let me know if you think the current solution could be done differently.
1. Rerun the installdb.php before completing and the error should be logged.
* https://github.com/aces/Loris/issues/5472
=> [installdb.php] Fixes sourceSchema not reporting error

modules/brainbrowser/php/brainbrowser.class.inc
In the test plan, we mention that only users with imaging browser permissions can view the scans in BB. Added the check for user permission before loading the module.
1. Try out the following URL on RB dataset <your_VM>/brainbrowser/?minc_id=[134] with a user that do not have imaging browser permission. This should lead you to a "No permission" with a redirect link to the dashboard.
* #5473
=> [brainbrowser] Add permissions to view the module

SQL/0000-00-01-Permission.sql, SQL/0000-00-02-Menus.sql, SQL/New_patches/2019-11-01-Add_data_release_permissions.sql, modules/data_release/php/data_release.class.inc, raisinbread/RB_files/RB_LorisMenuPermissions.sql, raisinbread/RB_files/RB_permissions.sql, raisinbread/RB_files/RB_user_perm_rel.sql
This adds a new permission to the database to allow users view/download access to the data release module. the other 2 permissions that already exist give the user slightly more power, this one is the most basic access.
addresses https://github.com/aces/Loris/issues/5496
=> [data_release] Add new permission for viewing only

modules/imaging_browser/php/viewsession.class.inc
The echo time in the header info section always displayed 0 for values below 1s.
Example: echo_time = 0.030 => the (int) before its value makes the echo_time becomes 0 then we multiply it by 1000 = 0
However, the value displayed in the front end should be 30ms not 0ms...
That simple bug fix fixes it.
1. Look at the echo time value on aces/bugfix (it will display 0 if echo_time < 1, 1 if 1 < echo_time < 2 ...)
2. Checkout this branch and you will see that the actual echo_time is displayed in ms
=> Bugfix display echo time repetition time

modules/imaging_uploader/jsx/UploadForm.js, modules/imaging_uploader/php/imaging_uploader.class.inc
This fixes the issue of any file type being able to be uploaded when the 'Phantom Scans' was set to 'Yes'. 
1. make sure you cannot upload file types different than `.zip`, `.tgz` or `.tar.gz` both when 'Phantom Scans' is set to 'Yes' and 'No'
* #5526
=> [imaging_uploader] fix forbidden file types that could be uploaded

modules/dicom_archive/php/viewdetails.class.inc
The metadata displayed at the top of the DICOM archive view details page were not populated. This fixes the bug.
1. checkout 22.0 and check that the metadata are not populated in the view details page
2. checkout this branch and check that the metadata are populated
* #5447
=> [dicom_archive] fixed the metadata not being displayed in the view details page

modules/new_profile/php/new_profile.class.inc
Fixes an issue when creating a new profile. This was originally sent to bugfix but the PR got auto-closed.
Using the "user" generation method, try creating a new profile. 
You'll get a freeze on the front-end and a TypeError on the back-end. 
This should fix it.
=> [New Profile] Fix TypeError when creating candidate with "user" generation method

modules/examiner/php/editexaminer.class.inc
This fixes 
- https://github.com/aces/Loris/issues/5423 (I think this bug is caused as an impact of #4914. The phan rule addition changed the behavior of the examiner module a little bit. So I am replacing the Loris Exception with some` if `cases in the code.
- https://github.com/aces/Loris/issues/5544
1) Try to create a new examiner and edit the examiner details by just clicking 'Save' with no data or with just one instrument details filled. It will throw 500 error. Check out to  this branch and try testing with the same case and see if the issue is resolved
2)  Add Certification instruments with similar naming (like BMI, BMI_version_2 etc)  and try to load the edit examiner page. It will throw 500 error.  Check out to this branch and try testing with the same case and see if the issue …
=> [Examiner] Fixing Errors while saving the form

modules/examiner/README.md
This PR removes the reference of Training Module in Examiner module's README
This task  was included in the bullet list of #4995
=> [Examiner README] Remove Reference of Training Module

modules/acknowledgements/php/acknowledgements.class.inc
Users with only `acknowledgements_edit` permission could not access the acknowledgements module. This fixes this issue.
=> [acknowledgements] fix bug where users with edit permission only could not access the module

modules/user_accounts/php/edit_user.class.inc, modules/user_accounts/php/my_preferences.class.inc, modules/user_accounts/test/user_accountsTest.php, php/libraries/User.class.inc, test/unittests/UserTest.php
Adds unit tests to the passwordChanged function. 
While this adds a unit test, the front-end should still be tested. 
* Item 15 in the [test plan](https://github.com/aces/Loris/blob/major/modules/user_accounts/test/TestPlan.md).
* #5439 reported that a passwordChanged() was not returning a false value, i.e. a user was able to keep the same password. I'm adding this function to prevent this kind of issue going forward.
=> [Testing] Add unit tests for User::passwordChanged

modules/configuration/templates/form_configuration.tpl
This fixes the rendering of boolean fields in the configuration module. without this change a boolean field without a default option set (field defined in `ConfigSettings` but no entry in `Config` table) renders as a text entry in the configuration module. it should render as true/false radio buttons with non selected with this change.
1. go to the configuration module
2. find any boolean field
3. delete the corresponding entry from the `Config` table in your database
4. make sure that the field still renders as radio buttons but non are selected.
* fixes https://github.com/aces/Loris/issues/5509
=> [Configuration] display radio buttons when boolean field does not have a default option

modules/media/ajax/FileUpload.php, modules/media/jsx/editForm.js, modules/media/jsx/mediaIndex.js, modules/media/php/media.class.inc
This PR Addresses Two Issues: 
#5581
I fixed the media datatable by adding Project to the column list and filter. Projects had been added to the query in MediaFileProvisioner, but was not added to the fields list which populates the Datatable. This was causing an issue where the values were not displayed right, and the edit file form was not accessible.
#5459
There was no field for 'Language' in the edit media form, and therefore there was no way to edit language. Language has now been added as a field and is editable.
=> [Media] Added Project to Columns; Added Language to Edit File Form

README.CentOS7.md, modules/user_accounts/php/edit_user.class.inc
This PR resolves php missing for httpd (apache) module.
Note: The command "sudo yum-config-manager --enable remi-php72" doesn't actually help change the repos for installation of php72
Please see https://github.com/aces/Loris/issues/5383 for details.
=> [install CentOS] Fixes httpd apache module for php is missing

php/libraries/User.class.inc
Fixes TypeError introduced by #5426.
> PHP Fatal error:  Uncaught TypeError: password_verify() expects parameter 2 to be string, null given
1. Try to change your password via Edit User to the same password you have now. LORIS will crash
2. This fixes the crash.
* resolves #5601
=> [User] Fix TypeError in password verification

webpack.config.js
This PR does two things to webpack.config.js
First change removes unnecessary `test: /\.js$/,` test and since the same functionality is done in the `/\.(js|jsx)$/` test.
Second change adds cache functionality to loader "[babel-loader](https://github.com/babel/babel-loader)" and "[eslint-loader](https://github.com/webpack-contrib/eslint-loader)" which is recommended for build performance (when executing "npm run compile" or "make"). The enforce: "pre" specifies that this is a pre-loader, which helps reinforce that this must run before normal loaders.
Basically turning on cache enables a directory for the loader that's cached in node_modules/.cache
Example: node_modules/.cache/eslint-loader and keeps track of cached files.
Similar: node_modules/.cache/babel-loader
So we will have a …
=> [webpack.config.js] update for build speed and correction

modules/configuration/templates/form_configuration.tpl, modules/configuration/test/TestPlan.md
This restores a behaviour from https://github.com/aces/Loris/pull/5592 while keeping the bugfix.
Previous behaviour was intentionally maintaining 1/0 values when previously saved value was 1/0 and true/false values when previously saved value was true/false. that is due to a lack of standard when coding with boolean values.
PR linked above converted all values to 1/0 automatically which is problematic because some code sections will be expecting a true or false to be returned from the `getSetting('something')` call.
1. choose a boolean config of your choice
2. set it to either 1 or 0 from the database and make sure the module displays the correct homologous value on the front end
3. from the front end, change the value of the field and make sure the database stores the 0 1 homologous …
=> [configurations] Allow for both 0/1 or true/false to be used

modules/acknowledgements/php/acknowledgements.class.inc, modules/imaging_browser/php/viewsession.class.inc
Users with phantom permissions could still view any view session page if given a link to that page. This PR fixes the permissions of the view session page of the imaging browser.
1. Make sure that users with phantom permissions cannot view any view session page for a candidate
* #5586
=> [imaging_browser] Fix permissions of the view session page

modules/user_accounts/php/edit_user.class.inc, modules/user_accounts/test/TestPlan.md, modules/user_accounts/test/user_accountsTest.php, php/libraries/User.class.inc, test/unittests/UserTest.php
Integration tests now verify:
* "Password" and "Confirm password" must match
* Password must not match email
* Password must be changed (i.e. submitting the same password as you had before gives an error)
This is done for both "My Preferences" and "Edit User"
This PR also does some refactoring of the file to make it easier to add to going forward.
* User Accounts test plan
* Resolves #5416
=> [User Accounts] Add integration tests for password change logic

modules/brainbrowser/templates/form_brainbrowser.tpl
This fixes the UI around the Overlay control panel display of BB.
Before:
Now:
1. Load BB with the overlay and check that the overlay control panel has the same border as the other control panels
* #5469
=> [brainbrowser] Fix overlay control panel display

modules/imaging_qc/php/imaging_qc.class.inc
Remove two unnecessary variables in getBreadcrumbs of the imaging_qc module.
Error logs (before):
```
[Wed Nov 13 12:19:55.111561 2019] [php7:notice] [pid 35053] [client ::1:50169] PHP Notice:  Undefined index: candID in /Users/alizee/Development/GitHub/McGill/Loris/modules/imaging_qc/php/imaging_qc.class.inc on line 371, referer: http://localhost/imaging_uploader/
[Wed Nov 13 12:19:55.111743 2019] [php7:notice] [pid 35053] [client ::1:50169] PHP Stack trace:, referer: http://localhost/imaging_uploader/
[Wed Nov 13 12:19:55.111752 2019] [php7:notice] [pid 35053] [client ::1:50169] PHP   1. {main}() /Users/alizee/Development/GitHub/McGill/Loris/htdocs/index.php:0, referer: http://localhost/imaging_uploader/
[Wed Nov 13 12:19:55.111822 2019] [php7:notice] [pid 35053] [client ::1:50169] PHP …
```
=> [imaging_qc] error log pollution fix

modules/behavioural_qc/php/behavioural_qc.class.inc
Remove two unnecessary variables in getBreadcrumbs of the behavioural_qc module.
Error logs (before):
```
[Wed Nov 13 12:12:39.730970 2019] [php7:notice] [pid 53725] [client ::1:49753] PHP Notice:  Undefined index: candID in /Users/alizee/Development/GitHub/McGill/Loris/modules/behavioural_qc/php/behavioural_qc.class.inc on line 866, referer: http://localhost/behavioural_qc/
[Wed Nov 13 12:12:39.731202 2019] [php7:notice] [pid 53725] [client ::1:49753] PHP Stack trace:, referer: http://localhost/behavioural_qc/
[Wed Nov 13 12:12:39.731211 2019] [php7:notice] [pid 53725] [client ::1:49753] PHP   1. {main}() /Users/alizee/Development/GitHub/McGill/Loris/htdocs/index.php:0, referer: http://localhost/behavioural_qc/
[Wed Nov 13 12:12:39.731254 2019] [php7:notice] [pid 53725] [client …
```
=> [behavioural_qc] error log pollution fix

tools/install.sh
Fixes a bug where the script would crash due to `$projectname` being accessed before it is initialized.
1. Run the install script. 
* Fixes #5640
=> [Install] Fix crash due to unbound variable access

jsx/DataTable.js, jsx/FilterableDataTable.js, modules/media/jsx/mediaIndex.js
Because the `getFormatedCell` function often both formats AND maps data, there was a developing issue where the downloaded data in the form of CSV did not represent what was shown in the datatable, but rather the initial data before mapping - therefore downloading keys rather than values.
This PR fixes this by allowing developers to disentangle mapping and formatting. A function can be created which checks the value of the parameter `column` and then changes the value correspondingly. This function can then be passed as a prop to the `FilterableDataTable` component which will take care of the rest.
E.G. from the Biobank module:
```
83   mapContainerColumns(column, value) {                                          
84     switch (column) { …
```
=> [JSX] Enabled Data Mapping for CSV Downloads

php/libraries/FeedbackMRI.class.inc
The error output log file was being polluted when clicking on the "Visit level Feedback" button. Inside the http://loris-url/imaging_browser/viewSession/?sessionID=1655# as an example.
Error output log:
```
[Tue Nov 12 15:37:11.232243 2019] [php7:notice] [pid 33144] [client ::1:49177] PHP Notice:  Undefined variable: statusField in /Users/alizee/Development/GitHub/McGill/Loris/php/libraries/FeedbackMRI.class.inc on line 359, referer: http://localhost/imaging_browser/viewSession/?sessionID=1655
[Tue Nov 12 15:37:11.232587 2019] [php7:notice] [pid 33144] [client ::1:49177] PHP Stack trace:, referer: http://localhost/imaging_browser/viewSession/?sessionID=1655
[Tue Nov 12 15:37:11.232602 2019] [php7:notice] [pid 33144] [client ::1:49177] PHP   1. {main}() …
```
=> [libraries/FeedbackMRI.class.inc] visit level feedback undefined

modules/login/php/passwordexpiry.class.inc, modules/login/php/passwordreset.class.inc, modules/user_accounts/php/edit_user.class.inc, modules/user_accounts/php/my_preferences.class.inc
_Replaces #5642_
Special characters can now be used in passwords. I forgot that they get automatically encoded upon submission to the codebase so passwords were never decoded before being hashed.
1. Checkout the branch, change your password to something containing a special character such as `&`, make sure you can login with that password.
* Resolves #5630 
* Extensive background reading about the history of why encoding happens https://github.com/aces/Loris/pull/4491#issuecomment-490567790
=> Fix account lockout when special character present in password

modules/dataquery/jsx/react.app.js, modules/dataquery/jsx/react.fieldselector.js
Re-issue of #5379 
This PR addresses the issues reported in #5364 
1. The `Delete All` link in DQT was broken and not actually deselecting the fields. 
2. You couldn't save a query if it had a space in the name. No error was displayed, it just wouldn't save. The code now replaces any space by underscores. 
1. Head over to DQT. 
2. Add some fields to your query. 
3. Attempt to deselect those fields using the `Delete All` button. 
4. Try saving a query that has spaces in the name. When you refresh, your query should appear. 
* #5364, #5500
* aces/CCNA#3342
=> [dataquery] Fixed broken link for 'deleteAll' and fixed save error on query names that contain spaces

modules/media/ajax/FileUpload.php, modules/media/jsx/editForm.js, modules/media/jsx/uploadForm.js
Addresses Issues From:
#5363 - Prevents Users from selecting a site, visit label, or instrument unless a pscid is selected.
This also removes the Site Field from the upload form and edit form in media. Site is redundant since visits are already associated with a site. This removes two unnecessary clicks for the user when uploading a file, and doesn't alter any data going to the database since the site was never saved anyways.
=> [Media] Resolving Issues from Testing

.travis.yml
> [php-ast 1.0.3+ is recommended for compatibility with future Phan releases.](https://github.com/phan/phan/wiki/Getting-Started#installing-dependencies)
I'm hoping this will also fix the PHP 7.4 build failure that seems to be caused by pecl.
=> [Travis] Update php-ast from 1.0.1 to 1.0.3

modules/login/php/passwordexpiry.class.inc
This file was not updated when the function `passwordChanged` was renamed to `isPasswordDifferent` which caused a PHP Fatal Error when trying to reset an expired password.
1. On `22.0-release`, Manually expire a user's password.
2. Try logging in to the front-end.
3. Enter a new password
4. You should get a 403 error.
5. Do the same on my branch and everything should work normally.
=> [Login] Fix issue where password could not be reset

Dockerfile.test.php7.debug, test/dockerized-integration-tests.sh, test/dockerized-unit-tests.sh, test/wait-for-services.sh
A recent PR causes strict checking of variables in bash. We are doing some sneaky environment variable tricks relying on variables sometimes being set so this made our scripts crash.
They should now work as before.
1. Running `npm run tests:unit` right now should cause an 'unbound variable error'
2. You should be able to run `npm run tests:unit` locally without that error (though the tests may fail for other reasons)
* Resolves #5515
=> [Test] Fix Docker scripts crashing when variables not set

README.CentOS7.md
The httpd.conf needs the DocumentRoot and <Directory "path"> modified.  Similar the ServerName needs to be configured. The installation guide of CentOS didn't inform the user about the step but now it does with the PR.
* https://github.com/aces/Loris/issues/5454
=> [install CentOS] httpd.conf configuration instructions

modules/user_accounts/php/edit_user.class.inc, modules/user_accounts/test/user_accountsTest.php
Fix #4743 where a user could accidentally lock themselves out but editing their own approval status.
1. Checkout this branch, go to user accounts.
2. You will no longer see the `Pending Approval` fields when editing your own accounts
=> [User Accounts] Hide UI option allowing users to edit their own approval status

Makefile, tools/create-version-file.sh, tools/gen-version.sh
When a user runs `make` without git being installed, the script will crash because git was required to create the VERSION file.
This adds a small script to fix that problem.
1. Checkout the branch. Delete your VERSION file if it exists.
2. Run `make VERSION`.
3. The VERSION file should contain information from git.
4. Run `mv .git/ .gitbkp/` to simulate a system without git.
5. Run `make VERSION`
6. The VERSION file should contain the string 'Unknown'
7. Run `mv .gitbkp/ .git/` to restore git.
* Resolves #5682
=> Script to create VERSION file without git

modules/brainbrowser/js/brainbrowser.loris.js
When trying to load more than one volume in BB via the imaging browser, only the first volume got displayed. When we refreshed the page, then the second volume would be displayed and so on.
This fixes that bug and now all volumes are being displayed the first time the page is loaded.
1. From the imaging browser page, select two volumes and click on either the "3D Only" or "3D + Overlay" button and verify that both volumes are being loaded. Note: the volumes might be slow to load given the size of the data being loaded in the browser...
* #5474 fixes the lack of clarity part of the issue (the slowness cannot really be fixed due to the size of the data being sent I guess...)
=> [brainbrowser] fix multiple volumes display bug

modules/conflict_resolver/help/conflict_resolver.md
Restores the conflict resolver help file that was mistakenly deleted on the repo.
Also incorporates new changes from original PR.
* Replaces #5692 
issue: #5576
=> [Conflict Resolver] Restore help file and update

modules/instrument_manager/php/instrument_manager.class.inc, php/libraries/NDB_BVL_Instrument.class.inc
Throws a configuration exception if the data in the config file is not formatted the way it's supposed to be.
Also fixes a namespacing issue in the Instrument Manager that was triggered in the same call stack. This caused a PHP Fatal Error.
1. Enable `EnableCertification` in your config.xml file.
2. Leave the rest of the tags empty.
3. Try to upload the `test_all_fields.linst` instrument to the instrument manager. (`test/instruments/test_all_fields.linst`)
4. It won't work
5. Do the same on this PR.
* Resolves #5698
=> [Core] Fix TypeError/500 error when Certification settings not well-formatted

modules/data_release/templates/menu_data_release.tpl
Fixes https://github.com/aces/Loris/issues/5708
Issue: when the version of the file is set to `0` the `in_array()` call will always return true because of cross-type checking. this eliminates the cross-type checking by adding the strict argument
=> [Data release] Edge case where version 0 always shows up checked

modules/publication/php/view_project.class.inc
Solve the broken breadcrumbs for View Project while consulting a project.
1. View publications module.
2. consult a project.
3. click on the View Project for breadcrumbs.
* https://github.com/aces/Loris/issues/5749
=> [publication] Broken link in Breadcrumbs fix

modules/conflict_resolver/jsx/resolvedConflictsIndex.js
fixes: https://github.com/aces/Loris/issues/5695
fixed undetermined reference to `row.oldvalue2`.
1. RUN MAKE BEFORE TESTING
=> [conflict_resolver] display correct answer bug

modules/help_editor/ajax/help.php, modules/imaging_browser/templates/form_viewSession.tpl, src/Middleware/UserPageDecorationMiddleware.php
The `subtest` field was not being populated by the Middleware. As a result, the parameter was never passed to the back-end in order to load subpage help text. Instead the code would always fall back to loading the main help text for the module.
Visit a module with a subpage. An example would be going to DICOM Archive and clicking "View Details". There should be specific help text for that module that is different from the help text for the main module.
* Resolves #5709
=> [Core] Fix help text not loading for subpages

php/libraries/NDB_BVL_Instrument.class.inc
This argument should be escaped as it may be possible for a front-end user to supply malicious data via the test name.
=> [Core] Escape shell argument in Instrument class

modules/document_repository/php/edit.class.inc
Clicking on the 'Edit' breadcrumb in document repository used to give an error.
1. Checkout PR
2. Visit Document Repository
3. Edit a file.
3. Click on BreadCrumb Edit
* https://github.com/aces/Loris/issues/5787
=> [document_repository] Fix clicking on the 'Edit' Breadcrumb

modules/user_accounts/php/my_preferences.class.inc
There was some validation added in My Preferences that differed to Edit User. Both modules now use PHP's filter_var() function to check emails (not visible in GitHub diff).
1. On 22.0-release, go to My Preferences and try changing your email to `nicolasbrossard.mni(test)@gmail.com`. You won't be able to.
2. On my branch, do the same. The email should work.
3. Try changing your email to an invalid value. Ensure that validation on emails still occurs.
* Resolves #5771
=> [User Accounts] Remove bad email validation in my preferences

modules/candidate_parameters/ajax/getData.php
When you only have the `candidate_parameter_view` permission, you can access the candidate parameter page but when it loads, an error page is shown with text: `An error occurred when loading the form`.
Fixes #5791
=> Candidate parametrers fail to load

tools/install.sh
Make the script fail when ran outside of the tools directory.
1. Attempt to run the install.sh from outside the tools directory.
* https://github.com/aces/Loris/issues/5643
=> [install.sh] Script fails when not run in `tools/` directory

smarty/templates/feedback_mri_popup.tpl
There should not be any drop down under the Overall MRI QC comments section like so:
On 22.0, there is an empty drop down for the overall section that should not be there:
This PR simply removes the empty drop down from the overall section of the MRI QC comments pop up page.
1. Check that no drop down are displayed next to the Overall header in the MRI QC pop up
2. Check that the other drop downs are correctly populated and can be saved
* #5705
=> [feedback_mri_comments] Removed empty Overall drop down

modules/instrument_manager/README.md, modules/instrument_manager/php/instrument_manager.class.inc, modules/instrument_manager/test/TestPlan.md, modules/instrument_manager/test/instrument_managerTest.php
This feature should be restricted to superusers, as discussed in the LORIS meeting.
I did not remove the `instrument_manager_write` permission from the codebase as we may want to use it in the future when JSON instruments are ready.
Background: #5778
=> [Instrument Manager] Require 'superuser' permission for instrument upload

modules/candidate_parameters/ajax/formHandler.php
When accessing the candidate parameter page, there was a bug preventing you from saving any consent change you perform. This PR fixes that.
#5801
=> Fixed bug that prevented any consent status from being saved.

modules/candidate_list/jsx/candidateListIndex.js
In the `formatColumn` function in Candidate List JSX Index file, if the subproject is `null` it now returns `<td></td>` instead of `null`. This is because if `null` is returned, the table data cell does not appear, and all the other rows of the table get shifted to the left.
#5799
=> [Candidate List] Fixed bug: Subproject column not displayed if value was null

README.md
Fixing a minor formatting issue in the Ubuntu readme
This resolves #5424 reported by @johnsaigle
This is issued to master not 22-release since 22-release's readme isn't quite up to date
Testing instructions
=> [Readme] fixing code formatting typo in main Ubuntu readme

modules/publication/ajax/FileUpload.php
Cleanup of undefined errors in error_log.
> [Mon Nov 25 12:29:33.014779 2019] [php7:notice] [pid 5215] [client ::1:60004] PHP Notice:  Undefined index: collaborators in /Users/alizee/Development/GitHub/McGill/Loris/modules/publication/ajax/FileUpload.php on line 192, referer: http://localhost/publication/
[Mon Nov 25 12:29:33.014981 2019] [php7:notice] [pid 5215] [client ::1:60004] PHP Stack trace:, referer: http://localhost/publication/
[Mon Nov 25 12:29:33.014990 2019] [php7:notice] [pid 5215] [client ::1:60004] PHP   1. {main}() /Users/alizee/Development/GitHub/McGill/Loris/htdocs/AjaxHelper.php:0, referer: http://localhost/publication/
[Mon Nov 25 12:29:33.014997 2019] [php7:notice] [pid 5215] [client ::1:60004] PHP   2. require() …
=> [publication] error_log undefined fixes when user proposes a project

jsx/Form.js, modules/new_profile/jsx/NewProfileIndex.js
Solves the bug where multiple candidates were made from the frontend form submission.
**Note this implementation is similar to how it was done before.** Another way would be to create a disabled props for the button component.
2. Go to New Profile and press the submit button as much as you want.
* https://github.com/aces/Loris/issues/5800
=> [new_profile] Pressing create multiple time creates multiple candidates "silently"

modules/login/php/requestaccount.class.inc
another issue on 21
user_accounts and examiner modules trim inputs before submission. request account does not do any trimming so entries like first/last name and emails get submitted with empty spaces around them.
This is particularly problematic for examiners where an examiner created with the incorrect `Real_name` value will cause a duplication of the examiner the first time the form is saved on user accounts because the name then gets trimmed and restored in it's correct format in the examiner table
result -> 500 error due to pselectrow returning more than one row
=> [login] TRIM inputs before inserting into users or examiners

modules/dataquery/jsx/react.app.js
Fixes the bug of when clicking on the "Manage Saved Queries" tab, then clicking on other tabs and then trying to click the Managed Saved Queries tab. The bug wouldn't let you view the content of the "Managed Saved Queries" tab again.
1. Checkout PR
2. Click Managed Saved Queries tab
3. Click other tabs.
4. Go back to Managed Saved Queries.
* https://github.com/aces/Loris/issues/5806
=> [DQT] Fix for Manage Saved Queries Tab

SQL/0000-00-03-ConfigTables.sql, SQL/New_patches/2019-10-09_move_MINCToolsPath_configuration_to_Config_tables.sql, docs/config/config.xml, modules/brainbrowser/README.md, raisinbread/RB_files/RB_Config.sql, raisinbread/RB_files/RB_ConfigSettings.sql, raisinbread/config/config.xml, test/config.xml
This PR moves the config setting `MINCToolsPath` from `config.xml` to the Config tables.
* Resolves #5019
=> [Configuration] Moved MINCToolsPath from config.xml to the Config module

modules/dicom_archive/test/dicom_archiveTest.php
This test is unstable and causing failures on PRs that should otherwise pass.
* This test caused failures in unrelated PRs, including #5717, #5699, #5634, #5690, #5591 and others referenced below
=> [DICOM Archive] Skip unstable integration test

modules/configuration/php/configuration.class.inc
This address the following error message
```
modules/configuration/php/configuration.class.inc:142 PhanCompatibleDimAlternativeSyntax Array and string offset access syntax with curly braces is deprecated in PHP 7.4. Use square brackets instead. Seen for $setting{'ID'}
```
fixes https://github.com/aces/Loris/issues/5626
=> Array offsets: change curly brackets to square brackets 

README.md
Adds a build badge to the README of LORIS for ReadTheDocs. This will indicate whether the docs are building successfully for a given version.
=> Add ReadTheDocs build badge to LORIS readme

README.md
Original PR should've used the SVG, not PNG.
=> Change LORIS logo in readme to SVG to prevent blurriness

tools/CouchDB_MRI_Importer.php
adding backticks to make sure no errors are thrown if these are dashes in the scan type name
=> [DQT Importer] Issue where script breaks if scantype has a '-' character

composer.json, composer.lock
`git checkout aces/major`
`make dev`
`composer update phpunit/phpunit phpunit/php-code-coverage phpunit/php-timer phpunit/php-token-stream phpunit/phpunit-mock-objects` (PHPUnit dependencies were iteratively added to the above command until composer was certain that the requirements could be satisfied.  
Required in order to install `phpstan` static analysis tool
* #4433 is a more substantial upgrade to PHPUnit 8. This is a stepping stone toward that PR. I've issued this so that I can install phpstan afterward.
=> Update PHPUnit to version 7

README.md
System requirements statement is not precise.
MySQL 5.7 or 8 both runs fine with the program, except that some configuration should be modified on MySQL 8 to make the system work.
1. Install MySQL, then run the installation script, the installation will fail at the step 6. In fact, the note I added could go to the step 6 either, without much difference.
*
=> [Install] System requirements state MySQL >= 5.7 but in fact MySQL 8 will run into trouble

README.md
Adds an explicit minimum version for composer based on discussion in #5845. 
There was some concern on the mailing list that an issue during the install was caused by an old composer version. It makes sense to be a little more specific about it in our documentation.
* Resolves #5845
=> Document composer version

.github/PULL_REQUEST_TEMPLATE.md
Remove reference to Redmine.
Also adds prompt to encourage developers to GitHub issues using the Resolves keyword, which will automatically close the linked issue if the PR is merged.
=> Cleanup pull request template

modules/api/php/endpoints/candidates.class.inc, modules/dashboard/ajax/get_recruitment_bar_data.php, modules/dashboard/ajax/get_recruitment_line_data.php, modules/dashboard/ajax/get_recruitment_pie_data.php, modules/dashboard/ajax/get_scan_line_data.php, modules/issue_tracker/ajax/EditIssue.php, php/libraries/Utility.class.inc, test/unittests/UtilityTest.php
* Replaces contents of `getSiteList()` with `getAssociativeSiteList()` because that code optionally allows for the exclusion of DCC data.
* Changes `getAssociativeSiteList()` to `getSiteList()` in the codebase.
* `getAssociativeSiteList()` now throws a DeprecationException for any projects that may be using it.
=> [Utility] Deprecate getAssociativeSiteList()

test/UnitTestGuide.md
The `major` branch is being phased out. This removes the remaining references to it in our documentation.
1. Checkout this branch and run `git grep -n "major" -- '*.md'`.
2. Verify that the results that refer to a "major branch" are only in the `deprecated_wiki/` folder.
=> Remove references to "major" branch in documentation

SQL/0000-00-03-ConfigTables.sql, SQL/New_patches/2019-11-29-Add_upload_directory_configuration.sql, modules/data_release/README.md, modules/data_release/ajax/FileUpload.php, modules/data_release/ajax/GetFile.php, modules/document_repository/php/files.class.inc, php/libraries/Utility.class.inc, raisinbread/RB_files/RB_Config.sql, raisinbread/RB_files/RB_ConfigSettings.sql, raisinbread/migration.md, tools/install.sh
This gives the option to the users to configure where the default upload directory of data_release and document_repository modules will be. this also removes the burden on LORIS to ensure these locations are readable/writeable and follows the standard established by the other modules uploading data to loris.
- before checking out the branch, make sure you are able to upload a file to doc repo and data release. If it is not the case, you should resolve the issue as it is not due to this change.
- check out this branch and ensure you are still able to upload and download files to the 2 modules (the sql patch for existing projects is designed to be backwards compatible)
- change the upload paths from the configuration module and make sure the new paths exist on your machine and are apache …
=> [data_release/document_repository] Make upload directory configurable

modules/genomic_browser/README.md
This reformats the information in the genomic_browser README to follow the same style
as the other modules specs. Information for required sections that was not present in the existing README or that I couldn't derived from the code is listed as "Unknown". Edits from
people who are familiar with the module to fill in those sections is welcome.
=> [Genomic Browser] Reformat README to be in the same style as other module specs

modules/dashboard/ajax/get_scan_line_data.php
For long running studies the "study progression" widget on the
dashboard was doing an excessive number of queries on the database
(one per site per month of the study having been running) which
was causing the dashboard to take an excessive amount of time to
load.
This replaces it with a single query using a GROUP BY, and then
massages the data in PHP to the same format.
To test this compare the dashboard/ajax/get_scan_line_data.php results
before and after this change. The JSON returned should be identical, but the
performance should be faster (if there's a large enough amount of data
that the before was noticeably slow to load.).
=> [Dashboard] Fix study progression performance

package-lock.json
NPM reported that there were a couple of security vulnerabilities with LORIS dependencies.
I ran the following commands:
```bash
git fetch aces
git checkout aces/master
make dev
make checkstatic
npm audit fix
```
and committed the resulting `package-lock.json`.
1. LORIS shouldn't break. Place your faith in Travis.
=> [Core] Fix security vulnerabilities reported by npm

.github/stale.yml
Adds a configuration for [stale bot](https://github.com/probot/stale), a tool that marks inactive issues and PRs and eventually closes them if no action is taken on them.
If used, it should assist with triage and keep us on our toes about what may be slipping through the cracks.
I used the default config file here, modified slightly to match the labels we use.
In order for this to work, someone with Admin privileges must [enable the Stale bot](https://github.com/apps/stale/installations/new). Until then this PR will remain in Draft state.
=> Add configuration file for the Stale Bot tool

.github/stale.yml
Stale bot was configured incorrectly. My bad.
=> Remove stale bot exemptions because we're not using its auto-close feature

composer.json, composer.lock, src/Http/Error.php, src/Http/FileStream.php, src/Http/Response.php, src/Http/Response/JsonResponse.php
Fixes the error "Package zendframework/zend-diactoros is
abandoned, you should avoid using it. Use laminas/laminas-diactoros instead."
while running composer install on LORIS.
=> Replace zend-diactoros with laminas-diactoros

.phan/config.php, .travis.yml, README.md, docs/wiki/00 - SERVER INSTALL AND CONFIGURATION/01 - LORIS Install/CentOS/README.CentOS7.md, modules/create_timepoint/php/create_timepoint.class.inc, php/libraries/NDB_Client.class.inc
PHP 7.2 is no longer receiving active support as of Nov. 30th, 2019. PHP 7.4 is being released at about the same time.
Typically we only support the last two releases of PHP. This PR brings the minimum requirement up to 7.3 from 7.2.
Detailed changes between these versions can be found here: https://www.php.net/manual/en/migration73.php
I'm adding the Security label because this upgrade will enable all LORIS instances to be fully protected from CSRF attacks via the SameSite cookie.
* Resolves #5063
=> [Core] Raise minimum PHP requirement to 7.3

modules/dashboard/php/dashboard.class.inc, php/libraries/User.class.inc
This moves the query to get the last user login from the
dashboard code to the User class, where it more accurately
belongs.
(This was extracted from #5896 where it was necessary because
multiple modules use the last login time to determine if something
is new.)
=> [Core] Add getLastLogin helper to user class

src/Middleware/AnonymousPageDecorationMiddleware.php
Brief summary of changes
Yesterday I was having issues with attempting to receive a JSON object from the server (after a post request from the client). The client was receiving data from the server but html content was included as well. Making my JSON object not be a JSON object and the javascript error would fail inside the fetch function.
One of my PRs is working on making the login form react. Well it turns out this bug only happens when the user isn't logged in. This bugfix is needed for when the user is not logged in and for the server to respond to a post request with data that's correctly formatted (such as a JSON object).
Note: I made a PR for both major & bugfix branch because I'm in the processing of making the login react on major.
This resolves issue...
Redmine? #
Github? #
To …
=> [src/Middleware] AnonymousPageDecorationMiddleware.php Post response bugfix

.phan/config.php
* Explicitly declare severity level (unchanged from before)
* ~~Explicitly declare targeted version of PHP version~~ This could cause a problem with Travis
* Update link from the etsy repo to phan
* Remove a duplicate, conflicting setting
* ~~Remove backward compatibility check because we don't need it~~ Dave wants this to stay
* Change tabs to spaces
=> [Testing] Cleanup phan file and make explicit the settings we are using

.phan/config.php, modules/dicom_archive/php/viewdetails.class.inc
There was only one error of type "PhanTypeInvalidDimOffset" detected (which was mostly just phan getting confused by the array being populated by a "SELECT *"), so this bandages over it by adding an isset. PhanNoopNew had no violations.
=> Fix PhanTypeInvalidDimOffset, PhanNoopNew and remove incorrect comment from phan config

modules/mri_violations/test/mri_violationsTest.php, php/libraries/NDB_Page.class.inc
This updates the default breadcrumb for a page to
use the module's getLongName for the first level of
the breadcrumb, rather than the hack where it replaces
'_' with space in the URL.
Fixes #5856.
=> Use module long name for Breadcrumb

php/libraries/NDB_Config.class.inc
This makes the field list in NDB_Config->getProjectSettings explicit
so that it crashes hard if a patch is missed rather than continuing
on and providing unrelated warnings later. It removes the try/catch
for the same reason (and because I couldn't figure out any reason it
was there in the first place. It looks like it was added in a commit to appease
phan, but phan is passing without it.)
=> [NDB_Config] Make field list explicit and remove unnecessary catch

docs/wiki/99 - Developers/Automated Testing.md, mkdocs.yml
Adds a document that gives a high-level overview of our TravisCI pipeline.
This is intended as a general explainer of each of the tools we use. It will not include a list of each and every rule enforced by different tools nor provide example issues and solutions. Instead, links will be provided to the repositories of those tools as they'll be able to provide better detail than we can.
Content adapted from my presentation "How To Win The Love Of Travis".
* Resolves #5819
=> Document LORIS automated testing

src/Http/Response/JSON/UnsupportedMediaType.php
UnsupportedMediaType is a type of JSON response with a specific
HTTP response code. The API was instantiating it as if it was
in the LORIS\Http\Response\JSON namespace (as all the other
JSON specific response classes are) but the file was in
LORIS\Http\Response. This moves the file to the correct
namespace.
=> [API/Router] Move UnsupportedMediaType to the json folder

composer.json, composer.lock
This updates phpmd to the latest release. This is
primarily to fix a number of warnings that it outputs
on PHP 7.4 when running `make checkstatic`.
=> [Dev] Update phpmd to the latest release

modules/statistics/php/stats_behavioural.class.inc
A user with role Data Entry was able to see statistics from sites it does not belong/have access
For example if there are two users and two sites:
user Site 1 is associate only to Site_1.
user Site 2 is associate only to Site_2.
(Both of them have the role Data Entry and nothing more in the permissions)
When going to MainMenu->Reports->Statistics->Behavioural Statistics
The user of Site 1 is able to see the statistics for Site 2 and vice versa
Now each user should be able to see only the statistics for the sites it belong/have access
This is a temp fix based on 21.0-released. A major refractory still pending.
=> [Statistics / Behavioural Statistics] Fix permission issue where users were allowed to see statistics from sites they don't have access to. 

.phan/config.php, php/libraries/NDB_Menu_Filter.class.inc, test/unittests/LorisForms_Test.php, test/unittests/VisitTest.php
$_GET['foo'] is usually a string, so we need to ensure
that it's an array places that it's submitted/treated as
an array.
=> [Phan] Fix PhanTypeMismatchDimFetch errors

htdocs/index.php, modules/api/php/endpoints/candidate/visit/image/format/raw.class.inc, modules/api/test/login_Test.php, modules/instruments/php/module.class.inc, php/libraries/NDB_BVL_Instrument.class.inc, src/Http/Error.php, src/Http/StringStream.php, src/Router/ModuleFileRouter.php
There were a few references to Zend (which was replaced by
Laminas in #5894) in our code base. For some reason, phan
didn't pick up on them until strict typing was enabled in #5923.
This fixes the references to zend and replaces them with laminas.
=> Replace straggling reference to zend with laminas

tools/exporters/DB_dump_table_data.php
This adds the ability to only dump certain tables by specifying them
as arguments on the command line to DB_dump_table_data.php.
=> [Tools] Add option to specify tables to dump for RB on command line

README.md, docs/wiki/00 - SERVER INSTALL AND CONFIGURATION/01 - LORIS Install/CentOS/README.CentOS7.md
change the link for the README.CentOS7.md file to the new docs/wiki directory.
and the link from that file to the README.md file
Click on the link in the README.md file, you should get to the CentOS7 version.
From there, click on the link to the README.md file (2 location, near top and at bottom).
=> [docs] change link to new location in docs/wiki/00

modules/behavioural_qc/php/behavioural_qc.class.inc, test/LorisPHPMD.xml
This removes a comment that was mistakenly merged in #4404. It also
removes a design rule from the config that should never have been
added, but only got included because PHPMD's config file is based
on excluding rules that you don't want, and not including rules
that you want, and the rule was snuck in in a PHPMD upgrade.
=> Remove unnecessary (and potentially incorrect comment) and PHPMD rule

.githooks/pre-push, CONTRIBUTING.md, Makefile
This PR adds a git hook that will run `make checkstatic` for you when you do `git push`. It will stop the push from going through if `make checkstatic` fails. The idea is to encourage developers to fix static analysis errors locally before pushing to GitHub. This should help accelerate code review and prevent clogging up Travis. 
This is opt-in; you can enable it by running `make githooks` just once.
1. Checkout this branch and run `make githooks`
2. Create a new branch and try to do a `git push`. `make checkstatic` should trigger.
This is a remake of #5246 that using plain git hooks instead of requiring a 3rd-party library.
=> Add opt-in option to auto run "make checkstatic" locally upon git push

src/Middleware/UserPageDecorationMiddleware.php
Do not display the "Admin" menu category when it contains
no items.
Fixes #5951.
=> Do not display admin menu category when empty

htdocs/acknowledgements/acknowledgements.php
remove useless column
Example public facing link:
`https://<YOUR-BASE-STUDY-URL>/acknowledgements/acknowledgements.php?date=2017-11-17`
Given the publication date of `2017-11-17`, this will limit the list to people
who started on or before `2017-11-17`.
This list is intended to be used in any publication(s), so keep in mind it will
be shared in the wild without authentication.
solve:
https://github.com/aces/Loris/issues/5885
=> [acknowledgements] public facing link broken - 500 error

modules/datadict/jsx/dataDictIndex.js, modules/datadict/php/datadict.class.inc, modules/datadict/php/datadictrow.class.inc, modules/datadict/php/datadictrowprovisioner.class.inc, modules/datadict/test/datadictTest.php
This updates the datadict module to use the data framework, using
the DataFrameworkMenu class infrastructure that was put in place
in #4918.
This necessitated updating the datadict from an older style of
our React components (where the QuickForm was serialized to
javascript server side) to the a newer form (where most of
the display concerns are handled from React, except for the
dynamic parts which must be sent by implementing getFieldOptions).
Unfortunately, the current React side filtering doesn't support
"Keyword" search in the same manner that was used, so it's
replaced by more consistent/traditional filters for now.
1.
*
=> [Data Dict] Update Data Dictionary module to use Data Framework

tools/lorisform_parser.php
With new update to Module or some related modules, the lorisform_parser is no longer working. See issue #5940, this PR is created according to the information provided by @driusan.
_To Reproduce_
Go to tools/, ls any instrument to feed lorisform_parser, the system will report
PHP Fatal error: Uncaught Error: Cannot instantiate abstract class Module in tools/lorisform_parser.php:57
1. Go to tools/, ls any instrument to feed lorisform_parser
Issue #5940
=> Module to NullModule change due to libraries modification

README.md
The badge version info gets pulled from our master branch on Travis so it's auto-updating.
=> Add PHP minimum version badge to README

jsx/Form.js
Select elements that have no label are supposed to take the whole row,
but the logic in the if statement was incorrect and no label was resulting
in an empty 3 columns of the bootstrap grid.
This fixes the logic.
=> [UI] Fix width of select elements that have no label

modules/user_accounts/php/edit_user.class.inc
When both the password and email fields were empty, an error was displayed saying "Your password cannot match your email address"
While technically accurate, this isn't actually helpful for a user, especially since our checkbox option "Generate new password" requires leaving the password field blank.
1. Verify the confusing error message in the linked Issue.
2. On this branch, do the same thing. The password error won't appear.
3. Repeat 2. but uncheck 'Generate new password'. Ensure that the error message "Please specify password or click Generate new password" is displayed instead.
* Resolves #5948
=> [User Accounts] Fix edge-case that gave a confusing error message

test/run-php-linter.sh
Adds the `tools/` directly to the files analyzed by `php -l` (basic syntax checking).
=> Add basic linting to tools/ scripts

CODE_OF_CONDUCT.md
This adds a CODE_OF_CONDUCT.md file with the goal of being as
non-politicized as possible. It defers to MCIN and McGill University
codes and policies with a vague paragraph trying to include external
contributors, who might otherwise think that we don't accept external
contributions.
1. Hire a lawyer and/or contact your local HR rep to ask if this code implies any legal or ethical issues that we should be aware of.
Resolves #5864
=> [Meta] Add CODE_OF_CONDUCT.md

SQL/0000-00-01-Permission.sql, SQL/New_patches/2019_07_02_Add_Edit_DoB_Permissions.sql, jsx/Form.js, modules/candidate_parameters/ajax/formHandler.php, modules/candidate_parameters/ajax/getData.php, modules/candidate_parameters/jsx/CandidateDOB.js, modules/candidate_parameters/jsx/CandidateParameters.js, raisinbread/RB_files/RB_permissions.sql
This PR adds a new tab to candidate parameters which can be used to amend a candidate's date of birth. 
This change is being applied as a result of the DoD meeting which took place on June 25, 2019. To follow is a PR which will add `Date of Death`.
**_[NOTE]:_** I am basing this PR on `21.0-release` branch for now, but will change it to `minor` after release happens.
=> [candidate_parameters] Add 'Date of Birth' tab

modules/statistics/php/statistics_site.class.inc
This fix an issue found during manual test in PR #5591 in which the `pselect` function from class `Database` was incorrectly called when using an IN clause in the SQL statement.
Now all candidates for all the sites for a given user should be displayed when asked for the **breakdown per participant** in **Statistics -> Behavioural Statistics -> breakdown per participant (link)**
* Resolves #5591
=> Fix to PR 5591: Correctly calling 'pselect' function from class 'Database'

modules/issue_tracker/ajax/EditIssue.php, php/libraries/Module.class.inc
Remove the remaining references to the LorisMenu table in the
issue tracker (in its ajax scripts) and update the code to
refer to the modules table instead.
Fixes #5938.
=> [Issue Tracker] Remove remaining references to LorisMenu table

SQL/0000-00-03-ConfigTables.sql, SQL/Cleanup_patches/2020-02-05-NoHostConfig.sql, SQL/New_patches/2020-02-05-NoHostConfig.sql, modules/api/php/endpoints/login.class.inc, modules/login/php/passwordreset.class.inc, modules/publication/ajax/FileUpload.php, modules/survey_accounts/php/addsurvey.class.inc, modules/user_accounts/php/edit_user.class.inc, modules/user_accounts/php/my_preferences.class.inc, php/libraries/NDB_Factory.class.inc, php/libraries/NDB_Notifier_Abstract.class.inc, php/libraries/NDB_Page.class.inc, php/libraries/Settings.class.inc, src/Router/BaseRouter.php, test/unittests/SettingsTest.php
The \LORIS\BaseRouter was already calculating the BaseURL of the incoming request and adding it to the request object. Unfortunately, most places in LORIS are not using it. Most instances would need to be refactored to get access to it since they're often deeper in the code and using `\NDB_Factory->settings()->getBaseURL()` at places with no direct access to the PSR7 request instance. This updates the code to have the router to pass the calculated URL to the factory singleton instance which injects it into the Settings object.
There were a very straggling instances to the (even older) `$config->getSetting('www')['url']` style of getting the baseURL which had to be updated to use the factory.
Fixes #5395, #6007.
1. Test LORIS. Everything should work as before.
2. Test LORIS via another …
=> Remove BaseURL config setting

modules/login/templates/form_passwordexpiry.tpl, modules/user_accounts/templates/form_edit_user.tpl, modules/user_accounts/templates/form_my_preferences.tpl
Adds a line to front-end explanation of password requirements to clarify what is expected from the users.
This is a small improvement but we need to add #5761 in order for this to be truly user-friendly.
* There was some confusion about the password requirements resulting in issue #5962. This is meant to address that confusion.
=> Clarify documentation on password requirements

Makefile, test/run-php-linter.sh, tools/raisinbread_refresh.php
This script will dump your raisinbread database and then re-import the data. It automates the steps in [raisinbread/README.md](https://github.com/aces/Loris/tree/minor/raisinbread).
* It will also restore your `url`, `base`, `host` settings so that LORIS won't break if you're not hosting it on `localhost`.
* It will ask you to change the front-end `admin` password so you can login to LORIS without using the public Raisinbread password.
* I've added `make testdata` as a quick way to refresh your database.
* This can also be used upon switching between branches so that you never get an issue where your database is broken because of sync issues.
~~As a precaution I decided to force the user of this script to manually type in the database name of the database they want to effectively delete. …
=> [Tools] Add script to delete and refresh raisinbread data

tools/raisinbread_refresh.php
#5260 was just merged but had references to a config setting removed in #6019.
=> Remove deleted URL config setting from raisinbread script

docs/wiki/00 - SERVER INSTALL AND CONFIGURATION/02 - Website Configuration/Handling Large File Uploads.md, mkdocs.yml, modules/genomic_browser/README.md, modules/imaging_uploader/README.md
Adds instructions to modifying Apache to allow for larger files to be uploaded via the front-end.
These will now be present on Read The Docs.
* Resolves #5849
=> Document how to upload larger files via front-end

README.md
Adds a build badge representing the status of our ReadTheDocs build.
It's helpful to have -- by chance, I noticed our build was failing. This would be a much earlier warning sign.
=> Add ReadTheDocs build status to README

php/libraries/NDB_BVL_Instrument.class.inc
Breadcrumb element of any instrument was linking to `instruments/instr/?commentID=587630DCC0901053161524238782` instead of `instruments/instr/?commentID=587630DCC0901053161524238782&sessionID=1053&candID=587630` like the instrument list module does. 
1. go on an instrument and click on it's breadcrumb with and without this PR
=> [Instrument] Breadcrumb does not match instrument_list link

modules/statistics/php/charts.class.inc
on MySQL 5.7 with SQL MODE `only_full_group_by` I get 500 errors on the dashboard for the query that was altered in this PR
1. open error_log
2. make sure your SQL mode is properly set to `only_full_group_by`
2. access the dashboard.
**NOTE** Whomever this affects should verify that the results on the query are unchanged from this PR
=> [stats] fixed only_full_group_by error in query

php/libraries/NDB_Menu_Filter.class.inc
Fix errors of the type "Undefined index: filter" when accessing
some NDB_Menu_Filter pages. This prevents some modules from loading
because the notice results in the JSON returned by LORIS being
invalid.
(This PR is a duplicate of #6011 but with the requested changes
incorporated, since some modules currently can't be loaded without a
fix.)
=> Fix "Undefined index: filter" errors in NDB_Menu_Filter

php/libraries/Database.class.inc, test/LorisCS.xml
PHPCS no longer fails code if it does not have:
* A class comment
* A PHP version
* Link tag
* Package tag
* Category tag
PHPCS still requires a file comment, author, and licence. I chose to keep file comments over class comments so that there will still be some documentation required for PHP code without classes, such as tools/ and ajax/ scripts.
=> Remove PHPCS requirement for boilerplate comments

.alexignore, .alexrc.yml, CONTRIBUTING.md, Makefile, README.Mac.md, README.md, docs/API/InstrumentFormat.md, docs/API/LorisRESTAPI.md, docs/HelpStyleGuide.md, docs/SQLModelingStandard.md, package.json
[How to remove condescending language from documentation](https://dev.to/meeshkan/how-to-remove-condescending-language-from-documentation-4a5p)
This post outlines why condescending documentation is a bad idea and recommends the `alex` tool to fix it.
This tool should be helpful as we go forward in creating our documentation on ReadTheDocs.
This PR:
* Adds the `alex` tool to devDependencies
* Creates configuration files for this tool
* Fixes detected occurrences
* Adds `alex` to our CI pipeline to prevent future issues.
=> Add tool to remove condescending language from LORIS documentation

.phan/config.php, modules/configuration/ajax/process.php, modules/examiner/php/editexaminer.class.inc, modules/imaging_uploader/php/imaging_uploader.class.inc, modules/media/ajax/FileUpload.php, modules/server_processes_manager/php/serverprocessesmonitor.class.inc, modules/statistics/php/statistics_mri_site.class.inc, modules/statistics/php/stats_demographic.class.inc, modules/user_accounts/php/edit_user.class.inc
This rule checks for a case where a variable may not be declared, for example if it is declared only within an if-statement, but the code below it uses it anyway.
e.g.
```php
if ($a === $b) {
$c = 10;
}
echo $a . $c;
```
The code assumes `$c` exists but this may not always be the case.
=> Add PhanPossiblyUndeclaredVariable rule to Phan checks

php/libraries/Module.class.inc
When there is an active module installed in the module table
that does not exist LORIS crashes with an exception while trying
to build the menus. This catches the exception and logs it to the
error log instead of dying.
While the 'Active' invalid module indicates a configuration error
that should be fixed, it can often happen in development environments
when switching branches, so instead we just log it in the error log.
=> [Core] Do not crash when there are Active invalid modules

test/phpunit.xml
Imaging QC was not included in the config file for our integration tests so until now the test for this module was not being done.
I also put the modules in alphabetical order.
=> [Imaging QC] Enable integration tests

test/integration.sh, test/unittests.sh
small change to bash syntax to pass shellcheck verification 
1.
in bash, run `shellcheck <scriptName>
run the script to confirm script behavior hasn't change 
shellcheck will eventually be enabled on all script (see #6053)
improve security
=> fix bash syntax

.phan/config.php
Raises phan's severity level to 1 from 5 (0 is the most sensitive, 10 is the least).
Our codebase passes under the current rules under almost the highest severity.
This will raise the bar for new code going into LORIS.
=> Increase phan severity level

jsx/Card.js
This allows the Card component to be provided with extra style
properties, which get merged into the parent div style attribute.
This can be used for specifying flexbox or CSS grid related properties
on a card.
=> [jsx/Card] Allow Card component to add extra styles to object

.github/ISSUE_TEMPLATE/bug_report.md
Adds a note to our bug report template that we only support the two most recent LORIS releases.
* Resolves #5109
=> Add support policy to bug report issue template

tools/raisinbread_refresh.php
Change the ordering of output redirection.
1. in tools/  `php raisinbread_refresh.php`
Ensure that no error message appear when the script test database connexion before deleting tables
* Resolves # 6060
=> [tools] fix redirection order

docs/CodingStandards.md, mkdocs.yml
The document was referring to an old process where we would manually test code with only PHPCS. Now it directs people to `make checkstatic` which automatically runs all of our analysis tools on all PHP source code.
=> Update Coding Standards document and add to ReadTheDocs

webpack.config.js
Currently, there is no way to access a module's exported
components from plain javascript in LORIS. This refactors
the webpack config so that each module's exports can be
accessed in lorisjs.modulename.exportname. For instance,
if a LORIS module named "MyModule" defines as class as
`export class MyClass {}` it would be accessible as
`lorisjs.MyModule.MyClass`. Note that any exports done
via statements at the end of the file such as `export default MyClass;`
(separate from the named class definition) are accessed as
`lorisjs.MyModule.default`, not `lorisjs.MyModule.MyClass`. A
module may only have one default export, or it will be overridden
according to webpack's whims.
Everything in LORIS should work identically to before with the
exception that the exports are now available via plain …
=> [webpack] Make module exports importable from LORIS

jsx/Card.js, jsx/Panel.js
This fixes the warnings from eslint in the Card and
Panel classes.
These had old warnings that were triggered while trying to validate that #6090 did not introduce any new errors.
=> [JS] Fix eslint errors in Card and Panel classes

modules/user_accounts/php/edit_user.class.inc
This form was hidden when it should not have been. In a recent meeting it was decided that it's OK for a user with `User Management` to edit their own examiner status.
1. Grant a user "User Management" and "Across all sites add and certify examiners"
2. Make sure that user can change their account details in `/user_accounts/edit_user/`
* Resolves #6012
=> [User Accounts] Fix hidden form field bug

modules/acknowledgements/php/acknowledgements.class.inc, modules/acknowledgements/test/AcknowledgementsTest.php, test/integrationtests/LorisIntegrationTest.class.inc
We've had many issues reported lately where module `X` doesn't load when a user has only the `X_edit` permission without the `X_view` permission. 
In almost every case, it should be possible to at least view a module when you have any of its permissions.
This is trivial to check with integration tests, but many modules are lacking permission checking or they are out of date with respect to new permissions added to a module.
This PR aims to address both of these by creating a generic way to check module permissions using integration tests by adding new methods to the parent class that can validate permissions in a standard way.
All module integration tests going forward can use this idiom to simply and concisely validate that a module loads IFF the user has one of the permission codes for …
=> [Core/Acknowledgments] Create generic way to check module permissions using integration tests

modules/imaging_browser/php/imagingbrowserrowprovisioner.class.inc
for a new installation, the `$modalities_subquery` might be empty, then the Query will be invalid, this causes some confusion for new users.
1. click on the Imaging browser module link
Issue #6088
=> [imaging browser] query construction bug

jsx/Card.js
onClick is not a required and defaults to null. Add a guard
so that an error is not triggered when none is provided.
=> [jsx/Card] Do not error out when no onClick is provided

jsx/CSSGrid.js
This adds a CSSGrid component type. A CSSGrid aligns
a number of cards (passed as a prop) in a grid. The
component takes care of converting the values passed
to it into cards with an appropriate title, size
and positioning.
=> [JSX] Add CSSGrid component type

modules/bvl_feedback/php/module.class.inc, modules/conflict_resolver/php/module.class.inc, modules/dashboard/php/dashboard.class.inc, modules/dashboard/php/module.class.inc, modules/document_repository/php/module.class.inc, modules/imaging_browser/php/module.class.inc, modules/instruments/php/module.class.inc, modules/issue_tracker/php/module.class.inc, modules/mri_violations/php/module.class.inc, modules/statistics/php/module.class.inc, modules/user_accounts/php/module.class.inc, php/libraries/Module.class.inc
This factors out the signature change from PR #6092 to simplify
the review process.
The signature of getWidgets if changed to include a weakly typed
'$options' parameter, which can be used to specify type-dependent
options.
=> [Widgets] Update signature of getWidgets to include options

docs/deprecated_wiki/Upgrading-17.0-to-17.1.md
We don't support this version of LORIS anymore so this document doe snot need to come forward with us into the new ReadTheDocs wiki.
There's also no content in it
=> Remove empty "Upgrading 17.0 to 17.1" document

jsx/Loader.js
The component is used multiple places, so generates numerous
warnings when running `make dev`. It's also very simple, so
easy to fix.
This also converts the component from a class to a function,
because that seems to be more in-line with the direction that
React is taking with React hooks, and there is no external
state.
=> [JSX] Fix ESLint errors in <Loader /> component

CHANGELOG.md, README.md, tools/create-project.sh, tools/install.sh
This PR improves the way UNIX permissions are used in LORIS.
* `lorisadmin` owns all files
* `lorisadmin` has sudo
* `www-data`/`apache2` selectively owns and is the group for web-writable files
* e.g. `drwxrwxrwx 2 www-data    www-data 4096 Oct  9 16:30 user_uploads`
*  Uses the same permissions as `lorisadmin`
* Typical permission codes: `775`, for directories, `664` for files 
* **Result**: On certain files and folders, Apache gets to do everything `lorisadmin` can do
* `lorisadmin` owns all files
* `lorisadmin` has sudo
* `lorisadmin` is the group for all files
* e.g. `drwxrwxrwx 2 lorisadmin    lorisadmin 4096 Oct  9 16:30 user_uploads`
* `www-data`/`apache2` is part of the `lorisadmin` group
* Typical permission codes: `755` for directories, `644` for files.
* **Result**: Certain …
=> [Core/Install] Improve UNIX permission usage

modules/survey_accounts/php/module.class.inc
Survey Accounts is the proper name of the module but the long name and menu item were "Survey Module"
This change the module's long name to match the way we refer to it in our file structure and documentation.
=> [Survey Accounts] Fix long name

modules/api/README.md
The API module is missing a README, because it didn't exist
as a module when it lived under htdocs and none was written
when it was migrated to a "real" LORIS module. This takes
a first pass at writing one to officially define its purpose.
=> [API] Add README for api module

src/Router/BaseRouter.php, src/Router/ModuleRouter.php
The module path and routes calculated by the ModuleRouter
are unused. In fact, the path passed to them is sometimes
wrong. The CSS, JS, and Static routes are handled by the
\Module class (where the path comes from the \Module::factory,
not the ModuleRouter). This removes the confusing dead
code.
1. Test LORIS modules that have custom CSS, JS, or use the /static directory. In particular, project overrides for such modules should still work.
=> [Router] Remove unused routing logic from ModuleRouter

php/libraries/NDB_BVL_InstrumentStatus_ControlPanel.class.inc
Reverses changes from https://github.com/aces/Loris/pull/4928 that renames $ValidityEnabled to $validityEnabled and $ValidityRequired to $validityRequired. The variabes are UpperCamerCase elsewhere on Loris. This PR removes the following error that does not allow the Validity flags to render in instruments' control panels
```
PHP Notice:  Undefined property: NDB_BVL_Instrument_aosi::$validityEnabled in /var/www/loris/php/libraries/NDB_BVL_InstrumentStatus_ControlPanel.class.inc on line 101
PHP Notice:  Undefined property: NDB_BVL_Instrument_aosi::$validityRequired in /var/www/loris/php/libraries/NDB_BVL_InstrumentStatus_ControlPanel.class.inc on line 102
```
1. On master, go to any instrument page and verify that the 'Validity' section in the control panel is not there. In your apache …
=> [InstrumentStatus_ControlPanel] Restore $validity to $Validity

webpack.config.js
Restore functionality broken in #6083 
Projects can define their own targets for webpack to compile. this functionality was already there, this is just a fix for it to be functional again.
projects should define their file as such
filename:`webpack-project.config.js`
```
const entry = {
'candidate_parameters' : ['CandidateParameters'],
'study_tracker' : ['index'],
'user_accounts' : ['userAccountsIndex']
};
module.exports = entry;
```
=> [webpack] restore support for webpack-project

modules/dashboard/php/dashboard.class.inc, src/LorisInstance.php, src/Middleware/UserPageDecorationMiddleware.php, src/Router/BaseRouter.php
This adds a class to LORIS to represent an installed LORIS instance.
It is primarily a stub that can be expanded in the future.
Resolves #6022
=> [Core] Add LorisInstance class

jsx/Card.js, modules/candidate_parameters/jsx/ConsentWidget.js, modules/candidate_parameters/php/module.class.inc, php/libraries/Candidate.class.inc, webpack.config.js
This adds a card with a summary of the candidate's consent to
the candidate_profile module. A table is shown with rows for
each type of consent showing the status and date of the consent
or withdrawal.
=> [candidate_profile] Add card summarizing candidate consent

modules/candidate_parameters/jsx/ConsentStatus.js
As discussed in today's Loris meeting, this PR changes the select field label to simply 'Response', the DateGiven field to 'Date of Response' and the DateWithdrawn field to 'Date of Withdrawal of Consent'. In place of the consent label being displayed in the label of the response select field, I have added a HeaderElement to display the consent label.
1. On 23.0-release, go to a candidate's consent status tab and see the UI
2. On this branch, see that the field labels have changed as described above and that the consent label is now being rendered as a header. Play around and see that there are no functional changes to the tab. Save a consent and verify nothing is broken.
=> [Candidate_parameters] Consent Status - Change label to 'Response'

SQL/0000-00-00-schema.sql, SQL/New_patches/2019-10-29_adding_issues_attachments_table.sql
This adds a foreign key from the issues_attachments table to the issue table. Since the issues_attachments hasn't been released yet, the existing patch is modified instead of adding a new patch for existing projects. (I also moved the issues_attachments table to be grouped with all the other issues related tables in the default schema.)
=> [issue_tracker] Add foreign key from issues attachments to issue

CONTRIBUTING.md, docs/CodingStandards.md, docs/wiki/99 - Developers/Automated Testing.md
Modifies some of our developer documentation to be up-to-date and less repetitive. Moves some sections around so that they are in a more appropriate place.
Resolves #4390  (With some parts of that issue being handled by #6105)
=> Streamline developer documentation

jsx/Breadcrumbs.js
This fixes the warning:
```
Warning: componentWillMount has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
* Move code with side effects to componentDidMount, and set initial state in the constructor.
* Rename componentWillMount to UNSAFE_componentWillMount to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
Please update the following components: Breadcrumbs
```
That has begun appearing since upgrading React.
=> [Breadcrumbs] Fix React warning about componentWillMount being deprecated

modules/conflict_resolver/jsx/conflictResolverIndex.js
The conflict resolver updates the URL when filters are modified to
reflect the current state of the filters. However, when these links
are loaded on their own the filters are not reflected in the results
until some other filter is changed.
This fixes the conflict resolver so that after data is loaded the
filter automatically applies to the results.
=> [conflict_resolver] Fix links to conflict resolver with filters set

modules/candidate_parameters/php/module.class.inc, modules/candidate_profile/jsx/CandidateInfo.js, modules/candidate_profile/php/candidate_profile.class.inc, modules/candidate_profile/php/candidateinfo.class.inc, modules/candidate_profile/php/module.class.inc, php/libraries/Candidate.class.inc
This adds a new type of widget ('candidateinfo') which can be used by modules or projects to add information to the "Candidate Info" card on the `candidate_profile` page. The new type of widget can be used by a module (or project module) to add information that can be summarized as a scalar to the quick summary.
It uses the new type to add information from the `candidate_parameters` module that make sense as an overview for the candidate. The Participant Status, Caveat, and any 'Candidate Parameters' category variables from the `parameter_candidate` table are now summarized in the card.
Other information from the candidate_parameters module is complex enough to merit its own card (ie. Consent often contains multiple entries to be summarized for different types of consent, and shouldn't be …
=> [candidate_profile] Add Candidate Parameters to Candidate Info card

modules/survey_accounts/php/survey_accounts.class.inc, modules/survey_accounts/php/surveyaccountsprovisioner.class.inc, modules/survey_accounts/php/surveyaccountsrow.class.inc, modules/survey_accounts/test/survey_accountsTest.php
This updates the survey accounts module to use the data framework. Functionality should remain identical to before, except that "Site" and "Project" permissions should now be enforced by the menu filter and users should not see rows from other project/site's sessions.
=> [Survey Accounts] Data Frameworkify the module

php/libraries/NDB_BVL_Instrument_LINST.class.inc
Linst instrument subtests are blank and not able to render its fields. This is because of legacy request variable left over from before PR https://github.com/aces/Loris/pull/4229 that introduced a new instruments loading module.
This PR replaces the call for a request variable that doesn't exist with the class' $this->page
*This might only be testable by a project developer who has access to a multi-page linst instrument. Raisinbread currently only has the bmi.linst, which does not have subtests. 
1. Go to any multi-page php instrument with subtests. There will be no errors. You are able to view everything fine.
2. Do the same with a mutli-page linst instrument with subtests. You will only be able to see the 'top' page, and not any of the other subtests.
3. On this PR branch, you will be …
=> [NDB_BVL_Instrument_LINST] Show subtests

modules/api/php/views/candidate.class.inc, modules/api/php/views/visit.class.inc, modules/api/php/views/visit/dicoms.class.inc, modules/api/php/views/visit/flags.class.inc, modules/api/php/views/visit/image/headers/full.class.inc, modules/api/php/views/visit/image/headers/specific.class.inc, modules/api/php/views/visit/image/headers/summary.class.inc, modules/api/php/views/visit/image/qc.class.inc, modules/api/php/views/visit/images.class.inc, modules/api/php/views/visit/instrument.class.inc, modules/api/php/views/visit/instruments.class.inc, modules/api/php/views/visit/qc.class.inc, src/StudyEntities/Candidate/CandID.php
Since CandID are proper objects and no longer strings or integer, json_encode was returning those objects as `{}`
This add the JsonSerialize function to the class to specify how json_encode should treat thos objects. In this case, as a string which value is the candid.  
Query any API endpoint which returns a CandID (most do in the Meta fields)
This will also fix the new endpoints return value in https://github.com/aces/Loris/pull/5739
=> [Core] CandID implements JsonSerializable

modules/data_release/.gitignore, modules/electrophysiology_browser/.gitignore, webpack.config.js
After `make` command is run, some files were showing up in the untracked files category, we can ignore these JS files because they are compiled.
Also, some imported JSX files were being compiled unecessarily, I removed them from the webpack file
=> Add .gitignorefile and remove unnecessary transpiling of files

docs/deprecated_wiki/How-to-Code-an-Instrument.md, docs/instruments/NDB_BVL_Instrument_TEMPLATE.class.inc, docs/instruments/NDB_BVL_Instrument_UPLOADER_TEMPLATE.class.inc, php/libraries/NDB_BVL_Instrument.class.inc, php/libraries/NDB_BVL_Instrument_LINST.class.inc, raisinbread/instruments/NDB_BVL_Instrument_aosi.class.inc, raisinbread/instruments/NDB_BVL_Instrument_medical_history.class.inc, raisinbread/instruments/NDB_BVL_Instrument_mri_parameter_form.class.inc
This was showing up as an error on my IDE, the variable is defined as private in the hchild class while the parent class refers to it.
change from `_select...` to `select...` because static checks enforce the ugly `_` before private variable rule
=> Instruments variable incorrectly defined

modules/media/README.md, modules/media/jsx/CandidateMediaWidget.js, modules/media/php/module.class.inc, webpack.config.js
This adds a widget to the candidate dashboard to display
any media associated with the candidate from the media
module. The visualization of how the data is displayed
is the same as the "Document Repository" widget on the
main LORIS dashboard.
=> [candidate_profile] Add media widget

modules/issue_tracker/README.md, modules/issue_tracker/jsx/CandidateIssuesWidget.js, modules/issue_tracker/php/module.class.inc, webpack.config.js
This adds a widget for any unclosed issues associated with a candidate to the
candidate dashboard. If there are no unresolved issues, the card is not displayed.
Issues are displayed as a simple list with links to the issue.
=> [candidate_profile] Add widget for open candidate issues to the candidate_profile

CHANGELOG.md, modules/candidate_list/jsx/candidateListIndex.js, modules/candidate_list/jsx/openProfileForm.js, modules/candidate_list/php/module.class.inc
Include 2 menu items in the LORIS menu, one of which accesses the
old timepoint_list module and one of which links to the new candidate_profile
module.
=> [Menu] Add new menu item to access beta candidate profile module

htdocs/js/instrument_controlpanel_control.js, htdocs/main.css, php/libraries/NDB_BVL_InstrumentStatus_ControlPanel.class.inc, smarty/templates/instrumentstatus_controlpanel.tpl
As a result of discussions springing up on https://github.com/aces/Loris/pull/5949, this PR adds a hover over tooltip on the Data Entry 'Complete' option in the instrument control panel to explain why 'Complete' is not clickable.
If the whole instrument is empty i.e. required fields have not been filled out, the workflow goes like this:
**1. If Administration and Validation empt**y
- 'Complete' not clickable
**2. If Administration 'None':**
- 'Complete' clickable
**3. If Administration 'Partial':**
- If Validity doesn't exist, 'Complete' clickable
- If Validity exists and empty - 'Complete' not clickable
- Validity selected - 'Complete' clickable
**4. If Administration 'All':**
- If Validity exists and empty - 'Complete' not clickable
- Validity selected or doesn't exist - 'Complete' not …
=> [Instrument_controlpanel] Add tooltip to explain 'Complete'

CHANGELOG.md, modules/issue_tracker/ajax/EditIssue.php
The issue tracker currently limits the dropdown to non-DCC study sites.
When entering a PSCID from a site such as the DCC, this means that there
is an (unresolvable) error about the PSCID and CenterID not matching,
because the candidate's site doesn't exist in the dropdown. This
updates the issue tracker to display all sites.
=> [issue_tracker] Include all sites in dropdown for issue tracker

php/libraries/NDB_BVL_Instrument.class.inc, php/libraries/NDB_BVL_Instrument_LINST.class.inc
This PR adds a function that determines an instrument's completion progress based on how many of its required fields have been filled out. This new function evolved from the already existing `_determineDataEntryCompletionStatus` function.
This function is being used in the new candidate profile page as implemented by PR https://github.com/aces/Loris/pull/6121
1. Test https://github.com/aces/Loris/pull/6121 to see if the function determineDataEntryCompletionProgress() is doing what it's intending to do.
2. On that branch, visit `https://$LORISURL/candidate_profile/$candID` and click on one of the timepoint boxes in the 'Behavioural Data' card to expand the instrument list for that timepoint with corresponding completion progress bar
3. Select a fresh blank instrument (completion progress …
=> [NDB_BVL_Instrument] Data entry completion progress function

raisinbread/RB_files/RB_modules.sql
add electrophysiology_browser into raisinbread. 
Electrophysiology_browser shows after runing raisinbread in local Loris.
=> [raisinbread] missing electrophysiology_browser module. 

tools/install.sh
This PR fixes an issue where a variable was used in the install script without being declared. It caused a bug during CentOS installation.
1. On CentOS, run the install script.
* Resolves #6185
=> [Install] Prevent unbound variable error

docs/wiki/99 - Developers/Automated Testing.md
The change is made to the markdown file. This fix a minor problem with the link to the unit test guide.
Haowei Qiu, Google Summer of Code Applicant
CC @christinerogers
=> minor fix on the link to the unit test guide

modules/dashboard/php/dashboard.class.inc, modules/dashboard/php/module.class.inc
=> [Dashboard] Update User::singleton() declarations to facilitate unit testing

modules/issue_tracker/ajax/EditIssue.php, modules/issue_tracker/php/attachment.class.inc, modules/issue_tracker/php/issue.class.inc, modules/issue_tracker/php/issue_tracker.class.inc, modules/issue_tracker/php/issuerowprovisioner.class.inc, modules/issue_tracker/php/issuewatchermapper.class.inc, modules/issue_tracker/php/uploadhelper.class.inc
=> [Issue Tracker] Update User::singleton() declarations to facilitate unit testing

modules/instruments/jsx/CandidateInstrumentList.js, modules/instruments/jsx/VisitInstrumentList.js, modules/instruments/php/module.class.inc, modules/instruments/php/visitsummary.class.inc, php/libraries/NDB_BVL_Instrument.class.inc, webpack.config.js
This adds a "Behavioural Data" widget to the candidate_profile
page for anyone who has access to the instruments module. The
Behavioural Data consists of a list of (initially collapsed)
visits which on click expand to a list of instruments and the data entry
percentage which is complete. Links are provided to the instrument
for data entry, the visit, and the conflict resolver (if applicable).
=> [candidate_profile] Add behavioural data widget

php/libraries/LorisForm.class.inc
Removed duplicate call to `HTMLSpecialChars()` causing double escaping on any instrument field with one of the following characters `& < > "`
The removal is justified since these fields are being escaped directly in the database class
https://github.com/aces/Loris/blob/master/php/libraries/Database.class.inc#L538
=> [Instruments] Bugfix multi-escaped special characters

modules/publication/ajax/FileDelete.php, modules/publication/ajax/FileDownload.php, modules/publication/ajax/FileUpload.php, modules/publication/ajax/getData.php, modules/publication/php/publication.class.inc, modules/publication/php/view_project.class.inc
=> [Publication] Update User::singleton() declarations to facilitate unit testing

src/Router/BaseRouter.php
This PR solves wrong URL problem in timepoint list at single parameter mode and the 404 error in the #6323. The PRs could be separated, but since the fix was applied to the same file instead of modifying instrument_list module, I just put the PRs together. The work were done in two steps.
Possible issue: if the value doesn't exist, the system will return an empty page with 500 error, #6325 which could be addressed in another PR.
Test directive:
Go to 'candidate profile'
Click on any profile
To test:
The issue #6271
Click on 'Create time point' button in the Actions zone
See the link itself, "v.loris.ca//create_timepoint..."
The correct one should not have double "/"
The issue #6272
Click on 'Candidate Info' button in the Actions zone
See the link itself, …
=> Timepoint list baseurl problem fix

modules/candidate_profile/php/candidate_profile.class.inc
Breadcrumb should go to the new module, not the old one.
Fixes #6305
=> [candidate_profile] Fix breadcrumb links in candidate_profile

modules/electrophysiology_browser/php/sessions.class.inc
This fixes the broken breadcrumb on the electrophysiology browser session page.
1. Check that the Session breadcrumb works on an electrophysiology session page.
* Resolves #6212
=> [electrophysiology_browser] Fix session breadcrumb

modules/mri_violations/php/mri_protocol_check_violations.class.inc
This PR fixes the broken links that you find on the MRI protocol checks violations sub-page of the MRI violations module.
Access the MRI violations module and search for violations for which the type of problem is `Protocol Violations`. When the search results are displayed, click on any of the `Protocol Violations` link (column `Problem`). This will take you to the MRI protocol checks violations sub-page. Click on any of the links in the patient name column. You should now be taken to a page of the DICOM archive module but the page will be missing almost all of its fields. This should not happen and the all (or almost all) the fields displayed on the page should have a value.
* Resolves #6318
=> [MRI Violations] Link to DICOM archive broken.

htdocs/css/simple-sidebar.css
This PR fixes this:
1. On mobile view, go to any instrument page and open up the side control panel. See what is on the screenshot above.
2. On this PR branch, see that the control panel now has correct font colours (same as on desktop)
=> [Instruments] Control Panel on Mobile has bad UI

README.md
* Fix broken link to LORIS webiste
* Fix broken link to MCIN website
* Change wording to "The Neuro" (this is recommended branding by the institution)
* Remove superfluous subheader
* Remove sudden change from first- to third-person writing style
1. Make sure the links work.
=> Fix broken links to MCIN websites in README; cleanup

modules/candidate_profile/help/candidate_profile.md
This adds some help text for the candidate_profile module. The help text is somewhat vague by necessity since it isn't context sensitive and the exact set of cards shown depends on the user's permissions and LORIS install's configurations. It only explains the visit link in the Candidate Info card (which is provided by the module itself and has minimal permissions, so should always be present.)
Fixes #6206
=> [candidate_profile] Add help text

modules/my_preferences/templates/form_my_preferences.tpl, modules/user_accounts/php/edit_user.class.inc, modules/user_accounts/templates/form_edit_user.tpl
The password field gets auto-completed on the edit_user page. This is a problem because the back-end expects this value to be blank unless you are changing a user's password.
What often happens is that when a user submits an unrelated account change and they get an error message saying that they must change their password.
This is symptomatic of general UI clunkiness in this module. Until it's reworked, disabling autocomplete seems like the best solution.
1. Visit `edit_user` and make sure the password fields are empty when you load the module.
I think this Resolves #6319
=> [User Accounts] Disable password auto-completion on edit_user page

smarty/templates/403.tpl
Add possibility to go back one page because if the permission control kicks in, we have to return to the home page if we don't know click on the browser back button
The #6266 is hard to do optimistically because imaging browser and instrument list are presented as two independent modules. The current solution could solve the similar problem in any module.
1. Click on any link that you don't have the permission, like a profile imaging data link, then the system will ask you to go back to the home page, you will have to start over again to navigate through the system.
Partially resolves #6266
=> [smarty template] add possible go back one page function

docs/ModuleWidgets.md
This adds developer documentation for the existing types of widgets that
can be added to LORIS modules, and what their expectations are of
the `getWidgets` function.
=> [Docs] Add documentation for the getWidgets function

modules/genomic_browser/README.md
Resolves #6389 
This PR adds content for the Scope and Intended users section, which have been empty since added in #5827
=> [GenomicBrowser] Readme missing sections added 

modules/imaging_uploader/jsx/UploadForm.js
This PR corrects the failures or these test cases:
1. Access the Imaging uploader module.
2. Select 'Yes' in the phantom scan drop-down.
3. Select a file with a name of the form `PSCID_CANDID_VISITLABEL.tar.gz`.
You'll that the CandID, PSCID and visit label field get populated even though they should be left empty.
1. Access the Imaging uploader module.
2. Select 'No' in the phantom scan drop-down.
3. Select a file with a name of the form `PSCID_CANDID_VISITLABEL.tar.gz` (the CandID, PS and visit label fields will be populated, which is all right).
4. Select 'Yes' in the phantom scan drop-down.
You'll that the CandID, PSCID and visit label field stay populated even though they should be erased.
See above
* Resolves #6288
=> [Imaging Uploader] Incorrect values in upload form for phantom scans.

modules/timepoint_list/templates/timepoint_list_controlpanel.tpl
The PR will now make the "Candidate Info" button be shown when the user doesn't have data_entry role permissions.
1. Make a user without data_entry role but with the necessary permissions to view Candidate Info.
2. Visit the Candidate Info with that user.
#6275
=> [candidate_parameters] Display Candidate Info button without data_entry permission

modules/mri_violations/jsx/columnFormatterUnresolved.js, modules/mri_violations/php/mri_violations.class.inc
This PR makes sure that when you click on any of the links in the MRI violations search results table, you are taken to a page where the filter is entirely filled out.
1. Access the MRI violations page and search for violations of type `Protocol Violations`. Click on the `Protocol Violation` link in the problem column when the search results are displayed. Ensure that the filter of the page you are taken to has entries for all its fields and that those correspond to the values found for the record displayed on the page you came from.
2. Test the same thing but for violations of type `Could not identify scan type`.
* Resolves #6300
=> [MRI Violations] Filter not populated completely after following links.

raisinbread/instruments/NDB_BVL_Instrument_aosi.class.inc
As the title says
Access the AOSI instrument and check that the question for the examiner location is 'Examiner location' and not 'Circle One'.
* Resolves #6269
=> [Instruments] Change examiner location question for instrument AOSI.

php/libraries/LorisForm.class.inc
This PR is the recreation of the PR #5886
A instrument with
`$this->addLabel('<label>')` will always report PHP warning "Undefined index: name in LorisForm.class.inc on line 1242"
This happens because Loris form assumes that a name is mandatory, even for a label. I don't see the necessity here.
1. 1. Create an instrument, or a unit test case, put a label `$this->addLabel('<label>')` anyway in an instrument, click the save button, check whether the PHP warning is in the log.
=> [Lorisform] undefined name fix

modules/bvl_feedback/jsx/react.behavioural_feedback_panel.js
Cleanup console log errors when viewing instrument_list and from mismatched react propTypes.
1.  View the browser console when viewing the module "instrument_list" on 23.0-release branch.
2. Checkout PR and do the same.
edit: Make sure the sandbox value is set to 1.
```
<config>
<dev>
<sandbox>1</sandbox>
</dev>
...
</config>
```
#6381
=> [instrument_list] cleanup browser console errors

php/libraries/LorisForm.class.inc, php/libraries/NDB_Page.class.inc
This is the recreation of the PR #6347 but without `var` to `public` variable declaration modifications at the beginnings of the two classes, the latter is not necessary as the others included in this PR.
Quite often the term `options` are mixed with the term `attributes` at different meanings and locations, this will create confusion for the programmers. This PR tries to correct this problem. This PR has also a little doc modification and the removal of the variable `$closer`, the latter is not too much related with the main task.
=> [LorisForm&NDB_Page] option vs attribute misuses

htdocs/css/simple-sidebar.css
Display overlap problem fix
1. Open a profile, click instrument list to show sidebar, check whether the menu is visible or not.
Issue #6411
=> [menu] fix instrument_list display problem

modules/dataquery/jsx/react.fieldselector.js, modules/dataquery/jsx/react.paginator.js, src/Router/BaseRouter.php
Fixes a bug with Data Query Tool where pagination list would not update based on the amount of results displayed.
1. Go to `Define Fields` tabe of DQT
2. Choose an instrument and filter instruments by 'Searching within Instrument'
3. Check that the pagination is displaying correctly.
* Resolves #6247
=> Fixed Pagination for Data Query Tools

jsx/CSSGrid.js, jsx/Card.js, jsx/Panel.js
This attempts to improve the layout of the CSS grid used by the `candidate_profile` page and after testing the page as a whole, rather than on an individual card basis.
- Height (in terms of number of grid rows spanned) of a card is now calculated dynamically, rather than needing to be heuristically guessed by the module registering the widget. 1 row = 100px. 
- Cards that have a width of "1" are always placed in the left column, until there are no more "large" (> 2) cards left, after which they start filling in underneath the other columns, so that column sizes the sizes are relatively balanced.
Combined, this improves the number of gaps when there are multiple cards added to the dashboard.
Before: 
After:
=> [candidate_profile] Improve gridyness of grid

jsx/DataTable.js, jsx/Filter.js, jsx/FilterableDataTable.js
Updated the propTypes to correspond with the correct "type" of the data being passed to the components. Updated DataTable.js to have a key be passed using React.cloneElement.
1. Visit the candidate_list module and view the browser console.
edit: Make sure the sandbox value is set to 1.
```
<config>
<dev>
<sandbox>1</sandbox>
</dev>
...
</config>
```
#6379
=> [jsx/(Filter.js FilterableDataTable.js DataTable.js)] Browser console error cleanup

modules/configuration/ajax/process.php
In the Config module, this error message is thrown whenever a duplicate value is submitted for a config ID (read the code comment for more details).
Previously this error message was targeted toward a specific part of the config module when it is in fact a more general error message. 
1. Reproduce the bug in #6287. You should get the new error message.
* This was brought up by #6287 but does not fully resolve it. The ticket requests error highlighting for the field generating the error which entails more significant changes to the module.
=> [Configuration] Improve error message

modules/statistics/php/stats_demographic.class.inc
Fix for` Statistics --> Demographic `where a user with the permission of a single project was able to see other projects in the project drop-down menu.
- The project drop-down menu was filtered to only show the projects for the logged user. 
- The results were filtered as well for the case "All Projects" is selected only allowing "All Projects for the logged user"  
1. Assign a user with one project permission.
2. go to statistics/Demographic Statistics
3. select project
4. See only the allowed projects in the drop-down menu.
5. If the option "All Projects" is selected the results should reflect only "All Projects for the logged user" 
To think if it will be good to add a new function to the `User class` for retrieving the projects for a given user the same way it exist for the user …
=> [Statistics / Demographic] fix issue where users were able to see other projects in the drop-down menu.

php/libraries/LorisForm.class.inc
This is the recreation of the PR #5884 first commit [e0ffb13](https://github.com/aces/Loris/pull/5884/commits/e0ffb13fb558ad8cde4d5c200e6747ed0daa3f88)
The third parameter of the form elements in the group mode was set as the fourth parameter somehow for `static` text Form type, this is clearly a bug.
The old format could be working in the following way (I just pass the label at the wrong place to make the system work):
$this->form->createElement('static', null, null, "label");
I noticed that the [wiki](https://github.com/aces/Loris/wiki/Instrument-Groups) manual suggests to use the format:
$group[] =& $this->form->createElement("static", null, null, "label");
I suggest to use the new format to be consistent with other types:
$this->form->createElement('static', null, "label");
Another …
=> [LorisForm] Form static element bug in group mode

modules/media/jsx/editForm.js
- go to media module, check if language of document is properly displayed in table
- edit a document with a language, current language should be displayed in the edit window.
- modify the language and check that change are properly reflected in table
https://github.com/aces/Loris/issues/6312
=> [media] use languageLabel derived from language_id to display

modules/candidate_profile/test/TestPlan.md
Add a test plan for new `candidate_profile` module to test
the functionality provided by the module itself.
Fixes #6207
=> [candidate_profile] Add test plan for module

htdocs/js/jquery.dynamictable.js
To be honest, I'm not sure how this became broken or 100% why this fixes it because the jQuery file doesn't seem to have been changed in a long time, but it does. This entire jQuery file should probably be moved to React at some point in the near future.
1. On aces/23.0-release, run make dev
2. Go to any Menu Filter module (e.g. media, candidate_list) with a large enough number of rows that you can scroll down the page.
3. See frozen headers work properly.
=> [DataTable] - Fix Frozen Headers

modules/candidate_list/php/candidate_list.class.inc, modules/datadict/php/datadict.class.inc, modules/dicom_archive/php/dicom_archive.class.inc, modules/electrophysiology_browser/php/electrophysiology_browser.class.inc, modules/imaging_browser/php/imaging_browser.class.inc, modules/media/php/media.class.inc, modules/module_manager/php/module_manager.class.inc, modules/survey_accounts/php/survey_accounts.class.inc, modules/user_accounts/php/user_accounts.class.inc, php/libraries/DataFrameworkMenu.class.inc
This PR adds a new abstract function to the DataFrameworkMenu: `useSitePermissionsFilter`. This function is meant to signal to the base class that the page's provisioner can support the `HasAnyPermissionOrUserSiteMatch` filter. 
This is needed because currently there is no way to signal to the provisioner that the user has an "across all sites" type of permission for the data being retrieved, and should therefore not filter based on site match.
1. Go through the affected modules and make sure the data tables are filtered properly according to their related site access permissions. 
Should remain unaffected, but should check functionality:
#6350
=> [DataFramework Filters] Check Site Permissions Filter

modules/electrophysiology_browser/test/TestPlan.md
First commit of a manual test plan for the Electrophysiological Browser module - for the 23.0.0 release
Partially modelled on the Imaging Browser test plan.
Resolves #6313 
To test : validate the test plan, and check for clarity and completeness of instructions
=> [ElectrophysiologyBrowser] Adding manual TestPlan

modules/user_accounts/php/edit_user.class.inc
Solves the `undefined index` error from polluting the error_log and when removing pending approval for a user in user_accounts module. 
1. Request account
2. Visit user_accounts module as admin
3. Remove pending approval for account.
#6353
=> [user_accounts] Resolve Notice: Undefined index: permID

modules/imaging_browser/test/TestPlan.md
I tried to make the test plan a little bit more clear and consistent with other test plans.
* Removed numbering
* Removed letters in front of sub-headings
* Added backticks to denote permissions
* Changed some wording to be more clear
=> [Imaging Browser] Cleanup test plan

SQL/0000-00-01-Permission.sql, SQL/New_patches/2020-04-27-AddViolatedScansOwnSitePermission.sql, modules/mri_violations/README.md, modules/mri_violations/php/module.class.inc, modules/mri_violations/php/mri_protocol_check_violations.class.inc, modules/mri_violations/php/mri_protocol_violations.class.inc, modules/mri_violations/php/mri_violations.class.inc, modules/mri_violations/php/resolved_violations.class.inc, modules/mri_violations/test/TestPlan.md, modules/mri_violations/test/mri_violationsTest.php, php/libraries/NDB_Menu_Filter.class.inc, raisinbread/RB_files/RB_permissions.sql
This PR fixes the following bugs in the MRI violations module, both in the `Not Resolved` and `Resolved` tabs:
1. When you select a given site in the drop-down list, the results contain records for which the site entry is empty: these should not be part of the result set.
2. When you access the MRI violations page for the first time or hit the `Clear Filter` button, all the MRI violations are shown even if the user does not have the `access_all_profiles` permission.
1. Check that the filter's sites drop-down list offers choices that allow you to see/hide the violations that are not associated to any site.
2. Make sure that as a user that does not have the `access_all_profiles` permission you can never see the violations that is associated to a site you do not belong to (this happens when …
=> [MRI Violations] Fixed bug in filter of the MRI violations module.

modules/dashboard/test/TestPlan.md, modules/user_accounts/README.md, modules/user_accounts/test/TestPlan.md
Update of the user account module's `README.md` and test plan to cover widget registration on the dashboard page.
N/A
* Resolves #6443
=> [User account] Update of the README file and test plan.

modules/imaging_uploader/jsx/UploadForm.js
This PR fixes the errors shown in https://github.com/aces/Loris/issues/6314. It also takes into account a 413 error, which should render the same swal error as 'mriFile' 400 error.
1. Go to 'Imaging Uploader' module
2. Click on 'Upload' tab
3. Fill in the form: 'Phantom Scans': Yes/No
4. Upload a file into 'File to Upload' field that is larger than the number stated in the 'Notes' field 'File cannot exceed ...'
5. Click 'Submit'
6. Swal will pop up with "Please make sure files are not larger than .."
7. See console log, which should only have the error `Failed to load resource: the server responded with a status of 400 (Bad Request)`
8. If you can, try to trigger a 413 (Request Entity Too Large) error. The swal should remain the same as above.
* Resolves …
=> [Imaging_uploader] Clear front-end console error logs

CHANGELOG.md, htdocs/js/jquery.dynamictable.js, modules/data_release/ajax/FileUpload.php, modules/data_release/jsx/uploadFileForm.js
This PR Prevents the duplication of file_names in the data_release table. If there is an attempt to submit a filename that already exists in the table, the user is given the option of overwriting the previous entry.
Part 1
1. Upload a file to data_release.
2. Upload file with same name but different content.
3. Make sure a swal appears asking whether you want overwrite the file.
4. Overwrite file and make sure of it by downloading the new resource.
Part 2
1. Upload file as user who is not super user.
2. Remove permission to that file for that user.
3. Have that user try to overwrite the file.
4. Receive "Forbidden" error message.
5. Repeat steps 1-4 with super user. They should be able to overwrite the file even if they don't have permission for it.
* Resolves #6435
=> [data_release] Preventing Duplication of File Names

modules/login/php/requestaccount.class.inc
The placeholder is at the wrong place, which became an issue after PR #6396. There might be other cases.
1. check request account page to see whether the request account form has placeholder.
* Resolves #6430
=> [Request Account] fix placeholder message issue

modules/conflict_resolver/php/conflict_resolver.class.inc, modules/conflict_resolver/php/resolved_conflicts.class.inc, modules/genomic_browser/php/cnv_browser.class.inc, modules/genomic_browser/php/cpg_browser.class.inc, modules/genomic_browser/php/genomic_browser.class.inc, modules/genomic_browser/php/snp_browser.class.inc, modules/help_editor/php/edit_help_content.class.inc, modules/login/php/passwordreset.class.inc, modules/mri_violations/php/mri_protocol_check_violations.class.inc, modules/my_preferences/php/my_preferences.class.inc, modules/user_accounts/php/edit_user.class.inc, php/libraries/NDB_BVL_Instrument.class.inc
Fix parameter position problem after the merge of the PR #6396. This is in addition to those processed in the PR #6431.
There are some trailing white spaces removed because of editor settings, which I did not notice early, but no much impact so I didn't redo the modification.
=> [Forms] fix parameter position problems because of PR #6396

modules/dashboard/test/TestPlan.md, modules/statistics/README.md, modules/statistics/test/TestPlan.md
Update of `README.md` and `TestPlan.md` for the `statistics` module: addition of documentation and test cases related to the registration of widgets on the `dashboard` module.
N/A
* Resolves #6441
=> [Statistics] Update of README.md and test plan.

modules/candidate_parameters/README.md, modules/candidate_parameters/test/TestPlan.md
Update the test plan to include the widgets registered in other modules.
Fixes #6433
=> [candidate_parameters] Update test plan and README to include widgets

modules/electrophysiology_browser/jsx/electrophysiologyBrowserIndex.js
**Changes:**
`Vist`  --> `Visit` in EEGBrowser, under the `Selection Filter` 
**Testing instructions**
1. Navigate to the EEGBrowser
2. Observe `Visit` label spelled correctly under the selection filter.
* Resolves #6493
=> [ElectrophysiologyBrowser] Fix typo in label

modules/issue_tracker/php/issue.class.inc
This PR fixes an issue which allowed users to view issues to which they didn't have the proper center.
1. Go to issue_tracker module. 
2. Go to an issue url which exists but to which the user doesn't have access based center.
3. Ensure that permission to view is denied.
#6282
=> [issue_tracker] Prevent users from accessing issues to which they don't have the appropriate Center

jsx/Filter.js, modules/issue_tracker/jsx/IssueForm.js, modules/issue_tracker/jsx/issueTrackerIndex.js
This PR overrides the default alphabetical sorting of SelectElements for the list of priorities in the issue tracker module.
NOTE: This PR did make me think that maybe the index files for each module should really be passing components for the filter fields rather than a series of parameters from a JSON object. 
1. Go to Issue Tracker module
2. Make sure list of priorities in the menu filter and on the new Issue page are ordered: 
normal, high, urgent, immediate.
* Replaces #6376
* Resolves #6328
=> [issue_tracker] Fix Priority Ordering.

modules/imaging_browser/jsx/imagingBrowserIndex.js
Fixed typo `Vist Label` to `Visit Label` in ImagingBrowser under `Selection Filter`.
1. Go to Imaging/Imaging Browser.
2. Observe `Visit Label` is spelled correctly under the selection filter and in the column names of the table below.
* Resolves #6507
* Related to #6493
=> [ImagingBrowser] Fixed typo in Visit Label under Selection Filter

php/libraries/Utility.class.inc
*Summary*
I changed how `$query` is concatenated in `getSiteList` by taking the WHERE clause out of the if statement and adding a possible AND operator only if `$study_site` and `$DCC` are both set to true.
*Testing*
1. calling the `getSiteList` function should not return any error messages 
* Resolves #6489
=> [Utilities] Fix SQL query inside getSiteList function

docs/API/LorisRESTAPI_v0.0.3.md, modules/api/php/provisioners/projectimagesrowprovisioner.class.inc, php/libraries/Project.class.inc
This PR replace #6401.
This PR removes `File` from being returned for project images. It also ensure that Project data is returned when querying visit information.
1. Run `GET /projects/$ProjectName/images/` and ensure `File` key is not returned
2. Run `GET /candidates/$CandID/$VisitLabel` and ensure `Project` key returns project data.
* Resolves #6321 (points 1 and 2)
=> [API] Adjust return values of API

modules/issue_tracker/php/issue_tracker.class.inc, modules/issue_tracker/php/issuerow.class.inc, modules/issue_tracker/php/issuerowprovisioner.class.inc, modules/issue_tracker/php/issuewatchermapper.class.inc
This PR handles values of NULL in the centerID column of the `issues` table by converting `NULL` values to an array of all centerIDs in the `psc` table in the `issuerowprovisioner` class.
1. Create an issue with no CenterID, or set centerID to null for an issue already in the `issues` database table.
2. Login as user who does not have access to all centers.
3. Make sure the Issue Tracker Module is working for that user.
* Resolves #6470
=> [issue_tracker] Handle a CenterID of NULL in issues table.

raisinbread/README.md
The Raisinbread README was updated to include specific instructions for dropping all tables pre-installation. A note about foreign key constraints and sourcing the schema files directly on the MySQL command line was also added. 
* Resolves #6495
=> [Raisinbread] Instructions and clarifications added to RaisinBread README

CHANGELOG.md
I added a note in Changelog under the Notes for Existing Projects section for the new  php7.3-curl dev install dependencies. I also fixed a redundancy in the file.
* Resolves #6509
=> [Changelog] Add note re php-curl dependency now required for dev install

modules/conflict_resolver/README.md, modules/conflict_resolver/test/TestPlan.md
Update conflict resolver to include tests for the widgets it includes in different modules.
Fixes #6434.
=> [conflict_resolver] Update test plan and README to test widgets

modules/imaging_uploader/jsx/UploadForm.js
This PR changes the swal displayed for MRI file uploads done when the network is down: the swal now displays an error message saying that the upload failed because of a network error. This PR also changes the swal displayed when HTTP codes other than 400 and 413 are received when the upload request is sent: the swal now displays the HTTP code received (the swal was empty before...)
Access the imaging uploader and fill out the upload form with valid data. Shutdown your server (`% sudo service apache2 stop`). Click on `Submit`: you should see the swal mentioned above.
* Resolves #6468
=> [Imaging Uploader] Corrected swal displayed for file uploads done when the network is down.

modules/genomic_browser/jsx/profileColumnFormatter.js
**Summary**
The link for a candidate's SNP (as well as the CNV, CPG) from the Genomic browser's profile tab doesn't have any visual indication that it can be clicked on. I changed the tag from `<span>` to `<a>` around the cell entry to properly format it as a hyperlink. 
**Testing instructions**
Navigate to the genomic browser, observe the SNP, CNV and CPG columns (CNV and CPG columns do not have data for their links to be tested as per #6302) . Cells with a 'Y' should be colored blue and change color on hover with an underline:
**Link(s) to related issue(s)**
* Related to #6302 but only addresses point B.
=> [Genomic Browser] Make SNP,CNV,CPG 'Y' links obvious

php/libraries/LorisForm.class.inc
This fix the warning mentioned in the PR #6520
Warning: strlen() expects parameter 1 to be string, array given in /Users/cmadjar/Github/Loris/php/libraries/LorisForm.class.inc on line 2069
1. Check to see whether the warning exists or not with a group element, for example, with the PR #6520.
PR #6520
=> [23.0 release LorisForm] fix PHP warning for string vs array

php/libraries/LorisForm.class.inc
The PR #6395 is radical, so the existing instruments might have table title text display problem, this PR will keep the old format and the new correct format available at the same time
1. Test instrument with table to check whether table title is displayed correctly.
For example: medical_history from raisonbread, check PR #6444
PR #6395, PR #6451
=> [LorisForm] keep old group mode text parameter mode

modules/dashboard/php/taskquerywidget.class.inc, modules/dashboard/php/taskwidget.class.inc, modules/dashboard/test/DashboardTest.php, modules/mri_violations/php/module.class.inc, modules/mri_violations/test/mri_violationsTest.php, test/integrationtests/LorisIntegrationTest.class.inc
- The widget displayed on the `dashboard/My Task` panel for violated scans now specifies whether all known sites or only the user's sites were taken into account when computing the number of violations.
- Deletion from the dashboard module of the tests associated to the violated scans widget in the `My Task` panel.
- Addition of tests in the MRI violations module for the registration of the violated scans widget in the dashboard module.
Make sure that when the dashboard is displayed, there will be either label `Site: All` or `Site: All User Sites` besides the number of violated scans depending on whether the user has the `violated_scans_view_allsites` or `violated_scans_view_ownsite` permission respectively
None
=> [MRI Violations] Fixing a bug in dashboard widget registration and adding some tests

modules/issue_tracker/php/issue_tracker.class.inc
I updated the issue_tracker class to avoid Object object to be populated in the Module dropdown.
I used getLongName() to retrieve the name of the module and populate the json.
* Resolves #6519
=> [issue_tracker] Module filter has entry [object Object]

php/libraries/LorisForm.class.inc, tools/single_use/instrument_double_escape_report.php
This PR fixes the issue where special characters entered in instrument forms were double escaped on saving but improperly decoded on instrument loading causing each save to prepend an `&amp;` escaping string to the already escaped characters. the problematic chars are `&`, `<`, `>` and `"`.
The escaping is done in the deleted lines as well as the insert and update functions of the database class making this first instance unnecessary.
A script has also been added to help projects identify if the bug has affected their data. Amending the data in the database will remain the responsibility of each project since it is highly specific to each project.
=> Fix data in fields where HTML characters were double escaped on 22

Dockerfile.test.db, docker-compose.yml, test/integrationtests/LorisIntegrationTest.class.inc
Changed the way that integration tests set up their baseURL value. 
1. Check out Travis or run `npm run tests:integration` if you have a test environment set up.
* Resolves #6562 
* Related to #6019
=> [Core] Changed call to baseURL for integration tests

modules/candidate_profile/test/TestPlan.md
The `CandID `suggested for testing the Widget permissions doesn't longer exist in the current version  of the database. Replaced for a new ones.
The new suggested `CandID ` should be available and matching required conditions for testing the Widget.
=> [Candidate Profile /  Test Plan] replaced candID for testing Widget.

modules/login/php/passwordexpiry.class.inc
In login/password-expiry/, I added a validation to display an error if the 2 passwords do not match.
This validation may have been removed [here](https://github.com/aces/Loris/commit/9c8a24bb395444a118c06b579cc4e44aeeceeb1d#diff-1dc7c9358a505a311690636f4e1bf51cL124)
**To test**
In the users table in the database, update the Password_expiry cell for a user you are testing to be a date in the past.
Login as that user. You should see an update password page.
* Related to #5417
* Resolves #6606
=> [Login] Password reset password mismatch

modules/media/ajax/FileDownload.php
This PR is related to issue #6136. This PR aims to fix a bug that was experienced by a CCNA user when trying to download a file that had a '&' in the name. SQL encodes strings containing special chars and thus we need to use the decoded file names in the path when downloading files from media module. 
Issuing this fix to the 21.0-release branch as it is affecting our users and current instance on CCNA. 
1. Upload a file to media module that contains special chars (&, >, <, etc)
2. Try downloading the file and ensure that you do not receive an error. 
* Resolves #6136
=> [media] File download should retrieve decoded path

modules/issue_tracker/test/issue_tracker_test_plan.md
Update the test plan to include instructions for the Issue Tracker Dashboard widget and the Issue Tracker Candidate Dashboard widget.
1. View the new test plan instructions.
2. follow the instructions.
#6438
=> [issue_tracker] Widgets not described in test plan

modules/issue_tracker/php/issue_tracker.class.inc
Adds Low in the priority filter, to let users filter Low priority issues.
Duplicate of PR #6263 (Created for master)
* Resolves #6262 
* Resolves #6608
=> [Issue Tracker] Fix Low priority filter missing

raisinbread/README.md
Instructions on using the `/tools/raisinbread_refresh.php` script to source RB data added to the RaisinBread README for the 23.0-release. 
* Resolves #6528
* Related to #6498, #6495
=> [Documentation] RB refresh script instructions added to RB Readme

modules/user_accounts/php/user_accounts.class.inc
I fixed a typo in /php/libraries/UserPermissions.class.inc:126. The permission user_accounts_multisite
is mispelled.
* Resolves #6655
=> [User Accounts] Typo in permission name

modules/survey_accounts/php/addsurvey.class.inc, modules/survey_accounts/test/survey_accountsTest.php
If a user attempts to create a survey for a candidate on a project they are not involved in, an error message will appear and the survey will not be created.
1. Create a user account who isn't affiliated with at least one project and with "User Management" permissions
2. Log-in as this user and go to the survey accounts page.
3. Try to add a survey using a candidate who is on a project that the user is not on. An error message should appear.
4. Check that the survey was not added to the list. 
* Resolves #6582
=> [survey_accounts] Error message when survey added on different project

modules/imaging_browser/php/imagingbrowserrowprovisioner.class.inc
This fixes projects that only inserts NIfTI files and not MINC files into the database. The query in the imagingbrowserrowprovisioner.class.inc file was limiting the query to `filettype='mnc'` only while we should also allow for `filetype='nii'`.
1. Ensure the imaging browser filter menu still loads.
no issues reported but a user of LORIS loading only BIDS dataset (aka NIfTI file types) could not see anything on the imaging browser menu filter page as there are no MINC files in their database, only NIfTI files.
=> add nii file type to the list of file types to show in the query

modules/user_accounts/php/edit_user.class.inc, modules/user_accounts/php/user_accounts.class.inc
We've had this a few times before; a multisite permission was added to the module at some point but if a user has ONLY this permission (and not the site-specific permission), they cannot access the module.
In addition, the User Accounts module was not displayed in the LorisMenu dropdown.
1. Modify a user's permission so that it has `user_accounts_multisite` but not `user_accounts`.
2. Confirm User Accounts does not show up in the Admin dropdown.
2. Try to go to the User Accounts module via URL. You can't!
3. Checkout my branch. You should be able to access the module via the dropdown.
* Resolves #5951 
* Resolves #6657
=> [User Accounts] Fix issue where users with multisite permission could not access the module

modules/imaging_uploader/jsx/UploadForm.js
For compound visit labels that contain underscores (EX: `Initial_MRI`), the auto-fill feature was not populating the full visit name due to how the file name was being spliced. This PR addresses that issue and ensures that full visit label is populated.
1. Try attaching a file with visit label containing an underscore. (EX: `Initial_MRI`)
2. Try attaching a file with visit label that does not contain underscores. (EX: `V1`)
3. Repeat steps 1 & 2 for both cases where Phantom Scan = `yes` & `no`
* Resolves #6569
=> [imaging_uploader] Fix bug with auto-filling compound visit labels

modules/dataquery/jsx/react.tabs.js
Solves the "Cannot read property '0' of null" type error.
2. Navigate to DQT.
3. Define Fields: aosi | Candidate_Age
4. Define Filters: aosi | Candidate_Age = 33 All Visits
5. View Data > Run Query
6. Switch to Longitudinal
7. Table should be visible.
https://github.com/aces/Loris/issues/6595
=> [DQT] Fixes error on View Data > Longitudinal view

modules/candidate_parameters/ajax/getData.php, modules/candidate_parameters/php/candidate_parameters.class.inc
This PR changes the access to the candidate_parameters module so that anyone with `access_all_profiles` permission can view the module (even without `candidate_parameter_view` or `candidate_parameter_edit` permissions). It also ensures that users with either `candidate_parameter_view` or `candidate_parameter_edit`, but without `access_all_profiles` can only access the module for candidates belonging to the same site(s) as themselves. 
1. Make user with only one site
2. From admin account, get link for candidate parameters of a candidate from a **different** site than the user's.
3. Navigate to this link from the user's account with the permission `access_all_profiles`. Make sure that you can access the page with this permission, with or without the `candidate_parameter_view` and …
=> [candidate_parameters] Fix access to module

modules/imaging_browser/php/viewsession.class.inc
If a user tries to access an individual session (by changing the sessionID in the URL), they are no longer able to access sessions for projects they are not affiliated with. 
1. Grant a user "view all sites Imaging browser browser pages" permission
2. Navigate to the imaging browser front page
3. Click on one of the hyperlinks under the "Links" column
4. Modify the `sessionID` number in the URL to a session belonging to a project the user is not affiliated with.
5. The "You do not have access to this page." message should appear. 
* Resolves #6618
=> [imaging_browser] ViewSession subpage: Add Project Permission checks

htdocs/survey.php, php/libraries/NDB_Caller.class.inc
A header location in survey is set with a variable which can be null. This has an unpredictable behaviour, and in Firefox, it seems to cause the reload of the page, where again, the header location is interpreted, causing an infinite redirection. I solved this with a check for Null before redirecting.
I also fixed some type issues (+1 on pageNum = finalpage).
* Resolves #6587
=> [Survey] Infinite redirect

modules/imaging_uploader/jsx/UploadForm.js
I noticed some problems in the phrasing of some error messages based on @jesscall's [comment](https://github.com/aces/Loris/issues/6620#issuecomment-638261560) in another issue.
This removes a debug message and also fixes grammer.
=> [Imaging Uploader] Fix grammar of alert messages

jsx/StaticDataTable.js, modules/genomic_browser/jsx/profileColumnFormatter.js, modules/genomic_browser/php/genomic_browser.class.inc, modules/genomic_browser/php/snp_browser.class.inc
In Genomic Browser > Profile and SNP screens, I added a parsing logic on the csv colums to allow special treatment of data (inspired by what is already implemented on the data table with [profileColumnFormatters](https://github.com/aces/Loris/blob/23.0-release/modules/genomic_browser/jsx/profileColumnFormatter.js)) and applied a Formatter on SNP > Subproject int he data table.
[Testing card](https://github.com/aces/Loris/projects/19#card-21296727)
* Resolves #6295
=> [Genomic Browser] Subproject Column label

modules/document_repository/jsx/docIndex.js, modules/document_repository/php/module.class.inc, modules/document_repository/php/uploadcategory.class.inc
- Changed the permission in module.class.inc to be able to access the module when you have only the permission to delete files
- When you only have permission to delete files, the tabs upload and category disappear (However, I was unable to forbid the user uploading a file or a category when they only have delete permission... Hiding the tabs should resolve it however I am not completely sure of it).
1. Check that if you only have delete permission, you can view the module.
2. Check that if you only have delete permission, you cannot access the upload and category tabs.
* Resolves #6373
=> [document_repository] Permission to access module

modules/api/php/models/projectimagesrow.class.inc, modules/api/php/provisioners/projectimagesrowprovisioner.class.inc
Fixing 500 error. 
remove "file" column from projectimagesrow, since #6516.
"PHP Fatal error: Uncaught TypeError: basename() expects parameter 1 to be string, null given in /var/www/Loris/modules/api/php/models/projectimagesrow.class.inc:79"
Test  "/api/v0.0.3/projects/Rye/images" on a loris instence with Rasinbread data set .
It will show the result.
https://github.com/aces/Loris/issues/6572
=> [API] Project /images endpoint broken  

modules/imaging_browser/php/imagingbrowserrowprovisioner.class.inc
Adding 't1-defaced' or 't2-defaced' scan types to the imaging browser was causing an SQL error due to the hyphen in the name.
- ~I replaced all hyphen occurrences in the array containing the scan type names with underscores. This does not change how the scan type name appears on the frontend.~ 
- I used Database->quote() to quote scan type names, or surrounded them with backticks if they needed to be interpreted as identifiers rather than string literals.
1. Go to Admin>Configuration>Imaging types>
2. Add t1-defaced and/or t2-defaced scan types next to the tabulated scan types and save
3. Go to the imaging module front page
4. Observe the module loading properly, with t1-defaced/t2-defaced QC columns
* Resolves #6616
=> [Imaging browser] Fix loading error for t1-defaced and t2-defaced scan types

modules/instrument_builder/jsx/react.questions.js
This PR allows the Start year and End year values for Date elements be emptied
1. On branch 23.0-release, add a Date element and notice that once you enter a value for both Start year and End year, you are not able to make the fields empty
2. Save the instrument with one Date element without min/max values, and another Date element with min/max values.
3. On this PR's branch, add a Date element and notice that you can make it empty after inserting a value. Make sure you run `make dev` after changing branches.
4. Save the instrument with the same elements as step 2.
5. Compare the two saved linst files and see that they are identical. This PR should only affect the front-end instrument builder. Please report if otherwise.
* Resolves https://github.com/aces/Loris/issues/6567
=> [instrument_builder] Let mindate and maxdate options be removable

modules/timepoint_list/test/TestPlan.md
The timepoint_list test plan refers to links to imaging browser but uses very similar terminology to refer to linking to different places. This specifies where the links should go more precisely to avoid confusion.
=> [timepoint_list] Clarify ambiguous parts of test plan for timepoint_list

modules/user_accounts/test/TestPlan.md
Minor changes to the test plan:
* The pwned password: a1b2c3!! triggers an error of type: The password is not complex enough.
It was changed for AKAX89Wn.
* The Display additional information option label is not accurate.
Resolves #6701
=> [User Accounts] Test plan minor changes

modules/statistics/php/stats_demographic.class.inc
Previous version of [Statistics] Demographics was producing 1500 lines of logs per display because of undefined array values. This was fixed by recursively checking if the array value is set before incrementing it.
* Resolves #6716
=> [Statistics] Set default values to avoid logs cluttering

modules/module_manager/jsx/modulemanager.js
Allows the enabling/disabling modules directly from the frontend to allow an option of refreshing the page and specifically when the swal is shown for the user confirming the changes.
1. Visit the module_manager
2. Change the active of a module
3. Test the refresh option or the continue option.
#6698
=> [module_manager] refresh menu bar after enabling/disabling modules

modules/user_accounts/php/module.class.inc, modules/user_accounts/test/TestPlan.md
In Dashboard > My Tasks 
~~I updated the query executed for displaying the users with Site set to the current user's site and Pending Approval set to 'Yes'. Previously, the query was targeting users from all sites except Data Coordinating Center and Pending Approval set to 'Yes'.~~
I updated the test plan to indicate that pending users can belong to any sites except Data Coordinating Center.
Resolves #6577
=> [Dashboard] User approval test plan

modules/my_preferences/php/my_preferences.class.inc, modules/user_accounts/php/edit_user.class.inc
The PR adds a password validation rule for username.
Side note, I wonder if the use of COALESCE [here](https://github.com/aces/Loris/pull/6705/files#diff-324943431518887444da99607e70a4e4R1111) is necessary?
* Resolves #6699
* Related to #6615
=> [User accounts] Add password validation rule for user name

modules/document_repository/README.md, modules/document_repository/test/TestPlan.md
Tentative to update the documentation of the document_repo module:
- update of the README
- update of the Test Plan to mention the Document Repository Notifications widget.
* Resolves #6631
=> [Documentation] Doc Repo Test plan and README update

modules/bvl_feedback/README.md, modules/bvl_feedback/test/TestPlan.md
Tentative to update the documentation of the bvl_feedback module:
- creation of a basic README
- update of the Test Plan to mention the Behavioral Feedback Notifications widget.
* Resolves #6630
=> [Documentation] Behaviour Feedback widgets description

htdocs/js/helpHandler.js, htdocs/main.css
Small script to close the help dialog on scroll and avoid the previous floating behaviour.
* Resolves #6686
=> [Help] Close dialog on scroll

README.md
The main LORIS README.md now points to the new install markdowns for the 23 release. The README also points to the ReadTheDocs URL. 
* Resolves #6709
=> [Documentation] Updating main README with new install markdowns

README.md, docs/wiki/00_SERVER_INSTALL_AND_CONFIGURATION/01_LORIS_Install/CentOS/README.md, docs/wiki/00_SERVER_INSTALL_AND_CONFIGURATION/01_LORIS_Install/Ubuntu/README.md, tools/install.sh
Overall, the CentOS install works relatively well, except for some problems with permissions:
* sudo is required in the install.sh tool L118
Some typos were also found in the install README (loris/docs/config/apache-site instead of loris/docs/config/apache2-site), and steps added. 
Also updated the references of php7.3 to php7.4 across the documentation (Ubuntu/CentOS).
* Resolves #6703
* Resolves #6722
* Related to #4824
=> [Install] Guideline and PHP version update

modules/login/php/passwordexpiry.class.inc, modules/login/test/Reset_Password_Test_Plan.md
In login/password-expiry/, I added a validation to display an error if the new password is set for the user's email, as otherwise, an exception is thrown from in User.class::updatePassword.
I also updated the test plan to add this test case and and password too short.
**To test**
In the users table in the database, update the Password_expiry cell for a user you are testing to be a date in the past.
Login as that user. You should see an update password page.
* Resolves #6607
=> [Login] Pwd Expiry - Validation for user's email, name and test plan update

modules/examiner/php/editexaminer.class.inc
- Light modification of the function that handles the validation `function _validateEditExaminer($values)`. Cleaning an unused if condition.
- Light modification of the function that handles the process of the form `function _process($values)`
- Reestablishing old code accidentally replaced by https://github.com/aces/Loris/commit/058fa91d174e66f3e847f82a1bb7dc8408c3b112#diff-e429062f89aabd1a9ed7a99166cf2e85R195
- Properly function of buttons “Save” and “Reset”
1. Go to Clinical/Examiner.
2. Add a new Examiner.
3. Click on the new examiner's name to edit the new examiner.
4. Play around with the buttons "Save" and "Reset". The behaviour should be the intended one. The page should refresh after each action.
5. No error 500  should be shown when leaving one of the instruments as …
=> [Examiner / Edit Examiner] fix various issues when establishing the Certification Status of the Examiner

modules/api/test/TestPlan.md
In the API TestPlan, the example of a POST request to create a new candidate does not create a candidate. The new command line example creates a new candidate successfully. 
Follow all the instructions in the API's _TestPlan.md_
* Resolves #6590
=> [API] Valid POST request of a candidate added to the API TestPlan

htdocs/css/simple-sidebar.css
The left side bar occupies unnecessarily takes too much space for the most cases, especially when some instruments has big table which will needs more space, even 10 pixels count. In fact, even 250px will not show all the item titles for some instruments.
It is better that the bar is extensible, but for now a fixed value is fine for me.
1. Check left side bar of the instrument under candidate profile, make sure that most items should be visible.
=> [left bar navigation] shrink left bar width size

jsx/DataTable.js
When a getFormattedCell callback is not defined, the DataTable component
currently silently throws away all the cells in the table. Since it's not
a required prop, this is confusing.
This provides a default cell format when no cell formatter is defined.
=> [Data Table] Provide default table cell when getFormattedCell is not defined

modules/user_accounts/php/edit_user.class.inc
Small change to error message. Saying that the email 'already exists' is a little weird to me. Saying that it's 'in use' is more clear.
=> [User Accounts] Improve email error message

modules/instrument_manager/php/instrument_manager.class.inc, src/LorisInstance.php, src/Router/BaseRouter.php
Adds NDB_Config as a property of LorisInstance. See #6118 and #6022 for more details about Loris Instance.
Modifies instrument manager to show an example of its usage. Also cleans up this class.
1. Follow the `instrument_manager` Test Plan.
=> [Loris Instance] Add NDB_Config property

Makefile
This PR enhances the "make clean" target to also remove installed JS libraries and the package-lock.json file from the development environment. It previously only deleted PHP libraries and compiled smarty templates.
1. Run `make clean` and make sure it deletes `node_modules/` and `package-lock.json`.
=> Remove JS as part of "make clean"

.phan/config.php, modules/candidate_parameters/ajax/formHandler.php, modules/genomic_browser/ajax/genomic_file_upload.php, src/Data/ProvisionerInstance.php, test/unittests/Database_Test.php
This enables Phan's ability to detect unused variables and dead code. As with default phan rules, some new rules have been suppressed and we will gradually enable these.
The following Phan rules are now checked and existing violations have been fixed:
* PhanUnusedProtectedMethodParameter
* PhanUnusedGlobalFunctionParameter
* PhanUnusedClosureParameter
=> [Phan] Enable dead code detection and solve some occurrences

modules/candidate_parameters/ajax/formHandler.php
Removed unused `$user` parameter causing new phan rule to fail on master.
Also removing passing of an extra parameter to the functions in this class
=> [candiodate_parameters] removing unused parameter causing phan fail

jsx/Form.js, modules/module_manager/jsx/modulemanager.js
Resolves the unnecessary padding to SelectElement components used inside the DynamicTable component.
1. Visit the module_manager module.
2. Observe the fix for the UI carousel scrollers.
#6697
=> [module_manager] remove extra padding on selectelement for dynamictable

modules/candidate_list/test/TestPlan.md
Test plan update: 
PSCID links should be clickable in the search result table without the access_all_profiles permission.
* Resolves #6694
=> [Candidate List] Test plan update

CHANGELOG.md, modules/issue_tracker/css/issue_tracker.css, modules/issue_tracker/jsx/CommentList.js
The comments and history were jumbled together in a way that made
it very difficult to determine what was a comment and what was an
item being changed. This updates the display in a way that is
much more readable and should make it possible to follow the conversation
of what is happening in an issue.
Before:
After:
=> [issue_tracker] Improve readability of comments and history

docs/wiki/99 - Developers/UnitTestGuide.md, htdocs/index.php, php/libraries/DataFrameworkMenu.class.inc
…
by
* Resolves #5015 (Core files only)
This is my first contribution, don't hesitate to comment on the possible improvement.
=> [Core] Update User::singleton() declarations to facilitate unit testing (#5015)

SQL/Release_patches/22.0_To_23.0_upgrade.sql
The modules table must be created before the battery_manager
attempts to insert into the module.
Resolves #6726
=> Fix order of SQL in release upgrade patch

modules/my_preferences/php/my_preferences.class.inc, modules/user_accounts/ajax/rejectUser.php, modules/user_accounts/php/edit_user.class.inc
=> [User Accounts] Update User::singleton() declarations to facilitate unit testing

tools/exporters/data_dictionary_builder.php, tools/generate_tables_sql.php, tools/generate_tables_sql_and_testNames.php
Fix warnings when running `make checkstatic`:
```
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in tools/generate_tables_sql.php on line 74
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in tools/generate_tables_sql.php on line 80
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in tools/exporters/data_dictionary_builder.php on line 169
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in tools/exporters/data_dictionary_builder.php on line 178
PHP Warning:  "continue" targeting switch is equivalent to "break". Did you mean to use "continue 2"? in …
```
=> [Core] Fix warnings about continue in a switch being equivalent to a break

README.md
For whatever reason I was reminiscing about the NIH MRI study of normal brain development this morning, and wondering what happened to that software project I contributed to in 2004. It was wonderful to see the great progress that has been made! I also see you recently corrected one of my stranger contributions of "There can only be one" #6416.
Anyway, I don't know if there is a logic to the order or inclusion of past contributor names, but I put myself before-last, as I find going last carries an extra "oomph" that Samir deserves :)
=> Add name of pre-GitHub contributor

raisinbread/README.md, tools/raisinbread_refresh.php
When writing this tool, I neglected to automate the part of the instructions where you have to copy the instrument files from `raisinbread/instruments/` to `project/instruments/`. Without this step, accessing instruments via the LORIS front-end will fail and throw a NotFound exception.
This PR automates that step into the raisinbread refresh process.
1. On a test VM, delete all LINST and .class.inc files in your `project/instruments/` folder.
2. Run `make testdata`
3. Check that the files from `raisinbread/instruments/` have been copied to `project/instruments/`
=> [Tools] Fix bug where Raisinbread refresh did not install instruments

modules/candidate_list/php/candidate_list.class.inc, modules/candidate_list/php/candidatelistrowprovisioner.class.inc
=> [Candidate List] Update User::singleton() declarations to facilitate unit testing

php/libraries/NDB_Page.class.inc
Since the type is currently only enforced by PHPDocs and not
PHP, incorrect types can be passed by addSelect. This enforces
the types from the PHP side of things.
(Currently when a string is passed instead of an array in some
instruments, the array_merge call generates a PHP warning which
breaks endpoints which use the instrument in a JSON context. This
change makes the invalid instruments die with a type error instead,
forcing them to be fixed.)
=> [Core] Require correct types for lorisform->addSelect

modules/statistics/php/statistics_site.class.inc
=> [Statistics] Update User::singleton() declarations to facilitate unit testing

modules/new_profile/php/new_profile.class.inc
Complementary effort to #5758 -- dates are now validated on the back-end as well as the front-end.
Also cleans up some of the related code.
1. Create a new candidate in `new_profile`. Try setting the date of birth to a date greater than today's date. You should get an error.
=> [New Profile] Add back-end validation for dates; cleanup

composer.json, composer.lock, php/libraries/Database.class.inc, test/StrictTypesCS.xml, test/run-php-linter.sh
Previous attempts to [force type hints](#5396 ) or [strict typing](#5923) en masse have failed because it's just too darn complicated to do it all at once.
This introduces a new Strict Type coding standard that we can selectively apply to files by adding to an array in `test/run-php-linter.sh`. Hopefully this will provide an approach to using stricter typing that is easier to author and review.
Using `vendor/bin/phpcbf --standard=test/StrictTypesCS.xml $file` will now allow PHPCBF to automatically provide 
* return types
* param types 
* strict_types =1 
based on PHPDocs. 
It will also throw errors if Traversable types do not have specific type annotations.
The Database.class.inc file has been modified as an example of the changes 
Resolves #5342
=> Add strict type coding standard

.travis.yml, Makefile, package.json, test/dockerized-integration-tests.sh
This PR uses caching + parallelization to reduce Travis testing time:
Travis will now also show an error status on GitHub as soon as any one of the jobs fails. However, other builds will still complete.
=> Travis parallelization (performance boost)

.phan/config.php, modules/api/php/endpoints/candidate/candidate.class.inc, modules/api/php/endpoints/candidate/visit/dicom/dicom.class.inc, modules/api/php/endpoints/candidate/visit/electrophysiology/bidsfile/archive.class.inc, modules/api/php/endpoints/candidate/visit/electrophysiology/bidsfile/channels.class.inc, modules/api/php/endpoints/candidate/visit/electrophysiology/bidsfile/electrodes.class.inc, modules/api/php/endpoints/candidate/visit/electrophysiology/bidsfile/events.class.inc, modules/api/php/endpoints/candidate/visit/image/format/brainbrowser.class.inc, modules/api/php/endpoints/candidate/visit/image/format/raw.class.inc, modules/api/php/endpoints/candidate/visit/image/format/thumbnail.class.inc, modules/api/php/endpoints/candidate/visit/image/qc.class.inc, modules/api/php/endpoints/candidate/visit/instrument/flags.class.inc, modules/api/php/endpoints/candidate/visit/instrument/instrument.class.inc, modules/api/php/endpoints/candidate/visit/instruments.class.inc, modules/api/php/endpoints/candidate/visit/qc.class.inc, modules/api/php/endpoints/candidate/visit/visit.class.inc, modules/api/php/endpoints/project/candidates.class.inc, modules/api/php/endpoints/project/instrument/instrument.class.inc, modules/api/php/endpoints/project/project.class.inc, modules/api/php/endpoints/project/visits.class.inc, modules/api/php/endpoints/projects.class.inc, modules/genomic_browser/php/view_genomic_file.class.inc, modules/issue_tracker/test/Issue_TrackerTest.php, modules/server_processes_manager/php/serverprocesslauncher.class.inc, php/libraries/User.class.inc
Adds a rule to check when a function has a parameter in its signature that is never used.
* #6027 must be merged first. This PR removes an exception introduced by that PR.
=> Add phan rule PhanUnusedPrivateMethodParameter

test/unittests/CandidateTest.php
Unit tests for the Candidate library under `php/libraries`. This PR completes the test coverage for the Candidate class, excluding the `'createNew` method. 
Run` npm run tests:unit -- --filter Candidate` or check out the Travis output.
=> [Test] unittests for Candidate.class.inc

test/unittests/Database_Test.php
Unit tests for the Database library under `php/libraries`. This PR will be updated as more unit test coverage is added. Comments were added to pre-existing and new unit tests.
setUp and tearDown functions were added as well.
As of 06/16: All **public** methods are covered except for `connect` and `singleton`. 
1. Run `npm run tests:unit -- --filter Database` or check out the Travis output.
=> [Test] unittests for Database.class.inc

src/LorisInstance.php, src/Router/ModuleRouter.php, test/SrcCS.xml
Adds a PHPCS rule to forbid superfluous parameter comments from function docs in the `src/` directory.
=> Remove superfluous parameter comments in src/

tools/delete_timepoint.php, tools/lorisform_parser.php, tools/mri_violations_resolver.php, tools/recreate_conflicts.php
Changes to syntax in some scripts in the tools directory that are causing Travis to fail in the master branch. Array declarations changed from `array()` to `[]`.
* Resolves #6753 
* Related to #6745
=> Fix phpcs errors causing Travis fail

modules/my_preferences/php/my_preferences.class.inc, smarty/templates/email/account_details_changed.tpl
My Preferences was sending a user's password in plaintext to their email whenever they changed it.
Edit User does this when a user has a password generated for them by the server. In this case it is acceptable because the password must be reset on login. My Preferences shares a lot of code with User Accounts so I believe it was included as a feature accidentally.
I've created a new email template notifying a user that their account details have changed.
This PR also does a bit of cleanup within the function.
1. Change your account details via the My Preferences module. You should receive an email. That email should not display your password.
* Resolves #6079
=> [My Preferences] Change contents of email sent to user upon changing their account details

modules/candidate_profile/jsx/CandidateInfo.js
Additional fields can show up in the Candidate Info card in the Candidate Profile page, but those with long titles overlap and are not readable. Removing White-space:nowrap on the container solved the problem.
* Resolves #6679
=> [Candidate parameters] Titles cut off in Candidate Info

SQL/0000-00-03-ConfigTables.sql, SQL/New_patches/2020-02-25_Add-Admin-Contact-Email.sql, raisinbread/RB_files/RB_Config.sql, raisinbread/RB_files/RB_ConfigSettings.sql
Adds a new configuration setting for an admin "point of contact" email. The idea is to have an email that is monitored by a developer and/or project administrator for LORIS users to contact directly from within the software. 
An example of this would be when an Exception occurs in LORIS. The error page will provide a link for the user to email an admin when the error occurs. #6076 
Another example will be in the server configuration check script #5965. This script will send a test email to the admin to make sure that outgoing emails are working properly on the server.
=> Add administrator contact email as a new config setting

php/libraries/Utility.class.inc, test/unittests/CandidateTest.php, test/unittests/UtilityTest.php
Unit tests for the Utility class under `php/libraries`. This PR completes the unit test coverage for this class. 
**Note:** This class has 3 deprecated functions which are not covered.
**Note (added later):** The unit tests for `structureToPCRE` were moved to the Candidate library unit tests following the merging of #6173. The `getScanTypeList` was also edited to match the changes from that PR.
Run `npm run tests:unit -- --filter UtilityTest` or check out the Travis output.
=> [Test] unittests for Utility.class.inc

modules/document_repository/php/files.class.inc, php/libraries/FilesDownloadHandler.php
Adds a class to be used for generic file downloading throughout LORIS. This serves as the counterpart to the generic file uploader from #4181.
1. Download a file from the document repository.
This is a remake of #3881
=> [Core] Add new FilesDownloadHandler class

test/dockerized-integration-tests.sh
Fix a regression introduced in #5635 which prevents integration tests to be run with `npm run tests:integration`
* Resolves #6781
=> [Tests] Integration tests Fix

SQL/0000-00-00-schema.sql, SQL/New_patches/2019-12-17-RemovePasswordExpiry.sql, htdocs/postdeploy.php, modules/dashboard/test/DashboardTest.php, modules/login/php/passwordreset.class.inc, modules/login/test/Reset_Password_Test_Plan.md, modules/user_accounts/php/edit_user.class.inc, modules/user_accounts/test/user_accountsTest.php, php/installer/Installer.class.inc, php/libraries/SinglePointLogin.class.inc, php/libraries/User.class.inc, raisinbread/RB_files/RB_Config.sql, raisinbread/RB_files/RB_users.sql, test/integrationtests/LorisIntegrationTest.class.inc, test/unittests/UserTest.php, tools/single_use/remove_logged_passwords.php
This PR removes the Password_expiry date column and adds a PasswordExpired boolean column.
Passwords will no longer be required to reset after 6 months as this is not actually a security benefit (see discussion in linked issue) and because most projects were subverting this by setting passwords to have an infinite expiry time anyway.
Calling code and relevant tables are updated.
Follow the Test plan at modules/login/test/Reset_Password_Test_Plan.md
Resolves #4458
Resolves #4208
=> [Core] Remove 6 month password expiry

php/libraries/NDB_BVL_Instrument.class.inc
Remove `var` from variables in favour of more explicit scope keywords.
I tried to maintain the current operation of the class rather than try to 'correct' variables; there are some properties that should likely be protected instead of public but this should be done in later refactoring.
* Resolves #6178
=> [Instrument] Add explicit scope on class properties

modules/user_accounts/php/edit_user.class.inc
When adding a new LORIS user, page returns error "Your password cannot be your email" when both "Make user name match email address" and "Generate new password" are checked.
This PR adds another condition to check if NA_UserID is set, which fixes the issue.
* Resolves #6802
=> [User accounts] New user email with pwd generation fix

modules/issue_tracker/ajax/EditIssue.php, modules/issue_tracker/jsx/IssueForm.js, modules/issue_tracker/jsx/issueTrackerIndex.js, modules/issue_tracker/php/issue_tracker.class.inc, modules/issue_tracker/php/issuerowprovisioner.class.inc, modules/issue_tracker/test/issue_tracker_test_plan.md
Since we want to allow new issues with NULL centerID to be created, the following changes have been made:
- a new Site option All Sites allows a user to save an issue with a NULL site
- The Comment History section displays **site to All sites** if an issue is edited/modified with the All Sites option.
- Alternatively, in the Comment History section, All sites can be replaced with a comma separated list of all CenterID (to discuss)
- An issue with a null centerID displays **All Sites** in the site column
- Issues can be filtered by sites: All Sites. 
- Alternatively, All sites can be replaced with a comma separated list of all CenterID (to discuss) in the datatable column, and sites can be made multi-selectable.
* Add modification to test instructions to handle the NULL CenterIDs
* …
=> [issue_tracker] Update validation to allow NULL Site

.eslintrc.json, htdocs/js/loris.js
This PR:
* resolves all eslint prefer-rest-params warnings
* raises prefer-rest-params severity to error
```
rm -R nodes_modules/
npm install
```
```
make checkstatic
```
No warnings `Use the rest parameters instead of 'arguments'  prefer-rest-params` should be printed.
```
git checkout master htdocs/js/loris.js
make checkstatic
```
An error `Use the rest parameters instead of 'arguments'  prefer-rest-params` should be printed.
* resolves #6750 (partially)
=> [eslint] Fix prefer-rest-params warning

.eslintrc.json
This changes console.log back from an eslint error to an
eslint warning. With the current settings console.log can't
be used (even in development) because `make dev` fails with
an error about console.log. Making it impossible to use
console.log in development just encourages people to misuse
other console levels, which won't be flagged by eslint.
=> Lower console.log from eslint error to warning

modules/candidate_parameters/php/module.class.inc, php/libraries/Settings.class.inc
Resolves https://github.com/aces/Loris/issues/6680
1. In Configurations module,  set 'Use consent' config option to Yes.
2. Navigate to Candidate Profile page from non-admin account and see the consent card there as it should be.
3. Now, set 'Use Consent' config to 'No'
4. Refresh the candidate profile page and see that the consent card is no longer there
* Resolves #6680
=> [candidate_profile] Show Consent Summary card iff useConsent Yes

modules/instrument_builder/jsx/react.questions.js
The default value "0" for both 'Min' and 'Max' fields return 'Max value must be larger than min value' error on clicking 'Add Row'.
The 'Min' and 'Max' fields are now empty as the default.
* Resolves #6568
=> [instrument builder] Min/max null default value

modules/module_manager/jsx/modulemanager.js
The alert prompting the user to reload the page in
the module manager had incorrect spacing and punctuation
in the message shown to the user. This corrects it.
=> [Module Manager] Fix punctuation in reload prompt

Makefile, package.json, test/run-shell-linter.sh, tools/install.sh
Building on the work of #5160, this adds `shellcheck` to our static analysis pipeline in the fashion of our PHP linters.
We can iterate on this to fix errors on a file-by-file basis. 
Run the install script and make sure it works like it did before.
=> Add shellcheck to static analysis suite

modules/electrophysiology_browser/php/sessions.class.inc, php/libraries/Module.class.inc, php/libraries/NDB_Page.class.inc
When a user tries to access the individual session page for a project they are not affiliated with (by altering the URL), a "permission denied" message should appear.
1. Create a user and give them `View all-sites Electrophysiology Browser pages` permission.
2. Assign the user project "Pumpernickel" and site "Ottawa"
3. Navigate to the EEG browser page as that user.
4. Copy either the "all-types" or "raw" link from one of the rows.
5. As an admin, change the user to a different project (anything other than Pumpernickel)
6. Go back to the user account and to the EEG Browser page.
7. Note that there are no sessions listed (on the test VM)
8. Paste the copied URL.
9. There should be a "Permission denied" message and no data should be displayed.  
* Resolves #6558
* Related to issue #6557 and …
=> [electrophysiology_browser] Session page: Add Project Permissions check

php/libraries/NDB_BVL_Instrument.class.inc
The variable was incorrectly renamed in a PR which was just
supposed to add access modifiers to variables. This old name
is used all over the place by instruments, so this restores
the name to prevent warnings from LORIS.
The keyword needs to remain `var` to prevent PHPCS from
complaining about the underscore.
=> [Instrument] Fix GUIDelimiter class variable name

modules/statistics/templates/form_stats_demographic.tpl
This PR  adds a check for whether a project has been selected in the Demographics Statistics tab of the Statistics module before adding the `Undefined` column.
1. Go to the `Demographics Statistics` tab of the `Statistics` module.
2. Check that the `Undefined` column of the first table is not present by default. 
3. Select a project in the project drop down above the table and click `Submit Query`. Check that the `Undefined` column appears for any project selected.
4. Select `All Projects` in the drop down again, and click `Submit Query`. Check that the `Undefined` column disappears again.
* Resolves #6771
=> [Statistics] Remove Undefined column when no project selected

Makefile
PR #6053 added the "shellcheck" tool to our static analysis suite
to lint shell scripts. However, the PR added it to `make checkstatic`
prematurely.
1. The wrapper shell script does not run on MacOS because it depends
on newer bash options.
2. The script requires a third party tool which is not managed by
any of our dependency managers (npm, composer, etc) to be installed.
The result is that developers can no longer run `make checkstatic`
to check their code without running through hoops. This removes
it from the checkstatic target, since it currently prevents developers
from working on LORIS.
=> [dev] Remove shellcheck from make checkstatic

modules/new_profile/php/new_profile.class.inc
Since #6186,  /new_profile/ triggers an error 500 on submission.
This PR fixes the regression.
* Resolves #6821
=> [New Profile] error 500 fix (regression from #6186)

htdocs/index.php, src/Middleware/ExceptionHandlingMiddleware.php, src/Router/BaseRouter.php
The ExceptionHandlingMiddleware uses the PageDecorationMiddleware,
and as such needs to be chained after all the prerequisites of the
PageDecorationMiddleware (ie. the lorisinstance and user) are added
to the request object.
This converts it from a MiddlewareChainer interface into a normal
middleware and explicitly adds it to the BaseRouter, instead of the
top level chain.
Replaces #6820.
=> [Exceptions] Fix null user on ExceptionHandlingMiddleware

CONTRIBUTING.md, README.md, docs/wiki/00_SERVER_INSTALL_AND_CONFIGURATION/01_LORIS_Install/Troubleshooting.md, docs/wiki/99 - Developers/UnitTestGuide.md, docs/wiki/99_Developers/Automated_Testing.md
Changes all (non-deprecated) references to the master branch
to now refer to the main branch in the codebase.
=> [Docs] Update documentation to refer to main branch

CHANGELOG.md, SQL/0000-00-00-schema.sql, SQL/New_patches/2020-03-26_add_account_request_date_to_users_table.sql, modules/login/php/requestaccount.class.inc, modules/user_accounts/jsx/userAccountsIndex.js, modules/user_accounts/php/edit_user.class.inc, modules/user_accounts/php/useraccountrowprovisioner.class.inc, modules/user_accounts/templates/form_edit_user.tpl, test/unittests/UserTest.php
This adds a new `account_request_date` field to the `users` table to register information about when a given user requested an account.
1. source the SQL patch attached to the PR
2. test that requesting a new account (on the login page) inserts a new user with the date properly filled
3. test that the 'Account Request Date' is properly displayed in the menu filter page of user accounts
4. check that the 'Account Request Date' is properly displayed after the 'Active from' and 'Active to' fields in the edit user page of user accounts.
* I don't believe an issue was created for that but this came up with Open PREVENT-AD where they wanted to have information about when a user requested access
=> [users] Add 'request account date' to users

SQL/0000-00-00-schema.sql, SQL/New_patches/2020-03-09-SQL_patch_for_HRRT_PET_images_insertion.sql
This PR updates the SQL schema to include the new PET HRRT archive tables and their link to the already existing imaging tables.
1. Ensure the SQL patches and schema run properly
* This is linked to LORIS-MRI PR https://github.com/aces/Loris-MRI/pull/524  
* Github issue: https://github.com/aces/Loris-MRI/issues/480
=> [SQL/imaging] Adding SQL code for the new HRRT PET insertion scripts

tools/delete_candidate.php
Fix in delete_candidate.php tool to use the CandID class.
* Resolves #6757
=> [Tools] delete_candidate CanID Fix

test/unittests/UserTest.php
Unit tests for the User and UserPermissions libraries under `php/libraries`. This PR completes the coverage of these two libraries.
**Note:** The functions `getSiteNames` and `getCenterID` are deprecated and are not covered.
**TODO:**
Run `npm run tests:unit -- --filter UserTest` or check out the Travis output.
=> [Test] unittests for User.class.inc, UserPermissions.class.inc

.travis.yml
16.04 is nearly 4 years old now. This PR changes Travis to test a more recent OS. It looks like it may also cut down on the start up time of the tests.
Modifications to the config file are made based on the official Travis update guide. https://docs.travis-ci.com/user/reference/bionic/
* #5253 should be updated with version information following this PR being merged.
=> Change Travis distribution target from Ubuntu 16.04 to 18.04

jsx/FilterableDataTable.js
This adds a callback for updating filters in a FilterableDataTable.
This is intended to make it possible to add features such as context
sensitive filters, where the option selected for filter A might affect
the options available in filter B (for instance, selecting a project filter
affecting which subprojects are available in a subproject filter.)
Since changing the options might result in filter B being in an invalid
state (if the option that was selected is no longer valid when A
changes) the FilterableDataTable also removes invalid choices from being
passed down to the DataTable or Filter components upon rendering.
=> Add callback for updates of filters in FilterableDataTable

src/Router/BaseRouter.php
The second argument to the "process" function is a RequestHandler,
but was incorrectly passed a response directly in the case where
the BaseRouter got a 404 error.
This is not a case that should generate any exceptions, since it's
not dependent on any user data (other than the URL from the request
object, which is just used for the error page).
Remove the ExceptionHandlingMiddleware to fix this case.
Fixes the error:
```
Fatal error:  Uncaught TypeError: Argument 2 passed to LORIS\\Middleware\\ExceptionHandlingMiddleware::process() must implement interface Psr\\Http\\Server\\RequestHandlerInterface, instance of LORIS\\Http\\Error given, called in /var/www/loris/src/Router/BaseRouter.php on line 140 and defined in /var/www/loris/src/Middleware/ExceptionHandlingMiddleware.php:29\nStack …
```
=> [Core] Fix fatal error caused by exception handling middleware

php/libraries/NDB_BVL_Instrument.class.inc
The instrument getFieldValue function was doing a "!empty" check
to see if the field is valid. This catches values such as "0"
incorrectly and converts them to false.
This changes it to array_key_exists to properly verify that the
field is valid. At the same time, it converts the "false" error
code return for an invalid field to an exception, since callers
shouldn't be requesting the value of fields that don't exist on
an instrument, and it indicates a programming error that is more
likely to be caught this way.
=> [Instrument] Allow fields to have value "0"

jsx/Panel.js
This PR does the following:
- makes title of Panel **bold** (let me know what you think about this. i find making it bold lets it stand out from other text on the page i.e. for if there are multiple Panels rendered such as in the new candidate profile module that has multiple cards)
- add missing proptypes and default proptype values (cleanup)
1. run `npm run compile` , checkout Examiner module for now bold title 'Examiner' at the top of the Panel
=> [jsx/Panel] Make Panel title Bold

SQL/0000-00-03-ConfigTables.sql, SQL/Cleanup_patches/2020-02-06-NoMultipleSitesConf.sql
I could not find any references to this config setting in the LORIS
codebase. The only references are in SQL patches adding it. It's
also not a very useful config setting, since it would be more reliable
to just check whether the psc table has multiple entries or not.
=> [SQL] Remove multipleSites config setting

modules/statistics/php/statistics_dd_site.class.inc, modules/statistics/php/statistics_site.class.inc
Code refactorization of the functions `_hasAccess` and `_checkCriteria`.
Adds per projects permissions restrictions.
A user with permission `data_entry` should be now able to access the 'breakdown per participant' only for the sites and projects it have access to.
* Resolves #6659
=> [Statistics/Behavioural]  Detailed View and Double Data Entry - Site permission fix

test/run-php-linter.sh
PR #6786 was merged with an issue which removes Database_test.php from the list of scripts PHPCS runs onto.
This PR fixes this issue.
=> [Test/Tools] Fix scripts issue with PR #6786

php/libraries/LorisForm.class.inc, smarty/templates/instrument_html.tpl
When working with Loris Form, one can only position the error message to row level or to element level if this is a standalone element. 
If the items is in a big table, Loris doesn't support cell level error message positioning, though the table rendering is supported and the row level error message could somehow be supported. Because of the fact that here we have two interpretations for the same id (element vs table row), the idea is not quite clear because one needs to find the table row id instead of element id to be able to show positioning error message. this could create some confusion for new developers.
The modification here will add this capacity, with the following formats:
`$errors[<table id>] = ["<cell id>" => "<error message>"]`
or `$errors[<table id>] = ["<cell id 1>" => …
=> [added function] Group error message cell positioning

modules/api/php/endpoints/candidates.class.inc
Fix for `PHP Fatal error:  Uncaught TypeError: Argument 4 passed to Candidate::createNew() must be an instance of LORIS\\StudyEntities\\Candidate\\Sex, string given, called in /var/www/loris/modules/api/php/endpoints/candidates.class.inc on line 213`
1. Use the API to POST a new candidate.
=> [API] fix POST to candidates type error

modules/imaging_browser/php/imagingbrowserrowprovisioner.class.inc
The mri_acquisition_date table dropped in LORIS 22.0, and replaced by
a JOIN to the `parameter_file` table in order to look up the header
directly. However, ths query is missing a clause to restrict it to
only look up the `acquisition_date` header, resulting in an
unconditional join to `parameter_file`. Due to the size of the table
in existing projects, this can make the imaging browser menu page
take minutes to load.
This adds a where clause to restrict it to joining the `acquisition_date`
header, making the load time of the module usable again.
=> [imaging_browser] Fix inefficient query for first acquisition date

modules/statistics/php/stats_behavioural.class.inc
When no project is selected the behavioural tab should show results for all projects for all visits. instead it was just displaying an empty row see images.
before:
after:
=> [Statistics] fix behavioural tab without any project selection

modules/instrument_builder/js/instrument_builder.instrument.js, modules/instrument_builder/jsx/react.questions.js
this is almost an exact replica of #5616 with the difference being that this would be backwards compatible with existing linst files havin `static{@}{@}<br />` encoding a blank line.
This functionality was removed 5 years ago in the following commit https://github.com/aces/Loris/commit/52b22d7fc66720e57ebc5f4d4564cdb288222409
=> [instrument_builer] Blank line fix

SQL/0000-00-00-schema.sql, SQL/New_patches/2020-02-10-AddConsentGrouping.sql, modules/candidate_parameters/ajax/formHandler.php, php/libraries/Utility.class.inc, raisinbread/RB_files/RB_consent.sql, raisinbread/RB_files/RB_consent_group.sql
**PR 1 of 2**
This PR:
- adds ConsentGroupID to consent table (schema + patch)
- updates RB_consent.sql to have consent group IDs
- adds RB_consent_group.sql to have 2 groups
- update getConsentList() function in \Utility to query only ConsentGroupID as well
- fixes PHP notice of undefined index in formHandler.php
This PR keeps the Consent Status tab rendering the same. Only the back-end is affected in this PR. This feature is increasingly in demand from projects who would like to split up consents via e.g. consent forms. Front-end changes are in PR #6044 (to be rebased after this PR gets merged)
1. On aces/main, test Consent Status tab of candidate_parameters module. See that you can fill in consent for a candidate for study_consent, raisin_consent, and bread_consent. If you don't see …
=> [Consent] Add ParentID to `consent` for consent grouping

SQL/0000-00-03-ConfigTables.sql, SQL/New_patches/2020_06_16_Add_Date_Format_to_ConfigSettings_DataType.sql, modules/candidate_parameters/ajax/formHandler.php, modules/configuration/php/configuration.class.inc, modules/configuration/templates/form_configuration.tpl
Quick fix for candidate parameter tabs `Date of Birth` and `Date of Death`. Altering the DOB format or the DOD format fields in the configuration module to either `YM` or `Ym` should result in the dates in cand param being saved with `YYYY-MM-01` as the day of the month rather than whatever the user entered. 
**Edit:**
This PR now adds a new dataType to ConfigSettings: `date_format`. Fields such as DOB and DOD format will now have a dropdown in which users that select what format they prefer. This should also resolve the ambiguity in candidate parameters that is discussed in the thread below.
1. See test plan steps 35 & 40
* Resolves #6678
=> [configuration] Add date_format as DataType in ConfigSettings

php/libraries/NDB_BVL_Instrument.class.inc, test/unittests/NDB_BVL_Instrument_Test.php
Unit tests for the NDB_BVL_Instrument library under `php/libraries`. This PR aims to complete coverage for this library.
1. Run `npm run tests:unit -- --filter NDB_BVL_Instrument_Test` or check out the Travis output
=> [Test] unittests for NDB_BVL_Instrument library

readthedocs/mkdocs.yml
The "wiki" link below the "Home" link on the ReadTheDocs
instructions doesn't include any information, has no subitems,
and isn't a wiki.
This removes it from the navbar.
=> Remove 'wiki' from ReadTheDocs menu

tools/exporters/dataExtractor.php
Fix the warning:
```
PHP Deprecated:  The behavior of unparenthesized expressions containing both
'.' and '+'/'-' will change in PHP 8: '+'/'-' will take a higher precedence
in tools/exporters/dataExtractor.php on line 279
```
when running `make checkstatic`.
As a bonus, also fix that line of the script, which was broken.
=> [Lint] Fix PHP Deprecated warning

CHANGELOG.md, modules/candidate_parameters/ajax/getData.php, modules/candidate_parameters/jsx/ConsentStatus.js, php/libraries/Utility.class.inc
**PR 2 of 2.** This PR includes changes from https://github.com/aces/Loris/pull/6042 and will need to be rebased once #6042 has been merged.
This PR follows the first PR by rendering the grouping of consents and improves other aspects of the UI.
This PR:
- Adds vertical tabs for each parent consent and renders within that tab all the children consents
- For each consent rendering: adds a HeaderElement for the consent label, changes label for Yes/No select Element to 'Response', changes label for Date element to 'Date of Response'
- Hides Consent history by default
- Add Show/Hide Consent history toggling
- Cleans up the rendering of the history string
1. Source all sql patches as instructed in PR #6042 
2. git checkout zaliqarosli/2020-02-10-AddParentToConsentUI
3. Run make
4. Got to …
=> [Consent] Group consents + Improve UI

test/run-php-linter.sh, tools/CouchDB_Import_Demographics.php
=> [Tools] Enable PHPCS for CouchDB_Import_Demographics.php

modules/candidate_profile/test/candidate_profileTest.php, test/integrationtests/LorisIntegrationTest.class.inc, test/phpunit.xml
I added 2 helper functions, `changeProject` and `resetProject`, to the LorisIntegrationTest.class.inc class. These will allow us to test project permissions on modules. 
I also added initial integration tests for the `candidate_profile`module, **including a project permission test**.
1. Check Travis or run `npm run tests:integration -- --filter CandidateProfileIntegrationTest`
* Resolves #6911
=> [Integration] changeUserProject helper function, candidate_profile tests
