aces/Loris

modules/api/php/endpoints/candidate/visit/image/format/raw.class.inc
`\NDB_Factory::singleton()->config()->getSetting('MINCToolsPath')` returns null, which creates an error when trying to execute `new \SPLFileInfo($mincpath)`. 
Setting `$mincpath` to an empty string when null solves the problem.
1. Go to <hostname>/api/v0.0.3/candidates//587630/V1/images/demo_587630_V1_t1_001.mnc/format/raw.
2. The message `{"error":"Invalid MINCToolsPath configuration setting."}` should be displayed.
* Resolves #6827
=> Empty string when MINCToolsPath not configured

modules/electrophysiology_browser/test/TestPlan.md, modules/electrophysiology_browser/test/electrophysiologyBrowserTest.php, test/integrationtests/LorisIntegrationTest.class.inc, test/phpunit.xml
Adding integration tests for the electrophysiology_browser module
1. Check out Travis or run the command `npm run tests:integration -- --filter EEGBrowserIntegrationTest`
=> [EEG Browser] Integration testing for EEG Browser module

modules/imaging_browser/php/imagingbrowserrowprovisioner.class.inc
The query was updated for the imaging browser to use an
AcquisitionDate column from the file table instead of a
join to the parameter_type table. However, a leftover
clause in the WHERE part of the SQL statement is referencing
the no longer joined table, causing the page to crash on
accessing the menu.
This removes the invalid clause.
=> [Imaging Browser] Fix menu loading

modules/api/php/endpoints/candidates.class.inc, modules/api/php/models/candidatesrow.class.inc, modules/api/php/provisioners/candidatesprovisioner.class.inc
The list of candidates returned by the /candidates endpoint is filtered for projects that the user has access to. Only candidates from projects a user has access to is returned.
1- Login your VM with admin
2- Make sure one of the users don't have access to all projects. 
3- Login as the user that don't have access to all projects.
4- Go to <hostname>/api/v0.0.3/candidates
5- Make sure only the projects the user has access to appear in the list displayed on the page
* Resolves #6931
=> [API] Users get candidates from own projects only in endpoint /candidates that list all candidates

SQL/9999-99-99-drop_tables.sql
This PR adds 4 tables to `9999-99-99-drop_tables.sql` that were missing. This prevents an error when dropping tables for foreign key constraint fail.
1. After sourcing RB dataset, run the drop table patches. Make sure that no error is thrown, and that all tables have been dropped from database.
2. Make sure there are no errors when sourcing raisinbread
* Resolves #6920
=> [Raisinbread] Add missing tables to 9999-99-99-drop_tables

raisinbread/test/api/LorisApiCandidatesTest.php, src/StudyEntities/Candidate/Sex.php
The "Sex" attribute in the single candidate portion of the API
was incorrectly being serialized as an object with a "value" key instead
of a string.
This fixes it by implementing to JSONSerializable interface to
serialize Sex objects as strings.
Fixes #6951
Fixes #6995
Fixes #7008
=> [api] Fix value in "Sex" field of candidate API

.babelrc, CHANGELOG.md, htdocs/index.php, jslib/fetchDataStream.js, jsx/DataTable.js, jsx/FilterableDataTable.js, modules/datadict/jsx/dataDictIndex.js, modules/datadict/php/fields.class.inc, modules/datadict/test/datadictTest.php, package.json, php/libraries/DataFrameworkMenu.class.inc, php/libraries/NDB_Page.class.inc, src/Http/DataIteratorBinaryStream.php, webpack.config.js
This is a proof of concept. It loads the data for the data dictionary
module from a binary stream rather than a JSON object and displays the
data in the table as it is loading. The stream consists of rows separated
by the byte 0x1f, and columns separated by 0x1e. The entire stream is
terminated with the byte 0x04.
FieldOptions are moved to a different endpoint rather than crammed
into the JSON since there is no longer any JSON to cram it into.
=> [Data Tables] Add ability for data tables to stream data

test/unittests/NDB_Factory_Test.php
Unit tests for the NDB_Factory library under `php/libraries`. This PR aims to complete coverage of this library.
1. Run `npm run tests:unit -- --filter NDB_Factory
=> [Test] unittests for NDB_Factory.class.inc

modules/help_editor/test/TestPlan.md
=> [Help editor] Test plan update

modules/instrument_list/test/TestPlan.md
Update test plan to meet current functionality. Apparently, it used to be the case that a user was able to access a patient's timepoint at another site that the user is not affiliated with if the candidate has at least 1 timepoint at a site the user *is* affiliated with. That now has since changed (?) but the test plan wasn't updated.
1. Test item 1 of test plan and verify that it is the case.
=> [instrument_list] Remove from test plan ability to view another site's timepoint

modules/media/php/media.class.inc, modules/media/test/MediaTest.php
Solves the bug found in #6950
1. Hide file as superuser.
2. Refresh module.
3. Hidden file row should still be visible to superuser.
4. Hidden file row should be hidden from non-superusers.
* Resolves #6950
=> [media] hidden files do not display for superuser

modules/behavioural_qc/jsx/behavioural_qc_module.js, modules/behavioural_qc/php/behavioural_qc.class.inc, modules/behavioural_qc/templates/form_behavioural_qc.tpl
This PR fixes a bunch of issues noticed on the Behavioural QC module:
- Console warning about type mismatch in React component
- A 500 error if the data table is filtered with Instrument set to All instrument
- The Instrument dropdown which did not keep track of the selected value 
#Blocking #6836
#Fixes  #6946
=> [Behavioural QC] - Instruments filter fixes

modules/dashboard/test/DashboardTest.php, modules/user_accounts/php/module.class.inc
This PR removes the restriction that DDC users are not included in pending account approval in the dashboard widget. 
1. Request an account and choose Data Coordinating Center as site
2. Ensure that the number of `Pending account approvals` increases accordingly in the `My tasks` section of the dashboard
3. Ensure that when clicking on `Pending account approvals`, the user is included in the results
4. Repeat steps 2-3 after creating a new user from the `user_accounts` module with `Pending approval` set to `Yes`.
* Resolves #6962
=> [user_accounts] Remove DDC restriction for pending accounts in dashboard

modules/survey_accounts/php/addsurvey.class.inc, php/libraries/NDB_BVL_Instrument.class.inc, test/unittests/NDB_BVL_Instrument_Test.php
1. Fixing the SessionID type in addSurvey function.
According to @driusan 's commnet in https://github.com/aces/Loris/pull/5352#discussion_r450254444
"The semantics of this function shouldn't be changed to throw an exception. This isn't backwards compatible and is unrelated to using the SessionID class."
2. Fixing the return value of getSession.
Add a new survey for a candidate.
=> [survey_account] fix can't add survey to candidate in main branch

modules/imaging_uploader/jsx/UploadForm.js
This PR fixes a bug that would prevent the imaging uploader from starting automatically even if you had the imaging uploader auto-launch set to true and your current upload overwrote an existing file. In a nutshell, the PR replaces the `swal.fire` invocations of this form:
```
swal.fire({
.
.
}, function () {
.
.
}.bind(this));
```
with invocations like these:
```
swal.fire({
.
.
}).then(
.
.
);
```
1. Make sure config setting imaging uploader auto-launch is set to `Yes`.
2. Access the imaging uploader and search for a file that was *not* processed successfully by the MRI pipeline (i.e `Progress=Failure`).
3. Upload a file with exactly the same base name as the file you found in 2. When asked if you want to overwrite the file, click `Yes`.
You should see a message indicating that the MRI …
=> Fixed imaging uploader that would not automatically start when overwriting a file

test/run-php-linter.sh
Updated test/run-php-linter.sh to replace the tests and tools include list for an exclude list.
This allows PHPCS to run on all new tests/tools.
=> [Tools] PHPCS exclude list

raisinbread/test/api/LorisApiCandidatesTest.php
Adds two new tests for POST requests to the \Candidates endpoint. 
1- A valid POST request to create a new candidate at a site where the user is not affiliated with. It expects a Forbidden HTTP error (403). 
2- An invalid POST request where the project is an empty string. It has to be an existing project, so it fails with NotFound error (400). 
* Resolves #
=> [API] New api candidates endpoint post tests

modules/configuration/js/configuration_helper.js
Fix bug where the fields added with the “Add field” button were not properly reset when the “Reset button” of the form was clicked.
See more details on issue #7009 
1. Go to: `MainMenu->Admin->Configuration->Satistics`
2. Add a new field using the button `“Add field”`
3. **Before submitting** the form click `“Reset”`
4. The fields should be now properly reset.
**Note:** The same functionality should be observed if done in other of the tabs (Study for example).
* Resolves #7009
=> [Configuration] fix funny behaviour of “Reset button” for fields that have the “Add field” button.

modules/mri_violations/help/resolved_violations.md
The help text for MRI Resolved Violations was missing. The screenshot below shows the help text that I added.
* Resolves #7021  (Reference the issue this fixes, if any.)
=> [MRI Violations] Add help text to MRI Resolved Violations

.travis.yml
Go back to using latest 1.x branch of composer on Travis for compatiblity with our dependencies.
=> Downgrade composer to latest 1.x branch

smarty/templates/public_layout.tpl
Public pages have an empty title attribute, resulting in a poor Google result preview.
=> [Core] Public page missing title fix

modules/instruments/help/instruments.md
I added a markdown file under `modules/instruments/help/` so that Help instructions for the user will render when they are completing instrument data entry. 
Here is a screenshot of how the markdown renders in the frontend. 
1. Checkout this branch and go to the LORIS frontend.
2. Navigate to `Candidate`->`Access Profile` and choose any candidate with associated instruments.
3. Navigate to the Data Entry page for any of the timepoint's instruments.
4. Go to the top of the page and click on the `?`
5. View the markdown.
* Resolves #6906
=> [Help Doc] Added help file for instrument data entry

.github/workflows/loristest.yml, .travis.yml
Given the changes to Travis pricing which are changing
at the end of the year and the long VM startup times
we've been experiencing lately, this adds a configuration
for GitHub actions to run our continuous integration
directly on GitHub.
The .travis.yml is kept around for now, but will likely
eventually be removed. PHP 7.4 is also removed from the
Travis configuration, because I discovered while setting
this up that there's a bug where both "PHP 7.3" and "PHP 7.4"
are running PHP 7.3 under docker with our current configuration.
(The bug is fixed in the GitHub actions configurations, but
given that we'll be moving away from Travis, isn't worth fixing
there.)
=> Add configuration to run CI with GitHub actions

SQL/0000-00-00-schema.sql, SQL/New_patches/2020-10-29-session-current-stage-default.sql
Update Current_stage column definition in session:
- Set default value of Current_stage to 'Not Started'
- Set Current_stage not nullable
Resolves #6874
=> Session Current_stage - Not Started as default value

modules/api/php/views/visit/flags.class.inc, modules/api/php/views/visit/instrument.class.inc, php/libraries/NDB_BVL_Instrument.class.inc, raisinbread/instruments/NDB_BVL_Instrument_aosi.class.inc, test/unittests/NDB_BVL_Instrument_Test.php, tools/single_use/instrument_double_escape_report.php
NDB_BVL_Instrument has an.. unusual.. way of dealing with instrument
data. Rather than having a class method for getting the data, there's
a static method which takes an instrument as a parameter. The result
is that data can not be cached in the object and needs to be continuously
re-loaded from the database every time if it's needed multiple times in
the same request. (For instance, calling getFieldValue for different fields
in a script.)
This adds a normal getter and caches the results in the object, deprecating
the old static loadInstanceData and its inexplicable behaviour.
=> [Instrument] Make instrument data non-static

tools/generate_candidate_externalids.php
New tool to fill external IDs for all candidates where a NULL value is found.
=> [Tools] Generate Candidate External IDs

modules/statistics/php/stats_demographic.class.inc
The demographics page currently uses hardcoded IDs `1` and `5` for `Active` and `Inactive` respectively, however the SQL 0000-00-00 patch does not insert with fixed IDs.
Added a subquery to refer to the description field instead
=> [statistics] Fix remove hardcoded IDs

package.json, webpack.config.js
Updates the dependancy copy-webpack-plugin in package.json.
Also updates the webpack.config.js to use the new copy-webpack-plugin format.
1. npm install
2. npm run compile
https://github.com/aces/Loris/issues/7109
=> [webpack.config.js] update copy-webpack-plugin dependency

php/libraries/LorisForm.class.inc, php/libraries/NDB_BVL_Battery.class.inc, php/libraries/TimePoint.class.inc
Fixes minor warnings and the logic to populate an instrument with json_data === true.
=> [instrument] insert JSON intrument fix

php/libraries/TimePoint.class.inc
The last commit broke the build. This PR fixes the PHPCS error.
FILE: /var/www/Loris/php/libraries/TimePoint.class.inc
--------------------------------------------------------------------------------
FOUND 2 ERRORS AFFECTING 2 LINES
--------------------------------------------------------------------------------
959 | ERROR | [x] Whitespace found at end of line
960 | ERROR | [x] Closing parenthesis of a multi-line IF statement must be on
|       |     a new line
--------------------------------------------------------------------------------
PHPCBF CAN FIX THE 2 MARKED SNIFF VIOLATIONS AUTOMATICALLY
--------------------------------------------------------------------------------
Time: 6.09 secs; Memory: 24MB
=> 23.0-release build fix

CHANGELOG.md, modules/candidate_profile/templates/form_candidate_profile.tpl
v0.0.2 support was removed in #6944.
The CHANGELOG was also referencing the wrong pull request.
=> [candidate_profile] Update API version used by candidate_profile to be v0.0.3

SQL/0000-00-01-Permission.sql, SQL/Cleanup_patches/2020-06-18-remove_violated_scans_edit_permission.sql, modules/mri_violations/php/resolved_violations.class.inc, raisinbread/RB_files/RB_permissions.sql, raisinbread/RB_files/RB_user_perm_rel.sql
A patch was created to Remove the unused permission `violated_scans_edit` from the database.
* Resolves #6723
=> [SQL Cleanup Patch] Remove violated_scans_edit permission

modules/dataquery/jsx/react.fieldselector.js, modules/dqt/jsx/react.fieldselector.js
Define Fields of the DQT module has incorrect field description. This PR fixes the bug.
1. Visit DQT
2. Add demographics to fields.
3. Look at the field descriptions
=> [DQT|dataquery] Define Fields showing incorrect field description

modules/create_timepoint/php/create_timepoint.class.inc
Small change to fix a reindexing of the languages, causing a database insert error (key constraint failure on languageID).
Add languages to the database (language) at sparse indexes (ex: 2, 4).
You should be able to submit without a 500 error.
* Related to #7145 (main)
=> [Create timepoint] Language dropdown index fix

CHANGELOG.md, modules/instrument_list/php/instrument_list.class.inc, php/libraries/Candidate.class.inc, php/libraries/Utility.class.inc, test/unittests/CandidateTest.php, test/unittests/UtilityTest.php
This PR adds a new function called `getLastVisitSubproject` in the candidate class. This new function replaces the function `getSubprojectIDUsingCandID` in Utility class.
`getSubprojectIDUsingCandID` is only currently being called in one place, the instrument_list class. The returned value there however affects nothing. It is passed as an argument to the function `getBatteryInstrumentList` that then does nothing with the parameter
1. Test instrument_list page on both master and this branch. Check that there are absolutely no changes.
2. Try to use getLastVisitSubproject and render the returned data somewhere on Loris and see the results
=> [Candidate] Add get last visit subproject

CHANGELOG.md, src/Data/Cardinality.php, src/Data/Dictionary/Category.php, src/Data/Dictionary/DictionaryItem.php, src/Data/Scope.php
This adds the classes representing the data scope, data type,
data cardinality, DictionaryItem (and dictionary Category) from
PR #6936 but does not use yet use them.
=> Add Scope, Cardinality, Type, and DictionaryItem classes

composer.json, composer.lock, src/Http/Client.php, test/unittests/PasswordTest.php
This updates all dependencies other than phan to a version
which supports PHP8.
In theory, this should make updating easier.
=> Update dependencies other than phan to versions supporting php8

tools/delete_candidate.php
delete_candidate.php now deletes corresponding rows from the candidate_consent_rel table. 
Delete candidate who has consent
* Resolves #7184
=> [tools] delete_candidate.php delete from candidate_consent_rel 

php/libraries/File_Upload.class.inc
phan doesn't flag any errors on the line being
suppressed.
=> Remove unnecessary phan suppression

.github/workflows/loristest.yml, .phan/config.php, composer.json, composer.lock, modules/document_repository/php/document_repository.class.inc, modules/document_repository/php/files.class.inc, modules/imaging_browser/php/imagingbrowserrowprovisioner.class.inc, modules/server_processes_manager/php/serverprocessesmonitor.class.inc, package.json, php/libraries/CouchDB.class.inc, php/libraries/NDB_BVL_Battery.class.inc, php/libraries/NDB_Form.class.inc, php/libraries/SiteIDGenerator.php
This copies the GitHub Actions CI configuration to the release branch, with the hopes that it'll work and we'll be able to continue doing bug fixes in the new year without Travis..
=> Copy GitHub actions config to 23.0-release branch

.github/workflows/loristest.yml
`make dev` and composer were being run with the default
php version, not the PHP version from the build matrix.
This was causing build failures as the default version is
PHP8 and some dependencies do not support it.
Add a Setup PHP step to fix.
=> Add setup php step to GitHub Actions workflow

modules/document_repository/jsx/docIndex.js
Related to aces/CCNA#4302
Root directory of the doc repo should only contain files that are located at root. All other files will be in subfolders.
Can see all files by filtering globally. 
This was a design decision made by Zal and Derek a while ago but was reverted in #6408.
Please see @zaliqarosli 's comment [here](https://github.com/aces/Loris/pull/6408#issuecomment-745620992)
=> [23.0][document_repository] Fix for contents displayed at root

modules/datadict/jsx/dataDictIndex.js, modules/datadict/test/TestPlan.md
Remove references to "search keyword" in test plan. The
search keyword was lost in reactification in favour of filters
consistent with the data table columns, like in other modules.
(Searching across multiple columns with the same filter is not
supported by our FilterableDataTable)
Update the "Source From" column to be a multiselect. This was
also lost in reactification, but is a simple fix.
Resolves #7205
=> [data_dict] Convert list of instruments back to multiselect

php/libraries/NDB_BVL_Instrument.class.inc, test/unittests/NDB_BVL_Instrument_Test.php
This removes some code that was in place to handle
differences between LorisForm and QuickForm. At this
point there's no excuse for instruments to not have
been migrated (and it's likely that at some point they
would have broken in a PHP upgrade anyways if they
weren't migrated to LorisForm yet.)
=> Remove legacy code to support QuickForm

modules/instrument_manager/jsx/instrumentManagerIndex.js, modules/instrument_manager/php/instrument_manager.class.inc, modules/instrument_manager/test/TestPlan.md
This PR makes it so that users with the instrument_manager_write permission are able to upload on instrument manager, and people without this permission do not have access to the upload tab. 
1. Access the instrument manager page with only the view permission. Make sure that you only see the "Browse" tab, and not the "Upload" tab. 
2. Attempt to go directly to the upload tab by adding /instrument_manager/?#upload to your base link. Make sure that the page loads with "You do not have access to this page"
3. Give yourself the instrument_manager_write permission.
4. Make sure that you now have access to the upload tab, either by reloading the page and clicking on the tab, or by navigating directly to the link.
5. Attempt to upload a file. Ensure that you are not given the "forbidden" error …
=> [instrument_manager] Fix write permission

modules/bvl_feedback/ajax/open_bvl_feedback_thread.php
This PR fixes a typo that was leading to a 400 error when trying to re-open a closed bvl thread. 
1. Try to open a closed thread in `bvl_feedback` module
* Resolves #7189
=> [23.0][bvl_feedback] Bugfix for re-opening a closed thread throwing 400 error

jsx/StaticDataTable.js
This PR solves 2 issues:
- when a row matches 2 filtering criteria, this row is included twice in the csv
- the rows matching the filtering criteria partially are included in the csv 
The bug was found on the publication module and probably affects all modules using the StaticDataTable.
Filter a data table with 2 criteria:
- check that the rows matching all criteria are not included twice in the csv
- check that the rows that match some but not all criteria are not included in the csv
* Resolves #7229
=> [Core] Download CSV issues

modules/behavioural_qc/jsx/behavioural_qc_module.js
This PR fixes a bug in the Behavioural QC module. The issue was that clicking on link in the `Instrument` column of the `Data Conflicts` tab would redirect to the Conflict Resolver module, but would not include the appropriate filters.
1. Go to Behaviour QC Module
2. Click on Data Conflicts Tab
3. Click on link in the Instruments column
4. Ensure that you are redirected to the Conflict Resolver module with the appropriate filters applied
* Resolves #7159
=> [behavioural_qc] Resolving redirect to conflict resolver issue

htdocs/css/panel.css, htdocs/main.css
The PR solves the bug where the user menu wasn't useable if the bvl_feedback panel was open.
1. `MainMenu->Canditate-> Access Profile`.
2. Click on a candidate of choice.
3. Open the  `bvl_feedback `panel clicking on the notepad icon in the left part of the Main Menu bar (at the left of the help button sign) 
4. See that the user menu like the Admin account is useable.
* Resolves #7188
=> [bvl_feedback] bvl_feedback panel not allowing access to User Menu while open

modules/imaging_qc/test/TestPlan.md
Remove part of test planning stating that downloaded csv should maintain the same row order as displayed in the datatable.
* Resolves #7191
=> [imaging_qc] Update Test Plan

php/libraries/NDB_BVL_Instrument_LINST.class.inc, test/unittests/NDB_BVL_Instrument_LINST_ToJSON_Test.php
This PR fixes the removal of '_date' by only allowing it to happen for Standard Date formats. 
Currently, all date elements (standard, basic, and month/year) in linst instruments have their field names redefined as the substring appearing before '_date'. For example, if a date element is called 'enrolment_date_v2', the instrument field name becomes `enrolment`. The issue with this is that on saving the instrument, the save function will try to update a field called 'enrolment' in the instrument table which does not exist.
Now, the reason why this functionality existed in the first place is because the Standard Date format requires a field name ending  with '_date'. Linst Standard Date formats are created by calling the `NDB_BVL_Instrument` class addDateElement() function which auto …
=> [LINST] Remove '_date' only for Standard Format

CHANGELOG.md, php/libraries/NDB_BVL_Instrument_LINST.class.inc, raisinbread/instruments/bmi.linst
LINST instrument class was using the legacy trait to bypass defining it's own instrument's full name and subtests, both values were already somewhere in the file and should now be implemented without using the database values
additional fix for numeric elements for which the min and max values were not passed on to the instrument
1. LINST instruments should work... more specifically LINST instruments with pages, pages should load properly
=> [LINST] Implement getFullName() and getSubtestList() and fix numeric type

src/Middleware/UserPageDecorationMiddleware.php
The PR solves the following:
Fatal error: Uncaught TypeError: method_exists(): Argument #1 ($object_or_class) must be of type object|string, null given in Loris/src/Middleware/UserPageDecorationMiddleware.php on line 139
The not empty checks solve the PhanEmptyFQSENInClasslike warnings.
src/Middleware/UserPageDecorationMiddleware.php:139 PhanEmptyFQSENInClasslike Possible use of a classlike '' with an empty FQSEN.
src/Middleware/UserPageDecorationMiddleware.php:251 PhanEmptyFQSENInClasslike Possible use of a classlike '' with an empty FQSEN.
1. MainMenu->Canditate-> Access Profile.
2. Visit candidate of choice
3. Check error_log
=> [middleware/UserPageDecorationMiddleware.php] fix visit candidate profile error

modules/conflict_resolver/php/conflict_resolver.class.inc, modules/conflict_resolver/php/resolved_conflicts.class.inc
Change the display of multi select values from value1{@}value2 to value1, value2 in the `Correct Answer` column of `Unresolved` and `Resolved Conflicts`.
* Resolves #7217
=> [Conflict Resolver] Multiselect values

modules/instrument_builder/js/instrument_builder.instrument.js, modules/instrument_builder/jsx/react.questions.js, php/libraries/NDB_BVL_Instrument_LINST.class.inc
This PR fixes multiple issues with Date elements in LINST files that have existed for several previous releases. Due to the age of these issues, some backwards compatibility logic was necessary for proper functioning of existing projects.
1. when adding a date field in the instrument builder, If the date format was not manually changed on the frontend, the default format was simply an empty string `''`. If however a user selected a date format and then re-selected the default standard date, the date format was saved as `Date`. Standard dates in existing instruments are saved as either `Date` or `''` currently due to this bug and thus both versions are currently!! Prospectively only `Date` will be saved in .linst files and a deprecation message was added to slowly modify all empty empty or …
=> [instrument_builder] Fix Date element corruption in LINST files when load/saving 

php/libraries/NDB_BVL_Instrument.class.inc
Currently the `_nullScores()` function saves all fields in the table, leading to an issue with double escaping of special characters. In other to amend, this PR ensures that only score fields are being saved by the `_nullScores()` function. 
1. Input a special character in an instrument text field (ex: `<`, `>`, `"`, `&`)
2. Run score instrument script to ensure no double escaping occurs.
* Resolves #7140
=> [Instrument.class.inc] Fix _nullScores() so that only score fields are saved

modules/dashboard/test/TestPlan.md
The dashboard TestPlan previously implied that there should be a separate issue tracker panel. This PR changes the wording of step 6 to refer to a row in the My Tasks panel rather than a separate panel. 
* Resolves https://github.com/aces/CCNA/issues/4275
=> [dashboard] Fix step 6 of TestPlan

SQL/Archive/21.0/Cleanup/2020-12-18-Remove_survey_emails.sql, modules/survey_accounts/jsx/surveyAccountsIndex.js, modules/survey_accounts/php/addsurvey.class.inc, modules/survey_accounts/php/survey_accounts.class.inc
Removing all traces of stored emails in the database without affecting emailing functionality.
=> [survey_accounts] Remove all traces of emails from the database

modules/document_repository/jsx/categoryForm.js, modules/document_repository/php/uploadcategory.class.inc
Preventing to add same category name under same parent directory.
If add same category name under same parent directory,
it will show a warning.
https://github.com/aces/Loris/issues/7232
=> [document repository] prevent to add same category name under same parent directory

modules/create_timepoint/php/timepoint.class.inc
Timepoint creation was incorrectly using the site dropdown as the
projectID instead of the project dropdown when the user had more
than 1 project. This corrects it to use the appropriate dropdown
for creation.
=> [create_timepoint] Use the project for the project, not the site

php/libraries/NDB_BVL_Instrument_LINST.class.inc, test/unittests/NDB_BVL_Instrument_LINST_ToJSON_Test.php
These changes were made to reflect the https://github.com/aces/Loris/pull/6923 which was issued to the `main` branch
Additional changes not in #6923:
- modified the "stripping" function to only remove `_date` if it is positioned at the end of the field name. For example if the user names their date field `my_date_of_release_date`, previously the function would strip the field name to `my`; now it would only strip the last `_date` to become `my_date_of_release`
- removed the check for `isset($dateformat)` since the code is already converting a null $dateformat to an empty string 2 lines above !
- reorganized the if statements to reduce over all complexity
- added an exception if the date format does not match any known formats
=> [LINST] modify LINST class to only strip '_date' from standard dates

php/libraries/NDB_BVL_Battery.class.inc
The behaviour change in the battery was copied over from the `assign_missing _instruments` php script. This is not the ideal implementation but is sufficient to serve as a proposal up for discussion. Alternate solutions can include
- completely separate function to populate vs create a battery
- only allow to "fill in" battery if already existing instruments are surveys (not a prepopulated battery of instruments)
- behaviour could be added uniquely to next stage (although this limits the potential to allow users to have a button au run "assign missing instruments from the front end")
- ... other combinations...
fixes #7162
=> [Battery] Potential improvement for battery assignment

src/Http/Error.php
=> [Core] Error page - Main page link fix

modules/api/php/endpoints/candidate/visit/instrument/flags.class.inc
There are many more that need to be fixed before the phan rule can
be enforced, but you eat an elephant one bite at a time.
1. Set `"allow_missing_properties" => false,` (is currently true) in .phan/config.php
2. Run phan and check for errors in the modified file. (There are still many from other files, but there shouldn't be any in this one.)
=> This fixes the undeclared properties identifier by phan in one file

modules/battery_manager/php/testendpoint.class.inc
This declares the properties that are undeclared in the battery_manager module.
1. Set `"allow_missing_properties" => false,` (is currently true) in .phan/config.php
2. Run phan and check for errors in the modified file. (There are still many from other files, but there shouldn't be any in this one.)
=> [battery_manager] Fix phan undeclared property errors

test/unittests/VisitTest.php
This starts fixing the errors that get identified
when you switch the "allow_missing_properties" flag
in phan. It only fixes the VisitTest unit test, but
it's a start.
The config isn't changed because there are still many
errors throughout LORIS that need to be fixed.
=> Fix PhanUndeclaredProperty errors in VisitTest

modules/dicom_archive/php/viewdetails.class.inc
Fix undeclared properties in the dicom_archive module.
1. Set `"allow_missing_properties" => false` and ensure there's no errors in the `dicom_archive` module from phan
=> [dicom_archive] Fix undeclared properties in dicom_archive

modules/datadict/jsx/dataDictIndex.js, modules/datadict/test/TestPlan.md
This PR does the following:
See TestPlan for instructions on testing the filters. Specifically steps 4 and 6.
> 4 - Check that selecting multiple instruments returns all relevant results.
> ...
> 6 - Ensure that 'Clear Filters' button works.
* Resolves #6964, #6965
=> [Data Dictionary] Change filter to multiselect + Update TestPlan

modules/api/test/login_Test.php
Fixes the PhanUndeclaredProperty errors in the API
module.
This probably should have been done in #7265, but this
fixes the rest of the module.
=> Fix PhanUndeclaredProperty Errors for API

tools/delete_candidate.php
Fixes a fatal error in tools/delete_candidate.
```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Candidate::select() must be an instance of LORIS\StudyEntities\Candidate\CandID, string given, called in /var/www/Loris/tools/delete_candidate.php on line 167 and defined in /var/www/Loris/php/libraries/Candidate.class.inc:67
```
=> [Tools] delete_candidate fix

php/libraries/NDB_BVL_Instrument.class.inc
This PR fixes the _save() method to call db update only if $values is not empty. This case pops up when you have a subtest with only static score elements. No error should be thrown so that $this->score() can eventually be called within the save() method. 
1. Mock an instrument subtest with only static score fields or test with one that you already have
2. on aces/main, click 'Save Data' on the front-end on that subtest. You will get a SQL error page.
2. on this PR branch, repeat the above, and no errors. you can add a .score file to test that the scoring still works even if no values are saved
=> [NDB_BVL_Instrument] Only update instrument table if $values not empty

modules/publication/jsx/projectFields.js
To complement #7091, an additional error introduced by #6195 is fixed by this PR, when a file previously uploaded is deleted.
- Create a publication with a file and the necessary permission to edit (LORIS Users with Edit Permission).
- Edit and delete the file.
- The file should be deleted without error
=> [Publication] File delete not working (#6195 regression)

htdocs/survey.php
1. Enable the setting in phan to detect undeclared properties and ensure it doesn't flag errors in this file.
=> Fix undeclared property in htdocs/survey.php

package.json, test/run-php-linter.sh
PHPCBF can auto-fix minor PHPCS lint issues (trailing spaces, indent spaces, short arrays notation), which can be convenient.
An es-lint auto-fixer script already exists on the js side (npm lintfix:javascript).
I extended run-php-linter.sh to automatically solve hundred of errors for a recent PR (#6786).
This PR:
- add a -f flag to `run-php-linter.sh`, to run PHPCBF in place of PHPCS with the defined rules.
- add a npm script `lintfix:php`
- make sure `npm run lintfix:php` run `PHPCBF and fixes fixable errors in php files.
- make sure run-php-linter.sh (make checkstatic) stills works as intended.
Resolves #6826
=> [Test/Tools] Option in run-php-linter.sh to auto fix PHPCS

modules/bvl_feedback/ajax/bvl_panel_ajax.php, modules/bvl_feedback/ajax/react_get_bvl_threads.php, modules/instrument_list/php/instrument_list_controlpanel.class.inc, modules/timepoint_list/php/timepoint_list.class.inc, php/libraries/BVL_Feedback_Panel.class.inc, php/libraries/NDB_BVL_Feedback.class.inc
This PR completes the work done on #7036 to solve some errors introduced by #5352 (candidate profile/instrument list)
error 500 if $_POST['sessionID'] is an empty string (react_get_bvl_threads.php)
console warning: sessionID is of type object (BVL_Feedback_Panel.class.inc)
one omitted conversion of $_POST['sessionID'] to new \SessionID($_POST['sessionID']) (bvl_panel_ajax.php)
Resolves #7139
Resolves #7017 
Resolves #6987
=> [cand. profile/instr. list] Send to DCC/BVL Feedback sessionID fixes

.phan/config.php, test/unittests/Database_Test.php, test/unittests/LorisForms_Test.php, test/unittests/NDB_BVL_FeedbackTest.php, test/unittests/NDB_BVL_Instrument_LINST_ToJSON_Test.php, test/unittests/NDB_BVL_Instrument_Test.php, test/unittests/NDB_Factory_Test.php, test/unittests/NDB_Menu_Filter_Test.php, test/unittests/SinglePointLoginTest.php
This fixes all of the "PhanUndeclaredMethod" class errors in the test directory. These are mostly caused by phan not knowing that mock objects have the methods of the class being mocked, and it needs to be specifically told so with a phan type assertion.
Calling methods that don't exist is a bad idea. We should unignore this error type, but first the errors need to be fixed. This PR starts with a large number of false positives caused by mock objects..
1. Remove "PhanUndeclaredMethod" from `.phan/config.php`.
2. Verify that there are no errors from the test directory (there are other errors from our code)
3. Check that the tests still pass. (The behaviour of them shouldn't have changed.)
=> Fix PhanUndeclaredMethod in tests directory

modules/publication/jsx/projectFields.js, modules/publication/jsx/publicationIndex.js, modules/publication/jsx/uploadForm.js, modules/publication/jsx/viewProject.js, modules/publication/jsx/viewProjectIndex.js
First attempt to clean progressively jQuery from the modules.
Replace $.ajax by fetch and $.ready by document.addEventListener('DOMContentLoaded')
Makes also use of arrow functions to avoid the use of bind(this)
* Will make a step toward #4213 resolution
* Testing requires the changes made in #7284
=> [Publication] jQuery usage cleaning

.eslintrc.json, package.json
Add new rules to eslint to flag all the jQuery usage in the modules.
Severity is error for the cleaned modules, warn for the others.
=> [Eslint] Warning/Error on jQuery usage

modules/instrument_list/README.md, modules/instrument_list/php/instrument_list.class.inc, modules/instrument_list/test/TestPlan.md
This updates the instrument_list page to use the TimePoint's
isAccessibleBy function for access checking rather than manually
doing a site comparison for more consistency across LORIS. A result
of this is that project permissions for the timepoint are now enforced
on the instrument_list page.
The "or the same site of the candidate" is removed from the README
because:
1. That doesn't make sense if they have access to a different timepoint
than the one being accessed.
2. The test plan doesn't agree and says you must have the timepoint's
visit.
=> [instrument_list] Add project permissions

jsx/Form.js, modules/dqt/jsx/react.app.js, modules/dqt/jsx/react.tabs.js
Fixes the warning in browser console:
```
Warning: Encountered two children with the same key, `demographics`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
```
also
```
react.development.js:1641 Warning: Failed prop type: The prop label is marked as required in RadioElement, but its value is undefined.
in RadioElement (created by ViewDataTabPane)
in ViewDataTabPane (created by DataQueryApp)
```
and lastly solves
```
When clicking Run Query:
react_devtools_backend.js:2273 Warning: Failed prop type: Invalid prop Data of type object supplied to StaticDataTable, expected array.
in StaticDataTable (created by ViewDataTabPane) …
```
=> [DQT beta] fix console warnings

modules/imaging_qc/php/imaging_qc.class.inc
This PR does two things:
1. Escapes field name in query
2. Only includes in the query scan_types that also appear in the MRI Parameter Form
**How to test:**
1. In `Configuration -> Imaging Modules -> Tabulated Scan Types`; add scan types that don't also appear in the MRI Parameter Form. 
2. Ensure the module will still load. 
3. Ensure that scan types not in MRI PF do not appear in the `imaging_qc` table. (EX: t1-defaced)
* Resolves #6967
=> [imaging_qc] Fix bugs in query that were leading to module not loading correctly

modules/dqt/jsx/react.tabs.js
Solves saved queries having wrong operator in list.
1. Visit DQT
2. Look at saved queries
3. The operator should be correct
=> [DQT] solves saved queries having wrong operator in list.

modules/instrument_builder/js/instrument_builder.instrument.js, php/libraries/NDB_BVL_Instrument.class.inc, php/libraries/NDB_BVL_Instrument_LINST.class.inc, raisinbread/instruments/bmi.linst, raisinbread/instruments/bmi.meta, tools/lorisform_parser.php
The `NDB_BVL_Instrument` class has supported instruments having test names different from the table names. The testname is generally used to load instruments in the front en while the table name is used to save/load data as well as the data dictionary.
These LINST tinstrument class extends the `NDB_BVL_Instrument` class but does not incorporate such functionality making it more restrictive than it's parent. This fix adds that capability while keeping the class 100% backwards compatible
This branch also adds the capacity to define if your LINST instrument should use the jsonData saving methid or the regular SQL saving.
All changes in this PR are 100% backwards compatible and futre deprecations will be done in the next major release.
- load this branch and test any existing LINST …
=> [LINST] Support for different test_name and table name

modules/dashboard/css/dashboard.css, modules/statistics/js/studyprogression.js, modules/statistics/templates/studyprogression.tpl
The PR will make the study progression legend a scrollable list and position it to the right of the graph. Also the new change allows user to click on the legend items to hide or show them on the graph. That's pretty cool imo.
Preview:
1. Use the CCNA data with lots of labels for the legend.
2. View the dashboard and visit the graph.
* Resolves #7196
=> [23.0][dashboard] Study Progression panel graphs only show data when zoomed out

modules/publication/jsx/publicationIndex.js
The publication module allows filtering hidden columns, which is confusing.
This PR makes all the filterable columns visible.
* Resolves #7209
=> [Publication] Display all filterable columns in list

php/libraries/UserPermissions.class.inc, test/LorisCS.xml
This removes the rule from PHPCS enforcing a mandatory `_` on private class properties in the php/libraries directory. Having this rule enforced prevents us from converting some of our code from PHP4 phpdoc style `@access` comments to proper php private/protected/public keywords (without updating all the code referencing the variables, which is risky since `allow_missing_properties` is true in our phan config.) It's also one of the incompatibilities between our old PEAR based php/libraries and PSR2 based src coding standards which prevents us from using the same standard throughout LORIS.
=> Remove mandatory underscore from private properties

jsx/Form.js
Solves eslint errors for react/jsx-key and useful for removing the off found in this PR: https://github.com/aces/Loris/pull/7137
=> [eslint] Missing key prop for element in iterator  react/jsx-key

php/libraries/NDB_Form.class.inc, php/libraries/NDB_Menu.class.inc
In the days of NDB_Caller there were static factory methods
on different page types which were used to load a page. After
things were turned into modules, these were replaced with directly
constructing the classes which extend NDB_Page.
Remove the unused factories that were replaced by page classes/routers.
(There are no references to them in the code, Phan doesn't raise any
PhanUndeclaredStaticMethod errors after removing them..)
=> Remove unused factories

.phan/config.php, modules/api/php/endpoints/candidate/visit/visit.class.inc, modules/api/test/login_Test.php, modules/help_editor/php/helpfile.class.inc, modules/server_processes_manager/php/abstractserverprocess.class.inc, modules/server_processes_manager/php/mriuploadserverprocess.class.inc, modules/server_processes_manager/php/process.class.inc, php/libraries/ImageQcStatus.class.inc, php/libraries/TimePointImagingQC.class.inc, php/libraries/UserPermissions.class.inc, php/libraries/Visit.class.inc, test/unittests/Database_Test.php, test/unittests/LorisForms_Test.php, test/unittests/NDB_BVL_Instrument_LINST_ToJSON_Test.php, test/unittests/NDB_BVL_Instrument_Test.php, test/unittests/SinglePointLoginTest.php
This fixes all the errors identified by phan where a property
was being assigned to an incompatible type. Most of these were
caused by assigning null to a non-nullable property, which was
fixed by declaring the property nullable.
=> Fix phan mismatched property errors

.phan/config.php
Do not ignore PhanUnusedPublicMethodParameter in the phan config.
There are no errors of this type detected by phan, so there's no
reason to ignore it.
=> phan PhanUnusedPublicMethodParameter

.phan/config.php, modules/api/php/endpoints/candidate/visit/instrument/flags.class.inc, modules/api/php/endpoints/candidate/visit/instrument/instrument.class.inc, modules/api/php/endpoints/candidate/visit/qc.class.inc, modules/candidate_parameters/ajax/getData.php, modules/create_timepoint/php/timepoint.class.inc, modules/dicom_archive/php/dicomarchiveanonymizer.class.inc, modules/document_repository/php/files.class.inc, modules/document_repository/php/uploadcategory.class.inc, modules/instrument_list/php/instrument_list_controlpanel.class.inc, modules/issue_tracker/php/attachment.class.inc, modules/media/ajax/FileUpload.php, modules/statistics/php/statistics_mri_site.class.inc, modules/statistics/php/statistics_site.class.inc, modules/statistics/php/stats_demographic.class.inc, modules/statistics/php/stats_mri.class.inc, php/libraries/CouchDB.class.inc, php/libraries/File_Upload.class.inc, php/libraries/LorisForm.class.inc, php/libraries/NDB_BVL_Instrument.class.inc, php/libraries/UserPermissions.class.inc, test/unittests/NDB_BVL_Instrument_LINST_ToJSON_Test.php, test/unittests/NDB_BVL_Instrument_Test.php
This fixes all errors from phan of type PhanTypeArraySuspiciousNullable. This catches situations where a variable or property may be null in some code paths, but the array is unconditionallly indexed as an array.
=> [phan] Fix errors of type PhanTypeArraySuspiciousNullable

modules/datadict/jsx/dataDictIndex.js, modules/publication/jsx/projectFields.js, modules/publication/jsx/publicationIndex.js, modules/publication/jsx/uploadForm.js, modules/publication/jsx/viewProject.js
Previous fetch implementations (PR #7293, #7283) were assuming a response status of 200, which will produce problems if the status is in the range [200..299]. Such status still confirms that the request ran successfully.
=> Fetch response status fix

modules/media/ajax/FileUpload.php
This is a proposed solution for https://github.com/aces/Loris/issues/7207
> uploading a big (>1024M) file and got an error message saying that there was an upload error. The message said that some of the required fields were missing even though I filled out the PSCID and VLabel.
This adds a specific error message for when the file can't be or is not uploaded.
=> [Media] Distinguish between file and other fields missing.

modules/issue_tracker/ajax/EditIssue.php, modules/issue_tracker/jsx/IssueForm.js, modules/issue_tracker/php/uploadhelper.class.inc
Fixes to address the comments on #7315
=> [Issue Tracker] Redirect and error warning fixes

jsx/DataTable.js, jsx/Filter.js, jsx/FilterableDataTable.js, jsx/Form.js
This PR updates the functionality of the Filterable datatable by changing the way that it loads filters via the URL query params. 
Instead of simply loading the query params into the filter object, upon component mount the query params will each trigger the update of the respective field they are associated with, if they exist. 
The resolves the issue #7216 which was causing filters that were meant to be exact match filters to be treated as substring, or "partial", filters.
1. Go to any module with a reactified filterable datatable.
2. Enter some filter values.
3. Refresh the page and ensure that the exact same filters are applied.
4. Do steps 2-3 with a select dropdown where the index for the value selected is a substring of other index values. (E.g. Select a subproject whose index is …
=> [filterable_datatable] Fix Query Param Filtering Bug

.phan/config.php, modules/api/test/login_Test.php, modules/candidate_list/php/validateids.class.inc, modules/dicom_archive/php/dicomarchiveanonymizer.class.inc, modules/document_repository/php/doctree.class.inc, modules/document_repository/php/uploadcategory.class.inc, modules/instrument_list/php/module.class.inc, modules/instruments/php/module.class.inc, modules/issue_tracker/php/attachment.class.inc, modules/issue_tracker/php/issuewatchermapper.class.inc, modules/media/php/hidefilefilter.class.inc, php/libraries/File_Upload.class.inc, php/libraries/NDB_BVL_Instrument.class.inc, src/Data/Filters/PhantomsFilter.php, src/Data/Filters/ScansFilter.php, src/Data/Filters/UserProjectMatch.php, src/Data/Filters/UserSiteMatch.php, src/Middleware/ETag.php, test/unittests/LorisForms_Test.php, test/unittests/NDB_BVL_Instrument_Test.php
This fixes all calls to undeclared methods caught by phan and removes the PhanUndeclaredMethod from the suppressed issue types.
The fixes are broadly classified into:
1. False positives caused by phan/phan#2628
2. False positives caused by phan/phan#2129
3. Mostly harmless positives caused by chaining withStatus on a PSR interface *after* a different call which lower the specificity from ResponseInterface to MessageInterface (because of which level of inheritance the method is defined on..)
4. Real positives
The first class of problems is fixed by putting the variable into a simple variable so that `@phan-var` annotations can be used on them to assert the type. These should eventually be removed when the above issue is solved.
The second class of problems by asserting the correct type …
=> Fix all calls to undeclared methods

php/libraries/NDB_Client.class.inc, php/libraries/NDB_Factory.class.inc, php/libraries/Settings.class.inc
This adds the ability for LORIS to get the database connection
information from environment variables prefixed by "LORIS_DB_".
This is primarily intended to make it easier to make it easier
to write a re-useable Docker image. The config.xml is normally
set up by the install.sh script with the connection info. However,
the values need to be known at the time that install.sh is run for
this to work. In the case of a Dockerfile, that needs to be known
when the image is being built. Allowing them to be overridden at runtime
allows the same docker image to be used to run multiple servers.
Note that this is only a first step. There is still a requirement to
mount a config.xml in the usual location when running a container in
order to get visit label and identifier format settings, but this …
=> Add ability to get database connection info from environment

jslib/fetchDataStream.js, src/Http/DataIteratorBinaryStream.php
Fix problems found on the datastream iterator
* the first element of the stream is always skipped
* an empty element is added at the end
To see this issue, go to /datadict/
* on the last page, notice the empty element
* compare the number of results with https://localhost/datadict/?format=json
* The iterator call next before current, causing the first element to be skipped
* the row callback is called when the last line is detected, causing the last empty line issue.
=> [Core] Datastream iterator fix

modules/api/php/models/candidatesrow.class.inc, modules/candidate_list/php/candidatelistrow.class.inc, modules/candidate_list/php/candidatelistrowprovisioner.class.inc, modules/configuration/php/project.class.inc, modules/create_timepoint/php/timepoint.class.inc, modules/electrophysiology_browser/php/electrophysiologybrowserrow.class.inc, modules/electrophysiology_browser/php/electrophysiologybrowserrowprovisioner.class.inc, modules/new_profile/php/new_profile.class.inc, modules/statistics/php/stats_behavioural.class.inc, modules/statistics/php/stats_demographic.class.inc, modules/statistics/php/stats_mri.class.inc, modules/survey_accounts/php/addsurvey.class.inc, modules/survey_accounts/php/surveyaccountsprovisioner.class.inc, modules/survey_accounts/php/surveyaccountsrow.class.inc, modules/user_accounts/php/edit_user.class.inc, modules/user_accounts/php/useraccountrow.class.inc, modules/user_accounts/php/useraccountrowprovisioner.class.inc, php/libraries/Candidate.class.inc, php/libraries/Project.class.inc, php/libraries/ProjectID.php, php/libraries/TimePoint.class.inc, php/libraries/User.class.inc, php/libraries/Utility.class.inc, src/Data/Filters/UserProjectMatch.php, test/phpunit.xml, test/unittests/CandidateTest.php, test/unittests/NDB_Factory_Test.php, test/unittests/UserTest.php, test/unittests/UtilityTest.php
This adds a ProjectID class to LORIS so that the typing
system can catch errors where the wrong type of integer
is passed.
I updated Project->getId and then updated the callsites
which were required to get `make checkstatic` to pass.
It ended up being a more significant change than expected,
but that's probably for the best.
=> Add ProjectID class to LORIS

modules/dqt/jsx/react.app.js, modules/dqt/jsx/react.sidebar.js
Solves Longitudinal bug when multiple spaces exist in visit label.
Also solves text overflow from fields. Thanks @zaliqarosli for that fix.
1. Visit DQT
2. Make a query that has spaces in visit label for query.
3. Visit the Longitudinal after query is run.
4. Rows should be populated with the data.
=> [DQT] Longitudinal bug when multiple spaces exist in visit label

.eslintrc.json, modules/candidate_list/jsx/onLoad.js, modules/candidate_list/jsx/openProfileForm.js
- Login with a user that does not have access_all_profile permission
- Go to /candidate_list/
- Open a candidate profile using the Open profile action.
Note: A second fix (L138) prevents the validation to be fired twice (and a fetch network error on the second run).
=> [Candidate list] jQuery cleanup

modules/publication/jsx/uploadForm.js, modules/publication/jsx/viewProject.js
Small changes following the comment made in #7315 
- Fix missing error message
- Fix missing swal callback change (#6195 regression) previously in #7091
=> [Publications] Error and swal fix

.phan/config.php, php/libraries/Database.class.inc, php/libraries/Visit.class.inc, test/integrationtests/BatteryLookup_Test.php, test/integrationtests/LorisIntegrationTest.class.inc, test/unittests/CandidateTest.php, test/unittests/Database_Test.php, test/unittests/LorisForms_Test.php, test/unittests/NDB_BVL_FeedbackTest.php, test/unittests/NDB_BVL_Instrument_LINST_ToJSON_Test.php, test/unittests/NDB_BVL_Instrument_Test.php, test/unittests/NDB_ConfigTest.php, test/unittests/NDB_Factory_Test.php, test/unittests/NDB_PageTest.php, test/unittests/PasswordTest.php, test/unittests/SettingsTest.php, test/unittests/SinglePointLoginTest.php, test/unittests/UserTest.php, test/unittests/UtilityTest.php, test/unittests/VisitTest.php, test/unittests/studyentities/CandID_Test.php
This fixes all the PhanTypeMismatchArguments in the tests directory. These are primarily caused by either phan not understanding that PHPUnit mocks should be compatible with the underlying type or incorrect phpdoc comment.
Mismatches outside of the test directory are not yet fixed.
1. Unignore PhanTypeMismatchArgument in `.phan/config.php` and ensure that there are no errors in the tests directory.
=> PhanTypeMismatchArgument tests

smarty/templates/404.tpl
Cleanup of error pollution of error_log when 404 on php8.
Solves the following:
```
PHP Warning:  Undefined array key "canReport"
PHP Warning:  Attempt to read property "value" on null
PHP Warning:  Undefined array key "contact"
```
1. Visit an incorrect path of Loris Ex. https://<your_sandbox>/test
2. Check error_log
=> [error_log] cleanup error pollution when 404 on php8

.github/workflows/loristest.yml
GitHub Actions appears to have started failing on `apt-get install php-ast` for an unknown reason.
This replaces the setup of php-ast with setting it up as an extension in the `setup-php` part of the GitHub Workflow to avoid needing to connect to whatever remote server is now failing/misconfigured/changed that caused `apt-get` to fail.
=> Install php-ast via setup-php

modules/candidate_parameters/ajax/formHandler.php, modules/create_timepoint/php/create_timepoint.class.inc, modules/create_timepoint/php/timepoint.class.inc, modules/examiner/php/editexaminer.class.inc, modules/instrument_list/php/instrument_list.class.inc, modules/issue_tracker/ajax/EditIssue.php, modules/issue_tracker/php/issue.class.inc, modules/issue_tracker/php/module.class.inc, modules/issue_tracker/php/uploadhelper.class.inc, modules/login/php/passwordexpiry.class.inc, modules/login/php/passwordreset.class.inc, modules/media/ajax/FileUpload.php, modules/my_preferences/php/my_preferences.class.inc, modules/new_profile/php/new_profile.class.inc, modules/statistics/php/statistics_site.class.inc, modules/statistics/php/stats_demographic.class.inc, modules/statistics/php/stats_mri.class.inc, modules/timepoint_list/php/timepoint_list.class.inc, modules/user_accounts/php/edit_user.class.inc, php/libraries/NDB_BVL_InstrumentStatus_ControlPanel.class.inc, php/libraries/NDB_Notifier.class.inc, php/libraries/NDB_Notifier_Abstract.class.inc, php/libraries/User.class.inc, src/Middleware/UserPageDecorationMiddleware.php, test/unittests/UserTest.php
The `getData` function is a code smell which we still have scattered throughout our code. It loses type information and generally makes it harder for static analysis tools (or humans) to figure out what our code is doing.
This updates most of the references to use the User class's getters for the appropriate field, which does not lose type information.
There are a couple exceptions which were not updated: 1. 2 places in the code use `getData()` to send the all the user's data to a template (`my_preferences` and `edit_user`). 2. Unit tests for the user class use it to get test the internal state. These situations need to be fixed/tested separately before the function could be completely removed.
=> Remove references to User->getData()

modules/api/php/models/candidatesrow.class.inc, modules/api/php/models/projectimagesrow.class.inc, modules/battery_manager/php/test.class.inc, modules/candidate_list/php/candidatelistrow.class.inc, modules/dicom_archive/php/dicomarchiveanonymizer.class.inc, modules/dicom_archive/php/dicomarchiverow.class.inc, modules/electrophysiology_browser/php/electrophysiologybrowserrow.class.inc, modules/imaging_browser/php/imagingbrowserrow.class.inc, modules/issue_tracker/php/issuerow.class.inc, modules/media/php/mediafile.class.inc, modules/survey_accounts/php/surveyaccountsrow.class.inc, modules/user_accounts/php/useraccountrow.class.inc, php/libraries/Candidate.class.inc, php/libraries/Site.class.inc, php/libraries/TimePoint.class.inc, php/libraries/User.class.inc, src/Data/Filters/PhantomsFilter.php, src/Data/Filters/ScansFilter.php, src/Data/Filters/UserSiteMatch.php, src/Data/Models/ImageDTO.php, src/Data/Models/RecordingDTO.php, src/StudyEntities/MultiSiteHaver.php, src/StudyEntities/SiteHaver.php
This adds 2 interfaces, SiteHaver and MultiSiteHaver to implement on classes that implement `getCenterID` and `getCenterIDs` functions respectively. This replaces the lossy method_exists checks for the 2 methods, which only verifies that a method with that name exists, and doesn't validate any type information such as arguments or return types. (In fact, it turns out there's a class in the examiners module which has an unrelated getCenterID($sitename) function, it's just luckily never passed to a pass which does a method_exists check).
This has a few benefits:
1. Static analysis tools are better able to analyze types
2. Some code can be simplified, since the types/nullability are explicit in the interface they don't need to be verified inside the method_exists checks
3. Some hacks that …
=> Add interface to replace method_exists('getCenterID') checks

php/libraries/NDB_BVL_Instrument.class.inc
Fixing undefined array key in PHP 8.
Clicking the save button in an instrument on PHP 8.
There is no error message.
=> [Instrument] fix undefined array key in PHP 8

modules/instrument_list/php/instrument_list_controlpanel.class.inc
The check for `$nextStage == 'Recycling Bin'` in the
instrument_list_controlpanel was doing an assignment,
not an equality check.
=> [instrument_list] Fix side effect in conditional

modules/api/php/endpoints/candidate/visit/dicoms.class.inc, modules/api/php/endpoints/candidate/visit/images.class.inc
The switches doing a version check for the API
were missing break statements, causing all versions
to fall through to the default and have the `$view`
variable immediately overwritten by the dev version,
for all versions of the API.
This adds a break so that the correct code is used.
=> [API] Fix v0.0.3 of API

modules/create_timepoint/php/create_timepoint.class.inc, modules/create_timepoint/php/timepoint.class.inc, modules/imaging_browser/php/imaging_session_controlpanel.class.inc, modules/imaging_browser/php/viewsession.class.inc, modules/timepoint_list/php/timepoint_list_controlpanel.class.inc, php/libraries/Candidate.class.inc, src/Middleware/AuthMiddleware.php, src/StudyEntities/Candidate/EntityType.php
This is analagous to #7334 but for `Candidate->getData`. It removes calls to `getData` in the candidate class and replaces them with appropriate getters. There are a few places where the array for getData is passed to a smarty template and some unit tests which rely on it, and these are untouched as they need more thorough testing 
This should improve the ability of phan to track our type information while it analyses the code.
=> Remove most references to Candidate->getData

modules/candidate_parameters/php/module.class.inc, php/libraries/Module.class.inc
This extracts the portion of #6936 which relates to candidate variables
in the `candidate_parameters` dictionary and puts it into a new PR
for reviewability now that the classes which it depends on have been
separately merged.
=> [candidate_parameters] Add data dictionary to candidate_parameters module

php/libraries/NDB_BVL_Instrument.class.inc, php/libraries/Utility.class.inc, tools/data_integrity/fix_candidate_age.php
Instrument Full names are no longer queried from the database `test_names` unless the instrument implements the LegacyTrait. that means that new "properly" implemented instruments should derive their full names directly from the instrument class.
The deprecated functions in this PR wrongly assume that the full name comes from the database table. the functions were deprecated to allow a sow transition to the newly created functions. The following 2 reasons explain why a deprecation was better than simply modifying the existing functions:
1. The old functions were in the Utility class which is a hodge-podge of function with no home. These functions belong more to the Instrument class in our libraries.
2. the is an added limitation to the new system of getting the instrument's full name. The …
=> [Utility] Deprecate old getInstrument functions and replace with new ones

php/libraries/NDB_BVL_Instrument.class.inc
This adds an explicit \LORIS\LorisInstance to the static functions added
in #7398. The parameter being explicit removes the implicit/hidden
global factory calls and makes the functions a little cleaner.
=> [Core] Explicitly add LorisInstance object to instrument list functions

jsx/Form.js
The value props of a fileElement can be of type string or Object, but the assignment to filename only covers the object case.
As a result, in media, if we edit a file, the fileElement does not display the file name.
This PR aims to fix this.
=> [core] fileElement multitype value fix

php/libraries/NDB_BVL_Instrument.class.inc, tools/single_use/SaveUserIDToInstrumentData.php
Currently, nothing is ever saved into the UserID field of instruments. This PR fixes that by inserting into the field the user's Real_name.
Context: Project require to render the Name of the Data Entry personnel on the instrument page on 21.0-release.
1. On main branch, go to any instrument page. Complete an instrument and save. Check the Data column of flag table and the UserID column of the instrument table. You will see that the UserID data is empty / doesn't exist. There is a UserID column of flag that has data in it, however that is specific to the session, not the instrument data entry.
2. On this PR branch, repeat the above step and notice the UserID in the instrument table will now be populated with your user account username, as well as the UserID key in the JSON data of flag …
=> [instruments] Save value into UserID field

src/Data/Filters/AccessibleResourceFilter.php
This adds a standard AccessibleResourceFilter which can be used
to filter out data for provisioners dealing with resource types
that use the AccessibleResource interface in LORIS. Any resource
which the user accessing the provisioner does not have access
to is filtered from the results.
=> Add AccessibleResourceFilter for filtering for data framework

modules/publication/ajax/FileUpload.php
This PR ensures that the creator of a publication project is added to the `publication_users_edit_perm_rel` table and given edit access to their submission.
1. Before checking out this PR, go to `Publication`
2. Create & submit a project proposal
3. Try accessing the created proposal and notice that you cannot edit the fields (other than status)
4. Checkout this PR
5. Repeat steps 1-3 and make sure that this time you can edit the fields
* Resolves #7401
=> [publication] Give publication creator edit permissions

modules/instrument_list/php/instrument_list.class.inc, modules/instrument_list/templates/menu_instrument_list.tpl
Control whether showing an imaging_browser link depending on the user permission & the status of the `imaging_browser` module.
1. Create a user without imaging_browser permission;
2. Login with the new user to verify whether the imaging_browser will be shown at the end of the instrument_list, which could be find if you click on a candidate profile -> timepoint -> visit;
3. The user without proper permission should not see the imaging_browser link;
4. Logout the new created user, login with one with the imaging_browser permission, check to make sure that the imaging_browser link is there;
5. Disable `imaging_browser` module, check again to see that the imaging_browser link is no longer displayed.
=> [instrument_list] control whether to show a imaging_browser link & active Module support

php/libraries/NDB_BVL_Instrument.class.inc
There is currently no mechanism to load the data from multiple
instrument instances at the same time efficiently and work with them
in PHP. (ie. to work the the data from multiple commentIDs for a single
instrument type in batch in a script) other than directly querying SQL.
However, this has other drawbacks such as the fact that you only know
whether the instrument data should be loaded from the flag.Data column
or a separate table once the instrument is instantiated.
This adds a bulkLoadInstanceData function which will load the data from
multiple commentIDs at the same time in a single SQL query and return an
array of \NDB_BVL_Instruments with the data loaded.
In my non-scientific benchmarking where I loaded all the data from a single
instrument type on my sandbox multiple times, and …
=> [Instrument] Add method for loading multiple instruments data at once

php/libraries/NDB_BVL_Instrument.class.inc
This PR fixes the issue reported in #7420 in which the form is frozen on first opening when the data entry is null.
1. Make sure that form is only frozen when Data entry = 'Complete'. Try use case where Data entry is `null` (first opening) and when it is `In Progress`
* Resolves #7420
=> [23.0][instrument] fix form freezing at first form opening

SQL/New_patches/2021-01-31-renaming_permissions.sql
In PR https://github.com/aces/Loris/pull/7327 the SQL patch is missing the permission table schema change before the update statements can be run.
=> [permissions] Missing schema change

.eslintrc.json, modules/media/jsx/editForm.js, modules/media/jsx/editFormIndex.js, modules/media/jsx/uploadForm.js
Additionally, this PR modifies the rules for the no-jQuery modules, by turning `no-jquery/no-other-methods` and `no-jquery/no-jquery-constructor` to warn. This is necessary as some modules still depends on jQuery libraries (bootstrap, DynamicTable).
=> [media] jQuery cleanup

php/libraries/NDB_BVL_Instrument.class.inc
See description in #7421 
This PR fixes logic so that both scoring formats are supported.
1. Check which score array format your project / raisinbread is using
2. Run `php score_instrument.php all`
3. Try implementing the opposite score array format on any instrument, make sure scoring succeeds.
* Resolves #7421
=> [23.0][instrument] Fix _nullScores() inconsistencies

modules/document_repository/jsx/docIndex.js, modules/document_repository/php/files.class.inc, tools/single_use/Cleanup_Special_Chars_Document_Repository.php
Solves an issue when if using special characters (&, <, >, ") the file download fails and the name of the file appears incorrectly in the browse tab of the document repository
1. Upload a file with special charcacters &, <, >, " into the document repository.
2. Look for the file in the file tree, check that the file name appears correctly
3. Try downloading the file and opening it.
=> [document_repository] Solves special characters issue

modules/media/ajax/FileUpload.php, modules/media/jsx/mediaIndex.js, tools/single_use/Cleanup_Special_Chars_Media.php
Solves an issue when if using special characters (&, <, >, ") the file download fails and the name of the file appears incorrectly in the browse tab of the media module.
The script removes the special characters from the sql data table media as well as from the file system.
1. Before checking out this branch, on 23.0-release, upload a file with special characters &, <, >, " into media.
2. Check that the file name appears incorrectly in the media table
3. Check out this branch.
4. Upload a different file with special characters &, <, >, " into media.
5. Look for the file in the browse tab, check that the file name appears correctly
6. Try downloading the file and opening it.
7. run (need sudo to be able to change the name of the files under /data/media_uploads/): sudo php …
=> [media] Special characters issue

jsx/Form.js, modules/issue_tracker/ajax/EditIssue.php, modules/issue_tracker/jsx/IssueForm.js
Currently, the issue tracker shows inactive users. You are able to create a new issue and assign it to them.
This PR filters out inactive users so that they don't show up in the list of assignees in the 'New Issue' form. In the 'Edit Issue' form, the inactive user appears in the list of assignees but the option is disabled. this is so that inactive users that are already assigned show up but cannot be reselected.
I thought of this fix super quickly, so am open to suggestions of perhaps better ways of doing this! I know that there are multiple modules across loris that show inactive users in a select element only because they may have been previously selected and the value cannot be orphaned.
1. Set one of your users as Inactive using the user accounts module.
2. On 23.0-release branch, …
=> [issue_tracker] Only show inactive user if already selected in form

modules/behavioural_qc/jsx/tabs_content/behaviouralFeedback.js, modules/behavioural_qc/jsx/tabs_content/dataConflicts.js, modules/behavioural_qc/jsx/tabs_content/incompleteForms.js, modules/behavioural_qc/php/behavioural.class.inc, modules/behavioural_qc/php/conflicts.class.inc, modules/behavioural_qc/php/incomplete.class.inc, modules/behavioural_qc/php/models/behaviouraldto.class.inc, modules/behavioural_qc/php/models/conflictsdto.class.inc, modules/behavioural_qc/php/models/incompletedto.class.inc, modules/behavioural_qc/php/provisioners/behaviouralprovisioner.class.inc, modules/behavioural_qc/php/provisioners/conflictsprovisioner.class.inc, modules/behavioural_qc/php/provisioners/incompleteprovisioner.class.inc, modules/behavioural_qc/php/views/behavioral.class.inc, modules/behavioural_qc/php/views/conflicts.class.inc, modules/behavioural_qc/php/views/incomplete.class.inc
This PR adds a subproject drop-down in the filters for Behavioural QC. This change was made on CCNA but should be relevant / useful to other projects as well.
1. Make sure that module loads properly
2. Make sure that all drop downs in the filters are populated with the correct options
3. Test the filters and make sure that the results are updated accordingly 
4. Make sure you can clear the filters, and the results are reset
=> [Behavioural QC] Add subproject filter

tools/exporters/data_dictionary_builder.php
- solves issue where testname was not recognized in the switch in the script. testname was introduced in this PR: #7153
1. cd /var/www/loris/tools
2. find ../project/instruments/*.class.inc | php lorisformparser.php
3. cd exporters
4. php data_dictionary_builder.php
=> [Data dictionary] Issue in builder script

smarty/templates/instrument_html.tpl
When a JSON data instrument has a score column that's saved
as 0 (the int value, not the string), the LORIS front end
does not display it, and instead displays the field as a header.
This is caused by PHP's weak equality treating `"string" == 0` as
true. Forcing the template to use a strict equality comparison
fixes this without affecting the header columns that the comparison
in the template was intended to catch.
Fixes #7441.
=> [Instruments] Fix Display of 0 scores with json data

modules/survey_accounts/php/surveyaccountsprovisioner.class.inc
Email column of participant_accounts was removed in #7248, but SurveyAccountsProvisioner is still selecting the removed column from the DB causing a 500 error. This was caught on CCNA after the 23 upgrade.
1. Navigate to survey accounts before and after this change. There should be an error before, but no error after. 
2. Make sure that you can still create a survey successfully, and use the filters successfully.
=> [survey_accounts] Remove Email column from SurveyAccountsProvisioner

modules/module_manager/jsx/modulemanager.js
This PR resolves the following issue that was being thrown on CCNA when trying to change the status of a module:
The `id` was undefined since the callback only passes 2 arguments to `toggleActive` (see https://github.com/aces/Loris/blob/main/jsx/Form.js#L521)
1. Make sure you can change the active status of a module successfully.
=> [Module Manager][Bugfix] id undefined, not passed to callback

SQL/New_patches/2021-03-15_change_parameter_file_Value_longtext.sql, SQL/Release_patches/21.0_To_22.0_upgrade.sql
Add a sql patch to change parameter_file Value to longtext for upgrade.
1. On a upgrade instance (upgraded from v21), check parameter_file table Value is text datatype ([see also 21.0_to_22.0 upgrade](https://github.com/aces/Loris/blob/11e6780c0d0e2f4e33ee915f8258f9222c314892/SQL/Release_patches/21.0_To_22.0_upgrade.sql))
2. Source mysql file on a upgrade instance (upgraded from v21)
3. Verify parameter_file table Value is longtext datatype, and your existing data is OK.
* Resolves  #7391
* Also resolves LORIS_MRI [issue# 589](https://github.com/aces/Loris-MRI/issues/589)
cc
@gdevenyi
=> change parameter_file Value to longtext

raisinbread/RB_files/RB_parameter_type.sql, raisinbread/RB_files/RB_physiological_parameter_file.sql
This adds the necessary EEG chunks path to the raisin bread database in order to be able to view the signals.
Note: the signals will be rsynced to the /data directory of raisinbread today.
* This is related to #7387
=> [raisinbread] Update RB with EEG chunks

php/libraries/AnonymousUser.class.inc, php/libraries/User.class.inc
User::factory() allows a nullable username argument. If null, the factory returns an instance of AnonymousUser and let userInfo unset. As most of User's getters rely on userInfo to return a value, such AnonymousUser's getter will return a null value, which contradicts their non-nullable type and throws an error.
This PR overrides the AnonymousUser's getters to return empty values instead of null.
* Resolves #7223
=> AnonymousUser getters override to prevent fatals

modules/api/php/endpoints/projects.class.inc
Remark: Project names are not designed to be unique in the DB. In case of duplicates, the Project factory fails [here](https://github.com/aces/Loris/blob/main/php/libraries/Project.class.inc#L64) (pselectRow used on a query that returns more than one row). (reported in #7464)
=> [API] Add support for project names with space

php/libraries/TimePoint.class.inc, php/libraries/TimePointData.php
Add a TimePointData class to act as a data transfer object for
data related to TimePoints.
A TimePointData object is a DTO (data transfer object) to
store a representation of data associated with a TimePoint
object in LORIS.
The TimePointData may be partially loaded, in which case any
getter trying to access an unknown will throw an exception.
This allows modules to only load relevant data in a query,
and avoid the overhead of the TimePoint::singleton() constructor.
For instance, a query that selected CenterID and ProjectID on
the database could instantiate a TimePoint as:
```
$visit = new TimePoint(new TimePointData(null, $projectid, $centerid));
```
with data loaded from the query, and then call
`$visit->isAccessibleBy($user)` without having to load all the
over data that …
=> [TimePoint] Add TimepointData DTO class

CHANGELOG.md, docs/instruments/NDB_BVL_Instrument_TEMPLATE.class.inc, docs/instruments/NDB_BVL_Instrument_UPLOADER_TEMPLATE.class.inc, php/libraries/NDB_BVL_Instrument.class.inc, php/libraries/NDB_BVL_Instrument_LINST.class.inc, raisinbread/instruments/NDB_BVL_Instrument_aosi.class.inc, raisinbread/instruments/NDB_BVL_Instrument_medical_history.class.inc, raisinbread/instruments/NDB_BVL_Instrument_mri_parameter_form.class.inc, raisinbread/instruments/NDB_BVL_Instrument_radiology_review.class.inc, test/unittests/NDB_BVL_Instrument_Test.php
1. Deprecation of `begintable` and `endtable` in LINST instruments. these elements do not appear to be used anywhere and when tested they only seemed to corrupt the HTML without bringing any advantages. The instrument template automatically converts groups to tables (behaviour that should be changed in the future) so removing these elements will just bring LINST to par with PHP instruments for now
2. Added a bunch of PHP docs on variables not having them
3. Deletion of the `dateTimeFields` and `monthYearFields` class arrays. Projects still maintain off and on these arrays which are unused anywhere. These arrays are being populated but their usage died with the LorisForm replacing quickform. [Here is an example of where they were used](https://github.com/aces/Loris/blob/53dd32dcb657e6f7199a …
=> Instrument class and LINST class cleanup

php/libraries/NDB_BVL_Instrument.class.inc
`clearInstrument` Function gives an error when the instrument has jsonData enabled. this fix adds support for clearInstrument by clear the data from the proper location
PS, make sure to ignore white spaces changes as most changes here are just indentation
1. use the API to save an instrument
* Resolves #7465
=> [Instrument] Add support for jsonData instrument in clearInstrument function

jsx/DataTable.js, jsx/Filter.js
When using a multiselect on a group concat set of parameters, the filters gave only perfect matches. For example, if a candidate has 2 subproject AD and MCI, setting the filter to AD will not return the candidate although it should
Issue caught after release on CCNA of v23.0.3
Also thanks @HenriRabalais for the help
=> [FilterableDataTable] Fix issue with GROUPCONCAT and multiselect

modules/imaging_browser/php/imagingbrowserrowprovisioner.class.inc
This PR fixes the issue in which the modality QC status was not being displayed in the imaging browser's data table. 
The bug resulted in queries that look like this (which returned no results):
```
...
CASE
COALESCE('`3d_t1w`.\\'3d_t1w\\'', '')
WHEN '' THEN ''
WHEN 1 THEN 'Passed'
WHEN 2 THEN 'Failed'
END as '3d_t1w_QC_Status',
...
```
Notice the parameter in the coalesce. This PR therefore fixes this issue.
1. Go to 'Imaging Browser' 
2. Check that QC status is blank before checking out this PR
3. Check out this PR
4. Refresh 
5. Check that QC Status is now populated in the data table for scans that have Failed / Passed QC
* Resolves #7468
=> [imaging_browser] Bugfix for Modality QC Status Display in Data Table

modules/api/php/endpoints/candidate/visit/instrument/instrument.class.inc, php/libraries/NDB_BVL_Instrument.class.inc
Currently the API only calls the `_save()` function which stores the data sent to it in the appropriate instrument. That workflow is not symmetrical to saving on the front end which computes the age and scores.
This PR is not making it 100% symmetrical either since validation is not being added but it gets closer to the target
1. try saving an instrument using the API and see if scoring and candidate age calculations are done
* Resolves #7460
=> [Instrument API] expand saving functionality to include Candidate age calculations and scoring

php/libraries/User.class.inc
Since group_concat limits the length of the string to 1024 characters by defaults, it becomes problematic for studies that have many sites. 
* Resolves #7480
=> [User] Remove usage of GROUP_CONCAT - based from 23.0

php/libraries/NDB_Menu_Filter.class.inc
This PR fixes a missing change from #3897 where gender was changed to sex but the substring query was not altered accordingly.
Fixes #7492
=> [Filter] Fix Menu Filter logic to recognise sex for exact match

modules/configuration/ajax/updateProject.php
This fixes the issue where a newly created project is hidden from all users including the one who created the project and all admins. 
1.  go to the config module -> "To configure study projects click here."
2. create a new project
3. make sure the user who created the project is automatically assigned the project in the user_project_rel table
* Resolves #7459
=> [Config] Assign user creating project to a newly created project

modules/help_editor/ajax/help.php, modules/help_editor/help/help_editor.md, modules/help_editor/php/edit_help_content.class.inc, php/libraries/NDB_BVL_Instrument.class.inc, raisinbread/RB_files/RB_help.sql
**Edited** 
This PR aimed to add data to the `help` table in Raisinbread so that the data would generate in the Help Editor module. This will allow the `Help Editor` module to be manually tested.
It was found that there is a bug in this module that causes it not to save/display this information. This issue is resolved in this PR. 
Here is a screenshot of the `Help Editor` module with the new data:
With a fresh RB install:
1. Navigate to `Help Editor` in the frontend and see that data loads for instructions for the BMI instrument.
* Resolves #5691
=> [Raisinbread] Fixing help_editor module to display RB instrument instructions

php/libraries/Candidate.class.inc
Currently, the default value for "Sex" when a scanner is created is NULL. This causes an error when the candidate profile is visited from the family tab (as described in issue #6990). This PR makes it so that a Sex value is not required when selecting a Candidate to accommodate these Scanner candidates.
1. Make sure that you can visit the candidate profile of a candidate with entity type `scanner`
2. Follow the procedure in the description of https://github.com/aces/loris/issues/6990 and make sure that you do not encounter the error.
* Resolves #6990
=> [Candidate] Allow null Sex for scanner candidates

modules/configuration/templates/form_configuration.tpl
When there is a value in ConfigSettings but not Config, the value does
not get saved to the database but silently discarded. This is caused by
the save logic assuming that the ID always exists to update. However,
other logic in the configuration saving deletes from the Config table
if the value is "". This means that once a config option is set to the
empty string it can never be saved again. (This can also happen for
new ConfigSettings.)
Since the name used for the text field in the HTML is the Config table ID
(which doesn't exist) and not the ConfigSetting ID to support ConfigSetting
options that allow multiple entries, the name of the ID is "0" in the form
and can not be converted to a ConfigSetting to change the statement from an
update to an insertOnDuplicateUpdate. AllowMultiple …
=> [Configuration] Fix saving of values when no previous value present

modules/genomic_browser/jsx/tabs_content/cnv.js, modules/genomic_browser/jsx/tabs_content/methylation.js, modules/genomic_browser/jsx/tabs_content/profiles.js, modules/genomic_browser/jsx/tabs_content/snp.js, modules/genomic_browser/php/cnvbrowser.class.inc, modules/genomic_browser/php/filemanager.class.inc, modules/genomic_browser/php/gwasbrowser.class.inc, modules/genomic_browser/php/methylation.class.inc, modules/genomic_browser/php/models/cnvdto.class.inc, modules/genomic_browser/php/models/filesdto.class.inc, modules/genomic_browser/php/models/methylationdto.class.inc, modules/genomic_browser/php/models/profiledto.class.inc, modules/genomic_browser/php/models/snpdto.class.inc, modules/genomic_browser/php/profiles.class.inc, modules/genomic_browser/php/provisioners/cnvprovisioner.class.inc, modules/genomic_browser/php/provisioners/filesprovisioner.class.inc, modules/genomic_browser/php/provisioners/gwasprovisioner.class.inc, modules/genomic_browser/php/provisioners/methylationprovisioner.class.inc, modules/genomic_browser/php/provisioners/profileprovisioner.class.inc, modules/genomic_browser/php/provisioners/snpprovisioner.class.inc, modules/genomic_browser/php/snpbrowser.class.inc, modules/genomic_browser/php/views/cnv.class.inc, modules/genomic_browser/php/views/methylation.class.inc, modules/genomic_browser/php/views/profiles.class.inc, modules/genomic_browser/php/views/snp.class.inc
Fixes following the reactification of the module:
- subproject filter not functional
- required getCenterID() for HasAnyPermissionOrUserSiteMatch missing
- user can see entries from projects he does not have permission for 
- move the logic of site, project and subproject options in methods in NDB_Page (see #6836)
Resolves partially #6829
=> Genomic browser post-reactification

modules/publication/ajax/getData.php
This sets the Content-Type header for the ajax responses
in the publication module. Because it's not explicitly
set, PHP is defaulting to text/html. This means that, in
the event that a user directly accesses the endpoint, the
browser will interpret the page as HTML, not JSON, and interpret
any HTML data in the object as HTML tags, opening the possibility of
an XSS attack if the an someone is tricked into accessing the
ajax endpoint directly.
The frontend isn't directly vulnerable, because the data is only
interpreted by React.
Setting the Content-Type explicitly to the correct "application/json"
means that browsers should interpret the data correctly even if
accessed directly, rather than interpretting HTML tags.
Thanks to @0xSmiley for reporting this.
=> [Publication] Set Content-Type for ajax responses

modules/publication/ajax/FileUpload.php
As it currently stands, when a publication is proposed (tab: propose a project) the user is asked, amongst other things, for a lead investigator name and email if these values are not already in the database, they get inserted into the collaborator table, if they do already exist they get linked to the new project.
The issue here is when 2 or more users share a name and/or an email address (project address like cbigr@mcin.ca for example) Since the SQL query currently uses and `OR` operator, the query returns the first name that matches or the first email that matches without checking the other value causing in some instances to select the wrong investigator and displaying the incorrect name or email in the menu filter.
Solves issue from CCNA: https://github.com/aces/CCNA/issues/4555
1. …
=> [publication] Lead investigator issue

htdocs/AjaxHelper.php, htdocs/index.php, htdocs/survey.php, php/libraries/NDB_Client.class.inc
This fixes 2 issues related to the SameSite cookie CSRF protection:
1. The session variable that indicates to use it was set to "true".
However, it should be a string indicating the value to use (either
"strict" or "lax"). See: https://www.php.net/manual/en/session.configuration.php#ini.session.cookie-samesite
2. The use_strict_mode setting (See: https://www.php.net/manual/en/session.configuration.php#ini.session.use-strict-mode)
in PHP is not enabled by default. This means that, even when logging out, the
session_destroy/session_start procedure reuses the old cookie and does not set a new cookie with
the proper samesite flag. All the PHP documentation I've seen says use_strict_mode should always
be enabled, but defaults to disabled. This explicitly overrides the php.ini setting (default …
=> [Security] Fix SameSite cookie CSRF protection

php/libraries/NDB_BVL_Instrument_LINST.class.inc
This PR fixes a PHP typing issue caused by the default values of a dateElement generated from the instrument builder
Error:
```
[php7:error] [pid 14345] [client 10.121.40.204:59323] PHP Fatal error:  Uncaught TypeError: Argument 3 passed to NDB_BVL_Instrument::addDateElement() must be of the type array, null given, called in /var/www/loris/php/libraries/NDB_BVL_Instrument_LINST.class.inc on line 620 and defined in /var/www/loris/php/libraries/NDB_BVL_Instrument.class.inc:1900\nStack trace:\n#0 /var/www/loris/php/libraries/NDB_BVL_Instrument_LINST.class.inc(620): NDB_BVL_Instrument->addDateElement('collection_date', '3. 
```
Instrument section
```
...
date{@}collection_date_date{@}3. Date of tissue collection:{@}1901{@}2100{@}
...
```
More details:
When creating a date element in the …
=> [LINST] Fixed default date field null error

tools/CouchDB_MRI_Importer.php
This PR helps resolve the issue reported in #6054, in which the argument checking for selected files was removed from the MRI importer script. This PR also adds support for the following cases: (a) multiple selected files, (b) no selected files.
The work here is taken from a previous PR (#5933), with some amendments.
1. Run the script and check DQT to make sure that the correct files and QC info was imported.
* Resolves #6054
=> [CouchDB MRI Importer] Account for selected file(s)

modules/imaging_browser/templates/table_session_header.tpl
The header table in the imaging_browser viewSession page is generated
by smarty, but the variables are not properly escaped. This adds the
`|escape` filter to all the outputs to fix reflected XSS attacks on that page.
(In particular, the outputType which comes from the URL, but all variables
are HTML escaped in this PR just to be on the safe side.)
=> [imaging_browser] Escape the header table in view session page

SQL/0000-00-05-ElectrophysiologyTables.sql, SQL/New_patches/2021-08-25-physiological_annotation_schema_changes.sql
This PR makes changes to the schema of table physiological_annotation_label to fix 2 problems:
- LabelDescription can exceed the max size of 255;
- LabelName can be non-unique if the same keyword is used for different dataset.
To manage duplicates, the UNIQUE constraint is dropped and a new column AnnotationFileID is added.
This PR makes changes to the schema of table physiological_annotation_parameter to fix:
- Author can exceed the max size of 50;
This PR adds a new table, physiological_annotation_rel, to map annotations TSV with their corresponding annotations JSON.
=> physiological_annotation_* schema changes

SQL/0000-00-00-schema.sql, SQL/9999-99-99-drop_tables.sql, SQL/New_patches/2021-06-11_exported_files_BIDS_tables.sql
This PR modifies the BIDS tables used to convert MINC datasets into BIDS datasets. In addition, it adds tables to store the path to the created files under the BIDS structure in the database so later on it can be queried via the API.
- Table modification (in green) required for the BIDS protocol identification and file naming scheme
- New tables (in green) where the converted BIDS files will be located
1. Ensure the SQL patch in the `SQL/New_patches` are correctly executing
2. Ensure the schema `SQL/0000-00-00-schema.sql` is loading properly
3. Ensure the `SQL/9999-99-99-drop_tables.sql` is properly cleaning all the BIDS tables
* Required by the changes made in https://github.com/aces/Loris-MRI/pull/636
=> add changes made to the BIDS tables for the mnc2bids conversion script

htdocs/index.php, jsx/Form.js
PR #7579 is failing on `npm run compile` even though it doesn't touch javascript. 
This PR fixes the build on the `23.0-release` branch.
=> [Ci] Fix Build on v23 branch

php/libraries/NDB_Client.class.inc
This adds to more CSP directives that are defined in CSP Level 3.
(See: https://w3c.github.io/webappsec-csp/)
`frame-ancestors: 'none'` prevents LORIS from being embedded in an
iframe. This prevents the class of attacks where a third party embeds
the page in an iframe, but covers it with an invisible div to intercept
clicks or other interactions.
`form-action: self` prevents forms from submitting data to a target that
is off-site.
1. Embed your LORIS instance in an off-site page such as
```
<html>
<body>
<iframe src="http://localhost:8000">
</body>
</html>
```
2. Access that page, you should get a security warning instead of an embedded version of your LORIS instance
=> [Security] Add 2 more Content-Security-Policy options

modules/user_accounts/php/edit_user.class.inc
Before the new user is not created, the Userid is '', so it can't insert into the "examiners" table.
remove the '' value from insert function.  
1. create a new user with an examiner and without an examiner.
[User Accounts] Unable to create new user 500 Error returned #7623
=> [User_accnout] can't create a new user

SQL/New_patches/2021-02-19_electrophysiology_annotation_tables.sql
Changed the final UPDATE statement in this [SQL patch](https://github.com/aces/Loris/blob/main/SQL/New_patches/2021-02-19_electrophysiology_annotation_tables.sql) to update based on the name in the `OutputTypeName` column rather than based on the auto-incremented ID. 
Resolves #7653
=> [SQL] Fixing incorrect update statement in EEG SQL patch

modules/bvl_feedback/test/TestPlan.md, src/Middleware/UserPageDecorationMiddleware.php
The bvl_feedback module can technically be disabled, but the pencil
icon for submitting feedback is added by middleware outside of the
module. Update the Middleware to not display bvl_feedback icon if
the module is disabled.
Resolves #7521
=> [bvl_feedback] Only show icon if module enabled

modules/create_timepoint/test/create_timepointTest.php, modules/dashboard/test/DashboardTest.php, modules/dictionary/test/datadictTest.php, modules/instrument_list/test/instrument_listTest.php
This replaces all remaining instances of $this->webDriver->findElement
with $this->safeFindElement. This is unlikely to completely fix the
random test failures, but should help with some that still have
problems.
=> [Tests] Replace webDriver->findElement with safeFindElement

php/libraries/NDB_BVL_Feedback.class.inc, src/Middleware/UserPageDecorationMiddleware.php
The middleware makes a call to NDB_BVL_Feedback::bvlFeedbackPossible
to determine whether the feedback icon should be displayed. This
function checks the test_name (based on the page passed by the middleware) and user permission to filter out who should not see the
icon. However, permission is already checked by the middleware, and
the test_name check breaks the loading of the icon for instruments
since the page passed by the middleware is the NDB_BVL_Instrument
(sub)class, not the "instruments" module.
The middleware checks for the existence of a "getFeedbackPanel"
method on the page (which is more robust, and exists on the instrument class),
so the test name check is unnecessary and only breaks instrument feedback.
The result is that the template variable can just be set to "true" if …
=> [bvl_feedback] Remove redundant bvlFeedbackPossible method

test/integrationtests/LorisIntegrationTest.class.inc
I have noticed that each random failure was showing the dashboard page instead of the one asked by safeGet. I figured that the login step was causing somewhat causing the issue. Looking at the login function, it calls click on a button which loads the dashboard page. But is safeGet is called too early than the old body is the login page instead of the dashboard page. When the login page is finally detached from the DOM, safeGet returns the dashboard page instead.
=> [Test] Integration test random failure fix test

php/libraries/NDB_BVL_Instrument.class.inc
Fix issue where multiselect value is of type string instead of array when only one value is selected
- With the addition of support for PHP8, the function `in_array(string needle, array haystack)` expects the parameter `haystack` to be of type `array`. Unlink PHP7.4, PHP8 will throw an error instead of a warning. When mapping the multiselect values from the DB, we expected the special chars `{@}` to be present in the string and only exploded the string if it was. In the case when only one value is selected the chars `{@}` aren't present and so the string is never split into an array. This would then cause the `haystack` value to be of type `string` instead of `array`. This PR removes the check for the special chars `{@}` and just always calls the explode method no matter if the `{@}` is …
=> [survey_accounts] Ensure Multiselect Value is Array

modules/next_stage/test/TestPlan.md
Updated Step 6 of the test plan to clarify that the instruments of the test_battery entry with a NULL visit label and that falls within the candidate's age should only be displayed for a timepoint if there does **not** exist other test_battery entries where the visit label is set to the visit of the timepoint. See [this section](https://github.com/aces/Loris/blob/main/modules/battery_manager/help/battery_manager.md#visitlabel) of the module help text for the behaviour expected. 
* Resolves #7641
=> [next_stage] Updated test plan for clarity

jsx/Form.js, modules/login/jsx/loginIndex.js, modules/login/jsx/requestAccount.js
Solves the incorrect order of dropdowns of select when no label is being used for login design.
* Resolves #7790
Preview of change:
=> [login/request account] Weird ordering of projects in dropdown

modules/imaging_browser/php/imaging_browser.class.inc, modules/imaging_browser/test/imaging_browserTest.php
Change the keys of the multiselect to make them match the values in the cells. It use to be `[scan_type_id => scan_type_label]` because the scan_type_id was sent to the backend to apply the filters. Now that the filtering is done in the frontend, the options needs to be `[scan_type_label => scan_type_label]`.
1. Go to `Imaging Browser`
2. Select a value in the `Sequence Type` filter
3. Notice there are now results in the data table
4. The multiselect is an OR so selecting multiple values creates an unions.
* Resolves #7563
P.S: This is changing some expected values in the tests.
- One of the tests on DCCID should check for an exact number of row that is not zero.
- The test on `Pumpernickel` project was looking for the string `20 rows` but that is just the maximum of rows displayed; not …
=> [Imaging Browser] Sequence Type filter fix

tools/assign_missing_instruments.php
1.  cd tools
2. run " php assign_missing_instruments confirm "
https://github.com/aces/Loris/issues/7797
=> [assign_missing_instruments] Error runing in confirm mode fix

php/libraries/NDB_Factory.class.inc, src/Router/BaseRouter.php
When `\NDB_Factory::singleton()->settings()->getBaseURL()` was called, an empty string was returned, so the emails sent to users when a survey is created were not displaying the correct URL. This bug fix should also solve similar errors from occurring in other modules that use the above line.
The issue occurs because the line `$DB = $factory->database()` is called in [NDB_Cient](https://github.com/aces/Loris/blob/6356a1ea5d01e719ca560695d31bcf569004f3e6/php/libraries/NDB_Client.class.inc#L59) before the baseURL for the factory object is set to the correct value in the BaseRouter using `setBaseURL`. The database() function constructs the factory's static Settings object with an empty baseURL, so the baseURL ends up being an empty string instead of the correct value. This bug is fixed by …
=> [survey_accounts] Fixed base URL not being set properly

modules/user_accounts/php/edit_user.class.inc, modules/user_accounts/templates/form_edit_user.tpl
fix the variable name
input an invalid email to create or edit a user, then the error shows on the page.
https://github.com/aces/Loris/issues/7746
)
=> [user account] fix can't show email errors

htdocs/js/jquery.dynamictable.js
The odd scrolling behaviour "bug" is from the jquery.dynamictable.js code.
Basically, the scrolling glitch happens when the static column "PatientName" is attempted to be always shown but the table width & browser width conflicts with all the other "widths" of the table columns.
This is a rare bug happening when the user's browser width including the table's columns widths are just right for the bug to happen. Furthermore, the module mri_violations hasn't been reactified and (I believe) only non-reactified tables attempt to show a static column like "PatientName" when scrolling throughout the table if the table width is too large.
My solution was to delete the code that attempts to always show the static column like "PatientName" and so the bug will never happen. The functionality that's …
=> [mri_violations] Scrolling

modules/dqt/jsx/react.fieldselector.js, tools/CouchDB_MRI_Importer.php
Downloadable files i.e. minc files are missing their download links when the 'Add All' button is used to select a query.
This PR fixes that by fixing a typo found.
This PR also fixes a typo in the CouchDB MRI import script that fails to find any scan types to import
1. On main, go to the new DQT module. Select mri_data category, filter for 'selected' string, and click on 'Add All'. Run the query and notice that the mri files appear as the correct path, but is not a downloadable link.
2. Repeat the above step, but only select one 'Selected_ ...' field without clicking on 'Add All'. Run the query and you will see that the mri files are downloadable links.
3. On this PR branch, repeat step 1 and confirm that the mri files are now downloadable links as seen in step 2.
* Resolves #  (Reference …
=> [DQT] Fix broken file link when querying using 'Add All'

php/libraries/UserPermissions.class.inc, test/unittests/UserTest.php
if set one module as "No"  in the module_manager, user account module can't edit the user ( 500 error)
module[1] = y
module[2] = n
module[3] = y
when one user has module 2 permission, it will call module[2]->getLongName function. 
1. set one module as "No" in module_manager.
2. create a new user or edit a user without 500 error.
=> [php/libraries/UserPermissions.class.inc] can't get longname

modules/electrophysiology_browser/README.md, modules/electrophysiology_browser/jsx/react-series-data-viewer/README.md, modules/electrophysiology_browser/jsx/react-series-data-viewer/src/eeglab/EEGLabSeriesProvider.tsx, modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/components/SeriesRenderer.tsx, modules/electrophysiology_browser/test/TestPlan.md
Add instructions to the test plan, solves a typo in the EEG Browser README, and a few bug fixes: 
- console error when json is null (no chunks).
- add opacity on the event bars
- fix a bug when pagination is set to NULL.
=> [EEG Browser] Typo, testplan and bugfixes.

modules/electrophysiology_browser/jsx/electrophysiologySessionView.js
This PR addresses the issue reported in #7810 
1. Go to `EEG Browser`
2. Ensure that the events panel and electrode panels are visible
* Resolves #7810
=> [EEG Browser][Bugfix] Fix Epochs and Electrodes URL Retrieval

modules/candidate_list/php/validateids.class.inc
remove the request access check. only keep the request methods validation, like other modules.
input an invalid DCCID or PSCID, then show the error message like the screenshot below.
* Resolves #  (Reference the issue this fixes, if any.
)
[candidate_list] Open Profile form gives 500 error #7612
=> [candidate list] when pscid and dccid don't match, missing error message.

php/libraries/NDB_BVL_Instrument.class.inc
This PR fixes the escaping issue that occurs when a text field in an instrument contains an HTML special character. The solution employed here is to redirect on successful save to reload data directly from the database instead of loading it using the _POST data.
Cons:
- This solution is **sub-optimal** because the escaping issue will still occur when an error is detected on instrument save and the values MUST be reloaded from the _POST array where the reload can not occur to avoid losing the unsaved data.
Pros:
- relatively minor changes
- easy to test
Alternate to: #7777
Fixes #7489
Replaces #7490
1. Go to an instrument with text element fields (not including text area element since the issue did not apply to those elements)
2. Outside of this PR, attempt to save a value in the text …
=> [Instruments] Escaping issue sub-optimal - Redirect on save success to load defaults from database

php/libraries/NDB_BVL_Instrument.class.inc
When Data column is empty (before first save) this returns `NULL` which causes an issue since this method expects a string returned
=> [NDB_BVL_Instrument] JSON Data support fix DECS field

modules/battery_manager/php/test.class.inc, modules/battery_manager/php/testendpoint.class.inc, modules/battery_manager/php/testprovisioner.class.inc, modules/issue_tracker/php/issue_tracker.class.inc, modules/issue_tracker/php/issuerow.class.inc, modules/issue_tracker/php/issuerowprovisioner.class.inc, src/LorisInstance.php
Fix issue tracker to load the correct type, as required by the
MultiSiteHaver interface that it declares itself to implement.
phan was not able to track down the type incompatibilities because
the docblock was using the less specific "array" and not the typed
"\CenterID[]" array.
Resolves #7799
=> [issue_tracker] Fix loading of page without superuser permission

php/libraries/NDB_BVL_Instrument.class.inc
Fix the warning:
```
b>Warning</b>:  Undefined array key "sessionID" in <b>/home/driusan/Code/Loris/php/libraries/NDB_BVL_Instrument.class.inc</b> on line <b>2891</b><br />
```
when an instrument is accessed without a sessionID set in the URL (such
as through the candidate profile), by using the instrument's getSessionID()
instead of trusting the request query param.
=> [instruments] Fix warning when no sessionID set

modules/issue_tracker/css/issue_tracker.css
Adds a space between the "user" in comments & history using css.
2. Visit issue tracker module
3. See if there's a space before and after user.
* Resolves #7800
=> [Issue tracker] No space before user in Comments & History

SQL/0000-00-03-ConfigTables.sql
The parent should be referred to by name, not a hardcoded ID.
Resolves #7691
=> [SQL] Remove hardcoded configID 26 from schema

jsx/CSSGrid.js, jsx/Card.js, jsx/Panel.js, modules/candidate_profile/templates/form_candidate_profile.tpl
Past discussion came to conclusion of removing minimizing from cards displayed at candidate_profile.
1. Checkout PR
2. Visit Access Profile (Beta)
3. Visit a candidate and the cards should not be able to be minimized.
=> [Access Profile (Beta)] remove Minimizing boxes

jsx/Form.js, modules/login/jsx/requestAccount.js, modules/login/php/signup.class.inc
Created an EmailElement that uses type="email" (see [here for specs](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email)). The user's browser will prevent the form being completed if the user has not entered a valid email when type="email".
2. Request account with invalid email
* Resolves #7827
=> [User Accounts] Users request are allowed to be created with "incorrect" email address via "user request" UI

php/libraries/NDB_BVL_Instrument.class.inc
This PR adds an empty value to the array of examiner names. This was mistakenly taken out in #7462, and is causing the first value to be selected by default in instruments.
1. Check that there is an empty option in the examiner drop down of instruments, and make sure that no value is selected by default.
=> [NDB_BVL_Instrument] Add null value to examiner array

php/libraries/LorisFormDictionaryImpl.class.inc, php/libraries/NDB_BVL_Instrument.class.inc, php/libraries/NDB_BVL_Instrument_LINST.class.inc, test/unittests/NDB_BVL_Instrument_Test.php
Fix a couple instances where the Instrument class does not support JSONData instruments by either looking for a specific field in the not-yet-populated instrument data object or using the `$this->table` variable
Testing
1. choose a JSONData=true instrument (you can turn `false` into `true` in the `bmi.meta` file for an easy instruement)
2. set he `Data` column to `NULL` directly in the flag table in the database
3. try entering the "Date of Administration" and other required fields on the top page and save.
Without this PR the save will fail claiming the `Date_taken` field does not exist in the instrument. With this PR, issue should be solved
=> [NDB_BVL_Instrument] fix support for JSONData instruments

modules/user_accounts/php/useraccountrow.class.inc, modules/user_accounts/php/useraccountrowprovisioner.class.inc
Fix access to the user accounts module when the user has only the
"own site" permission. The user_accounts module was returning
strings of CenterIDs instead of objects, this updates it to return
CenterID objects.
Resolves #7642
Replaces/Closes #7764
=> [user_accounts] Fix Access when only own site permission is set

SQL/0000-00-01-Modules.sql
This removes the `dataquery` module from the `modules` database table. Note: there is already a [patch](https://github.com/aces/Loris/blob/main/SQL/New_patches/2021-09-07_dqt_drop_old_dataquery.sql) taking care of that but the default schema was not up to date.
Note: RB `modules` table does not contain `dataquery` so no need to update RB data here.
=> Remove dataquery from the modules table in the default schema

modules/user_accounts/php/edit_user.class.inc, modules/user_accounts/templates/form_edit_user.tpl
Updates the logic for `Account Request Date` to always be displayed. Unsure if we want to hide it for administrators. @ridz1208 ?
1. See issue.
* Resolves #7912
=> [user_accounts] Random "none" on the page when adding new user

modules/dqt/php/dqt.class.inc
Removes an old reference that somehow wasn't caught in previous merged PR. Note: We're getting the removed include from node_modules/package.json.
=> [dqt] critical fix remove old dataquery include

php/libraries/NDB_BVL_Instrument_LINST.class.inc
XIN rules always required Standard Date elements to be completed, even when user tries to override rules from the `.rules` file. The bug is caused by the stripping of the `_date` suffix for datefields (the suffix is later added in the Instrument class to make LINST and PHP instruments compatible) which means the incorrect question name was being passed to validation without the `_date` suffix.
This PR moves the addition of the question to the validated array to BEFORE the `_date` is stripped
1. create or use an existing instrument having a standard date field
2. load the instrument for a candidate and try to save it without any data in the date field (the form should return an error as all fields are required by default)
3. add a rule to the `.rules` file for the linst instrument to make …
=> [LINST] Fix standard dates always required bug

modules/user_accounts/templates/form_edit_user.tpl
I was getting tired of chrome autofilling the password field when editing a user in the user accounts module. I followed the instructions [here](https://stackoverflow.com/questions/12374442/chrome-ignores-autocomplete-off) to get rid of that and it seems to work
Issue:
Using chrome, if you have a password saved for user **X** on the loris instance you are using and you navigate to the user_accounts module and edit user **X**, Chrome decides to autofill the "password" field (I think simply because it's called password). If you are not mindful of the autofill and try to modify some permission of other parameter and hit save you get an error (see images)
Autofill on page load:
Error after saving without clearing the password field:
This PR should simply prevent chrome from being annoying …
=> [user_accounts] Prevent password autofill in chrome when editing or creating an account

tools/data_integrity/score_instrument.php, tools/single_use/instrument_double_escape_report.php
strftime() missing a parameter. 
strftime and gmstrftime functions will are deprecated on php 8.1
remove deprecated functions
run this file under tools folder
"php tools/data_integrity/score_instrument.php"
=> [tools] fix strftime

modules/create_timepoint/jsx/createTimepointIndex.js, modules/create_timepoint/php/timepoint.class.inc, php/libraries/Utility.class.inc
This PR fixes a few long-standing issues exacerbated by the addition of user-multisites and user-multiprojects. Below is the list of changes:
- Cleanup of code duplication and inefficiencies
- Reorganization of the fields in a more logical order on the front end
- conditional display of options based on previous selections
- swal prompts when study configurations are missing preventing the creation of a timepoint
* Resolves #7602
=> [create_timepoint] Code refactor to display proper select options based on previous selections

modules/imaging_browser/jsx/ImagePanel.js, modules/imaging_browser/php/viewsession.class.inc, modules/imaging_browser/templates/form_viewSession.tpl
This updates the imaging browser to use the "thumbnail"
API which is specifically defined for that purpose. It
also updates the "Download Minc" button to use the API.
=> [imaging_browser] Use API for thumbnail and download

modules/conflict_resolver/jsx/resolved_filterabledatatable.js, modules/conflict_resolver/jsx/unresolved_filterabledatatable.js, modules/conflict_resolver/test/conflict_resolverTest.php
Bar graph in candidate profile widget will now link to the conflict_resolver module correctly and where the filters of the conflict_resolver will be correctly displayed for the user.
See issue for testing instructions.
* Resolves #7703
=> [conflict_resolver] Bar graph in candidate profile widget not working correctly

modules/document_repository/README.md, raisinbread/RB_files/RB_notification_modules_perm_rel.sql
Change necessary permissions to document_repository_view only in order to be able to toggle the doc repo notification settings in "my preferences"
Add info to the readme to know where the notification permission control can be found
1.
* Resolves #7867
=> [document_repository] simplify notification permission restrictions to view only

modules/document_repository/jsx/docIndex.js, modules/document_repository/php/doctree.class.inc, modules/document_repository/php/edit.class.inc, modules/document_repository/php/files.class.inc, modules/document_repository/php/module.class.inc
There are 2 changes made in this PR. 
1. Users with the document repository edit/upload permission but no view/delete permissions can access the document repository module
2. Users without edit/upload permission cannot access the edit and upload pages of the module. The `Edit` button and `Upload` tab are not visible for users without the edit/upload permission.
To test module access:
1. Give a non-superuser only the Document Repository Edit/Upload permission
2. Log in as this user and see that the document repository is accessible 
To test edit/upload permissions:
1. Give a non-superuser the Document Repository View or Delete permissions
2. Log in as this user and see that the `Upload` tab is not visible or accessible
3. Navigate to a file in the document tree and see that it cannot be …
=> [document_repository] Edit/Upload permissions fixes

SQL/0000-00-03-ConfigTables.sql, SQL/Cleanup_patches/2021-11-17-noextlibs.sql, php/libraries/NDB_Client.class.inc
This removes the extLibs path from the database. The config
setting was at one point used to locate the system version
of smarty, but this has not been the case since composer was
used to manage external libraries in January 2015.
Now it's just an arbitrary setting in the config module
with the value "PATH/TO/EXTERNAL/LIBRARY/" which has no impact
other than adding "PATH/TO/EXTERNAL/LIBRARY/" to the include
path (which is also unused, since classes are autoloaded.)
=> [Config] Remove unused extLibs setting from DB

modules/imaging_browser/jsx/ImagePanel.js
This removes the couple references to jQuery in the imaging_browser
so that the errors:
```
/home/runner/work/Loris/Loris/modules/imaging_browser/jsx/ImagePanel.js
26:5  warning  The jQuery constructor is not allowed  no-jquery/no-jquery-constructor
26:5  warning  .tooltip is not allowed                no-jquery/no-other-methods
126:5  warning  The jQuery constructor is not allowed  no-jquery/no-jquery-constructor
126:5  warning  .DynamicTable is not allowed           no-jquery/no-other-methods
134:5  warning  The jQuery constructor is not allowed  no-jquery/no-jquery-constructor
134:5  warning  .DynamicTable is not allowed           no-jquery/no-other-methods
```
are not displayed. The first error was a call to ".tooltip" which was
unnecessary. The value of the tooltip is the same as the …
=> [imaging_browser] Remove jQuery from imaging browser

modules/api/php/endpoints/candidate/visit/visit.class.inc, modules/api/php/endpoints/candidate/visit/visit_0_0_4_dev.class.inc, modules/create_timepoint/php/timepoint.class.inc, php/libraries/TimePoint.class.inc
Create timepoint logic now uses a combination of project/subproject to validate the visit label selected (and displayed). in this case the validation code needs to be passed the projectID to do the validation.
1. try creating a timepoint
* Resolves #7959
=> [create_timepoint] Require project for validation

CHANGELOG.md, SQL/0000-00-03-ConfigTables.sql, SQL/New_patches/2022-01-26-S3Support.sql, composer.json, composer.lock, htdocs/index.php, modules/api/php/endpoints/candidate/visit/image/format/thumbnail.class.inc, modules/api/php/endpoints/candidate/visit/image/image.class.inc, php/libraries/Image.class.inc, php/libraries/NDB_Client.class.inc
This adds support for accessing files via S3 to LORIS. The AWS SDK is used so that `s3://` URLs can be accessed as normal files within PHP if the environment variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` are set (which roughly correspond to AWS username and passport). One of the LORIS config settings `AWS_S3_Region` or `AWS_S3_Endpoint` must be set for the SDK to work (the latter for AWS hosted instances, and the latter for self-hosted.)
In this PR the LORIS API for imaging is updated (for both thumbnails and the mnc files). The imaging_browser and brainbrowser have already been updated to use the LORIS API, so should work transparently.
Other modules that deal with files (document_repository, media, issue_tracker, etc) will need to be tested separately. (The most likely cause …
=> Add S3 Support to LORIS

SQL/Archive/24.0/Cleanup/2022-02-03-remove_CenterName_from_mri_protocol.sql, SQL/Archive/24.0/Cleanup/2022-02-03-remove_password_expiry_from_users.sql, SQL/Release_patches/23.0_To_24.0_upgrade.sql
Some `DROP table` statements were inserted into the release patch and should be removed to avoid the deletion of tables with potential data if projects already had those table set up.
=> Remove drop table statements that should not be in the release patch for 24.0

tools/single_use/Set_Required_elements_completed_flag.php
This PR fixes a bug where the Set_Required_elements_completed_flag.php script was using the test_name where it should have been using the table name.
1. Test the script with an instrument whose table name is different than the test_name
=> [Tools] use table name in Set_Required_elements_completed_flag.php

modules/create_timepoint/php/timepoint.class.inc, modules/create_timepoint/test/TestPlan.md, php/libraries/Utility.class.inc, php/libraries/VisitController.class.inc
Visit ID was accidentally being submitted at timepoint creation instead of visit name. This fixes that issue and corrects the documentation in the Utility class.
1. Create a new timepoint for any candidate and make sure the value inserted into the session table is the visitName, (Not vistID nor visit label, see `visit` table in the DB for distinction)
* Resolves #7998, #7960  (Reference the issue this fixes, if any.)
=> [create_timepoint] Use visit name for session table insert

SQL/0000-00-00-schema.sql, SQL/Archive/24.0/2019-07-01_fix_project_in_session.sql, SQL/Release_patches/23.0_To_24.0_upgrade.sql
Making the projectID field in the session table not nullable and prefilling all currently null fields with the candidate's Registration project.
=> [SQL] Make projectID NOT NULL in session table

modules/dqt/php/dqt_setup.class.inc
This fixes an issue where the DQT crashes if the last update time
is not set. The key indexed from PHP is not set, causing it to print
a warning resulting in invalid JSON being returned to the browser.
This can happen if, for instance, CouchDB_Import_Demographics is
run for testing without the other import scripts (the last update
time is only set by the instruments import script.)
=> [DQT] Fix crash when last update time is not set.

SQL/Archive/24.0/2019-07-01_fix_project_in_session.sql, SQL/Release_patches/23.0_To_24.0_upgrade.sql
Make MariaDB happy by dropping foreign key contraints before modifying the ProjectId fields to `NOT NULL`. otherwise MariaDB throws an error
=> [SQL] Drop foreign keys before making ProjectID not nullable

modules/create_timepoint/php/timepoint.class.inc, php/libraries/TimePoint.class.inc
This addresses the issue where duplicate visit labels were being created. 
This is yet another patch to fix the ID vs NAME vs LABEL confusion that is happening since the reactification of create_timepoiint without the normalization. this should all become much cleaner in the next release
=> [create_timepoint] validate on visit label not ID

php/libraries/LorisFormDictionaryImpl.class.inc
The LorisFormDictionaryImpl trait for instruments was using the `$this->lorisinstance` variable which happens to be null in survey instruments, replaced with `$this->loris` instanciated in the constructor of NDB_Page and now it works
* Resolves #8021 and #8020
=> [survey] Fix saving functionality using LorisFormDictionaryImpl trait

modules/statistics/templates/table_statistics.tpl, php/libraries/Utility.class.inc
`math` function in smarty seems to be broken (deprecated?). I replaced it with direct math as supported in smarty 3
1. make sure the percentages show up as indicated in the issue linked below
* Resolves #8027
=> [statistics] recover percentage values

jsx/Form.js, modules/login/jsx/requestAccount.js
Updates the email component to use the pattern property for the email input. Also using the type property for the message to displayed to the user when email isn't matching the pattern property. See here: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/email
edit: I added frontend logic for if by any chance the php validation finds an error not caught by the frontend and so the user will get a notification that email is invalid.
1. Checkout PR
2. Attempt request account with bad email ex. "bad@email"
3. User should not be able to use bad email.
* Resolves #7897
=> [Login] Request account with bad email UI seems to work

modules/media/ajax/FileUpload.php, modules/media/jsx/uploadForm.js
Made the upload file process better.
1. Checkout PR
2. Upload file
3. Observe if user experience is okay.
* Resolves #5055
=> [Media] Content does not update after a new file is uploaded

SQL/0000-00-05-ElectrophysiologyTables.sql, SQL/New_patches/2022-02-03-physiological_annotation_parameter_fix_description_default.sql
The `Description` field of the annotation.json sidecar is recommended but not required. 
Ran into this issue with the bids_import:
```
Traceback (most recent call last):
File "/opt/eegnet/bin/mri/python/bids_import.py", line 464, in <module>
main()
File "/opt/eegnet/bin/mri/python/bids_import.py", line 76, in main
read_and_insert_bids(bids_dir, config_file, verbose, createcand, createvisit)
File "/opt/eegnet/bin/mri/python/bids_import.py", line 230, in read_and_insert_bids
loris_bids_root_dir    = loris_bids_root_dir
File "/opt/eegnet/bin/mri/python/lib/eeg.py", line 155, in __init__
self.register_data()
File "/opt/eegnet/bin/mri/python/lib/eeg.py", line 284, in register_data
derivatives
File "/opt/eegnet/bin/mri/python/lib/eeg.py", line 757, in fetch_and_insert_annotation_files …
```
=> [EEG] Modify physiological_annotation_parameter `Description` datatype

modules/next_stage/help/next_stage.md
This PR adds help text for users in the frontend of the next stage module
1. Create a new timepoint for a candidate and go to the next stage page
2. Click on the `?` icon and see help text
* Resolves #7871
=> [next_stage] Help text for next_stage module

modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/components/SeriesRenderer.tsx
Epochs should not be highlighted (in blue) in the Signal Viewer unless they are marked as visible using the eye button. This PR fixes bug where all epochs were being shown.
This fix was done by @laemtl on iEEG ATLAS, just pushing it to LORIS
**What it should look like (notice the eye button on first 3 epochs):**
**What it looks like currently (notice no epochs are marked as visible):**
1. Go EEG Browser
2. Notice that the signal viewer highlights all epochs before checking this PR out (second screenshot)
3. Checkout this PR, notice the behaviour from first screenshot
=> [EEG Broswer] Bugfix for Filtered Epochs

CHANGELOG.md, modules/candidate_profile/templates/form_candidate_profile.tpl
This PR changes the candidate_profile template that loads the widgets of the candidate_profile page so that it catches the errors when loading candidate visit information. Specifically, this handles the issue where a candidate is affiliated with multiple sites and the user only has access to one of those sites and the candidate_profile page does not load. 
1. Create a user with `access_all_profiles` permission and only give them permission for one site
2. Find a candidate that has some of its visits at the site your user is affiliated with and some of its visits at other sites your user should not have permission for
3. Go to the candidate_profile page of this candidate
4. See that the page loads correctly
5. See that the list of visits does not include any of the visits that your user …
=> [candidate_profile] Error handling when loading widgets

modules/media/php/mediafileprovisioner.class.inc
This adds a static variable in the getInstance function of the provisioner to load each instrument only once instead of for each rows.
1. Access `/media`
2. Check if datatable loads. (There should be no timeout)
Resolves https://github.com/aces/Loris/issues/8033
=> [media] Caching instrument names

composer.lock
This manually updates guzzle to 1.8.5 in order to fix the tests that
are failing in the automatic upgrade to 1.8.4 from #8076.
Replaces #8076.
=> Manually update Guzzle

modules/timepoint_list/templates/menu_timepoint_list.tpl
This updates the error message when attempting to access a candidate for which the user doesn't have permission to access any timepoints.
The previous message claimed that there was no timepoints registered, which was not the case if the list is empty for permission related reasons.
=> [timepoint_list] Update error message when no access to timepoints

modules/timepoint_list/php/timepoint_list.class.inc
Do not filter the sites in the timepoint_list page if the
user has the access_all_profiles permission since the permission
says it gives access to all profiles *and* visits.
=> Do not filter sites with access_all_profiles permission

php/libraries/NDB_BVL_Instrument_LINST.class.inc
This PR cherry picks a few key bugfixes already merged into 24 back into the 23 branch for projects not looking to upgrade immediately and are using LINST
1. Print out (debugging) showing up on the front end of instruments: https://github.com/aces/Loris/commit/a6e1744bc642a0413d2e27bd10f832ee32f4da3e#diff-1d18bbc27ba2cabe74bdf1a067307ce735f0f84fd29c735010eb122abc370c14L843
2. Date elements are always required even when a rule is explicitly added to make them not required: https://github.com/aces/Loris/pull/7925/files#diff-1d18bbc27ba2cabe74bdf1a067307ce735f0f84fd29c735010eb122abc370c14R660
3. The `multiple` parameter should be passed as an array, not a string: https://github.com/aces/Loris/commit/137f1fb5fa19d8934a2d80c340477e1e1b9bee90#diff-1d18bbc27ba2cabe74bdf1a067307ce735f0f84fd29c7350 …
=> [LINST/Instruments] Backporting fixes from 24 + group errors

php/libraries/Utility.class.inc, test/unittests/UtilityTest.php
Comment in Utility Class
>      * @note    Function comment written by Dave, not the author of this function.
>      *       The return value format seems weird. Should possibly be refactored.
>      * @note    Used in:
>      *      - behavioural_qc/php/NDB_Form_behavioural_qc.class.inc
>      *      - behavioural_qc/ajax/GetInstruments.php
>      * @cleanup
I should mention that the files mentioned in the comment no longer exist and as far as I can tell there are no other uses of this function in the code base.
1. Use the utility somewhere and make sure the output is in the form of an array: `[$Test_name => $Full_name]`
=> [Utility] Refactor getVisitInstruments function

docs/wiki/00_SERVER_INSTALL_AND_CONFIGURATION/01_LORIS_Install/Ubuntu/README.md
While testing the install, I noticed the order in the installation instructions were off. Should first create the `lorisadmin` user and `/var/www/loris` and then download the source code to move it to `/var/www/loris`.
Also, NPM is missing in the prerequisites.
=> Update install order and add npm dependency to the list of dependencies

src/Log/ErrorLogLogger.php
PHP Fatal error:  Declaration of LORIS\\Log\\ErrorLogLogger::log($level, $message, array $context = []) must be compatible with Psr\\Log\\LoggerTrait::log($level, Stringable|string $message, array $context = []): void in /var/www/Loris/src/Log/ErrorLogLogger.php on line 65
Testing instructions (if applicable)
install Loris 24.1-release
Test Enviorment:
Ubuntu:22
php 8.1
npm -v 8.12.1
node v14.19.3
Composer version 2.3.7
=> [installation] fix bug on Loris 24.1-release

readthedocs/requirements.txt
A new version of the "jinja" package is causing the Read the Docs build to fail, so the Read the Docs page cannot be updated to the latest version of the documentation. This PR adds a line to the `readthedocs/requirements.txt` file specifying the version of jinja to use that will not cause errors in the build.
Testing:
This change has been tested on my forked version of the Loris Read the docs and correctly builds the latest (24.0) version of the documentation
=> [Readthedocs] Updating requirements file to fix RTD build

php/libraries/LorisFormDictionaryImpl.class.inc
This PR fixes getDataDictionary() that doesn't support the 'file' type (which is getting called indirectly while saveValues() calls getCandidateAge()).
=> fixes getDataDictionary() not support the 'file' type

tools/generic_includes.php
`tools/generic_includes.php` missed the #8074 refactoring boat where all `Database::singleton` have been replaced by `NDB_Factory::singleton()->database()`
This fixes the `generic_includes.php` file to use the new way of loading the DB object.
=> Fix broken tool's generic_includes.php 

modules/dataquery/jsx/react.fieldselector.js, tools/exporters/data_dictionary_builder.php
This PR is 2 parts:
1. backporting fix for the display of the dictionary in the DQT module (#7098)
2. in the data_dictionary_builder script, reference the `tesname` value in parsed instruments (lorisform parser output format) instead of `table` while keeping it backwards compatible. This is needed because JSONdata instruments do not define a `table` variable and since [23.0.3] (https://github.com/aces/Loris/pull/7153/files#diff-962394c093e5275dcfa7cc6eca8927b2f8f592f42b7b95ec5921cb7fc0dc8453R88) the lorisform parser exports the test name in its output for this specific reason.
=> [DQT] v23 - Fix dictionary builder and dictionary display issues

modules/login/php/requestaccount.class.inc, modules/user_accounts/php/edit_user.class.inc
The issue came up when registering a user using the User Accounts -> add user functionality. If you select the "Make user name match email address" checkbox and your email address contains HTML special characters, you end up with a 500 error.
The email address failing here is: `test@gmail.com>` This address does not pass `FILTER_VALIDATE_EMAIL` check but because of the sanitization step removed in this PR, the email actually being validated is `test@gmail.com` which is valid.
This PR also removes an old check for < > and " because the new check offers a clearer error message and covers a broader range of characters we don't want in emails (because of escaping issues)
=> [user_accounts] Revert #2018 - Sanitization before validation of email falsifies validity

modules/user_accounts/jsx/userAccountsIndex.js, modules/user_accounts/php/useraccountrowprovisioner.class.inc
Although this usecase should never happen as it is prevented by rules in the edit_user logic, a couple bugs have let it happen in the pass and the entire module becomes inaccessible. This makes the module load and displays a message in the user row informing the editor that the user does not currently have any sites and projects.
The only way to test this would be to manually delete all site associations directly in the DB `user_psc_rel` OR all project associations `user_project_rel`
Note that the module crashes even if the user not having any sites or projects is not the editor nor the editee... any user can cause this issue
=> [user_accounts] Prevent crash when one user has no site/project affiliations

raisinbread/RB_files/RB_physiological_event_file.sql, raisinbread/RB_files/RB_physiological_task_event.sql, raisinbread/test/api/LorisApiRecordingsTest.php, test/dockerized-unit-tests.sh
fix gitactions frozen.
clean up - [EEG] Database Architecture for HED Tags #8036
modify - [RaisinBread] add physiological_* data for integration test
skip RecordingsTest (rewrite in the future)
pass git action test
=> [RaisinBread] main branch - fix gitactions frozen - add physiological_* data for integration test

jsx/Form.js
This removes the regex pattern from the "email" type. It currently
breaks on addresses that have a "+" in them and is difficult to debug.
(The regex looks like it should work, but it doesn't and is very complicated.)
This only potentially impacts browsers that *do* support "pattern" but
*don't* support the "email" data type. Otherwise, the browser's built in
validation will check the validity of the email address. In the case where
neither is supported, the browser will submit and fall back to server side
validation.
The [internet](https://www.html5pattern.com/Emails) suggests using "pattern" to validate email addresses is a bad idea because it's difficult to get right.
I've tested this on the request accounts page, and frontend validation still works
in Firefox, while if I change the …
=> Remove pattern from email validation

tools/CouchDB_Confirm_Integrity.php
1. Delete a session in SQL DB that has data associated with it i.e. instrument data
2. On main branch, run `php tools/CouchDB_Confirm_Integrity.php`. Go to the DQT, run a query with instrument data fields and notice that your deleted session data is still there.
3. On this PR branch, run `php tools/CouchDB_Confirm_Integrity.php` again. In the script output, you should see a print out that flags the deleted session. Go to the DQT, using the same query as you used above, notice that your deleted session data is no longer there.
=> [tools/CouchDB_Confirm_Integrity] Add case where VL doesn't exist in SQLDB

docs/wiki/00_SERVER_INSTALL_AND_CONFIGURATION/01_LORIS_Install/Troubleshooting.md
* Updated the Installation troubleshooting guide's admin section
*  Step by step instruction to deal with a deactivated admin account due to inactivity 
* Resolves #7974
=> [Docs] Update Troubleshooting Documentation for expired lorisadmin account 

htdocs/css/c3.css, modules/statistics/css/recruitment.css, modules/statistics/js/studyprogression.js
* Added total scan and recruitment data in their respective chart visualisations
* Added total calculation
* Updated related CSS
* Updated scale of chart appropriately
* Minor Spelling mistake fixes
1. Check the dashboards for Study Progression Data
* Resolves #8122 
Here's how the changes look:
=> [dashboard][Study Progression] Add tooltip visualising of Total in line chart

modules/api/docs/LorisRESTAPI_v0.0.4-dev.md, modules/api/php/endpoints/candidates.class.inc, modules/api/static/schema-v0.0.4-dev.yml
This adds the ability to use PSCID instead of CandID in the URL for
the v0.0.4-dev version of the API. All endpoints under /candidates/{candID} should now accept /candidates/{PSCID} instead, as long as there's one single unique PSCID with that identifier.
This was requested by the HBCD project, but after talking to @ridz1208 is a common request for many projects, so I've added the functionality to v0.0.4-dev of the API.
=> Add the ability to use PSCID in place of CandID in the candidates API.

CHANGELOG.md, modules/mri_violations/php/mri_protocol_violations.class.inc
This adds the `image_type`, `PhaseEncodingDirection` and `EchoNumber` to the tables displayed under the page displayed after clicking on "Could not identify scan type" link in the main page.
1. check out this branch
2. go to the MRI violation module and click on one of the "Could not identify scan type" link present in the violation table. That will redirect you to the page with the list of MRI protocol and list of fields for the violated scans. Ensure that there are `image_type`, `PhaseEncodingDirection` and `EchoNumber` (note: sometimes those fields will be empty if there is not restriction on the `mri_protocol` table for those fields or if the violated scan does not contain a `PhaseEncodingDirection` or multiple `EchoNumber`
Note: make sure to run the SQL patches that affect the MRI …
=> [mri_violations] Add new mri_protocol fields to "Could not identify scan type" page

smarty/templates/instrument_html.tpl, smarty/templates/time_element.tpl
This PR fixes the display of time fields in instrument tables to be inline (hours at the left of minutes) instead of vertical (hours on top of minutes) AND fixes the loading of stored time values in the database when the time entry contains leading zeros i.e. `05:05:00`
More info on time data loading: When we were using SQL data saving, SQL seems to have been fixing our time fields by adding a leading 0 to the hours or minutes that were <10 so even when the code was sending `5:5:00`, SQL was converting it to `05:05:00`. Since we started using JSONdata instruments, this correction has not been happening and any time value saved without correction CAN NOT be reloaded when the instrument is reloaded thus magically erasing data.
=> [Instruments] Fix display and loading of time elements

CHANGELOG.md, modules/imaging_uploader/jsx/LogPanel.js
This fixes the imaging uploader so that when clicking on an upload row, the row is highlighted and the proper log is being displayed in the log viewer. 
Currently on demo that is on 24.0-release:
On sandbox after the fix:
1. On raisin bread, branch 24.0-release or latest bug fix release for 24.0, click on any row in the Upload table and notice that it is always the UploadID of the first row that is being shown in the log viewer
2. Check out this branch, run make dev and notice that clicking on different rows will bring up the information in the log viewer with the correct UploadID (the one showed in the selected row)
* Resolves #8153
=> 2022 08 22 bug fix imaging uploader 24.0

CHANGELOG.md, modules/imaging_browser/jsx/ImagePanel.js
This modifies the image panel of the imaging browser to get rid of the weird dangling SNR label when no SNR value is associated to the file.
1. On branch 24.0-release or latest bug fix release for 24.0, check that the SNR label is always there whether there is actually an SNR value to be displayed or not
2. On this branch, check that the SNR label shows only for images that have SNR values associated to them
* Resolves https://github.com/aces/HBCD/issues/228
=> Remove dangling SNR from the image panel in the imaging browser when SNR is not available for the image

modules/instrument_manager/php/instrument_manager.class.inc
The function signature for Database->connect was updated in #8083, but a call in the instrument_manager was missed.
This updates the call to pass the credentials with the new signature which doesn't include username/password in the stack trace.
Resolves #8182
=> [instrument_manager] Fix page load

package.json, webpack.config.js
Update dependencies for webpack, webpack-cli, and terser-webpack-plugin. Latest nodejs removed openssl causing error when trying to build Loris. Solution to upgrade dependencies. Changes are backwards compatible with current Loris supported version of nodejs.
Solves error:
````
webpack
node:internal/crypto/hash:71
this[kHandle] = new _Hash(algorithm, xofLen);
Error: error:0308010C:digital envelope routines::unsupported
...
````
1. git checkout pr
2. make clean
3. make dev
4. upgrade to latest nodejs example 18.10.0 nodejs.org/en/
5. make clean
6. make dev
=> [webpack] Update dependencies for latest nodejs (openssl unsupported)

modules/candidate_list/jsx/candidateListIndex.js, modules/candidate_list/php/candidatelistrowprovisioner.class.inc, modules/candidate_list/test/TestPlan.md, modules/candidate_list/test/candidate_listTest.php
The max alphabetical visit doesn't mean anything. (See resolved issues for explanation.)
Resolves #5115, #7093
=> [candidate_list] Remove meaningless Latest_Visit_Status column

webpack.config.js
Developers can now compile a single module individually with npm.
Example 1: `target=dqt npm run compile` will only compile the dqt module.
Example 2: `target=create_timepoint npm run compile` will only compile the create_timepoint module.
Example 3: `npm run compile` will compile all modules.
Anyone have a particular dislike about this method or suggestion?
=> [webpack] target=module_name npm run compile

tools/generic_includes.php
`tools/generic_includes.php` missed the https://github.com/aces/Loris/pull/8074 refactoring boat in 24.1 where all `Database::singleton` have been replaced by `NDB_Factory::singleton()->database()`
This fixes the `generic_includes.php` file to use the new way of loading the DB object for branch 24.1-release.
=> fix generic_includes for 24.1

Makefile
The `make clean` command should remove the `node_modules` and `package-lock.json` files from the electrophysiology_browser module. I modified Makefile to include the cleanup task of those files.
1. checkout pr
2. run `make clean`
=> [Makefile] improve the "make clean" command

babel.config.js, package.json
The plugin @babel/plugin-proposal-object-rest-spread is unnecessary to install/include inside babel.config.js because the plugin is included in @babel/preset-env, in [ES2018]. See https://babeljs.io/docs/en/babel-plugin-proposal-object-rest-spread
1. checkout PR
2. make clean
3. make dev
=> [package.json] remove unnecessary plugin

modules/dashboard/php/dashboard.class.inc
The FIXME comment in the dashboard class is no longer accurate.
There is a LorisInstance passed as a function argument, so use it instead of the static call from the modules class.
=> [dashboard] Use proper getActiveModules in dashboard

jsx/Breadcrumbs.js
This makes it possible for javascript modules to update the breadcrumbs dynamically and add an onClick handler to individual crumbs by doing something like:
```
const breadcrumbs = [
{
text: 'Item1',
onClick: (e) => {
e.preventDefault();
console.log('Clicked breadcrumb 1');
},
},
{
text: 'Item2',
onClick: (e) => {
e.preventDefault();
console.log('Clicked breadcrumb 2');
},
}
];
ReactDOM.render(
<Breadcrumbs
breadcrumbs={breadcrumbs}
baseURL={loris.BaseURL}
/>,
document.getElementById('breadcrumbs')
);
```
=> [Breadcrumbs] Added onClick handler to breadcrumbs

htdocs/AjaxHelper.php, modules/candidate_list/php/candidate_list.class.inc, modules/candidate_parameters/ajax/getData.php, modules/candidate_profile/php/candidate_profile.class.inc, modules/candidate_profile/php/module.class.inc, modules/dashboard/php/dashboard.class.inc, modules/dashboard/php/module.class.inc, modules/help_editor/ajax/help.php, modules/issue_tracker/php/edit.class.inc, modules/issue_tracker/php/issue_tracker.class.inc, modules/issue_tracker/php/issuerowprovisioner.class.inc, modules/module_manager/php/module_manager.class.inc, modules/module_manager/php/modulemanagerprovisioner.class.inc, modules/module_manager/php/modulerow.class.inc, modules/user_accounts/php/edit_user.class.inc, php/libraries/Module.class.inc, php/libraries/NDB_BVL_Instrument.class.inc, php/libraries/NullModule.class.inc, php/libraries/UserPermissions.class.inc, src/LorisInstance.php, src/Middleware/PageDecorationMiddleware.php, src/Router/BaseRouter.php, test/unittests/NDB_PageTest.php, test/unittests/UserTest.php
There was a static getActiveModules function in the module class
as well as a getActiveModules function in the LorisInstance class.
This removes the duplicate and unnecessary function, cleaning up the
references to the non-static version now that NDB_Page has a LorisInstance
object passed in the constructor and all references should be able to use
the non-static version.
=> [Core] Remove duplicated getActiveModules function

jsx/Form.js
Input elements should not require a min and a max. They may not be required (or known) and aren't necessary for the underlying <input type="number"> element.
=> [Form.js] No required min/max for numeric elements

jsx/Form.js
when the label is empty for some elements, it still includes a col-sm-3 element which offsets the element and no way to suppress it. Other elements do not include the 3 column space for the label when there is no label provided. This causes our elements to look weird and inconsistent when used in places that we just want the element (ie. in a flexbox row.)
This fixes the
- DateElement
- TimeElement
- NumericElement
- FileElement
So that there is no space left for the label if the label is not provided.
=> Fix sizing of form elements when there is no label

docs/wiki/01_STUDY_PARAMETERS_SETUP/01_Study_Variables/01_Identifiers.md, docs/wiki/99_Developers/Help_Style_Guide.md, docs/wiki/99_Developers/LORIS-REST-API-0.0.3-dev.md, docs/wiki/99_Developers/LORIS-REST-API-0.0.4-dev.md, readthedocs/mkdocs.yml
Small formatting changes to a few of the markdowns so that they appear correctly in Read the docs. Updated the `mkdocs.yml` file to point to the correct document links. Updated the API documentation symlink `docs/wiki/99_Developers/LORIS-REST-API-0.0.3-dev.md` to point to the updated v0.0.4 version. Not shown here but multiple wiki links were updated to point to RTD.
Checkout this branch on your fork and test how it appears on RTD. Please check that all the links are pointing to the correct document and that all formatting changes are appearing correctly. See [this document](https://docs.google.com/document/d/19JAcogjb9mam6goD3p0KhgGIWq_G1KxXUc37mwAeqTU/edit?usp=sharing) for more information on setting up RTD and testing.
=> [Documentation] Small formatting fixes for ReadTheDocs

jsx/InfoPanel.js
This adds an InfoPanel component to show a message to the user in a box that's styled to draw their attention. The "alert alert-info" bootstrap classes weren't working for me with our current stylesheet, so the InfoPanel wraps around what's needed to make it look reasonable and uses a FontAwesome icon to mark it as an information panel.
Usage:
```
<InfoPanel>
Message that should go in the panel, can include arbitrary other react or html if you want.
</InfoPanel>
```
It looks like this
=> [JSX] Add InfoPanel component

.github/workflows/loristest.yml, php/libraries/Candidate.class.inc, php/libraries/CandidateData.class.inc, test/unittests/CandidateTest.php
This adds a CandidateData DTO object which mirrors the TimepointData which already exists. It is the Candidate equivalent of PR#7432.
A CandidateData object is a DTO (data transfer object) to
store a representation of data associated with a Candidate
object in LORIS.
The CandidateData may be partially loaded, in which case any
getter trying to access an unknown will throw an exception.
This allows modules to only load relevant data in a query,
and avoid the overhead of the Candidate::singleton() constructor.
=> [Candidate DTO] Add CandidateData DTO object

SQL/Archive/24.1/2022-08-10-add_PhaseEncodingDirection_and_EchoNumber_to_files_and_mri_qc_tables.sql, SQL/Release_patches/24.0_To_24.1_upgrade.sql
An error was reported where the query being modified returns an SQL error because of the missing `FROM` clause on mariaDB 10.3
This fix was taken from the MAriaDB official documentation to fix the issue https://mariadb.com/kb/en/dual/
=> [SQL] Make release patch compatible with mariadb 10.3

php/libraries/Module.class.inc, src/Router/BaseRouter.php
This is an attempt to solve the speed issues with demo-24.loris.ca.
In LORIS 23, there was no LORISInstance object that was used for getting active modules, nor was there a logger instantiated from the constructor. The added overhead of retrieving the log settings for every module instantiation and LorisInstance->getActiveModules instantiating every module is adding up to a lot of overhead in the critical path on demo-24.loris.ca.
This moves the logger instantiation to be done after the Module::factory call in the router instead of in the constructor. The result is that it's only done once, instead of done n times (where n is the number of modules.)
This doesn't get demo-24.loris.ca up to the speed of demo.loris.ca, but it's significantly closer.
It's not clear why this performance …
=> [Performance] Do not load module logger from constructor

modules/electrophysiology_browser/jsx/electrophysiologySessionView.js, modules/electrophysiology_browser/jsx/react-series-data-viewer/src/eeglab/EEGLabSeriesProvider.tsx, modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/store/types.tsx, modules/electrophysiology_browser/php/models/electrophysioannotations.class.inc, modules/electrophysiology_browser/php/sessions.class.inc, modules/electrophysiology_browser/test/electrophysiologyBrowserTest.php
=> [EEG Browser] Add ability to view annotations in event panel and overlaid on signal viewer

Dockerfile.test.php7.debug, Dockerfile.test.php8, Dockerfile.test.php8.debug, docker-compose.yml
PHP does not install libzip anymore, resulting in a error when running `npm run tests:integration`
```
configure: error: Package requirements (libzip >= 0.11 libzip != 1.3.1 libzip != 1.7.0) were not met:
No package 'libzip' found
```
Upgrade Dockerfile php image to 8.1 to fix
```
Fatal error: Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". You are running 8.0.25. in /app/vendor/composer/platform_check.php on line 24
```
=> [Tests] php install failure (Docker)

modules/electrophysiology_browser/css/electrophysiology_browser.css, modules/electrophysiology_browser/jsx/components/DownloadPanel.js, modules/electrophysiology_browser/jsx/electrophysiologySessionView.js, modules/electrophysiology_browser/jsx/react-series-data-viewer/src/eeglab/EEGLabSeriesProvider.tsx, modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/components/AnnotationForm.tsx, modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/components/EventManager.tsx, modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/components/Form.js, modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/components/IntervalSelect.tsx, modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/components/SeriesCursor.tsx, modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/components/SeriesRenderer.tsx, modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/store/index.tsx, modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/store/state/currentAnnotation.tsx, modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/store/types.tsx, modules/electrophysiology_browser/php/annotations.class.inc, modules/electrophysiology_browser/php/models/electrophysioannotations.class.inc, modules/electrophysiology_browser/php/models/electrophysioevents.class.inc, modules/electrophysiology_browser/php/sessions.class.inc
=> [EEG Browser] Annotations: Add new and HED tags

CHANGELOG.md, modules/statistics/php/charts.class.inc
This PR uses the user sites instead of a full site list in the visualizations of statistics displayed on the dashboard. 
1. Test the dashboard charts with a user who only has access to some but not all sites
2. Make sure that the numbers are correct
3. Repeat steps 1 and 2 but with a user who has all sites
4. Repeat steps 1 and 2 but with a user who has the "all sites" permission
=> [dashboard] Use user site permissions for dashboard charts

modules/behavioural_qc/php/models/behaviouraldto.class.inc, modules/behavioural_qc/php/models/conflictsdto.class.inc, modules/behavioural_qc/php/models/incompletedto.class.inc
fixes 
```
<b>Fatal error</b>:  Uncaught TypeError: ValidatableIdentifier::__construct(): Argument #1 ($value) must be of type string, int given, called in /var/www/loris/modules/behavioural_qc/php/models/incompletedto.class.inc on line 126
```
Testing: Module currently doesnt load, it should load
=> [behavioural_qc] Fix critical error

htdocs/survey.php, modules/imaging_browser/php/feedback_mri_popup.class.inc, modules/imaging_browser/php/imaging_session_controlpanel.class.inc, modules/imaging_browser/php/viewsession.class.inc, modules/instrument_list/php/instrument_list_controlpanel.class.inc, modules/statistics/php/stats_demographic.class.inc, modules/statistics/php/stats_mri.class.inc, modules/timepoint_list/php/timepoint_list_controlpanel.class.inc, src/Http/Error.php, src/Middleware/AnonymousPageDecorationMiddleware.php, src/Middleware/UserPageDecorationMiddleware.php
For some reason, the class `Smarty_NeuroDB` in `Smarty_hook.class.inc` is being called in other scripts as `Smarty_neurodb`. The non-matching case returned the following error:
```
Fatal error: Uncaught Error: Class "Smarty_neurodb" not found in /Users/cmadjar/Development/Github/Loris/src/Http/Error.php:84 Stack trace: #0 /Users/cmadjar/Development/Github/Loris/src/Router/PrefixRouter.php(102): LORIS\Http\Error->__construct(Object(Laminas\Diactoros\ServerRequest), 404) #1 /Users/cmadjar/Development/Github/Loris/php/libraries/Module.class.inc(336): LORIS\Router\PrefixRouter->handle(Object(Laminas\Diactoros\ServerRequest)) #2 /Users/cmadjar/Development/Github/Loris/src/Middleware/ResponseGenerator.php(50): Module->handle(Object(Laminas\Diactoros\ServerRequest)) #3 …
```
=> Replace all `Smarty_neurodb` occurrences in the code with correct name of the class `Smarty_NeuroDB`

modules/issue_tracker/php/edit.class.inc
When people are added to the watchers list, they do not receive a notification email upon creation/update of the issue. This fixes the bug and allows notification to be sent to watchers when an issue is created/updated.
This resolves #8004
=> [issue tracker] Email watchers when issue is updated or created

.eslintignore
Removal of `modules/*/js/*/*` because it's redundant since `modules/*/js/*` prevents git adding additional directories that may contain files as well.
=> [eslintignore] cleanup of redundancy

CHANGELOG.md, src/Data/Query/Criteria.php, src/Data/Query/Criteria/EndsWith.php, src/Data/Query/Criteria/Equal.php, src/Data/Query/Criteria/GreaterThan.php, src/Data/Query/Criteria/GreaterThanOrEqual.php, src/Data/Query/Criteria/In.php, src/Data/Query/Criteria/IsNull.php, src/Data/Query/Criteria/LessThan.php, src/Data/Query/Criteria/LessThanOrEqual.php, src/Data/Query/Criteria/NotEqual.php, src/Data/Query/Criteria/NotNull.php, src/Data/Query/Criteria/StartsWith.php, src/Data/Query/Criteria/Substring.php, src/Data/Query/QueryEngine.php, src/Data/Query/QueryTerm.php
This defines the QueryEngine interface that I've been using to build a new, CouchDB-free DQT as well as used to create a new candidates module. It's stable enough that I'm confident it will require little modification now.
```
/**
* A QueryEngine is an entity which represents a set of data and
* the ability to query against them.
*
* Queries are divided into 2 phases, filtering the data down to
* a set of CandIDs, and retrieving the data for a known set of
* CandID/SessionIDs.
*
* There is usually one query engine per module that deals with
* candidate data.
*/
```
After this is merged, the QueryEngine()->getDataDictionary() for a module will replace the getDataDictionary() method that currently exists and I'll begin sending individual engines as they're completed and well tested. (I …
=> QueryEngine interface

tools/data_integrity/data_deletion/delete_candidate.php, tools/data_integrity/data_deletion/delete_ignored_conflicts.php, tools/data_integrity/data_deletion/delete_physiological_file.php, tools/data_integrity/data_deletion/delete_timepoint.php
- Script to delete all the files/db entries created by an eeg file ingestion.
Usage: php delete_physiological_file.php [PID] confirm|tosql
Split files not supported at the moment.
- Move deletion tools into data_integrity/data_deletion
=> [Tools] delete physiological files

webpack.config.js
To prevent a compilation error when protobuf is not installed, we check if the compiled protobuf file exists to turn 'ON' the visualization. Fix a bug that turns 'OFF' the viz when the EEG Browser is overridden in project/
=> [Webpack] Viz status check fix

Makefile, modules/login/jsx/loginIndex.js, modules/login/jsx/requestAccount.js
This makes it possible to link to the Request Account page by making it possible to set a default mode in the login module via the page=?? query param. It also makes it possible to set the firstname, lastname, or email address by passing them as query params.
This is useful for authentication workflows (such as OpenID Connect) that might want to direct the user to sign up for an account and pre-populate it with known values
=> [login] Make it possible to set default page and values via query params

modules/candidate_list/README.md, modules/candidate_list/test/TestPlan.md
- updates the language of the test plan, particularly the naming of certain elements on the candidate list page. 
- removes items 4 and 6, which seem to be left over from before the Reactification of the module, and re-enumerates the list.
- removes item 17 because PSCID links are now always clickable, regardless of permission. this is because the workflow for using the 'Open Profile' form was changed. The form was previously used when the PSCID was not clickable. Now, the form is used only to access restricted candidates (from a site with which you are not affiliated)
- clarifies useEDC section
- corrects permission and  use of Open Profile form. I believe this workflow was changed to only be used to view a restricted candidate when the user does not have access to all candidates. The …
=> [candidate_list] Update test plan, README

npm-postinstall.js, package.json, webpack.config.js
Following a discussion with @regisoc,
this script defines a set of paths where a package.json with additional dependencies can potentially exists.
This script is executed with npm install (postinstall step).
This fixes several issues:
- allow automated installation of /project additional npm dependencies;
- allow to automatically detect if a path is inside modules and overridden in project, and amend the path with project/
Potential improvements: Migrating the [EEG Browser install step](https://github.com/aces/Loris/tree/main/modules/electrophysiology_browser#-installation-requirements-to-use-the-visualization-features) in this script with a config Enable_EEGBrowser_visualization set to yes/no.
=> npm postinstall script

modules/instrument_builder/jsx/react.questions.js, modules/instrument_builder/test/TestPlan.md
…t Builder
* Added field warnings for length for `_status` fields: 
* Added field warnings for length for all the fields
* Minor spelling mistake fix
1. Go to /instrument_builder/#Build 
2. Check for warnings for input length greater than 57 for the following fields by clicking Add Row 
1. Data entry->Textbox->Question Name
2. Data entry->Textarea->Question Name
3. Data entry->Date->Question Name
4. Data entry->Numeric->Question Name
3. Check for warnings for input length greater than 64 for the rest of the Question Name and Question Text fields by clicking Add Row
* Resolves #7582
=> [instrument_builder] ADDED: field warnings for maximum length in Instrument Builder module

docs/wiki/00_SERVER_INSTALL_AND_CONFIGURATION/01_LORIS_Install/CentOS/README.md, docs/wiki/00_SERVER_INSTALL_AND_CONFIGURATION/01_LORIS_Install/Ubuntu/README.md
- Modified the instructions to include the correct PHP library versions required for both Ubuntu and CentOS.
- Added the missing variable assignment to the section titled: 'Creating the lorisadmin user'.
- Changed an argument of the chown command in 'Creating the lorisadmin user' to prevent unwanted side-effects of creating a user with a period in its name.
Resolves #8220
=> [Docs - LORIS installation] Updated installation instructions to reflect the requirement of PHP 8.0+

.github/workflows/loristest.yml, composer.lock, docs/wiki/00_SERVER_INSTALL_AND_CONFIGURATION/01_LORIS_Install/CentOS/README.md, docs/wiki/00_SERVER_INSTALL_AND_CONFIGURATION/01_LORIS_Install/Ubuntu/README.md, modules/api/php/endpoints/candidate/visit/image/format/raw.class.inc, modules/help_editor/php/edit_help_content.class.inc, php/installer/Database.class.inc, php/libraries/Module.class.inc, shell.nix
Update packages that were failing `composer install`, fix deprecated dynamic property warning from NDB_Page by only setting $cls->menu after checking if it exists. (It exists on NDB_Menu subclasses but not all NDB_Pages.)
I clicked around a few pages to make sure that LORIS works, but didn't thoroughly test it with PHP 8.2. So far it seems to have been much less painful than 8.0->8.1 and I haven't encountered anything that can't be fixed in a bugfix release.
=> Add PHP 8.2 support to main branch, drop 8.0 support

CHANGELOG.md, modules/bvl_feedback/php/module.class.inc
This PR changes the getWidget code so that a user only sees behavioural feedback notifications relevant to their own sites (unless they have the access all sites permission) / projects.
1. Login with a user who only has some sites / projects but not all
2. Check that the bvl feedback widget on the dashboard only includes notifications for that users sites / projects
3. Give the user the access_all_profiles permission, and check that the notifications no longer have the site restriction
=> [bvl_feedback][dashboard] Add project/site specs to widget

modules/instrument_builder/test/TestPlan.md
This is a Test Plan updates for the Instrument Builder module after changes introduced by  PR #8112
- [x ] Have you updated related documentation?
1. The Test Plan now should reflect the changes introduced by the PR #8112 addressing the issue #7582
* Resolves #8257
=> [instrument_builder] Updates Test Plan according to changes introduced by PR#8112.

modules/mri_violations/test/mri_violationsTest.php, php/libraries/NDB_Client.class.inc
This adds a session_write_close() call to the end of NDB_Client,
after the last reference to $_SESSION has been made. This causes
PHP to release the lock it holds on the session file which prevents
further incoming requests from being handled. After this point in
NDB_Client all of our session related state should be read from
the PSR request, not the superglobal.
PHP by default holds a lock on the session until it is closed in case
there is a write to the superglobal. However, this prevents other
requests from the same session from reading the variable (which
is where our login state is stored) until the end of the request,
when the lock is released. Closing it explicitly releases the lock
and allows us to handle multiple requests from the same user in parallel
instead of in series.
=> [Core] Allow parallel handling of requests from same session

modules/issue_tracker/php/issuerowprovisioner.class.inc, modules/module_manager/php/modulerow.class.inc, php/libraries/NDB_BVL_Instrument.class.inc, src/LorisInstance.php, src/Router/BaseRouter.php
LorisInstance already has functions to check if a module exists, get the module directories, etc.
This adds a getModule to replace \Module::factory() so that the code dealing with modules can be centralized in one place.
=> [LorisInstance] add getModule function

modules/dataquery/static/schema.yml
This defines the schema I've been using to design a QueryEngine (rather than CouchDB) based data query tool.
The meaning of the 3 types of queries in the /queries endpoints are:
1. `recent`: There are no more "saved queries". Instead, all recent queries are "saved" and can be reloaded. Users can star or name a query in order to indicate that they're important queries that shouldn't be purged and duplicate the functionality of the old saved queries. (Currently, no queries are ever purged, but if we do change that in the future, starred ones are the equivalent of saved ones.)
2. `shared`: Shared queries, similar to existing shared queries. These queries are public for everyone.
3. `topqueries`: Admin queries that were pinned to the top of the DQT. Similar to shared queries, but pinned by an …
=> [dataquery] Define new swagger schema for data query API

modules/api/php/endpoints/candidates.class.inc, php/libraries/Candidate.class.inc
(Rebase of #8267 for 24.1)
When using `/api/v0.0.3/candidates` with an invalid date format, returns 400 Bad Requests/JSON errors.
This PR checks the date of birth and returns the correct format in the message ('yyyy-mm-dd').
1. Log into to get a token:
```bash
curl -v -k -X 'POST' \
'https://<hostname>/api/v0.0.3/login' \
-H 'accept: application/json' \
-H 'Content-Type: application/json' \
-d '{
"username": "<username>",
"password": "<password>"
}'
```
2. Test for `/api/v0.0.3/candidates` endpoint:
```bash
curl -v -k -X POST 'https://<hostname>/api/v0.0.3/candidates' \
-H "Authorization: Bearer <token>" \
-d '{
"Candidate": {
"Project": "Rye",
"Site": "Montreal",
"DoB": "<a_date>",
"Sex": "Female"
}
}'
```
* #8127
=> [core] return error message on invalid dob (rebase 24.1)

modules/create_timepoint/jsx/createTimepointIndex.js, modules/create_timepoint/php/timepoint.class.inc, modules/create_timepoint/test/TestPlan.md
In this PR, the language drop down for timepoints is only contains a null option when creating a new timepoint if there are more than one languages to choose from in the language table. Otherwise the field automatically selected. 
1. Check that exactly one language exists in the language table
2. Create a new timepoint
3. Make sure that the language drop down does not contain a null option & that you are successfully able to create the timepoint with the one option automatically selected
4. Add a language to the language table to have 2 or more
5. Create another timepoint and make sure that the language drop down is displayed with a null option
6. Check that the language field is required in this case, and that you can not save without it
7. If the language selection is made, make sure …
=> [new_timepoint] only show null language option when multiple exist

modules/candidate_list/php/candidate_list.class.inc, modules/candidate_profile/php/candidate_profile.class.inc, modules/candidate_profile/php/module.class.inc, modules/create_timepoint/php/timepoint.class.inc, modules/dashboard/php/module.class.inc, modules/datadict/php/datadict.class.inc, modules/dictionary/php/dictionary.class.inc, modules/dictionary/php/fields.class.inc, modules/dictionary/php/module.class.inc, modules/dictionary/php/moduledict.class.inc, modules/issue_tracker/php/issue_tracker.class.inc, modules/issue_tracker/php/issuerowprovisioner.class.inc, modules/media/php/media.class.inc, modules/media/php/mediafileprovisioner.class.inc, modules/module_manager/php/module_manager.class.inc, modules/module_manager/php/modulemanagerprovisioner.class.inc, modules/module_manager/php/modulerow.class.inc, modules/user_accounts/php/edit_user.class.inc, php/libraries/LegacyInstrumentTrait.class.inc, php/libraries/LorisFormDictionaryImpl.class.inc, php/libraries/Module.class.inc, php/libraries/NDB_Page.class.inc, src/Router/BaseRouter.php
This removes the duplicate references to the LorisInstance object in NDB_Page and harmonizes them to all use $this->loris, which is set from the constructor.
Resolves #8049
=> [Core] Replace all $this->lorisinstance with $this->loris

npm-postinstall.js, webpack.config.js
Address an issue that prevents webpack and the post-install script to run when patch SQL/New_patches/2022-12-05-AddVizConfig.sql is not applied.
Now the errors are caught and a warning is printed on the screen.
=> [Webpack] Compilation error fix

modules/candidate_parameters/jsx/ConsentStatus.js
fixes https://github.com/aces/Loris/issues/6993
fixes https://github.com/aces/Loris/issues/6102
1.
=> [candidate_parameters] Add date restriction for consent withdrawal

.github/workflows/loristest.yml, modules/server_processes_manager/test/server_processes_managerTest.php, test/dockerized-integration-tests.sh
Split the integration tests methods in roughly 4 equal datasets.
Execution time decreased from 45min to 20min.
=> Parallelize integration tests

modules/candidate_list/jsx/candidateListIndex.js
Fix Typo 'VisitCount' to 'Visit Count', VisitCount should have a space in the middle
#7609 
1.
=> [candidate_list] Fix Typo 'VisitCount' to 'Visit Count' 

php/libraries/NDB_BVL_Instrument.class.inc
An incorrect error message was displayed on the frontend when a user did not have the permission to access an instrument.
The code was test looping on ALL permissions, but it failed when trying to do so on only ONE permission (the loop went through the instrument name and permission instead of the actual instruments objects). 
This PR fix the error message linked to permission listing. 
1. Add a new user
2. Give the user permissions through the `db` and `config.xml` file except one permission on one instrument (e.g. instrument "bmi", permission "data_entry")
3. Enter the permission selected in 2. in the config.xml file (`instrumentPermissions` section)
4. Go to Loris > Menu > Candidate > Access Profile
5. Choose one PSCID (candidate) then one associated visit (visit label)
6. In the …
=> [core] Fix incorrect message/error for instrument access

modules/issue_tracker/jsx/IssueForm.js
The issue description is currently rendered in a static text field, while comments (or the description in the comments) are rendered as markdown. This updates the description to be wrapped in a `<Markdown>` tag so that it gets consistently rendered.
=> [issue tracker] Fix issue description

php/libraries/NDB_Client.class.inc
Strict is too strict, while "Lax" still provides SameSite protection.
The differences are well summarized in the graphic in this Stack Overflow post https://stackoverflow.com/questions/59990864/what-is-the-difference-between-samesite-lax-and-samesite-strict
There are some situations blocked by "Strict" that we want to support for our session cookies. Currently, opening a link from an email sent by LORIS logs you out, or opening a tab from the browser dev tools. Strict would also prevent us from using OAuth or other third party authentication providers in the future (such as in PR#8255)
=> [Core] Change SameSite cookie policy from strict to Lax

tools/CouchDB_MRI_Importer.php
Fixes
```
php CouchDB_Import_MRI.php
PHP Fatal error:  Uncaught TypeError: join(): Argument #2 ($array) must be of type ?array, string given in /var/www/loris/tools/CouchDB_MRI_Importer.php:446
Stack trace:
#0 /var/www/loris/tools/CouchDB_MRI_Importer.php(446): join()
#1 /var/www/loris/tools/CouchDB_MRI_Importer.php(78): CouchDBMRIImporter->updateCandidateDocs()
#2 /var/www/loris/tools/CouchDB_MRI_Importer.php(781): CouchDBMRIImporter->run()
#3 /var/www/loris/tools/CouchDB_Import_MRI.php(19): require_once('/var/www/loris/...')
#4 {main}
thrown in /var/www/loris/tools/CouchDB_MRI_Importer.php on line 446
```
=> Fix CouchDB_MRI_Importer.php for php8

htdocs/mri/jiv/get_file.php, modules/electrophysiology_browser/jsx/components/DownloadPanel.js, modules/electrophysiology_browser/jsx/electrophysiologySessionView.js, modules/electrophysiology_browser/php/models/electrophysioannotations.class.inc, modules/electrophysiology_browser/php/sessions.class.inc
Fix a few issues with EEGLAB set/fdt files:
- Download link broken
- incorrect placement, it should be logically after the .set file
Download `All files` fails when no annotations exists. 
Migrate the annotation files creation logic from `update` to `updateFiles`, since `update` handles DB updates only.
=> [EEG Browser] Fix Download broken links

Makefile, package.json, webpack.config.js
Prevent ESLint to be run when make is run (prod instances) vs make dev (dev instance).
make steps order were switched to solve a bug with `make clean && make` (thanks to @maltheism amazing testing skills). The post-install node script runs a tool that requires autoload.php to be generated so composer needs to be run first.
=> [ESLint] Disable on prod instances

php/libraries/TimePoint.class.inc
Updates the return type of getScreeningStatus() to allow null values.
See:
https://github.com/aces/Loris/blob/9860f7f4bba8d70f29936594b8372f45c71b6050/php/libraries/TimePoint.class.inc#L774
https://github.com/aces/Loris/blob/main/SQL/0000-00-00-schema.sql#L194
Fixes #7282
=> Fix TimePoint getScreeningStatus return type

modules/issue_tracker/php/edit.class.inc
The logic to send emails to watchers and assignee was off. Watchers ended up receiving emails that an issue was assigned to them even though it was not. With this bug fix:
- an "issue assigned" email is sent to new assignees
- a 'issue changed' email is sent to watchers
=> [issue tracker] Fix emailing bug found in HBCD

php/libraries/NDB_BVL_Instrument.class.inc
=> [NDB_BVL_Instrument] Add get function to access protected selectMultipleElements

SQL/New_patches/2022-12-01-subprojects_no_more.sql
This fixes the revert section of the `SQL/New_patches/2022-12-01-subprojects_no_more.sql` patch so can easily switch between main and 24.1-release branches when developing.
1. Run the alter statements on your DB if your DB has subproject instead of cohort
2. Run the revert alter statements to revert cohort to subproject.
* Related to https://github.com/aces/Loris/pull/7817
=> Fixes the revert section of the subproject/cohort patch

htdocs/survey.php, modules/api/php/endpoints/candidate/visit/instruments.class.inc, modules/api/php/endpoints/project/instruments.class.inc, modules/conflict_resolver/php/endpoints/unresolved.class.inc, modules/datadict/php/datadict.class.inc, modules/instruments/php/module.class.inc, modules/instruments/php/visitsummary.class.inc, php/libraries/NDB_BVL_Instrument.class.inc
This removes the exception from NDB_BVL_Instrument::factory(), so that it's possible to call hasAccess on an instrument. Currently the hasAccess or Factory call mix concerns, making it difficult for a module to check if a user has access to an instrument.
=> [Instrument] Remove exception from NDB_BVL_Instrument::factory

htdocs/AjaxHelper.php, modules/candidate_list/php/candidate_list.class.inc, modules/candidate_parameters/ajax/getData.php, modules/help_editor/ajax/help.php, php/libraries/Module.class.inc, src/LorisInstance.php, src/Router/BaseRouter.php, test/unittests/UserTest.php, tools/manage_modules.php
This finishes what was started in PR#8221 and eliminates the \Module::factory method. All remaining instances are updated to use $loris->getModule instead, which takes the LorisInstance module paths into consideration.
=> [core] Remove \Module::factory, update remaining instances to $loris->getModule()

modules/mri_violations/php/module.class.inc
The main branch is failing since #8287 because when dashboard calls getWidgets() on the mri_violations module the module autoloader hasn't been loaded. This registers the autoloader when it's called so that the "new" class can be found.
=> [mri_violations] Fix main branch

php/libraries/NDB_BVL_Feedback.class.inc
Fix the warnings
```
<br />
<b>Notice</b>:  Only variables should be assigned by reference in <b>/home/driusan/Code/Loris/php/libraries/NDB_BVL_Feedback.class.inc</b> on line <b>383</b><br />
<br />
<b>Notice</b>:  Only variables should be assigned by reference in <b>/home/driusan/Code/Loris/php/libraries/NDB_BVL_Feedback.class.inc</b> on line <b>383</b><br />
<br />
<b>Notice</b>:  Only variables should be assigned by reference in <b>/home/driusan/Code/Loris/php/libraries/NDB_BVL_Feedback.class.inc</b> on line <b>383</b><br />
```
when accessing some candidates (depending on their feedback status) in LORIS such as CandID 587630 in Raisinbread.
=> Fix Console Output on timepoint list

SQL/0000-00-05-ElectrophysiologyTables.sql, SQL/New_patches/2022-11-22-eeg-additional-events-table.sql
This PR adds a new table to keep additional data from BIDS event files (Loris-MRI).
Currently, additional data are ignored.
Linked to:
- [Loris-MRI 835](https://github.com/aces/Loris-MRI/issues/835)
- [Loris-MRI 873](https://github.com/aces/Loris-MRI/pull/873)
=> [EEG] new table to track EEG additional events

modules/api/php/endpoints/candidates.class.inc
The candidates/{CanID} endpoint throws a fatal if a missing but valid (format pass validation) CanID is provided.
- a 404 NotFound is returned [here](https://github.com/aces/Loris/blob/main/modules/api/php/endpoints/candidates.class.inc#L137) if the missing  CanID is not valid (incorrect format) since `new CanID()` will throw an error
- a fatal is thrown by `\NDB_Factory::singleton()->candidate()` if the format is valid but the value does not exist in the DB.
This PR catches the Exception thrown by new Candidate() to return a 404 NotFound.
=> [API] Fix Candidate endpoint error

modules/api/php/module.class.inc, modules/conflict_resolver/php/module.class.inc, php/libraries/NDB_Page.class.inc, src/Http/Endpoint.php
This makes sure that endpoints always have access to things that are always necessary (such as the LorisInstance object and PSR logger). NDB_Page is updated to extend Endpoint, since pages are types of endpoints.
=> Cleanup endpoint hierarchy

docs/CodingStandards.md, docs/instruments/NDB_BVL_Instrument_UPLOADER_TEMPLATE.class.inc, docs/wiki/99_Developers/UnitTestGuide.md, php/libraries/Database.class.inc, php/libraries/NDB_Client.class.inc, php/libraries/NDB_Factory.class.inc, test/unittests/Database_Test.php, test/unittests/Loris_PHPUnit_Database_TestCase.php, test/unittests/UserTest.php, test/unittests/VisitTest.php
There are currently 3 methods of getting a reference to a database in LORIS, in order of preference:
1. LorisInstance->getDatabaseConnection()
2. NDB_Factory::singleton()->database();
3. Database::singleton()
The only reference to 3 left is in the implementation of option 2. This removes the Database::singleton by inlineing the reference into the factory and removes all remaining references to Database::singleton (mostly from documentation and a couple unit tests.)
=> [Core] Remove Database::singleton function

src/LorisInstance.php
PR#8287 refactored the code in a way which removed the side-effect of registering an autoloader when calling Module::factory. This was probably not a good idea. Calls to methods on a Module instance retrieved now crash when attempting to call a method on the module if the module uses a class internal to the module.
Since the caller doesn't know if the module is going to use internal namespace classes, this re-adds the implicit autoloader registration when getting a module to the LorisInstance object.
It also caches the module descriptor in the LorisInstance after it's retrieved in order prevent registering the same autoloader multiple times.
=> Make getModule register autoloader for module

modules/dictionary/php/datadictrow.class.inc, modules/dictionary/php/datadictrowprovisioner.class.inc, modules/dictionary/php/moduledict.class.inc
PR#6936 includes a /dictionary/module/(modulename) REST endpoint to act as an API which provides the dictionary for the QueryEngine of a module.
This updates it to include the valid visits for which the data point is valid for session scoped variables.
1. This requires a module with session based variables in its QueryEngine such as #8216 (instruments) or #8288 (candidate parameters). Access `$LORISURL/dictionary/module/$modulename` and look at the JSON returned. Session scoped variables should include a visits key with an array of the correct visits for that variable.
=> [dictionary] Add visits for session scoped variables to API

modules/media/jsx/uploadForm.js
=> [media] add feedback to dropdown field when is empty

php/libraries/NDB_BVL_Instrument.class.inc
This updates the default instrument score() function (mostly used by LINST files) to check that the script is executable before trying to run it. If it's not executable, it will throw a ConfigurationException and log the reason.
Some more logs of various levels are also added to aid in diagnostics and the print statement is replaced by an log.
=> Validate LINST scoring scripts before running and log.

smarty/templates/main.tpl
Prevents autofill in chrome being incorrectly applied throughout LORIS like in the DQT module.
2. make clean && make dev
3. Visit the DQT and examine fields in chrome if passwords are being autofilled.
* Resolves #7938
=> [DQT] Prevent Autofill in chrome

modules/instruments/README.md, modules/instruments/test/TestPlan.md, php/libraries/NDB_BVL_Instrument_LINST.class.inc
This PR:
- fixes the Candidate Age at Death field label and Data Dictionary item for LINST instruments
- adds `postMortem` functionality for LINST instruments
- solidifies workflow for when Candidate Age at Death is displayed vs. Candidate Age (only when postMortem variable is set to true, and is independent of whether candidate has DoD or not - it is truly an instrument configuration and not dependent on instrument/candidate data)
- adds this workflow/configuration to the instruments module testplan and readme
1.
=> [instruments] Display Candidate Age at Death if postMortem is true

modules/imaging_browser/css/imaging_browser.css
=> [imaging_browser] Fix control panel positioning

docs/config/config.xml, docs/deprecated_wiki/Setup/Initial Setup/Imaging Database/Imaging-Database.md, php/libraries/Database.class.inc, php/libraries/NDB_Config.class.inc, raisinbread/config/config.xml, test/config.xml, test/unittests/NDB_ConfigTest.php
With this PR the venerable debug option showDatabaseQueries is no more. It has been replaced with the Database debug log level, which now logs queries to the error log instead of printing them to the wild.
RIP showDatabaseQueries 1999(est.)-2023.
It is survived by its config.xml contemporaries sandbox, database connection information, and PSCID structure.
=> [Database] remove showDatabaseQueries config.xml option

modules/api/docs/LorisRESTAPI.md, modules/api/docs/LorisRESTAPI_v0.0.4-dev.md, modules/api/php/endpoints/candidate/visit/instrument/instrument.class.inc, modules/api/php/views/visit/instrument_0_0_4_dev.class.inc, modules/api/static/schema-v0.0.4-dev.yml, modules/api/static/schema.yml, raisinbread/test/api/LorisApiInstrumentsTest.php
=> [api] Modify YAML schema so that Swagger Codegen PHP Client works

modules/mri_violations/jsx/mriViolationsIndex.js, modules/mri_violations/jsx/violations.js
There is currently no feedback to the user when they change the resolution status of a violation that something has changed, which can be confusing.
This fades the table cell to green after the cell has been changed in the same way that the conflict resolver does, so that the user is aware that something happened.
Green is probably not the ideal colour, but is consistent with the conflict resolver.
Fixes #8441
=> [mri_violations] Provide feedback on resolution status change

modules/candidate_parameters/ajax/formHandler.php, modules/candidate_parameters/jsx/ConsentStatus.js
This PR allows users to set a consent status back to null. I chose not to do this with a "Clear" button because a clear button would mean you are clearing all or none of the consent statuses on the page, or otherwise we would need a clear button for each individual consent. Instead, the participant can set the status to be empty and update the consent as usual. The date and withdrawal date are cleared and disabled when the status is set back to empty. 
1. Check that you are successfully able to update a consent status from non-null to empty
2. Check that when you update the status to empty, it only updates empty values for that consent and not for any other consent that was already empty
3. Make sure that the consent status history is updated appropriately
3. Check that all of the …
=> [candidate_parameters] Allow clearing of consent status

CHANGELOG.md, Makefile, SQL/0000-00-02-Permission.sql, SQL/New_patches/2022-12-20-instrumentpermissions.sql, docs/config/config.xml, modules/instrument_manager/jsx/instrumentManagerIndex.js, modules/instrument_manager/php/instrument_manager.class.inc, modules/instrument_manager/php/permissions.class.inc, modules/instrument_manager/test/TestPlan.md, package-lock.json, package.json, php/libraries/NDB_BVL_Instrument.class.inc, test/config.xml, tools/single_use/migrate_instrument_permissions.php
This migrates instrument permissions from the config.xml to the database in a new `testnames_permissions_rel` table. The table can be managed from the frontend in the `instrument_manager` module by any user who has the `instrument_manager_write` permission. The script `tools/single_use/migrate_instrument_permissions.php` can be used by existing projects to migrate their permissions from the config.xml to the new table.
=> [instruments/instrument_manager] Migrate instrument permissions from config.xml to database

modules/instrument_manager/jsx/instrumentManagerIndex.js
PR#7300 made proptypes required, but PR#8302 was merged between the time it was rebased and merged and was missing some proptypes.
This adds the missing proptypes to fix the build on aces/main.
=> Fix aces/main branch

jsx/Form.js
This adds a placeholder option for the TextareaElement, similar to TextboxElements.
=> [Form.js] Add placeholder option for TextareaElement

CHANGELOG.md, modules/dqt/ajax/DeleteDoc.php, modules/dqt/ajax/saveQuery.php, modules/dqt/css/dataquery.css, modules/dqt/jsx/react.app.js, modules/dqt/jsx/react.savedqueries.js, modules/dqt/jsx/react.tabs.js, modules/dqt/php/dqt_setup.class.inc, tools/dqt_delete_saved_query.php
Add delete feature for DQT
Add tools/dqt_delete_saved_query.php
1. Save a private or global query.
2. click delete button to delete or using dqt_delete_saved_query.php to delete the new saved query.
=> [DQT] add delete feature

modules/issue_tracker/css/issue_tracker.css, modules/issue_tracker/jsx/CommentList.js
This PR modifies the margins of the history and comments so that it's easier on the eyes to read
Before:
After:
1.
=> [issue_tracker] Make Comments and History easier to read 

modules/dqt/jsx/react.savedqueries.js
Another PR that was sent before PropTypes were mandatory was merged, causing the main branch to fail. This adds the missing PropTypes.
=> Add required proptypes to react.savedqueries.js

jsx/Card.js, jsx/FilterForm.js, jsx/FilterableDataTable.js, jsx/Form.js, jsx/InfoPanel.js, jsx/Modal.js, jsx/Panel.js, jsx/Tabs.js, modules/bvl_feedback/jsx/react.behavioural_feedback_panel.js, modules/document_repository/jsx/NullFilterableDataTable.js, modules/dqt/jsx/react.sidebar.js, modules/dqt/jsx/react.tabs.js, modules/electrophysiology_browser/jsx/components/electrophysiology_session_panels.js
- Proptypes.element does not allow multiple children
- Proptypes.array/Proptypes.object is too vague
Proptypes.node is a compound type for any renderable object: nothing, string, single element, several elements, fragment, component.
=> Fix PropsTypes for children

.eslintrc.json
There are no violations currently, there's no reason to disable the rule and let them sneak in in the future.
=> [eslint] Enable no-find-dom-node rule

.eslintrc.json, modules/dqt/jsx/react.savedqueries.js, modules/dqt/jsx/react.tabs.js
2 new warnings of the type:
```
"Invalid JSDoc tag name "deleteclick"   jsdoc/check-tag-names
```
snuck in with PR#8078.
This removes the lines causing the warnings. Since we don't have any other warnings of this type, it also upgrades the level of check-tag-names from warning to error.
=> [dqt] Fix new warnings

modules/document_repository/jsx/docIndex.js, modules/document_repository/php/files.class.inc, modules/document_repository/php/module.class.inc
1. Checkout branch 24.1-release and run make dev or npm run compile
2. Upload a file as User 1 (i.e. your own). Download that file once uploaded and confirm that the download worked.
3. Login as User 2 (i.e. admin). Try to download the same file and confirm that the download fails.
4. Go to the dashboard and click on one of the items in the 'Document Repository Notifications' widget. Confirm that the download fails.
5. Checkout this PR branch. Download the same file as User 2 and confirm that the download worked
6. Go to the dashboard and click on one of the items in the 'Document Repository Notifications' widget. Confirm that the download worked.
=> [document_repository] Fix download path to correct user

htdocs/bootstrap/css/custom-css.css, jsx/Panel.js, modules/dashboard/css/dashboard.css, modules/dashboard/templates/panel.tpl, modules/dashboard/test/DashboardTest.php, modules/imaging_browser/css/imaging_browser.css, modules/imaging_browser/jsx/ImagePanel.js, modules/issue_tracker/css/issue_tracker.css
Updated the Panel component to handle views if given. Also refactored the code to be a react functional component instead of a class. Used in PR: https://github.com/aces/Loris/pull/8261
1. checkout pr
2. make clean && make dev
3. visit modules that use the Panel component and see if anything broke.
=> [jsx/Panel.js] Improved Panel component with optional multiple views

modules/dqt/jsx/react.app.js
This bit of code was introduced in this [PR](https://github.com/aces/Loris/commit/90e17c78ff5a15c8c24e00553647fdc700bef54d#diff-54b30034c9a58a43476f9a8142cc301d7df7d22d769efaa31529757b06f3125fR509) and then reverted back in this [PR](https://github.com/aces/Loris/commit/c59d5f8dbb17011191fe11fb06ac17d5fa09906c#diff-54b30034c9a58a43476f9a8142cc301d7df7d22d769efaa31529757b06f3125f).
I am reverting the code back to what it was when it was introduced as the ['keys' parameter in the query string](https://github.com/aces/Loris/blob/65e676a1604f50447af1331d0ae7f5a43608131a/modules/dqt/ajax/datadictionary.php#L46) wasn't changed back. I'm assuming reverting the code was a mistake when it got lumped in with the rest of the intended code changes
1.
* Resolves #  (Reference the issue this fixes, if …
=> [dqt] Fix loading saved query

.eslintrc.json, modules/battery_manager/jsx/batteryManagerIndex.js, modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/store/state/channels.tsx, modules/imaging_qc/jsx/imagingQCIndex.js, modules/mri_violations/jsx/mriViolationsIndex.js
Forgetting a "break" in a switch statement is a common developer error. For instance, most of the places caught by this rule which is currently disabled.
=> [eslint] enable no-fallthrough rule

modules/genomic_browser/php/models/cnvdto.class.inc, modules/genomic_browser/php/models/filesdto.class.inc, modules/genomic_browser/php/models/gwasdto.class.inc, modules/genomic_browser/php/models/methylationdto.class.inc, modules/genomic_browser/php/models/profiledto.class.inc, modules/genomic_browser/php/models/snpdto.class.inc
Fix a Fatal error on the Genomic Browser tabs:` [ERROR] Can not implement UserSiteMatch on a resource type that has no sites.`
To test:
Use a user that have permission `Genomic Browser: View Genomic Data - Own Sites` but do not have  `genomic_browser_view_allsites`. Visit the Genomic Browser and check that the tabs loads without error.
Fixes #7589
=> [Genomic Browser] UserSiteMatch fix

SQL/Archive/23.0/2019-10-29-adding_issues_attachments_table.sql, SQL/Release_patches/22.0_To_23.0_upgrade.sql
=> [SQL] Fix hardcoded parent ID for IssueTrackerDataPath in patches

CHANGELOG.md
Adds to Changelog for #7491 and #7772
=> [documentation] Add to CHANGELOG

SQL/0000-00-03-ConfigTables.sql, SQL/Cleanup_patches/2023-02-21-unusedconfigs.sql, php/libraries/NDB_Menu_Filter.class.inc, src/Middleware/AnonymousPageDecorationMiddleware.php, src/Middleware/UserPageDecorationMiddleware.php
This removes the `css` config setting (which has the ability to point to a different file than main.css but in practice is never edited because everything in LORIS would break without main.css loaded) and rowsPerPage (which is no longer supported because it's not honoured by our React menu filters.)
=> [Meta] Remove css config setting and rowsPerPage

modules/electrophysiology_browser/css/electrophysiology_browser.css, modules/electrophysiology_browser/jsx/components/DownloadPanel.js, modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/components/EventManager.tsx, modules/electrophysiology_browser/php/models/electrophysioannotations.class.inc, modules/electrophysiology_browser/php/sessions.class.inc
PR #8242 modified the electrodes DB schemas and since then, the EEG Browser is broken. 
This fixes the issue by rewriting the query logic. 
Also fixes a few issues with the download buttons and the layout.
To test:
----------- 
- Make sure the EEG Browser loads
- Create a new annotation
- Check that the comment section of the new comment is displayed without any layout issues
- Make sure the annotations, electrodes and all files are downloadable.
=> [EEG] Electrodes query and file download fix

modules/issue_tracker/jsx/IssueForm.js, modules/issue_tracker/jsx/attachments/attachmentsList.js, modules/issue_tracker/php/edit.class.inc
[Issue tracker] - Delete attachment #8006
A clear and concise description of what the bug is
If a user does not have Issue Tracker: Close/Edit/Re-assign/Comment on All Issues, they cannot delete their own attachment.
If a user does not have Issue Tracker: Close/Edit/Re-assign/Comment on All Issues, they can delete their own attachment.
=> [Issue tracker] - fix can't Delete attachment #8006

modules/dqt/jsx/react.fieldselector.js, modules/dqt/jsx/react.filterBuilder.js
This replaces all the jQuery ajax calls with fetch in the files modules/dqt/jsx/react.fieldselector.js and modules/dqt/jsx/react.filterBuilder.js.
N.B. this should be tested. I don't have CouchDB setup to test it but the behaviour should theoretically be the same.
=> [dqt] Replace jQuery ajax calls with fetch in DQT

jsx/Form.js, modules/document_repository/css/document_repository.css, modules/document_repository/jsx/uploadForm.js, modules/document_repository/php/files.class.inc, modules/document_repository/test/document_repositoryTest.php, smarty/templates/email/notifier_document_repository_upload.tpl
- \<FileElement\> now supports the 'multiple' attribute.
- The document_repository module has been modified to support multiple uploaded files.
- Some visual feedback has been added (error reporting + uploading status).
- Ensure that another module using \<FileElement\> still works as intended.
- Try with different files, file types and folder permissions to ensure proper error reporting.
=> [Document Repository] Upload multiple files at once

CHANGELOG.md, modules/configuration/ajax/updateProject.php, modules/configuration/js/project.js
This PR prevents the user from saving a Project configuration with a null Alias in a new project as well as existing projects. 
While testing, I also noticed that several of the error messages were broken, so those were fixed as well
1. Try testing a new project with the following mistakes and make sure that the form does not save, and a relevant error message is given in each case.
- No project name
- No Alias
- An Alias longer than 4 characters
2. Repeat above steps but in an existing Project
* Resolves #7948
=> [configuration] Fix error messages & saving with null Alias

src/Middleware/AnonymousPageDecorationMiddleware.php, src/Middleware/UserPageDecorationMiddleware.php
Since PR #8397, the main.css. is broken since it includes the base_url twice:
https://github.com/aces/Loris/pull/8397/files#diff-d4b838452a61b616f3f7e797208ebad8d83d2f7ec9412183f691f2631cdadf64R42
https://github.com/aces/Loris/blob/main/smarty/templates/main.tpl#L5
This should fix the styling issues for the help tooltip and the user page.
=> Fix main.css broken link

jsx/StaticDataTable.js
Fixes a regression introduced by #7473. 
https://github.com/aces/Loris/pull/7473/files#diff-a2dad6817e8e695e9b53e19bc1bd4195daae329095623a068992de999568828fR555
Notice that the PSCID value is hidden and the columns shifted to the left.
=> [Core] StaticDataTable column freeze fix

webpack.config.js
The conflict resolver wasn't being compiled, causing the candidate profile of any candidate with conflicts to not load. This fixes the issue so that the page now loads.
Resolves #8568
=> [conflict_resolver/candidate_profile] Fix loading of conflict widget

docs/wiki/99_Developers/Code_Customization.md, readthedocs/mkdocs.yml, readthedocs/themes/loris_theme/css/theme_extra.css, webpack.config.js
- Reordering of the RDT Developers sections by logical concepts
- Fix a typo in `webpack.config.js` found while working on this PR
- A few RTD templates fixes like:
To review: https://loris-dev.readthedocs.io/en/latest/docs/wiki/99_Developers/Code_Customization.html
=> Code customization doc

modules/issue_tracker/jsx/CommentList.js, modules/issue_tracker/jsx/IssueForm.js
This PR imports markdown in the relevant jsx files for issue_tracker module
I didn't update the changelog because I believe this fixes a bug that was introduced in this version, but let me know if there's anything I need to update!
1. In the 25.0-release branch, open an issue on the front end
2. See that it does not display
3. In this branch, compile code and then open an issue on the front end
4. See that it does display.
* Resolves #8645
=> [issue_tracker] Fix issue display by importing Markdown

raisinbread/test/api/LorisApiProjectsTest.php
Add two endpoint integration tests:
- `/projects/{project}/instruments/{instrument}`
- `/projects/{project}/recordings`
* Resolves #8617
=> [api] add new integration tests for API project endpoint

tools/single_use/instrument_double_escape_report.php
This tool tries to run pregmatch on every value pulled from the instrument Data. there is a possibility that values coming from `json_decode()` are decoded into floats or arrays if that is how they have been saved. if it's the case the script should just skip them and not fail
=> [Tools] double_escape_report tool breaking on non-string values

modules/media/ajax/FileDownload.php
Changed permission check in filedownload.php so that files in the media widget download when the user has media_read permission.
https://github.com/aces/Loris/issues/8583
=> changed permision check to media_read to enable media downloads

modules/issue_tracker/php/issue_tracker.class.inc
In the issue tracker module, the reporter dropdown is populated with the assignee users instead of the reporter users.
This PR fills the reporter dropdown with the right reporter values.
1. Go to the menu > tools > issue tracker.
2. See the values in the reporter dropdown field, they should be different from the assignee values (depending on the values in the table - reporter and assignee columns).
- #8429 
Rebased from #8450
=> [issue tracker] Populate reporter dropdown (24.1)

modules/examiner/templates/form_editExaminer.tpl
This PR is changing the CSS class used in the examiner page. The former class had a small percentage of the width causing the first field become narrow, by changing it to another class, the problem is solved.
1. Go to the examiner module
2. Select an examiner to access the 'Certification' page
3. Text in the 'Instrument' column should not be narrow anymore.
* Resolves #  #8026
=> [examiner] Column for 'Instrument' in certification menu appears narrow

tools/data_integrity/fix_candidate_age.php
1. Run this script on instruments with and without SQL tables
2. Manually modify a "Date_taken" value in the SQL table and/or flag table
3. Run the script again and make sure that the value is modified correctly
4. Manually modify a "Candidate_Age" value in the SQL table and/or flag table to be null
5. Run the script again and make sure that the value is modified correctly
6. Check the script with both "check" and "confirm" 
* Resolves #8090
=> [tools] support JSON instruments in fix_candidate_age.php

php/libraries/NDB_BVL_Feedback.class.inc
Currently, only users with the `access_all_profiles` permission can see Feedback Threads and Open Thread Summary at the profile level. Even if a user adds a feedback entry, they won't be able to see their own feedback thread unless they have the `access_all_profiles` permission.
This PR allows users to see threads and the summary that exists for candidates that they have access to (i.e., if a user is affiliated with MTL, they can now see the feedback threads & summary of MTL candidates).
1. Ensure that your user DOES NOT have the `access_all_profiles` permission and DOES have the `bvl_feedback` permission
2. Go to Candidate --> Access Profile
3. Click on any candidate 
4. Click the notepad icon in the top right-hand corner of the page (next to the question mark icon). This will open the …
=> [bvl_feedback] Fix Permissions for Feedback Summary & Thread List

modules/instruments/php/instrumentqueryengine.class.inc, modules/instruments/php/module.class.inc, php/libraries/NDB_BVL_Instrument.class.inc, src/Data/Query/QueryEngine.php
This adds a QueryEngine for the instruments module. The Instrument
QueryEngine bulk loads the data so that it can work with either JSON
or SQL instruments, and then compares the data that was loaded
against the criteria given.
This is intended to be an example of a QueryEngine for PR#8215.
It could use more automated tests but tests for instruments are difficult
since they're so highly customized per project.
=> [Instruments] Instrument data QueryEngine

modules/instrument_builder/help/instrument_builder.md, modules/instrument_builder/test/TestPlan.md
* The `instrument_builder/test/TestPlan.md` was updated.
* The `instrument_builder/help/instrument_builder.md` was updated.
1. The `Test Plan` and the `Help` for the `instrument_builder module` should be now consistent.
* Resolves #8575
**Note:** The second part of the issue #8575 is considered a feature request, nor a bug in this case. A new issue will be opened for this second part.
=> [Instrument Builder] updates Test Plan and Help to fix inconsistencies.

CHANGELOG.md, SQL/0000-00-00-schema.sql, SQL/New_patches/2023-04-24_add_phase_enc_dir_and_echo_number_to_MRICandidateErrors.sql, modules/mri_violations/php/provisioner.class.inc, modules/mri_violations/php/resolve.class.inc, tools/single_use/update_violations_resolved_hashes.sql.php
In the MRI violation module, the hash generated for the violations_resolved table was created under the assumption that `SeriesUID` is enough to determine a unique image file. Unfortunately, this is not true anymore and multiple files with the same `SeriesUID` can be generated. The new unique criteria for a file is `SeriesUID/EchoTime/EchoNumber/PhaseEncodingDirection` combo. This PR:
- Updates the `MRICandidateErrors` table to add the missing columns `PhaseEncodingDirection` and `EchoNumber`
- Updates the MRI Violation module to use the new hashing algorithm for resolved violations:
```
md5(
concat_WS(
':',MincFile,PatientName,SeriesUID,TimeRun,
PhaseEncodingDirection,EchoTime,EchoNumber
)
```
- Add a single use tool script to run at the time of upgrade.
1. Check out the code from this …
=> [MRI violations] Fix hashing of MRI violation module

modules/mri_violations/css/mri_violations.css, modules/mri_violations/jsx/protocolModal.js, modules/mri_violations/php/mri_violations.class.inc
This PR adds spacing between the description items, as requested in #8627. 
I avoided redundancy by adding the attributes required on several child elements via css selectors.
The selectors needed to be declared in a css file, which this module did not have yet.
This PR also adds a css file.
=> [mri_violations] Added spacing between description items

php/libraries/Recording.class.inc, raisinbread/test/api/LorisApiRecordingsTest.php
Update the metadata recording endpoints:
#8616
=> [api] Recordings endpoints integration tests update

modules/new_profile/php/new_profile.class.inc, modules/new_profile/test/new_profileTest.php, src/StudyEntities/Candidate/Sex.php
the keys in the new_profile module were lower case which forces the Sex library class to use a `strtolower()` function to validate the value and then submits the lowercase value in the SQL insert statement where SQL implicitly converts it to uppercase. This workflow is very risky as different versions of SQL or different databases may not recognise the lowercase and uppercase as the same word and treat it as a truncation. This is also simply bad practice and unnecessary here.
1. Make sure new profile still works properly and that the sex loads properly on other modules (i.e. candidate_list, timepoint list...)
=> [new_profile/sex] Remove strtolower() and force uppercase

modules/mri_violations/php/provisioner.class.inc, modules/mri_violations/php/resolve.class.inc, modules/mri_violations/test/mri_violationsTest.php
This fixes a bug where the violation could not be resolved when there is more than one `Protocol Violation` returned for a file/timerun combination. The fixes include the following:
- only show one row per pname/timeRun/mincFile/scanType in the main menu filter table when there are multiple `Protocol Violation` for a given file (the list of violations will be displayed when clicking on the `Protocol Violation` link.
- when selecting a resolution, loop through all entries in `mri_violations_log` matching the `timeRun/mincFile` and update the resolution status for all matching entries in the `violations_resolved` table.
For the raisinbread dataset, the following images match what this PR is fixing: 
- `assembly/300170/V1/mri/native/demo_300170_V1_dwi65_001.mnc`
- …
=> [MRI violations] Fix multiple rows for file protocol violations not resolvable

php/libraries/Candidate.class.inc
When a dob Format of Ym (year and month without day) is set in the config module, candidates could not be created for 2 reasons. 
1. The wrong format (`!Y-m-d`) was being passed through the function `DateTime::createFromFormat` in the `createNew` function of the candidate class, which gave a wrong format error to the user even if they were passing through the expected format of Year-month
2. Even if this was fixed, the date was inserted into the candidate table as YYYY-MM, but this is not compatible with the SQL Type `date`
This PR fixes this issue by getting the date format from config, processing it to the right format and passing it through to `DateTime::createFromFormat`, as well as adding a '-01' to the end of the date if Ym format is selected in the configuration. This inserts the …
=> [candidate] Allow dob format Y-m

php/libraries/NDB_BVL_Instrument_LINST.class.inc
Currently, the metadata fields are only defined in the LINST instrument's data dictionary for the 'top' page, causing an error when trying to access those fields' values from other subtests. This is happening because the data dictionary definition is being called only when the fields' input elements are being added to the page in `_addMetadataFields` function. This PR changes to logic to follow the data dictionary definition for all other fields which get called whether or not the fields' input element is being added to the current page i.e. outside of `if ($addElements) { }` block
1.
=> [instruments] Fix LINST metadata fields not in data dictionary

modules/electrophysiology_browser/help/electrophysiology_browser.md, modules/electrophysiology_browser/help/sessions.md, modules/electrophysiology_browser/jsx/react-series-data-viewer/README.md, modules/electrophysiology_browser/test/TestPlan.md
Amendments to documentation to address typos and reflect changes brought in the new release.
=> [electrophysiology_browser] Updated module documentation

modules/api_docs/php/api_docs.class.inc, modules/api_docs/php/module.class.inc, modules/api_docs/test/api_docsTest.php
Currently, the API Docs module is accessible even if you don't have the 'api_docs' (API Documentation: View LORIS API Manual) permission. This PR fixes that by moving the hasAccess function from the NDB Page to the module class
1. Make sure that the module page is only accessible if the user has the "API Documentation: View LORIS API Manual" permission selected.
2. Make sure that the 'API Documentation' item is available in the navigation bar's 'Tools' tab only if the user has the "API Documentation: View LORIS API Manual" permission selected.
* Resolves https://github.com/aces/Loris/issues/8602
=> [api_docs] Fix permissions access

Makefile, modules/data_release/jsx/managePermissionsForm.js
This fixes the console warnings (which were mostly proptype errors) in the data_release module.
=> [data_release] Fix console warnings in data_release modules

modules/candidate_parameters/ajax/formHandler.php
- The permissions checks were updated on **modules/candidate_parameters/ajax/formHandler.php**
- Now a user with the permission "candidate_dob_edit" and without "candidate_parameter_edit" should be able to "Edit date of birth".
- Also for the "Edit date of Death".
The rest of the behaviour should not be affected. 
- [X ] Have you updated related documentation?
Not needed in this case.
1. Go to candidate parameter
2. Click on date of birth
3. Edit date of birth
3a. Edit date of death
4. The issue reported in https://github.com/aces/Loris/issues/8574 should be fixed.
* Resolves #  https://github.com/aces/Loris/issues/8574
=> [candidate_parameters] Fix permission issue.

modules/candidate_list/php/validateids.class.inc
1. Enter wrong PSCID & CandID
fixes #8590
=> [candidate_list] fix error message not displaying if entered wrong IDs in the 'Open Profile' tab

jsx/Filter.js
- adds a sortByValue option that can be set to false to disable the sortByValue default behaviour on multiselects.
- the sortByValue option is already available for selects
- set the default value to true to keep the default behaviour of the existing filters.
=> Add an option to disable sortByValue on filter multiselects

modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/components/EventManager.tsx
Changed &nbsp to regular white space so that the Event Panel title renders correctly.
Closes #8690.
=> [electrophysiology_browser] Event Panel title fix

modules/instruments/test/TestPlan.md, php/libraries/NDB_BVL_InstrumentStatus_ControlPanel.class.inc
Currently, if the 'InstrumentResetting' config is set to 'No', the 'Delete instrument data' button is displayed and the user is able to clear the instrument. This PR fixes that by letting the if statement check a true boolean instead of string "true" by calling 'settingEnabled'. The PR also modifies the testing plan so this is tested in the future.
1.
=> [instruments] Fix properly disabling/enabling 'Delete instrument data' button display

modules/battery_manager/jsx/batteryManagerForm.js
- A few number values were being passed as Strings in the props to Form elements, I changed those to be numbers.
1. Tools>Battery Manager>New Test
2. Observe that no errors appear in the console.
* Resolves #8703
=> [battery_manager] React warning messages in console

modules/user_accounts/test/TestPlan.md
This PR changes the wording slightly in the TestPlan of user_accounts to indicate that an email is only sent to a new user if the "Send email to user" button is selected.
* Resolves #6971
=> [user_accounts] Update TestPlan wording

modules/user_accounts/test/TestPlan.md
The pwned password example was not complex enough to pass the complexity check and trigger the pwned check.
For testing assignment #8535.
=> [user_accounts] Update TestPlan.md

modules/instrument_manager/test/TestPlan.md, modules/instruments/test/TestPlan.md
This PR transfers the permission test step from `instruments` module to `instrument_manager` module.
* Resolves #8755
=> [instrument & instrument_manager] test plans update

modules/configuration/ajax/process.php
The values get double-escaped when modified now if they contain HTML. Use unsafe variants of database calls so that the values to not get modified when re-saved.
Fixes #8748
=> [configuration] Use unsafeInsert/unsafeUpdate for saving values

modules/new_profile/jsx/NewProfileIndex.js, php/libraries/Candidate.class.inc
- Fixed NewProfileIndex to use the correct variable containing the EDC date
- To create a candidate, the date of birth for a candidate is now required only when useEDC = no in `Candidate.class.inc`. 
If useEDC = yes, DoB is `null` unless it's specified. 
- Added the validation of the EDC date format
- If the Ym format is selected in the configuration, added a '-15' to the end of the EDC date to be compatible with the SQL type date
1. Attempt to create candidates with the following combinations from configuration
a. useEDC = no, DOB format = Ym
b. useEDC = no, DOB format = Ymd
c. useEDC = yes, DOB format = Ym - once with DoB not specified, once with DoB specified too
d. useEDC = yes, DOB format = Ymd - once with DoB not specified, once with DoB specified too
* Resolves #8742
=> [new_profile] Fix date requirements and formats with EDC

htdocs/survey.php
The module search path for survey instruments was incorrect. Set to the same search path as in tools/generic_includes.php
Resolves #8546
=> [Survey] Fix loading of survey instruments

modules/survey_accounts/help/survey_accounts.md
This PR replaces `<br>` tag with 2 spaces.
Before:
After:
1.
=> [survey_accounts] Fix help text

modules/candidate_profile/test/TestPlan.md, modules/timepoint_list/php/timepoint_list.class.inc, modules/timepoint_list/test/TestPlan.md, php/libraries/Candidate.class.inc
- Adjusted the Timepoint_List module to also filter out the visits of projects that are not affiliated to the current user when they have permission to all sites.
1. Create a timepoint for a candidate for another project
2. Look at the candidate with a user that does not have permissions to that project
3. You should not see that timepoint
4. Confirm that visits with user affiliated projects do not disappear as well
* Resolves #8710 
**Before:**
**After:**
=> [Timepoint List] Hide visits that are from user unaffiliated projects

php/libraries/Candidate.class.inc
=> [Candidate] Fix wrong comments to avoid confusion in future

modules/candidate_parameters/php/candidate_parameters.class.inc
Remove unnecessary access_profiles permission check
1. Login with a user account without candidate_parameters permission.
2. Try accessing the URL of candidate profile of any candidate obtained from the admin account.
3. You should be able to see a permission denied note on the screen.
* Resolves #8733
=> Fix candidate_parameters permission problem

modules/data_release/php/permissions.class.inc
When adding version permissions for a user, permissions for unversioned files are no longer added 
1. Go to data_release
2. Make sure that there is at least one file uploaded without a version (version will show up as "Unversioned"), and at least one file uploaded under a specified version
3. Add permissions for a user to give them permission to the specified version
4. See that the user now only has permission to the specified version, and not "Unversioned" too
* Resolves #8741
=> [data_release] Permission not added to unversioned files if version specified

modules/api/php/views/visit/flags.class.inc
Fix a bug where in json instrument, CommentID is not part of the instrumentData properties.
=> [API] Using accessor to access instrument's commentid

php/libraries/NDB_BVL_Instrument.class.inc, test/unittests/NDB_BVL_Instrument_Test.php
The CommentID is not part of the data, it's the foreign key used between the flag table and the instrument table. JSON-based instruments do not have it, and this ensures better consistency between the two so that issues such as #8796 and #8801 will not vary based on instrument type and will be caught sooner.
Resolves part of #8804 (Inconsistency #2)
=> [instruments] Remove CommentID from getInstanceData.

modules/battery_manager/php/testoptionsendpoint.class.inc, php/libraries/VisitController.class.inc
The battery manager currently uses the `Utility::getVisitList()` function to list the visits available. That utility function queries the session table for existing visitlabels used in at least one session. That is problematic when you are creating a new visit and new instruments and want to assign instruments to the new visit, it simply does not show up in the drop down.
This PR fixes that problem and removes the use of Utility::getInstrumentList to get an accurate list of full names for instruments and get rid of deprecation warnings 
* Resolves #8459
=> [battery_manager] use visit controller to fetch visit list

.github/workflows/loristest.yml
PR #8802 increased the speed of our test suite a little, and gives a better at-a-glance overview of our API status, but the order that `find` finds the schema patches is inconsistent and can sometimes be sourced out-of-order, causing sporadic test failures.
This sources them explicitly instead of using find, to ensure the order is always correct and test runs don't sporadically fail.
=> [GitHub Actions] Fix order of schema sourcing

modules/instruments/php/dictionaryitem.class.inc, php/libraries/LorisFormDictionaryImpl.class.inc, php/libraries/NDB_BVL_Instrument.class.inc, php/libraries/NDB_BVL_Instrument_LINST.class.inc, raisinbread/test/api/LorisApiInstrumentsTest.php, raisinbread/test/api/LorisApiInstruments_v0_0_3_Test.php, test/unittests/NDB_BVL_Instrument_LINST_ToJSON_Test.php, test/unittests/NDB_BVL_Instrument_Test.php
The previous test was "incomplete" (it sent a request to the URL but didn't do anything to verify it.) This adds real tests for the candidate instrument data endpoint now that Issue #8781 was fixed by PR#8796.
Also resolves #8804 point 1. (Point 2 was resolved by #8805)
=> [test/api] Add tests for getting instrument data from API.

modules/issue_tracker/php/attachment.class.inc
- Changed the error message from "upload failed" to be more specific based on the problem
* Resolves #8327
=> Make upload error message more specific in issue tracker

modules/candidate_list/jsx/candidateListIndex.js
The filters for site, cohort and visit label are now multiselect
1. Go to Candidate -> Access Profiles page
2. Check that you can select multiple visit labels, cohorts, and visits
This is a CCNA override - https://github.com/aces/CCNA/pull/3922
=> [candidate_list] Multiselect for visit label, site, and cohort

modules/configuration/ajax/process.php, modules/imaging_qc/jsx/imagingQCIndex.js, modules/imaging_qc/php/imaging_qc.class.inc
- Changed the error message to be more specific
1. run `alter table mri_parameter_form rename to mri_parameter_form2;`
2. Try to open Imaging>Imaging Quality Control
3. See the new error message
* Resolves #5325 
New error:
**If there is an error caused by something else since mri_parameter_form exists:**
=> [imaging_qc] Improve Error Message

php/libraries/NDB_BVL_Instrument.class.inc
The logic of bulkLoadInstanceData constructs an SQL statement with the parameters bound to it by looping over the iterable passed to it. If the iterable is empty, the result will be SQL with the string `.. IN ()` which is not valid SQL. This returns an empty array in that case before attempting to run the generated SQL, since the result of bulk loading nothing should be nothing.
=> [Instruments] Handle empty bulkLoadInstanceData

modules/survey_accounts/js/survey_accounts_helper.js, modules/survey_accounts/jsx/surveyAccountsIndex.js, modules/survey_accounts/php/addsurvey.class.inc, modules/survey_accounts/php/survey_accounts.class.inc
This PR was made to remove overrides on COPN and CBIGR
- removes notices
- removes deprecation warning
- add filter options to filter with limited set of options
=> [survey_accounts] notices, warnings and filter options

php/libraries/LorisForm.class.inc, test/unittests/LorisForms_Test.php
This PR was made to remove overrides on COPN and CBIGR
Checkbox elements can not be defined as required like the rest of the elements. This add support for required
=> [LorisForm] add required to checkboxes

modules/candidate_parameters/jsx/ParticipantStatus.js
For Participant Status, make comments mandatory when setting the status to anything other than "Active" or "Complete".
1. Go to Candidate -> Access Profiles
2. Select any participant
3. Go to Candidate Info -> Participant Status
4. Try updating the participant status to "Active", then "Complete" and ensure comments aren't mandatory. 
5. Try updating the participant status to all other statuses and ensure comments are mandatory i.e., that an error message pops up when trying to update without comments.  
This is a CCNA override - https://github.com/aces/CCNA/pull/6311
=> [candidate_parameters] Participant status - mandatory comments if not active or complete

modules/candidate_list/jsx/candidateListIndex.js, modules/candidate_list/php/candidatelistrowprovisioner.class.inc, tools/CouchDB_Import_Demographics.php
This PR adds the date of registration of the candidate as a field in the candidate list table and adds it to CouchDB demographic import script.
1. Go to Candidate -> Access Profile
a. See 'Date of registration' as a Selection Filter & as a column in the candidate list table 
b. Check that the Date of Registration displayed is correct for the candidate 
c. Filter for the Date of Registration and check that the appropriate candidates are displayed => then click 'Clear Filters' and see the date blank
2. (After the CouchDB_Import_Demographics script is run) Go to Reports -> Data Query Tool
a. In Define Fields, select 'demographics'
b. Find the field 'Date_registered' with description 'Date of Registration' (might not be on first page) -> select that field and all visits
c. Run query -> ensure …
=> [candidate_list][CouchDB_demographics] Add date of registration

php/libraries/BVL_Feedback_Panel.class.inc
In the feedback panel for an instrument, the only option in 'Field Name' was 'Across all fields'. This PR changes how the field names for an instrument are fetched so that all of them appear as an option too. 
1. Go to Candidate -> Access Profile -> choose a participant -> choose a timepoint -> choose an instrument
2. Open the feedback panel
3. In Field Name, ensure you can see all the fields of that instrument, and not just 'Across all fields'
4. Repeat for a different instrument to make sure the appropriate field names appear for different instruments 
This is a CCNA override - https://github.com/aces/CCNA/pull/5444
=> [Libraries] Feedback panel - fix fieldnames setting

modules/bvl_feedback/ajax/close_bvl_feedback_thread.php, modules/bvl_feedback/ajax/delete_thread_comment_bvl_feedback.php, modules/bvl_feedback/ajax/get_thread_entry_data.php, modules/bvl_feedback/ajax/open_bvl_feedback_thread.php, modules/bvl_feedback/ajax/update_thread_comment_bvl_feedback.php, modules/bvl_feedback/css/bvl_feedback_panel.css, modules/bvl_feedback/jsx/react.behavioural_feedback_panel.js, modules/bvl_feedback/test/TestPlan.md, php/libraries/NDB_BVL_Feedback.class.inc
- Moved [CCNA overrides to bvl_feedback module](https://github.com/aces/CCNA/pull/6360) to LORIS Core
- Switched Add Comment button from Pencil to a Comment (Original was confusing)
- Set threads to be shown automatically for open threads as having them hidden made the UI confusing.
- Added an Edit and Delete button for comments of which the author is the user viewing them
- Flipped the order of comments around so that the newer comments show up below. Makes more sense when reading the comments
- Made New Comment TextArea section show up below the thread, as that is where the new comment will appear
- Changed panel width to work on mobile devices
Behaviour:
- Defaults to closed
- Date is not shown
- Comments are ordered in a confusing way
(Everything is cut off)
Behaviour:
- Defaults to …
=> [bvl_feedback] Edit comment section

htdocs/AjaxHelper.php
This change enables the use of project modules for requests that use `AjaxHelper`.
The order in which the directories are defined, when the `LorisInstance` is instantiated, determines the order of locations where modules are searched for and registered.
=> [Core] Enable use of project modules for ajax requests

SQL/New_patches/2023-07-19_add_index_parameter_type.sql, modules/conflict_resolver/jsx/resolved_filterabledatatable.js, modules/conflict_resolver/jsx/unresolved_filterabledatatable.js, modules/conflict_resolver/php/models/resolveddto.class.inc, modules/conflict_resolver/php/models/unresolveddto.class.inc, modules/conflict_resolver/php/provisioners/resolvedprovisioner.class.inc, modules/conflict_resolver/php/provisioners/unresolvedprovisioner.class.inc
This adds a 'Description' field to the Conflict Resolver module (both Resolved and Unresolved tabs), which corresponds to the description of the 'Question' with the conflict. Instead of using parameter_type like in the CCNA code, it uses /dictionary/module/instruments to get the description of the fields. Since some fields don't have descriptions (e.g. some _status variables), the empty string is used as default. 
Changes have been made to the Instrument_LINST file such that numeric and date elements are added to the dictionary, even if they are not in the top page (inspired by the change in https://github.com/aces/Loris/pull/8869). 
1. Go to Clinical -> Conflict Resolver 
2. Ensure both tabs 'Unresolved' and 'Resolved' load correctly, and in both, ensure that:
a. You can see a …
=> [conflict_resolver]  Add description field

SQL/0000-00-00-schema.sql, modules/issue_tracker/php/edit.class.inc
- Tracks "Others Watching" in issue history
* Resolves #8874
=> [IssueTracker] Fix for "othersWatching" history tracking

modules/imaging_uploader/jsx/UploadForm.js
Fixes https://github.com/aces/Loris/issues/8803
1. In Imaging uploader Upload Form, choose Phantom 'No' and select a file with the proper naming convention, suffixed by any random string.
2. Make sure that only the visit label is populated in the Visit Label field, and not the entire end of the string
=> [imaging_uploader] Fix auto-populating VisitLabel

php/libraries/LorisFormDictionaryImpl.class.inc
Some instruments use hidden fields which were not taken into consideration in this class. This should simply skip over the fields in the dictionary building
=> [Dict] hotfix add hidden fields to dictionary implementation

modules/dataquery/static/schema.yml
This makes a couple updates to the schema defined for the dataquery API.
Visits may be defined for session scoped fields. A description is added, but the field is not marked as required because it is not used for candidate fields.
QueryResults is better defined. The separators are explicitly defined to be those currently used by `src/Http/DataIteratorBinaryStream` and the cells are now always defined to be JSON values. The format of session scoped data is more explicitly defined to be in line with the expectations of the new data query frontend.
=> [dataquery api] Clarify schema

modules/configuration/templates/form_configuration.tpl
On 24.1++, 
In configuration -> Email, we currently have in From and Reply-to values 50 and 51 respectively and updating them does not change the value.
Fixes https://github.com/aces/Loris/issues/8890
=> [Configuration] Fix values of email fields

modules/configuration/templates/form_configuration.tpl
PR#8759 converted the escape module to use unsafeInsert/update to save data and prevent double escaping issues. The usages of the textarea were audited to make sure they were properly escaped, however the value is also displayed in the configuration module itself. Until the module is updated from smarty to react (PR#8471), they need to be escaped in the config module itself.
This adds escaping to the config module smarty template.
=> [configuration] Escape values in config module

modules/media/ajax/FileUpload.php
This fixes 2 problems with the SQL in the media FileUpload?action=getData endpoint
1. There is an obvious SQL injection attack where user input from the request is directly concatenated into a string that's passed to the database.
2. There was an unnecessary sub-select that could have been a join
This whole section of the code is a mess that should to be re-written, but this PR just tackles the urgent string concatenation.
=> [media] Fix SQL injection 

modules/api/php/endpoints/candidates.class.inc, modules/configuration/templates/form_configuration.tpl, modules/imaging_uploader/jsx/UploadForm.js, modules/issue_tracker/php/edit.class.inc, modules/media/ajax/FileUpload.php, modules/survey_accounts/js/survey_accounts_helper.js, modules/survey_accounts/jsx/surveyAccountsIndex.js, modules/survey_accounts/php/addsurvey.class.inc, modules/survey_accounts/php/survey_accounts.class.inc, php/libraries/BVL_Feedback_Panel.class.inc, php/libraries/LorisForm.class.inc, php/libraries/LorisFormDictionaryImpl.class.inc, php/libraries/NDB_BVL_Instrument_LINST.class.inc, test/unittests/LorisForms_Test.php, tools/importers/CouchDB_MRI_Importer.php
Push bug fixes forward. 
**DO NOT SQUASH.**
=> Push v24.1.5 bug fixes into v25.0.x release branch

htdocs/js/loris.js, smarty/templates/main.tpl, src/Middleware/UserPageDecorationMiddleware.php
Currently, you can access the PHP user object from smarty templates, but if you need access the username/userid from javascript you need to jump through hoops (like putting them in a smarty template or an endpoint that returns them.)
This adds a `user` object of the form `{username: string, id: number}` to the loris helper object so that you can access the basics from javascript as `loris.user.username` or `loris.user.id` when needed.
=> [JS] Add username/id to Loris helper object

jsx/Form.js
- Modified Form.js to no longer use the "selected" attribute in option tags, and rather the "value" attribute of select tags.
_If you cannot see the issue on your dev vm, you may need to delete_ `./node_modules` _and re-do_ `npm install`
1. Open the media module and press upload then switch to a few different PSCIDs
2. See if the warning appears in your console
* Resolves #8702
=> [media] React Warning on Upload Tab

modules/api/static/schema-v0.0.4-dev.yml, modules/api/static/schema.yml
When querying a specific candidate with `api/v0.0.4-dev/candidates/$id/` endpoint, the returned object looks like this:
```
{"Meta":{"CandID":"000001","Project":"COPN","PSCID":"CA0003","Site":"University of Calgary","EDC":null,"DoB":"1956-01-01","Sex":"Male"},"Visits":{"InitialVisit":"99999","SampleCollection01":"99991"}}
```
The inline_response_200_2 object should have the 'Meta' property instead of 'Candidate' as key to the Candidate object
1.
=> [YAML schema] Fix candidate key to meta

composer.lock, modules/oidc/php/callback.class.inc
Some OpenID Connect providers (ie. Globus) don't specify 'kid' in their JWKS response. The field is optional according to the spec, despite the fact that JWK::parseKeySet errors if it's not provided.
As a workaround, this manually tries each key returned until one works.
Partially resolves #8926.
=> [OIDC] Handle providers that don't provide a 'kid' parameter

tools/new_module.php
This adds a helper script to reduce the boilerplate of creating a new module.
It creates the module structure and stubs for all the files/directories in the module expected by LORIS, including `README`, help, and basic tests/test plan. The script takes a directory path as an argument, verifies that it doesn't already exist and can be written to, deduces the module name from the last part of the path, and then creates all necessary files doing the minimum of what needs to be done.
The module contains a root page and a single endpoint named "some_api" as an example.
If the --tsx option is specified, a stub tsx index is created as well.
Note: SQL is contained in the new module's directory rather than the LORIS SQL directory because the script doesn't know if it's a project or LORIS module …
=> [script] Add script to create a new module

webpack.config.js
There is an unnecessary ".js" added to the name resolution in webpack.config.js which forces the entrypoint of modules referred to by the config to be javascript. This removes it so that .ts/.tsx files can serve as the entrypoint to a module.
=> [Core] Allow module entrypoint to be written in typescript

SQL/0000-00-00-schema.sql, SQL/New_patches/2023-11-07-No-Null-Subgroup.sql, modules/dashboard/test/DashboardTest.php
Changes constraints on test_names.Sub_group so that it can not be
null.
Resolves #4268
=> [SQL] Require test_names.Sub_group to not be null

modules/issue_tracker/php/edit.class.inc, modules/issue_tracker/php/issue.class.inc, modules/issue_tracker/php/issue_tracker.class.inc
Inactive users are not displayed in dropdowns to assign / watch an issue
1. Go to Tools -> Issue Tracker
2. Make a new issue / edit an existing one -> ensure you don't see any inactive user in the "Assignee" nor "Add others to watching" dropdowns
This is a CCNA override - https://github.com/aces/CCNA/pull/4100
=> [issue_tracker] Do not display inactive users in issue form

jsx/StaticDataTable.d.ts, jsx/StaticDataTable.js
This adds a typescript module definition for StaticDataTable, so that it can be imported from typescript in strict mode without triggering errors.
It also adds a new parameter to the "getFormattedColumn" callback to indicate the current index of the column. (This should technically be a different PR, but it's easier to do it at the same time rather than need to modify the definition after.)
=> [TypeScript] Add StaticDataTable type definition

php/libraries/NDB_BVL_Instrument.class.inc
When calling bulkLoadInstanceData, currently only instrument data is bulk loaded from the database. However, calling getSessionID or getVisitLabel is almost always required in order to use the data. This bulk loads the session id and visit label from the same query when calling bulkLoadInstanceData in order to further optimize it.
=> [instruments] Bulk load SessionID and VisitLabel

jsx/DataTable.js, jsx/Filter.js, jsx/FilterForm.js, jsx/Form.js, jsx/TriggerableModal.js, modules/acknowledgements/jsx/acknowledgementsIndex.js, modules/candidate_list/jsx/openProfileForm.js, modules/conflict_resolver/jsx/fix_conflict_form.js, modules/create_timepoint/jsx/createTimepointIndex.js, modules/document_repository/jsx/categoryForm.js, modules/document_repository/jsx/docIndex.js, modules/document_repository/jsx/uploadForm.js, modules/electrophysiology_uploader/jsx/UploadForm.js, modules/examiner/jsx/examinerIndex.js, modules/genomic_browser/jsx/tabs_content/filemanager/uploadForm.js, modules/help_editor/jsx/helpEditorForm.js, modules/imaging_uploader/jsx/ImagingUploader.js, modules/imaging_uploader/jsx/LogPanel.js, modules/imaging_uploader/jsx/UploadForm.js, modules/login/jsx/loginIndex.js, modules/login/jsx/requestAccount.js, modules/login/jsx/resetPassword.js, modules/media/jsx/uploadForm.js, modules/new_profile/jsx/NewProfileIndex.js, php/libraries/NDB_Page.class.inc, test/unittests/NDB_PageTest.php, webpack.config.js
This adds the `export` keyword for the classes defined in jsx/Form.js so that they can be imported with a more standard (ie) `import {SelectElement, StaticElement} from 'jsx/Form';`. It removes the globals on `window` and replaces all references in the code with an explicit import.
This allows the element types to be imported from TypeScript strict mode without complaining about them not being defined.
=> [Core] Named form exports for Form.js

.eslintrc.json, jsx/Breadcrumbs.d.ts
A few eslint warnings crept in in #8940. This fixes them and upgrades them from warning to error so that they don't get missed by our tests in the future. (There are no other instances of these error types currently being detected by eslint.)
=> [ESLint] Fix new warnings, upgrade to error

jsx/InfoPanel.tsx
This converts the InfoPanel component from JavaScript to TypeScript in order to make it easier to import/type check in TS (without affecting the ability to load it in JS.)
(The component is small enough that this is easier than writing a .d.ts file and keeping it in sync.)
=> [TypeScript] Convert InfoPanel.js to TypeScript

tools/importers/CouchDB_MRI_Importer.php
's.ID' was being passed as a third argument to the function _getQueryForSelectedFiles, but this function only takes 2 arguments.
1. Run the CouchDB_MRI_Importer script and ensure that the QC on selected files is correctly selected.
* Resolves #8470
=> [CouchDB_MRI_Importer] Remove extra argument in _getQueryForSelectedFiles

jslib/fetchDataStream.d.ts, jslib/fetchDataStream.js
This adds a .d.ts file to accompany the functions defined in jslib/fetchDataStream.d.ts, allowing them to be type checked in typescript with noImplicitAny enabled.
=> [TypeScript] Add TypeScript module definition for fetchDataStream

modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/components/SeriesCursor.tsx, modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/components/SeriesRenderer.tsx, modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/store/logic/dragBounds.tsx, modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/store/logic/fetchChunks.tsx, modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/store/logic/timeSelection.tsx, modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/store/state/dataset.tsx, modules/electrophysiology_browser/jsx/react-series-data-viewer/src/vector/index.tsx, modules/electrophysiology_browser/jsx/react-series-data-viewer/tsconfig.json, modules/electrophysiology_browser/tsconfig.json, tsconfig.json
This enable strict mode in our TypeScript config so that we will catch as many errors as possible. The config is overloaded for the EEG Browser to disable it because the EEG browser doesn't currently passed, but this should be a short term solution.
=> Typescript strict mode

jsx/Modal.js
The Modal class uses the ButtonElement which needs to be imported to avoid runtime errors.
=> [Modal] Add missing import statement

modules/next_stage/php/next_stage.class.inc, modules/next_stage/templates/form_next_stage.tpl, modules/next_stage/test/next_stageTest.php
1. click on `Create time point` under any candidate profile. And create a time point for a new visit.
2. Open the visit you created and click on the button `Start Visit Stage` on the top left.
3. You shouldn't see the scan done dropdown menu under the `/next_stage` module
- Related to: https://github.com/aces/Loris/issues/8348
=> Remove 'Scan done' field from 'Start visit' menu

jsx/InfoPanel.tsx
This prevents errors about "ReactNode is not a valid JSX element" similar to https://stackoverflow.com/questions/72392225/reactnode-is-not-a-valid-jsx-element
The component always returns a single element, so changing the return from ReactNode to ReactElement is more descriptive at any rate.
=> [TS] Use ReactElement instead of ReactNode for InfoPanel

jsx/Form.d.ts
This adds a typescript definition file for the Form.js module so that the React props/types within it can be type checked in typescript without triggering "no implicit any" errors.
=> [Typescript] Add Form.d.ts typescript definition

Makefile, modules/publication/ajax/getData.php, modules/publication/jsx/projectFields.js, modules/publication/jsx/publicationIndex.js, modules/publication/jsx/uploadForm.js, modules/publication/jsx/viewProject.js, modules/publication/php/publication.class.inc
This fixes 2 problems with loading the publication module on Raisinbread:
1. When trying to load the page, I get the error:
```
<b>Deprecated</b>:  htmlspecialchars_decode(): Passing null to parameter https://github.com/aces/Loris/pull/1 ($string) of type string is deprecated in <b>/home/driusan/Code/Loris/modules/publication/php/publication.class.inc</b> on line <b>304</b><br />
```
with PHP 8.2.
2. The Form.js imports were missing.
=> [publication] Fix publication loading

php/libraries/NDB_BVL_Instrument.class.inc, php/libraries/NDB_BVL_Instrument_LINST.class.inc, test/unittests/NDB_BVL_Instrument_Test.php
replacing https://github.com/aces/Loris/pull/8863
Skip over metadatafields and calculate ages in surveys
This is not a big change, one way or another the fields were either being skipped with an empty check, through a project override or through code in the module itself handling the submission. this is just an explicit check to make everything clearer
1.
=> [LINST] skip metadatafields for surveys

tools/fix_timepoint_date_problems.php
Fixes https://github.com/aces/Loris/issues/5040
The script now uses 'Other' has Feedback type instead of the one with id `5` (Which was failing due to foreign key constraint if there was no feedback type with id = 5)
Also remove the part where the date of birth was determined based on the Subproject/Cohort id 1 or 2 (which does not mean anything) and now relies on Timepoint::getEffectiveDateOfBirth. I assumed that subproject 1 and 2 was making a distinction between pre ans post natal visits.  Timepoint::getEffectiveDateOfBirth should handle that.
=> [Tools] fix timepoint data problems

Makefile, modules/candidate_parameters/jsx/CandidateDOB.js, modules/candidate_parameters/jsx/CandidateDOD.js, modules/candidate_parameters/jsx/CandidateInfo.js, modules/candidate_parameters/jsx/ConsentStatus.js, modules/candidate_parameters/jsx/ParticipantStatus.js
The candidate_parameters pages were missing a number of import statements for elements from Form.js, making the page not load. This adds the missing imports.
Resolves #8968
=> [candidate_parameters] Fix loading of candidate_parameters page

CHANGELOG.md, modules/bvl_feedback/ajax/open_bvl_feedback_thread.php, modules/bvl_feedback/jsx/react.behavioural_feedback_panel.js
This PR fixes the bvl_feedback module to update the summary in real time after opening or closing feedbacks. The PR also fixes a `Unexpected end to json input ` react error when opening and closing feedbacks by changing the success response to a json response.
1. Off of the main branch, load the bvl_feedback module by clicking the edit icon in the top right of a candidate, visit, or instrument page.
2. Save a few new feedbacks, and notice that the number of open feedbacks in the summary at the top increases every time you save a feedback.
3. Open and close a few feedbacks, and notice that if you open a closed feedback, it still shows as closed until you refresh the page. The summary at the top also does not change until you refresh the page.
4. Load this PR and repeat the previous steps. …
=> [bvl_feedback] Update summary in real time

modules/datadict/php/module.class.inc, modules/dictionary/php/module.class.inc
The "beta" dictionary module was added in LORIS 24, and tested in both 24.1, and 25. When 26 is released, it will be the 4th release including it. Its API is also used by the conflict resolver to get field descriptions.
It should no longer be considered beta.
This removes the "beta" tag from the description in the menu, and adds a "legacy" to the old datadict, which needs to be maintained until the new DQT is released (based on the new dictionary.)
=> [dictionary] Remove beta tag from dictionary module

jsx/DataTable.js
When hide defaultColumn is set to true the DataTable hides the table header but doesn't hide the column in the datatable. This fixes the bug so that the column is hidden and not just the column header.
=> [DataTable] Fix hide defaultColumn

modules/instrument_list/php/instrument_list_controlpanel.class.inc
Fix the warnings:
```
<b>Deprecated</b>:  strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in <b>modules/instrument_list/php/instrument_list_controlpanel.class.inc</b> on line <b>475</b><br />
<br />
<b>Deprecated</b>:  strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in <b>modules/instrument_list/php/instrument_list_controlpanel.class.inc</b> on line <b>514</b><br />
```
in PHP 8.2 and above (and maybe below, I didn't check.)
=> [instrument_list] Fix deprecation warning

php/libraries/NDB_BVL_Instrument_LINST.class.inc
@zaliqarosli some changes derived from the QPN overrides that I believe apply to LORIS
- add fields to XIN validation which are not parts of groups
=> [LINST] fix survey and date issues

jsx/Modal.js
- Adds a width prop to Modal so that it can be changed from the default 700px
- This exists in the main branch, but was not added to v24 for some reason
- This would be used in CCNA v24.1 upgrade, and would also be useful for any other projects on 24 that use modals
1. Add the width prop to a modal such as `width={'1000px'}` and see if the modal is larger than before
=> [JSX] Modal Width Prop

php/libraries/User.class.inc, test/unittests/UserTest.php
We found this bug on CCNA where if a user has the same full name as another user, the examiner sites from the other user will show up in the edit user page. 
1. Outside of this PR, Create 2 users with the same name
2. Set one user as examiner at multiple sites
3. Go to the other user, and see that the same sites show up as examiner
4. Try to remove the examiner sites and notice that you cannot
5. Checkout this PR and refresh the second user (without the examiner sites)
6. Now you should not see examiner sites where they are not meant to be
=> [libraries] Get examiner sites by UserID

modules/genomic_browser/jsx/tabs_content/files.js, modules/genomic_browser/php/filemanager.class.inc, modules/genomic_browser/php/uploading/genomicfile.class.inc
Made the name column a link for downloading. Note: This module needs refactoring of the upload and download logic to be more robust.
* Resolves #7594
remake of #7856
=> [genomic_browser] Download button not showing up in the Files tab

modules/configuration/ajax/updateCohort.php
[Config] Subproject recruitment target can be larger than its Project target #5832
The Config module should probably pop up a warning, e.g. Your Subproject recruitment target is greater than the Project recruitment target -- if not enforce a relationship.
(See Staler (SubprojectID 1) on test-loris-dev today, tho not RB -- has Recruitment target 1000000000)
test 
1. goto configration module then click "To configure study cohorts [click here]"
2. input a number of recruitment target, try larger than project's  and  smaller than project's
=> add greater than project's recruitmentTarget message for cohort

modules/api/docs/LorisRESTAPI_v0.0.4-dev.md, modules/api/php/endpoints/candidate/visit/instruments.class.inc, modules/api/static/schema-v0.0.4-dev.yml, raisinbread/test/api/LorisApiInstrumentsTest.php
This implements a `/candidates/{id}/{visit}/instruments` `POST` endpoint which allows you to programmatically add an instrument to a candidate's battery through the LORIS API.
The `POST` endpoint takes input in the same format as `GET`, but adds any missing instruments to the battery instead of simple returning the existing test battery. It returns the new battery.
=> [api/instruments] Add endpoint that allows you to add instruments to a battery

modules/api/php/endpoints/candidate/visit/image/image.class.inc
There is an error message in the web server logs when a file is in the database but not on the filesystem but it doesn't tell you where it was looking on the filesystem. This adds the full path to make it easier to determine where LORIS is trying to find the file when ie. setting up raisinbread.
=> [api] Log filename in error message

modules/issue_tracker/jsx/IssueForm.js, modules/issue_tracker/php/edit.class.inc, modules/issue_tracker/test/issue_tracker_test_plan.md, smarty/templates/email/issue_assigned_modified.tpl, smarty/templates/email/issue_change.tpl
- Fixed issue where the assignee dropdown did not show the current assignee
- Emails users who were added as watching
- When a comment is added, it adds it to the email to everyone watching
1. Open the issue tracker and add a user with your email address as the watcher to an issue
2. Confirm that you received an email about the issue
3. Try changing various fields and confirm an email is sent for each with some context.
CCNA Overrides:
https://github.com/aces/CCNA/pull/3889
https://github.com/aces/CCNA/pull/4618
Old PR To Loris Core Main:
https://github.com/aces/Loris/pull/8850
=> [Issue Tracker] Issue Change Notifications

modules/behavioural_qc/jsx/tabs_content/behaviouralFeedback.js
The visit Level feedback was included as part of the `formatColumn()` function in the `BehaviouralFeedback` class file `/modules/behavioural_qc/jsx/tabs_content/behaviouralFeedback.js`
1. Go to `MainMenu-> Clinical -> Behavioural Quality Control`.
2. Then go to the `Behavioural Feedback` tab.
3. All the columns should show properly now.
4. The links should be also properly working.
* Resolves #8037
=> [behavioural_qc] fixes visitLevel feedback not showing up.

modules/battery_manager/test/TestPlan.md
- Update test plan for Battery Manager with the requested changes
* Resolves #8739
=> [battery_manager] Update Test Plan

modules/electrophysiology_browser/jsx/react-series-data-viewer/src/eeglab/EEGLabSeriesProvider.tsx, modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/components/LineChunk.tsx, modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/components/SeriesRenderer.tsx, modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/store/logic/fetchChunks.tsx, modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/store/state/dataset.tsx
Closes #8992. Has a Loris-MRI counterpart: aces/Loris-MRI#1030
Loosely dependant on #8998 (file modifications in common and done at a later time).
This PR resolves the data shift issue by adding the number of valid samples in the last chunk to the index.json, and using it for the calculations which previously assumed all chunks were filled.
Testing: Zoom in so that the last chunk of the recording is in frame and ensure that the signal does not flatline at the end. You can also compare the values in the chunk payload with the value obtained by hovering the signal at a given time.
=> [electrophysiology_browser] Fix EEG data shift

CHANGELOG.md, modules/candidate_parameters/ajax/getData.php, modules/candidate_parameters/jsx/CandidateDOB.js, modules/candidate_parameters/jsx/CandidateDOD.js
This PR uses the DoB and DoD format from configuration in the DoB and DoD tabs respectively.
1. Modify the DoB and DoD format in the configuration module
2. Make sure that these formats are respected in their respective tabs in the candidate parameters module
3. Try saving the DoB and DoD in each new format, make sure it saves properly and loads properly
4. Make sure to test on candidates _with_ and _without_ DoB and DoD
* Resolves #6994
=> [candidate_parameters] use DoB and DoD format

modules/my_preferences/php/my_preferences.class.inc, modules/my_preferences/php/userpreferencewidget.class.inc, modules/my_preferences/templates/form_my_preferences.tpl
This adds a new widget type, "userpreference" which allows modules to plug content into the user's my_preferences page.
It works similarly to the candidate_profile widget, where it assumes each call will return an array of UserPreferenceWidget's to add to the page, each one denoting a single react component. The UserPreferenceWidget must have:  
1. A title to display as a heading
2. A URL to get the javascript for the component
3. The component name to instantiate
4. React props to pass to the widget
This is useful for ie. the OIDC module adding a widget where the user can link an external openid account to the logged in user, but can also be used for any other modules which have preferences that should be configurable by the user on the my_preferences page.
=> [my_preference] Add support for my_preference widgets

modules/data_release/php/data_release.class.inc
[data_release] Can not sort by version #8621
sort the data_release table by version (Unversioned)
[data_release] Can not sort by version #8621
=> fix data release sort issue

modules/instrument_builder/jsx/react.questions.js
https://github.com/aces/Loris/issues/9037
Go to 'instrument_builder'
Click on 'Data entry'
create any data entry will cause the error
textbox
textarea
....
=> [instrument_builder] - fix blank page

modules/instrument_list/templates/menu_instrument_list.tpl
- Changed the behaviour of showcasing the Candidate Registration Project on a visit's page. If the Timepoint Project differs from the Candidate Registration Project then it displays them separately, if they are the same then it shows the project under "Project"
Timepoint with a different project than the Candidate:
<kbd>
</kbd>
Timepoint with the same project as the Candidate:
<kbd>
</kbd>
1. Try adding a timepoint to a candidate with a different project
2. See that it shows the correct Timepoint Project and Candidate Project
3. Try different combinations including same timepoint and candidate project
* Resolves #8784  (Reference the issue this fixes, if any.)
=> [Instrument List] Show Timepoint Project

.phan/config.php, CHANGELOG.md, SQL/0000-00-00-schema.sql, SQL/New_patches/2024-01-29-create-sex-table.sql, modules/candidate_list/jsx/candidateListIndex.js, modules/candidate_list/php/candidate_list.class.inc, modules/candidate_parameters/ajax/getData.php, modules/candidate_parameters/jsx/ProbandInfo.js, modules/candidate_parameters/php/candidatequeryengine.class.inc, modules/genomic_browser/jsx/tabs_content/cnv.js, modules/genomic_browser/jsx/tabs_content/methylation.js, modules/genomic_browser/jsx/tabs_content/profiles.js, modules/genomic_browser/jsx/tabs_content/snp.js, modules/genomic_browser/php/views/cnv.class.inc, modules/genomic_browser/php/views/methylation.class.inc, modules/genomic_browser/php/views/profiles.class.inc, modules/genomic_browser/php/views/snp.class.inc, modules/new_profile/php/new_profile.class.inc, php/libraries/Utility.class.inc, src/StudyEntities/Candidate/Sex.php, test/unittests/CandidateTest.php, tools/CouchDB_Import_Demographics.php
This PR changed the datatype of the candidate table columns "Sex" and ProbandSex" from enum to varchar(255), instead creating a constraint on the columns determined by a new "sex" table. 
The "sex" table contains optional values for candidate sex and candidate proband sex. Projects can add or remove Sex options by simply inserting into or dropping from this table. 
I also modified anywhere that I could find that was hardcoding Sex options to instead get the sex options from the database through a Utility class function.
1. Test creating a new candidate. Make sure that the sex is inserted into the candidate table properly. 
2. Set "use proband" config setting to true in the config module, and then test the proband tab of candidate parameters
3. Go to the candidate list module and select …
=> [candidate] Create Sex table and remove Sex enum

modules/configuration/jsx/DiagnosisEvolution.js, modules/imaging_qc/jsx/imagingQCIndex.js
Fix eslint warnings about console.log that slipped through the code review of the PRs where they were merged.
One was a debug statement left behind, and 2 were the incorrect log level.
=> [Cleanup] Remove console.log

modules/instrument_list/templates/instrument_list_controlpanel.tpl
- Refresh page when stage changes
1. Try changing the stage of a timepoint and see that the stage updates in the main page.
2. See issue for a video demo
* Resolves #6988 (Reference the issue this fixes, if any.)
=> [Instrument List] Refresh on Stage Update

jsx/Filter.js, modules/battery_manager/jsx/batteryManagerForm.js, modules/battery_manager/jsx/batteryManagerIndex.js
Fix missing imports in the battery manager and its dependencies (`jsx/Filter.jsx`), which prevented the main page of the battery manager from loading.
- Resolves #9062
=> fix missing imports

modules/instrument_list/php/instrument_list_controlpanel.class.inc
Port of #8867 for `24.1`, needed in [HBCD#1640](https://github.com/aces/HBCD/issues/1640).
=> [instrument_list] Fix deprecation warning (24.1)

modules/login/jsx/passwordExpiry.js
The password expiry page was missing imports for jsx/Form. This adds the imports that were missing referenced in the code.
=> [login] Add missing imports on password expiry page

modules/mri_violations/php/mri_violations.class.inc
The permission violated_scans_view_allsites does not work anymore for the module. This fixes the issue.
=> [MRI Violations] Fix violated_scans_view_allsites permission

htdocs/index.php
Removes `lorispath` from the PSR7 request's query parameters and uri query string (both must be updated separately).
Manipulating arrays in PHP is so verbose 😴.
var dump `$serverrequest`
* Resolves #9049
* Enables #9041
=> Remove lorispath from PSR7 request

modules/dataquery/jsx/definefilters.tsx
The strike-through effect on a line is only supposed to happen when hovering over the trashcan icon. After clicking it, "onMouseLeave" event doesn't fire, causing the component's state to remain in a state where the last index is "hovered". As a result, the next time you add a filter upon deleting the last one it has an incorrect strike-through effect.
This resets the hovered index onClick in addition to onMouseLeave to fix the issue.
Resolves #9076.
=> [dataquery] Fix bug where field is incorrectly striked-through

modules/mri_violations/README.md, modules/mri_violations/test/TestPlan.md
Updated TestPlan and Readme of mri_violations module. Changes made:
1. New step in TestPlan to check that the links in the Image File tab take you to the correct page in the Brainbrowser module.
2. Clarify in TestPlan and Readme that the dashboard widget displays the total number of **Unresolved** violations.
Resolves #9093
=> [mri_violations] Update module TestPlan and Readme

modules/dataquery/jsx/nextsteps.tsx
Shifts the block few px away from the right window side so the right arrow can be accessed anytime.
* Resolves #9065
=> [dataquery] shift next step box to the left

htdocs/main.css
issue #9087
This PR fixes the help widget height extending over a page
=> [help] fix the help widget extending over the height of a page

htdocs/main.css
- There was a line in the css file `font-color #000000:` that has been removed as it looks like a typo
- The line does nothing as font-color is not a css property. The line was problematic since it should have a colon after font-color, and a semi-colon after the line.
=> [help] Remove typo from CSS

php/libraries/NDB_BVL_Instrument_LINST.class.inc
For LINST instruments, some can have very long line (i.e. lots of options for select/dropdown).
These lines are bigger than the currently defined buffer read size i.e. `4K` and triggers visible warnings.
E.g. for HBCD, one instrument generated from REDCap has one line with 15869 characters. 
The line is truncated and some select options cannot be read.
https://github.com/aces/HBCD/issues/1725
This PR pushes the buffer size to `128K`.
1. Try accessing a LINST instrument with a very long line.
E.g. 
```
select{@}very_long_line{@}This line is very long{@}NULL=>''{-}'1'=>'0.1'{-}'2'=>'0.2'{-}'3'=>'0.3'{-}'4'=>'0.4'{-}'5'=>'0.5'{-}'6'=>'0.6'{-}'7'=>'0.7'{-}'8'=>'0.8'{-}'9'=>'0.9'{-}'10'=>'1.0'{-}'11'=>'1.1'{-}'12'=>'1.2'{-}'13'=>'1.3'{-}'14'=>'1.4'{-}'15'=>'1.5'{-}'16'=>'1.6'{-}'17'=>'1.7'{-}'1 …
```
=> Augment LINST instrument read buffer

modules/data_release/php/data_release.class.inc, modules/data_release/php/datareleaseprovisioner.class.inc, modules/data_release/php/datareleaserow.class.inc
Refactoring module
1. All previous functionalities should be unchanged after adding the data framework.
* Resolves #6055
=> [data_release] refactoring to use data framework.

modules/candidate_profile/jsx/CandidateInfo.js
1. Under `Candidate profile` go to any candidate and see the Ccandidate info card you will notice that the cohort info is displaying incorrectly. After fetching the new changes and `npm run compile` you will notice the fields are separated by comma.
- https://github.com/aces/Loris/issues/9090
=> [candidate_profile] Fixing the display of cohorts in candidate Info card

modules/configuration/jsx/configuration_helper.js
The handler in `configuration/jsx/configuration_helper.js` was not properly taken the option to be deleted since the fields not always have necessary to be of SELECT type (they could be also text for example).
Now it should take the appropriate option to be deleted.
1. Please go to configuration module `MainMenu->Admin->Configuration`
2. Go to one of the "Tabs" that allow multiselect (for example `MINC to BIDS Converter Tool Options` )
3. Create some options and try to delete they after
5.  Test **Confirming** and **Canceling** 
6.  The field should be deleted under confirmation.
7.  Please test also with "other data type" (for example instruments in Study tab)
* Resolves #9096
=> [configuration] Fix option deletion issue.

SQL/New_patches/2024-02-31-api_docs_permission_visible.sql, raisinbread/RB_files/RB_permissions.sql
Adding moduleID value to existing projects/raisinbread (already in main schema) because without it the permission does not show up
=> [api_docs] add ModuleID to permission

modules/new_profile/test/TestPlan.md
This PR updates the test plan of the `new_profile` module. The test plan now specifies that all fields on the form should be filled out in order for the form to be valid with one exception: if you have `useEDC` turned on you can get away with not entering the DoB.
Fixes #9141
=> [new_profile] Test plan update

tools/generate_tables_sql_and_testNames.php
The `tools/generate_tables_sql_and_testNames.php` script is causing an error when uploading a new instrument using the Instrument Manager module. Since the output string was being reset to empty within the for-loop, the "Create Table" statement was not properly generated. 
1. Go to the instrument manager module and try uploading the `/test/instruments/test_all_fields.linst` file
2. Check that there is a success message and that the project folder and database are correctly updated with the new instrument.
=> [instrument_manager] Fixing error in generate_tables_sql_and_testNames tool

modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/components/AnnotationForm.tsx, modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/components/DatasetTagger.tsx
=> [electrophysiology_browser] Minor HED display modifications

modules/issue_tracker/php/edit.class.inc
This PR:
- Forces an internal server error JSON response on db update error, which allows to actually see front-end swal error.
- Bug fixes the "null" userID assignee that was the current user (i.e. added based on a composed string "full name (userid)").
1. Go to Report > issue tracker
2. click on "new issue".
3. assert no "null" user is in the "assignee" dropdown
4. create new issue with some basic fileds.
5. click inside the previously created issue inside the main issue tracker table.
6. click on "assignee" dropdown.
7. assert no "null" user is in the "assignee" dropdown.
* Resolves #9128
=> [issue_tracker] null option assignee

npm-postinstall.js, webpack.config.js
- Fix a WebpackMissingModule error with the EEGBrowser when EEGVisEnabled is set to "1" | "0" instead of "true" | "false".
- Turn the webpack cache to off as it contributes to the heap memory issues for users with less than 2GB Ram. In dev mode, all cache is stored in memory. Alternatively, if build speed is impacted, it can also be set to filesystem.
=> EEGVisEnabled check issue and webpack cache

jsx/StaticDataTable.js
When mixing numbers with strings in an instrument field value (e.g. text field) results in a DQT column that has a sorting issues. This happened for a "summary" instrument in HBCD project that import results from multiple other instruments. This instrument has to clearly display the value of the field (i.e. numeric) or "No data" (i.e. string).
1. Apply numeric values in an instrument field.
2. Run the DQT update (dict build + DQT imports).
3. Make a DQT query that contains the right fields/columns.
4. Try to sort these columns.
5. See error.
Linked to [HBCD#1652](https://github.com/aces/HBCD/issues/1652)
=> StaticDataTable mixed column types sorting

tools/detect_duplicated_commentids.php
Update the select query from `pselectRow` to `pselect` on line 105 under [tools] detect_duplicated_commentids.php file
Have you updated related documentation?yes, [tools] detect_duplicated_commentids.php file
Issue: https://github.com/aces/Loris/issues/8060
rebase: https://github.com/aces/Loris/pull/8305
=> [tools] Fix SQL error for duplicate rows

modules/imaging_browser/php/viewsession.class.inc, modules/imaging_browser/templates/form_viewSession.tpl
While browsing Loris code, I stumbled upon a button in view session that appears to be broken / dead code in the imaging browser:
- The button points to the `BrainBrowser/display.html` URL. However, there seems is no such file in LORIS.
- The button uses a relative link, which is probably wrong.
- The button is only displayed if a session has a corresponding "obj" file in the database. However, there is no such file in Rainsinbread.
Thus, I open this PR to remove this button. But before merging it, I'd like to know if anyone has any information regarding the button or its display condition.
Pinging the imaging squad @ridz1208 @cmadjar @laemtl.
=> [imaging browser] Remove apparently unused button

modules/statistics/php/statistics_site.class.inc
fix issue 
https://github.com/aces/Loris/issues/9137
[CRITICAL] /var/www/Loris/php/libraries/User.class.inc:476: Uncaught TypeError: User::hasProject(): Argument #1 ($projectID) must be of type ProjectID, string given, called in /var/www/Loris/modules/statistics/php/statistics_site.class.inc on line 134 and defined in /var/www/Loris/php/libraries/User.class.inc:476
Bug 
https://test-dev-260.loris.ca/statistics/statistics_site/?CenterID=2&ProjectID=1
=> [statistics] bug fix - projectID issue

modules/login/jsx/passwordExpiry.js
StaticElement
https://github.com/aces/Loris/issues/9143
[login] Update password page still accessible with expired one-time password #9144
Testing reset password page and submitting two mismatching passwords, it will show the error, not the blank page.
=> [Login] password reset page-  missing element import

CHANGELOG.md, modules/publication/jsx/projectFields.js
In this PR the deleteUpload function of ProjectFormFields class in projectFields.js is fixed by changing the syntax of the swal.
1. Propose a project with a file
2. Edit that project and attempt to delete the file. 
3. When you click the X next to the file, a swal should show up.
4. If you click "No, cancel it" in the swal, make sure that the file is kept.
5. If you click "Yes, I am sure" in the swal, make sure that the file is removed.
* Resolves #9135
=> [Publication] Fix deletion of file when editing project

modules/statistics/templates/form_stats_MRI.tpl
The checkboxes had alignment issues
1. Go to the statistic module
2. go to Imaging Statistics
3. Check the alignment of the checkboxes
* Resolves #9140
=> [Statistics] Fix checkbox places in Imaging Statistics

modules/new_profile/test/TestPlan.md
Updated the testplan for new_profile to reflect that min and max ages are calculated based on StartYear and EndYear respectively, which can appear to be a bug.
=> updated testplan for new_profile to specify age calculation

modules/document_repository/jsx/uploadForm.js, modules/document_repository/php/files.class.inc
[document_repository] Uploading file too large not reporting correctly #9158
upload a large file more than 1 GB, it will popup a error message "file too large"
=> [document_repository] Uploading file too large not reporting correctly #9158 - fix

SQL/New_patches/2024-03-11-changePermissionCodeToDictionary.sql, modules/conflict_resolver/README.md, modules/conflict_resolver/php/conflict_resolver.class.inc, modules/conflict_resolver/test/TestPlan.md, modules/conflict_resolver/test/conflict_resolverTest.php, modules/dashboard/test/DashboardTest.php, raisinbread/RB_files/RB_permissions.sql
Makes changes to reflect the necessity of dictionary edit and view permissions in order to access the conflict resolver module. This includes:
- the addition of checks for relevant permissions
- an update to the readme and test plan files
- an sql patch which changes the permission code prefixes  from 'Data Dictionary (legacy)...' to 'Dictionary...'
* Resolves #9095
=> [Conflict Resolver] readme + permission edits to reflect the need for datadict permissions

modules/examiner/jsx/examinerIndex.js
=> [examiner] fix error message display format

modules/dataquery/help/dataquery.md
This adds help text for the new dataquery module. The help text is adapted from the "Introduction" panel on the front page and largely says the same thing, but unfortunately can't display the icons that come from React components so instead uses text description of them.
Fixes #9129
=> Add help text for new data query module

modules/new_profile/jsx/NewProfileIndex.js, modules/new_profile/test/TestPlan.md
This PR ensures that if a user is associated to only one site and creates two candidates in a row, his/her site will be automatically selected on the new profile form when the form is first displayed and when he/she clicks on 'Recruit another candidate'. It also updates the module's test plan to cover this scenario.
Fixes #9146
=> [new_profile] Site not selected when recruiting another candidate

php/libraries/NDB_Notifier.class.inc
Display the name of the user instead of their ID in the notification emails.
1. Trigger an email notification which displays the sender name in the email (such as media file upload).
* Resolves #9202
=> [notification] Fix sender name in email

modules/statistics/php/charts.class.inc, modules/statistics/php/widgets.class.inc
The recruitment graphs on the dashboard provided by the statistics module are not efficient. They run one SQL query per month per year per site for each graph that is displayed. This is highly inefficient for large projects.
This replaces the single queries in the inner loops with a single group-by query which it processes into the same format.
The result should be significantly faster load times on the dashboard when the statistics module is loaded.
1. Load the LORIS dashboard with and without this change. The load time should be significantly faster for on-going projects with a lot of sites or spread over a long amount of time. The results returned should be identical.
=> [statistics] Recruitment graph optimization

modules/publication/ajax/getData.php, modules/publication/jsx/viewProject.js
- The value expected by the field is the number id, but the fetch statement was returning the name - so I modified the sql statement to fetch the project ID.
1. Propose a new project in the publication module and remember the project name
2. Submit and then go back to the main module and select it and make sure the project is auto selected
* Resolves #9134  (Reference the issue this fixes, if any.)
=> [Publication] Fix for auto-selecting Project in edit

modules/media/ajax/FileUpload.php, modules/media/jsx/uploadForm.js
[media] 413 error improperly handled #9163
upload a large file more than 1 GB file, it will show the error message.
=> [media] 413 error improperly handled #9163 - fix

modules/publication/php/files.class.inc
Closes #9133.
An error regarding the non-existence of a `notification_module` with module: `publication` and operation: `download` prevented the downloading of files.
The notification function was overridden for this module to bypass the `LorisException` thrown by the non-existence of entries. It appeared by far to be a simpler solution than checking for and adding extra logic when the entries do not exist.
=> [publication] Fix download prevention by overriding download notification function

modules/publication/ajax/FileUpload.php, modules/publication/jsx/uploadForm.js, modules/publication/jsx/viewProject.js
- The loris baseURL is now sent from the react pages to the ajax scripts on submit for both editing and uploading a new publication, and then is sent in the email.
- I did it this way as `\NDB_Factory::singleton()->settings()->getBaseURL()` does not work in ajax files, and since it is deprecated it made more sense to do a hotfix rather than investigating the issue with ajax.
- This was noticed and fixed for files in php folders in #7807, however that same fix does not work for ajax. Thankfully publication is the only module with ajax still that uses getBaseUrl().
1. Open the publication module and propose a project, enter a real email and make sure to press send email to lead investigator. 
2. Check your email and confirm that the link is complete
3. Try editing a publication and make …
=> [Publication] Fix baseurl missing from emails

modules/instrument_builder/jsx/react.questions.js
1. go to instrument builder
2. create a score element
3. make sure it is added correctly
#9152
=> [isntrument_builder] blank page when trying to add a score 

modules/candidate_parameters/test/candidateQueryEngineTest.php, src/Data/Query/SQLQueryEngine.php
Use a batch insert instead of a prepared statement loop to populate temporary table in new DQT for SQLQueryEngine.
This makes the SQLQueryEngine use the same logic as modules/dataquery/php/query.class.inc, which is much more efficient for large data sets such as the UK biobank.
=> [dataquery] Use batch insert instead of prepared statement

tools/exporters/data_dictionary_builder.php
Fix the data_dictionary_builder.php script 
~~by enforcing the unique key constraint Name + SourceFrom.~~
by reducing the scope of the main query to instruments. Instruments have unique parameter names, and the script is intended to  build a dictionary for instruments. 
Error below was encountered with EEG/MRI parameter_file fields.
Error seen when 2 parameter_type entries share the same Name:
```
lorisadmin@smathew-dev:/var/www/loris/project/tools/exporters$ php data_dictionary_builder.php
Could not execute Select Name, ParameterTypeID from parameter_type. Stack trace#0 /var/www/loris/project/tools/exporters/data_dictionary_builder.php(60): Database->pselectColWithIndexKey()
#1 {main}
PHP Fatal error:  Uncaught DatabaseException: The uniqueKey supplied to pselectColWithIndexKey() does …
```
=> data_dictionary_builder.php unique constraint fix

modules/dataquery/php/query.class.inc
The Query class in the dataquery module includes an IsAccessibleBy function to check accessibility of a query by checking if the user has access to all fields used in the query (for both fields and filters). It currently caches the data dictionary of a module the first time it's used to avoid having to re-retrieve the dictionary for every field. However, each Query object instance has its own cache.
This changes the dictionary cache to be a static variable so that it can be shared across different instantiations of the object. This significantly speeds up the `/dataquery/queries/` endpoint which applies an AccessibleResource filter to every query returned by a provisioner.
=> [dataquery] Share cache of module dictionary across queries

modules/survey_accounts/js/survey_accounts_helper.js
=> Survey Module Validation Fix

modules/help_editor/test/TestPlan.md
1. The Test plan should now accurately reflect the content of the module and how to test it.
* Resolves #8624
=> [help_editor] Updates Test plan.

modules/candidate_parameters/php/candidatequeryengine.class.inc
The "Sex" data type is incorrectly returning an object instead of an array for the field options of the dictionary because \Utility::getSexList returns an associative array, not an array.
This fixes it so that the dictionary module loads.
=> [dictionary] Fix loading of dictionary module

php/libraries/NDB_BVL_Instrument.class.inc
getCandID in the instrument class was incorrectly returning a string instead of a CandID object. (Since the function was recently added, we still have a narrow window to fix it before the release with little chance of it having been used elsewhere in the code.)
=> [instrument] Fix data type of getCandID function

babel.config.js, package-lock.json, package.json
This seems to fix the issue found during the testing meeting, where there was a problem in the compilation of JS modules (found in the dataquery but probably in other places too).
For me, it looks like a clean solution, as we probably want to "unmodule" our code as late as possible, and thus in Babel, but I am not sure what caused the problem in the first place sooo.
=> Fix webpack compilation of JS modules

modules/dataquery/jsx/definefilters.addfiltermodal.tsx, modules/dataquery/jsx/hooks/usebreadcrumbs.tsx, modules/dataquery/jsx/types.tsx, modules/dataquery/jsx/viewdata.tsx, modules/dataquery/php/module.class.inc, modules/dictionary/php/moduledict.class.inc, php/libraries/LorisFormDictionaryImpl.class.inc, php/libraries/NDB_BVL_Instrument_LINST.class.inc, src/Data/Types/Enumeration.php
The dataquery module was showing the backend enum value, rather than the frontend label, which isn't very useful to most users.
This adds an option for the user to select how they want to display enums.
It also updates the menu label from "alpha" to "beta" since the module has now been tested with large data sets.
=> [dataquery/dictionary] Add option to display enums as either value or field in dataquery module

modules/next_stage/test/TestPlan.md
This PR updates the test plan of next_stage module because there is no longer a "scan done" option (#8955). This step is removed from the testing instructions
=> [next_stage] Update test plan

modules/api/php/endpoints/candidates.class.inc, modules/new_profile/jsx/NewProfileIndex.js, modules/new_profile/php/new_profile.class.inc, modules/new_profile/test/new_profileTest.php
It seems like until this PR any user, regardless of their projects, could create participants for any other project. This is very problematic on the institutional LORIS instances like CBIG and BHI.
Currently submitted to CBIG as an override
=> [new_profile] Make list of available projects user dependent

CHANGELOG.md, modules/conflict_resolver/php/module.class.inc, modules/dashboard/php/taskquerywidget.class.inc, modules/dashboard/test/DashboardTest.php, modules/imaging_browser/php/module.class.inc, modules/instruments/php/module.class.inc, modules/issue_tracker/php/module.class.inc, modules/user_accounts/php/module.class.inc
This PR adds a project filter for TaskQueryWidget so that a user will only see the relevant tasks to their own project assignments.
1. Login with a user that has only one project
2. Check that all of the task counts are relevant for only that project
3. Take note that the Imaging tasks may not reflect what is shown in the table results that it links to, I have created a separate issue [here](https://github.com/aces/Loris/issues/9219) for that.
* Resolves #9130
=> [dashboard] Add project filter for tasks widget

modules/statistics/jsx/widgets/chartBuilder.js
This bug was noticed while testing a different module.
The `Study Progression - site scans` graph on the dashboard has a few instances of this bug: [spaces added to avoid cross-linking: github.com /c3js/ c3/issues/1885], where the timeseries goes back in time in order to make a smooth spline.
The simple fix was taken from the same issue.
Example pre-fix:
=> [statistics] Fix timeseries graph spline bug

modules/issue_tracker/test/issue_tracker_test_plan.md
Updated testplan to reflect that 'assignee' should not be required when creating an issue. 
https://github.com/aces/Loris/issues/9253#issuecomment-2103084392
=> [Issue_tracker] Updated testplan to reflect that 'assignee' should not be required when creating an issue

jsx/DatetimeElement.tsx, jsx/Filter.js, jsx/form/DateTimePartialElement.tsx, modules/mri_violations/jsx/mriViolationsIndex.js
Add a `DatetimeElement` to input datetime information, which can be used to filter table columns with both dates times.
I originally developed this custom input last thursday, but then learned that this kind of input already exists in HTML `<input type="datetime-local" step="1" />`. However, the HTML input only allows to enter complete datetimes, which is not what we want as a filter should work even with incomplete information.
I wrote my input in a separate file from `jsx/Form` to use a more modern technology stack (Typescript / functional React) from those. However, I still follow their structure somewhat closely.
1. Go to MRI violations,  filter entries by datetime.
* Resolves #9091
=> [form + mri_violations] Add DatetimeElement to filter fields by date and time

modules/dataquery/jsx/definefields.tsx
When a field is removed by the trashbin icon, the onMouseLeave for the hover effect doesn't fire as the component is unmounted. When a new field is added, the wrong "hover" index is set and it incorrectly shows a strike-through effect.
This is effectively the same fix as #9104 on a different tab.
Resolves #9249
=> [dataquery] Fix strikethrough effect when field re-added

modules/login/jsx/loginIndex.js, modules/login/test/Login_Redirect_Test_Plan.md, smarty/templates/403.tpl, src/Http/Error.php
Whenever an unauthenticated gets a 403 error, they can try logging in and be redirected to the page they got the 403 on.
1. Go to a page that exists and require authentication while not being authenticated.
2. Click "Try logging in"
3. Log in (after one or several tries)
4. You are redirected to the previous page
I implemented this using an URL query parameter, but I guess using `window.history` could also have worked. If anyone has an opinion on this please tell me.
=> [Login] Add login suggestion and redirection for error 403

modules/dataquery/php/module.class.inc
The dataquery module uses the dictionary module's API to load the data dictionary. A user needs access to it for the dataquery module to load.
Fixes #9244
=> [dataquery] Require access to dictionary module

tools/data_integrity/score_instrument.php
The score_instrument script breaks with JSON data. This updates the script to use getInstanceData() instead of trying to write an SQL query directly so that it works no matter what format the instrument saves data in.
=> [score_instrument] use getInstanceData to get the instrument data

tools/recreate_conflicts.php
Refactored `recreate_conflicts.php` to replace the deprecated `Utility::getAllInstruments()` function with `NDB_BVL_Instrument::getInstrumentNamesList($lorisInstance)
`
1. Navigate to /var/www/loris/tools.
2. Run the script with the command `php recreate_conflicts.php all`.
3. Verify that the script runs without the deprecation error and correctly retrieves all instrument names.
* Resolves #9267
=> [tools] Refactor recreate_conflicts.php to use getInstrumentNamesList()

modules/imaging_uploader/jsx/UploadForm.js
When config option ImagingUploaderAutoLaunch is on and you successfully upload a scan, there is a popup that appears indicating that the MRI pipeline has been launched in order to process the scan. This PR makes the popup modal (i.e user has to click Ok for the popup to disappear).
Fixes #9286
=> [imaging_uploader] Make auto-launch info popup modal

modules/electrophysiology_browser/jsx/react-series-data-viewer/src/series/components/EEGMontage.tsx
Add a colormap to flag specific channels in the EEG montage:
To enable it, add the following in In `modules/electrophysiology_browser/jsx/electrophysiologySessionView.js`
```
<EEGMontage colorMap={
{ 
color: '#FF0000',
ids: [1,2,4,7] // index of electrodes to include in the colorMap
}
} />
```
=> [EEG] Montage color map

tools/generate_tables_sql.php, tools/generate_tables_sql_and_testNames.php
This PR forces the `decimal(14,4)` (10 digits on the integer part, and 4 digits on the floating point part), instead of `decimal(10,0)` which is the default for `numeric` and was truncating floating point digits. 
It only applies this change for instruments that require their own table (non JSON) and have `numeric` attribute.
1. use `tools/generate_tables_sql.php` and `tools/generate_tables_sql_and_testNames.php` with a **non JSON LINST instrument** with at least a `numeric` type line.
2. the resulting SQL should be a valid SQL code that add a `decimal(14,4)` type for the numeric attribute, instead of a `numeric` attribute.
Resolves #9237
=> Defining default decimal point for non JSON table LINST instruments

modules/statistics/php/statistics_dd_site.class.inc, modules/statistics/php/statistics_mri_site.class.inc, modules/statistics/php/statistics_site.class.inc
Update queries in statistics_site to not rely on instrument tables for the counts.
All the data required for the query was already in the flag table without having to join the data table.
Fixes #9232
=> [statistics] Do not depend on instrument table for queries

modules/electrophysiology_uploader/README.md, modules/electrophysiology_uploader/jsx/ElectrophysiologyUploader.js
Documentation patch to resolve #9293.
Let users and admins know that they will encounter a known issue (#9191), not a bug with their setup:
This does this by: 
- Adding text visible to Users at the top of the module 
- Adding README message
- Adding Help text note for users
This does not resolve  #9191, but it clarifies the state for LORIS users.
=> [EEG Uploader] User messaging and Documentation update

CHANGELOG.md, README.md, docs/wiki/00_SERVER_INSTALL_AND_CONFIGURATION/01_LORIS_Install/CentOS/README.md
Update the version of LORIS in documentation that references it.
This should be merged immediately before the release (with the date updated if necessary.)
=> [Documentation] Update v26 version

modules/statistics/php/charts.class.inc
If a user has a site which has no candidate has data for, the statistics chart will print a warning because of a misplaced bracket.
Move the null coalesce inside of the intval argument to fix the warning.
This should theoretically fix the second part of https://github.com/aces/Loris/discussions/9308
=> [statistics] Fix bracket for null coalesce

SQL/0000-00-00-schema.sql, SQL/New_patches/2024-07-16-CleanDefault.sql, SQL/New_patches/2024-07-16-CleanFlagSession.sql
While browsing the database schema, I noticed there were a lot of `default '0'` everywhere, even for foreign keys ! This is an anti-pattern that is easy to fix and should not require any change to the codebase outside of the schema, so here is a PR.
List of changes:
1. Drop the `DEFAULT 0` for foreign key fields (we do not have any table with a record at index `0` as far as I know/checked)
2. Change `DEFAULT '0'` (or `'1'`) to `DEFAULT 0` (or `1`) for other fields, which is more correct (the former can notably raise type errors with some database engines IIRC).
I don't think the `ALTER column SET DEFAULT 0` is actually useful in the SQL patch, but it cannot hurt.
I omitted the `mri_protocol.Scan_type` field as it is fixed in #9304 instead.
More broadly, it seems to me that there is an …
=> [database] Improve schema defaults

tools/generate_tables_sql.php
Fix for #9312.
The version before the regression generated broken SQL for `testname`, which was then erased when the table was created.
The regression was due to the erasement being removed.
This removes the broken SQL generation.
I don't know how critical this bug is but this PR should be in the next bugfix patch if there is one.
Use the tools `lorisform_parser.php` and `generate_tables_sql.php` script to generate instrument SQL, and ensure this SQL is correct.
=> [tools] fix instrument SQL generator script

tools/generic_includes.php
This fixes the script `generic_includes.php` that calls the $DB variable before it is defined when calling LorisInstance.
Without this fix, anything calling `generic_includes.php` will trigger the following error:
```
Undefined variable in /var/www/loris/tools/generic_includes.php on line 28
PHP Fatal error:  Uncaught TypeError: LORIS\\LorisInstance::__construct(): Argument #1 ($db) must be of type Database, null given, called in /var/www/loris/tools/generic_includes.php on line 27
```
=> fix generic_includes.php returning error "Undefined variable in /var/www/loris/tools/generic_includes.php on line 28" - 26 branch

php/libraries/SinglePointLogin.class.inc
There is a function in SinglePointLogin named "save" that was commented out 5 years ago.
It doesn't seem to be used.
=> [SinglePointLogin] Remove commented out code

SQL/0000-00-00-schema.sql, SQL/New_patches/2024-08-13-issuetracker-AddWatchingToIssuesHistory.sql, modules/issue_tracker/php/edit.class.inc
- Modified the `issues_history` table to include the 'watching' field in the `fieldChanged` enum.
- Fixed the issue where the "watching" field was taking the "no" value when an issue was updated.
- Fixed the unreported issue of 500 Internal server errors, whenever watching was changed.
1. Go to the issue tracker and create a new issue (MainMenu -> Tools -> Issue Tracker -> New issue).
2. Create a new issue with any test information.
3. Go to the created issue and verify that all fields are populated correctly.
4. Update the issue, making changes to any field(s).
5. Click the "Update" button and observe that the "watching" field retains its previous value.
6. Verify that no 500 errors occur during the update process.
* Resolves #9315
=> [issue_tracker] Resolve issue with "watching" field in issue tracker

php/libraries/Utility.class.inc
getVisitList can be called many times within the same query, in particular when trying to get dictionaries for the dataquery module which include a visit list.
This caches the result instead of re-running the same query multiple times.
=> [Utility] Cache getVisitList result

raisinbread/RB_files/RB_modules.sql
The dataquery table and oidc modules were not in the "modules" table in Raisinbread. This adds them (dataquery enabled since it's a core part of LORIS and oidc disabled by default since it's an optional part that can be enabled in the module manager for those who need it.)
=> [Raisinbread] Add missing modules to RB

modules/dataquery/php/query.class.inc, modules/instruments/php/instrumentqueryengine.class.inc
The InstrumentQueryEngine converts the results of a query
that returns all values from an iterator to an array because
it's used twice. However, the second usage is unnecessary as the
data is available in another way. This switches the second usage
to be array_keys of a variable created in the first iteration and
removes the iterator_to_array, which should result in less memory
usage as it can be freed after the first iteration.
=> [Optimization/dataquery] Remove unnecessary array

modules/dataquery/php/endpoints/queries/query/count.class.inc, modules/dataquery/php/query.class.inc, modules/dataquery/php/queryrun.class.inc, src/LorisInstance.php
This optimizes the filtering of inaccessible candidates, building on PR#9334
Previously, the entire query was loaded into memory, and then manipulated in a way that made it easier to see which candidates are valid, then returned as an array by putting the valid ones in a temporary table and selecting from it.
With this change, instead of an array, a generator is used so that only one candidate (and its sessions) need to be loaded into memory at a time. This is done on an unbuffered connection, which necessitates a different database connection since only one query can be run at a time on a connection and the caller may make other queries before the generator finished.
This result should be significantly less memory required for filtering candidates.
=> [dataquery] Optimize filtering of valid candidates for large datasets

modules/battery_manager/php/testendpoint.class.inc, modules/battery_manager/test/BatteryManagerTest.php
The new integration test catched a new bug in battery manager. 
Add a request method param to check and avoid performing duplicate checks during the update operation.
=> [battery manager] duplicate check fix

modules/statistics/php/statistics_dd_site.class.inc, modules/statistics/php/statistics_mri_site.class.inc, modules/statistics/php/statistics_site.class.inc
Fix type errors on the page loaded from the link on the LORIS dashboard for "data entry incomplete" in my tasks.
Fixes #9353
=> [Statistics] Fix site statistics page loading

php/libraries/NDB_BVL_Instrument.class.inc
BulkLoadInstanceData currently returns an array of instruments for each candidate. This is inefficient because every instrument needs to be loaded into memory, when the results are only ever used in a foreach loop. This replaces the array_map with a generator that yields the instrument, and uses an unbuffered database connection.
This uses significantly less memory for large datasets as now only one CommentID needs to be loaded into memory at a time.
=> [Optmization] Replace bulkLoadInstanceData with generator

modules/candidate_parameters/test/candidateQueryEngineTest.php, modules/imaging_browser/test/ImagingQueryEngineTest.php, modules/instruments/php/instrumentqueryengine.class.inc, php/libraries/NDB_BVL_Instrument.class.inc, src/Data/Query/SQLQueryEngine.php
This updates the bulkLoadInstanceData function to optionally take a single QueryTerm to load candidates for, in addition (or instead of) a list of CommentIDs. If provided, the bulk load will filter for instruments matching the term from SQL, rather than loading them all into memory and filtering from the PHP side.
This should significantly reduce the memory consumption for large data sets.
=> [dataquery] Filter candidates from SQL instead of PHP

modules/candidate_parameters/jsx/DiagnosisEvolution.js
After We merge the diagnosis new feature into 26.0-release([New Feature] Tracking and Configuration of Candidate's Diagnosis Evolution (https://github.com/aces/Loris/pull/7560)), it cause a bug. 
if diagnosis is empty. the whole candidate param page will be broken.
=> [candidate parameters] diagnosis fix

modules/issue_tracker/php/edit.class.inc
- Modified getComments() to convert Query object to array
- Resolved "An iterator cannot be used with foreach by reference" error
1. Navigate to the Issue Tracker module
2. View an existing issue
3. Confirm the issue loads without errors
The pselect() function returns a Query object (iterator), which caused an error when used in a foreach loop by reference. This PR fixes the issue by converting the Query object to an array using iterator_to_array(), ensuring compatibility with the foreach loop and resolving the loading error in the Issue Tracker.
* Resolves #9366
=> [issue_tracker] Resolve Iterator Error in getComments() Method

tools/generic_includes.php
This fixes the script `generic_includes.php` that calls the $DB variable before it is defined when calling LorisInstance.
Without this fix, anything calling `generic_includes.php` will trigger the following error:
```
Undefined variable in /var/www/loris/tools/generic_includes.php on line 28
PHP Fatal error:  Uncaught TypeError: LORIS\\LorisInstance::__construct(): Argument #1 ($db) must be of type Database, null given, called in /var/www/loris/tools/generic_includes.php on line 27
```
=> fix generic_includes.php returning error "Undefined variable in /var/www/loris/tools/generic_includes.php on line 28" - 25 branch

modules/api/php/endpoints/candidate/visit/image/qc.class.inc, raisinbread/test/api/LorisApiImagesTest.php, raisinbread/test/api/LorisApiImages_v0_0_3_Test.php
This fixes the PUT request not updating the image's QC values when testing the API via the Swagger.
1. Go to the API documentation module and scroll down to the specified request section
2. Click on "Try it out" and enter a CandID, visit label, and filename. You can use the GET requests above this section to get the visit labels and filenames for a given candidate.
3. Fill in the request body section with updated QC values for the image.
4. Click on "Execute" (should return a 204 code and successfully update the QC status of the given file)
* Resolves #7917
* Replaces #9375
=> [API] Fix PUT request not updating image's QC values

.github/workflows/loristest.yml
fix this PR Bump actions/download-artifact from 3 to 4.1.7 in /.github/workflows #9330
=> [gitaction]  - update "artifact" from V3 to V4

modules/instruments/php/instrumentqueryengine.class.inc
The ability for the frontend to display session variables with a cardinality of "many" per session was added for the imaging, but the instrument queryengine backend was not updated to properly format multi-select elements. This adds support for multiselect elements by updating the instrument queryengine to return correctly formatted data for instruments with the many cardinality.
=> [dataquery/instruments] Handle cardinality::many instruments in DQT

jsx/Card.js, modules/candidate_profile/templates/form_candidate_profile.tpl
This adds an error boundary to the jsx/Card class, so that when a widget doesn't render properly on the candidate profile page that panel is displayed with an error and the rendering of other widgets is unaffected, instead of crashing and showing a blank page.
Fixes an issue I can't find keywords to find the reference for.
=> [candidate_profile] Add error boundary to cards with errors

modules/document_repository/php/files.class.inc
- Updated Document Repository to no longer have a file type restriction
- Restriction was introduced in #5234 however there was no specific reason listed for the addition, and it is restricting for projects
1. Try uploading a document that is not of the types listed. (Example a .etf file)
[ORIGINAL CCNA PR](https://github.com/aces/CCNA/pull/7466)
=> [document_repository] Remove File Type Restriction

modules/create_timepoint/test/TestPlan.md, modules/create_timepoint/test/create_timepointTest.php
=> [Create timepoint] test

modules/user_accounts/php/edit_user.class.inc
- Fixed bug in user_accounts when examiner details are selected caused by the introduction of the /Database/Query class. It thought that new examiner's IDs existed and tried to use it, even when that examiner did not exist and needed to be created
- Fixed bug where examiner status is always reset to pending from user accounts (CCNA OVERRIDE)
1. Create a new user and modify examiner details
2. Confirm an examiner is added to examiners
3. Change the pending to No and confirm the database reflects that
[CCNA OVERRIDE PR](https://github.com/aces/CCNA/pull/7128)
=> [User_Accounts] Fix examiner always pending & bugfix

modules/statistics/php/widgets.class.inc
A query introduced in #9010 did not have any join condition between the candidate and session table, resulting in both incorrect data and slow query times.
=> [Statistics/Dashboard] Fix query

docker-compose.yml, test/wait-for-services.sh
Update selenium image from V3 to V4 to support new JS fetures(i18next ...) in firefox browser.  
Selenium standalone-firefox-debug now is part of standalone-firefox: 4.25.
=> [Test] update selenium image from V3 to V4 

php/libraries/Utility.class.inc
There were (at least) 2 unnecessaries joins in database queries in getVisitList and getVisitInstruments where a table was joined, and then the table was only used to filter for the same key that was used in the join condition.
Remove those joins by just filtering on the key in the first place.
=> [Utility] Remove unnecessary joins in queries

jsx/Filter.js
This PR reduces the strictness of the filter logic in the Filter.js component by adjusting the conditions for the exactMatch variable, functionally changing the multiselect filter from an AND to an OR boolean operators.
If this change is contentious, I can work on a way of have this be decided either by individual modules via a prop, or by use input by incorporating some sort of toggle button.
=> [JSX] Relax Strictness of Filter for Multiselect in Filter Component

tools/CouchDB_Import_Instruments.php, tools/importers/CouchDB_MRI_Importer.php
- Updated CouchDB import tools to remove some PHP warnings
- Updated CouchDB instrument import tool to actually work after flag Test_name removal
1. Try running both scripts and confirm they both run
[CCNA OVERRIDE PR](https://github.com/aces/CCNA/pull/7169)
=> [Tools] CouchDB tools fix and PHP warning removal

modules/conflict_resolver/php/provisioners/resolvedprovisioner.class.inc, modules/conflict_resolver/php/provisioners/unresolvedprovisioner.class.inc
- Show the examiner name in the conflict resolver as well as the ID, as just the ID makes it difficult for users.
- This was [previously done](https://github.com/aces/Loris/pull/2891) as well but the change was likely lost in the shuffle 
1. create a data entry conflict for the Examiner field if your DB does not have any already
2. see that the conflict has the examiner names and not just the ID
3. resolve Examiner conflict & make sure examiner name is there as well
4. check respective instrument table that ExaminerID is valid for the resolved conflict
5. comment "Good job, Saagar! 🍻" and approve PR
[CCNA OVERRIDE PR](https://github.com/aces/CCNA/pull/7220/files)
=> [Conflict_resolver] Show examiner name

modules/conflict_resolver/jsx/resolved_filterabledatatable.js, modules/conflict_resolver/jsx/unresolved_filterabledatatable.js, modules/conflict_resolver/php/endpoints/resolved.class.inc, modules/conflict_resolver/php/endpoints/unresolved.class.inc, modules/conflict_resolver/php/models/resolveddto.class.inc, modules/conflict_resolver/php/models/unresolveddto.class.inc, modules/conflict_resolver/php/provisioners/resolvedprovisioner.class.inc, modules/conflict_resolver/php/provisioners/unresolvedprovisioner.class.inc
Adds a 'Cohort' filter and field to both unresolved and resolved tabs of the conflict resolver
In the Unresolved & Resolved tabs:
1. In the Selection filter, verify that the 'Cohort' filter exists and has the appropriate options in the dropdown
2. Check that the 'Cohort' field appears as a column
3. Select any option and check that only conflicts of that cohort appear
[CCNA Override](https://github.com/aces/CCNA/pull/6562)
=> [conflict_resolver] Add Cohort filter and field

php/libraries/NDB_BVL_Instrument.class.inc
- When running clear instrument on a non JSON instrument with non NULLABLE fields, it tries to set values to null which results in an error, this is resolved
1. Set a field of an instrument to NULLABLE = 'NO' in information_schema
2. Try clearing the instrument with the LORIS API, see that it works now
[CCNA OVERRIDE PR](https://github.com/aces/CCNA/pull/7603)
=> [NDB_BVL_Instrument] Fix for clearing instrument

.eslintrc.json
As discussed in private message with @driusan, this PR relaxes the Typescript JSDoc linting configuration by doing the following:
- Remove the need for a `@returns` annotations, since the rest of the documentation and the return type are often sufficient.
- Remove warnings for no `@param` and `@returns` type in the documentation, since those are already provided by Typescript.
The doc comment for functions is still required and there is still a warning when no `@param` is present.
=> Relax Typescript JSdoc linting configuration

php/libraries/Utility.class.inc
- optimize the list of scan types returned.
- HBCD has a lot of scan types, only returning unique ones fixes `dictionary` module (it is not loading with the new QueryEngine).
Rebase #9453
=> [dictionary] optimize unique scan types

modules/issue_tracker/jsx/issueTrackerIndex.js
- Replaced the view toggle button with a tabbed interface using `Tabs` component
- Added permission check to show Batch Edit tab only for users with `issue_tracker_developer` permission
- Implemented data refresh when switching back to Browse Issues tab
1. Login as a user without `issue_tracker_developer` permission - verify only "Browse Issues" tab is visible
2. Login as a user with `issue_tracker_developer` permission - verify both "Browse Issues" and "Batch Edit" tabs are visible
3. Make changes in Batch Edit mode, then switch back to Browse Issues - verify data refreshes automatically
* Resolves #9422, #9423 
* Part of #9418
=> [issue_tracker] Convert batch/normal mode toggle to tabs and implement permission control

src/Http/Response/JSON/Accepted.php, src/Http/Response/JSON/SeeOther.php
Extracted from #9154.
Add JSON responses for HTTP codes [Accepted](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/202) and [See other](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/303).
It works in #9154 
=> Add JSON HTTP responses for "accepted" and "see other"

jsx/Form.js, jsx/form/DateTimePartialElement.tsx, jsx/form/InputLabel.tsx
- Factorize input labels in `jsx/Form.js`
- More idiomatic React code in `jsx/form/DateTimePartialElement.tsx`
- Do not convert `disabled`, `required` and `multiple` to strings as input expect booleans ([doc](https://react.dev/reference/react-dom/components/input)).
Note that I did not factorize checkboxes for radio buttons and checkboxes as they use a different layout.
1. Open LORIS
2. Go to any form and ensure the inputs are correctly displayed.
=> Factorize JSX input label

modules/candidate_list/jsx/candidateListIndex.js
[v26 Upgrade HBCD] Selection Filter boxes on 'Access Profile' page are empty when accessed via direct link
When the 'Access Profile' is reached via clicking on the direct link at the top left of the page (e.g. from participant's profile page), the page will load, but the multi-select boxes in the 'Selection Filter' Menu appear empty. This is not the case if the page is accessed via the link in the 'Candidate' menu.
This PR fixes the issue.
=> [candidate_list] Fix 'Access Profile' link on timepoint list page

CHANGELOG.md, php/libraries/NDB_BVL_Feedback.class.inc
I had looked into the suspected bug and confirmed that it is indeed a bug. 
This PR fixes the BVL Feedback summary in instruments by taking the commentID for query params from the array _feedbackObjectInfo instead of _feedbackCandidateProfileInfo, which only included candidate specific data instead of instrument specific data.
1. Outside of this PR, navigate to an instrument that has at least one feedback comment. 
2. Look at the feedback for that instrument, and check the feedback summary at the top of the window. Notice that it is indicated that there is no feedback
3. Load this PR and refresh the page. 
4. Notice that the summary exists and holds accurate information
=> [Feedback] Fix typo in getSummaryOfThreads

tools/assign_missing_instruments.php
assign_missing_instruments.php - fix wrong tpye
**[php assign_missing_instruments.php 
PHP Fatal error:  Uncaught TypeError: LORIS\StudyEntities\Candidate\ValidatableIdentifier::__construct(): Argument #1 ($value) must be of type string, int given, called in /var/www/Loris/tools/assign_missing_instruments.php on line 94 and defined in /var/www/Loris/src/StudyEntities/Candidate/ValidatableIdentifier.php:59]** 
test: run "php assign_missing_instruments.php"
=> [Tools] assign_missing_instruments.php - fix wrong tpye

composer.json, composer.lock, docs/wiki/99_Developers/Code_Customization.md, modules/issue_tracker/php/edit.class.inc, php/libraries/Candidate.class.inc, php/libraries/FeedbackMRI.class.inc
- Allow additional composer deps to be managed in `project/` without the need to override the main `composer.json`.
- Adds the documentation section to cover how to override LORIS.
1. create a `project/composer.json` with additional deps.
2. run `composer update`
Reopening #8319 as a new dependency is needed in HBCD.
=> [composer] manage project dependencies

tools/data_integrity/fix_candidate_age.php
- Updated the fix_candidate_age php tool to only consider candidates with Data, and to skip bulk loading when there are no participants
1. Try running the fix_candidate_age script and confirm it works
CCNA OVERRIDE
=> [Tools] Update fix_candidate_age.php speed

php/libraries/NDB_BVL_Instrument.class.inc, tools/data_integrity/score_instrument.php
In the Instrument class' `_save()` function, updates the instance data if the instrument has an SQL table so that the instance data only needs to be saved once to calculate the correct score
This also updates the `score_instrument.php` script to resolve issue relating to the `Query` class update
1. Run the scoring script for a candidate with the bmi instrument and verify that the scores are correct
2. Modify the instrument data in the instrument table only, not in data_instrument
3. Re-run the scoring script and verify that the scores are updated according to the changes made
[CCNA Override](https://github.com/aces/CCNA/pull/7270)
[CCNA Override 2](https://github.com/aces/CCNA/pull/7452)
=> [NDB_BVL_Instrument] Modify InstanceData Setting

modules/issue_tracker/jsx/IssueCard.js, modules/issue_tracker/jsx/IssueTrackerBatchMode.js, modules/issue_tracker/php/edit.class.inc
- Added site selector to Issue Card edit mode
- Enhanced Add Comment modal with assignee and watchers selectors
- Updated backend endpoint to fetch otherWatchers and assignees
1. Go to Issue Tracker Batch Mode
2. Click "Edit Issue" on any issue
3. Verify site can be modified using the new dropdown
4. Update Issue
5. Click "Add Comment"
6. Verify assignee and watchers can be modified in the modal
7. Submit changes and verify they persist
* Part of #9418
=> [issue_tracker] Enable editing of site, assignee and watchers in Batch Mode

modules/issue_tracker/jsx/issueTrackerIndex.js, modules/issue_tracker/php/issue_tracker.class.inc
This PR only shows the "My Issues" filter if the user has any issues assigned to them. Since there is no way to filter for issues assigned to no one and the drop down only includes users who have issues assigned to them, this filter will always break for a user with no issues. 
The alternative would be to include all users in the "Assignee" filter drop down. 
1. Compile code on this branch
2. Create a new user and do not assign them to any issues
3. Go to the issue tracker and look in the preset filters
4. There should not be any "My issues" filter for this user
5. From the Admin account assign an issue to the user that you just created
6. Sign in with that user again and check the preset filters again
7. Make sure that the "My Issues" filter does show up now. 
8. Select "My Issues" …
=> [issue_tracker] 'My Issues' filter for users with no issues

php/libraries/Candidate.class.inc
The current code tries to get a username from the session. the session does not have a state when the candidate::createnew function is called from a script on the backend. 
The new code is inpired by the database class which tries to use the environment username to create the data.
1. make sure you can still create a candidate with no issue the standard way
2. try to create a candidate fro ma script in the backend
=> [Candidate] RE-add support to create candidates from the backend (unix user)

modules/electrophysiology_browser/jsx/react-series-data-viewer/tsconfig.json, webpack.config.ts
Fix the webpack and TS config for EEG Browser:
- disable TS strict mode for the EEG visualization module for successful compilation
- remove unecessary webpack hack with proper ts config
=> [EEG Browser] Fix webpack and ts config

test/run-php-linter.sh
PHP 8.3 added the ability to pass more than one filename at a time to 'php -l'. As such, we no longer need to specify that xargs should only lint one file at a time and let it work on batches now that the minimum supported version of LORIS is PHP 8.3.
This improves the time of running 'make checkstatic'.
=> [Core] Faster php syntax checking

modules/conflict_resolver/jsx/resolved_filterabledatatable.js, modules/conflict_resolver/php/models/resolveddto.class.inc, modules/conflict_resolver/php/provisioners/resolvedprovisioner.class.inc
In the Conflict Resolver's Resolved tab, replaces the fields 'Value 1' and 'Value 2' with 'Incorrect Answer'
(changes brought over from https://github.com/aces/Loris/pull/9488)
1. In the Conflict Resolver's 'Resolved' tab, check that the Value 1 & 2 filters & data columns have been replaced with 'Incorrect Answer'
2. Verify that the filters function properly
[CCNA Override](https://github.com/aces/CCNA/pull/6856)
=> [conflict_resolver] Replace 'Value 1 & 2' with 'Incorrect Answer'

modules/data_release/php/files.class.inc
When uploading a new file with an existing version, users with permission to that version would be reset. This ensures users with access to the version gain permission to the new file
1. In Data Release, upload a new file with a new version and give a non-admin user permissions to that version in 'Manage Permissions'
2. Upload another file under that version
3. In 'Manage Permissions', verify that the non-admin user still has access to the version
4. Access the data release module as the non-admin user and check that you have access to the files under that version
[CCNA Override](https://github.com/aces/CCNA/pull/6854)
=> [data_release] FileUpload version permission

php/libraries/NDB_BVL_Instrument_LINST.class.inc
PHP Fatal error:  Uncaught TypeError: substr(): Argument #2 ($offset) must be of type int, false given in /var/www/Loris/php/libraries/NDB_BVL_Instrument_LINST.class.inc:172
test: save data in the BMI instrument without issue.
=> [NDB_BVL_Instrument_LINST] - fix

modules/media/jsx/mediaIndex.js, php/libraries/FilesDownloadHandler.php
In the Media module, allows files with names containing commas to be downloaded (would previously result in an error)
1. Upload a file containing a comma in its name to the Media module
2. Check that the file can be downloaded
The same fix was made [here](https://github.com/aces/Loris/pull/9461) for the document repository
=> [media] Fix download of filenames with commas

.eslintignore, .github/workflows/loristest.yml, modules/electrophysiology_browser/test/electrophysiologyBrowserTest.php, webpack.config.ts
=> Fix 26.0-release CI

php/libraries/Utility.class.inc, tools/data_integrity/data_deletion/delete_timepoint.php, tools/data_integrity_check.php, tools/fix_timepoint_date_problems.php
- Fix missing changes for including test_names.ID instead of Test_names from flag.
* Resolves #9440
=> [flag] Fix remaining test_name flag

modules/imaging_browser/jsx/imagingBrowserIndex.js
- There was a typo in the `ImagingBrowserIndex` options for the entityType.
1. Go to the imaging browser and check the Entity Type to see the two options (Humen, Scanner).
- https://github.com/aces/Loris/issues/8962#event-16018789519
=> Fixing the display of the Entity Type options in the Imaging Browser

php/libraries/NDB_BVL_Instrument.class.inc, tools/recreate_conflicts.php
- Includes a CCNA override that makes recreate_conflicts work when there are many examiners
[CCNA OVERRIDE PR](https://github.com/aces/CCNA/pull/5025)
=> [NDB_BVL_Instrument] Modify Examiner Select

modules/instruments/php/instrumentqueryengine.class.inc, php/libraries/NDB_BVL_Instrument.class.inc
This adds instrument flags to the data that is bulk loaded by bulkLoadInstanceData and uses that to address the low hanging fruit of #9372 of including administration flags in the data query tool.
It does not address the DDE and conflict related fields that are in the CouchDB import script because we should investigate if those make sense in the instruments query engine or if it's possible to have those provided by the conflict resolver module rather than the instruments module, as they are more related to that module.
=> [dataquery] Add instrument flags to instruments query engine

modules/dataquery/php/endpoints/queries/query/run.class.inc, modules/dataquery/php/endpoints/queries/query/run/run.class.inc, modules/dataquery/php/endpoints/queries/runs.class.inc, modules/dataquery/php/provisioners/queryruns.class.inc, modules/dataquery/php/queries.class.inc, modules/dataquery/php/query.class.inc, modules/dataquery/php/querydataprovisioner.class.inc, modules/dataquery/php/queryrun.class.inc, modules/dataquery/static/schema.yml, php/libraries/Candidate.class.inc, src/Http/DataIteratorBinaryStream.php
This implements the endpoint that is listed as "aspirational" in the
dataquery api schema to load the results of a previously run query.
It was originally left out for fear of performance issues but with
this implementation performance seems to be comparable to without
it.
This does not implement a frontend to reload query results, but
the API functionality is useful for i.e. api callbacks that want
to process the results of a query without the need to re-run
it (and the possibility to get different results.)
=> [dataquery] Add ability to retrieve results of previous run from API

SQL/0000-00-02-Permission.sql, SQL/New_patches/2025_02_03_permissions_Modifies_issue_tracker_reporter_description.sql, modules/issue_tracker/php/edit.class.inc, raisinbread/RB_files/RB_permissions.sql
- There were a bug - possible do to an upgrade - that was making the `issue tracker reporter username` been compared with the "formatted" username of the user logged. Now the comparison is properly done.
- The permission's description for `issue_tracker_reporter` was updated thus now it properly reflect that the user is indeed able to close the issues created by himself.
1. Please log into LORIS with and admin account and notice that for the `issue_tracker_reporter ` the permission's description was changed from `Issue Tracker: Create/Edit Own Issues and Comment on All Issues`  to `Issue Tracker: Create/Edit/Close Own Issues and Comment on All Issues` 
2. Please log into LORIS now with a user having only the `Issue Tracker: Create/Edit/Close Own Issues and Comment on All Issues` but not …
=> [issue_tracker] Fixes but in permission when own user editing.

modules/dataquery/php/provisioners/queryruns.class.inc
The static tests are failing as of 79a1c779c815e05e73bf3075497881bff44c4f0f, because it wasn't based on the latest commit.
Fix the failing phan errors.
=> [Tests] Fix failing static tests on main branch

SQL/0000-00-00-schema.sql, SQL/New_patches/2025_02_05_change_candid_fk_to_id.sql
Closes #9564 .
This PR addresses the forgotten `NULL`ability annotations, found by Loris-MRI integration tests.
`NULL`ability should now be identical to how it was prior to the last patch in  #9556
=> [SQL] Fix NULLability of CandidateID FK

modules/dicom_archive/php/viewdetails.class.inc
This PR checks the user attached projects on top of the `dicom_archive_view_allsites` permission when trying to access the `view details` page.
Resolves #6658
=> [dicom archive] add project permission check based on tarchiveID

SQL/Login_Summary_Statistics/04_Visit.sql
There was a semantic conflict between PR#9556 and one of the queries in PR#9518, as the CandID now needs to come from the candidate table.
This adds a JOIN from the session for the one query missing it, so that the update login statistics script doesn't fail with an SQL error.
=> [Login Statistics] Fix query

composer.lock
I've been getting deprecation warnings on the first page load after starting the PHP web server from smarty under PHP 8.4. This updates smarty by running `composer update smarty/smarty`, which appears to fix the warnings under php 8.4.
=> [Smarty] Update Smarty

php/libraries/NDB_BVL_InstrumentStatus.class.inc, php/libraries/NDB_Client.class.inc
This removes 2 unnecessary lines from NDB_Client.
The global $DB variable is defined in generic_includes for scripts. Outside of scripts, the database connection always comes from the LorisInstance object.
The include for Smarty_hook is unnecessary because the file is autoloaded by composer.
=> Remove redundant NDB_Client lines

htdocs/bootstrap/css/custom-css.css, modules/user_accounts/php/edit_user.class.inc
CBIG has a lot of sites and projects and the tiny 10px  sized multiselects are just not cutting it anymore, they are extremely difficult to work with. This PR is 100% self isolated to the user_accounts module and only affects the site and project selects.
attached are 2 images to contrast the expandable selects vs the non expandable. NOTE that I made the changes to both sites and projects, the screeshots are simply to compare and contrast before vs after
1. make still work
=> [user_accounts] Made Site & Project multiselect expandable

src/Data/Filters/AccessibleResourceFilter.php, src/Data/Filters/CompositeANDFilter.php, src/Data/Filters/CompositeORFilter.php, src/Data/Filters/ResourceHasNoSession.php, src/Data/Filters/UserHasAnyPermission.php, src/Data/Filters/UserIsCreator.php, src/Data/Filters/UserProjectMatch.php, src/Data/Filters/UserSiteMatch.php
This PR creates new filters and modifies existing ones to add functionality and make them more scalable. Two new composite filters can also be used to join other filters in an AND or OR logic. These filters should allow us to move away from writing a new filter with "combined" functionality for each module (i.e. `UserProjectMatchOrHasAnyPermissions`) instead you can use independent filters and join them in the order you need them to be.
Changes in PR https://github.com/aces/Loris/pull/9549 demo the use of these filters and how to combine them
PS these changes should not break existing code
1. Hard to test on it's own but will be tested buy changes in another PR
=> [Core] New Filters and Logic

modules/server_processes_manager/php/mriuploadserverprocess.class.inc, modules/server_processes_manager/php/serverprocessesmonitor.class.inc
Extracted from #9154
Those are minor documentation changes of the server process monitor that were present in #9154. I don't remember writing these changes so those were probably in the original PR. I do not have a strong opinion myself on the doc changes, but the doc type changes certainly better fit the function behaviour.
@driusan feel free to ping someone more knowledgeable than us on this subject.
=> [server process monitor] minor doc comment changes

php/libraries/User.class.inc
User::singleton currently always returns the logged in user. If the $username argument is passed, it still returns the logged in user instead of the user requested.
This updates the singleton so that it's possible to use it to get references to other users.
=> Fix user singleton when an argument is passed.

modules/examiner/php/editexaminer.class.inc
A smarty was trying to use a variable that was directly set to a pselect output, causing an error. Explicitly convert it to an array.
Fixes #9605
=> [Examiner] Fix loading of edit examiner page

jsx/StaticDataTable.js, modules/issue_tracker/php/edit.class.inc, tools/detect_duplicated_commentids.php
DO NOT SQASH
```
Changes to be committed:
modified:   jsx/StaticDataTable.js
modified:   modules/issue_tracker/php/edit.class.inc
Unmerged paths:
(use "git add <file>..." to mark resolution)
both modified:   tools/detect_duplicated_commentids.php
```
=> Push 24.1 into 26.0

SQL/0000-00-00-schema.sql, SQL/New_patches/2025-02-26_alter_issues_history_fieldChanged.sql, modules/issue_tracker/php/edit.class.inc, modules/issue_tracker/php/issuerowprovisioner.class.inc, modules/issue_tracker/php/models/attachmentdto.class.inc
Related to #9606
- This PR fixes the issue description. The cause of the issue is the change of CandID => CandidateID.
- It also resolves a bug that causes the Edit Issue page to fail to display when an attachment is included in an issue. 
To Test:
- See if you can create a new issue or update existing issue
- Upload a file to an issue and see if the page doesn't break and you can see the attachments/file when the page refreshes.
=> [issue_tracker] Fix bug that prevents new issue creation

modules/imaging_qc/php/imaging_qc.class.inc
…nd project
Fixes #6591
**To Test**
1. Create a user with the following permission only:
> Imaging Quality Control: View Flagged Imaging Entries
Make sure not to include `View all-sites Imaging Browser pages` or any other permissions
2. Assign the user site e.g "Ottawa" and project "Pumpernickel"
3. Log in as this user, and navigate to the imaging quality control module
4. Observe that the front page loads with data pertaining only to the user site and project  
5. Observe that the `site` filter only allows filtering only to the user's site
6. Observe that the `project` filter allows filtering only to the user's project
=> [imaging_qc] fix module to display only data affliated to user's site and project

modules/publication/ajax/FileUpload.php
In the Publication module, when editing a PI for a project (name/email), all other projects with the same PI would be modified. This PR takes the PI's email as the PI's identifier and
- if the email is updated to an existing email in the db, updates the name associated to the email and the project's `LeadInvestigatorID`
- if the email is updated to a new email, creates a new collaborator with a new ID
- if the email is not updated and the name is updated, updates the name associated to the email
1. Create new projects with different PIs
2. Edit the PI information (name & email) in various ways and check that the projects are updated accordingly
3. Verify in the `publication_collaborator` table that when an email is updated to a new email that does not exist, a new collaborator is created, …
=> [publication] Fix edit PI issue

modules/server_processes_manager/php/server_processes_manager.class.inc
This PR modifies the server process manager so that it properly updates the status of processes before displaying the search result list. This fixes a bug that would cause some processes to be listed with an unknown exit code and/or exit text message.
Fixes #8593
=> Server process manager now displays updated process information

htdocs/index.php, php/libraries/NDB_Client.class.inc, src/AWS/Client.php, src/Middleware/AWS.php, src/Router/BaseRouter.php, tools/generic_includes.php
This refactors the way AWS S3 buckets are handled so that the stream wrapper registration is added by a middleware. For scripts, the logic of registering a stream wrapper is moved to generic_includes.
This is a first pass at addressing the comment in htdocs/index.php that most of the work of NDB_Client should be done by middleware.
=> Move AWS to middleware

tools/configuration_check.php
- Tried to run `php configuration_check.php` and since I do not have nodejs on my vm, the script crashed at that check. Added an if statement to only check version if nodejs is installed to begin with.
Original:
<kbd>
</kbd>
Now:
<kbd>
</kbd>
=> [tools] configuration_check doesn't error on no nodejs

modules/timepoint_list/php/timepoint_list.class.inc
Currently the user cannot access other sites timepoints even if the user has access_all_profile permission. This PR fixes tat issue
See if user with access_all_profiles permission can access all timepoints
* Resolves #9628
=> [Timepoint List] Fix Timepoint List Access Issue when User have access_all_profiles Permission

php/libraries/NDB_BVL_Instrument.class.inc, test/unittests/NDB_BVL_Instrument_Test.php
- updated addHourMinElement to have the yellow warning when a status is selected
1. Open an instrument with `addHourMinElement`
2. Select an option from the status dropdown
3. Confirm that the yellow warning appears
4. Confirm that you can save with no errors
* Resolves #9541
=> [NDB_BVL_Instrument] addHourMin Warning

php/libraries/NDB_BVL_Instrument.class.inc, php/libraries/NDB_BVL_Instrument_LINST.class.inc
- raisinbread BMI instrument was not opening due to a change I made in #9416 where getExaminerFields in NDB_BVL_Instrument now relied on data being present in the instrument's dictionary.
- Unfortunately, when loading a LINST instrument with Direct Entry enabled, it would first run _addMetadataFields, and then add metadata fields to the dictionary
- _addMetadataFields would then call getExaminerFields causing it to fail, since getExaminerFields relies on the dictionary having metadata, but the metadata is added after _addMetadataFields
- The change has been made so _addMetadataFields is run _after_ metadata is entered in the instance's dictionary. Further, metadata fields are only added to the instances dictionary if direct entry is not enabled. Otherwise they were added to the dictionary …
=> [NDB_BVL_Instrument_LINST] Add Metadata Fields after adding to dictionary

modules/instrument_builder/jsx/react.instrument_builder.js
- Improved error message handling for file uploads in Instrument Builder.
- Now provides **specific error messages** for:
- Invalid extension. Only .linst files are allowed.
- Spaces are not allowed in the file name.
- Special characters are not allowed (only letters, numbers, and _).
- Multiple periods in the file name are not allowed.
- File name cannot end with a special character.
1. Try uploading different files with:
- Valid names (`validFile.linst`) → Should succeed.
- Names with **spaces** (`my file.linst`) → Should show `"Spaces are not allowed."`
- Names with **special characters** (`file@name.linst`) → Should show `"Special characters are not allowed."`
- Names with **multiple periods** (`file.name.linst`) → Should show `"Multiple periods in the file name are not allowed."`
- …
=> [instrument_builder] Improve error message specificity for file upload

php/libraries/NDB_BVL_Instrument.class.inc
- make change that was also done in #9498 but for addDateElement too
- Unfortunately my vm would not load anything so I did not get to test this
1. Open instrument and see that you cannot enter more than 4 digits for date fields
* Resolves #9620
=> [NDB_BVL_Instrument] Set dateOptions for addDateElement too

modules/electrophysiology_browser/test/TestPlan.md
This updates the test plan of the electrophysiology_browser to remove step 13 since it is not available for testing in the LORIS code. It also simplifies step 14.
=> [electrophysiology_browser] Update TestPlan

modules/instrument_builder/jsx/react.questions.js
1. Navigate to the Build tab:
- Add Question Name with the Dropdown Option click Add row, it should add the row successfully.
- Add the same question again. The error message `Duplicate question name` will appear. Change the value of the field → The error message should disappear.
2. Navigate to the "Add Question" section.
- Select **Dropdown** as the question type.
- Click **Add Row** without adding options → **Error should appear**.
- Add one option and click **Add Row** again → **Error about needing two options should appear**.
- Add a second option. → **Errors should disappear, and Add Row should work**.
- Run:
```
npm run compile
```
- https://github.com/aces/Loris/issues/8572
=> [Instrument Builder] Fix error message for Question Name and Dropdown Option 'Build' tab

modules/instrument_list/php/instrument_list.class.inc, php/libraries/NDB_BVL_Battery.class.inc
- Make `isDoubleDataEntryEnabledForInstrument` consider CohortID as there can be instances in the test_battery with the same instrument and visit_label but different CohortID
1. Try adding an instrument in two different cohorts with the same visit_label
2. Confirm you can open it and do not face an error with the function.
- Found in testing round
=> [NDB_BVL_Battery] isDoubleDataEntryEnabledForInstrument should consider CohortID

modules/candidate_parameters/jsx/ParticipantStatus.js
This PR makes the participant status reason field show up as enabled and required when a participant status is configured to have a reason required. This is done by casting the participant status index as a number before checking if it is in the required array. I also removed some unnecessary code in setFormData() that was making the field highlight red before anything was saved.
1. Go to participant status
2. Try selecting different participant status values and make sure that the reason field is only enabled / required when the participant status chosen has "Required" set to true in participant_status_options.
3. Try saving when the participant status reason is not required, make sure it saves properly without a value entered
4. Try saving when the participant status reason is required …
=> [candidate_parameters] Make Participant Status Reason properly required

modules/configuration/jsx/DiagnosisEvolution.js
[configuration] Bugs found in this module #9599
test: step 1 go to configration page 
step 2 create a new Diagnosis Evolution
step 3 make sure the projects is in the option list.
=> [configration] DiagnosisEvolution missing projectID - fix

modules/datadict/ajax/UpdateDataDict.php, modules/datadict/php/datadict.class.inc, modules/datadict/php/fields.class.inc
fixes #9618
To Test:
1. Log in as a user with permission data_dict_edit.
2. Edit the description of any field in the search result table.
3. Reload the page in the browser.
4. See the new description has been saved
=> [data_dict (legacy)] fix description not updating upon refresh

modules/dataquery/test/TestPlan.md, modules/login/test/Login_Statistics_Test_Plan.md
Update the test plan for Login Statistics in both the Login module and dataquery module.
=> [Test Plan] Login Statistics and Dataquery test update

modules/examiner/jsx/examinerIndex.js
Added filter to filter out NULL values in case 'site'
- checkout branch `examinerSitesJS`. 
- npm run compile
- create or go to existing user with 
-  [x] Examiner: Add and Certify Examiners - Own Sites
- select 1 2 or 3 sites for this user
- save 
- Go to Clinical/Examiner in front end  and assert that there are no commas in the string of Sites
#9704
#9704
=> [examiner] filter out NULL values in case 'site'

SQL/0000-00-00-schema.sql, SQL/New_patches/2024-07-16-CleanDefault.sql
This PR fixes a bug that would prevent the following visit level properties from being saved: QC status, QC pending and visit level caveat. 
Partial fix for #9587
=> [imaging_browser] Fix visit level feedback cannot be saved

SQL/0000-00-02-Permission.sql, SQL/0000-00-03-ConfigTables.sql, SQL/New_patches/2025-01-31-dicom_archive_permissions.sql, modules/dicom_archive/README.md, modules/dicom_archive/php/dicom_archive.class.inc, modules/dicom_archive/php/dicomarchiveanonymizer.class.inc, modules/dicom_archive/php/dicomarchiverowprovisioner.class.inc, modules/dicom_archive/php/dicomarchiverowwithoutsession.class.inc, modules/dicom_archive/php/dicomarchiverowwithsession.class.inc, modules/dicom_archive/php/module.class.inc, modules/dicom_archive/php/viewdetails.class.inc, modules/dicom_archive/test/TestPlan.md, raisinbread/RB_files/RB_permissions.sql, raisinbread/RB_files/RB_user_perm_rel.sql
This PR adds advanced site and project permissions to the dicom archive. It is designed to be fully backwards compatible based on the `useImagingSiteProjectPermissions` configuration setting. Here is how the permissions are designed to work
- If useImagingSiteProjectPermissions is disabled (status-quo)
- A user with dicom_archive_allsites can see all the data (DEFAULT)
- A user with own sites can only see data at their own sites (can not see data with no session ID)
- A user with own sites and nosessionid permission can see their site data + dicoms not associated to a session
- A user can always see DICOMS of scans they uploaded
- If useImagingSiteProjectPermissions is enabled
- A user with all sites permissions can see all the data from all sites as long as the projectID is defined and …
=> [dicom_archive] Dicom archive siteproject main

modules/electrophysiology_browser/php/models/electrophysioevents.class.inc, tools/data_integrity/data_deletion/delete_physiological_file.php, tools/update_annotation_files.php, tools/update_event_files.php
=> [tools] Replace 'annotation' references in tools with 'events'

modules/candidate_parameters/ajax/getData.php
This PR wraps the $db->pselect() call with iterator_to_array so that it can be processed with .map in [DiagnosisEvolution.js](https://github.com/aces/Loris/blob/main/modules/candidate_parameters/jsx/DiagnosisEvolution.js#L65). This is necessary following the change in #9334
1. Open the candidate parameters module for any participant and go to the Diagnosis Evolution tab
2. Make sure there are no errors
* Resolves #9711
=> [candidate_parameters] Fix DB select with iterator_to_array

modules/battery_manager/jsx/batteryManagerForm.js
- Updated the New Test form in the Battery Manager to better showcase that selecting a DDE option is required.
- It defaults to No, and includes a red * that the field is required.
1. Try to create a new Test without modifying the DDE selection and confirm it works
2. Try to create a new Test with DDE == 'Yes' and confirm it works
* Resolves #9698
=> [battery_manager] Add required DDE selection

tools/fix_timepoint_date_problems.php
This fixes the following errors when running the tool `fix_timepoint_date_problems.php`
```
PHP Fatal error:  Uncaught TypeError: preg_match(): Argument #2 ($subject) must be of type string, LORIS\StudyEntities\Candidate\CandID given in /var/www/Loris/tools/fix_timepoint_date_problems.php:157
Stack trace:
#0 /var/www/Loris/tools/fix_timepoint_date_problems.php(157): preg_match()
#1 {main}
thrown in /var/www/Loris/tools/fix_timepoint_date_problems.php on line 157
```
```
PHP Fatal error:  Uncaught TypeError: checkdate(): Argument #1 ($month) must be of type int, string given in /var/www/Loris/tools/fix_timepoint_date_problems.php:519
Stack trace:
#0 /var/www/Loris/tools/fix_timepoint_date_problems.php(519): checkdate()
#1 /var/www/Loris/tools/fix_timepoint_date_problems.php(244): fixDate() …
```
=> [tool - fix_timepoint_date_problems.php] Fix PHP Fatal error

modules/imaging_browser/php/feedback_mri_popup.class.inc, php/libraries/FeedbackMRI.class.inc
This PR fixes the bugs in the imaging browser's MRI feedback popup during the testing phase for LORIS 27.0, namely:
- Incomplete MRI popup displayed when clicking "QC Comments" (all the comment sections are missing).
- Clicking on "Save" in the above popup yields an error.
Partial fix for #9587
=> [imaging_browser] Fix bugs in imaging browser's MRI feedback popup

jsx/Form.d.ts, jsx/Modal.tsx, modules/data_release/jsx/managePermissionsForm.js, modules/dataquery/jsx/definefilters.importcsvmodal.tsx, modules/dataquery/jsx/welcome.adminquerymodal.tsx, modules/dataquery/jsx/welcome.namequerymodal.tsx
This pull request refactors the `Modal` component to improve flexibility and maintainability by conditionally wrapping `content` in a `FormElement` if an `onSubmit` callback is provided.
- **Conditional Form Wrapping**:  
- Added logic to wrap `content` in a `FormElement` when `onSubmit` is passed as a prop.  
- Ensures consistent behavior for submitting forms or displaying static content.
- **Simplified JSX Structure**:  
- Improved formatting and readability by restructuring the ternary operator.  
- Ensured consistent indentation and reduced code duplication.
- **Preserved Functionality**:  
- Maintains existing behavior while improving code clarity and maintainability.
- Enables better handling of forms inside the modal.  
- Prepares the component for future enhancements.
=> [JSX] Refactor Modal Component to Support Conditional Form Wrapping

php/libraries/LorisForm.class.inc, php/libraries/NDB_BVL_Instrument.class.inc
test: save the BMI instrument(linst).
=> [instrument] fix can't save linst file 

modules/dataquery/jsx/definefields.tsx
Changes the width of the right panel "Selected Fields" thus it's render properly when projects have multiples visits labels. 
1. The issue observed in  #9771 when a project have multiple visits should be not longer present.
* Resolves #9771
=> [dataquery] fix "Selected Fields" panel width.

modules/genomic_browser/help/genomic_browser.md, modules/genomic_browser/jsx/tabs_content/filemanager/uploadForm.js, modules/genomic_browser/jsx/tabs_content/files.js, modules/genomic_browser/jsx/tabs_content/gwas.js, modules/genomic_browser/jsx/tabs_content/profiles.js, modules/genomic_browser/jsx/tabs_content/snp.js, modules/genomic_browser/php/filemanager.class.inc, modules/genomic_browser/php/models/cnvdto.class.inc, modules/genomic_browser/php/models/methylationdto.class.inc, modules/genomic_browser/php/models/profiledto.class.inc, modules/genomic_browser/php/models/snpdto.class.inc, modules/genomic_browser/php/provisioners/cnvprovisioner.class.inc, modules/genomic_browser/php/provisioners/methylationprovisioner.class.inc, modules/genomic_browser/php/provisioners/profileprovisioner.class.inc, modules/genomic_browser/php/provisioners/snpprovisioner.class.inc, modules/genomic_browser/php/uploading/genomicfile.class.inc, modules/genomic_browser/test/TestPlan.md, modules/genomic_browser/test/genomic_browserTest.php
- Help was missing, added something basic so that there is at least something
- Removed DoB from the data as it was visible when downloading the CSV.
- Cleaned up the TestPlan document
- Makes Upload Form button only appear when you have permission to Upload to genomic browser
- Close FileUploadModal after successful upload
- Fixes the File Upload to work properly
1. Check that helptext loads
2. Download csv from tabs and confirm DoB is no longer present
3. Try to upload a file in the Files tab and confirm it works
4. Remove the genomic_browser_upload permission and confirm you do not see the Upload File button in the Files tab
* Resolves #7597
* Resolves #7596
* Resolves #7591
* Resolves #7590
=> [genomic_browser] Solve the issues

modules/genomic_browser/php/uploading/genomicfile.class.inc, modules/imaging_browser/php/mricommentdictionaryitem.class.inc, modules/imaging_browser/php/mrifeedbackdictionaryitem.class.inc, modules/imaging_browser/php/mripredefinedcommentdictionaryitem.class.inc, modules/imaging_browser/php/parameterdictionaryitem.class.inc, modules/imaging_browser/php/queryengine.class.inc, php/libraries/FeedbackMRI.class.inc
This PR that adds the MRI variables in the imaging_browser's query engine. The information used to set the variable values sometimes differs from those used in `CouchDB_MRI_Importer` but I put comments in the code for those cases.
(This is a re-issue of PR #9545 on branch `27.0-release`)
Fixes #9374
=> Add the MRI variables in the imaging_browser's query engine

modules/genomic_browser/jsx/tabs_content/gwas.js, modules/genomic_browser/php/filemanager.class.inc, modules/genomic_browser/php/uploading/genomicfile.class.inc
There were static tests that were failing on the 27.0-release branch related to the genomic browser. This fixes them so that the build passes.
=> [genomic_browser/27 branch] Fix build errors on 27 branch

modules/instruments/php/instrumentqueryengine.class.inc
fix "query not run yet"
Numeric value out of range: 1264 Out of range value for column 'CandID' at row 677#0 /var/www/Loris/modules/instruments/php/instrumentqueryengine.class.inc(257): PDOStatement->execute()\n#1 /var/www/Loris/modules/dataquery/php/querydataprovisioner.class.inc(82): LORIS\\instruments\\InstrumentQueryEngine->getCandidateData()\n#2 /var/www/Loris/src/Data/ProvisionerInstance.php(116): LORIS\\dataquery\\QueryDataProvisioner->getAllInstances()\n#3 /var/www/Loris/modules/dataquery/php/querydataprovisioner.class.inc(41): LORIS\\Data\\ProvisionerInstance->execute()\n#4 /var/www/Loris/modules/dataquery/php/endpoints/queries/query/run.class.inc(69): LORIS\\dataquery\\QueryDataProvisioner->execute()\n#5 /var/www/Loris/modules/dataquery/php/endpoints/queries/query/run.class.inc(4 …
=> [dataquerytool] fix Numeric value out of range: 1264 Out of range value for column 'CandID' at row 

modules/redcap/php/endpoints/notifications.class.inc
Found this while doing some tests. This seems like a security issue.
=> Remove debug code in the REDCap module

modules/instruments/php/instrumentqueryengine.class.inc
[DataQueryTool] Query stuck when CandID is NULL — add safeguard  #9835
test:
Add a condition to check if CandID is NULL in any query. If any CandID is 0, it will cause the query to hang or behave unexpectedly
What did you expect to happen?
It should show "no results found"
=> [DataQueryTool] Query stuck when CandID is NULL — add safeguard  #9835 -fix

modules/instruments/php/instrumentqueryengine.class.inc
" FILE: ...r/work/Loris/Loris/modules/instruments/php/instrumentqueryengine.class.inc
256 | ERROR | [x] Line indented incorrectly; expected at least 12 spaces,
|       |     found 8
257 | ERROR | [x] Line indented incorrectly; expected at least 12 spaces,
|       |     found 8
257 | ERROR | [x] Whitespace found at end of line
Time: [37](https://github.com/aces/Loris/actions/runs/15588881822/job/43902390350?pr=9843#step:12:38).25 secs; Memory: 28MB
make: *** [Makefile:[38](https://github.com/aces/Loris/actions/runs/15588881822/job/43902390350?pr=9843#step:12:39): checkstatic] Error 2"
=> fix cs error in github actions

jsx/Form.js, modules/document_repository/jsx/uploadForm.js
Closes #9768 
This PR adds the `disabledLabel` attribute to `jsx/Form`'s `ButtonElement`.
It also sets this value to the intended value for the `document_repository`'s upload button.
=> [jsx - document_repository] Add disabledLabel to ButtonElement

php/libraries/LorisFormDictionaryImpl.class.inc
Modifies LorisFormDictionaryImpl.class.inc library file to properly populate the values in the data-dictionary. Thus it fixed the original issue identified in the dataquery module.
1. Go the new dictionary.
2. The fields should be properly populated and the issue reported and commented in #9801 not longer present. 
* Resolves #9801
=> [dictionary] Fixes description field been populated with the latest select option, not the actual field name.

modules/issue_tracker/php/edit.class.inc, modules/issue_tracker/php/issue.class.inc
This PR edits the issue tracker code to fix a users abilities for various permissions. Following this PR, users should only be able to do exactly what the permission describes that they should be able to do. 
1. Make sure you do not have access to the issue tracker module without any issue tracker permissions
2. Grant your user the `Issue Tracker: View/Edit/Comment/Close Issues - Own` permission. 
3. Make sure you are able to view, create, and close (in the status option) your own issues and no others. 
4. Other issues should not be viewable in the filterable datatable or through a direct link
5. Grant your use the `Issue Tracker: View/Edit/Comment Issues - Own Sites` permission. 
6. You should now be able to view, edit, and comment on issues at your user's sites, or at "All sites", but …
=> [issue_tracker] Fix permissions

jsx/Modal.tsx
Closes #9854.
This was not a critical error but is fixed by adding `name` to `FormElement` in `jsx/Modal.tsx`
=> [dataquery - jsx/Modal] Add 'name' attribute to FormElement

modules/dataquery/php/endpoints/queries.class.inc
This PR modifies the data query endpoint so that changes to table `dataquery_queries` are not saved in the `history` table anymore.
Fixes #9847
=> [dataquery] Changes to table dataquery_queries are not saved in the history table anymore

modules/dataquery/jsx/definefilters.tsx, modules/dataquery/jsx/querytree.tsx
- Removing the strikethrough from the subgroup after delete and re-add.
1. go to Beta(dataquery).
2. Add filters.
3. Add a condition (Add two conditions).
4. Add a subgroup and remove it.
5. Re-add the subgroup. You will notice the strikethrough is removed.
- https://github.com/aces/Loris/issues/9849
=> [dataquery]Remove Strikethrough From New Flters Subgroup

src/Data/Query/SQLQueryEngine.php
This PR fixes a bug that would cause the queries run by the SQL engine to fail if any of the variables it depended on contained a question mark. The PR escapes escapes the question marks so that PDO does not interpret them as positional placeholders.
Reference: [https://www.php.net/manual/en/pdo.prepare.php](url)
Fixes #9884
=> The SQL engine now supports dictionary names containing question marks

.eslintrc.json, modules/dataquery/jsx/definefilters.importcsvmodal.tsx, modules/issue_tracker/jsx/issueTrackerIndex.js
"npm run lintfix;js" currently generates hundreds of changes because the rules enforced don't match the coding style of the codebase.
This fixes the rule for the number of lines between the tagblock and the params to match what's actually used by the codebase, and fixes the couple leftovers that were wrong.
=> Fix eslint line rules

Makefile, jsx/DataTable.js, jsx/Filter.js, jsx/FilterableDataTable.js, locale/ja/LC_MESSAGES/loris.po, locale/loris.pot, modules/acknowledgements/jsx/acknowledgementsIndex.js, modules/battery_manager/jsx/batteryManagerIndex.js, modules/behavioural_qc/jsx/behaviouralQCIndex.js, modules/candidate_list/jsx/candidateListIndex.js, modules/conflict_resolver/jsx/conflict_resolver.js, modules/conflict_resolver/jsx/resolved_filterabledatatable.js, modules/conflict_resolver/jsx/unresolved_filterabledatatable.js, modules/datadict/jsx/dataDictIndex.js, modules/dicom_archive/jsx/dicom_archive.js, modules/dictionary/jsx/dataDictIndex.js, modules/electrophysiology_browser/jsx/electrophysiologyBrowserIndex.js, modules/examiner/jsx/examinerIndex.js, modules/genomic_browser/jsx/genomicBrowserIndex.js, modules/imaging_browser/jsx/imagingBrowserIndex.js, modules/media/jsx/mediaIndex.js, modules/server_processes_manager/jsx/server_processes_managerIndex.js, modules/server_processes_manager/php/module.class.inc, modules/statistics/jsx/WidgetIndex.js, modules/statistics/jsx/widgets/helpers/queryChartForm.js, modules/survey_accounts/jsx/surveyAccountsIndex.js, modules/user_accounts/jsx/userAccountsIndex.js
This translates the DataTable jsx component used within LORIS menus, so that the candidate_list menu is fully translated.
Blocked by #9797 (because of javascript dependencies) and will be easier to review once that is merged.
=> Translate DataTable

modules/redcap/php/client/models/mappings/iredcapinstrumentevent.class.inc, modules/redcap/php/client/models/mappings/redcapinstrumenteventmap.class.inc, modules/redcap/php/client/models/mappings/redcaprepeatinginstrumentevent.class.inc, modules/redcap/php/client/models/redcapnotification.class.inc, modules/redcap/php/client/redcaphttpclient.class.inc, modules/redcap/php/config/redcapconfig.class.inc, modules/redcap/php/config/redcapconfigparser.class.inc, modules/redcap/php/endpoints/notifications.class.inc, modules/redcap/php/redcapmapper.class.inc, modules/redcap/php/redcapnotificationhandler.class.inc, modules/redcap/php/redcapqueries.class.inc
This PR contains a few small code improvements to the REDCap module. It does not change the behavior of the module, but it will be followed up by another PR that adds automatic session creation when new data is received from REDCap.
List of changes:
- Extract REDCap / LORIS mapping methods from `RedcapNotificationHandler` to a new `RedcapMapper` class, allowing to use those methods without a REDCap notification, which is useful to write a clean REDCap bulk import script.
- Move the `getIssueAssignee()` method from the `RedcapConfigParser` class to the `RedcapQueries` (previously `Queries`) class, as the REDCap issue assignee has previously been moved from the XML configuration to the database.
- Correctly rename all relevant variables and methods to match REDCap "event names" and "unique …
=> REDCap module improvements

tools/assign_missing_instruments.php, tools/data_integrity/data_deletion/delete_ignored_conflicts.php, tools/fix_timepoint_date_problems.php, tools/lorisform_parser.php, tools/mri_violations_resolver.php, tools/single_use/DB_date_zeros_removal.php, tools/update_issues_with_description.php
This makes the tools directory scripts which independently called NDB_Client use generic_includes.php, including it where necessary and removing duplicated code that is already done by generic_includes.php.
=> [Scripts] Consistent use of generic_includes

modules/issue_tracker/php/edit.class.inc
The create new issue page breaks
Testing:
Click the `New Issue` button and see if the page loads.
=> [issue_tracker] fix new issue creation breaking IBIS v27

modules/redcap/php/redcapnotificationhandler.class.inc
I have an instrument with some integer-like field names in REDCap ("0" / "1"), this caused a type error in `RedcapNotificationHandler` with "`string` expected, `int` given". After investigating a bit, REDCap correctly sends the field namesas strings but it turns out that PHP implicitly converts array keys to integers if they look like integers.
- Add a `strval` in the regex matching where the field name is required to be a string.
- Make `_formatEnumFields` slightly less unreadable by using a `foreach` instead of `array_keys` / `array_reduce`.
=> [redcap] Fix record field name implicit `int` conversion

modules/redcap/CONFIGURATION.md, modules/redcap/php/client/models/records/redcaprecord.class.inc, modules/redcap/php/config/redcapconfigcreatesession.class.inc, modules/redcap/php/config/redcapconfigparser.class.inc, modules/redcap/php/config/redcapconfigvisit.class.inc, modules/redcap/php/redcapmapper.class.inc, modules/redcap/php/redcapnotificationhandler.class.inc
First two commits are #9839.
Successfully tested in C-BIG dev (in a backported version).
=> [redcap] Add REDCap automatic session creation

modules/conflict_resolver/php/module.class.inc, modules/dashboard/locale/dashboard.pot, modules/dashboard/locale/ja/LC_MESSAGES/dashboard.po, modules/dashboard/php/taskquerywidget.class.inc, modules/imaging_browser/locale/imaging_browser.pot, modules/imaging_browser/locale/ja/LC_MESSAGES/imaging_browser.po, modules/imaging_browser/php/module.class.inc, modules/instruments/locale/instruments.pot, modules/instruments/locale/ja/LC_MESSAGES/instruments.po, modules/instruments/php/module.class.inc, modules/issue_tracker/locale/issue_tracker.pot, modules/issue_tracker/locale/ja/LC_MESSAGES/issue_tracker.po, modules/issue_tracker/php/module.class.inc, modules/mri_violations/locale/ja/LC_MESSAGES/mri_violations.po, modules/mri_violations/locale/mri_violations.pot, modules/mri_violations/php/module.class.inc, modules/user_accounts/locale/ja/LC_MESSAGES/user_accounts.po, modules/user_accounts/locale/user_accounts.pot, modules/user_accounts/php/module.class.inc
This builds on #9747 to add support for translating the "My Tasks" widgets on the LORIS dashboard. In the current code, an "s" is hardcoded to be added when count > 1, which doesn't work for other languages.
The signature had to be updated to include a singular and plural label, as well as the text domain that the labels come from, since they come from the module providing the widget and not the dashboard. (The dngettext call also could not be done in the module, because the module doesn't have the count to know if it's plural.)
=> [i18n] Dashboard -- My Tasks

docs/wiki/00_SERVER_INSTALL_AND_CONFIGURATION/01_LORIS_Install/Ubuntu/README.md
The IntlDateFormatter used in PR #9981 to provide locale specific date formatting is a standard part of PHP, but requires the php8.3-intl to be installed. Update the docs to mention it.
I believe we also require the curl extension in general now, because of a dependency that uses it, so remove the note saying it's "for development only".
=> [docs] Add intl dependency

locale/ja/LC_MESSAGES/loris.po, modules/candidate_list/locale/ja/LC_MESSAGES/candidate_list.po
Some incorrect namespaces were fixed in the Hindi translation in PR#9899, but they had already been incorrectly merged into the Japanese .po files in another PR.
This moves the strings in the Japanese localization so that they load again.
=> [candidate_list] Fix Japanese translation namespaces

modules/conflict_resolver/php/module.class.inc, modules/dashboard/php/taskquerywidget.class.inc, modules/imaging_browser/php/module.class.inc, modules/instruments/php/module.class.inc, modules/issue_tracker/php/module.class.inc, modules/user_accounts/php/module.class.inc, src/GUI/LocalizableString.php
There are numerous places in the code where we need to provide a label, but don't yet know the cardinality of the data that the label is going to be provided for. (Often in widgets.)
This provides a "LocalizableString" class for strings that will eventually need to be translated by dngettext, but where we don't yet know the number of things for the label at the point where we are creating it.
1. There should be no visible changes to LORIS. In particular, the "My Tasks" widgets should all have the exact same behaviour as before.
=> [Localization] add LocalizableString class

jsx/DataTable.js
This change modifies the transformation of csvData in the DataTable component by replacing .flatMap() with .map().
•	Before: csvData was a flattened array of mapped cells across all fields and rows.
•	After: csvData is now a nested array (Array<Array<Cell>>), preserving the structure of rows.
•	This aligns better with expected downstream usage or fixes unintended flattening issues in CSV processing.
=> [JSX] Revert CSV data transformation: replace flatMap with map

tools/redcap2linst.php
Remove the `{-@-}` prefix from the `redcap2linst.php` script as it is deprecated. As discussed on Slack, it was currently present because HBCD uses an old version of the data dictionary, but newer projects such as C-BIG do not want it and it should be handled by HBCD at the project level.
* Add an opt-in option `--use-legacy-linst` (name not fixed) to keep the old behavior ?
=> [redcap] Fix REDCap to LINST test name prefix

jsx/DataTable.js
[battery_manager] Filtering for minimum age/maximum age = 0 does not work#9967
fixed:<img width="852" height="654" alt="截屏2025-08-28 下午7 53 00" src="https://github.com/user-attachments/assets/3ed44b71-5e0d-451c-8f56-2bbce66c77a2" />
=> [battery_manager] Filtering for minimum age/maximum age = 0 does not work  -  fix 

SQL/Release_patches/26.0_To_27.0_upgrade.sql
=> IBIS 27 update patch file

locale/ja/LC_MESSAGES/loris.po, locale/loris.pot, modules/candidate_list/locale/ja/LC_MESSAGES/candidate_list.json, modules/dictionary/jsx/dataDictIndex.js, modules/dictionary/locale/dictionary.pot, modules/dictionary/locale/ja/LC_MESSAGES/dictionary.po, modules/dictionary/php/datadictrowprovisioner.class.inc, modules/dictionary/php/dictionary.class.inc
The row name keys in the json passed by the DataTable are translated, so the key looking up the "Field Name" needs to be translated when looking up information from them.
Fixes #10011.
Also adds an explicit label for the "Cancel" button as it was not translated (the label came from swal when not explicitly provided.)
=> [dictionary] Fix override functionality in non-English languages

locale/es/LC_MESSAGES/loris.po, locale/ja/LC_MESSAGES/loris.po, locale/loris.pot, modules/timepoint_list/locale/es/LC_MESSAGES/timepoint_list.po, modules/timepoint_list/locale/ja/LC_MESSAGES/timepoint_list.po, modules/timepoint_list/templates/menu_timepoint_list.tpl
Add Japanese translation strings for the timepoint_list module.
Also re-added the file headers and instead added a guard around the empty string before calling gettext. Gettext("") returns the file header by design (see: https://stackoverflow.com/questions/7610144/why-does-gettext-translate-an-empty-string-to-the-po-header-text) but also has important meta-data such as the number of plural forms or the character set. We may want to consider adding a wrapper around (d)(n)gettext to handle this more generally.
Also added a missing gettext around "Project" for the table header, which is already in the loris namespace.
=> [timepoint_list] Translates Timepoint list module to Japanese.

modules/dashboard/test/DashboardTest.php, modules/login/php/logout.class.inc, smarty/templates/main.tpl
There is no need to be able to log out on every request. This creates a specific logout endpoint to be explicitly called when the user wants to log out and removes the unnecessary code from NDB_Client.
=> [Login/NDB_Client] Create logout endpoint

docs/wiki/99_Developers/Translating.md, readthedocs/mkdocs.yml
This adds documentation to our readthedocs with instructions for how to add translations for new languages to LORIS.
The target audience is a non-developer who wants to contribute to LORIS that speaks multiple languages, but the RTD didn't really have any better section than "99_Developers" to put it in.
I'd like to add a link it to `CONTRIBUTING.md`, but the first few paragraphs of our `CONTRIBUTING.md` is assuming the reader is a developer and needs to be reworked slightly, so I think that should be updated separately.
=> [docs] Add translator instructions to LORIS readthedocs
