htdocs/main.php
CSS was not being fetched properly due to the new rewrite rules.
=> Fixing CSS fetching for the mod_rewrite rules

tools/install.sh
Changing group to www-data to give permission to create directories in Document Repository module
=> Changing Doc Repo's user_uploads dir group to www-data

php/libraries/Database.class.inc
This adds the date/time to showDatabase queries.
=> Adds the timestamp to showDatabase queries

tools/CouchDB_Import_MRI.php
This updates the CouchDB Import script for MRIs to add all the selected scans to CouchDB so that download functionality will work. This has been live in IBIS for quite a while, but is missing in aces/Loris.
=> Add MINC attachment support to CouchDB

modules/user_accounts/php/NDB_Form_user_accounts.class.inc, php/libraries/User.class.inc
Update to code include : 
1) In modules user account - no need to create another user instance as its already done at the beginning of the process function. The set array does no contain userID key and this will lead to issue with the user object further in the code
2) In the User class in the updateCouchUser function , the userobj was not initialized before it was used.
=> Fixing issue with creating user object before updating couch host

.travis.yml, composer.json, composer.lock, test/integrationtests/Login_Test.php
This updates the Login_Test to use facebook's PHP webdriver implementation, instead of phpunit's selenium plugin. Facebook's is better maintained and more closely follows the WebDrvier spec, which makes it much easier to find help/documentation for.
=> WebDriver test implementation

.travis.yml, htdocs/lost_password.php, htdocs/main.php, htdocs/request_account/process_new_account.php, php/libraries/NDB_Config.class.inc, php/libraries/SinglePointLogin.class.inc, smarty/templates/login.tpl, smarty/templates/lost_password.tpl, smarty/templates/password_expiry.tpl, smarty/templates/process_new_account.tpl
This updates the NDB_Config class to throw a ConfigurationException when a configuration does not exist in either the database or config.xml
=> Invalid Config Exception

.travis.yml, docs/LorisCS.xml, htdocs/AjaxHelper.php, htdocs/GetJS.php, htdocs/GetStatic.php, htdocs/feedback_bvl_popup.php, htdocs/feedback_mri_popup.php, htdocs/lost_password.php, htdocs/main.php, htdocs/mri/jiv/get_file.php, htdocs/mri/jiv/show_one_jiv_file.php, htdocs/request_account/process_new_account.php, htdocs/request_account/thank-you.html, htdocs/request_account/verificationimage.php, htdocs/survey.php
I've fixed all the phpcs errors in htdocs and added it to Travis, to ensure that the coding style stays clean.
=> Ran PHPCS on htdocs directory

docs/config/config.xml
Update default subproject titles to be representative of what a subproject is intended to be.
=> Config.xml: update default subproject titles

.travis.yml, modules/candidate_list/js/candidate_list.js, modules/candidate_list/php/NDB_Menu_Filter_candidate_list.class.inc
Ran PHPCS on the candidate_list module.
=> PHP CodeSniffer on candidate_list module

SQL/0000-00-00-schema.sql, SQL/2015-02-16-SupplementalSessionStatus.sql, docs/config/config.xml
SupplementalSessionStatus was missing but code was referring to it
=> Adding SupplementalSessionStatus config

htdocs/main.css, modules/help_editor/js/help_editor.js, modules/help_editor/templates/form_edit_help_content.tpl
Redmine6656 : fixing bugs in help module
=> Creating function which uses window history for back button

modules/candidate_list/php/NDB_Menu_Filter_candidate_list.class.inc, modules/candidate_list/templates/menu_candidate_list.tpl
Also fixing problem with the query that was breaking the access profile
=> Redmine5274: Adding total rows in access profile

modules/mri_upload/test/mri_uploadTest.php
Removed the teardown function as it is currently causing conflicts.
=> Removed the teardown function

.travis.yml, docs/config/config.xml, modules/dashboard/ajax/get_recruitment_bar_data.php, modules/dashboard/ajax/get_recruitment_line_data.php, modules/dashboard/ajax/get_recruitment_pie_data.php, modules/dashboard/ajax/get_scan_line_data.php, modules/dashboard/php/NDB_Form_dashboard.class.inc, modules/dashboard/templates/form_dashboard.tpl, modules/dashboard/templates/progress_bar.tpl
- Adds a view to the recruitment panel showing recruitment per project. This only shows up if the "useProject" flag is set to true
- Code cleaned up; template for progress bars now in a separate file.
- PHPCS has been run; dashboard now in travis
=> Dashboard with project-based recruitment breakdown

.travis.yml, modules/statistics/tests/Statistics_Test.php, smarty/templates/main.tpl
Added basic tests for stats page. This ensures that:
1. The page loads
2. The page has a clickable "Demographic" link
3. The "General" stats tab loads
=> Added basic tests for stats page

docs/instruments/NDB_BVL_Instrument_TEMPLATE.class.inc, docs/instruments/NDB_BVL_Instrument_UPLOADER_TEMPLATE.class.inc
* Adding sample SQL statements
* Fixing issue with Uploader template - adding missing functions
=> Updating sample instrument files 

.travis.yml, modules/dashboard/test/DashboardTest.php, test/integrationtests/LorisIntegrationTest.class.inc
Tests that the welcome panel contains the text "Welcome"
=> Adding a basic integration test for the dashboard

.gitignore, .travis.yml, modules/configuration/test/ConfigurationTest.php, modules/dashboard/test/DashboardTest.php, modules/instrument_builder/test/instrument_builderTest.php, modules/instrument_list/tests/instrument_listTest.php, modules/instrument_manager/tests/instrument_managerTest.php, modules/mri_upload/test/instrument_managerTest.php, modules/mri_upload/test/mri_uploadTest.php, modules/mri_violations/test/mri_violationsTest.php, modules/next_stage/test/next_stageTest.php, modules/reliability/test/reliabilityTest.php, modules/statistics/tests/Statistics_Test.php, modules/survey_accounts/test/survey_accountsTest.php, modules/timepoint_flag/test/timepoint_flagTest.php, modules/user_accounts/test/user_accountsTest.php, test/integrationtests/Login_Test.php, test/integrationtests/LorisIntegrationTest.class.inc
adding automated tests for the following modules: user_accounts, timepoint_flag, survey_accounts, reliability, next_stage, mri_violations, mri_upload, instrument_manager, instrument_list, instrument_builder.
=> adding phpunit tests for 9 modules.

composer.lock, htdocs/feedback_bvl_popup.php, modules/genomic_browser/php/NDB_Menu_Filter_genomic_browser.class.inc, modules/genomic_browser/php/NDB_Menu_Filter_snp_browser.class.inc, php/libraries/NDB_BVL_Instrument_LINST.class.inc, php/libraries/NDB_Breadcrumb.class.inc, php/libraries/NDB_Config.class.inc, php/libraries/NDB_Menu_Filter.class.inc, php/libraries/User.class.inc
The version of PHPCS installed by composer is currently 2.1, but the most recent version is 2.3. This updates to the most recent version and fixes any new problems found.
=> PHPCodesniffer Upgrade

modules/timepoint_list/js/timepoint_list.js, modules/timepoint_list/templates/menu_timepoint_list.tpl
updating module to use post request to set filter in imaging browser when Scan done link is clicked
=> Linking timepoint imagingbrowser

modules/candidate_list/js/candidate_list.js, modules/candidate_list/php/NDB_Menu_Filter_candidate_list.class.inc, modules/candidate_list/templates/menu_candidate_list.tpl
* Added Visit label dropdown to allow filtering for candidates if they have the visit
* Added code to make open profile visible only if user does not have access all profiles permission
* Added code to make open profile be inside a panel that can be toggled 
* Made the filters to be three columns instead of two
=> Candidate List Menu filter update

tools/CouchDB_Confirm_Integrity.php, tools/CouchDB_Import_Demographics.php, tools/CouchDB_Import_Instruments.php, tools/CouchDB_Import_MRI.php, tools/CouchDB_Import_RadiologicalReview.php, tools/assign_missing_instruments.php, tools/config_to_db.php, tools/delete_candidate.php, tools/detect_conflicts.php, tools/detect_duplicated_commentids.php, tools/excelDump.php, tools/fix_timepoint_date_problems.php, tools/generate_tables_sql.php, tools/generate_tables_sql_and_testNames.php, tools/populate_visit_windows.php, tools/populateage.php, tools/recreate_conflicts.php, tools/score_instrument.php
=> add require_once autoload to php scripts don't already have it. 

SQL/0000-00-00-schema.sql, SQL/2015-04-04-ServerProcessLauncher.sql, modules/mri_upload/php/NDB_Menu_Filter_mri_upload.class.inc, modules/server_processes_manager/ajax/ProcessStateRequestHandler.php, modules/server_processes_manager/php/AbstractServerProcess.class.inc, modules/server_processes_manager/php/DefaultDatabaseProvider.class.inc, modules/server_processes_manager/php/DefaultProcessMonitor.class.inc, modules/server_processes_manager/php/IDatabaseProvider.class.inc, modules/server_processes_manager/php/IProcessMonitor.class.inc, modules/server_processes_manager/php/MriUploadServerProcess.class.inc, modules/server_processes_manager/php/NDB_Menu_Filter_server_processes_manager.class.inc, modules/server_processes_manager/php/Process.class.inc, modules/server_processes_manager/php/ServerProcessFactory.class.inc, modules/server_processes_manager/php/ServerProcessLauncher.class.inc, modules/server_processes_manager/php/ServerProcessesMonitor.class.inc, modules/server_processes_manager/templates/menu_server_processes_manager.tpl
First draft for the server process manager. The manager will be used to launch asynchronous processes on the server from the LORIS web client.
=> This commit is the first draft for the server process manager.

.travis.yml, SQL/0000-00-00-schema.sql, SQL/2015-03-17-TrainingModule.sql, htdocs/main.css, modules/training/ajax/getTabContent.php, modules/training/ajax/getTabs.php, modules/training/ajax/getTrainingDoc.php, modules/training/ajax/markQuiz.php, modules/training/css/training.css, modules/training/js/training.js, modules/training/php/NDB_Form_training.class.inc, modules/training/templates/form_training.tpl, modules/training/templates/training.tpl, modules/training/templates/training_pdf.tpl, modules/training/templates/training_quiz.tpl, modules/training/templates/training_tabs.tpl, modules/training/templates/training_video.tpl, modules/training/test/TrainingTest.php, modules/training/training_docs/.gitignore
Separating the training module from the examiner module.
- Adds a basic integration test for the training module
Caveat: removes the H4 styling from the main.css because it interferes with the regular bootstrap styling. I looked quickly through LORIS and don't see anywhere that is affected by this change. I also searched the codebase and H4 doesn't appear to be used anywhere, accept for in the CSS files.
=> Training module

SQL/0000-00-00-schema.sql, modules/mri_upload/test/mri_uploadTest.php
This pull-request adds the missing permission for the mri_upload
=> Missing mri upload permission dummy schema

modules/instrument_builder/js/instrument_builder.instrument.js
add the download element to the document body so that it could be dynamically clicked in firefox. Removed the element once it was clicked.
This branch is based off of pull request #1017
=> Instrument builder firefox fix

modules/new_profile/test/new_profileTest.php, test/integrationtests/LorisIntegrationTest.class.inc
This automates steps 1-3 of the test plan for the new profile
link to be run automatically by Travis.
=> Automate New Profile Tests

modules/imaging_browser/templates/form_viewSession.tpl
This fixes redmine task [#6693](https://redmine.cbrain.mcgill.ca/issues/6693).
=> Bug fix to scroll in BB popup window using Firefox. 

smarty/templates/main.tpl
kgkjgkjg didn't make as much sense.
=> Renaming kgkjgkjg div in main.tpl

modules/training/php/NDB_Form_training.class.inc
the loading of test list was breaking with only one item, working with >1.
fix was to use of utility:toArray()
-->> check for same bug on examiner module.
=> Training bugs 1 -

tools/install.sh
Includes:
* Fixing Apache configuration for CentOS
* Making "LORIS" more consistent
* Clarifications on LORIS 'admin' user and MySQL lorisuser to be created later on by the script
* Misc clean ups
=> Install script improvements

modules/final_radiological_review/php/NDB_Form_final_radiological_review.class.inc
* Loris Form issue - post request contains static elements on the page. This needs to be resolved properly. Redmine ticket with all information has been logged : https://redmine.cbrain.mcgill.ca/issues/7364
=> Fixing issue with saving values in radiology review form

htdocs/request_account/process_new_account.php
Corrected the URL for the request account thank you page.
=> Fixed broken URL for the request account thank you page

modules/candidate_list/php/NDB_Menu_Filter_candidate_list.class.inc, php/libraries/Candidate.class.inc
Config call to visitLabels was not calling an existing tagset
=> Fix spurious config call

modules/candidate_list/php/NDB_Menu_Filter_candidate_list.class.inc, smarty/templates/login.tpl
=> Remove spurious bracket

modules/document_repository/css/document_repository.css, modules/document_repository/js/document_repository.js, modules/document_repository/templates/menu_document_repository.tpl
Fix various bugs introduced wight
=> Doc repo bug fixes

php/libraries/NDB_BVL_Instrument.class.inc
transcript of bug
```
tstrauss@ace-ws-10:/var/www/ccna/tools$ ls ../project/instruments/NDB_BVL_Instrument_General_Health_Vision.class.inc | php quickform_parser.php 
../project/instruments/NDB_BVL_Instrument_General_Health_Vision.class.inc
Reading file ../project/instruments/NDB_BVL_Instrument_General_Health_Vision.class.inc
Instrument found: NDB_BVL_Instrument_General_Health_Vision
Requiring file...
Instantiating new object...
Initializing instrument object...
PHP Notice:  Undefined variable: CertificationProjects in /var/www/ccna/php/libraries/NDB_BVL_Instrument.class.inc on line 866
PHP Stack trace:
PHP   1. {main}() /var/www/ccna/tools/quickform_parser.php:0
PHP   2. NDB_BVL_Instrument_General_Health_Vision->setup() /var/www/ccna/tools/quickform_parser.php:56
PHP   3. …
```
=> Instrument parsing bug certification variables

modules/candidate_list/ajax/validateProfileIDs.php, modules/candidate_list/js/candidate_list.js, modules/candidate_list/php/NDB_Menu_Filter_candidate_list.class.inc, modules/candidate_list/templates/menu_candidate_list.tpl, php/libraries/Candidate.class.inc, php/libraries/NDB_Page.class.inc
In Access Profile module (candidate_list), form "Open Profile":
- added validation for DCCID & PSCID, checking they match before submitting form
- bug fix: wrong var was submitted, timepoint_list expects a GET[‘candID’], but GET[‘DCCID’] was submitted
=> Candidate list ids mismatch 7263

modules/candidate_list/templates/menu_candidate_list.tpl
This file was responsible for toggling the advanced filters on load depending on if a filter was set or not
=> Add advancedFilter JavaScript file to candidate list

modules/training/ajax/getTrainingDoc.php, modules/training/templates/training_video.tpl
- route requests for pdf or mp4 training docs to the /project/data/training folder
- implement AJAX file lookup for training video
=> Training docs path

modules/examiner/php/NDB_Form_examiner.class.inc, modules/examiner/templates/form_editExaminer.tpl
- modified SELECT query to retrieve examiner's site name.  
- using Database factory instead of `Database::singleton()`
=> Examiner module: display site name on edit examiner page

modules/conflict_resolver/php/NDB_Menu_Filter_Form_conflict_resolver.class.inc, modules/data_team_helper/js/data_team_helper.js, modules/data_team_helper/templates/form_data_team_helper.tpl
Fixing link to conflict resolver. Using POST request, otherwise filter is not applied.
=> Fix link to conflict resolver in data team helper module

php/libraries/NDB_BVL_Instrument_instrument_preview.class.inc
fix the bug where the instrument builder preview page wasn't loading
=> get instrument preview displaying again

modules/document_repository/ajax/documentEditUpload.php, modules/document_repository/js/document_repository.js, modules/document_repository/templates/menu_document_repository.tpl
You were able to edit a file to not have a category. This would lead to the category not showing up in the frontend, making it seem like it was deleted from the DB
=> Fix bug in editing a file

SQL/0000-00-00-schema.sql, SQL/2015-04-14_imaging_upload_auto_launch_config_option.sql, modules/mri_upload/php/NDB_Menu_Filter_mri_upload.class.inc
This pull request includes a new config option called "ImagingUploaderAutoLaunch" which indicates whether the imaging-upload pre-processing scripts should be ran automatically by the ServerProcessLauncher on the front-end or not.
=> Mri upload auto launcher config option

modules/document_repository/ajax/addCategory.php, modules/document_repository/js/document_repository.js, modules/document_repository/templates/menu_document_repository.tpl
Add a check in the backend to ensure that the category name is set. Return a 400 error if not.
=> check to ensure that the category name is set on add category

modules/data_team_helper/js/data_team_helper.js, modules/data_team_helper/php/NDB_Form_data_team_helper.class.inc, modules/data_team_helper/templates/form_data_team_helper.tpl
"Show Data" button did not reload/refresh page, if filter drop drop down selections was not changed.
=> fix show data button in data team helper

modules/user_accounts/php/NDB_Form_user_accounts.class.inc, modules/user_accounts/templates/form_edit_user.tpl, php/libraries/LorisForm.class.inc
Namely:
- Required fields could be missing and the form could be saved anyway
- Password validation did not work
- Email uniqueness check was buggy
- Focus is now transferred to the first invalid field
- Generate new Password could be checked even though Send email was not.
=> This fixes a lot of issues with the User Account/My Preferences/Add User page

SQL/0000-00-00-schema.sql, SQL/2015-04-27_MRI_upload_phantom_option.sql, modules/mri_upload/php/NDB_Menu_Filter_mri_upload.class.inc, modules/mri_upload/templates/menu_mri_upload.tpl
This pull request adds a phantom drop-down with Yes and No options (By default No) on the front-end. If 'Yes' is selected, the PSCID, Candid and Visit-label options will not be required.
=> Imaging uploader phantom option

php/libraries/NDB_Config.class.inc
Fixed a bug that would report that a setting exists in the XML config file even though it does not.
=> Fixed a bug that would report that a setting exists in the XML config file even though it does not.

tools/CouchDB_Confirm_Integrity.php
The CouchDB_Confirm_Integrity script which deletes invalid documents
that got inserted into CouchDB (ie. things that have been deleted from
the database) to ensure consistency between MySQL and CouchDB was
deleting cancelled Visit labels. However, it's possible that the visit
was cancelled and replaced by a new session with the same Visit label,
and this caused the new session to be incorrectly deleted from CouchDB.
This adds a check to ensure that it only deletes cancelled session if
there is no active equivalent.
=> Check for an equivalent active session when a cancelled session is found

modules/statistics/php/NDB_Form_statistics.class.inc
fix two failing queries that were zapping the imaging tab.
there are still other bugs in the imaging tab, but it now it opens.
https://redmine.cbrain.mcgill.ca/issues/6706
=> [Rebased] Fix Stats - Imaging tab not displaying [redmine 6706]

README.md
Added optional step to set config variables if the server is not running on localhost.
=> Updated README to tell people to set host and URL

php/libraries/Utility.class.inc
- Check pull request https://github.com/aces/Loris/pull/1111 has been merged ( Removed call to `getEthnicityList` in this pull request)
- Is this method used by any project?
=> Remove getEthnicityList method from Utility class

docs/config/apache2-site
This was removed / overlooked in a pull request Apr 2
=> Putting back Apache redirect to main.php instead of index.html

composer.json, composer.lock, test/bootstrap.php, test/phpunit.xml, test/unittests/Loris_PHPUnit_Database_TestCase.php
- new abstract Loris_PHPUnit_Database_TestCase class which facilitates DBunit tests
- adding a bootstrap file which:
- includes the autoloader
- include Loris_PHPUnit_Database_TestCase class
- defines path to fixtures (for populating test DB)
- defines path to a test config.xml 
A test DB should be used when running unit tests, therefore a need for a different config.xml file.
=> Setting up phpunit tests with DBUnit

.travis.yml, tools/generic_includes.php
Ran PHPCS on:
* generic_includes.php
* CouchDB_Import_MRI.php
=> Adding more scripts travis' PHPCS

php/libraries/LorisForm.class.inc, test/unittests/LorisForms_Test.php
This adds support for multiselect elements to the LorisForm QuickForm replacement.
=> LorisForm multiselect elements

docs/config/apache2-site
We should discuss whether or not we should still support this file (and other configuration sort of files)
=> Modifying sample Apache config to accommodate Rewrite rules

.travis.yml, modules/configuration/ajax/process.php, modules/configuration/php/NDB_Form_configuration.class.inc
Ran PHPCS on the configuration module
=> Phpcs configuration

php/libraries/Candidate.class.inc, php/libraries/NDB_Factory.class.inc, test/unittests/CandidateTest.php
* implemented unit tests for Candidate class
* some modifications to Candidate class
* replacing singleton by factory
* updating some function docblocks
* adding visibility keyword to functions (mainly public)
* added setters to NDB_Factory to be able to inject test doubles
=> Candidate unittests

README.md
=> Composer requirement in README

CONTRIBUTING.md
I've taken a first stab at writing a friendlier CONTRIBUTING.md file than the one in #933. This is meant as a starting point for the documentfor external people to read, feedback is appreciated.
=> Alternative CONTRIBUTING.md file

php/libraries/NDB_BVL_Instrument.class.inc, php/libraries/Utility.class.inc
This fixes the issue where the 0 was being saved in the db for numeric variables that were set to not answered
=> Instrument numeric save

php/libraries/TimePoint.class.inc
Catching an exception and throwing a different one masks underlying issues and makes it difficult to debug stuff.
=> Change exception that is thrown in the timepoint class

modules/document_repository/js/document_repository.js
This would cause the directories to not expand and their children would not be added to them properly
=> fix replace regex to handle special chars such as *

.travis.yml, php/libraries/NDB_BVL_Feedback.class.inc, php/libraries/NDB_Factory.class.inc, php/libraries/Settings.class.inc, test/bootstrap.php, test/fixtures/tables/NDB_BVL_FeedbackTest.xml, test/fixtures/tables/feedback_bvl_type.xml, test/fixtures/tables/psc.xml, test/unittests/Loris_PHPUnit_Database_TestCase.php, test/unittests/NDB_BVL_FeedbackTest.php, test/unittests/SettingsTest.php, tools/fix_timepoint_date_problems.php
Added `setup` method to `test/unittests/Loris_PHPUnit_Database_TestCase.php` which checks 'sandbox' config before running tests. DBunit test are destructive therefore should not be run in production.
=> Unit tests sandbox check

modules/examiner/php/NDB_Menu_Filter_Form_examiner.class.inc, modules/examiner/templates/menu_examiner.tpl, php/libraries/LorisForm.class.inc, php/libraries/NDB_Page.class.inc
Used the addCheckbox method in the examiner module to test
=> add function to add checkbox in LorisForm

php/libraries/LorisForm.class.inc
Date elements had no min and max years so you could select dates outside the desired range
=> apply min and max dates for date element in LorisForm

tools/install.sh
Implementing prompts for steps within the Install Script
=> Making Install Script more modular

htdocs/main.php
Adding support for Dashboard CSS and JS fetching on main.php in case where instances skip going to index.html and go directly to main.php
=> Adding support for Dashboard CSS and JS fetching on main.php

modules/final_radiological_review/php/NDB_Form_final_radiological_review.class.inc, php/libraries/LorisForm.class.inc
This bug was first seen in the final radiological review module. A quick fix was done (https://github.com/aces/Loris/pull/1076). This is a more permanent fix to the problem
=> fix bug with LorisForm post request with static elements

htdocs/js/components/FilterTable.js, jsx/FilterTable.js, modules/dicom_archive/js/dicom_archive.js, modules/dicom_archive/jsx/dicom_archive.js, modules/dicom_archive/php/NDB_Menu_Filter_dicom_archive.class.inc, modules/dicom_archive/templates/menu_dicom_archive.tpl, smarty/templates/main.tpl
This adds a FilterTable react component that can be used to render the tables where filters are selected on Loris menu pages in Loris modules.
Once again, the dicom_archive is used as an example of how to use this component
=> React Filter table

SQL/Archive/15.10/2015-08-08-ConflictResolver_InProgress.sql, php/libraries/NDB_BVL_InstrumentStatus.class.inc
see PR#1162
only including conflicts where DDE data entry status is 'complete'
remove from conflict resolver conflicts where the data entry status changes to 'in progress'
=> Redmine4319  - Conflict Resolver bug (revised)

modules/conflict_resolver/php/NDB_Menu_Filter_Form_conflict_resolver.class.inc, modules/conflict_resolver/php/NDB_Menu_Filter_resolved_conflicts.class.inc, modules/conflict_resolver/templates/menu_conflict_resolver.tpl, modules/conflict_resolver/templates/menu_resolved_conflicts.tpl
=> Redmine7722 - add "Project" filter to Conflict Resolver

SQL/0000-00-00-schema.sql, SQL/2015-09-14-DropFeedbackBvlTypesSite.sql
Removed obsolete table feedback_bvl_types_site.
=> Removed obsolete table feedback_bvl_types_site.

modules/final_radiological_review/php/NDB_Menu_Filter_final_radiological_review.class.inc
Step to reproduce/test:
1. Click on a review for a particular candidate and edit field 'Review done' in column 'Final Review'.
2. Save.
3. Go back to the main radiological review page.
4. Click on the review you just edited: your change to Review done has been lost...
=> Corrected a bug in the final radiological review.

modules/imaging_uploader/css/imaging_uploader.css, modules/imaging_uploader/js/imaging_uploader.js, modules/imaging_uploader/php/NDB_Menu_Filter_imaging_uploader.class.inc, modules/imaging_uploader/templates/menu_imaging_uploader.tpl
Add progress bar to the imaging uploader
=> Imaging uploader progress bar

php/libraries/Database.class.inc
This class now rely on PDO_Exceptions
But error handling strategies will have to be review for the next release
https://redmine.cbrain.mcgill.ca/issues/8329
=> Database class - Every isError() are removed

modules/dashboard/js/dashboard.js
This caused the dashboard graphs not to load
=> Fix the bug in the dashboard where the c3 graph failed to parse

htdocs/.htaccess
So that LORIS should still work whether or not mod_rewrite is enabled.
=> Wrapping the RewriteEngine rule around IfModule mod_rewrite in .htaccess

htdocs/request_account/process_new_account.php, smarty/templates/process_new_account.tpl
- $baseurl is now assigned a value.
- There is no relative links anymore
- Links to bootstrap.css and main.css now works
- Some display "beautifying"
- Headers have been resized and centred
- LORIS website and GitHub links have been removed (There are still in the login page)
=> Request account - Links and display fixing

docs/config/apache2-site, tools/install.sh
Noticed a mismatch for the path replacements
=> Updating sed replaces for Install

modules/help_editor/test/TestPlan.md, modules/training/test/TestPlan.md
This Pull-Request:
* Fixes small typos in the Test Plans
* Provides a better structure with proper markdown formatting.
=> Test Plan Formatting Improvement

modules/data_team_helper/js/data_team_helper_react.js, modules/data_team_helper/jsx/behavioural_qc_module.jsx
Also I move the jsx file into the modules jsx folder as opposed to the generic jsx folders
=> make links open in new tab without loading in current window

modules/instrument_manager/php/NDB_Menu_Filter_instrument_manager.class.inc, modules/instrument_manager/templates/menu_instrument_manager.tpl
Typo found in both template and class
=> Instrument Manager 'writable' typo

htdocs/js/components/FilterTable.js, jsx/FilterTable.js, modules/dicom_archive/js/dicom_archive.js, modules/dicom_archive/jsx/dicom_archive.js, modules/dicom_archive/php/NDB_Menu_Filter_dicom_archive.class.inc, modules/dicom_archive/templates/menu_dicom_archive.tpl, php/libraries/NDB_Menu_Filter.class.inc
Fixed bug where filters in dicom_archive were not showing value
The current query state was not propagated to the react components.
This adds it.
=> Fix dicom filter values

modules/brainbrowser/css/volume-viewer-demo.css, modules/brainbrowser/templates/form_brainbrowser.tpl
Bug8476
Sync volumes does work but does not style as checked or not.
=> Sync volumes 'check box' does not style correctly if checked or not

php/libraries/Database.class.inc
Will make this throw an exception after the release...?
=> Temporary stub function for isError in Database class

modules/imaging_uploader/js/imaging_uploader.js, modules/imaging_uploader/php/NDB_Menu_Filter_imaging_uploader.class.inc, modules/imaging_uploader/templates/menu_imaging_uploader.tpl
=> Imaging uploader release 1510

modules/imaging_browser/php/Imaging_Session_ControlPanel.class.inc, modules/imaging_browser/test/imaging_browser_test_plan.md, modules/timepoint_list/js/timepoint_list.js, modules/timepoint_list/templates/menu_timepoint_list.tpl
imaging_browser_test_plan more specific
visit_status can now be set to nothing, Bug #8444
Corrected Button View imaging data sets js link, Bug #8426
=> improved test plan, visit_status sets to nothing, View imaging data sets link works

php/libraries/NDB_Menu_Filter.class.inc, test/unittests/NDB_Menu_Filter_Test.php
This removes the failing test from @taracampbell's examiner_sorting branch (pull request #1306) so that it can be merged, as the sorting bug is more important than the whitespace filter..
=> Examiner sorting fixed

modules/candidate_list/ajax/validateProfileIDs.php, modules/candidate_parameters/ajax/GetParticipant_suboptions.php, modules/configuration/ajax/process.php, modules/configuration/ajax/updateProject.php, modules/configuration/ajax/updateSubproject.php, modules/data_team_helper/ajax/GetCandidates.php, modules/data_team_helper/ajax/GetInstruments.php, modules/datadict/ajax/UpdateDataDict.php, modules/document_repository/ajax/GetFile.php, modules/document_repository/ajax/addCategory.php, modules/document_repository/ajax/categoryEdit.php, modules/document_repository/ajax/documentDelete.php, modules/document_repository/ajax/documentEditUpload.php, modules/document_repository/ajax/getFileData.php, modules/help_editor/ajax/help.php, modules/imaging_uploader/ajax/read_log.php, modules/mri_violations/ajax/UpdateMRIProtocol.php, modules/server_processes_manager/ajax/ProcessStateRequestHandler.php, modules/survey_accounts/ajax/GetEmailContent.php, modules/training/ajax/getTabContent.php, modules/training/ajax/getTabs.php, modules/training/ajax/getTrainingDoc.php, modules/training/ajax/markQuiz.php
Add basic module permission checks for the ajax helper scripts. If the user doesn't have the correct permission a 403 Forbidden is returned
=> Ajax helpers permissions

htdocs/request_account/process_new_account.php, smarty/templates/process_new_account.tpl
=> Error message correction

modules/document_repository/ajax/documentEditUpload.php, modules/instrument_builder/js/react.instrument_builder.js, modules/instrument_builder/jsx/react.instrument_builder.js
When editing an element in the instrument builder, you couldn't save the element with the same question name. This pull request fixes this bug
=> Instrument Builder edit element

modules/training/test/TestPlan.md
This PR improves the test plan for the Training Module and addresses some minor Markdown formatting issues.
=> Improve test plan

modules/mri_violations/css/mri_violations.css, modules/mri_violations/js/mri_violations.js, modules/mri_violations/php/NDB_Menu_Filter_Form_mri_violations.class.inc, modules/mri_violations/php/NDB_Menu_Filter_Form_resolved_violations.class.inc, modules/mri_violations/php/NDB_Menu_Filter_mri_protocol_violations.class.inc, modules/mri_violations/templates/menu_mri_violations.tpl, modules/mri_violations/templates/menu_resolved_violations.tpl
fixing bugs raised in
https://redmine.cbrain.mcgill.ca/issues/8530
=> Mri viol fixup1510

modules/mri_violations/test/mri_violationsTest.php, tools/generate_project_statistics_csv.php, tools/redmine8083.php
Script to generate csv file with project statistics
At this point, must be put into tools file for every instance of Loris. Some designated user needs to run this file and manually copy and paste into Google Doc:
https://docs.google.com/spreadsheets/d/11MY91v0SrygAKI9bUQ7JXA5JGBXwJZPfmtZAmt23pKM/edit#gid=0
=> Redmine 8083 - Project Statistics (Updating Counts from Each Loris)

modules/user_accounts/php/NDB_Form_user_accounts.class.inc
This is a slight hack which works, but we should look more into the ```_isAdvCheckbox``` function in ```LorisForm``` post release
=> make modification in user account form to save the user permissions

php/libraries/NDB_BVL_Feedback.class.inc
This was occurring when you were viewing an instrument
=> fix bug where the feedback button wasnt showing

modules/user_accounts/php/NDB_Form_user_accounts.class.inc
=> User account code cleanup for consistency with recent permission fix/patch

modules/data_integrity_flag/js/data_integrity_flag.js
This bug was introduced with the upgrade to the data team helper :hankey:
=> fix bug where instruments werent populating

modules/configuration/templates/form_subproject.tpl
Adding a warning in the `New subproject` page : 
"To create timepoints for this new subproject, a visitLabel entry will have to be added in the config.xml file [...]"
=> New subproject - Warning

modules/configuration/js/project.js, modules/configuration/templates/form_project.tpl, modules/configuration/templates/form_subproject.tpl
The find function was looking for wrong class names.
=> Name and recruitementTarget have a value now

CONTRIBUTING.md
Gave a brief description about version branches to CONTRIBUTING.md
=> Added note about version branches

htdocs/request_account/process_new_account.php
- Check for quotes and HTML/PHP tags and show errors if some are found.
- Insert htmlspecialchars'ed values
=> Fix request account js inj

modules/brainbrowser/css/brainbrowser.css, modules/brainbrowser/templates/form_brainbrowser.tpl
Places the filter menu between the volumes. The volumes should form a 9 x 9 grid.
place the filter on the LHS of each volume instead of above
=> Overlay/Blend Option - need to put volumes together

tools/install.sh
Adds explanatory preamble for one new input (mysqluserhost) requested by Install script. 
Clarifing some of the wording in the script intro, especially around the choice to create a database.
Fixed a typo.
Added a mention to consult the wiki in GitHub for more details.
=> Update Install script text

modules/document_repository/ajax/documentEditUpload.php
this fixes the bug causing the doc repo to redirect you to a blank page
=> fix bug with redirect in doc repo

modules/mri_violations/php/NDB_Menu_Filter_Form_mri_violations.class.inc
remove resolved violations from unresolved query
=> remove resolved violations from unresolved query

php/libraries/Utility.class.inc
will replace getSubprojectsForProject in next release.
=> expanded getSubprojectList to filter for projectID

modules/imaging_browser/php/NDB_Menu_Filter_imaging_browser.class.inc
to show pass when at least 1 image has passed QC
=> makes sure QCStatus=1 will show as minimum

modules/mri_violations/php/NDB_Menu_Filter_Form_mri_violations.class.inc
add Visit label does not exist to problem drop down in selection filter
=> add Visit label does not exist to problem dropdown

modules/timepoint_list/templates/timepoint_list_controlpanel.tpl
This makes it so it doesn't seem like the links aren't working
=> remove text if the user isnt a DataEntryPerson

modules/mri_violations/php/NDB_Menu_Filter_Form_mri_violations.class.inc, modules/mri_violations/php/NDB_Menu_Filter_Form_resolved_violations.class.inc, modules/mri_violations/templates/menu_mri_violations.tpl, modules/mri_violations/templates/menu_resolved_violations.tpl
Fix the bug where the series id was populating to a single series id for all rows
=> Mri violations series 

php/libraries/Utility.class.inc
fix bug where you got a 500 error on submit query
=> fix bug where you got a 500 error on submit query

modules/mri_violations/php/NDB_Menu_Filter_mri_protocol_check_violations.class.inc
use a left join instead of a join to include null values
=> Fix no data in protocol check

README.CentOS6.md
Adding a few further details on how to name and populate the Apache config file for CentOS.
=> CentOS Readme - updating Apache notes

modules/configuration/js/SubprojectRelations.js, modules/configuration/jsx/SubprojectRelations.js, modules/configuration/php/NDB_Form_configuration.class.inc, modules/configuration/templates/form_project.tpl
This displays the list of related subprojects on the project configuration page in a React component.
=> Display subproject relations on the project config page

README.md
There seems to be some syntax issues in the current README.md file.
=> Fixing README syntax

htdocs/js/components/StaticDataTable.js, jsx/StaticDataTable.js
StaticDataTables are in fact interactive and can deal with pagination if
there's an overflow, but all data is passed in via React properties.
=> This adds a react component that can be used for rendering a data table

htdocs/bootstrap/css/custom-css.css, htdocs/js/components/DynamicDataTable.js, htdocs/js/components/StaticDataTable.js, jsx/DynamicDataTable.js, jsx/StaticDataTable.js
This adds a DynamicDataTable component to LORIS which is a wrapper
around the StaticDataTable. A DynamicDataTable loads its data from
an AJAX URL, rather than expecting it to be known at render time
and delegates the table rendering to StaticDataTable
=> React DynamicDataTable Component

modules/dicom_archive/test/TestPlan, modules/mri_violations/test/TestPlan.md, modules/statistics/php/NDB_Form_statistics.class.inc
This pull request was sent to the wrong branch.. luckily, it doesn't affect any code, so we can just merge it back into 16.04-dev
=> Merge Test Plan Back to 16.04-dev

.travis.yml, composer.json, composer.lock, modules/brainbrowser/ajax/getMincName.php, modules/help_editor/php/HelpFile.class.inc, modules/imaging_uploader/php/File_Decompress.class.inc, modules/imaging_uploader/php/NDB_Menu_Filter_imaging_uploader.class.inc, php/libraries/BVL_Feedback_Panel.class.inc, php/libraries/Log.class.inc, php/libraries/NDB_BVL_Battery.class.inc, php/libraries/NDB_BVL_Instrument.class.inc, php/libraries/NDB_BVL_Instrument_LINST.class.inc, php/libraries/NDB_BVL_Instrument_instrument_preview.class.inc, php/libraries/NDB_Caller.class.inc, php/libraries/NDB_Config.class.inc, php/libraries/NDB_Factory.class.inc, php/libraries/NDB_Reliability.class.inc, php/libraries/SinglePointLogin.class.inc, php/libraries/Smarty_hook.class.inc, php/libraries/Utility.class.inc, test/bootstrap.php, test/integrationtests/LorisIntegrationTest.class.inc, test/phpunit.xml, test/unittests/NDB_BVL_Instrument_LINST_ToJSON_Test.php, test/unittests/NDB_BVL_Instrument_ToJSON_Test.php
This combines the 3 types of test into one run of PHPUnit, so that code coverage reports can be generated and look at with codecov.io.
Note that quickform is no longer loaded by composer because it breaks in modern versions of PHP. Existing instruments depending on QuickForm will need to explicitly load it.
=> Code coverage report

modules/candidate_parameters/js/candidate_parameters.js
Disabled submit if suboption is not set
=> Reason is not required for setting participant status to inactive or incomplete

modules/imaging_browser/js/imagingbrowser.js
- Display a warning if no image is selected otherwise build the param list using .each() function.
=> Imaging browser validation

htdocs/.htaccess, htdocs/js/helpHandler.js, htdocs/js/loris.js, htdocs/main.php, modules/candidate_list/js/candidate_list.js, php/libraries/NDB_Page.class.inc, smarty/templates/main.tpl
This creates a base javascript file for LORIS to be shared between modules. This base file permits access to certain important configuration variables (such as baseURL) without resorting to smarty variables and allows javascript to check if a user has a permission similarly to how we can do so in PHP. 
As a result, the help javascript currently in main.tpl can be moved to a standard javascript file using the loris helper variable.
=> Removing javascript from main.tpl and create javascript base file

tools/install.sh
=> Updating user_uploads permission instruction

.travis.yml, modules/timepoint_flag/php/NDB_Form_timepoint_flag.class.inc, modules/timepoint_flag/php/NDB_Menu_Filter_timepoint_flag.class.inc, modules/timepoint_flag/php/TimePoint_Flag.class.inc, modules/timepoint_flag/test/timepoint_flagTest.php, modules/timepoint_flag/tools/derive_timepoint_flags.php, modules/timepoint_flag/tools/generate_exclusion_report.php
phpcs --standard=docs/LorisCS.xml modules/timepoint_flag
=> phpcs clean up of module timepoint_flag

php/libraries/NDB_BVL_InstrumentStatus.class.inc
This is a backport of @Jkat's conflict detector bugfix for 15.10.1
=> Backport of conflict detector bug

htdocs/main.php, php/libraries/NDB_Breadcrumb.class.inc, smarty/templates/main.tpl
This updates the breadcrumb links so that they should in theory
work with PrettyURLs enabled, instead of taking you to a 404
page
=> Fix breadcrumb links

modules/timepoint_list/php/TimePoint_List_ControlPanel.class.inc, modules/timepoint_list/templates/timepoint_list_controlpanel.tpl
Use the baseurl config to build the link for the buttons
And now comply to phpcs requirements
=> Timepoint list action button links

php/libraries/Database.class.inc
Database class no longer extends PEAR
=> Throwing exception for Database isError() calls

htdocs/js/components/FilterTable.js, jsx/FilterTable.js
The links in the FilterTable were trying to use "main.php", which doesn't exist relative to the directory of the module with PrettyURLs. This updates it to use the properly formatted URL.
(The JS looks like a bigger change than it is, because it was previously compiled with jsx and is now compiled with babel..)
=> Fixed filter links in FilterTables to use PrettyURL

modules/datadict/js/columnFormatter.js, modules/datadict/jsx/columnFormatter.js, modules/datadict/php/NDB_Menu_Filter_datadict.class.inc, modules/datadict/templates/menu_datadict.tpl
This updates the DataDict module to use the React DynamicData Table component.
=> Update DataDict module to use DynamicDataTable component

modules/bvl_feedback/js/react.behavioural_feedback_panel.js, modules/bvl_feedback/jsx/react.behavioural_feedback_panel.jsx, smarty/templates/bvl_feedback_panel.tpl
This fixes 2 issues with loading BVL feedback:
1. The URLs are updated to use PrettyURLs, so that they load correctly from any path and more importantly
2. It removes a file being loaded from https://fb.me on every request(!)
=> Fix loading issues with BVL Feedback

htdocs/js/components/FilterTable.js, jsx/FilterTable.js, modules/dicom_archive/js/columnFormatter.js, modules/dicom_archive/js/dicom_archive.js, modules/dicom_archive/jsx/columnFormatter.js, modules/dicom_archive/php/NDB_Menu_Filter_dicom_archive.class.inc, modules/dicom_archive/templates/menu_dicom_archive.tpl, php/libraries/NDB_Menu_Filter.class.inc
This upgrades the DICOM Archive Menu Filter to use our React Dynamic Data Table component.
=> Reactify DICOM Archive Menu Filter

php/libraries/Database.class.inc, test/integrationtests/LorisIntegrationTest.class.inc
Database execute function now handle insert and update prepared statements using and additional option argument.
Plus, phpcs...
=> fix LorisintegrationTest

php/libraries/Database.class.inc, test/integrationtests/LorisIntegrationTest.class.inc
One should use this function as follow:
1. Setup the permission using $this->setupPermissions(array('config'));
2. Refresh the page using $this->webDriver->navigate()->refresh();
3. $this->assertTrue($this->assertMenuItemPresent('Admin', 'Configuration'));
...or the opposite
1. Setup the permission using $this->setupPermissions(array(''));
2. Refresh the page using $this->webDriver->navigate()->refresh();
3. $this->assertFalse($this->assertMenuItemPresent('Admin', 'Configuration'));
=> Integration test helper functions

modules/new_profile/php/NDB_Form_new_profile.class.inc, php/libraries/NDB_BVL_Instrument.class.inc, php/libraries/Utility.class.inc
and moved _checkDate function from NDB_Form to Utility class
=> allow DCC to create profiles

modules/bvl_feedback/ajax/new_bvl_feedback.php, php/libraries/NDB_BVL_Feedback.class.inc, tools/fix_timepoint_date_problems.php
=> why are there so many problems with feedback

php/libraries/NDB_BVL_Feedback.class.inc
=> Fixing deleteThread typo in Feedback

modules/create_timepoint/templates/form_create_timepoint.tpl
=> Removing unused template code in Create Timepoint

SQL/0000-00-00-schema.sql, SQL/2016-02-16-CriticalConflictsResolverBugFix.sql
This is extremely critical and needs to be fixed asap. Data is potentially being truncated as we speak.
=> Critical Conflicts Resolver bug fix

htdocs/js/components/DynamicDataTable.js, htdocs/js/components/StaticDataTable.js, jsx/DynamicDataTable.js, jsx/StaticDataTable.js, modules/candidate_list/templates/menu_candidate_list.tpl
add the dynamic table functionality to the react tables
=> Static table improvements

modules/document_repository/ajax/addCategory.php, modules/document_repository/ajax/documentDelete.php, modules/document_repository/ajax/documentEditUpload.php
This was not passed to the template.
=> Fixing subject (study title) for Document Repository notifications

.travis.yml, test/config.xml, test/integration.sh, test/unittests.sh
Because life is complicated enough already.
=> Killing PHP web server at the end of integration.sh

modules/genomic_browser/php/NDB_Menu_Filter_snp_browser.class.inc, modules/genomic_browser/templates/menu_snp_browser.tpl, modules/genomic_browser/test/genomic_browserTest.php
- testGenomicBrowserDoespageLoad 
- testGenomicBrowserDoespageLoadPermissions
- testConfigurationMenuDisplayWithPermissions
- testGenomicBrowserCNVBrowserDoespageLoad
- testGenomicBrowserSNPBrowserDoespageLoad
=> Auto test genomic browser

modules/user_accounts/php/NDB_Form_user_accounts.class.inc, modules/user_accounts/templates/form_edit_user.tpl, modules/user_accounts/test/TestPlan
Upgrade of the user_account TestPlan
=> Added a test case for the new confirm email text field located on the add new user page

test/integrationtests/LorisIntegrationTest.class.inc
This should help resolve the Travis/Selenium error where random element can't be found.
=> Integration test click to load new page helper function

htdocs/js/helpHandler.js, htdocs/main.css
Remove br tags from the helpHandler and make changes to main.css instead, re: https://github.com/aces/Loris/pull/1565
=> Move spacing from HTML to CSS

modules/imaging_browser/test/imaging_browserTest.php, test/integrationtests/LorisIntegrationTest.class.inc
- Multiple tests written. Order of tests follows the Test Plan (more elaborate tests could be added)
- Multiple skipped tests (React elements do not seem to render on Travis, and popup windows unselectable, although these tests pass when launched locally) 
- Incomplete tests (Caveat link is not activated when set to True, 3D buttons not activated by onClick: awaiting redmine tasks)
=> Automated test: Imaging Browser

modules/statistics/php/NDB_Menu_statistics_mri_site.class.inc
=> Revert "Fixing sql query in the statistics"

SQL/0000-00-00-schema.sql, SQL/0000-00-03-ConfigTables.sql, SQL/2016-03-02-Add-Genomic-Files-GWAS-split-SNP.sql, modules/genomic_browser/css/genomic_browser.css, modules/genomic_browser/js/genomic_browser.js, modules/genomic_browser/php/GenomicFile.class.inc, modules/genomic_browser/php/NDB_Form_genomic_browser.class.inc, modules/genomic_browser/php/NDB_Menu_Filter_cnv_browser.class.inc, modules/genomic_browser/php/NDB_Menu_Filter_genomic_browser.class.inc, modules/genomic_browser/php/NDB_Menu_Filter_gwas_browser.class.inc, modules/genomic_browser/php/NDB_Menu_Filter_snp_browser.class.inc, modules/genomic_browser/templates/form_viewGenomicFile.tpl, modules/genomic_browser/templates/menu_cnv_browser.tpl, modules/genomic_browser/templates/menu_genomic_browser.tpl, modules/genomic_browser/templates/menu_gwas_browser.tpl, modules/genomic_browser/templates/menu_snp_browser.tpl, modules/genomic_browser/test/genomic_browserTest.php
Adding to the Genomic Browser module: 
- Genomic File support, including for PLINK-format files
-- includes GenomicFile class, ViewGenomicFile page, with CSS designed to match ImagingBrowser:ViewSession  
- new main Profiles tab: displays all available genomic data per subject
- GWAS tab to display analyzed Genome-Wide Association Study format data
=> Adding Genomic File support, Genomic Profile tab, GWAS support

SQL/0000-00-00-schema.sql, SQL/2016-03-02-Add-Genomic-Files-GWAS-split-SNP.sql
for genomic browser patch and table key
=> Patch improvement for schema

modules/next_stage/test/next_stageTest.php
=> removing the error_log(print_r)

htdocs/postdeploy.php
This was missed in PR https://github.com/aces/Loris/pull/1586
=> Updating SQL indexes for Heroku deployment

modules/conflict_resolver/test/conflict_resolverTest.php, test/integration.sh
Next is probably to look into resolving a conflict.
=> Conflict Resolver / Resolved Conflicts tests next draft

modules/imaging_uploader/php/NDB_Menu_Filter_imaging_uploader.class.inc
Due to a race condition the MRI pipeline was sometimes reporting that the tar archive was not copied to the MRI data incoming directory.
=> Fix for Redmine ticket #9593

modules/instrument_list/test/instrument_listTest.php
Might make sense to do more tests once Timepoints test has been updated.
=> Instrument List test next draft

modules/final_radiological_review/php/NDB_Form_final_radiological_review.class.inc
all credit goes to master gluneau
=> missing require once lines causing php500 error

modules/examiner/test/ExaminerTest.php
Not running properly on my sandbox so I'm running these through Travis for now while I debug.
=> Some initial tests for the examiner module

modules/genomic_browser/php/NDB_Menu_Filter_cnv_browser.class.inc, modules/genomic_browser/php/NDB_Menu_Filter_genomic_browser.class.inc, modules/genomic_browser/php/NDB_Menu_Filter_snp_browser.class.inc, modules/genomic_browser/templates/menu_cnv_browser.tpl, modules/genomic_browser/templates/menu_genomic_browser.tpl, modules/genomic_browser/templates/menu_snp_browser.tpl
Also works with CandID < 10000
=> Genomic module - timepoint_list links use pretty url

htdocs/js/components/DynamicDataTable.js, jsx/DynamicDataTable.js
An error div is now displayed and error message is send to the console.
=> Dynamic table handle ajax error

SQL/0000-00-00-schema.sql, SQL/2016-03-22-InstrumentListOrdering.sql, SQL/Archive/16.04/2016-01-20-InstrumentListOrdering.sql
Removing the patch in the archives and adding one in the current patch directory.
Changing schema also.
fix for https://github.com/aces/Loris/pull/1500
=> Rm9536 group order patch

SQL/0000-00-00-schema.sql, SQL/2016-01-19-EmptyQueries.sql, php/libraries/Database.class.inc
This can be discussed, but essentially I am more properly using "$this->affected" as designated and improving the visibility of empty database calls.
=> Improving database execution result handling

modules/training/test/TrainingTest.php
Not running properly on my sandbox so I'm running these through Travis for now while I debug.
=> Some initial tests for the training module

htdocs/main.php, modules/dashboard/ajax/get_recruitment_bar_data.php, modules/dashboard/ajax/get_recruitment_line_data.php, modules/dashboard/ajax/get_recruitment_pie_data.php, modules/dashboard/ajax/get_scan_line_data.php, modules/datadict/templates/menu_datadict.tpl, modules/datadict/test/datadictTest.php, php/libraries/NDB_Client.class.inc, php/libraries/SinglePointLogin.class.inc
This adds a test to ensure the "keyword" filter on the datadictionary module is working and returns the correct results.
=> DataDict Keyword Filter Test

modules/imaging_browser/js/columnFormatter.js, modules/imaging_browser/jsx/columnFormatter.js, modules/imaging_browser/php/NDB_Menu_Filter_imaging_browser.class.inc, modules/imaging_browser/templates/menu_imaging_browser.tpl, modules/imaging_browser/test/imaging_browserTest.php
This updates the imaging browser menu to use the React DynamicDataTable component. It's more responsive now.
=> Dynamic Data Table for Imaging Browser

modules/server_processes_manager/test/TestPlan
=> Basic test plan for the server processes manager module.

SQL/0000-00-00-schema.sql, SQL/2016-03-30-RemoveSelectedFromParameterType.sql, tools/CouchDB_MRI_Importer.php
Modified the query in the CouchDB import script to grep the Selected information from the files_qcstatus table instead of the parameter_file table
=> Fixed the CouchDB import script for the Selected information

php/libraries/LorisForm.class.inc
=> add getHTML argument to LorisForm functions

SQL/2015-11-26-MenuPrettyURLs.sql, SQL/2016-04-04-MenuPrettyURL-server_processes_manager.sql
spelling error in **server_processes_manager** item that should be **server_processeses_manager**
=> added the missing "es" to the server_process_manager item

README.Mac.md
Carbon copy of https://github.com/aces/Loris/pull/1170
=> adding Deepak4077 suggestion

modules/imaging_browser/php/Imaging_Session_ControlPanel.class.inc, modules/imaging_browser/test/imaging_browserTest.php, test/integrationtests/LorisIntegrationTest.class.inc
Added helper methods in LorisIntegrationTest and used them in imaging_browserTest in order to stop the random failing of these tests in Travis. Also contains a bug fix: the "Back" link on the imaging browser result page was broken.
=> Stabilization of imaging_browser tests that were randomly failing.

SQL/0000-00-00-schema.sql, SQL/2016-04-02-GenomicBrowser-FileUploader.sql, modules/genomic_browser/README.md, modules/genomic_browser/ajax/genomic_file_upload.php, modules/genomic_browser/ajax/get_genomic_file_type.php, modules/genomic_browser/js/FileUploadModal.js, modules/genomic_browser/js/genomic_file_uploader.js, modules/genomic_browser/jsx/FileUploadModal.jsx, modules/genomic_browser/php/NDB_Form_genomic_browser.class.inc, modules/genomic_browser/php/NDB_Menu_Filter_genomic_browser.class.inc, modules/genomic_browser/php/NDB_Menu_Filter_genomic_file_uploader.class.inc, modules/genomic_browser/templates/form_viewGenomicFile.tpl, modules/genomic_browser/templates/menu_cnv_browser.tpl, modules/genomic_browser/templates/menu_cpg_browser.tpl, modules/genomic_browser/templates/menu_genomic_browser.tpl, modules/genomic_browser/templates/menu_genomic_file_uploader.tpl, modules/genomic_browser/templates/menu_gwas_browser.tpl, modules/genomic_browser/templates/menu_snp_browser.tpl, php/libraries/Utility.class.inc
Altered Profile tab
new Files tab
1 modality upload
**Release notes**: This requires a genomic_uploder directory under the GenomicDataPath (Config) directory. this directory needs to be r+w for the apache user.
=> Genomic files tab

modules/instrument_builder/js/react.questions.js, modules/instrument_builder/jsx/react.questions.js
Some error message were not showing.
=> Fix instrument builder js

modules/genomic_browser/templates/menu_cnv_browser.tpl, modules/genomic_browser/templates/menu_cpg_browser.tpl, modules/genomic_browser/templates/menu_genomic_browser.tpl, modules/genomic_browser/templates/menu_gwas_browser.tpl, modules/genomic_browser/templates/menu_snp_browser.tpl, php/libraries/NDB_Menu_Filter.class.inc
- Removed the main.php from the constructed url.
- Added submenu to the filename.
- Templates adjusted to use baseurl
=> fix csvFile url

htdocs/bootstrap/css/custom-css.css
=> DynamicDataTable carousel control margin

modules/imaging_browser/php/NDB_Menu_Filter_imaging_browser.class.inc
The query for "New" data included QCStatus field. Now this is only showing New data as it is supposed to.
=> Removed QCStatus field from the "New" data query

modules/candidate_list/test/TestPlan
Open Profile Panel should only appear if not access_all_profiles permissions
https://redmine.cbrain.mcgill.ca/issues/9723
=> Update Candidate List Test Plan - Open Profile Panel

modules/dicom_archive/js/view_details_link.js, modules/dicom_archive/templates/form_viewDetails.tpl
This fix allows to view directly the proper violated scans in the MRI violations module
=> Fixed the links from DICOM archive to the MRI violations so that the filters are active.

modules/imaging_browser/test/imaging_browser_test_plan.md
=> two minor changes to the imaging browser test plan

htdocs/js/helpHandler.js, modules/help_editor/ajax/help.php
fixes the broken edit link and loading of help content
=> Help editor bugfix

modules/instrument_builder/js/react.questions.js, modules/instrument_builder/jsx/react.questions.js
Check for invalid date and End year < Start Year
Branch of https://github.com/aces/Loris/pull/1683
=> Rm9047 instrument builder end date before start date

modules/imaging_browser/php/NDB_Menu_Filter_imaging_browser.class.inc
Forgot to remove MRIQCStatus field from the query for "New or Pending" in previous pull request.
=> Removed MRIQCStatus from the New or Pending query in the imaging browser

modules/dataquery/css/dataquery.css, modules/dataquery/js/arrayintersect.js, modules/dataquery/js/react.app.js, modules/dataquery/js/react.filterBuilder.js, modules/dataquery/js/react.tabs.js, modules/dataquery/jsx/react.app.js, modules/dataquery/jsx/react.filterBuilder.js, modules/dataquery/jsx/react.tabs.js, php/libraries/CouchDB.class.inc
Apply the bug fixes discovered during first iteration of testing
=> Dqt bug fixes

modules/candidate_list/js/candidate_list.js, modules/candidate_list/js/columnFormatter.js
The links to the imaging browser page in the candidate list table for those candidates with an MRI scan are now missing. This adds them back.
=> Missing link to imaging browser page in candidate list table.

modules/candidate_list/js/candidate_list.js, modules/candidate_list/templates/menu_candidate_list.tpl
removed main.php from template and added baseurl
=> Open Profile Button Doesn't Work

modules/user_accounts/php/NDB_Form_user_accounts.class.inc
On the edit user and preferences page, when you enter a new password, it has to change (i.e. you cannot enter the current value).
=> When entering a new password, you cannot set it to its current value.

modules/genomic_browser/php/NDB_Menu_Filter_cnv_browser.class.inc, modules/genomic_browser/php/NDB_Menu_Filter_cpg_browser.class.inc, modules/genomic_browser/php/NDB_Menu_Filter_genomic_browser.class.inc, modules/genomic_browser/php/NDB_Menu_Filter_snp_browser.class.inc
- Properly formatting The DCCID string to a number
- Fixing Files filter in the profile tab
- Fixing the equal None value query for the File, SNV, SNP and CPG filters
=> Genomic Browser - fixing some filters

tools/install.sh
There was a reason someone wanted this
=> Adding CREATE TEMPORARY TABLES privilege

modules/genomic_browser/templates/menu_cnv_browser.tpl, modules/genomic_browser/templates/menu_snp_browser.tpl
Because for now, there is no association between genes and CNV/SNP
=> Do not show the Gene filter in the CNV et SNP tab

modules/brainbrowser/css/volume-viewer-demo.css, modules/brainbrowser/test/brainbrowser_test_plan.md
=> Brainbrowser test plan and css updated

php/libraries/NDB_BVL_Battery.class.inc, php/libraries/Utility.class.inc
Fixes bug reported here: https://redmine.cbrain.mcgill.ca/issues/9870
=> bugfix - check if column has any null values.

modules/instrument_list/php/Instrument_List_ControlPanel.class.inc
=> Missing baseurl variable assignation in the php file

modules/statistics/php/NDB_Menu_statistics_mri_site.class.inc
=> Initializing $counter variable in MRI statistics

modules/brainbrowser/templates/form_brainbrowser.tpl
This fixes the displaying of brainbrowser on the mobile device
=> fix UI bug for mobile

modules/timepoint_list/test/TestPlan
People should be able to view timepoint list (i.e. radiologists, who do not have data entry permission)
=> Redmine 10083 - Update Timepoint List Test Plan

docs/instruments/NDB_BVL_Instrument_radiology_review.class.inc, modules/final_radiological_review/php/NDB_Form_final_radiological_review.class.inc, modules/final_radiological_review/php/NDB_Menu_Filter_final_radiological_review.class.inc
** This pull request should be accompagnied by the database alter statement for radiology_review table 
ALTER TABLE radiology_review CHANGE abnormal_atypical_exculsionary abnormal_atypical_exclusionary enum('exclusionary','non_exclusionary','not_answered');
=> Fixed typo where exclusionary was spelled exculsionary

smarty/templates/feedback_mri_popup.tpl
=> Redmine 10115 - Remove Redundant Save Button in Imaging Browser Feedback MRI Popup

modules/mri_violations/js/mri_protocol_check_violations.js, modules/mri_violations/php/NDB_Menu_Filter_Form_resolved_violations.class.inc, modules/mri_violations/php/NDB_Menu_Filter_mri_protocol_check_violations.class.inc, modules/mri_violations/templates/menu_resolved_violations.tpl
Fix some styling bugs and add missing js dependencies in mri_violations module
=> Fix bugs in mri_violations

README.md
=> Getting rid of annoying quotes in the README

tools/install.sh
Someone wanted this, and now I feel like a slave
=> Adding project modules directory

modules/instrument_list/templates/instrument_list_controlpanel.tpl, modules/timepoint_list/templates/menu_timepoint_list.tpl, smarty/templates/instrumentstatus_controlpanel.tpl
This is not how we should do it to comply to pretty url but it will work for 16.0
=> fixing url

modules/datadict/ajax/UpdateDataDict.php, modules/dicom_archive/php/NDB_Form_dicom_archive.class.inc, modules/mri_violations/ajax/UpdateMRIProtocol.php
=> replace split with explode

htdocs/js/helpHandler.js
ALL CREDIT GOES TO @christinerogers
=> fixed permission name for non-superusers

htdocs/lost_password.php
User is now prompted to change PW since expiry has passed
=> Redmine 10071 - Lost Password Forces PW Change

php/libraries/NDB_Reliability.class.inc
=> added missing require once to NDB_Reliability

modules/document_repository/ajax/documentEditUpload.php
=> rename variable workaround fixes PHP bug

modules/imaging_browser/js/ImagePanel.js, modules/imaging_browser/jsx/ImagePanel.js
The React component was incorrectly using the variable
XMLReport twice instead of NrrdFile, causing both links
to break.
This fixes the NrrdFile variable to use the correct name.
=> Fix Nrrd Download Link

README.Mac.md
Update Mac Readme to say we no longer support mac and instructions are for yosemite
=> Update Mac README Disclaimer

modules/imaging_browser/templates/table_session_header.tpl
re-sending pull request 1808: https://github.com/aces/Loris/pull/1808
=> Easy grab of patient name; resending to 16p0 from 16p1

modules/imaging_uploader/templates/menu_imaging_uploader.tpl
https://github.com/aces/Loris/pull/1821
=> "Success" in Progress column in imaging_uploader: Resending pull request 1821 to 16p0

tools/data_dictionary_builder.php
This is something I needed to do to use the data_dictionnary_builder.php script
=> skip empty labels

htdocs/js/modules/dynamic_table.table.js
=> Fixed offsetheight JS error, added null check

htdocs/js/components/StaticDataTable.js, jsx/StaticDataTable.js
**[Redmine #10251](https://redmine.cbrain.mcgill.ca/issues/10251)** - Data Table Fixes
=> [Redmine #10251] Data Table Fixes

htdocs/js/jquery.fileupload.js, modules/instrument_builder/css/instrument_builder.css, modules/instrument_builder/js/instrument_builder.instrument.js, modules/instrument_builder/js/react.instrument_builder.js, modules/instrument_builder/js/react.questions.js, modules/instrument_builder/jsx/react.instrument_builder.js, modules/instrument_builder/jsx/react.questions.js, php/libraries/NDB_BVL_Instrument_LINST.class.inc
**[Redmine #9050](https://redmine.cbrain.mcgill.ca/issues/9050)** - Instrument Builder Date Format
---
**[Redmine #9776](https://redmine.cbrain.mcgill.ca/issues/9776)** - Rules for multiselect dropdown options
---
**[Redmine #9780](https://redmine.cbrain.mcgill.ca/issues/9780)** - Numeric Options updates
---
**[Redmine #9781](https://redmine.cbrain.mcgill.ca/issues/9781)** - Truncate file names in instrument uploader
=> Instrument Uploader Bug Fixes

htdocs/bootstrap/css/custom-css.css, htdocs/js/components/MultiSelectDropdown.js, jsx/MultiSelectDropdown.js, modules/dataquery/js/react.app.js, modules/dataquery/js/react.fieldselector.js, modules/dataquery/js/react.paginator.js, modules/dataquery/js/react.sidebar.js, modules/dataquery/js/react.tabs.js, modules/dataquery/jsx/react.app.js, modules/dataquery/jsx/react.fieldselector.js, modules/dataquery/php/NDB_Form_dataquery.class.inc
=> DQT Phase 2

README.md, htdocs/postdeploy.php, php/libraries/SinglePointLogin.class.inc
Fixing some php/apache bugs and hardcoding deployment branch
=> Update Heroku Deployment

php/libraries/SinglePointLogin.class.inc
Function to change the user's active flag in the user table. Returns true if flag changed to 'N'. Currently checked everytime a user logs in, could more efficiently be run as a cron job?
=> Disable users after inactivity

tools/excelDump.php
=> [Core] Dire typo in Excel Dump

README.md
=> [Core] Adding Travis CI Badge

CONTRIBUTING.md
Updating our CONTRIBUTING.md to reflect more accuracy.
=> [Core] Updating CONTRIBUTING.md

.travis.yml
=> [Core] Just making .travis.yml syntax more consistent 

htdocs/bootstrap/css/custom-css.css, htdocs/js/components/react.breadcrumb.js, jsx/react.breadcrumb.js
---
**Before:** 
---
**After:**
=> [Core] Fix jumping nav items in breadcrumbs

modules/document_repository/js/document_repository_helper.js, modules/document_repository/php/NDB_Menu_Filter_document_repository.class.inc
>Issue with document-repo tree:
When clicking on the expand link another category's sub-group expands.
**Zia**
**Note**: to see relevant changes **[click here](https://github.com/aces/Loris/pull/1988/commits/b7f792a5a29a402c8f3d7ae9aa6e01f18864d0a0)**
=> [Document Repository] Fix bug with category IDs

htdocs/bootstrap/css/custom-css.css, smarty/templates/login.tpl
=> [Core] Spacing in the header on login page

modules/user_accounts/php/NDB_Menu_Filter_user_accounts.class.inc
I don't think this is supposed to be a reference?
=> [User Accounts] Removing reference to list of sites variable

Dockerfile.MySQL, docs/Docker/LorisDB-EntryPoint.sh
=> Updating Docker MySQL

modules/candidate_list/templates/menu_candidate_list.tpl
=> [Candidate List] Rearrange EDC and Feedback Filters (Redmine 10573)

htdocs/js/components/DynamicDataTable.js, htdocs/js/components/StaticDataTable.js, jsx/DynamicDataTable.js, jsx/StaticDataTable.js
Phase 1 of front-end selection filter rollout
=> [Core] Data Table Filters

htdocs/js/components/Form.js, jsx/Form.js
```onChange``` listener allows the component to communicate any changes to its state to the parent class using a callback function
The same implementation is already used in dropdown element and textarea element
=> [Core] React textbox onChange listener

modules/dashboard/php/NDB_Form_dashboard.class.inc, modules/dashboard/test/TestPlan
missing AND in SQL statements
#2023
=> [Dashboard] Broken for non access_all_profiles permission (Redmine10601)

modules/brainbrowser/css/brainbrowser.css, modules/brainbrowser/css/volume-viewer-demo.css, modules/brainbrowser/js/brainbrowser.loris.js, modules/brainbrowser/php/NDB_Form_brainbrowser.class.inc, modules/brainbrowser/templates/form_brainbrowser.tpl
Before          | After
------------ | -------------
---
>Make Play button clickable and update associated javascript to make it an actual button instead of a styled checkbox. Also change text from Play to Pause dynamically depending on the current state of the playback.
---
---
>**NOTE:** In order to see file changes without changes in spacing/formatting **[click here](https://github.com/aces/Loris/pull/2028/files?w=1)**
=> [Brain Browser] Bug fixes and UI updates

modules/imaging_browser/js/columnFormatter.js, modules/imaging_browser/jsx/columnFormatter.js
Clicking on the "Links" leads to broken links because of missing "/"
native | selected | all types
=> [Imaging Browser] Broken links to scans (Redmine10599)

php/libraries/Database.class.inc
=> Database Wrapper: New escape function for column and table names

tools/install.sh
This fixes various issues throughout a LORIS instance (eg pretty URLs, API usage, etc)
=> [Core] Adding stuff about Apache mod rewrite

Vagrantfile
=> [Core] Vagrant Ubuntu 14.04

modules/dashboard/php/NDB_Form_dashboard.class.inc, modules/dashboard/test/TestPlan
…01) (#2043)
* missing AND
* Added test for 'Across all sites access candidate profiles'
=> Merge 16.0 into 16.1

modules/training/readme.md
Adding some documentation for the training module.
=> Training Module: Add readme

modules/dicom_archive/php/NDB_Menu_Filter_dicom_archive.class.inc
>**[Click Here](https://github.com/aces/Loris/pull/2067/files?w=1)** to see version without spacing changes
=> [DICOM Archive] Update JS dependency

modules/final_radiological_review/php/NDB_Form_final_radiological_review.class.inc, modules/final_radiological_review/php/NDB_Menu_Filter_final_radiological_review.class.inc, modules/help_editor/php/NDB_Form_help_editor.class.inc
Some minor bug fixes reported from the testing phase
=> 16.1 bug fixes

modules/imaging_uploader/test/TestPlan.md
=> [Imaging Uploader] Update Testplan

smarty/templates/instrumentstatus_controlpanel.tpl
If you click "Save" on an instrument, then try to change Administration, Validity, Data Entry, it takes you to the dashboard because the URL isn't being passed the test name
=> [Control Panel] Append test name to URLS (Redmine 10729)

modules/dataquery/js/arrayintersect.js
=> [data_query] fix bug in logic intersect/union

php/libraries/LorisForm.class.inc
- fix bug where form wasnt setting values if a filter wasn't defined
- make LorisForm errors populate like Quick_From's array renderer
=> Loris form improvements

modules/genomic_browser/ajax/get_genomic_file.php, modules/genomic_browser/templates/form_viewGenomicFile.tpl
Ajax script using GenomicFileID for Download
=> [Genomic Browser] Fix paths problems when using mri/jiv/get_file.php 

modules/genomic_browser/php/NDB_Menu_Filter_cnv_browser.class.inc, modules/genomic_browser/php/NDB_Menu_Filter_cpg_browser.class.inc, modules/genomic_browser/php/NDB_Menu_Filter_genomic_browser.class.inc, modules/genomic_browser/php/NDB_Menu_Filter_snp_browser.class.inc
There was a typo in the field names
And the 4 tabs are already ajaxmodule
=> [Genomic browser] fix SNP Observed Base & Reference Base filtering

htdocs/js/components/Form.js, jsx/Form.js, modules/instrument_builder/js/react.questions.js, modules/instrument_builder/jsx/react.questions.js
=> [Core] Make react form more robust

modules/media/js/uploadForm.js, modules/media/jsx/uploadForm.js, modules/media/part/file_upload.tpl, modules/media/php/NDB_Menu_Filter_media.class.inc
=> [Media] Filter bug fix 

tools/generate_tables_sql_and_testNames.php
=> Tools: fixed warning and deprecated function (Redmine 9054)

modules/imaging_uploader/php/NDB_Menu_Filter_imaging_uploader.class.inc, modules/imaging_uploader/test/TestPlan.md
Reverted the condition from if (preg_match) to if (!preg_match);
reference: https://github.com/aces/Loris/pull/2100/
=> Imaging Uploader: Reverted the condition for throwing the error when checking for the new naming convention: Redmine 10849

htdocs/js/components/DynamicDataTable.js, jsx/DynamicDataTable.js
>- For relevant chages, **[click here](https://github.com/aces/Loris/pull/2110/commits/9539c6ee32cf97b0c3769960154059a2b4fc8856#diff-7642a267b2813c88568b1911f1a58cc0)**
- For example usage, **[click here](https://github.com/aces/Loris/blob/17.0-dev/modules/media/jsx/uploadForm.js#L254)**
=> [Core] Update events in DynamicDataTable

modules/imaging_browser/php/NDB_Menu_Filter_imaging_browser.class.inc
>**Note**: The column and corresponding filter will only display, if projects are enabed in Loris configuration.
See **[Relevant Changes](https://github.com/aces/Loris/pull/2115/files?w=1)**
=> [Imaging Browser] Add 'Project' column (Redmine #9128)

smarty/templates/login.tpl
>For relevant changes, **[click here](https://github.com/aces/Loris/pull/2152/files?w=1)** 
Before | After
----- | ------
=> [Core] Responsive login page

htdocs/js/components/StaticDataTable.js, jsx/StaticDataTable.js
=> [Core] Update toCamelCase function

SQL/0000-00-00-schema.sql, SQL/Archive/17.0/2016-08-19-SelectedTrueFalse_fileqcstatusTable.sql, modules/imaging_browser/js/ImagePanel.js, modules/imaging_browser/jsx/ImagePanel.js, modules/imaging_browser/php/NDB_Form_imaging_browser.class.inc, modules/imaging_browser/templates/form_viewSession.tpl
Still not sure if: CouchDB_MRI_Importer.php is impacted?
=> Imaging Browser: Selected is True/False; Redmine 9029

php/libraries/TimePoint.class.inc
PSCID not used anywhere in the function.
=> [Core] Removing unused PSCID select in TimePoint class

modules/imaging_browser/php/NDB_Form_imaging_browser.class.inc, modules/imaging_browser/php/NDB_Menu_Filter_imaging_browser.class.inc
>For relevant changes **[click here](https://github.com/aces/Loris/pull/2153/files?w=1)**
=> [Imaging Browser] Add getCSSDependencies()

modules/final_radiological_review/php/NDB_Menu_Filter_final_radiological_review.class.inc, modules/final_radiological_review/templates/menu_final_radiological_review.tpl
Needed to indicate on the radiological review landing page if T1 image has been inserted (as otherwise, it takes the radiologist 3+ clicks to find out if images for a given candidate have been inserted or not)
=> Final radiological Review: Added a column as to whether a T1 scan was inserted: Redmine 9560

modules/brainbrowser/css/brainbrowser.css, modules/brainbrowser/js/brainbrowser.loris.js
=> [Brainbrowser] Fix panel auto-resizing

SQL/0000-00-00-schema.sql, SQL/Archive/17.0/2016-08-18-RemovingTitleFromAcknowledgements.sql, modules/acknowledgements/php/NDB_Menu_Filter_Form_acknowledgements.class.inc, modules/acknowledgements/templates/menu_acknowledgements.tpl
We have both Full Name and Citation Name so this column is not really necessary.
=> [Acknowledgements] Dropping unused 'title' column

htdocs/js/components/StaticDataTable.js, jsx/StaticDataTable.js
>Note: the selection is saved in localstorage on per module basis. Meaning that changing the selection will save it for all data tables in the module.
=> [Core] Save page max row per page selection

modules/instrument_builder/js/react.questions.js, modules/instrument_builder/jsx/react.questions.js
=> [Instrument Builder] Add rules to Question Name

modules/timepoint_list/php/NDB_Menu_timepoint_list.class.inc, modules/timepoint_list/templates/menu_timepoint_list.tpl, modules/timepoint_list/test/timepoint_listTest.php
Added a Site column to the timepoint list; this will become useful if some timepoints/visits took place at other sites...
=> Time point list: Added a Site column to the table; Redmine 10938

modules/dicom_archive/js/columnFormatter.js, modules/dicom_archive/js/dicom_archive.js, modules/dicom_archive/jsx/columnFormatter.js, modules/dicom_archive/jsx/dicom_archive.js, modules/dicom_archive/php/dicom_archive.class.inc
>**Note**: a bug was found in filtering function, so **[this PR](https://github.com/aces/Loris/pull/2159)** should be applied before testing SeriesUID
=> [DICOM Archive] Add SeriesUID filter (Redmine #8846)

modules/instrument_builder/php/NDB_Form_instrument_builder.class.inc
=> [Instrument Buider] Add getCSSDependencies()

Gruntfile.js, htdocs/js/components/Tabs.js, jsx/Tabs.js, modules/instrument_builder/js/react.instrument_builder.js, modules/instrument_builder/jsx/react.instrument_builder.js, modules/instrument_builder/php/NDB_Form_instrument_builder.class.inc
This adds a generic React <Tabs> component to be used throughout LORIS.
The instrument_builder module is updated as an example of how to use it.
This is a product of the September 1st Mob Programming session.
=> [Core/Instrument Builder] React Tabs component

php/libraries/LorisForm.class.inc, smarty/templates/main.tpl
=> [Core] UI update to jQuery datepicker

SQL/Archive/17.0/2016-09-18-Config_add_content_security, SQL/Archive/17.0/2016-09-18-Config_add_content_security.sql, php/libraries/NDB_Client.class.inc
@taracampbell you can try this with the vimeo addon we have in NDB_Client in project/libraries
@driusan example: 
```frame-src 'self' https://player.vimeo.com/;```
=> [Config] add Content-Security policy field in DB

modules/media/js/editForm.js, modules/media/jsx/editForm.js
=> [Media] Update back URL

.travis.yml, modules/create_timepoint/php/NDB_Form_create_timepoint.class.inc, modules/create_timepoint/php/create_timepoint.class.inc, modules/create_timepoint/php/module.class.inc, modules/create_timepoint/test/create_timepointTest.php, php/libraries/Module.class.inc
=> [Create Timepoint] Convert to new module structure

Gruntfile.js, modules/reliability/js/columnFormatter.js, modules/reliability/jsx/columnFormatter.js, modules/reliability/php/NDB_Menu_Filter_reliability.class.inc, modules/reliability/templates/menu_reliability.tpl, modules/reliability/test/reliabilityTest.php
=> [Reliability] Update data table to use React

modules/acknowledgements/templates/menu_acknowledgements.tpl
=> [Acknowledgements] fail copy paste

modules/configuration/ajax/updateProject.php, modules/configuration/ajax/updateSubproject.php, modules/configuration/js/project.js, modules/configuration/js/subproject.js
Provides a new warning and does not allow duplicate names or titles.
=> [Configuration] add error message if adding duplicate (sub)Project Name (Redmine 9622)

modules/genomic_browser/ajax/genomic_file_upload.php, modules/genomic_browser/js/FileUploadModal.js, modules/genomic_browser/jsx/FileUploadModal.js
This is almost identical to https://github.com/aces/Loris/pull/2069 but based on 17.0-dev branch.
It is a contribution of @manubati that I have rebased
The log that were sent to the console are now shown in a progress bar.
=> [Genomic Browser] Uploader progress bar

modules/survey_accounts/templates/menu_survey_accounts.tpl
=> [Survey] fix add survey button

Dockerfile, README.CentOS6.md, README.Mac.md, composer.json, docs/config/apache2-site, modules/bvl_feedback/ajax/react_get_bvl_threads.php, modules/timepoint_flag/php/TimePoint_Flag.class.inc, tools/generic_includes.php, tools/install.sh
- Dockerfile tries to install it
- LorisCS.xml
And other places...
Full list: 
https://github.com/aces/Loris/search?utf8=%E2%9C%93&q=PEAR
=> [CORE] Pear cleanup (Redmine9973)

SQL/0000-00-00-schema.sql, SQL/Archive/17.0/2016-09-13-AddScannerIDInFiles.sql
Related to:
https://github.com/aces/Loris/pull/2189
=> Set ScannerID default to NULL in the files table: Redmine 10939

modules/statistics/php/NDB_Form_statistics.class.inc, modules/statistics/php/NDB_Menu_statistics_dd_site.class.inc, modules/statistics/php/NDB_Menu_statistics_mri_site.class.inc, modules/statistics/php/NDB_Menu_statistics_site.class.inc, modules/statistics/templates/form_stats_behavioural.tpl
@taracampbell 
- make sure site names are showing in big tables 
- behavioural tab "please click here" links work
@gluneau 
- make sure css loads on everypage
- make sure the behavioural tab works as it should (specially please click here links)
=> [statistics] using psc name when pscarea is null

modules/media/php/NDB_Form_media.class.inc, modules/media/php/NDB_Menu_Filter_media.class.inc
>Necessary for integration tests to pass
=> [Media] Remove unused requires

modules/survey_accounts/templates/menu_survey_accounts.tpl
Survey module selection filter chevron arrow works now (Redmine 10804)
=> [Survey] missing baseurl reference 

.travis.yml, modules/candidate_parameters/ajax/formHandler.php, modules/candidate_parameters/js/candidateInfo.js, modules/candidate_parameters/js/consentStatus.js, modules/candidate_parameters/jsx/candidateInfo.js, modules/candidate_parameters/jsx/consentStatus.js, modules/candidate_parameters/jsx/familyInfo.js
=> [Candidate Parameters] Run ESLint + Add to Travis

CONTRIBUTING.md
Adding more details about our branches for contributing.
=> [Core] Branches for contributing

modules/issue_tracker/js/columnFormatter.js, modules/issue_tracker/js/editIssue.js, modules/issue_tracker/jsx/columnFormatter.js, modules/issue_tracker/jsx/editIssue.js
=> [Issues Module] ESLint

modules/dicom_archive/js/columnFormatter.js, modules/dicom_archive/jsx/columnFormatter.js, modules/dicom_archive/php/dicom_archive.class.inc
=> [DICOM Archive] Fix broken links

PULL_REQUEST_TEMPLATE.md
=> [Core] First pass at Pull Request template

.eslintrc.json, .travis.yml, htdocs/js/components/DynamicDataTable.js, htdocs/js/components/FilterTable.js, htdocs/js/components/Form.js, htdocs/js/components/Markdown.js, htdocs/js/components/MultiSelectDropdown.js, htdocs/js/components/PaginationLinks.js, htdocs/js/components/StaticDataTable.js, htdocs/js/components/Tabs.js, htdocs/js/components/react.breadcrumb.js, jsx/FilterTable.js, jsx/Markdown.js, jsx/MultiSelectDropdown.js, jsx/StaticDataTable.js, jsx/react.breadcrumb.js
>Note: All changes in this PR are made only to pass ESLint
=> [Core] Lint all core JSX

modules/genomic_browser/ajax/get_genomic_file_type.php, modules/genomic_browser/js/FileUploadModal.js, modules/genomic_browser/jsx/FileUploadModal.js
=> [Genomic Browser] Run ESLint

modules/imaging_browser/js/ImagePanel.js, modules/imaging_browser/js/columnFormatter.js, modules/imaging_browser/jsx/ImagePanel.js, modules/imaging_browser/jsx/columnFormatter.js
=> [Imaging Browser] ESLint

modules/configuration/js/SubprojectRelations.js, modules/configuration/jsx/SubprojectRelations.js
=> [Configuration] Lint

.babelrc, Gruntfile.js
>Note: this should be merge after all other linting modules have been merged #2259 
#2263 #2265 #2269 #2270 #2271 #2272
=> [Core] Update Babel + Grunt

.travis.yml
=> [Core] Update Travis to lint all Loris JS

SQL/0000-00-00-schema.sql, SQL/Archive/17.0/2016-09-20-OrderOfAcquisition
Related to: https://github.com/aces/Loris-MRI/pull/160
=> Imaging Preprocessing: Order the acquisitions per modality based on series number: Redmine 10959 

.eslintrc.json, htdocs/js/components/DynamicDataTable.js, jsx/DynamicDataTable.js, modules/genomic_browser/js/FileUploadModal.js, modules/genomic_browser/jsx/FileUploadModal.js
>Note: `console.info`, `console.warn`, `console.error` are still allowed but should only be used when appropriate
=> [Core] Add rule to check for forgotten console.logs

SQL/Archive/17.0/2016-10-17_Default_date_value.sql
This is a missing patch for https://github.com/aces/Loris/pull/2222
=> [Schema] Defaut date values

modules/dicom_archive/php/dicom_archive.class.inc
Some of [these changes](https://github.com/aces/Loris/pull/2160/commits/a0f0fd960c756b72dae3446c53769622e7e64921) got lost during a big dicom rebase. 
Bringing them back / addressing Redmine 11221
=> [DICOM Archive] Add SeriesUID hidden column

php/libraries/NDB_Client.class.inc
@driusan & @alisterdev I could never reproduce it so maybe you guys can test that one
=> [Configuration] Added if statement for empty result case

modules/acknowledgements/php/NDB_Menu_Filter_Form_acknowledgements.class.inc
basicDateElement return strings and not arrays. (It might be a new behaviour)
This make sur that the date are not 0000-00-00 for NO_ZERO_DATE sql mode
=> [Acknowledgements] compatibility with sql NO_ZERO_DATE mode and LorisForm

modules/dicom_archive/js/dicom_archive.js, modules/dicom_archive/jsx/dicom_archive.js
=> [Dicom Archive] make the PatienID filter match toCamelCase result in StaticDataTable

modules/user_accounts/php/NDB_Form_user_accounts.class.inc
The password_group element doesn't exist in my preferences
=> Preference same password

modules/candidate_parameters/templates/form_candidate_parameters.tpl
RM#11236
The component is created only if useConsent setting is true.
=> [Candidate Parameters] conditionnal component

modules/final_radiological_review/php/NDB_Menu_Filter_final_radiological_review.class.inc
Fixes a bug where Exclusionary Status filters were not being applied properly.
See Redmine #11228
=> [Final Radiological Review] Add r.Final_Exclusionary to EqualityFilters

php/exceptions/LorisModuleMissingException.class.inc, php/libraries/Module.class.inc, php/libraries/NDB_Caller.class.inc
=> [Core] Implement the hasAccess function for new Module type modules

modules/candidate_parameters/js/candidateInfo.js, modules/candidate_parameters/js/consentStatus.js, modules/candidate_parameters/js/familyInfo.js, modules/candidate_parameters/js/participantStatus.js, modules/candidate_parameters/js/probandInfo.js, modules/candidate_parameters/jsx/candidateInfo.js, modules/candidate_parameters/jsx/consentStatus.js, modules/candidate_parameters/jsx/familyInfo.js, modules/candidate_parameters/jsx/participantStatus.js, modules/candidate_parameters/jsx/probandInfo.js
Success/error messages now disappear after 5 seconds
=> [Candidate Params] Alert Messages Disappear (Redmine11234)

modules/mri_violations/php/NDB_Menu_Filter_Form_mri_violations.class.inc
https://redmine.cbrain.mcgill.ca/issues/11198
https://redmine.cbrain.mcgill.ca/issues/11199
=> [MRI Violated] bug -11198 -11199 

modules/dataquery/css/dataquery.css, modules/dataquery/js/react.app.js, modules/dataquery/js/react.tabs.js, modules/dataquery/jsx/react.app.js, modules/dataquery/jsx/react.tabs.js
Adding a loading page she the DQT is loading data to indicate to users that its currently working hard to make their lives easier
=> add functionality to notify users that data is loading

modules/dashboard/templates/form_dashboard.tpl
Adds disclaimer/label on the Dashboard mentioning that the current numbers include ineligible/excluded/consent withdrawn.
See Redmine #11207
=> Add disclaimer regarding candidate status to dashboard

SQL/0000-00-02-Menus.sql, SQL/Archive/17.0/2016-10-19-LorisMenuPermissions_add_media.sql
=> Add permissions for Media to LorisMenuPermissions

modules/instrument_builder/js/react.instrument_builder.js, modules/instrument_builder/jsx/react.instrument_builder.js
=> [Instrument Builder] Allow question name to be reused when deleted

tools/delete_candidate.php
https://redmine.cbrain.mcgill.ca/issues/11259
=> [Tools / delete_candidate.php] Bug #11259 

modules/bvl_feedback/js/react.behavioural_feedback_panel.js, modules/bvl_feedback/jsx/react.behavioural_feedback_panel.js
=> [BVL Feedback] Add missing column

modules/data_team_helper/js/behavioural_qc_module.js, modules/data_team_helper/jsx/behavioural_qc_module.js
https://redmine.cbrain.mcgill.ca/issues/11231
=> [Data team helper] Bug-11231 - link broken

modules/server_processes_manager/test/TestPlan
In relation to:
https://github.com/aces/Loris/pull/2252
=> Server process manager: Updated test plan

modules/brainbrowser/test/brainbrowser_test_plan.md
https://redmine.cbrain.mcgill.ca/issues/11184
=> Updated the test plan to clarify the "Reset view" function.

modules/datadict/test/TestPlan
See Redmine #11181
Since moving to React tables the expected behaviour is to be able to sort the 'No.' column. This updates the datadict test plan to reflect that.
=> [datadict] Update datadict test plan

modules/candidate_parameters/test/TestPlan.md
=> testplan clarification

modules/help_editor/ajax/help.php
help dropdown no longer contains weird characters
=> Help Dropdown Character Encoding Fix (Redmine #11182)

modules/candidate_parameters/js/candidateInfo.js, modules/candidate_parameters/jsx/candidateInfo.js, modules/candidate_parameters/test/TestPlan.md
Update test plan in case there is no "Other" field in the caveat_options table
=> [Candidate Params] Update Test Plan "Other" (Redmine11238)

modules/user_accounts/php/NDB_Form_user_accounts.class.inc, php/libraries/User.class.inc
Now uses any site's pending/radiologist fields to populate default values
=> [user_accounts] Changed logic of get defaults

modules/candidate_parameters/ajax/formHandler.php, modules/candidate_parameters/js/candidateInfo.js, modules/candidate_parameters/jsx/candidateInfo.js
https://redmine.cbrain.mcgill.ca/issues/11237#change-40607
It's probably not the best way to do it, but we always need to calculate the key of the "Other" field. 
This does 2 things:
=> [Candidate Parameters] Handle nulls in other field

modules/user_accounts/php/NDB_Form_user_accounts.class.inc
Now the form stays editable in all cases.
=> Fixed a bug that would cause the user account form to become non-editable after a new user is created or a modification is done to a user account.

modules/imaging_browser/php/NDB_Menu_Filter_imaging_browser.class.inc
Relates to https://github.com/aces/Loris-MRI/pull/166#issuecomment-255792000
=> add AND s.Active = 'Y'

modules/dicom_archive/test/TestPlan
https://redmine.cbrain.mcgill.ca/issues/11215
=> [Dicom_Archive] update TestPlan -- bug 11215

SQL/Release_patches/16.1_To_17.0_upgrade.sql
Release patch for upgrading from the most recent minor release (16.1) to Loris 17.0.
Note that projects upgrading from 16.0 should first apply the 16.0 to 16.1 upgrade patch.
[CR]
=> New 16.1-17.0 sql patch

modules/candidate_parameters/ajax/getData.php
Fix for when there's only a single consent
=> [Candidate Params] fix single consent error

SQL/Archive/17.0/2016-06-29-adding_filetypes_to_new_table.sql
Related to https://github.com/aces/Loris/pull/2359
=> set blank file type to the file extension

modules/data_team_helper/php/NDB_Form_data_team_helper.class.inc
https://redmine.cbrain.mcgill.ca/issues/11232
=> Data Team Helper - Filters out `Instrument : null` rows (Redmine 11232)

modules/media/test/TestPlan.md
Indicate clearly that `Site` can't be edited 
https://redmine.cbrain.mcgill.ca/issues/11341
=> [Media] Update TestPlan

modules/candidate_parameters/test/TestPlan.md
Formatting + more in depth instructions + adding case when only one consent in config
=> [Candidate Params] Update Test Plan

CONTRIBUTING.md
* removing Pear mention
* adding mention of Coding standards 
* adding mention of new Pull request template Readme. 
* updating version numbers for now
=> Further tweaks to Contributing guidelines for 17 release

README.CentOS6.md
* not including new web-based install process
=> CentOS Readme Updates

README.md
main Readme updates for 17.0  
Dependencies currently underspecified - no specific packages mentioned
=> some Readme updates for 17.0 

SQL/Release_patches/16.1_To_17.0_upgrade.sql
release patch was missing a space in 2 places - lines were not properly commented out
=> release patch : add missing spaces in 2 comment lines

modules/data_integrity_flag/js/data_integrity_flag_helper.js, modules/data_integrity_flag/php/NDB_Form_data_integrity_flag.class.inc, modules/data_integrity_flag/templates/form_data_integrity_flag.tpl, php/libraries/Database.class.inc, php/libraries/Utility.class.inc
=> [Data Integrity Flag] - Unsupported element bugfix

modules/candidate_parameters/test/TestPlan.md
Should be able to access all candidate parameter profiles with AAP
=> [Cand params] Test Plan Update (access all profiles)

php/libraries/LorisForm.class.inc, php/libraries/NDB_BVL_Instrument.class.inc, smarty/templates/time_element.tpl, tools/lorisform_parser.php
=> [lorisparser] - time element

modules/statistics/php/NDB_Form_statistics.class.inc
=> [Stats] added c.Active to query

tools/data_dictionary_builder.php
Only add ParameterTypeID key if array_key_exists($Name, $parameter_types) is true.
=> [Data dictionary builder] Not inserting empty value in autoincrement field

php/libraries/NDB_BVL_Instrument.class.inc
=> Instruments working with MySQL 5.7 strict mode

modules/candidate_parameters/js/probandInfo.js, modules/candidate_parameters/jsx/probandInfo.js
Fixes a bug where unedited fields were being submitted as null
Redmine #11486
=> [Candidate Parameters] Initialize formData on page load

php/libraries/LorisForm.class.inc
Fix regex to work with database time strings and set time to null if not set
=> Loris form time html

SQL/0000-00-00-schema.sql
=> [Schema] add 'drop table'

modules/bvl_feedback/ajax/bvl_panel_ajax.php, modules/bvl_feedback/ajax/react_get_bvl_threads.php
Client is already initialized by AjaxHelper.
=> [bvl_feedback] removing redundant lines

modules/media/ajax/FileUpload.php, modules/media/js/editForm.js, modules/media/jsx/editForm.js
=> [Media] MySQL 5.7 date bug

htdocs/js/components/Form.js, jsx/Form.js
>**Note about changes**: 
This update is the first step in converting Loris filter forms to use react (i.e dicom_archive style)
>**Note for Manual Testing:**
Make sure that Media, DICOM Archive, Issue Tracker and Candidate Parameters are all rendered as before
=> [Core] Update react form 

php/libraries/NDB_BVL_Instrument.class.inc
=> [Instrument] We hate empty strings

smarty/templates/instrument_html.tpl
This fixes formatting of groups in instruments
=> Instrument groups

PULL_REQUEST_TEMPLATE.md
[comment]: # ( 
Make sure you send your pull request to the right VERSIONNUMBER-dev branch. It's still possible to change it afterwards and if you are not sure which branch to send to, please consult the CONTRIBUTING.md. 
) 
[comment]: # (
Please also make sure to indicate in the pull request title the general domain in which your pull request pertains to. For example, "[Core] Adding CentOS support to Install Script" or "[Document Repository] Adding functionality to group files under Categories". 
)
[comment]: # ( 
Also set appropriate Labels and Milestones as you see fit. Assignee is usually set to whoever may be the right person to test your pull request. 
)
Above this text there is a hidden comment !! ITS LIKE MAGIC
=> GitHub template comment sections

modules/dataquery/css/dataquery.css, modules/dataquery/js/arrayintersect.js, modules/dataquery/js/react.app.js, modules/dataquery/js/react.filterBuilder.js, modules/dataquery/js/react.tabs.js, modules/dataquery/js/workers/savezip.js, modules/dataquery/jsx/react.app.js, modules/dataquery/jsx/react.filterBuilder.js, modules/dataquery/jsx/react.tabs.js, modules/dataquery/php/NDB_Form_dataquery.class.inc
Currently the filters in the DQT are very buggy. This pull request fixes it 
- Fixes bug where adding filters returned no data.
- Add user feedback that data is loading.
- Fix bug with downloading files
=> Dataquery Bugfixes

modules/media/ajax/FileUpload.php, modules/media/js/uploadForm.js, modules/media/jsx/uploadForm.js
=> [Media] Prevent duplicate file names in DB

modules/dashboard/css/dashboard.css, modules/dashboard/php/NDB_Form_dashboard.class.inc, modules/dashboard/templates/form_dashboard.tpl, modules/dashboard/test/TestPlan.md
Adds behavioural feedback notifications to dashboard
=> [Dashboard] add behavioural feedback

modules/statistics/templates/form_stats_behavioural.tpl
[comment]: # (
)
[comment]: # (
)
[comment]: # (
)
=> [Statistics] Replaced ID by longname

modules/dataquery/ajax/retrieveCategoryDocs.php, modules/dataquery/js/react.app.js, modules/dataquery/jsx/react.app.js, modules/dataquery/php/NDB_Form_dataquery.class.inc
The DQT would request the same data multiple times in the same request causing duplicate data to be passed back in the response
=> DQT Query Bug Fix

modules/media/php/NDB_Menu_Filter_media.class.inc
=> [Media] Only show data from user's site by default

.travis.yml
[comment]: # (
)
[comment]: # (
)
[comment]: # (
)
=> fix travis.yml - test script runs twice

modules/media/js/editForm.js, modules/media/js/uploadForm.js, modules/media/jsx/editForm.js, modules/media/jsx/uploadForm.js
A step toward standardising our components to use ES6 class syntax (like DicomArchive).
=> [Media] Use ES6 class syntax

htdocs/js/jquery.dynamictable.js, package.json, test/run-js-linter.sh
=> [Core] Get rid of JSLint dependency

htdocs/js/components/Tabs.js, jsx/Tabs.js, modules/instrument_builder/js/react.instrument_builder.js, modules/instrument_builder/jsx/react.instrument_builder.js
---
**PS: This is my 💯  pull request! Yay me! 🏅**
=> [Core] Refactor Tabs component

.eslintignore, Gruntfile.js, modules/data_team_helper/js/behavioural_qc_module.js, modules/data_team_helper/jsx/behavioural_qc_module.js, modules/data_team_helper/php/NDB_Form_data_team_helper.class.inc, modules/data_team_helper/templates/form_data_team_helper.tpl
=> [Data Team Helper] ESLint

modules/conflict_resolver/test/TestPlan.md
Change to md and update part about pagination since reactification
=> [Conflict Resolver] update test plan

htdocs/request_account/thank-you.html
Fixed bootstrap path and did a bit of styling
Before:
After:
=> [htdocs] Thank you page

modules/configuration/test/ConfigurationTest.php, modules/configuration/test/TestPlan.md, test/integrationtests/LorisIntegrationTest.class.inc
=> [Configuration] test

.eslintignore, Gruntfile.js, modules/bvl_feedback/ajax/new_bvl_feedback.php, modules/bvl_feedback/js/react.behavioural_feedback_panel.js, modules/bvl_feedback/jsx/react.behavioural_feedback_panel.js, php/libraries/NDB_BVL_Feedback.class.inc, smarty/templates/bvl_feedback_panel.tpl
=> [BVL Feedback] ESLint 

tools/score_instrument.php
Making prepared statements and added single quotes
=> [Tools] Prepared statements and added single quotes

modules/statistics/php/NDB_Form_statistics.class.inc, modules/statistics/php/NDB_Menu_statistics_dd_site.class.inc, modules/statistics/php/NDB_Menu_statistics_site.class.inc
[comment]: # (
)
[comment]: # (
)
[comment]: # (
)
Added CenterID restriction to all queries to avoid counting DCC candidates
=> [STATS] Added centerid <> 1 to all queries

modules/next_stage/templates/form_next_stage.tpl
[comment]: # (
)
[comment]: # (
)
[comment]: # (
)
Removed confusing message at the bottom of the next_stage page as it does not apply to all projects using Loris. To be included in MOP …
=> [next_stage] Confusing message

htdocs/js/components/ProgressBar.js, jsx/ProgressBar.js, php/libraries/NDB_Page.class.inc
- Reusable React ProgressBar component
- Accepts a value showing the loaded percentage
**Example**
`<ProgressBar value="90" />` renders:
=> [Core] React progress bar

modules/candidate_parameters/ajax/getData.php
=> [Candidate Parameters] make select statement use join instead of subselect

php/libraries/LorisForm.class.inc, smarty/templates/toHTML_form.tpl
This adds the toHTML function to LorisForm along with the ability to add link elements
=> LorisForm add toHTML function

htdocs/api/v0.0.2/Candidates.php
=> [API] Candidate fix post data

php/libraries/NDB_BVL_Battery.class.inc
The @return comment was not accurate.
=> [Core] Fixing return comment on addInstrument function

modules/imaging_browser/php/Imaging_Session_ControlPanel.class.inc, modules/imaging_browser/templates/imaging_session_controlpanel.tpl
Rebasing of https://github.com/aces/Loris/pull/2506 did not work, so closing it and sending this to the proper branch instead.
=> Imaging Browser: Make the radiology review and mri parameter form links show if tables exist in the database: Redmine 11738

htdocs/api/v0.0.2/Login.php
=> [API] Login expect json object

php/libraries/SinglePointLogin.class.inc
=> [Core] Adding alias in sql query in SinglePointLogin

php/libraries/NDB_Config.class.inc
[comment]: # (
)
[comment]: # (
)
[comment]: # (
)
Fixed Directory path of Config.xml in NDB_Config
=> [Core] made config.xml path absolute and fixed directory

modules/create_timepoint/php/create_timepoint.class.inc
[comment]: # (
)
[comment]: # (
)
[comment]: # (
)
=> [Create Timepoint] Added deprecation message to error log for user input visit label

htdocs/js/components/Form.js, jsx/Form.js, modules/media/js/editForm.js, modules/media/js/uploadForm.js, modules/media/jsx/editForm.js, modules/media/jsx/uploadForm.js
=> [Core] React form updates

php/libraries/NDB_Config.class.inc
=> Revert "[Core] made config.xml path absolute and fixed directory"

modules/dashboard/templates/form_dashboard.tpl, modules/dashboard/test/DashboardTest.php, modules/dashboard/test/TestPlan.md
=> [Dashboard] Automation Test - rebase

modules/issue_tracker/test/Issue_TrackerTest.php, test/phpunit.xml
=> [Issue Tracker] test

tools/generic_includes.php
[comment]: # (
)
[comment]: # (
)
[comment]: # (
)
Made paths absolute so scripts can be run from any directory
=> [Tools] Generic includes are not generic enough

php/libraries/NDB_Reliability.class.inc
Replacing Quickform to LorisForm in reliability
=> Replacing Quickform to LorisForm in Reliablity

tools/data_dictionary_builder.php
This is no longer necessary.
Names should be more intuitive now instead of like 'hee' or 'hwb'.
=> [data_dictionary_builder.php] Removing old abbreviations for the old Data Query GUI in data_dictionary_builder.php

modules/examiner/php/NDB_Menu_Filter_Form_examiner.class.inc, modules/examiner/test/ExaminerTest.php
=> [Examiner] Redmine-11798 Clean up Examiner list

htdocs/api/v0.0.2/projects/Project.php, php/libraries/NDB_Factory.class.inc, php/libraries/Project.class.inc
=> Project class

modules/data_integrity_flag/php/NDB_Form_data_integrity_flag.class.inc
=> [data_integrity_flag] Data Integrity Flag Save Button Broken -- [Redmine-11314]

tools/delete_timepoint.php
[comment]: # (
)
[comment]: # (
)
[comment]: # (
)
This is an edited version of Stella's Delete timepoint script
https://github.com/aces/Loris/pull/2478 …
=> [tools] Improved Delete Timepoint

htdocs/survey.php
See Redmine 11961
The template expects a `study_title` variable which wasn't being populated.
=> [Survey] Add DB call for missing template <title> variable

modules/user_accounts/php/NDB_Menu_Filter_user_accounts.class.inc, modules/user_accounts/test/user_accountsTest.php, test/run-php-linter.sh
=> Run PHPCS On modules/user_accounts

php/libraries/NDB_BVL_Battery.class.inc
=> [Core] Cleaning up SQL syntax in getBatteryVerbose in Battery class

modules/final_radiological_review/js/columnFormatter.js, modules/final_radiological_review/jsx/columnFormatter.js, modules/final_radiological_review/php/NDB_Menu_Filter_final_radiological_review.class.inc, modules/final_radiological_review/templates/menu_final_radiological_review.tpl
Adding review done and finalized filter,
Fixing review done and finalized column.
Before:
After:
=> [Final_Radiological_Review] Fix review and finalized - redmine 11991

README.md
Updating Heroku button as well as other links for 17.1
=> [Core] Updating README for 17.1

modules/timepoint_list/php/NDB_Menu_timepoint_list.class.inc, modules/timepoint_list/php/TimePoint_List_ControlPanel.class.inc, test/run-php-linter.sh
Only changing the format and adding some comments.
It is ready to merge.
=> [Timepoint_List] Run Phpcs

htdocs/js/workers/savecsv.js
fix bug when downloading csv with numeric values
=> Download csv bug fix

tools/CouchDB_Import_Demographics.php
=> fix dqt data dictionary for projects in demographics

tools/CouchDB_Import_Demographics.php
fix bug with project filtering in dqt
=> [DQT] Project filter

php/libraries/LorisForm.class.inc
In attempt to get rid of invalid output, forgot to allow nulls 😊  (Redmine 12072)
=> [Core] Allow null dates

modules/server_processes_manager/php/NDB_Menu_Filter_server_processes_manager.class.inc, modules/server_processes_manager/php/Process.class.inc, modules/server_processes_manager/php/ServerProcessLauncher.class.inc, modules/server_processes_manager/php/ServerProcessesMonitor.class.inc, test/run-php-linter.sh
Only fixing format.
It is safe to merge it.
=> PHPCS  in [server_processes_manager]

modules/statistics/test/Statistics_Test.php
=> [statistics] Automation Test

modules/candidate_parameters/ajax/formHandler.php, modules/candidate_parameters/ajax/getData.php
Module unable to handle case when a single consent is used. toArray problem
=> [candidate_parameters] Single Consent bug

htdocs/js/loris.js, modules/imaging_uploader/test/imaging_uploaderTest.php, test/phpunit.xml
=> [Imaging uploader] Test

htdocs/feedback_mri_popup.php
return false if the candidate isnt initialized
=> Mri Feedback 

modules/new_profile/php/NDB_Form_new_profile.class.inc, modules/new_profile/test/new_profileTest.php, test/run-php-linter.sh
It runs PHPCS in [new_profile] module. It fixed the format.
=> [New_profile] PHPCS

modules/instrument_builder/php/NDB_Form_instrument_builder.class.inc, modules/instrument_builder/test/instrument_builderTest.php, test/run-php-linter.sh
It runs PHPCS in [instrument_builder] module. It fixed the format.
=> [Instrument_builder] PHPCS

modules/instrument_manager/php/NDB_Menu_Filter_instrument_manager.class.inc, modules/instrument_manager/test/instrument_managerTest.php, test/run-php-linter.sh
It runs PHPCS in [instrument_manager] module. It fixed the format.
=> [Instrument_manager] PHPCS

.eslintrc.json
=> [Core] Add ReactDOM to ESLint

SQL/Archive/17.1/2016-11-21-CreateUserSitesRelTable.sql, htdocs/main.php, modules/dashboard/php/NDB_Form_dashboard.class.inc, modules/dashboard/templates/form_dashboard.tpl, modules/document_repository/php/NDB_Menu_Filter_document_repository.class.inc, modules/imaging_browser/test/imaging_browserTest.php, modules/issue_tracker/ajax/EditIssue.php, modules/issue_tracker/php/NDB_Menu_Filter_Form_my_issue_tracker.class.inc, modules/issue_tracker/php/NDB_Menu_Filter_Form_resolved_issue_tracker.class.inc, modules/media/php/NDB_Menu_Filter_media.class.inc, modules/training/ajax/markQuiz.php, modules/training/php/NDB_Form_training.class.inc, modules/user_accounts/php/NDB_Form_user_accounts.class.inc, modules/user_accounts/php/NDB_Menu_Filter_user_accounts.class.inc, php/libraries/NDB_BVL_Feedback.class.inc, php/libraries/User.class.inc, smarty/templates/main.tpl
sequel to: https://github.com/aces/Loris/pull/2468 
Changes mainly include grouping user sites in one row in the user_accounts, having the user Site Affiliations count displayed while hovering over shows the sites, and a few bug fixes related to user multisite changes.
=> [Core] Additional changes for the user @ multiple sites

modules/data_team_helper/php/NDB_Form_data_team_helper.class.inc, modules/data_team_helper/test/data_team_helperTest.php, test/run-php-linter.sh
It runs PHPCS in [data team helper] module. It fixed the format.
=> [Data team helper] PHPCS

tools/lorisform_parser.php
Does the same thing as #2670.
Hopefully passes Travis this time?
=> [Tools] lorisform_parser.php, better error checking Attempt #2

modules/user_accounts/php/NDB_Form_user_accounts.class.inc
Fix User Accounts Page loads same page upon creating user by redirecting the form to users account page via identifier
=> [User Accounts] Redirect form

modules/final_radiological_review/php/NDB_Form_final_radiological_review.class.inc, modules/final_radiological_review/php/NDB_Menu_Filter_final_radiological_review.class.inc
Check before querying non-existent table.
Can someone test this.
=> [Final Radiological Reivew] Error handling of 'radiology_review' instrument

modules/media/ajax/FileDownload.php
Fixes bug discovered by @johnsaigle 
Fore details, see https://github.com/aces/Loris/pull/2742 and `Redmine #12220`
=> [Media] Download Fix

LORIS_react.README.md
=> [Docs] Updated React Readme

php/libraries/User.class.inc
Just added a simple `getId()` function to class `User`. Surely, it can be useful?
=> [Core] Added function User::getId()

modules/new_profile/php/NDB_Form_new_profile.class.inc
Fix the format of "modules/new_profile/php/NDB_Form_new_profile.class.inc".
It caused the Travis_CI failure.
=> [New_profile] PHPCS Fix

modules/final_radiological_review/php/NDB_Form_final_radiological_review.class.inc, modules/final_radiological_review/php/NDB_Menu_Filter_final_radiological_review.class.inc, modules/final_radiological_review/test/final_radiological_reviewTest.php, test/run-php-linter.sh
This pull request fixed the format of [Final_Radiological_Review]  module.
Run "PHPCS" in this folder.
=> [Final_Radiological_Review] PHPCS

.editorconfig
- Suggestion to add an `.editorconfig` to loris root in order to maintain consistent code style across different developers
- The idea is to avoid changes in whitespace in the future PRs
- Used and recommended by [a lot](https://github.com/editorconfig/editorconfig/wiki/Projects-Using-EditorConfig) of people
>Note: the plugins seems to be smart enough to not affect existing code. (i.e when making changes to a file, it is shown in proper format + new changes are made in proper format, but old code is not converted, avoiding insane changes in PRs)
- [More info](http://editorconfig.org/) 
- [Plugins for text editors and IDEs](http://editorconfig.org/#download)
=> [Core] Code style file

.travis.yml, modules/mri_violations/php/NDB_Menu_Filter_Form_mri_violations.class.inc, modules/mri_violations/test/mri_violationsTest.php
Added Loris testing environment PHP 7.1 to Travis_CI.
Fixed a bug in PHP 7.1.
Previously, a warning would be emitted for invoking user-defined functions with too few arguments. Now, this warning has been promoted to an Error exception.
=> [Travis_CI] add php 7.1 into Travis_CI

htdocs/feedback_mri_popup.php, modules/document_repository/ajax/GetFile.php, modules/final_radiological_review/php/NDB_Form_final_radiological_review.class.inc, modules/final_radiological_review/php/NDB_Menu_Filter_final_radiological_review.class.inc, modules/media/ajax/FileDownload.php, modules/user_accounts/php/NDB_Form_user_accounts.class.inc, tools/generate_tables_sql.php, tools/generate_tables_sql_and_testNames.php
=> Merge 17.0-dev into 17.1-dev

modules/candidate_list/test/candidate_listTest.php
Adding test permissions function.
=> [candidate_list] automation test

SQL/0000-00-00-schema.sql
Add apostrophe into fields of subproject table.
Add apostrophe into fields of files_qcstatus table.
=> [SQL] clean up formatting 

modules/imaging_browser/php/NDB_Form_imaging_browser.class.inc
In reference to 12514,
I speak for everyone when I say that patients should have the right to refuse getting vaxxed.
The needles are sharp and cause autism.
This pull request causes very little change to the system.
But all great things begin with a little change.
=> [Imaging Browser] Doctors Hate Him!

htdocs/api/v0.0.2/candidates/Visit.php
Creating a new visit wasn't working
=> [API] fix error in adding new visit via api

SQL/0000-00-00-schema.sql
Base on this PR https://github.com/aces/Loris/pull/2503/files.
We should add column 'phone'  into 0000-00-schema.
=> [SQL] add column 'phone'  into 00-schema

modules/mri_violations/test/mri_violationsTest.php
These tests failed on MYSQL 5.7. So, base on the 17.1's SQL schema, changing test data.
Adding function to test breadcrumb.
=> [mri_violations] update testing data for 17.1

modules/imaging_browser/php/Imaging_Session_ControlPanel.class.inc, php/libraries/Candidate.class.inc
Phantoms did not have their Tarchive information linkable. This pull request fixes this.
=> Imaging Browser: Display tarchiveID information for phantoms as well: Redmine 12650

modules/final_radiological_review/php/NDB_Form_final_radiological_review.class.inc, modules/final_radiological_review/php/NDB_Menu_Filter_final_radiological_review.class.inc
This pull request adds a deprecation message to the Final radiological review module which should be removed from loris in the 18.0 release
https://redmine.cbrain.mcgill.ca/issues/12581
=> [FRR] Deprecation messages added

modules/user_accounts/php/NDB_Form_user_accounts.class.inc, modules/user_accounts/templates/form_edit_user.tpl, modules/user_accounts/test/user_accountsTest.php
https://redmine.cbrain.mcgill.ca/issues/12673
=> [User Accounts] Enforce site selection

modules/timepoint_list/php/TimePoint_List_ControlPanel.class.inc, php/libraries/User.class.inc
Had to close #2903, so this PR just has the hasCenter() and hasCenterPermission() functions added to `User.class.inc` along with an example of it being used in `TimePoint_List_ControlPanel.class.inc`.
=> [libraries] added hasCenterPermission() and example of using hasCenterPermission() 

php/libraries/ConflictDetector.class.inc
Less PHP Notices especially when running the recreate_conflicts script.
=> [Core] Removing reference assignments Conflict Detector class

htdocs/bootstrap/css/custom-css.css, htdocs/js/jquery.dynamictable.js
=> Table header freeze

modules/create_timepoint/test/create_timepointTest.php
This pull request removes markTestSkipped.
=> [Create timepoint] remove markTestSkipped

modules/instrument_list/templates/instrument_list_controlpanel.tpl
=> [Instrument List] Replaced the cross icon with (No actions)

SQL/Archive/17.1/2017-02-20-SchemaFixSuperfluousCharacterSetIssuesCategories.sql
The initial patch to create the issues_categories table used latin1 charset.
=> [Issue Tracker] Updating patch for Issue Tracker issues_categories table

modules/create_timepoint/test/create_timepointTest.php, modules/user_accounts/test/user_accountsTest.php, test/phpunit.xml
This pull request adds selecting at least one site for editing a user profile.
=> [Travis_CI] fix block

modules/candidate_list/test/candidate_listTest.php
This pull request removes markTestSkipped in the automation test.
Adding more test cases to test breadcrumb, table headers and PSCID link.
=> [candidate_list] remove markTestSkipped

php/libraries/Notify.class.inc
This pull request changes time() to date() in Notify.class.inc.
In **notification_spool** table, TimeSpooled column is datetime type.
=> [Core] Notify.class.inc  change time() to date()

modules/dicom_archive/php/dicom_archive.class.inc
quick fix to load all data when other modules add filters
=> [Dicom_archive] Fix issue with filters

modules/datadict/test/datadictTest.php
This pull request removing skipTest and adding more test cases.
=> [Datadict] remove skipTest and add more test cases

modules/statistics/php/NDB_Form_statistics.class.inc
added `htmlspecialchars()` around `$_REQUEST` assignments
replaced `isset($var) && $var != ''` with `$var ?? ''`
=> [Statistics] Security fixes

.travis.yml
update Travis CI --- add "dist: precise" into .travis.yml
=> update Travis CI --- add "dist: precise" into .travis.yml

modules/media/test/TestPlan.md
This pull request update the testplan to reflect the while-you-type filtering
=> [Media] Testplan update

docs/instruments/NDB_BVL_Instrument_mri_parameter_form.class.inc
https://redmine.cbrain.mcgill.ca/issues/12648
adding Discussion Required since i think the entire file upload functionality in here is broken or outdated
=> [Sample MRI Parameter Form] Remove line disabling DB tracking

modules/conflict_resolver/php/NDB_Menu_Filter_Form_conflict_resolver.class.inc, modules/conflict_resolver/php/NDB_Menu_Filter_resolved_conflicts.class.inc
Currently limits max display results to rowsPerPage as per config. This should rectify the issue as we're using React for rendering now...
=> [Conflict Resolver] Fix results display bug

modules/user_accounts/php/NDB_Form_user_accounts.class.inc
This pull request adding an error message when a user doesn't set pending approval Yes or No, if Examiner Status is Radiologist.
=> [user account] can't saving pending_approval as null

modules/instrument_manager/php/NDB_Menu_Filter_instrument_manager.class.inc
When installing an instrument from the instrument manager, the linst file was put in instruments, the SQL script was created in tables_sql, but the SQL script needed to be run manually. 
This pull request allows the SQL script to be run automatically.
=> Instrument Manager Sourcing SQL (#12748 on Redmine)

modules/candidate_list/php/NDB_Menu_Filter_candidate_list.class.inc, modules/conflict_resolver/php/NDB_Menu_Filter_Form_conflict_resolver.class.inc, modules/conflict_resolver/php/NDB_Menu_Filter_resolved_conflicts.class.inc, modules/examiner/php/NDB_Menu_Filter_Form_examiner.class.inc, modules/genomic_browser/php/NDB_Menu_Filter_cnv_browser.class.inc, modules/genomic_browser/php/NDB_Menu_Filter_cpg_browser.class.inc, modules/genomic_browser/php/NDB_Menu_Filter_genomic_browser.class.inc, modules/genomic_browser/php/NDB_Menu_Filter_snp_browser.class.inc, modules/issue_tracker/ajax/EditIssue.php, modules/issue_tracker/php/NDB_Menu_Filter_Form_issue_tracker.class.inc, modules/issue_tracker/php/NDB_Menu_Filter_Form_my_issue_tracker.class.inc, modules/issue_tracker/php/NDB_Menu_Filter_Form_resolved_issue_tracker.class.inc, modules/mri_violations/php/NDB_Menu_Filter_Form_mri_violations.class.inc, modules/mri_violations/php/NDB_Menu_Filter_Form_resolved_violations.class.inc, modules/reliability/php/NDB_Menu_Filter_reliability.class.inc, modules/user_accounts/php/NDB_Menu_Filter_user_accounts.class.inc
This line below will fail (500 error) in some modules that check is the user is in a study site; unless $site is first initialized to be of the array() type.
$sites = array('' => 'All User Sites') + $sites;
=> Across many modules; Initialize sites array for the All User Sites option: Redmine 12944

htdocs/AjaxHelper.php, htdocs/GetCSS.php, htdocs/GetJS.php, htdocs/GetStatic.php, htdocs/api/v0.0.2/Candidates.php, htdocs/mri/jiv/get_file.php, modules/data_release/ajax/GetFile.php, modules/training/ajax/getTrainingDoc.php, php/libraries/Candidate.class.inc, php/libraries/LorisForm.class.inc, php/libraries/Utility.class.inc
=> [Branch Update] Merge latest changes in 17.0-dev into 17.1-dev

modules/genomic_browser/test/TestPlan.md
formatting & grammar error updates + updates to reflect new changes to the Genomic Browser
=> [Genomic Browser] TestPlan update

modules/data_team_helper/php/NDB_Form_data_team_helper.class.inc, modules/issue_tracker/ajax/EditIssue.php, modules/timepoint_list/php/NDB_Menu_timepoint_list.class.inc, php/libraries/User.class.inc
A couple of places where I forgot to incorporate the `$user->getData('CenterIDs')` changes
=> Data Team Helper, Timepoint list, and issue tracker: More user multisites forgotten fixes: Redmine 12885

modules/candidate_parameters/ajax/getData.php
This pull request corresponds to https://redmine.cbrain.mcgill.ca/issues/12943
=> [candidate_parameters] Fixes participant status sub options bug 

modules/document_repository/ajax/documentEditUpload.php, modules/document_repository/templates/menu_document_repository.tpl
This pull request fixed the bug which document_repository can't upload a file and add a category.
=> [document_repository] can't upload a file and add a category__ fix null value

modules/issue_tracker/ajax/EditIssue.php
fixing issue tracker function less arguments error in PHP 7.1.
=> [issue tracker] function less arguments error in php 7.1.

modules/genomic_browser/php/NDB_Menu_Filter_genomic_browser.class.inc
Adding missing file to use the script so the filter panel hide and show onClick
=> [Genomics] adding script to included scripts

php/libraries/Project.class.inc, php/libraries/ProjectDefault.class.inc
This pull request introduce the ProjectDefault class to simulate a project for studies that doesn't use projects. It extends the Project class providing default values and behaviours.
=> [API] Default project class

modules/dashboard/php/NDB_Form_dashboard.class.inc, modules/dashboard/templates/form_dashboard.tpl, modules/dashboard/test/DashboardTest.php
Cecile says this is more inline with the Imaging Browser
=> [Dashboard] Fixing new pending sessions scans

modules/conflict_resolver/php/NDB_Menu_Filter_Form_conflict_resolver.class.inc, tools/fix_timepoint_date_problems.php
Bring the script to PHP 7 syntax.
=> [tools] php7 fix for fix_timepoint_date_problems.php

htdocs/api/v0.0.2/candidates/InstrumentData.php
This pull request fix a bug with the parsing of the provided inputs. It uses json_decode instead of parse_str.
=> [API] fix instrument_data PUT

modules/imaging_browser/test/imaging_browser_test_plan.md
Update test plan to include some features added in the 17.1 (18.0) release
=> Imaging Browser: Update Test Plan

modules/brainbrowser/test/brainbrowser_test_plan.md
A few small features added to the test plan.
=> Brainbrowser: Updated test plan

php/libraries/NDB_Caller.class.inc
This pull request does what the title says it does and only what the title says it does.
=> [Core] update deprecation message for more information

SQL/Archive/17.1/2017-03-25-notifications.sql, htdocs/api/v0.0.2/candidates/Visit.php, modules/create_timepoint/php/create_timepoint.class.inc, php/libraries/TimePoint.class.inc
This pull request use the valide method of create_timepoint class to validate inputs befor timepoint creation. It calls the _valide() method of the create_timepoint module class.
=> [API] Now validate using create_timepoint->validate 

webpack.config.js
The javascript wasn't removed from webpack as it should have been.
=> Remove straggling reference to final radiological review

modules/user_accounts/php/NDB_Form_user_accounts.class.inc
https://redmine.cbrain.mcgill.ca/issues/12972
Changing null value to 0.
=> [User account] Can't create user if Radiologist field is not set

modules/dashboard/php/NDB_Form_dashboard.class.inc
https://redmine.cbrain.mcgill.ca/issues/13150
=> [Dashboard] Fix Sites display under "My Tasks"

tools/DB_date_zeros_removal.php
This pull request improves the php script to avoid updating data where it should not be updated.
=> [script] check for auto update fields

modules/imaging_uploader/test/TestPlan.md
Major updates on the test plan.
Redmine ticket referenced above in the pull request title has the details of which main pull requests introduced the new features that are now documented in this updated test plan.
=> Imaging Uploader test plan updated with all 17p1 features: Redmine 13100

SQL/Archive/17.1/clean-up/Clean_up_patch.sql, tools/DB_date_zeros_removal.php
This pull request makes small changes that can streamline and facilitate the release procedure for projects.
This PR comes with a tested release procedure
=> [Core] Pre-Release minor modifications

modules/user_accounts/php/NDB_Form_user_accounts.class.inc
This pull request fixes the bug where the examiner gets added automatically even if checkboxes are empty
=> [user_accounts] Examiner insert bug

modules/user_accounts/test/TestPlan
This pull request fixes an error in the testPlan of the user_acounts module
=> [user_accounts] testplan update

php/libraries/NDB_Reliability.class.inc
This pull request removing centerID from examiner.
=> [Reliability] remove centerID from examiner

docs/instruments/NDB_BVL_Instrument_TEMPLATE.class.inc, docs/instruments/NDB_BVL_Instrument_UPLOADER_TEMPLATE.class.inc, docs/instruments/NDB_BVL_Instrument_mri_parameter_form.class.inc, docs/instruments/NDB_BVL_Instrument_radiology_review.class.inc
Fixing PHP warnings generated by https://github.com/aces/Loris/pull/2812.
Developers should fix their code accordingly.
=> [Core] Fixing Instrument setup function call definitions

modules/configuration/tools/import_projects.php, php/libraries/NDB_BVL_Instrument.class.inc
This pull request updates Utility::nullifyEmpty.
=> [Core] update Utility::nullifyEmpty

htdocs/.htaccess
Currently tries to parse/rewrite dataDumps as a Loris Module, but it's not one so adding it as an exception.
=> [Core] Fixing Excel Dumps URL rewrites

htdocs/postdeploy.php
No longer using the old password generation/column
=> [Install] Updating Heroku postdeploy password generation

modules/next_stage/php/module.class.inc, modules/next_stage/php/next_stage.class.inc
This updates the next_stage module to the "modern", non-deprecated module format.
=> Convert next_stage module to proper LORIS module structure

modules/help_editor/php/HelpFile.class.inc
Help Editor is not Final Radiological Review
=> [Help Editor] Correct function comment that was copy pasted from elsewhere

modules/document_repository/ajax/GetFile.php
=> [Doc Repo] Remove superfluous session checks generating PHP Notices

tools/DB_date_zeros_removal.php
This fixes the database zero dates removal script... again !
=> [tools] fixing PHP concatenation

modules/genomic_browser/README.md
Carried over from #3028 because I messed up the branching before.
=> [Genomics] README formatting and phrasing changes 

modules/candidate_list/php/NDB_Menu_Filter_candidate_list.class.inc
this pull request is similar to #3197 but for Issue Tracker.
=> Candidate list: use getStudySites() from the User class for cleanup

modules/brainbrowser/help/brainbrowser.md, modules/brainbrowser/php/brainbrowser.class.inc, modules/brainbrowser/php/module.class.inc
Make brain browser into a real LORIS module.
Added one line of help text as well (as there was none).
=> Modularize brainbrowser

modules/dataquery/php/dataquery.class.inc, modules/dataquery/php/module.class.inc
- Add module class descriptor
- Add namespace
- Remove unnecessary imports
=> [dataquery] Convert dataquery module to LORIS module

modules/configuration/php/configuration.class.inc, modules/configuration/php/module.class.inc, modules/configuration/php/project.class.inc, modules/configuration/php/subproject.class.inc
Separated pages into different classes which are only concerned
with their page, created namespace, and and added module class for config module.
=> [configuration] Convert module to modern module structure

modules/candidate_list/help/candidate_list.md, modules/candidate_list/php/candidate_list.class.inc, modules/candidate_list/php/module.class.inc
This updates the candidate_list module to have a proper namespace and
Module descriptor class.
=> [candidate_list] Convert candidate list module to a "real" LORIS module

modules/datadict/help/datadict.md, modules/datadict/php/datadict.class.inc, modules/datadict/php/module.class.inc
Update the data dictionary module to use the proper LORIS module
structure.
=> [Datadict] Modularize Module

modules/instrument_manager/help/instrument_manager.md, modules/instrument_manager/php/instrument_manager.class.inc, modules/instrument_manager/php/module.class.inc
This pull request make the instrument manager module comply to the new Module framework. It adds namespacing and rely on the Module class to load.
=> [Desing SIG] Modularize instrument manager

modules/candidate_list/php/candidate_list.class.inc
This pull request fixes the conflict in the candidate_list.
=> [candidate_list] fix conflict 

modules/README.md
Add the help directory description in the module readme
=> [Documentation] adding help directory comment

composer.json, composer.lock, docs/LorisPHPMD.xml, php/libraries/Database.class.inc, php/libraries/FeedbackMRI.class.inc, php/libraries/LorisForm.class.inc, php/libraries/NDB_BVL_Battery.class.inc, php/libraries/NDB_BVL_Feedback.class.inc, php/libraries/NDB_BVL_Instrument.class.inc, php/libraries/NDB_BVL_InstrumentStatus.class.inc, php/libraries/NDB_BVL_InstrumentStatus_ControlPanel.class.inc, php/libraries/NDB_Caller.class.inc, php/libraries/NDB_Client.class.inc, php/libraries/NDB_Config.class.inc, php/libraries/NDB_Form.class.inc, php/libraries/NDB_Menu_Filter.class.inc, php/libraries/NDB_Menu_Filter_Form.class.inc, php/libraries/NDB_Notifier.class.inc, php/libraries/NDB_Notifier_Abstract.class.inc, php/libraries/NDB_Reliability.class.inc, php/libraries/Project.class.inc, php/libraries/SinglePointLogin.class.inc, php/libraries/Site.class.inc, php/libraries/TimePoint.class.inc, php/libraries/User.class.inc, php/libraries/UserPermissions.class.inc, php/libraries/Utility.class.inc, test/run-php-linter.sh
This adds the unused code ruleset of PHPMD to Travis, and fixes any errors
that were identified.
=> Remove unused variable declarations and fix problems identified by PHPMD

modules/acknowledgements/help/acknowledgements.md, modules/acknowledgements/php/acknowledgements.class.inc, modules/acknowledgements/php/module.class.inc, php/libraries/Module.class.inc
Added namespace and add Module class to the acknoledgement module.
=> [Acknowledgement] Convert module to module.

modules/data_team_helper/help/data_team_helper.md, modules/data_team_helper/php/data_team_helper.class.inc, modules/data_team_helper/php/module.class.inc
This adds a namespace and Module class to the Data Team Helper module.
function_getDefaults() seems to be unused. So removing that as the part of clean up.
=> Modularize Data Team Helper

README.Mac.md
=> [Installation] Updating Mac README with markdown updates

modules/reliability/help/reliability.md, modules/reliability/php/module.class.inc, modules/reliability/php/reliability.class.inc, modules/statistics/php/stats_reliability.class.inc
namespace
filenames
help content
=> [Reliability] Module now a module

modules/instrument_list/test/instrument_listTest.php
This pull request removes skip test function.
=> [instrument_list] remove skip test function

modules/data_release/help/data_release.md, modules/data_release/php/data_release.class.inc, modules/data_release/php/module.class.inc
Created namespace, and and added module class for new_profile module.
=> [Data_Release] Convert module to modern module structure

modules/help_editor/ajax/help.php, modules/help_editor/help/help_editor.md, modules/help_editor/php/edit_help_content.class.inc, modules/help_editor/php/help_editor.class.inc, modules/help_editor/php/helpfile.class.inc, modules/help_editor/php/module.class.inc
namespace
filenames
help content
=> [Help Editor] Module now a module

modules/document_repository/php/document_repository.class.inc, modules/document_repository/php/module.class.inc
Add namespace to document repository.
=> [Document_Repo] Convert document repository to module

modules/imaging_uploader/php/NDB_Menu_Filter_imaging_uploader.class.inc, modules/server_processes_manager/help/server_processes_manager.md, modules/server_processes_manager/php/abstractserverprocess.class.inc, modules/server_processes_manager/php/defaultdatabaseprovider.class.inc, modules/server_processes_manager/php/defaultprocessmonitor.class.inc, modules/server_processes_manager/php/idatabaseprovider.class.inc, modules/server_processes_manager/php/iprocessmonitor.class.inc, modules/server_processes_manager/php/module.class.inc, modules/server_processes_manager/php/mriuploadserverprocess.class.inc, modules/server_processes_manager/php/process.class.inc, modules/server_processes_manager/php/server_processes_manager.class.inc, modules/server_processes_manager/php/serverprocessesmonitor.class.inc, modules/server_processes_manager/php/serverprocessfactory.class.inc, modules/server_processes_manager/php/serverprocesslauncher.class.inc
Add namespace and change filename + help file
=> [Server Process Manager] Convert to module

modules/media/php/edit.class.inc, modules/media/php/media.class.inc, modules/media/php/module.class.inc
This adds a namespace and Module class to the media module.
Note: I don't really know how this module is supposed to work, so I couldn't test it properly, but the page loads and I think all the classes outside of the namespace are referred to properly.
=> [Media] Convert to modern module structure

modules/imaging_uploader/help/imaging_uploader.md, modules/imaging_uploader/php/file_decompress.class.inc, modules/imaging_uploader/php/imaging_uploader.class.inc, modules/imaging_uploader/php/module.class.inc
This adds a namespace and Module class to the imaging uploader module.
Like 'Media', the function display() had to be removed.
=> Modularize Imaging Uploader

modules/examiner/help/examiner.md, modules/examiner/php/editexaminer.class.inc, modules/examiner/php/examiner.class.inc, modules/examiner/php/module.class.inc
This adds a namespace, Module class and help to the examiner module.
=> Modularize examiner

modules/survey_accounts/php/addsurvey.class.inc, modules/survey_accounts/php/module.class.inc, modules/survey_accounts/php/survey_accounts.class.inc
This converts the survey_accounts to a proper LORIS module. It adds a
namespace and Module class descriptor.
=> [survey_accounts] Convert to "real" LORIS module

modules/candidate_list/php/candidate_list.class.inc, modules/candidate_parameters/php/candidate_parameters.class.inc, modules/new_profile/php/new_profile.class.inc
This fixes the build on the major branch after an incorrectly resolved conflict.
=> Fix the major branch

modules/media/php/media.class.inc
This pull request fix a problem with page not loading from Ajax call. It fix a namespacing issue.
It was introduce in a PR merged in the `minor` branch. It is not a bugfix for the `bugfix` branch.
=> [Media] fix namespacing issue

modules/login/php/passwordreset.class.inc
This pull request fix a namespacing issue whit Email class
=> [Login] Password reset fix

htdocs/main.php, modules/candidate_list/ajax/validateProfileIDs.php, modules/candidate_list/php/candidate_list.class.inc, modules/imaging_browser/ajax/setSortedRows.php, modules/imaging_browser/php/imaging_browser.class.inc, modules/new_profile/php/new_profile.class.inc, php/libraries/NDB_BVL_Feedback.class.inc, php/libraries/User.class.inc
Cleanup the code to use the isInOneStudySite() in the User class that was introduced in #2996 for data team helper. In this series of changes, we check if the user is in at least one study site and/or at the "DCC" (or centerID=1).
In reference to Redmine 13485, and related to redmine 12946;
=> Cleanup multiple modules: if user is in one study site and/or in "DCC": Redmine 13485

modules/server_processes_manager/test/TestPlan, modules/server_processes_manager/test/server_processes_managerTest.php, test/phpunit.xml
This pull request adds new test file for this module.
=> [server_processes_manager] test

modules/mri_violations/help/mri_violations.md, modules/mri_violations/help/resolved_violations.md
This PR updates the Markdown help text for the MRI Violations module.
=> [Help Text] fix mri violations help text (markdown version) 

docs/instruments/test_all_fields.linst, modules/instrument_manager/php/instrument_manager.class.inc, modules/instrument_manager/test/TestPlan.md
This pull request fix a bug when uploading an instrument in the instrument manager.
Argument 2 and 3 of `\NDB_BVL_Instrument::factory` must be strings
Also fix `PHP Notice:  Only variables should be assigned by reference`
See also: RM#13643 & RM#13644
=> [Instrument manager] Bug fix & cleanup

.travis.yml, modules/media/php/NDB_Form_media.class.inc
This pull request follows https://github.com/aces/Loris/pull/3321. Fixed the Travis router issue.
=> Fixing travis on bugfix branch

modules/brainbrowser/php/brainbrowser.class.inc
=> [Brainbrowser] Cleanup

modules/media/php/NDB_Form_media.class.inc
:sos: :rotating_light: :sos: :policeman: :police_car:
=> [Media] Fix SQLi vulnerability

SQL/0000-00-02-Menus.sql, SQL/Release_patches/18.0_To_19.0_upgrade.sql
This pull request adds edit permission for Loris menu.
https://redmine.cbrain.mcgill.ca/issues/11180
=> [datadict] adding edit permission for Loris menu

php/libraries/LorisForm.class.inc
`PHP Notice:  Undefined index`
=> [LorisForm] PHP notice cleanup

modules/datadict/ajax/UpdateDataDict.php, modules/datadict/php/datadict.class.inc
- This pull request fix the filtering on modified/unmodified datadictionnary items.
- Also delete non modified items (back to original description)
- Ran phpcs and deleted dead code
=> [Datadict] bug fix on filtering and modifiing unmodified items

modules/login/README.md
This adds a README for the login module based on the template of the imaging_browser.
=> Added README/specification for login module

modules/document_repository/php/document_repository.class.inc
bug fix - can't show uploaded files.
Rename function name setup to _setupVariables.
https://redmine.cbrain.mcgill.ca/issues/13564
=> [document_repository] bug fix - can't show uploaded files

modules/data_release/README.md
Looks like md formatting was changed between now and when I last wrote the README.
=> [Data Release] Fixing Data Release README formatting

modules/login/php/passwordreset.class.inc, modules/login/php/requestaccount.class.inc, modules/login/templates/form_requestaccount.tpl, php/libraries/NDB_Client.class.inc
This re-adds the code that was lost for the captcha, examiner and user multisite changes.
PRs concerned:
https://github.com/aces/Loris/pull/2582
https://github.com/aces/Loris/pull/2468
https://github.com/aces/Loris/pull/2721
=> [login] restore lost code for password reset and request account

modules/instrument_list/README.md
Add a README for the instrument list module following the imaging browser template.
=> Add README/spec for instrument_list page

modules/dicom_archive/README.md
Add specification for the DICOM archive in the standard format.
=> Add DICOM Archive README/Spec

htdocs/GetCSS.php, htdocs/GetJS.php, smarty/templates/public_layout.tpl
Public modules were not correctly retrieving JS and CSS for instruments relying on JS/React.
Retest any public modules that were previously working, and test a reactified public module.
=> fixed public module bugs

modules/brainbrowser/README.md, modules/imaging_browser/README.md
=> Brainbrowser: Added Spec/Readme

modules/user_accounts/README.md
As the title says, added file `modules/user_accounts/README.md`
=> Added README for the user account module

modules/statistics/README.md
Added spec for statistics module in the form of a README
=> Add README for statistics

modules/data_release/test/data_release_test_plan.md
Adding a test plan for the data release module.
=> Data release module test plan

htdocs/main.php, smarty/templates/500.tpl
This fix the switch statement value accessor. It also add a 500 template file
See also: RM#13803
=> Fix redirector

modules/candidate_list/test/TestPlan.md
This changes false to no since false does not actually exist in config module
=> [candidate_list] Minor test plan change

modules/dataquery/README.md
This updates the DQT to README to follow the same format as
the imaging browser template.
=> Update DQT README to follow standard README/spec format

modules/training/php/training.class.inc
This pull request fixes the loading problem.
https://redmine.cbrain.mcgill.ca/issues/13837
=> [training] fix loading problem

modules/server_processes_manager/README.md
As the tile says, adds file `modules/server_processes_manager/README.md` to the code base.
=> Add README for server processes manager module

modules/help_editor/README.md
Add README/spec for help_editor module.
=> Added README for help_editor module.

modules/instrument_builder/README.md
Add a README for the instrument_builder module in the standard format.
=> Add README/spec for instrument_builder module

tools/cleanup_mri_tables_for_19-0_release.php
This allows this tool to be run from any directory rather then having to navigate to the tools/ directory
=> [tools] added absolute path

modules/examiner/README.md
=> Add README for examiner module

.travis.yml, composer.json, htdocs/api/v0.0.1/APIBase.php, modules/configuration/test/ConfigurationTest.php, modules/dashboard/test/DashboardTest.php, modules/genomic_browser/test/genomic_browserTest.php, php/libraries/Database.class.inc, php/libraries/NDB_BVL_Instrument_LINST.class.inc, test/integrationtests/BatteryLookup_Test.php, test/integrationtests/LorisIntegrationTest.class.inc, test/unittests/CandidateTest.php, test/unittests/Database_Test.php, test/unittests/LorisForms_Test.php, test/unittests/Loris_PHPUnit_Database_TestCase.php, test/unittests/NDB_BVL_Instrument_LINST_ToJSON_Test.php, test/unittests/NDB_BVL_Instrument_ToJSON_Test.php, test/unittests/NDB_Menu_Filter_Test.php, test/unittests/SettingsTest.php, test/unittests/SinglePointLoginTest.php, test/unittests/api/v0.0.1/BaseTestCase.php, test/unittests/api/v0.0.1/Candidates_Test.php
This pull request updates phpunit to 6.5.5.
=> [travis]  update to PHP 7.2 

php/libraries/AnonymousUser.class.inc, php/libraries/User.class.inc
This should allow us to make better use of PHP's type system when dealing with users.
=> Add AnonymousUser class to differentiate logged in from logged out users

.travis.yml, Dockerfile, Dockerfile.MySQL, Dockerfile.test.php7
It appears that whether or not the path is required before the file
for the router or whether it implicitly looks in the htdocs folder
has sporadically changed.. again.
This reverts the change to docker compose and instead adds the
path so that it can find the file.
=> Readd multiversion testing

smarty/templates/directentry.tpl
This add modernizer and polyfill libraries for datepicker to be used by browsers like Safari in surveys
=> [Survey accounts] Fix surveys datepicker

tools/score_instrument.php
- removes requirement that instrument name be all lower case
- moves some query variables into params array
- remove pass by reference causing PHP Notices
=> [tools] score_instrument.php fixes & adjustments

.travis.yml
This pull request fixes travis_ci can't run PHP 7.0 on minor branch.
=> [travis-ci] test php 7.0 and 7.1 on minor branch

jsx/Tabs.js
This creates the JSX element for vertical tabs currently used in the candidate parameters module on CCNA. This might be used in biobanking and possibly instruments
=> [JSX] adding vertical tab support

php/libraries/Database.class.inc
This PR just edits the misleading comments of the pselectCol function
=> [Database] Fix pselectCol doc

modules/dataquery/ajax/queryEqual.php, modules/dataquery/ajax/queryGreaterThanEqual.php, modules/dataquery/ajax/queryLessThanEqual.php
This restores the deleting of some lines during the PHPCSing of the module (see PR https://github.com/aces/Loris/pull/2666/files?w=1)
=> [DQT] Ajax null return bug

modules/statistics/php/module.class.inc, modules/statistics/php/statistics.class.inc, modules/statistics/php/statistics_dd_site.class.inc, modules/statistics/php/statistics_mri_site.class.inc, modules/statistics/php/statistics_site.class.inc, modules/statistics/php/stats_behavioural.class.inc, modules/statistics/php/stats_demographic.class.inc, modules/statistics/php/stats_general.class.inc, modules/statistics/php/stats_mri.class.inc, modules/statistics/php/stats_reliability.class.inc, modules/statistics/templates/form_stats_behavioural.tpl
This PR includes the non essential aesthetic changes from #3379 [Closed]
Multiple new PRs will break down the functional changes from that PR for easier testing.
=> [Statistics] Cleanup

modules/mri_violations/README.md
This pull request adds the specification for the MRI Violations module.
Note: this module is extremely buggy and not completely functional. Will need to be revamped. See ticket: #13773
=> Add MRI Violations README/Spec

php/libraries/Database.class.inc
cherry picked commits from previous PR made to major, the PR belongs on minor and would be usefull to start cleaning up the code
https://github.com/aces/Loris/pull/3428
=> Copy of [Core-Database] added 2 new functions to help avoid code duplication

docs/API/LorisRESTAPI_v0.0.3.md, htdocs/api/v0.0.3-dev/projects/Images.php
This add new fields to project/images API endpoint
- PSCID
- Visit_date
- Site
- QC_status
- Selected
It should at least provide a way to filter data once the result is send to the user.
A further step will be to add filter option server side.
=> [API] Adding new fields to project/images endpoint

modules/acknowledgements/README.md
=> [Acknowledgements] Updating README

modules/help_editor/php/edit_help_content.class.inc
Found these errors while working on https://github.com/aces/Loris/pull/3558:
Removes defining of variable before isset check
=> [Help_editor] Fix undefined index

tools/assign_missing_instruments.php
https://github.com/aces/Loris/issues/3562
=> [Tools] Fixing spelling in comments within assign_missing_instruments.php

docs/API/LorisRESTAPI_v0.0.3.md
This pull request `correct a grammar error`.
=> [DOCS] Update LorisRESTAPI_v0.0.3.md

modules/imaging_browser/css/imaging_browser.css
This pull request fixes the imaging_browser.css. 
https://redmine.cbrain.mcgill.ca/issues/14091
=> [Imaging Browser View Session]: fix CSS re sidebar Save button

modules/media/php/media.class.inc
This builds on the existent language flag in the media uploader to add a serach by language functionality to the browsing tab.
additions: 
- filter dropdown
- table column
=> [Media] added search by language functionality

modules/document_repository/ajax/documentEditUpload.php
=> [Doc Repo] Comments never worked but they do now!

modules/instrument_list/php/instrument_list_controlpanel.class.inc
This pull request fixes the bug that can't save the null value and can't save the data into SQL table in some cases. It also fixes the logic error.
=> [instrument_list] BVL QC panel bug fix- can't save the QC status and QC type properly.  

modules/document_repository/js/document_repository_helper.js, modules/document_repository/php/document_repository.class.inc, modules/document_repository/templates/menu_document_repository.tpl
Redmine: https://redmine.cbrain.mcgill.ca/issues/11251
Apologies in advance if the code is not great - trying to understand how Mustache.js communicates with the other languages was a struggle. Open to all reviews/suggestions! Thanks :)
=> [Doc repo] Remove Delete column if user doesn't have delete permissions

modules/document_repository/README.md
This pull request adds README for document_repository module.
=> Add README for document_repository module

modules/instrument_manager/php/instrument_manager.class.inc
This pull request addresses an issue where the file name of a new uploaded instrument was not sanitized.
See Redmine #14347 for more info.
=> [Instrument Manager] Sanitize filename before using in exec

modules/media/README.md, modules/media/Setup.md, modules/media/help/Setup.md, modules/media/help/media.md
This brings the readme.md for Media up to date to conform to the remainder of LORIS.
In addition, a Setup file was added to the module as a proof of concept for futur changes to the wiki/documentation
=> [Media] removed emojis from README and conformed to new convention

modules/instrument_manager/php/instrument_manager.class.inc
See also: #3612, Redmine 14377
=> [Instrument Manager] Sanitize instrument table name before using in exec

smarty/templates/install.tpl
This pull request modifies a small typo in the installdb script.
=> [InstallDB] Fixing small typo

.travis.yml, modules/data_team_helper/php/data_team_helper.class.inc, modules/server_processes_manager/php/abstractserverprocess.class.inc, php/libraries/Database.class.inc
Remove the conflict markers from .travis.yml so that
Travis runs on the major branch.
=> Fix major branch

php/libraries/NDB_Client.class.inc
Same as #3651 but issued to major.
=> [Client] Remove unused FeedbackButtonBoolean cookie

.phan/config.php, htdocs/api/v0.0.2/candidates/visits/images/Image.php, htdocs/api/v0.0.2/candidates/visits/images/format/Raw.php, htdocs/api/v0.0.2/candidates/visits/images/format/Thumbnail.php, htdocs/api/v0.0.3-dev/candidates/visits/images/Image.php, htdocs/api/v0.0.3-dev/candidates/visits/images/format/Raw.php, htdocs/api/v0.0.3-dev/candidates/visits/images/format/Thumbnail.php, modules/data_team_helper/php/data_team_helper.class.inc, modules/document_repository/php/document_repository.class.inc, modules/server_processes_manager/php/serverprocesslauncher.class.inc, modules/statistics/php/statistics_mri_site.class.inc, php/libraries/Database.class.inc, php/libraries/LorisForm.class.inc, php/libraries/NDB_BVL_Feedback.class.inc, php/libraries/NDB_BVL_Instrument.class.inc, php/libraries/NDB_BVL_Instrument_LINST.class.inc, php/libraries/NDB_Form.class.inc, php/libraries/NDB_Menu.class.inc, php/libraries/NDB_Menu_Filter.class.inc, php/libraries/NDB_Menu_Filter_Form.class.inc, php/libraries/NDB_Page.class.inc, php/libraries/NDB_Reliability.class.inc, test/test_instrument/NDB_BVL_Instrument_testtest.class.inc, test/unittests/NDB_Menu_Filter_Test.php, test/unittests/api/v0.0.1/Candidates_Test.php, test/unittests/api/v0.0.1/Login_Test.php, test/unittests/api/v0.0.1/candidates/Visit_Test.php
…g number of parameters.
This fixes both the PhanTooFew and PhanTooMany error classes.
=> Phan incorrect param number

modules/login/php/requestaccount.class.inc
Related: https://github.com/aces/Loris/pull/3645, https://github.com/aces/Loris/pull/3556
=> [Request Account] Remove references to obsolete custom CAPTCHA

tools/delete_candidate.php, tools/delete_timepoint.php
Ref.:https://redmine.cbrain.mcgill.ca/issues/12473
to test: 
1. cd <Loris Dir>/tools/
2. php delete_candidate.php delete_candidate 587630 DCC090 tosql (creates SQL file with delete statements - does not delete candidate)
3. check for `DELETE_candidate_587630.sql` in `/project/tables_sql`
4. php delete_candidate.php delete_candidate 587630 DCC090 confirm (calls delete on database - actually deletes candidate)
=> using tosql now generate only 1 file with ordered instruction

modules/configuration/css/configuration.css, modules/configuration/js/project.js, modules/configuration/js/subproject.js, modules/configuration/php/project.class.inc, modules/configuration/templates/form_project.tpl, modules/configuration/templates/form_subproject.tpl
This PR addresses https://redmine.cbrain.mcgill.ca/issues/11343
Added mouseover text (tooltip) to the Project and Subproject sections of the Configuration Module.
=> Added mouseover text to configuration module project and subproject labels

modules/data_release/ajax/FileUpload.php
So that it doesn't silently fail upon improper setup
=> [Data Release] Adding error handling for missing default `user_uploads` directory

php/libraries/Utility.class.inc
This pull request `fixes variable $instruments may not be defined fix `.
=> [php/libraries] Utility.class.inc variable $instruments may not be defined fix 

modules/new_profile/php/new_profile.class.inc
Add missing error messages when EDC is not submitted or does not match the Confirm EDC date
Resolves Redmine: #14711
=> Improve error checking for EDC

.phan/config.php, .travis.yml, README.md, modules/imaging_browser/php/imaging_browser.class.inc, php/libraries/FeedbackMRI.class.inc, php/libraries/NDB_BVL_Instrument.class.inc, php/libraries/NDB_Config.class.inc, php/libraries/NDB_Menu_Filter.class.inc, php/libraries/NDB_Page.class.inc, php/libraries/NDB_Reliability.class.inc, php/libraries/SinglePointLogin.class.inc, php/libraries/TimePoint.class.inc, php/libraries/Utility.class.inc, test/unittests/Loris_PHPUnit_Database_TestCase.php
Phan is failing with redeclared class exceptions on some
PRs that otherwise pass, this is a check for whether that's
just broken on the 20.0-release branch in general.
=> Fix phan on 20.0-release branch

modules/statistics/test/TestPlan.md
Addresses Redmine #14746. Also some other minor changes.
=> [Statistics] (20.0) Update test plan

modules/candidate_parameters/help/candidate_parameters.md, modules/media/help/media.md, modules/new_profile/help/new_profile.md, modules/reliability/help/reliability.md, modules/statistics/help/statistics.md, modules/survey_accounts/help/survey_accounts.md
This pull request fix format.
https://redmine.cbrain.mcgill.ca/issues/14747
=> [Help editor] fix format

modules/help_editor/test/TestPlan.md
Addresses https://redmine.cbrain.mcgill.ca/issues/14750
=> [Help_editor] (20.0) Update test plan

modules/media/test/TestPlan.md
This pull request updates the test plan. If a user has "superuser" permission, the hidden row is still in the table.
https://redmine.cbrain.mcgill.ca/issues/14779
=> [Media] update test plan 

modules/dicom_archive/php/dicom_archive.class.inc, modules/dicom_archive/test/TestPlan
This pull request updates the test plan of the dicom archive module and changes the filter tag Series UI to become Series UID
=> [20.0-testing] Dicom archive: update test plan and change Series UI to SeriesUID

modules/document_repository/test/TestPlan
Modifies the Testplan by updating the permission, fixing typos, updating test for deleting files. 
[Redmine ticket 14637](https://redmine.cbrain.mcgill.ca/issues/14637)
=> [20.0][Document Repository] Testplan modifications

modules/dashboard/php/dashboard.class.inc
Links to instruments were broken and links to visits were missing altogether for some reason
=> [20.0] [Dashboard] BVL Feedback links: fix instrument level links & add visit level links

htdocs/installdb.php, htdocs/test.php, php/installer/Database.class.inc, php/installer/Installer.class.inc
This pull request `fixes 500 Internal Server Error from happening after user submits admin mysql detail`.
The namespace references to the Database.class.inc in the php/installer directory was breaking the installer by some exceptions being thrown. Solution is to try catch the exceptions.
=> [install] Bugfix 500 Internal Server Error 20.0-release

modules/examiner/php/editexaminer.class.inc
This pull request adds breadcrumb link for this module.
https://redmine.cbrain.mcgill.ca/issues/14780
=> [Examiner] add breadcrumb link

modules/statistics/test/TestPlan.md
small PR, addresses https://redmine.cbrain.mcgill.ca/issues/14826
=> [Statistics] Change Gender to Sex in Test Plan

modules/dashboard/test/TestPlan.md
This pull requests amends the Dashboard test plan to accurately represent the current functionality of the 'My Tasks' section of the dashboard.
This addresses the issue raised in [this redmine ticket](https://redmine.cbrain.mcgill.ca/issues/14911).
To test (confirm the reason for the change), follow test plan items 10, 11, and 15.
=> [Dashboard][20.0] Amend testplan

modules/media/test/TestPlan.md
Outdated info:
-> 'Instrument' is not a required field.
-> 'Site' is a required field.
=> [media] Update Test Plan

modules/data_team_helper/php/data_team_helper.class.inc
This pull request fixes Instrument & Site Filters are not holding/displaying the values once it is applied.
Adding a missing variable into PHP file.
https://redmine.cbrain.mcgill.ca/issues/14807
=> [data_team_helper] Instrument & Site Filters are not holding/displaying the values once it is applied.

modules/mri_violations/test/TestPlan.md
This pull request updates the test plan of the MRI violations test plan. Some information in the test plan were either incorrect or misleading so changed it to make it clearer.
=> Updates to the MRI violations test plan for 20.0 release
